FROM therecipe/qt:windows_64_shared_base_5
LABEL maintainer therecipe

RUN cd /usr/lib/mxe && make MXE_TARGETS='x86_64-w64-mingw32.shared' qtactiveqt qtcanvas3d qtmultimedia qtcharts qtconnectivity qtdatavis3d qtgraphicaleffects jasper xz tiff lcms libmng libwebp qtimageformats qtlocation
