FROM therecipe/qt:windows_64_shared_base_6 as base

RUN cd /usr/lib/mxe && make MXE_TARGETS='x86_64-w64-mingw32.shared' EXCLUDE_PKGS='qtwebkit' qt5
RUN rm -rf /usr/lib/mxe/log && rm -rf /usr/lib/mxe/pkg
