// +build !minimal

#pragma once

#ifndef GO_QTDBUS_H
#define GO_QTDBUS_H

#ifdef __cplusplus
extern "C" {
#endif

void* QDBusAbstractAdaptor_NewQDBusAbstractAdaptor(void* obj);
int QDBusAbstractAdaptor_AutoRelaySignals(void* ptr);
void QDBusAbstractAdaptor_SetAutoRelaySignals(void* ptr, int enable);
void QDBusAbstractAdaptor_DestroyQDBusAbstractAdaptor(void* ptr);
void QDBusAbstractAdaptor_TimerEvent(void* ptr, void* event);
void QDBusAbstractAdaptor_TimerEventDefault(void* ptr, void* event);
void QDBusAbstractAdaptor_ChildEvent(void* ptr, void* event);
void QDBusAbstractAdaptor_ChildEventDefault(void* ptr, void* event);
void QDBusAbstractAdaptor_ConnectNotify(void* ptr, void* sign);
void QDBusAbstractAdaptor_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusAbstractAdaptor_CustomEvent(void* ptr, void* event);
void QDBusAbstractAdaptor_CustomEventDefault(void* ptr, void* event);
void QDBusAbstractAdaptor_DeleteLater(void* ptr);
void QDBusAbstractAdaptor_DeleteLaterDefault(void* ptr);
void QDBusAbstractAdaptor_DisconnectNotify(void* ptr, void* sign);
void QDBusAbstractAdaptor_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusAbstractAdaptor_Event(void* ptr, void* e);
int QDBusAbstractAdaptor_EventDefault(void* ptr, void* e);
int QDBusAbstractAdaptor_EventFilter(void* ptr, void* watched, void* event);
int QDBusAbstractAdaptor_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusAbstractAdaptor_MetaObject(void* ptr);
void* QDBusAbstractAdaptor_MetaObjectDefault(void* ptr);
void* QDBusAbstractInterface_AsyncCall(void* ptr, char* method, void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7, void* arg8);
void* QDBusAbstractInterface_Call(void* ptr, char* method, void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7, void* arg8);
void* QDBusAbstractInterface_Connection(void* ptr);
char* QDBusAbstractInterface_Interface(void* ptr);
int QDBusAbstractInterface_IsValid(void* ptr);
void* QDBusAbstractInterface_LastError(void* ptr);
char* QDBusAbstractInterface_Path(void* ptr);
char* QDBusAbstractInterface_Service(void* ptr);
void QDBusAbstractInterface_SetTimeout(void* ptr, int timeout);
int QDBusAbstractInterface_Timeout(void* ptr);
void QDBusAbstractInterface_DestroyQDBusAbstractInterface(void* ptr);
void QDBusAbstractInterface_TimerEvent(void* ptr, void* event);
void QDBusAbstractInterface_TimerEventDefault(void* ptr, void* event);
void QDBusAbstractInterface_ChildEvent(void* ptr, void* event);
void QDBusAbstractInterface_ChildEventDefault(void* ptr, void* event);
void QDBusAbstractInterface_ConnectNotify(void* ptr, void* sign);
void QDBusAbstractInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusAbstractInterface_CustomEvent(void* ptr, void* event);
void QDBusAbstractInterface_CustomEventDefault(void* ptr, void* event);
void QDBusAbstractInterface_DeleteLater(void* ptr);
void QDBusAbstractInterface_DeleteLaterDefault(void* ptr);
void QDBusAbstractInterface_DisconnectNotify(void* ptr, void* sign);
void QDBusAbstractInterface_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusAbstractInterface_Event(void* ptr, void* e);
int QDBusAbstractInterface_EventDefault(void* ptr, void* e);
int QDBusAbstractInterface_EventFilter(void* ptr, void* watched, void* event);
int QDBusAbstractInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusAbstractInterface_MetaObject(void* ptr);
void* QDBusAbstractInterface_MetaObjectDefault(void* ptr);
void* QDBusArgument_NewQDBusArgument();
void* QDBusArgument_NewQDBusArgument3(void* other);
void* QDBusArgument_NewQDBusArgument2(void* other);
void* QDBusArgument_AsVariant(void* ptr);
int QDBusArgument_AtEnd(void* ptr);
void QDBusArgument_BeginArray(void* ptr, int id);
void QDBusArgument_BeginArray2(void* ptr);
void QDBusArgument_BeginMap(void* ptr, int kid, int vid);
void QDBusArgument_BeginMap2(void* ptr);
void QDBusArgument_BeginMapEntry(void* ptr);
void QDBusArgument_BeginMapEntry2(void* ptr);
void QDBusArgument_BeginStructure(void* ptr);
void QDBusArgument_BeginStructure2(void* ptr);
int QDBusArgument_CurrentType(void* ptr);
void QDBusArgument_EndArray(void* ptr);
void QDBusArgument_EndArray2(void* ptr);
void QDBusArgument_EndMap(void* ptr);
void QDBusArgument_EndMap2(void* ptr);
void QDBusArgument_EndMapEntry(void* ptr);
void QDBusArgument_EndMapEntry2(void* ptr);
void QDBusArgument_EndStructure(void* ptr);
void QDBusArgument_EndStructure2(void* ptr);
void QDBusArgument_Swap(void* ptr, void* other);
void QDBusArgument_DestroyQDBusArgument(void* ptr);
void* QDBusConnection_QDBusConnection_SessionBus();
void* QDBusConnection_QDBusConnection_SystemBus();
void* QDBusConnection_NewQDBusConnection3(void* other);
void* QDBusConnection_NewQDBusConnection2(void* other);
void* QDBusConnection_NewQDBusConnection(char* name);
char* QDBusConnection_BaseService(void* ptr);
void* QDBusConnection_AsyncCall(void* ptr, void* message, int timeout);
int QDBusConnection_CallWithCallback(void* ptr, void* message, void* receiver, char* returnMethod, char* errorMethod, int timeout);
int QDBusConnection_Connect(void* ptr, char* service, char* path, char* interfa, char* name, void* receiver, char* slot);
int QDBusConnection_Connect2(void* ptr, char* service, char* path, char* interfa, char* name, char* signature, void* receiver, char* slot);
int QDBusConnection_Connect3(void* ptr, char* service, char* path, char* interfa, char* name, char* argumentMatch, char* signature, void* receiver, char* slot);
void* QDBusConnection_QDBusConnection_ConnectToBus(int ty, char* name);
void* QDBusConnection_QDBusConnection_ConnectToBus2(char* address, char* name);
void* QDBusConnection_QDBusConnection_ConnectToPeer(char* address, char* name);
int QDBusConnection_ConnectionCapabilities(void* ptr);
int QDBusConnection_Disconnect(void* ptr, char* service, char* path, char* interfa, char* name, void* receiver, char* slot);
int QDBusConnection_Disconnect2(void* ptr, char* service, char* path, char* interfa, char* name, char* signature, void* receiver, char* slot);
int QDBusConnection_Disconnect3(void* ptr, char* service, char* path, char* interfa, char* name, char* argumentMatch, char* signature, void* receiver, char* slot);
void QDBusConnection_QDBusConnection_DisconnectFromBus(char* name);
void QDBusConnection_QDBusConnection_DisconnectFromPeer(char* name);
void* QDBusConnection_Interface(void* ptr);
int QDBusConnection_IsConnected(void* ptr);
void* QDBusConnection_LastError(void* ptr);
char* QDBusConnection_QDBusConnection_LocalMachineId();
char* QDBusConnection_Name(void* ptr);
void* QDBusConnection_ObjectRegisteredAt(void* ptr, char* path);
int QDBusConnection_RegisterObject(void* ptr, char* path, void* object, int options);
int QDBusConnection_RegisterObject2(void* ptr, char* path, char* interfa, void* object, int options);
int QDBusConnection_RegisterService(void* ptr, char* serviceName);
int QDBusConnection_Send(void* ptr, void* message);
void QDBusConnection_Swap(void* ptr, void* other);
void QDBusConnection_UnregisterObject(void* ptr, char* path, int mode);
int QDBusConnection_UnregisterService(void* ptr, char* serviceName);
void QDBusConnection_DestroyQDBusConnection(void* ptr);
void QDBusConnectionInterface_ConnectCallWithCallbackFailed(void* ptr);
void QDBusConnectionInterface_DisconnectCallWithCallbackFailed(void* ptr);
void QDBusConnectionInterface_CallWithCallbackFailed(void* ptr, void* error, void* call);
void QDBusConnectionInterface_ConnectServiceRegistered(void* ptr);
void QDBusConnectionInterface_DisconnectServiceRegistered(void* ptr);
void QDBusConnectionInterface_ServiceRegistered(void* ptr, char* serviceName);
void QDBusConnectionInterface_ConnectServiceUnregistered(void* ptr);
void QDBusConnectionInterface_DisconnectServiceUnregistered(void* ptr);
void QDBusConnectionInterface_ServiceUnregistered(void* ptr, char* serviceName);
void QDBusConnectionInterface_TimerEvent(void* ptr, void* event);
void QDBusConnectionInterface_TimerEventDefault(void* ptr, void* event);
void QDBusConnectionInterface_ChildEvent(void* ptr, void* event);
void QDBusConnectionInterface_ChildEventDefault(void* ptr, void* event);
void QDBusConnectionInterface_ConnectNotify(void* ptr, void* sign);
void QDBusConnectionInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusConnectionInterface_CustomEvent(void* ptr, void* event);
void QDBusConnectionInterface_CustomEventDefault(void* ptr, void* event);
void QDBusConnectionInterface_DeleteLater(void* ptr);
void QDBusConnectionInterface_DeleteLaterDefault(void* ptr);
void QDBusConnectionInterface_DisconnectNotify(void* ptr, void* sign);
void QDBusConnectionInterface_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusConnectionInterface_Event(void* ptr, void* e);
int QDBusConnectionInterface_EventDefault(void* ptr, void* e);
int QDBusConnectionInterface_EventFilter(void* ptr, void* watched, void* event);
int QDBusConnectionInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusConnectionInterface_MetaObject(void* ptr);
void* QDBusConnectionInterface_MetaObjectDefault(void* ptr);
void* QDBusContext_NewQDBusContext();
int QDBusContext_CalledFromDBus(void* ptr);
void* QDBusContext_Connection(void* ptr);
int QDBusContext_IsDelayedReply(void* ptr);
void* QDBusContext_Message(void* ptr);
void QDBusContext_SendErrorReply2(void* ptr, int ty, char* msg);
void QDBusContext_SendErrorReply(void* ptr, char* name, char* msg);
void QDBusContext_SetDelayedReply(void* ptr, int enable);
void QDBusContext_DestroyQDBusContext(void* ptr);
void* QDBusError_NewQDBusError(void* other);
char* QDBusError_QDBusError_ErrorString(int error);
int QDBusError_IsValid(void* ptr);
char* QDBusError_Message(void* ptr);
char* QDBusError_Name(void* ptr);
void QDBusError_Swap(void* ptr, void* other);
int QDBusError_Type(void* ptr);
void* QDBusInterface_NewQDBusInterface(char* service, char* path, char* interfa, void* connection, void* parent);
void QDBusInterface_DestroyQDBusInterface(void* ptr);
void QDBusInterface_TimerEvent(void* ptr, void* event);
void QDBusInterface_TimerEventDefault(void* ptr, void* event);
void QDBusInterface_ChildEvent(void* ptr, void* event);
void QDBusInterface_ChildEventDefault(void* ptr, void* event);
void QDBusInterface_ConnectNotify(void* ptr, void* sign);
void QDBusInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusInterface_CustomEvent(void* ptr, void* event);
void QDBusInterface_CustomEventDefault(void* ptr, void* event);
void QDBusInterface_DeleteLater(void* ptr);
void QDBusInterface_DeleteLaterDefault(void* ptr);
void QDBusInterface_DisconnectNotify(void* ptr, void* sign);
void QDBusInterface_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusInterface_Event(void* ptr, void* e);
int QDBusInterface_EventDefault(void* ptr, void* e);
int QDBusInterface_EventFilter(void* ptr, void* watched, void* event);
int QDBusInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusInterface_MetaObject(void* ptr);
void* QDBusInterface_MetaObjectDefault(void* ptr);
void* QDBusMessage_CreateErrorReply3(void* ptr, int ty, char* msg);
void* QDBusMessage_NewQDBusMessage();
void* QDBusMessage_NewQDBusMessage2(void* other);
int QDBusMessage_AutoStartService(void* ptr);
void* QDBusMessage_QDBusMessage_CreateError3(int ty, char* msg);
void* QDBusMessage_QDBusMessage_CreateError2(void* error);
void* QDBusMessage_QDBusMessage_CreateError(char* name, char* msg);
void* QDBusMessage_CreateErrorReply2(void* ptr, void* error);
void* QDBusMessage_CreateErrorReply(void* ptr, char* name, char* msg);
void* QDBusMessage_QDBusMessage_CreateMethodCall(char* service, char* path, char* interfa, char* method);
void* QDBusMessage_CreateReply2(void* ptr, void* argument);
void* QDBusMessage_QDBusMessage_CreateSignal(char* path, char* interfa, char* name);
void* QDBusMessage_QDBusMessage_CreateTargetedSignal(char* service, char* path, char* interfa, char* name);
char* QDBusMessage_ErrorMessage(void* ptr);
char* QDBusMessage_ErrorName(void* ptr);
char* QDBusMessage_Interface(void* ptr);
int QDBusMessage_IsDelayedReply(void* ptr);
int QDBusMessage_IsReplyRequired(void* ptr);
char* QDBusMessage_Member(void* ptr);
char* QDBusMessage_Path(void* ptr);
char* QDBusMessage_Service(void* ptr);
void QDBusMessage_SetAutoStartService(void* ptr, int enable);
void QDBusMessage_SetDelayedReply(void* ptr, int enable);
char* QDBusMessage_Signature(void* ptr);
void QDBusMessage_Swap(void* ptr, void* other);
int QDBusMessage_Type(void* ptr);
void QDBusMessage_DestroyQDBusMessage(void* ptr);
void* QDBusObjectPath_NewQDBusObjectPath();
void* QDBusObjectPath_NewQDBusObjectPath3(void* path);
void* QDBusObjectPath_NewQDBusObjectPath5(char* p);
void* QDBusObjectPath_NewQDBusObjectPath4(char* path);
void* QDBusObjectPath_NewQDBusObjectPath2(char* path);
char* QDBusObjectPath_Path(void* ptr);
void QDBusObjectPath_SetPath(void* ptr, char* path);
void QDBusObjectPath_Swap(void* ptr, void* other);
void* QDBusPendingCall_NewQDBusPendingCall(void* other);
void* QDBusPendingCall_QDBusPendingCall_FromCompletedCall(void* msg);
void* QDBusPendingCall_QDBusPendingCall_FromError(void* error);
void QDBusPendingCall_Swap(void* ptr, void* other);
void QDBusPendingCall_DestroyQDBusPendingCall(void* ptr);
void QDBusPendingCallWatcher_WaitForFinished(void* ptr);
void* QDBusPendingCallWatcher_NewQDBusPendingCallWatcher(void* call, void* parent);
void QDBusPendingCallWatcher_ConnectFinished(void* ptr);
void QDBusPendingCallWatcher_DisconnectFinished(void* ptr);
void QDBusPendingCallWatcher_Finished(void* ptr, void* self);
int QDBusPendingCallWatcher_IsFinished(void* ptr);
void QDBusPendingCallWatcher_DestroyQDBusPendingCallWatcher(void* ptr);
void QDBusPendingCallWatcher_TimerEvent(void* ptr, void* event);
void QDBusPendingCallWatcher_TimerEventDefault(void* ptr, void* event);
void QDBusPendingCallWatcher_ChildEvent(void* ptr, void* event);
void QDBusPendingCallWatcher_ChildEventDefault(void* ptr, void* event);
void QDBusPendingCallWatcher_ConnectNotify(void* ptr, void* sign);
void QDBusPendingCallWatcher_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusPendingCallWatcher_CustomEvent(void* ptr, void* event);
void QDBusPendingCallWatcher_CustomEventDefault(void* ptr, void* event);
void QDBusPendingCallWatcher_DeleteLater(void* ptr);
void QDBusPendingCallWatcher_DeleteLaterDefault(void* ptr);
void QDBusPendingCallWatcher_DisconnectNotify(void* ptr, void* sign);
void QDBusPendingCallWatcher_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusPendingCallWatcher_Event(void* ptr, void* e);
int QDBusPendingCallWatcher_EventDefault(void* ptr, void* e);
int QDBusPendingCallWatcher_EventFilter(void* ptr, void* watched, void* event);
int QDBusPendingCallWatcher_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusPendingCallWatcher_MetaObject(void* ptr);
void* QDBusPendingCallWatcher_MetaObjectDefault(void* ptr);
void* QDBusServer_NewQDBusServer2(void* parent);
void* QDBusServer_NewQDBusServer(char* address, void* parent);
char* QDBusServer_Address(void* ptr);
int QDBusServer_IsAnonymousAuthenticationAllowed(void* ptr);
int QDBusServer_IsConnected(void* ptr);
void* QDBusServer_LastError(void* ptr);
void QDBusServer_ConnectNewConnection(void* ptr);
void QDBusServer_DisconnectNewConnection(void* ptr);
void QDBusServer_NewConnection(void* ptr, void* connection);
void QDBusServer_SetAnonymousAuthenticationAllowed(void* ptr, int value);
void QDBusServer_DestroyQDBusServer(void* ptr);
void QDBusServer_TimerEvent(void* ptr, void* event);
void QDBusServer_TimerEventDefault(void* ptr, void* event);
void QDBusServer_ChildEvent(void* ptr, void* event);
void QDBusServer_ChildEventDefault(void* ptr, void* event);
void QDBusServer_ConnectNotify(void* ptr, void* sign);
void QDBusServer_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusServer_CustomEvent(void* ptr, void* event);
void QDBusServer_CustomEventDefault(void* ptr, void* event);
void QDBusServer_DeleteLater(void* ptr);
void QDBusServer_DeleteLaterDefault(void* ptr);
void QDBusServer_DisconnectNotify(void* ptr, void* sign);
void QDBusServer_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusServer_Event(void* ptr, void* e);
int QDBusServer_EventDefault(void* ptr, void* e);
int QDBusServer_EventFilter(void* ptr, void* watched, void* event);
int QDBusServer_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusServer_MetaObject(void* ptr);
void* QDBusServer_MetaObjectDefault(void* ptr);
void QDBusServiceWatcher_SetWatchMode(void* ptr, int mode);
int QDBusServiceWatcher_WatchMode(void* ptr);
void* QDBusServiceWatcher_NewQDBusServiceWatcher(void* parent);
void* QDBusServiceWatcher_NewQDBusServiceWatcher2(char* service, void* connection, int watchMode, void* parent);
void QDBusServiceWatcher_AddWatchedService(void* ptr, char* newService);
void* QDBusServiceWatcher_Connection(void* ptr);
int QDBusServiceWatcher_RemoveWatchedService(void* ptr, char* service);
void QDBusServiceWatcher_ConnectServiceOwnerChanged(void* ptr);
void QDBusServiceWatcher_DisconnectServiceOwnerChanged(void* ptr);
void QDBusServiceWatcher_ServiceOwnerChanged(void* ptr, char* serviceName, char* oldOwner, char* newOwner);
void QDBusServiceWatcher_ConnectServiceRegistered(void* ptr);
void QDBusServiceWatcher_DisconnectServiceRegistered(void* ptr);
void QDBusServiceWatcher_ServiceRegistered(void* ptr, char* serviceName);
void QDBusServiceWatcher_ConnectServiceUnregistered(void* ptr);
void QDBusServiceWatcher_DisconnectServiceUnregistered(void* ptr);
void QDBusServiceWatcher_ServiceUnregistered(void* ptr, char* serviceName);
void QDBusServiceWatcher_SetConnection(void* ptr, void* connection);
void QDBusServiceWatcher_SetWatchedServices(void* ptr, char* services);
char* QDBusServiceWatcher_WatchedServices(void* ptr);
void QDBusServiceWatcher_DestroyQDBusServiceWatcher(void* ptr);
void QDBusServiceWatcher_TimerEvent(void* ptr, void* event);
void QDBusServiceWatcher_TimerEventDefault(void* ptr, void* event);
void QDBusServiceWatcher_ChildEvent(void* ptr, void* event);
void QDBusServiceWatcher_ChildEventDefault(void* ptr, void* event);
void QDBusServiceWatcher_ConnectNotify(void* ptr, void* sign);
void QDBusServiceWatcher_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusServiceWatcher_CustomEvent(void* ptr, void* event);
void QDBusServiceWatcher_CustomEventDefault(void* ptr, void* event);
void QDBusServiceWatcher_DeleteLater(void* ptr);
void QDBusServiceWatcher_DeleteLaterDefault(void* ptr);
void QDBusServiceWatcher_DisconnectNotify(void* ptr, void* sign);
void QDBusServiceWatcher_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusServiceWatcher_Event(void* ptr, void* e);
int QDBusServiceWatcher_EventDefault(void* ptr, void* e);
int QDBusServiceWatcher_EventFilter(void* ptr, void* watched, void* event);
int QDBusServiceWatcher_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusServiceWatcher_MetaObject(void* ptr);
void* QDBusServiceWatcher_MetaObjectDefault(void* ptr);
void* QDBusSignature_NewQDBusSignature();
void* QDBusSignature_NewQDBusSignature3(void* signature);
void* QDBusSignature_NewQDBusSignature5(char* sig);
void* QDBusSignature_NewQDBusSignature4(char* signature);
void* QDBusSignature_NewQDBusSignature2(char* signature);
void QDBusSignature_SetSignature(void* ptr, char* signature);
char* QDBusSignature_Signature(void* ptr);
void QDBusSignature_Swap(void* ptr, void* other);
void* QDBusUnixFileDescriptor_NewQDBusUnixFileDescriptor();
void* QDBusUnixFileDescriptor_NewQDBusUnixFileDescriptor3(void* other);
void* QDBusUnixFileDescriptor_NewQDBusUnixFileDescriptor2(int fileDescriptor);
int QDBusUnixFileDescriptor_FileDescriptor(void* ptr);
int QDBusUnixFileDescriptor_QDBusUnixFileDescriptor_IsSupported();
int QDBusUnixFileDescriptor_IsValid(void* ptr);
void QDBusUnixFileDescriptor_SetFileDescriptor(void* ptr, int fileDescriptor);
void QDBusUnixFileDescriptor_Swap(void* ptr, void* other);
void QDBusUnixFileDescriptor_DestroyQDBusUnixFileDescriptor(void* ptr);
void* QDBusVariant_NewQDBusVariant();
void* QDBusVariant_NewQDBusVariant3(void* v);
void* QDBusVariant_NewQDBusVariant2(void* variant);
void QDBusVariant_SetVariant(void* ptr, void* variant);
void QDBusVariant_Swap(void* ptr, void* other);
void* QDBusVariant_Variant(void* ptr);
void* QDBusVirtualObject_NewQDBusVirtualObject(void* parent);
int QDBusVirtualObject_HandleMessage(void* ptr, void* message, void* connection);
char* QDBusVirtualObject_Introspect(void* ptr, char* path);
void QDBusVirtualObject_DestroyQDBusVirtualObject(void* ptr);
void QDBusVirtualObject_TimerEvent(void* ptr, void* event);
void QDBusVirtualObject_TimerEventDefault(void* ptr, void* event);
void QDBusVirtualObject_ChildEvent(void* ptr, void* event);
void QDBusVirtualObject_ChildEventDefault(void* ptr, void* event);
void QDBusVirtualObject_ConnectNotify(void* ptr, void* sign);
void QDBusVirtualObject_ConnectNotifyDefault(void* ptr, void* sign);
void QDBusVirtualObject_CustomEvent(void* ptr, void* event);
void QDBusVirtualObject_CustomEventDefault(void* ptr, void* event);
void QDBusVirtualObject_DeleteLater(void* ptr);
void QDBusVirtualObject_DeleteLaterDefault(void* ptr);
void QDBusVirtualObject_DisconnectNotify(void* ptr, void* sign);
void QDBusVirtualObject_DisconnectNotifyDefault(void* ptr, void* sign);
int QDBusVirtualObject_Event(void* ptr, void* e);
int QDBusVirtualObject_EventDefault(void* ptr, void* e);
int QDBusVirtualObject_EventFilter(void* ptr, void* watched, void* event);
int QDBusVirtualObject_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDBusVirtualObject_MetaObject(void* ptr);
void* QDBusVirtualObject_MetaObjectDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif