#ifdef __cplusplus
extern "C" {
#endif

void* QQuickItem_NewQQuickItem(void* parent);
int QQuickItem_ActiveFocusOnTab(void* ptr);
int QQuickItem_Antialiasing(void* ptr);
double QQuickItem_BaselineOffset(void* ptr);
int QQuickItem_Clip(void* ptr);
int QQuickItem_HasActiveFocus(void* ptr);
int QQuickItem_HasFocus(void* ptr);
double QQuickItem_Height(void* ptr);
double QQuickItem_ImplicitHeight(void* ptr);
int QQuickItem_IsEnabled(void* ptr);
int QQuickItem_IsTextureProvider(void* ptr);
int QQuickItem_IsVisible(void* ptr);
double QQuickItem_Opacity(void* ptr);
void* QQuickItem_ParentItem(void* ptr);
void QQuickItem_ResetAntialiasing(void* ptr);
void QQuickItem_ResetHeight(void* ptr);
void QQuickItem_ResetWidth(void* ptr);
double QQuickItem_Rotation(void* ptr);
double QQuickItem_Scale(void* ptr);
void QQuickItem_SetActiveFocusOnTab(void* ptr, int v);
void QQuickItem_SetAntialiasing(void* ptr, int v);
void QQuickItem_SetBaselineOffset(void* ptr, double v);
void QQuickItem_SetClip(void* ptr, int v);
void QQuickItem_SetEnabled(void* ptr, int v);
void QQuickItem_SetFocus(void* ptr, int v);
void QQuickItem_SetFocus2(void* ptr, int focus, int reason);
void QQuickItem_SetHeight(void* ptr, double v);
void QQuickItem_SetImplicitHeight(void* ptr, double v);
void QQuickItem_SetImplicitWidth(void* ptr, double v);
void QQuickItem_SetOpacity(void* ptr, double v);
void QQuickItem_SetParentItem(void* ptr, void* parent);
void QQuickItem_SetRotation(void* ptr, double v);
void QQuickItem_SetScale(void* ptr, double v);
void QQuickItem_SetSmooth(void* ptr, int v);
void QQuickItem_SetState(void* ptr, char* v);
void QQuickItem_SetTransformOrigin(void* ptr, int v);
void QQuickItem_SetVisible(void* ptr, int v);
void QQuickItem_SetWidth(void* ptr, double v);
void QQuickItem_SetX(void* ptr, double v);
void QQuickItem_SetY(void* ptr, double v);
void QQuickItem_SetZ(void* ptr, double v);
int QQuickItem_Smooth(void* ptr);
void* QQuickItem_TextureProvider(void* ptr);
int QQuickItem_TransformOrigin(void* ptr);
double QQuickItem_Width(void* ptr);
double QQuickItem_X(void* ptr);
double QQuickItem_Y(void* ptr);
double QQuickItem_Z(void* ptr);
int QQuickItem_AcceptHoverEvents(void* ptr);
int QQuickItem_AcceptedMouseButtons(void* ptr);
void* QQuickItem_ChildAt(void* ptr, double x, double y);
int QQuickItem_Contains(void* ptr, void* point);
int QQuickItem_FiltersChildMouseEvents(void* ptr);
int QQuickItem_Flags(void* ptr);
void QQuickItem_ForceActiveFocus(void* ptr);
void QQuickItem_ForceActiveFocus2(void* ptr, int reason);
void QQuickItem_GrabMouse(void* ptr);
double QQuickItem_ImplicitWidth(void* ptr);
void* QQuickItem_InputMethodQuery(void* ptr, int query);
int QQuickItem_IsFocusScope(void* ptr);
int QQuickItem_KeepMouseGrab(void* ptr);
int QQuickItem_KeepTouchGrab(void* ptr);
void* QQuickItem_NextItemInFocusChain(void* ptr, int forward);
void QQuickItem_Polish(void* ptr);
void* QQuickItem_ScopedFocusItem(void* ptr);
void QQuickItem_SetAcceptHoverEvents(void* ptr, int enabled);
void QQuickItem_SetAcceptedMouseButtons(void* ptr, int buttons);
void QQuickItem_SetCursor(void* ptr, void* cursor);
void QQuickItem_SetFiltersChildMouseEvents(void* ptr, int filter);
void QQuickItem_SetFlag(void* ptr, int flag, int enabled);
void QQuickItem_SetFlags(void* ptr, int flags);
void QQuickItem_SetKeepMouseGrab(void* ptr, int keep);
void QQuickItem_SetKeepTouchGrab(void* ptr, int keep);
void QQuickItem_StackAfter(void* ptr, void* sibling);
void QQuickItem_StackBefore(void* ptr, void* sibling);
void QQuickItem_UngrabMouse(void* ptr);
void QQuickItem_UngrabTouchPoints(void* ptr);
void QQuickItem_UnsetCursor(void* ptr);
void QQuickItem_Update(void* ptr);
void* QQuickItem_Window(void* ptr);
void QQuickItem_ConnectWindowChanged(void* ptr);
void QQuickItem_DisconnectWindowChanged(void* ptr);
void QQuickItem_DestroyQQuickItem(void* ptr);

#ifdef __cplusplus
}
#endif