// +build !minimal

#pragma once

#ifndef GO_QTQUICK_H
#define GO_QTQUICK_H

#include <stdint.h>

#ifdef __cplusplus
int QQuickFramebufferObject_QQuickFramebufferObject_QRegisterMetaType();
int QQuickImageResponse_QQuickImageResponse_QRegisterMetaType();
int QQuickItem_QQuickItem_QRegisterMetaType();
int QQuickItemGrabResult_QQuickItemGrabResult_QRegisterMetaType();
int QQuickPaintedItem_QQuickPaintedItem_QRegisterMetaType();
int QQuickRenderControl_QQuickRenderControl_QRegisterMetaType();
int QQuickTextDocument_QQuickTextDocument_QRegisterMetaType();
int QQuickTextureFactory_QQuickTextureFactory_QRegisterMetaType();
int QQuickView_QQuickView_QRegisterMetaType();
int QQuickWidget_QQuickWidget_QRegisterMetaType();
int QQuickWindow_QQuickWindow_QRegisterMetaType();
int QSGAbstractRenderer_QSGAbstractRenderer_QRegisterMetaType();
int QSGDynamicTexture_QSGDynamicTexture_QRegisterMetaType();
int QSGEngine_QSGEngine_QRegisterMetaType();
int QSGTexture_QSGTexture_QRegisterMetaType();
int QSGTextureProvider_QSGTextureProvider_QRegisterMetaType();
extern "C" {
#endif

struct QtQuick_PackedString { char* data; long long len; };
struct QtQuick_PackedList { void* data; long long len; };
void* QQuickAsyncImageProvider_NewQQuickAsyncImageProvider();
void* QQuickAsyncImageProvider_RequestImageResponse(void* ptr, struct QtQuick_PackedString id, void* requestedSize);
void QQuickAsyncImageProvider_DestroyQQuickAsyncImageProvider(void* ptr);
void QQuickAsyncImageProvider_DestroyQQuickAsyncImageProviderDefault(void* ptr);
void QQuickFramebufferObject_ConnectMirrorVerticallyChanged(void* ptr);
void QQuickFramebufferObject_DisconnectMirrorVerticallyChanged(void* ptr);
void QQuickFramebufferObject_MirrorVerticallyChanged(void* ptr, char vbo);
void QQuickFramebufferObject_SetMirrorVertically(void* ptr, char enable);
void QQuickFramebufferObject_SetTextureFollowsItemSize(void* ptr, char follows);
void QQuickFramebufferObject_ConnectTextureFollowsItemSizeChanged(void* ptr);
void QQuickFramebufferObject_DisconnectTextureFollowsItemSizeChanged(void* ptr);
void QQuickFramebufferObject_TextureFollowsItemSizeChanged(void* ptr, char vbo);
char QQuickFramebufferObject_MirrorVertically(void* ptr);
char QQuickFramebufferObject_TextureFollowsItemSize(void* ptr);
void* QQuickImageProvider_RequestImage(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void* QQuickImageProvider_RequestImageDefault(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void* QQuickImageProvider_RequestPixmap(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void* QQuickImageProvider_RequestPixmapDefault(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void* QQuickImageProvider_NewQQuickImageProvider(long long ty, long long flags);
void* QQuickImageProvider_RequestTexture(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void* QQuickImageProvider_RequestTextureDefault(void* ptr, struct QtQuick_PackedString id, void* size, void* requestedSize);
void QQuickImageProvider_DestroyQQuickImageProvider(void* ptr);
void QQuickImageProvider_DestroyQQuickImageProviderDefault(void* ptr);
long long QQuickImageProvider_Flags(void* ptr);
long long QQuickImageProvider_FlagsDefault(void* ptr);
long long QQuickImageProvider_ImageType(void* ptr);
long long QQuickImageProvider_ImageTypeDefault(void* ptr);
void* QQuickImageResponse_NewQQuickImageResponse();
void QQuickImageResponse_Cancel(void* ptr);
void QQuickImageResponse_CancelDefault(void* ptr);
void QQuickImageResponse_ConnectFinished(void* ptr);
void QQuickImageResponse_DisconnectFinished(void* ptr);
void QQuickImageResponse_Finished(void* ptr);
void QQuickImageResponse_DestroyQQuickImageResponse(void* ptr);
void QQuickImageResponse_DestroyQQuickImageResponseDefault(void* ptr);
void* QQuickImageResponse_TextureFactory(void* ptr);
struct QtQuick_PackedString QQuickImageResponse_ErrorString(void* ptr);
struct QtQuick_PackedString QQuickImageResponse_ErrorStringDefault(void* ptr);
void* QQuickImageResponse___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickImageResponse___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickImageResponse___dynamicPropertyNames_newList(void* ptr);
void* QQuickImageResponse___findChildren_atList2(void* ptr, int i);
void QQuickImageResponse___findChildren_setList2(void* ptr, void* i);
void* QQuickImageResponse___findChildren_newList2(void* ptr);
void* QQuickImageResponse___findChildren_atList3(void* ptr, int i);
void QQuickImageResponse___findChildren_setList3(void* ptr, void* i);
void* QQuickImageResponse___findChildren_newList3(void* ptr);
void* QQuickImageResponse___findChildren_atList(void* ptr, int i);
void QQuickImageResponse___findChildren_setList(void* ptr, void* i);
void* QQuickImageResponse___findChildren_newList(void* ptr);
void* QQuickImageResponse___children_atList(void* ptr, int i);
void QQuickImageResponse___children_setList(void* ptr, void* i);
void* QQuickImageResponse___children_newList(void* ptr);
char QQuickImageResponse_EventDefault(void* ptr, void* e);
char QQuickImageResponse_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickImageResponse_ChildEventDefault(void* ptr, void* event);
void QQuickImageResponse_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickImageResponse_CustomEventDefault(void* ptr, void* event);
void QQuickImageResponse_DeleteLaterDefault(void* ptr);
void QQuickImageResponse_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickImageResponse_TimerEventDefault(void* ptr, void* event);
void* QQuickImageResponse_MetaObjectDefault(void* ptr);
void* QQuickItem_NextItemInFocusChain(void* ptr, char forward);
void* QQuickItem_NewQQuickItem(void* parent);
void* QQuickItem_ChildrenRect(void* ptr);
char QQuickItem_ChildMouseEventFilter(void* ptr, void* item, void* event);
char QQuickItem_ChildMouseEventFilterDefault(void* ptr, void* item, void* event);
char QQuickItem_Event(void* ptr, void* ev);
char QQuickItem_EventDefault(void* ptr, void* ev);
void QQuickItem_ClassBegin(void* ptr);
void QQuickItem_ClassBeginDefault(void* ptr);
void QQuickItem_ComponentComplete(void* ptr);
void QQuickItem_ComponentCompleteDefault(void* ptr);
void QQuickItem_DragEnterEvent(void* ptr, void* event);
void QQuickItem_DragEnterEventDefault(void* ptr, void* event);
void QQuickItem_DragLeaveEvent(void* ptr, void* event);
void QQuickItem_DragLeaveEventDefault(void* ptr, void* event);
void QQuickItem_DragMoveEvent(void* ptr, void* event);
void QQuickItem_DragMoveEventDefault(void* ptr, void* event);
void QQuickItem_DropEvent(void* ptr, void* event);
void QQuickItem_DropEventDefault(void* ptr, void* event);
void QQuickItem_FocusInEvent(void* ptr, void* event);
void QQuickItem_FocusInEventDefault(void* ptr, void* event);
void QQuickItem_FocusOutEvent(void* ptr, void* event);
void QQuickItem_FocusOutEventDefault(void* ptr, void* event);
void QQuickItem_ForceActiveFocus(void* ptr);
void QQuickItem_ForceActiveFocus2(void* ptr, long long reason);
void QQuickItem_GeometryChanged(void* ptr, void* newGeometry, void* oldGeometry);
void QQuickItem_GeometryChangedDefault(void* ptr, void* newGeometry, void* oldGeometry);
void QQuickItem_GrabMouse(void* ptr);
void QQuickItem_GrabTouchPoints(void* ptr, void* ids);
void QQuickItem_HoverEnterEvent(void* ptr, void* event);
void QQuickItem_HoverEnterEventDefault(void* ptr, void* event);
void QQuickItem_HoverLeaveEvent(void* ptr, void* event);
void QQuickItem_HoverLeaveEventDefault(void* ptr, void* event);
void QQuickItem_HoverMoveEvent(void* ptr, void* event);
void QQuickItem_HoverMoveEventDefault(void* ptr, void* event);
void QQuickItem_InputMethodEvent(void* ptr, void* event);
void QQuickItem_InputMethodEventDefault(void* ptr, void* event);
void QQuickItem_KeyPressEvent(void* ptr, void* event);
void QQuickItem_KeyPressEventDefault(void* ptr, void* event);
void QQuickItem_KeyReleaseEvent(void* ptr, void* event);
void QQuickItem_KeyReleaseEventDefault(void* ptr, void* event);
void QQuickItem_MouseDoubleClickEvent(void* ptr, void* event);
void QQuickItem_MouseDoubleClickEventDefault(void* ptr, void* event);
void QQuickItem_MouseMoveEvent(void* ptr, void* event);
void QQuickItem_MouseMoveEventDefault(void* ptr, void* event);
void QQuickItem_MousePressEvent(void* ptr, void* event);
void QQuickItem_MousePressEventDefault(void* ptr, void* event);
void QQuickItem_MouseReleaseEvent(void* ptr, void* event);
void QQuickItem_MouseReleaseEventDefault(void* ptr, void* event);
void QQuickItem_MouseUngrabEvent(void* ptr);
void QQuickItem_MouseUngrabEventDefault(void* ptr);
void QQuickItem_Polish(void* ptr);
void QQuickItem_ReleaseResources(void* ptr);
void QQuickItem_ReleaseResourcesDefault(void* ptr);
void QQuickItem_ResetAntialiasing(void* ptr);
void QQuickItem_ResetHeight(void* ptr);
void QQuickItem_ResetWidth(void* ptr);
void QQuickItem_SetAcceptHoverEvents(void* ptr, char enabled);
void QQuickItem_SetAcceptedMouseButtons(void* ptr, long long buttons);
void QQuickItem_SetActiveFocusOnTab(void* ptr, char vbo);
void QQuickItem_SetAntialiasing(void* ptr, char vbo);
void QQuickItem_SetBaselineOffset(void* ptr, double vqr);
void QQuickItem_SetClip(void* ptr, char vbo);
void QQuickItem_SetCursor(void* ptr, void* cursor);
void QQuickItem_SetEnabled(void* ptr, char vbo);
void QQuickItem_SetFiltersChildMouseEvents(void* ptr, char filter);
void QQuickItem_SetFlag(void* ptr, long long flag, char enabled);
void QQuickItem_SetFlags(void* ptr, long long flags);
void QQuickItem_SetFocus(void* ptr, char vbo);
void QQuickItem_SetFocus2(void* ptr, char focus, long long reason);
void QQuickItem_SetHeight(void* ptr, double vqr);
void QQuickItem_SetImplicitHeight(void* ptr, double vqr);
void QQuickItem_SetImplicitWidth(void* ptr, double vqr);
void QQuickItem_SetKeepMouseGrab(void* ptr, char keep);
void QQuickItem_SetKeepTouchGrab(void* ptr, char keep);
void QQuickItem_SetOpacity(void* ptr, double vqr);
void QQuickItem_SetParentItem(void* ptr, void* parent);
void QQuickItem_SetRotation(void* ptr, double vqr);
void QQuickItem_SetScale(void* ptr, double vqr);
void QQuickItem_SetSmooth(void* ptr, char vbo);
void QQuickItem_SetState(void* ptr, struct QtQuick_PackedString vqs);
void QQuickItem_SetTransformOrigin(void* ptr, long long vtr);
void QQuickItem_SetVisible(void* ptr, char vbo);
void QQuickItem_SetWidth(void* ptr, double vqr);
void QQuickItem_SetX(void* ptr, double vqr);
void QQuickItem_SetY(void* ptr, double vqr);
void QQuickItem_SetZ(void* ptr, double vqr);
void QQuickItem_StackAfter(void* ptr, void* sibling);
void QQuickItem_StackBefore(void* ptr, void* sibling);
void QQuickItem_TouchEvent(void* ptr, void* event);
void QQuickItem_TouchEventDefault(void* ptr, void* event);
void QQuickItem_TouchUngrabEvent(void* ptr);
void QQuickItem_TouchUngrabEventDefault(void* ptr);
void QQuickItem_UngrabMouse(void* ptr);
void QQuickItem_UngrabTouchPoints(void* ptr);
void QQuickItem_UnsetCursor(void* ptr);
void QQuickItem_Update(void* ptr);
void QQuickItem_UpdateDefault(void* ptr);
void QQuickItem_UpdateInputMethod(void* ptr, long long queries);
void QQuickItem_UpdatePolish(void* ptr);
void QQuickItem_UpdatePolishDefault(void* ptr);
void QQuickItem_WheelEvent(void* ptr, void* event);
void QQuickItem_WheelEventDefault(void* ptr, void* event);
void QQuickItem_ConnectWindowChanged(void* ptr);
void QQuickItem_DisconnectWindowChanged(void* ptr);
void QQuickItem_WindowChanged(void* ptr, void* window);
void QQuickItem_DestroyQQuickItem(void* ptr);
void QQuickItem_DestroyQQuickItemDefault(void* ptr);
long long QQuickItem_Flags(void* ptr);
void* QQuickItem_Cursor(void* ptr);
struct QtQuick_PackedList QQuickItem_ChildItems(void* ptr);
void* QQuickItem_MapFromGlobal(void* ptr, void* point);
void* QQuickItem_MapFromItem(void* ptr, void* item, void* point);
void* QQuickItem_MapFromScene(void* ptr, void* point);
void* QQuickItem_MapToGlobal(void* ptr, void* point);
void* QQuickItem_MapToItem(void* ptr, void* item, void* point);
void* QQuickItem_MapToScene(void* ptr, void* point);
void* QQuickItem_ChildAt(void* ptr, double x, double y);
void* QQuickItem_ParentItem(void* ptr);
void* QQuickItem_ScopedFocusItem(void* ptr);
void* QQuickItem_Window(void* ptr);
void* QQuickItem_MapRectFromItem(void* ptr, void* item, void* rect);
void* QQuickItem_MapRectFromScene(void* ptr, void* rect);
void* QQuickItem_MapRectToItem(void* ptr, void* item, void* rect);
void* QQuickItem_MapRectToScene(void* ptr, void* rect);
void* QQuickItem_TextureProvider(void* ptr);
void* QQuickItem_TextureProviderDefault(void* ptr);
struct QtQuick_PackedString QQuickItem_State(void* ptr);
void* QQuickItem_InputMethodQuery(void* ptr, long long query);
void* QQuickItem_InputMethodQueryDefault(void* ptr, long long query);
long long QQuickItem_AcceptedMouseButtons(void* ptr);
long long QQuickItem_TransformOrigin(void* ptr);
char QQuickItem_AcceptHoverEvents(void* ptr);
char QQuickItem_ActiveFocusOnTab(void* ptr);
char QQuickItem_Antialiasing(void* ptr);
char QQuickItem_Clip(void* ptr);
char QQuickItem_Contains(void* ptr, void* point);
char QQuickItem_ContainsDefault(void* ptr, void* point);
char QQuickItem_FiltersChildMouseEvents(void* ptr);
char QQuickItem_HasActiveFocus(void* ptr);
char QQuickItem_HasFocus(void* ptr);
char QQuickItem_HeightValid(void* ptr);
char QQuickItem_IsAncestorOf(void* ptr, void* child);
char QQuickItem_IsComponentComplete(void* ptr);
char QQuickItem_IsEnabled(void* ptr);
char QQuickItem_IsFocusScope(void* ptr);
char QQuickItem_IsTextureProvider(void* ptr);
char QQuickItem_IsTextureProviderDefault(void* ptr);
char QQuickItem_IsVisible(void* ptr);
char QQuickItem_KeepMouseGrab(void* ptr);
char QQuickItem_KeepTouchGrab(void* ptr);
char QQuickItem_Smooth(void* ptr);
char QQuickItem_WidthValid(void* ptr);
double QQuickItem_BaselineOffset(void* ptr);
double QQuickItem_Height(void* ptr);
double QQuickItem_ImplicitHeight(void* ptr);
double QQuickItem_ImplicitWidth(void* ptr);
double QQuickItem_Opacity(void* ptr);
double QQuickItem_Rotation(void* ptr);
double QQuickItem_Scale(void* ptr);
double QQuickItem_Width(void* ptr);
double QQuickItem_X(void* ptr);
double QQuickItem_Y(void* ptr);
double QQuickItem_Z(void* ptr);
int QQuickItem___grabTouchPoints_ids_atList(void* ptr, int i);
void QQuickItem___grabTouchPoints_ids_setList(void* ptr, int i);
void* QQuickItem___grabTouchPoints_ids_newList(void* ptr);
void* QQuickItem___childItems_atList(void* ptr, int i);
void QQuickItem___childItems_setList(void* ptr, void* i);
void* QQuickItem___childItems_newList(void* ptr);
void* QQuickItem___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickItem___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickItem___dynamicPropertyNames_newList(void* ptr);
void* QQuickItem___findChildren_atList2(void* ptr, int i);
void QQuickItem___findChildren_setList2(void* ptr, void* i);
void* QQuickItem___findChildren_newList2(void* ptr);
void* QQuickItem___findChildren_atList3(void* ptr, int i);
void QQuickItem___findChildren_setList3(void* ptr, void* i);
void* QQuickItem___findChildren_newList3(void* ptr);
void* QQuickItem___findChildren_atList(void* ptr, int i);
void QQuickItem___findChildren_setList(void* ptr, void* i);
void* QQuickItem___findChildren_newList(void* ptr);
void* QQuickItem___children_atList(void* ptr, int i);
void QQuickItem___children_setList(void* ptr, void* i);
void* QQuickItem___children_newList(void* ptr);
char QQuickItem_EventFilter(void* ptr, void* watched, void* event);
char QQuickItem_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickItem_ChildEvent(void* ptr, void* event);
void QQuickItem_ChildEventDefault(void* ptr, void* event);
void QQuickItem_ConnectNotify(void* ptr, void* sign);
void QQuickItem_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickItem_CustomEvent(void* ptr, void* event);
void QQuickItem_CustomEventDefault(void* ptr, void* event);
void QQuickItem_DeleteLater(void* ptr);
void QQuickItem_DeleteLaterDefault(void* ptr);
void QQuickItem_DisconnectNotify(void* ptr, void* sign);
void QQuickItem_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickItem_TimerEvent(void* ptr, void* event);
void QQuickItem_TimerEventDefault(void* ptr, void* event);
void* QQuickItem_MetaObject(void* ptr);
void* QQuickItem_MetaObjectDefault(void* ptr);
void QQuickItemGrabResult_ConnectReady(void* ptr);
void QQuickItemGrabResult_DisconnectReady(void* ptr);
void QQuickItemGrabResult_Ready(void* ptr);
void* QQuickItemGrabResult_Image(void* ptr);
void* QQuickItemGrabResult_Url(void* ptr);
char QQuickItemGrabResult_SaveToFile(void* ptr, struct QtQuick_PackedString fileName);
void* QQuickItemGrabResult___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickItemGrabResult___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickItemGrabResult___dynamicPropertyNames_newList(void* ptr);
void* QQuickItemGrabResult___findChildren_atList2(void* ptr, int i);
void QQuickItemGrabResult___findChildren_setList2(void* ptr, void* i);
void* QQuickItemGrabResult___findChildren_newList2(void* ptr);
void* QQuickItemGrabResult___findChildren_atList3(void* ptr, int i);
void QQuickItemGrabResult___findChildren_setList3(void* ptr, void* i);
void* QQuickItemGrabResult___findChildren_newList3(void* ptr);
void* QQuickItemGrabResult___findChildren_atList(void* ptr, int i);
void QQuickItemGrabResult___findChildren_setList(void* ptr, void* i);
void* QQuickItemGrabResult___findChildren_newList(void* ptr);
void* QQuickItemGrabResult___children_atList(void* ptr, int i);
void QQuickItemGrabResult___children_setList(void* ptr, void* i);
void* QQuickItemGrabResult___children_newList(void* ptr);
char QQuickItemGrabResult_EventDefault(void* ptr, void* e);
char QQuickItemGrabResult_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickItemGrabResult_ChildEventDefault(void* ptr, void* event);
void QQuickItemGrabResult_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickItemGrabResult_CustomEventDefault(void* ptr, void* event);
void QQuickItemGrabResult_DeleteLaterDefault(void* ptr);
void QQuickItemGrabResult_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickItemGrabResult_TimerEventDefault(void* ptr, void* event);
void* QQuickItemGrabResult_MetaObjectDefault(void* ptr);
void* QQuickPaintedItem_NewQQuickPaintedItem(void* parent);
void QQuickPaintedItem_ConnectContentsScaleChanged(void* ptr);
void QQuickPaintedItem_DisconnectContentsScaleChanged(void* ptr);
void QQuickPaintedItem_ContentsScaleChanged(void* ptr);
void QQuickPaintedItem_ConnectContentsSizeChanged(void* ptr);
void QQuickPaintedItem_DisconnectContentsSizeChanged(void* ptr);
void QQuickPaintedItem_ContentsSizeChanged(void* ptr);
void QQuickPaintedItem_ConnectFillColorChanged(void* ptr);
void QQuickPaintedItem_DisconnectFillColorChanged(void* ptr);
void QQuickPaintedItem_FillColorChanged(void* ptr);
void QQuickPaintedItem_Paint(void* ptr, void* painter);
void QQuickPaintedItem_ConnectRenderTargetChanged(void* ptr);
void QQuickPaintedItem_DisconnectRenderTargetChanged(void* ptr);
void QQuickPaintedItem_RenderTargetChanged(void* ptr);
void QQuickPaintedItem_SetContentsScale(void* ptr, double vqr);
void QQuickPaintedItem_SetContentsSize(void* ptr, void* vqs);
void QQuickPaintedItem_SetFillColor(void* ptr, void* vqc);
void QQuickPaintedItem_SetMipmap(void* ptr, char enable);
void QQuickPaintedItem_SetOpaquePainting(void* ptr, char opaque);
void QQuickPaintedItem_SetPerformanceHint(void* ptr, long long hint, char enabled);
void QQuickPaintedItem_SetPerformanceHints(void* ptr, long long hints);
void QQuickPaintedItem_SetRenderTarget(void* ptr, long long target);
void QQuickPaintedItem_SetTextureSize(void* ptr, void* size);
void QQuickPaintedItem_ConnectTextureSizeChanged(void* ptr);
void QQuickPaintedItem_DisconnectTextureSizeChanged(void* ptr);
void QQuickPaintedItem_TextureSizeChanged(void* ptr);
void QQuickPaintedItem_Update(void* ptr, void* rect);
void QQuickPaintedItem_DestroyQQuickPaintedItem(void* ptr);
void QQuickPaintedItem_DestroyQQuickPaintedItemDefault(void* ptr);
long long QQuickPaintedItem_PerformanceHints(void* ptr);
void* QQuickPaintedItem_FillColor(void* ptr);
void* QQuickPaintedItem_ContentsSize(void* ptr);
void* QQuickPaintedItem_TextureSize(void* ptr);
long long QQuickPaintedItem_RenderTarget(void* ptr);
char QQuickPaintedItem_Mipmap(void* ptr);
char QQuickPaintedItem_OpaquePainting(void* ptr);
double QQuickPaintedItem_ContentsScale(void* ptr);
void* QQuickRenderControl_Grab(void* ptr);
void* QQuickRenderControl_NewQQuickRenderControl(void* parent);
void* QQuickRenderControl_RenderWindow(void* ptr, void* offset);
void* QQuickRenderControl_RenderWindowDefault(void* ptr, void* offset);
void* QQuickRenderControl_QQuickRenderControl_RenderWindowFor(void* win, void* offset);
char QQuickRenderControl_Sync(void* ptr);
void QQuickRenderControl_Initialize(void* ptr, void* gl);
void QQuickRenderControl_Invalidate(void* ptr);
void QQuickRenderControl_PolishItems(void* ptr);
void QQuickRenderControl_PrepareThread(void* ptr, void* targetThread);
void QQuickRenderControl_Render(void* ptr);
void QQuickRenderControl_ConnectRenderRequested(void* ptr);
void QQuickRenderControl_DisconnectRenderRequested(void* ptr);
void QQuickRenderControl_RenderRequested(void* ptr);
void QQuickRenderControl_ConnectSceneChanged(void* ptr);
void QQuickRenderControl_DisconnectSceneChanged(void* ptr);
void QQuickRenderControl_SceneChanged(void* ptr);
void QQuickRenderControl_DestroyQQuickRenderControl(void* ptr);
void* QQuickRenderControl___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickRenderControl___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickRenderControl___dynamicPropertyNames_newList(void* ptr);
void* QQuickRenderControl___findChildren_atList2(void* ptr, int i);
void QQuickRenderControl___findChildren_setList2(void* ptr, void* i);
void* QQuickRenderControl___findChildren_newList2(void* ptr);
void* QQuickRenderControl___findChildren_atList3(void* ptr, int i);
void QQuickRenderControl___findChildren_setList3(void* ptr, void* i);
void* QQuickRenderControl___findChildren_newList3(void* ptr);
void* QQuickRenderControl___findChildren_atList(void* ptr, int i);
void QQuickRenderControl___findChildren_setList(void* ptr, void* i);
void* QQuickRenderControl___findChildren_newList(void* ptr);
void* QQuickRenderControl___children_atList(void* ptr, int i);
void QQuickRenderControl___children_setList(void* ptr, void* i);
void* QQuickRenderControl___children_newList(void* ptr);
char QQuickRenderControl_EventDefault(void* ptr, void* e);
char QQuickRenderControl_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickRenderControl_ChildEventDefault(void* ptr, void* event);
void QQuickRenderControl_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickRenderControl_CustomEventDefault(void* ptr, void* event);
void QQuickRenderControl_DeleteLaterDefault(void* ptr);
void QQuickRenderControl_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickRenderControl_TimerEventDefault(void* ptr, void* event);
void* QQuickRenderControl_MetaObjectDefault(void* ptr);
void* QQuickTextDocument_NewQQuickTextDocument(void* parent);
void* QQuickTextDocument_TextDocument(void* ptr);
void* QQuickTextDocument___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickTextDocument___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickTextDocument___dynamicPropertyNames_newList(void* ptr);
void* QQuickTextDocument___findChildren_atList2(void* ptr, int i);
void QQuickTextDocument___findChildren_setList2(void* ptr, void* i);
void* QQuickTextDocument___findChildren_newList2(void* ptr);
void* QQuickTextDocument___findChildren_atList3(void* ptr, int i);
void QQuickTextDocument___findChildren_setList3(void* ptr, void* i);
void* QQuickTextDocument___findChildren_newList3(void* ptr);
void* QQuickTextDocument___findChildren_atList(void* ptr, int i);
void QQuickTextDocument___findChildren_setList(void* ptr, void* i);
void* QQuickTextDocument___findChildren_newList(void* ptr);
void* QQuickTextDocument___children_atList(void* ptr, int i);
void QQuickTextDocument___children_setList(void* ptr, void* i);
void* QQuickTextDocument___children_newList(void* ptr);
char QQuickTextDocument_EventDefault(void* ptr, void* e);
char QQuickTextDocument_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickTextDocument_ChildEventDefault(void* ptr, void* event);
void QQuickTextDocument_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickTextDocument_CustomEventDefault(void* ptr, void* event);
void QQuickTextDocument_DeleteLaterDefault(void* ptr);
void QQuickTextDocument_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickTextDocument_TimerEventDefault(void* ptr, void* event);
void* QQuickTextDocument_MetaObjectDefault(void* ptr);
void* QQuickTextureFactory_QQuickTextureFactory_TextureFactoryForImage(void* image);
void* QQuickTextureFactory_NewQQuickTextureFactory();
void QQuickTextureFactory_DestroyQQuickTextureFactory(void* ptr);
void QQuickTextureFactory_DestroyQQuickTextureFactoryDefault(void* ptr);
void* QQuickTextureFactory_Image(void* ptr);
void* QQuickTextureFactory_ImageDefault(void* ptr);
void* QQuickTextureFactory_CreateTexture(void* ptr, void* window);
void* QQuickTextureFactory_TextureSize(void* ptr);
int QQuickTextureFactory_TextureByteCount(void* ptr);
void* QQuickTextureFactory___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickTextureFactory___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickTextureFactory___dynamicPropertyNames_newList(void* ptr);
void* QQuickTextureFactory___findChildren_atList2(void* ptr, int i);
void QQuickTextureFactory___findChildren_setList2(void* ptr, void* i);
void* QQuickTextureFactory___findChildren_newList2(void* ptr);
void* QQuickTextureFactory___findChildren_atList3(void* ptr, int i);
void QQuickTextureFactory___findChildren_setList3(void* ptr, void* i);
void* QQuickTextureFactory___findChildren_newList3(void* ptr);
void* QQuickTextureFactory___findChildren_atList(void* ptr, int i);
void QQuickTextureFactory___findChildren_setList(void* ptr, void* i);
void* QQuickTextureFactory___findChildren_newList(void* ptr);
void* QQuickTextureFactory___children_atList(void* ptr, int i);
void QQuickTextureFactory___children_setList(void* ptr, void* i);
void* QQuickTextureFactory___children_newList(void* ptr);
char QQuickTextureFactory_EventDefault(void* ptr, void* e);
char QQuickTextureFactory_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickTextureFactory_ChildEventDefault(void* ptr, void* event);
void QQuickTextureFactory_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickTextureFactory_CustomEventDefault(void* ptr, void* event);
void QQuickTextureFactory_DeleteLaterDefault(void* ptr);
void QQuickTextureFactory_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickTextureFactory_TimerEventDefault(void* ptr, void* event);
void* QQuickTextureFactory_MetaObjectDefault(void* ptr);
void* QQuickView_NewQQuickView2(void* engine, void* parent);
void* QQuickView_NewQQuickView(void* parent);
void* QQuickView_NewQQuickView3(void* source, void* parent);
void QQuickView_SetResizeMode(void* ptr, long long vre);
void QQuickView_SetSource(void* ptr, void* url);
void QQuickView_SetSourceDefault(void* ptr, void* url);
void QQuickView_ConnectStatusChanged(void* ptr);
void QQuickView_DisconnectStatusChanged(void* ptr);
void QQuickView_StatusChanged(void* ptr, long long status);
void QQuickView_DestroyQQuickView(void* ptr);
void QQuickView_DestroyQQuickViewDefault(void* ptr);
struct QtQuick_PackedList QQuickView_Errors(void* ptr);
void* QQuickView_RootContext(void* ptr);
void* QQuickView_Engine(void* ptr);
void* QQuickView_RootObject(void* ptr);
void* QQuickView_InitialSize(void* ptr);
void* QQuickView_Source(void* ptr);
long long QQuickView_ResizeMode(void* ptr);
long long QQuickView_Status(void* ptr);
void* QQuickView___errors_atList(void* ptr, int i);
void QQuickView___errors_setList(void* ptr, void* i);
void* QQuickView___errors_newList(void* ptr);
void* QQuickWidget_NewQQuickWidget2(void* engine, void* parent);
void* QQuickWidget_NewQQuickWidget(void* parent);
void* QQuickWidget_NewQQuickWidget3(void* source, void* parent);
char QQuickWidget_EventDefault(void* ptr, void* e);
void QQuickWidget_DragEnterEventDefault(void* ptr, void* e);
void QQuickWidget_DragLeaveEventDefault(void* ptr, void* e);
void QQuickWidget_DragMoveEventDefault(void* ptr, void* e);
void QQuickWidget_DropEventDefault(void* ptr, void* e);
void QQuickWidget_FocusInEventDefault(void* ptr, void* event);
void QQuickWidget_FocusOutEventDefault(void* ptr, void* event);
void QQuickWidget_HideEventDefault(void* ptr, void* vqh);
void QQuickWidget_KeyPressEventDefault(void* ptr, void* e);
void QQuickWidget_KeyReleaseEventDefault(void* ptr, void* e);
void QQuickWidget_MouseDoubleClickEventDefault(void* ptr, void* e);
void QQuickWidget_MouseMoveEventDefault(void* ptr, void* e);
void QQuickWidget_MousePressEventDefault(void* ptr, void* e);
void QQuickWidget_MouseReleaseEventDefault(void* ptr, void* e);
void QQuickWidget_PaintEventDefault(void* ptr, void* event);
void QQuickWidget_ConnectSceneGraphError(void* ptr);
void QQuickWidget_DisconnectSceneGraphError(void* ptr);
void QQuickWidget_SceneGraphError(void* ptr, long long error, struct QtQuick_PackedString message);
void QQuickWidget_SetClearColor(void* ptr, void* color);
void QQuickWidget_SetFormat(void* ptr, void* format);
void QQuickWidget_SetResizeMode(void* ptr, long long vre);
void QQuickWidget_SetSource(void* ptr, void* url);
void QQuickWidget_SetSourceDefault(void* ptr, void* url);
void QQuickWidget_ShowEventDefault(void* ptr, void* vqs);
void QQuickWidget_ConnectStatusChanged(void* ptr);
void QQuickWidget_DisconnectStatusChanged(void* ptr);
void QQuickWidget_StatusChanged(void* ptr, long long status);
void QQuickWidget_WheelEventDefault(void* ptr, void* e);
void QQuickWidget_DestroyQQuickWidget(void* ptr);
void QQuickWidget_DestroyQQuickWidgetDefault(void* ptr);
void* QQuickWidget_GrabFramebuffer(void* ptr);
struct QtQuick_PackedList QQuickWidget_Errors(void* ptr);
void* QQuickWidget_RootContext(void* ptr);
void* QQuickWidget_Engine(void* ptr);
void* QQuickWidget_RootObject(void* ptr);
void* QQuickWidget_QuickWindow(void* ptr);
void* QQuickWidget_InitialSize(void* ptr);
void* QQuickWidget_Format(void* ptr);
void* QQuickWidget_Source(void* ptr);
long long QQuickWidget_ResizeMode(void* ptr);
long long QQuickWidget_Status(void* ptr);
void* QQuickWidget___errors_atList(void* ptr, int i);
void QQuickWidget___errors_setList(void* ptr, void* i);
void* QQuickWidget___errors_newList(void* ptr);
void* QQuickWidget___addActions_actions_atList(void* ptr, int i);
void QQuickWidget___addActions_actions_setList(void* ptr, void* i);
void* QQuickWidget___addActions_actions_newList(void* ptr);
void* QQuickWidget___insertActions_actions_atList(void* ptr, int i);
void QQuickWidget___insertActions_actions_setList(void* ptr, void* i);
void* QQuickWidget___insertActions_actions_newList(void* ptr);
void* QQuickWidget___actions_atList(void* ptr, int i);
void QQuickWidget___actions_setList(void* ptr, void* i);
void* QQuickWidget___actions_newList(void* ptr);
void* QQuickWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickWidget___dynamicPropertyNames_newList(void* ptr);
void* QQuickWidget___findChildren_atList2(void* ptr, int i);
void QQuickWidget___findChildren_setList2(void* ptr, void* i);
void* QQuickWidget___findChildren_newList2(void* ptr);
void* QQuickWidget___findChildren_atList3(void* ptr, int i);
void QQuickWidget___findChildren_setList3(void* ptr, void* i);
void* QQuickWidget___findChildren_newList3(void* ptr);
void* QQuickWidget___findChildren_atList(void* ptr, int i);
void QQuickWidget___findChildren_setList(void* ptr, void* i);
void* QQuickWidget___findChildren_newList(void* ptr);
void* QQuickWidget___children_atList(void* ptr, int i);
void QQuickWidget___children_setList(void* ptr, void* i);
void* QQuickWidget___children_newList(void* ptr);
char QQuickWidget_CloseDefault(void* ptr);
char QQuickWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QQuickWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QQuickWidget_ActionEventDefault(void* ptr, void* event);
void QQuickWidget_ChangeEventDefault(void* ptr, void* event);
void QQuickWidget_CloseEventDefault(void* ptr, void* event);
void QQuickWidget_ContextMenuEventDefault(void* ptr, void* event);
void QQuickWidget_EnterEventDefault(void* ptr, void* event);
void QQuickWidget_HideDefault(void* ptr);
void QQuickWidget_InputMethodEventDefault(void* ptr, void* event);
void QQuickWidget_LeaveEventDefault(void* ptr, void* event);
void QQuickWidget_LowerDefault(void* ptr);
void QQuickWidget_MoveEventDefault(void* ptr, void* event);
void QQuickWidget_RaiseDefault(void* ptr);
void QQuickWidget_RepaintDefault(void* ptr);
void QQuickWidget_ResizeEventDefault(void* ptr, void* event);
void QQuickWidget_SetDisabledDefault(void* ptr, char disable);
void QQuickWidget_SetEnabledDefault(void* ptr, char vbo);
void QQuickWidget_SetFocus2Default(void* ptr);
void QQuickWidget_SetHiddenDefault(void* ptr, char hidden);
void QQuickWidget_SetStyleSheetDefault(void* ptr, struct QtQuick_PackedString styleSheet);
void QQuickWidget_SetVisibleDefault(void* ptr, char visible);
void QQuickWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QQuickWidget_SetWindowTitleDefault(void* ptr, struct QtQuick_PackedString vqs);
void QQuickWidget_ShowDefault(void* ptr);
void QQuickWidget_ShowFullScreenDefault(void* ptr);
void QQuickWidget_ShowMaximizedDefault(void* ptr);
void QQuickWidget_ShowMinimizedDefault(void* ptr);
void QQuickWidget_ShowNormalDefault(void* ptr);
void QQuickWidget_TabletEventDefault(void* ptr, void* event);
void QQuickWidget_UpdateDefault(void* ptr);
void QQuickWidget_UpdateMicroFocusDefault(void* ptr);
void* QQuickWidget_PaintEngineDefault(void* ptr);
void* QQuickWidget_MinimumSizeHintDefault(void* ptr);
void* QQuickWidget_SizeHintDefault(void* ptr);
void* QQuickWidget_InputMethodQueryDefault(void* ptr, long long query);
char QQuickWidget_HasHeightForWidthDefault(void* ptr);
int QQuickWidget_HeightForWidthDefault(void* ptr, int w);
int QQuickWidget_MetricDefault(void* ptr, long long m);
char QQuickWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickWidget_ChildEventDefault(void* ptr, void* event);
void QQuickWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickWidget_CustomEventDefault(void* ptr, void* event);
void QQuickWidget_DeleteLaterDefault(void* ptr);
void QQuickWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickWidget_TimerEventDefault(void* ptr, void* event);
void* QQuickWidget_MetaObjectDefault(void* ptr);
void* QQuickWindow_GrabWindow(void* ptr);
void* QQuickWindow_NewQQuickWindow(void* parent);
struct QtQuick_PackedString QQuickWindow_QQuickWindow_SceneGraphBackend();
char QQuickWindow_EventDefault(void* ptr, void* e);
char QQuickWindow_QQuickWindow_HasDefaultAlphaBuffer();
void QQuickWindow_ConnectActiveFocusItemChanged(void* ptr);
void QQuickWindow_DisconnectActiveFocusItemChanged(void* ptr);
void QQuickWindow_ActiveFocusItemChanged(void* ptr);
void QQuickWindow_ConnectAfterAnimating(void* ptr);
void QQuickWindow_DisconnectAfterAnimating(void* ptr);
void QQuickWindow_AfterAnimating(void* ptr);
void QQuickWindow_ConnectAfterRendering(void* ptr);
void QQuickWindow_DisconnectAfterRendering(void* ptr);
void QQuickWindow_AfterRendering(void* ptr);
void QQuickWindow_ConnectAfterSynchronizing(void* ptr);
void QQuickWindow_DisconnectAfterSynchronizing(void* ptr);
void QQuickWindow_AfterSynchronizing(void* ptr);
void QQuickWindow_ConnectBeforeRendering(void* ptr);
void QQuickWindow_DisconnectBeforeRendering(void* ptr);
void QQuickWindow_BeforeRendering(void* ptr);
void QQuickWindow_ConnectBeforeSynchronizing(void* ptr);
void QQuickWindow_DisconnectBeforeSynchronizing(void* ptr);
void QQuickWindow_BeforeSynchronizing(void* ptr);
void QQuickWindow_ConnectColorChanged(void* ptr);
void QQuickWindow_DisconnectColorChanged(void* ptr);
void QQuickWindow_ColorChanged(void* ptr, void* vqc);
void QQuickWindow_ExposeEventDefault(void* ptr, void* vqe);
void QQuickWindow_FocusInEventDefault(void* ptr, void* ev);
void QQuickWindow_FocusOutEventDefault(void* ptr, void* ev);
void QQuickWindow_ConnectFrameSwapped(void* ptr);
void QQuickWindow_DisconnectFrameSwapped(void* ptr);
void QQuickWindow_FrameSwapped(void* ptr);
void QQuickWindow_HideEventDefault(void* ptr, void* vqh);
void QQuickWindow_KeyPressEventDefault(void* ptr, void* e);
void QQuickWindow_KeyReleaseEventDefault(void* ptr, void* e);
void QQuickWindow_MouseDoubleClickEventDefault(void* ptr, void* event);
void QQuickWindow_MouseMoveEventDefault(void* ptr, void* event);
void QQuickWindow_MousePressEventDefault(void* ptr, void* event);
void QQuickWindow_MouseReleaseEventDefault(void* ptr, void* event);
void QQuickWindow_ConnectOpenglContextCreated(void* ptr);
void QQuickWindow_DisconnectOpenglContextCreated(void* ptr);
void QQuickWindow_OpenglContextCreated(void* ptr, void* context);
void QQuickWindow_ReleaseResources(void* ptr);
void QQuickWindow_ReleaseResourcesDefault(void* ptr);
void QQuickWindow_ResetOpenGLState(void* ptr);
void QQuickWindow_ResizeEventDefault(void* ptr, void* ev);
void QQuickWindow_ConnectSceneGraphAboutToStop(void* ptr);
void QQuickWindow_DisconnectSceneGraphAboutToStop(void* ptr);
void QQuickWindow_SceneGraphAboutToStop(void* ptr);
void QQuickWindow_ConnectSceneGraphError(void* ptr);
void QQuickWindow_DisconnectSceneGraphError(void* ptr);
void QQuickWindow_SceneGraphError(void* ptr, long long error, struct QtQuick_PackedString message);
void QQuickWindow_ConnectSceneGraphInitialized(void* ptr);
void QQuickWindow_DisconnectSceneGraphInitialized(void* ptr);
void QQuickWindow_SceneGraphInitialized(void* ptr);
void QQuickWindow_ConnectSceneGraphInvalidated(void* ptr);
void QQuickWindow_DisconnectSceneGraphInvalidated(void* ptr);
void QQuickWindow_SceneGraphInvalidated(void* ptr);
void QQuickWindow_ScheduleRenderJob(void* ptr, void* job, long long stage);
void QQuickWindow_SetClearBeforeRendering(void* ptr, char enabled);
void QQuickWindow_SetColor(void* ptr, void* color);
void QQuickWindow_QQuickWindow_SetDefaultAlphaBuffer(char useAlpha);
void QQuickWindow_SetPersistentOpenGLContext(void* ptr, char persistent);
void QQuickWindow_SetPersistentSceneGraph(void* ptr, char persistent);
void QQuickWindow_SetRenderTarget(void* ptr, void* fbo);
void QQuickWindow_SetRenderTarget2(void* ptr, unsigned int fboId, void* size);
void QQuickWindow_QQuickWindow_SetSceneGraphBackend(long long api);
void QQuickWindow_QQuickWindow_SetSceneGraphBackend2(struct QtQuick_PackedString backend);
void QQuickWindow_ShowEventDefault(void* ptr, void* vqs);
void QQuickWindow_Update(void* ptr);
void QQuickWindow_UpdateDefault(void* ptr);
void QQuickWindow_WheelEventDefault(void* ptr, void* event);
void QQuickWindow_DestroyQQuickWindow(void* ptr);
void QQuickWindow_DestroyQQuickWindowDefault(void* ptr);
void* QQuickWindow_AccessibleRoot(void* ptr);
void* QQuickWindow_Color(void* ptr);
void* QQuickWindow_OpenglContext(void* ptr);
void* QQuickWindow_RenderTarget(void* ptr);
void* QQuickWindow_IncubationController(void* ptr);
void* QQuickWindow_ActiveFocusItem(void* ptr);
void* QQuickWindow_ContentItem(void* ptr);
void* QQuickWindow_MouseGrabberItem(void* ptr);
void* QQuickWindow_CreateImageNode(void* ptr);
void* QQuickWindow_CreateRectangleNode(void* ptr);
void* QQuickWindow_RendererInterface(void* ptr);
void* QQuickWindow_CreateTextureFromId(void* ptr, unsigned int id, void* size, long long options);
void* QQuickWindow_CreateTextureFromImage2(void* ptr, void* image);
void* QQuickWindow_CreateTextureFromImage(void* ptr, void* image, long long options);
void* QQuickWindow_RenderTargetSize(void* ptr);
char QQuickWindow_ClearBeforeRendering(void* ptr);
char QQuickWindow_IsPersistentOpenGLContext(void* ptr);
char QQuickWindow_IsPersistentSceneGraph(void* ptr);
char QQuickWindow_IsSceneGraphInitialized(void* ptr);
double QQuickWindow_EffectiveDevicePixelRatio(void* ptr);
unsigned int QQuickWindow_RenderTargetId(void* ptr);
void* QQuickWindow___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickWindow___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickWindow___dynamicPropertyNames_newList(void* ptr);
void* QQuickWindow___findChildren_atList2(void* ptr, int i);
void QQuickWindow___findChildren_setList2(void* ptr, void* i);
void* QQuickWindow___findChildren_newList2(void* ptr);
void* QQuickWindow___findChildren_atList3(void* ptr, int i);
void QQuickWindow___findChildren_setList3(void* ptr, void* i);
void* QQuickWindow___findChildren_newList3(void* ptr);
void* QQuickWindow___findChildren_atList(void* ptr, int i);
void QQuickWindow___findChildren_setList(void* ptr, void* i);
void* QQuickWindow___findChildren_newList(void* ptr);
void* QQuickWindow___children_atList(void* ptr, int i);
void QQuickWindow___children_setList(void* ptr, void* i);
void* QQuickWindow___children_newList(void* ptr);
char QQuickWindow_CloseDefault(void* ptr);
char QQuickWindow_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QQuickWindow_AlertDefault(void* ptr, int msec);
void QQuickWindow_HideDefault(void* ptr);
void QQuickWindow_LowerDefault(void* ptr);
void QQuickWindow_MoveEventDefault(void* ptr, void* ev);
void QQuickWindow_RaiseDefault(void* ptr);
void QQuickWindow_RequestActivateDefault(void* ptr);
void QQuickWindow_RequestUpdateDefault(void* ptr);
void QQuickWindow_SetHeightDefault(void* ptr, int arg);
void QQuickWindow_SetMaximumHeightDefault(void* ptr, int h);
void QQuickWindow_SetMaximumWidthDefault(void* ptr, int w);
void QQuickWindow_SetMinimumHeightDefault(void* ptr, int h);
void QQuickWindow_SetMinimumWidthDefault(void* ptr, int w);
void QQuickWindow_SetTitleDefault(void* ptr, struct QtQuick_PackedString vqs);
void QQuickWindow_SetVisibleDefault(void* ptr, char visible);
void QQuickWindow_SetWidthDefault(void* ptr, int arg);
void QQuickWindow_SetXDefault(void* ptr, int arg);
void QQuickWindow_SetYDefault(void* ptr, int arg);
void QQuickWindow_ShowDefault(void* ptr);
void QQuickWindow_ShowFullScreenDefault(void* ptr);
void QQuickWindow_ShowMaximizedDefault(void* ptr);
void QQuickWindow_ShowMinimizedDefault(void* ptr);
void QQuickWindow_ShowNormalDefault(void* ptr);
void QQuickWindow_TabletEventDefault(void* ptr, void* ev);
void QQuickWindow_TouchEventDefault(void* ptr, void* ev);
void* QQuickWindow_FocusObjectDefault(void* ptr);
void* QQuickWindow_SizeDefault(void* ptr);
void* QQuickWindow_FormatDefault(void* ptr);
long long QQuickWindow_SurfaceTypeDefault(void* ptr);
char QQuickWindow_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickWindow_ChildEventDefault(void* ptr, void* event);
void QQuickWindow_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickWindow_CustomEventDefault(void* ptr, void* event);
void QQuickWindow_DeleteLaterDefault(void* ptr);
void QQuickWindow_DisconnectNotifyDefault(void* ptr, void* sign);
void QQuickWindow_TimerEventDefault(void* ptr, void* event);
void* QQuickWindow_MetaObjectDefault(void* ptr);
void QSGAbstractRenderer_RenderScene(void* ptr, unsigned int fboId);
void QSGAbstractRenderer_ConnectSceneGraphChanged(void* ptr);
void QSGAbstractRenderer_DisconnectSceneGraphChanged(void* ptr);
void QSGAbstractRenderer_SceneGraphChanged(void* ptr);
void QSGAbstractRenderer_SetClearColor(void* ptr, void* color);
void QSGAbstractRenderer_SetClearMode(void* ptr, long long mode);
void QSGAbstractRenderer_SetDeviceRect(void* ptr, void* rect);
void QSGAbstractRenderer_SetDeviceRect2(void* ptr, void* size);
void QSGAbstractRenderer_SetProjectionMatrix(void* ptr, void* matrix);
void QSGAbstractRenderer_SetProjectionMatrixToRect(void* ptr, void* rect);
void QSGAbstractRenderer_SetViewportRect(void* ptr, void* rect);
void QSGAbstractRenderer_SetViewportRect2(void* ptr, void* size);
long long QSGAbstractRenderer_ClearMode(void* ptr);
void* QSGAbstractRenderer_ClearColor(void* ptr);
void* QSGAbstractRenderer_ProjectionMatrix(void* ptr);
void* QSGAbstractRenderer_DeviceRect(void* ptr);
void* QSGAbstractRenderer_ViewportRect(void* ptr);
void* QSGAbstractRenderer___dynamicPropertyNames_atList(void* ptr, int i);
void QSGAbstractRenderer___dynamicPropertyNames_setList(void* ptr, void* i);
void* QSGAbstractRenderer___dynamicPropertyNames_newList(void* ptr);
void* QSGAbstractRenderer___findChildren_atList2(void* ptr, int i);
void QSGAbstractRenderer___findChildren_setList2(void* ptr, void* i);
void* QSGAbstractRenderer___findChildren_newList2(void* ptr);
void* QSGAbstractRenderer___findChildren_atList3(void* ptr, int i);
void QSGAbstractRenderer___findChildren_setList3(void* ptr, void* i);
void* QSGAbstractRenderer___findChildren_newList3(void* ptr);
void* QSGAbstractRenderer___findChildren_atList(void* ptr, int i);
void QSGAbstractRenderer___findChildren_setList(void* ptr, void* i);
void* QSGAbstractRenderer___findChildren_newList(void* ptr);
void* QSGAbstractRenderer___children_atList(void* ptr, int i);
void QSGAbstractRenderer___children_setList(void* ptr, void* i);
void* QSGAbstractRenderer___children_newList(void* ptr);
char QSGAbstractRenderer_EventDefault(void* ptr, void* e);
char QSGAbstractRenderer_EventFilterDefault(void* ptr, void* watched, void* event);
void QSGAbstractRenderer_ChildEventDefault(void* ptr, void* event);
void QSGAbstractRenderer_ConnectNotifyDefault(void* ptr, void* sign);
void QSGAbstractRenderer_CustomEventDefault(void* ptr, void* event);
void QSGAbstractRenderer_DeleteLaterDefault(void* ptr);
void QSGAbstractRenderer_DisconnectNotifyDefault(void* ptr, void* sign);
void QSGAbstractRenderer_TimerEventDefault(void* ptr, void* event);
void* QSGAbstractRenderer_MetaObjectDefault(void* ptr);
void* QSGBasicGeometryNode_Geometry2(void* ptr);
void QSGBasicGeometryNode_SetGeometry(void* ptr, void* geometry);
void QSGBasicGeometryNode_DestroyQSGBasicGeometryNode(void* ptr);
void* QSGBasicGeometryNode_Geometry(void* ptr);
void* QSGClipNode_NewQSGClipNode();
void QSGClipNode_SetClipRect(void* ptr, void* rect);
void QSGClipNode_SetIsRectangular(void* ptr, char rectHint);
void QSGClipNode_DestroyQSGClipNode(void* ptr);
void* QSGClipNode_ClipRect(void* ptr);
char QSGClipNode_IsRectangular(void* ptr);
char QSGDynamicTexture_UpdateTexture(void* ptr);
void QSGDynamicTexture_Bind(void* ptr);
void QSGDynamicTexture_BindDefault(void* ptr);
void* QSGDynamicTexture_TextureSize(void* ptr);
void* QSGDynamicTexture_TextureSizeDefault(void* ptr);
char QSGDynamicTexture_HasAlphaChannel(void* ptr);
char QSGDynamicTexture_HasAlphaChannelDefault(void* ptr);
char QSGDynamicTexture_HasMipmaps(void* ptr);
char QSGDynamicTexture_HasMipmapsDefault(void* ptr);
int QSGDynamicTexture_TextureId(void* ptr);
int QSGDynamicTexture_TextureIdDefault(void* ptr);
void* QSGEngine_NewQSGEngine(void* parent);
void QSGEngine_Initialize(void* ptr, void* context);
void QSGEngine_Invalidate(void* ptr);
void QSGEngine_DestroyQSGEngine(void* ptr);
void* QSGEngine_CreateRenderer(void* ptr);
void* QSGEngine_CreateImageNode(void* ptr);
void* QSGEngine_CreateRectangleNode(void* ptr);
void* QSGEngine_RendererInterface(void* ptr);
void* QSGEngine_CreateTextureFromId(void* ptr, unsigned int id, void* size, long long options);
void* QSGEngine_CreateTextureFromImage(void* ptr, void* image, long long options);
void* QSGEngine___dynamicPropertyNames_atList(void* ptr, int i);
void QSGEngine___dynamicPropertyNames_setList(void* ptr, void* i);
void* QSGEngine___dynamicPropertyNames_newList(void* ptr);
void* QSGEngine___findChildren_atList2(void* ptr, int i);
void QSGEngine___findChildren_setList2(void* ptr, void* i);
void* QSGEngine___findChildren_newList2(void* ptr);
void* QSGEngine___findChildren_atList3(void* ptr, int i);
void QSGEngine___findChildren_setList3(void* ptr, void* i);
void* QSGEngine___findChildren_newList3(void* ptr);
void* QSGEngine___findChildren_atList(void* ptr, int i);
void QSGEngine___findChildren_setList(void* ptr, void* i);
void* QSGEngine___findChildren_newList(void* ptr);
void* QSGEngine___children_atList(void* ptr, int i);
void QSGEngine___children_setList(void* ptr, void* i);
void* QSGEngine___children_newList(void* ptr);
char QSGEngine_EventDefault(void* ptr, void* e);
char QSGEngine_EventFilterDefault(void* ptr, void* watched, void* event);
void QSGEngine_ChildEventDefault(void* ptr, void* event);
void QSGEngine_ConnectNotifyDefault(void* ptr, void* sign);
void QSGEngine_CustomEventDefault(void* ptr, void* event);
void QSGEngine_DeleteLaterDefault(void* ptr);
void QSGEngine_DisconnectNotifyDefault(void* ptr, void* sign);
void QSGEngine_TimerEventDefault(void* ptr, void* event);
void* QSGEngine_MetaObjectDefault(void* ptr);
void* QSGFlatColorMaterial_NewQSGFlatColorMaterial();
void QSGFlatColorMaterial_SetColor(void* ptr, void* color);
void* QSGFlatColorMaterial_Color(void* ptr);
void* QSGFlatColorMaterial_CreateShader(void* ptr);
void* QSGFlatColorMaterial_CreateShaderDefault(void* ptr);
void* QSGFlatColorMaterial_Type(void* ptr);
void* QSGFlatColorMaterial_TypeDefault(void* ptr);
unsigned short QSGGeometry_IndexDataAsUShort(void* ptr);
unsigned int QSGGeometry_IndexDataAsUInt(void* ptr);
void* QSGGeometry_IndexData(void* ptr);
void* QSGGeometry_VertexData(void* ptr);
void QSGGeometry_Allocate(void* ptr, int vertexCount, int indexCount);
void QSGGeometry_MarkIndexDataDirty(void* ptr);
void QSGGeometry_MarkVertexDataDirty(void* ptr);
void QSGGeometry_SetDrawingMode(void* ptr, unsigned int mode);
void QSGGeometry_SetIndexDataPattern(void* ptr, long long p);
void QSGGeometry_SetLineWidth(void* ptr, float width);
void QSGGeometry_SetVertexDataPattern(void* ptr, long long p);
void QSGGeometry_QSGGeometry_UpdateColoredRectGeometry(void* g, void* rect);
void QSGGeometry_QSGGeometry_UpdateRectGeometry(void* g, void* rect);
void QSGGeometry_QSGGeometry_UpdateTexturedRectGeometry(void* g, void* rect, void* textureRect);
void QSGGeometry_DestroyQSGGeometry(void* ptr);
void QSGGeometry_DestroyQSGGeometryDefault(void* ptr);
long long QSGGeometry_IndexDataPattern(void* ptr);
long long QSGGeometry_VertexDataPattern(void* ptr);
unsigned short QSGGeometry_IndexDataAsUShort2(void* ptr);
unsigned int QSGGeometry_IndexDataAsUInt2(void* ptr);
void* QSGGeometry_IndexData2(void* ptr);
void* QSGGeometry_VertexData2(void* ptr);
float QSGGeometry_LineWidth(void* ptr);
int QSGGeometry_AttributeCount(void* ptr);
int QSGGeometry_IndexCount(void* ptr);
int QSGGeometry_IndexType(void* ptr);
int QSGGeometry_SizeOfIndex(void* ptr);
int QSGGeometry_SizeOfVertex(void* ptr);
int QSGGeometry_VertexCount(void* ptr);
unsigned int QSGGeometry_DrawingMode(void* ptr);
void* QSGGeometryNode_NewQSGGeometryNode();
void QSGGeometryNode_SetMaterial(void* ptr, void* material);
void QSGGeometryNode_SetOpaqueMaterial(void* ptr, void* material);
void QSGGeometryNode_DestroyQSGGeometryNode(void* ptr);
void* QSGGeometryNode_Material(void* ptr);
void* QSGGeometryNode_OpaqueMaterial(void* ptr);
void QSGImageNode_QSGImageNode_RebuildGeometry(void* g, void* texture, void* rect, void* sourceRect, long long texCoordMode);
void QSGImageNode_SetFiltering(void* ptr, long long filtering);
void QSGImageNode_SetMipmapFiltering(void* ptr, long long filtering);
void QSGImageNode_SetOwnsTexture(void* ptr, char owns);
void QSGImageNode_SetRect(void* ptr, void* rect);
void QSGImageNode_SetRect2(void* ptr, double x, double y, double w, double h);
void QSGImageNode_SetSourceRect(void* ptr, void* rect);
void QSGImageNode_SetSourceRect2(void* ptr, double x, double y, double w, double h);
void QSGImageNode_SetTexture(void* ptr, void* texture);
void QSGImageNode_SetTextureCoordinatesTransform(void* ptr, long long mode);
void QSGImageNode_DestroyQSGImageNode(void* ptr);
void QSGImageNode_DestroyQSGImageNodeDefault(void* ptr);
void* QSGImageNode_Rect(void* ptr);
void* QSGImageNode_SourceRect(void* ptr);
void* QSGImageNode_Texture(void* ptr);
long long QSGImageNode_Filtering(void* ptr);
long long QSGImageNode_MipmapFiltering(void* ptr);
long long QSGImageNode_TextureCoordinatesTransform(void* ptr);
char QSGImageNode_OwnsTexture(void* ptr);
void QSGMaterial_SetFlag(void* ptr, long long flags, char on);
long long QSGMaterial_Flags(void* ptr);
void* QSGMaterial_CreateShader(void* ptr);
void* QSGMaterial_Type(void* ptr);
int QSGMaterial_Compare(void* ptr, void* other);
int QSGMaterial_CompareDefault(void* ptr, void* other);
struct QtQuick_PackedString QSGMaterialShader_FragmentShader(void* ptr);
struct QtQuick_PackedString QSGMaterialShader_FragmentShaderDefault(void* ptr);
struct QtQuick_PackedString QSGMaterialShader_VertexShader(void* ptr);
struct QtQuick_PackedString QSGMaterialShader_VertexShaderDefault(void* ptr);
void* QSGMaterialShader_Program(void* ptr);
void QSGMaterialShader_Activate(void* ptr);
void QSGMaterialShader_ActivateDefault(void* ptr);
void QSGMaterialShader_Compile(void* ptr);
void QSGMaterialShader_CompileDefault(void* ptr);
void QSGMaterialShader_Deactivate(void* ptr);
void QSGMaterialShader_DeactivateDefault(void* ptr);
void QSGMaterialShader_Initialize(void* ptr);
void QSGMaterialShader_InitializeDefault(void* ptr);
void QSGMaterialShader_SetShaderSourceFile(void* ptr, long long ty, struct QtQuick_PackedString sourceFile);
void QSGMaterialShader_SetShaderSourceFiles(void* ptr, long long ty, struct QtQuick_PackedString sourceFiles);
void* QSGNode_NewQSGNode();
void QSGNode_AppendChildNode(void* ptr, void* node);
void QSGNode_InsertChildNodeAfter(void* ptr, void* node, void* after);
void QSGNode_InsertChildNodeBefore(void* ptr, void* node, void* before);
void QSGNode_MarkDirty(void* ptr, long long bits);
void QSGNode_PrependChildNode(void* ptr, void* node);
void QSGNode_Preprocess(void* ptr);
void QSGNode_PreprocessDefault(void* ptr);
void QSGNode_RemoveAllChildNodes(void* ptr);
void QSGNode_RemoveChildNode(void* ptr, void* node);
void QSGNode_SetFlag(void* ptr, long long fo, char enabled);
void QSGNode_SetFlags(void* ptr, long long fo, char enabled);
void QSGNode_DestroyQSGNode(void* ptr);
void QSGNode_DestroyQSGNodeDefault(void* ptr);
long long QSGNode_Flags(void* ptr);
long long QSGNode_Type(void* ptr);
void* QSGNode_ChildAtIndex(void* ptr, int i);
void* QSGNode_FirstChild(void* ptr);
void* QSGNode_LastChild(void* ptr);
void* QSGNode_NextSibling(void* ptr);
void* QSGNode_Parent(void* ptr);
void* QSGNode_PreviousSibling(void* ptr);
char QSGNode_IsSubtreeBlocked(void* ptr);
char QSGNode_IsSubtreeBlockedDefault(void* ptr);
int QSGNode_ChildCount(void* ptr);
void* QSGOpacityNode_NewQSGOpacityNode();
void QSGOpacityNode_SetOpacity(void* ptr, double opacity);
void QSGOpacityNode_DestroyQSGOpacityNode(void* ptr);
double QSGOpacityNode_Opacity(void* ptr);
void* QSGOpaqueTextureMaterial_NewQSGOpaqueTextureMaterial();
void QSGOpaqueTextureMaterial_SetAnisotropyLevel(void* ptr, long long level);
void QSGOpaqueTextureMaterial_SetFiltering(void* ptr, long long filtering);
void QSGOpaqueTextureMaterial_SetHorizontalWrapMode(void* ptr, long long mode);
void QSGOpaqueTextureMaterial_SetMipmapFiltering(void* ptr, long long filtering);
void QSGOpaqueTextureMaterial_SetTexture(void* ptr, void* texture);
void QSGOpaqueTextureMaterial_SetVerticalWrapMode(void* ptr, long long mode);
void* QSGOpaqueTextureMaterial_Texture(void* ptr);
long long QSGOpaqueTextureMaterial_AnisotropyLevel(void* ptr);
long long QSGOpaqueTextureMaterial_Filtering(void* ptr);
long long QSGOpaqueTextureMaterial_MipmapFiltering(void* ptr);
long long QSGOpaqueTextureMaterial_HorizontalWrapMode(void* ptr);
long long QSGOpaqueTextureMaterial_VerticalWrapMode(void* ptr);
void* QSGOpaqueTextureMaterial_M_texture(void* ptr);
void QSGOpaqueTextureMaterial_SetM_texture(void* ptr, void* vqs);
void* QSGOpaqueTextureMaterial_CreateShader(void* ptr);
void* QSGOpaqueTextureMaterial_CreateShaderDefault(void* ptr);
void* QSGOpaqueTextureMaterial_Type(void* ptr);
void* QSGOpaqueTextureMaterial_TypeDefault(void* ptr);
void QSGRectangleNode_SetColor(void* ptr, void* color);
void QSGRectangleNode_SetRect(void* ptr, void* rect);
void QSGRectangleNode_SetRect2(void* ptr, double x, double y, double w, double h);
void QSGRectangleNode_DestroyQSGRectangleNode(void* ptr);
void QSGRectangleNode_DestroyQSGRectangleNodeDefault(void* ptr);
void* QSGRectangleNode_Color(void* ptr);
void* QSGRectangleNode_Rect(void* ptr);
void QSGRenderNode_ReleaseResources(void* ptr);
void QSGRenderNode_ReleaseResourcesDefault(void* ptr);
void QSGRenderNode_DestroyQSGRenderNode(void* ptr);
void* QSGRenderNode_Rect(void* ptr);
void* QSGRenderNode_RectDefault(void* ptr);
long long QSGRenderNode_Flags(void* ptr);
long long QSGRenderNode_FlagsDefault(void* ptr);
long long QSGRenderNode_ChangedStates(void* ptr);
long long QSGRenderNode_ChangedStatesDefault(void* ptr);
void* QSGRenderNode_Matrix(void* ptr);
void* QSGRenderNode_ClipList(void* ptr);
double QSGRenderNode_InheritedOpacity(void* ptr);
void QSGRendererInterface_DestroyQSGRendererInterface(void* ptr);
void QSGRendererInterface_DestroyQSGRendererInterfaceDefault(void* ptr);
long long QSGRendererInterface_GraphicsApi(void* ptr);
long long QSGRendererInterface_ShaderCompilationType(void* ptr);
long long QSGRendererInterface_ShaderSourceType(void* ptr);
long long QSGRendererInterface_ShaderType(void* ptr);
void* QSGRendererInterface_GetResource(void* ptr, void* window, long long resource);
void* QSGRendererInterface_GetResourceDefault(void* ptr, void* window, long long resource);
void* QSGRendererInterface_GetResource2(void* ptr, void* window, char* resource);
void* QSGRendererInterface_GetResource2Default(void* ptr, void* window, char* resource);
void* QSGTexture_NewQSGTexture();
void QSGTexture_Bind(void* ptr);
void QSGTexture_SetAnisotropyLevel(void* ptr, long long level);
void QSGTexture_SetFiltering(void* ptr, long long filter);
void QSGTexture_SetHorizontalWrapMode(void* ptr, long long hwrap);
void QSGTexture_SetMipmapFiltering(void* ptr, long long filter);
void QSGTexture_SetVerticalWrapMode(void* ptr, long long vwrap);
void QSGTexture_UpdateBindOptions(void* ptr, char force);
void QSGTexture_DestroyQSGTexture(void* ptr);
void* QSGTexture_ConvertToNormalizedSourceRect(void* ptr, void* rect);
void* QSGTexture_NormalizedTextureSubRect(void* ptr);
void* QSGTexture_NormalizedTextureSubRectDefault(void* ptr);
void* QSGTexture_RemovedFromAtlas(void* ptr);
void* QSGTexture_RemovedFromAtlasDefault(void* ptr);
long long QSGTexture_AnisotropyLevel(void* ptr);
long long QSGTexture_Filtering(void* ptr);
long long QSGTexture_MipmapFiltering(void* ptr);
long long QSGTexture_HorizontalWrapMode(void* ptr);
long long QSGTexture_VerticalWrapMode(void* ptr);
void* QSGTexture_TextureSize(void* ptr);
char QSGTexture_HasAlphaChannel(void* ptr);
char QSGTexture_HasMipmaps(void* ptr);
char QSGTexture_IsAtlasTexture(void* ptr);
char QSGTexture_IsAtlasTextureDefault(void* ptr);
int QSGTexture_TextureId(void* ptr);
void* QSGTexture___dynamicPropertyNames_atList(void* ptr, int i);
void QSGTexture___dynamicPropertyNames_setList(void* ptr, void* i);
void* QSGTexture___dynamicPropertyNames_newList(void* ptr);
void* QSGTexture___findChildren_atList2(void* ptr, int i);
void QSGTexture___findChildren_setList2(void* ptr, void* i);
void* QSGTexture___findChildren_newList2(void* ptr);
void* QSGTexture___findChildren_atList3(void* ptr, int i);
void QSGTexture___findChildren_setList3(void* ptr, void* i);
void* QSGTexture___findChildren_newList3(void* ptr);
void* QSGTexture___findChildren_atList(void* ptr, int i);
void QSGTexture___findChildren_setList(void* ptr, void* i);
void* QSGTexture___findChildren_newList(void* ptr);
void* QSGTexture___children_atList(void* ptr, int i);
void QSGTexture___children_setList(void* ptr, void* i);
void* QSGTexture___children_newList(void* ptr);
char QSGTexture_EventDefault(void* ptr, void* e);
char QSGTexture_EventFilterDefault(void* ptr, void* watched, void* event);
void QSGTexture_ChildEventDefault(void* ptr, void* event);
void QSGTexture_ConnectNotifyDefault(void* ptr, void* sign);
void QSGTexture_CustomEventDefault(void* ptr, void* event);
void QSGTexture_DeleteLaterDefault(void* ptr);
void QSGTexture_DisconnectNotifyDefault(void* ptr, void* sign);
void QSGTexture_TimerEventDefault(void* ptr, void* event);
void* QSGTexture_MetaObjectDefault(void* ptr);
void QSGTextureProvider_ConnectTextureChanged(void* ptr);
void QSGTextureProvider_DisconnectTextureChanged(void* ptr);
void QSGTextureProvider_TextureChanged(void* ptr);
void* QSGTextureProvider_Texture(void* ptr);
void* QSGTextureProvider___dynamicPropertyNames_atList(void* ptr, int i);
void QSGTextureProvider___dynamicPropertyNames_setList(void* ptr, void* i);
void* QSGTextureProvider___dynamicPropertyNames_newList(void* ptr);
void* QSGTextureProvider___findChildren_atList2(void* ptr, int i);
void QSGTextureProvider___findChildren_setList2(void* ptr, void* i);
void* QSGTextureProvider___findChildren_newList2(void* ptr);
void* QSGTextureProvider___findChildren_atList3(void* ptr, int i);
void QSGTextureProvider___findChildren_setList3(void* ptr, void* i);
void* QSGTextureProvider___findChildren_newList3(void* ptr);
void* QSGTextureProvider___findChildren_atList(void* ptr, int i);
void QSGTextureProvider___findChildren_setList(void* ptr, void* i);
void* QSGTextureProvider___findChildren_newList(void* ptr);
void* QSGTextureProvider___children_atList(void* ptr, int i);
void QSGTextureProvider___children_setList(void* ptr, void* i);
void* QSGTextureProvider___children_newList(void* ptr);
char QSGTextureProvider_EventDefault(void* ptr, void* e);
char QSGTextureProvider_EventFilterDefault(void* ptr, void* watched, void* event);
void QSGTextureProvider_ChildEventDefault(void* ptr, void* event);
void QSGTextureProvider_ConnectNotifyDefault(void* ptr, void* sign);
void QSGTextureProvider_CustomEventDefault(void* ptr, void* event);
void QSGTextureProvider_DeleteLaterDefault(void* ptr);
void QSGTextureProvider_DisconnectNotifyDefault(void* ptr, void* sign);
void QSGTextureProvider_TimerEventDefault(void* ptr, void* event);
void* QSGTextureProvider_MetaObjectDefault(void* ptr);
void* QSGTransformNode_NewQSGTransformNode();
void QSGTransformNode_SetMatrix(void* ptr, void* matrix);
void QSGTransformNode_DestroyQSGTransformNode(void* ptr);
void* QSGTransformNode_Matrix(void* ptr);
void* QSGVertexColorMaterial_NewQSGVertexColorMaterial();
void* QSGVertexColorMaterial_CreateShader(void* ptr);
void* QSGVertexColorMaterial_CreateShaderDefault(void* ptr);
void* QSGVertexColorMaterial_Type(void* ptr);
void* QSGVertexColorMaterial_TypeDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif