// +build !minimal

#pragma once

#ifndef GO_QTPRINTSUPPORT_H
#define GO_QTPRINTSUPPORT_H

#include <stdint.h>

#ifdef __cplusplus
int QAbstractPrintDialog_QAbstractPrintDialog_QRegisterMetaType();
int QPageSetupDialog_QPageSetupDialog_QRegisterMetaType();
int QPrintDialog_QPrintDialog_QRegisterMetaType();
int QPrintPreviewDialog_QPrintPreviewDialog_QRegisterMetaType();
int QPrintPreviewWidget_QPrintPreviewWidget_QRegisterMetaType();
extern "C" {
#endif

struct QtPrintSupport_PackedString { char* data; long long len; };
struct QtPrintSupport_PackedList { void* data; long long len; };
void* QAbstractPrintDialog_NewQAbstractPrintDialog(void* printer, void* parent);
int QAbstractPrintDialog_Exec(void* ptr);
void QAbstractPrintDialog_SetFromTo(void* ptr, int from, int to);
void QAbstractPrintDialog_SetMinMax(void* ptr, int min, int max);
void QAbstractPrintDialog_SetOptionTabs(void* ptr, void* tabs);
void QAbstractPrintDialog_SetPrintRange(void* ptr, long long ran);
long long QAbstractPrintDialog_PrintRange(void* ptr);
void* QAbstractPrintDialog_Printer(void* ptr);
int QAbstractPrintDialog_FromPage(void* ptr);
int QAbstractPrintDialog_MaxPage(void* ptr);
int QAbstractPrintDialog_MinPage(void* ptr);
int QAbstractPrintDialog_ToPage(void* ptr);
void* QAbstractPrintDialog___setOptionTabs_tabs_atList(void* ptr, int i);
void QAbstractPrintDialog___setOptionTabs_tabs_setList(void* ptr, void* i);
void* QAbstractPrintDialog___setOptionTabs_tabs_newList(void* ptr);
void* QAbstractPrintDialog___addActions_actions_atList(void* ptr, int i);
void QAbstractPrintDialog___addActions_actions_setList(void* ptr, void* i);
void* QAbstractPrintDialog___addActions_actions_newList(void* ptr);
void* QAbstractPrintDialog___insertActions_actions_atList(void* ptr, int i);
void QAbstractPrintDialog___insertActions_actions_setList(void* ptr, void* i);
void* QAbstractPrintDialog___insertActions_actions_newList(void* ptr);
void* QAbstractPrintDialog___actions_atList(void* ptr, int i);
void QAbstractPrintDialog___actions_setList(void* ptr, void* i);
void* QAbstractPrintDialog___actions_newList(void* ptr);
void* QAbstractPrintDialog___dynamicPropertyNames_atList(void* ptr, int i);
void QAbstractPrintDialog___dynamicPropertyNames_setList(void* ptr, void* i);
void* QAbstractPrintDialog___dynamicPropertyNames_newList(void* ptr);
void* QAbstractPrintDialog___findChildren_atList2(void* ptr, int i);
void QAbstractPrintDialog___findChildren_setList2(void* ptr, void* i);
void* QAbstractPrintDialog___findChildren_newList2(void* ptr);
void* QAbstractPrintDialog___findChildren_atList3(void* ptr, int i);
void QAbstractPrintDialog___findChildren_setList3(void* ptr, void* i);
void* QAbstractPrintDialog___findChildren_newList3(void* ptr);
void* QAbstractPrintDialog___findChildren_atList(void* ptr, int i);
void QAbstractPrintDialog___findChildren_setList(void* ptr, void* i);
void* QAbstractPrintDialog___findChildren_newList(void* ptr);
void* QAbstractPrintDialog___children_atList(void* ptr, int i);
void QAbstractPrintDialog___children_setList(void* ptr, void* i);
void* QAbstractPrintDialog___children_newList(void* ptr);
char QAbstractPrintDialog_EventFilterDefault(void* ptr, void* o, void* e);
void QAbstractPrintDialog_AcceptDefault(void* ptr);
void QAbstractPrintDialog_CloseEventDefault(void* ptr, void* e);
void QAbstractPrintDialog_ContextMenuEventDefault(void* ptr, void* e);
void QAbstractPrintDialog_DoneDefault(void* ptr, int r);
void QAbstractPrintDialog_KeyPressEventDefault(void* ptr, void* e);
void QAbstractPrintDialog_OpenDefault(void* ptr);
void QAbstractPrintDialog_RejectDefault(void* ptr);
void QAbstractPrintDialog_ResizeEventDefault(void* ptr, void* vqr);
void QAbstractPrintDialog_SetVisibleDefault(void* ptr, char visible);
void QAbstractPrintDialog_ShowEventDefault(void* ptr, void* event);
void* QAbstractPrintDialog_MinimumSizeHintDefault(void* ptr);
void* QAbstractPrintDialog_SizeHintDefault(void* ptr);
char QAbstractPrintDialog_CloseDefault(void* ptr);
char QAbstractPrintDialog_EventDefault(void* ptr, void* event);
char QAbstractPrintDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QAbstractPrintDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QAbstractPrintDialog_ActionEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_ChangeEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragEnterEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragLeaveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragMoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DropEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_EnterEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_FocusInEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_FocusOutEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_HideDefault(void* ptr);
void QAbstractPrintDialog_HideEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_InputMethodEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_LeaveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_LowerDefault(void* ptr);
void QAbstractPrintDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MouseMoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MousePressEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MouseReleaseEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_PaintEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_RaiseDefault(void* ptr);
void QAbstractPrintDialog_RepaintDefault(void* ptr);
void QAbstractPrintDialog_SetDisabledDefault(void* ptr, char disable);
void QAbstractPrintDialog_SetEnabledDefault(void* ptr, char vbo);
void QAbstractPrintDialog_SetFocus2Default(void* ptr);
void QAbstractPrintDialog_SetHiddenDefault(void* ptr, char hidden);
void QAbstractPrintDialog_SetStyleSheetDefault(void* ptr, struct QtPrintSupport_PackedString styleSheet);
void QAbstractPrintDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QAbstractPrintDialog_SetWindowTitleDefault(void* ptr, struct QtPrintSupport_PackedString vqs);
void QAbstractPrintDialog_ShowDefault(void* ptr);
void QAbstractPrintDialog_ShowFullScreenDefault(void* ptr);
void QAbstractPrintDialog_ShowMaximizedDefault(void* ptr);
void QAbstractPrintDialog_ShowMinimizedDefault(void* ptr);
void QAbstractPrintDialog_ShowNormalDefault(void* ptr);
void QAbstractPrintDialog_TabletEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_UpdateDefault(void* ptr);
void QAbstractPrintDialog_UpdateMicroFocusDefault(void* ptr);
void QAbstractPrintDialog_WheelEventDefault(void* ptr, void* event);
void* QAbstractPrintDialog_PaintEngineDefault(void* ptr);
void* QAbstractPrintDialog_InputMethodQueryDefault(void* ptr, long long query);
char QAbstractPrintDialog_HasHeightForWidthDefault(void* ptr);
int QAbstractPrintDialog_HeightForWidthDefault(void* ptr, int w);
int QAbstractPrintDialog_MetricDefault(void* ptr, long long m);
void QAbstractPrintDialog_ChildEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QAbstractPrintDialog_CustomEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DeleteLaterDefault(void* ptr);
void QAbstractPrintDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void QAbstractPrintDialog_TimerEventDefault(void* ptr, void* event);
void* QAbstractPrintDialog_MetaObjectDefault(void* ptr);
void* QPageSetupDialog_NewQPageSetupDialog(void* printer, void* parent);
void* QPageSetupDialog_NewQPageSetupDialog2(void* parent);
void* QPageSetupDialog_Printer(void* ptr);
int QPageSetupDialog_Exec(void* ptr);
int QPageSetupDialog_ExecDefault(void* ptr);
void QPageSetupDialog_Done(void* ptr, int result);
void QPageSetupDialog_DoneDefault(void* ptr, int result);
void QPageSetupDialog_SetVisibleDefault(void* ptr, char visible);
void QPageSetupDialog_DestroyQPageSetupDialog(void* ptr);
void* QPageSetupDialog___addActions_actions_atList(void* ptr, int i);
void QPageSetupDialog___addActions_actions_setList(void* ptr, void* i);
void* QPageSetupDialog___addActions_actions_newList(void* ptr);
void* QPageSetupDialog___insertActions_actions_atList(void* ptr, int i);
void QPageSetupDialog___insertActions_actions_setList(void* ptr, void* i);
void* QPageSetupDialog___insertActions_actions_newList(void* ptr);
void* QPageSetupDialog___actions_atList(void* ptr, int i);
void QPageSetupDialog___actions_setList(void* ptr, void* i);
void* QPageSetupDialog___actions_newList(void* ptr);
void* QPageSetupDialog___dynamicPropertyNames_atList(void* ptr, int i);
void QPageSetupDialog___dynamicPropertyNames_setList(void* ptr, void* i);
void* QPageSetupDialog___dynamicPropertyNames_newList(void* ptr);
void* QPageSetupDialog___findChildren_atList2(void* ptr, int i);
void QPageSetupDialog___findChildren_setList2(void* ptr, void* i);
void* QPageSetupDialog___findChildren_newList2(void* ptr);
void* QPageSetupDialog___findChildren_atList3(void* ptr, int i);
void QPageSetupDialog___findChildren_setList3(void* ptr, void* i);
void* QPageSetupDialog___findChildren_newList3(void* ptr);
void* QPageSetupDialog___findChildren_atList(void* ptr, int i);
void QPageSetupDialog___findChildren_setList(void* ptr, void* i);
void* QPageSetupDialog___findChildren_newList(void* ptr);
void* QPageSetupDialog___children_atList(void* ptr, int i);
void QPageSetupDialog___children_setList(void* ptr, void* i);
void* QPageSetupDialog___children_newList(void* ptr);
char QPageSetupDialog_EventFilterDefault(void* ptr, void* o, void* e);
void QPageSetupDialog_AcceptDefault(void* ptr);
void QPageSetupDialog_CloseEventDefault(void* ptr, void* e);
void QPageSetupDialog_ContextMenuEventDefault(void* ptr, void* e);
void QPageSetupDialog_KeyPressEventDefault(void* ptr, void* e);
;
void QPageSetupDialog_RejectDefault(void* ptr);
void QPageSetupDialog_ResizeEventDefault(void* ptr, void* vqr);
void QPageSetupDialog_ShowEventDefault(void* ptr, void* event);
void* QPageSetupDialog_MinimumSizeHintDefault(void* ptr);
void* QPageSetupDialog_SizeHintDefault(void* ptr);
char QPageSetupDialog_CloseDefault(void* ptr);
char QPageSetupDialog_EventDefault(void* ptr, void* event);
char QPageSetupDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QPageSetupDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPageSetupDialog_ActionEventDefault(void* ptr, void* event);
void QPageSetupDialog_ChangeEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragEnterEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragLeaveEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragMoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_DropEventDefault(void* ptr, void* event);
void QPageSetupDialog_EnterEventDefault(void* ptr, void* event);
void QPageSetupDialog_FocusInEventDefault(void* ptr, void* event);
void QPageSetupDialog_FocusOutEventDefault(void* ptr, void* event);
void QPageSetupDialog_HideDefault(void* ptr);
void QPageSetupDialog_HideEventDefault(void* ptr, void* event);
void QPageSetupDialog_InputMethodEventDefault(void* ptr, void* event);
void QPageSetupDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QPageSetupDialog_LeaveEventDefault(void* ptr, void* event);
void QPageSetupDialog_LowerDefault(void* ptr);
void QPageSetupDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPageSetupDialog_MouseMoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_MousePressEventDefault(void* ptr, void* event);
void QPageSetupDialog_MouseReleaseEventDefault(void* ptr, void* event);
void QPageSetupDialog_MoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_PaintEventDefault(void* ptr, void* event);
void QPageSetupDialog_RaiseDefault(void* ptr);
void QPageSetupDialog_RepaintDefault(void* ptr);
void QPageSetupDialog_SetDisabledDefault(void* ptr, char disable);
void QPageSetupDialog_SetEnabledDefault(void* ptr, char vbo);
void QPageSetupDialog_SetFocus2Default(void* ptr);
void QPageSetupDialog_SetHiddenDefault(void* ptr, char hidden);
void QPageSetupDialog_SetStyleSheetDefault(void* ptr, struct QtPrintSupport_PackedString styleSheet);
void QPageSetupDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QPageSetupDialog_SetWindowTitleDefault(void* ptr, struct QtPrintSupport_PackedString vqs);
void QPageSetupDialog_ShowDefault(void* ptr);
void QPageSetupDialog_ShowFullScreenDefault(void* ptr);
void QPageSetupDialog_ShowMaximizedDefault(void* ptr);
void QPageSetupDialog_ShowMinimizedDefault(void* ptr);
void QPageSetupDialog_ShowNormalDefault(void* ptr);
void QPageSetupDialog_TabletEventDefault(void* ptr, void* event);
void QPageSetupDialog_UpdateDefault(void* ptr);
void QPageSetupDialog_UpdateMicroFocusDefault(void* ptr);
void QPageSetupDialog_WheelEventDefault(void* ptr, void* event);
void* QPageSetupDialog_PaintEngineDefault(void* ptr);
void* QPageSetupDialog_InputMethodQueryDefault(void* ptr, long long query);
char QPageSetupDialog_HasHeightForWidthDefault(void* ptr);
int QPageSetupDialog_HeightForWidthDefault(void* ptr, int w);
int QPageSetupDialog_MetricDefault(void* ptr, long long m);
void QPageSetupDialog_ChildEventDefault(void* ptr, void* event);
void QPageSetupDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QPageSetupDialog_CustomEventDefault(void* ptr, void* event);
void QPageSetupDialog_DeleteLaterDefault(void* ptr);
void QPageSetupDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void QPageSetupDialog_TimerEventDefault(void* ptr, void* event);
void* QPageSetupDialog_MetaObjectDefault(void* ptr);
void QPrintDialog_Done(void* ptr, int result);
void QPrintDialog_DoneDefault(void* ptr, int result);
void* QPrintDialog_NewQPrintDialog(void* printer, void* parent);
void* QPrintDialog_NewQPrintDialog2(void* parent);
int QPrintDialog_Exec(void* ptr);
int QPrintDialog_ExecDefault(void* ptr);
void QPrintDialog_ConnectAccepted(void* ptr);
void QPrintDialog_DisconnectAccepted(void* ptr);
void QPrintDialog_Accepted(void* ptr, void* printer);
void QPrintDialog_Open(void* ptr, void* receiver, char* member);
void QPrintDialog_SetOption(void* ptr, long long option, char on);
void QPrintDialog_SetOptions(void* ptr, long long options);
void QPrintDialog_DestroyQPrintDialog(void* ptr);
long long QPrintDialog_Options(void* ptr);
char QPrintDialog_TestOption(void* ptr, long long option);
char QPrintEngine_Abort(void* ptr);
char QPrintEngine_NewPage(void* ptr);
void QPrintEngine_SetProperty(void* ptr, long long key, void* value);
void QPrintEngine_DestroyQPrintEngine(void* ptr);
void QPrintEngine_DestroyQPrintEngineDefault(void* ptr);
long long QPrintEngine_PrinterState(void* ptr);
void* QPrintEngine_Property(void* ptr, long long key);
int QPrintEngine_Metric(void* ptr, long long id);
void* QPrintPreviewDialog_NewQPrintPreviewDialog(void* printer, void* parent, long long flags);
void* QPrintPreviewDialog_NewQPrintPreviewDialog2(void* parent, long long flags);
void* QPrintPreviewDialog_Printer(void* ptr);
void QPrintPreviewDialog_Done(void* ptr, int result);
void QPrintPreviewDialog_DoneDefault(void* ptr, int result);
void QPrintPreviewDialog_ConnectPaintRequested(void* ptr);
void QPrintPreviewDialog_DisconnectPaintRequested(void* ptr);
void QPrintPreviewDialog_PaintRequested(void* ptr, void* printer);
void QPrintPreviewDialog_SetVisibleDefault(void* ptr, char visible);
void QPrintPreviewDialog_DestroyQPrintPreviewDialog(void* ptr);
void* QPrintPreviewDialog___addActions_actions_atList(void* ptr, int i);
void QPrintPreviewDialog___addActions_actions_setList(void* ptr, void* i);
void* QPrintPreviewDialog___addActions_actions_newList(void* ptr);
void* QPrintPreviewDialog___insertActions_actions_atList(void* ptr, int i);
void QPrintPreviewDialog___insertActions_actions_setList(void* ptr, void* i);
void* QPrintPreviewDialog___insertActions_actions_newList(void* ptr);
void* QPrintPreviewDialog___actions_atList(void* ptr, int i);
void QPrintPreviewDialog___actions_setList(void* ptr, void* i);
void* QPrintPreviewDialog___actions_newList(void* ptr);
void* QPrintPreviewDialog___dynamicPropertyNames_atList(void* ptr, int i);
void QPrintPreviewDialog___dynamicPropertyNames_setList(void* ptr, void* i);
void* QPrintPreviewDialog___dynamicPropertyNames_newList(void* ptr);
void* QPrintPreviewDialog___findChildren_atList2(void* ptr, int i);
void QPrintPreviewDialog___findChildren_setList2(void* ptr, void* i);
void* QPrintPreviewDialog___findChildren_newList2(void* ptr);
void* QPrintPreviewDialog___findChildren_atList3(void* ptr, int i);
void QPrintPreviewDialog___findChildren_setList3(void* ptr, void* i);
void* QPrintPreviewDialog___findChildren_newList3(void* ptr);
void* QPrintPreviewDialog___findChildren_atList(void* ptr, int i);
void QPrintPreviewDialog___findChildren_setList(void* ptr, void* i);
void* QPrintPreviewDialog___findChildren_newList(void* ptr);
void* QPrintPreviewDialog___children_atList(void* ptr, int i);
void QPrintPreviewDialog___children_setList(void* ptr, void* i);
void* QPrintPreviewDialog___children_newList(void* ptr);
char QPrintPreviewDialog_EventFilterDefault(void* ptr, void* o, void* e);
int QPrintPreviewDialog_ExecDefault(void* ptr);
void QPrintPreviewDialog_AcceptDefault(void* ptr);
void QPrintPreviewDialog_CloseEventDefault(void* ptr, void* e);
void QPrintPreviewDialog_ContextMenuEventDefault(void* ptr, void* e);
void QPrintPreviewDialog_KeyPressEventDefault(void* ptr, void* e);
;
void QPrintPreviewDialog_RejectDefault(void* ptr);
void QPrintPreviewDialog_ResizeEventDefault(void* ptr, void* vqr);
void QPrintPreviewDialog_ShowEventDefault(void* ptr, void* event);
void* QPrintPreviewDialog_MinimumSizeHintDefault(void* ptr);
void* QPrintPreviewDialog_SizeHintDefault(void* ptr);
char QPrintPreviewDialog_CloseDefault(void* ptr);
char QPrintPreviewDialog_EventDefault(void* ptr, void* event);
char QPrintPreviewDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QPrintPreviewDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPrintPreviewDialog_ActionEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_ChangeEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragEnterEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragLeaveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragMoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DropEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_EnterEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_FocusInEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_FocusOutEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_HideDefault(void* ptr);
void QPrintPreviewDialog_HideEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_InputMethodEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_LeaveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_LowerDefault(void* ptr);
void QPrintPreviewDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MouseMoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MousePressEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MouseReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_PaintEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_RaiseDefault(void* ptr);
void QPrintPreviewDialog_RepaintDefault(void* ptr);
void QPrintPreviewDialog_SetDisabledDefault(void* ptr, char disable);
void QPrintPreviewDialog_SetEnabledDefault(void* ptr, char vbo);
void QPrintPreviewDialog_SetFocus2Default(void* ptr);
void QPrintPreviewDialog_SetHiddenDefault(void* ptr, char hidden);
void QPrintPreviewDialog_SetStyleSheetDefault(void* ptr, struct QtPrintSupport_PackedString styleSheet);
void QPrintPreviewDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QPrintPreviewDialog_SetWindowTitleDefault(void* ptr, struct QtPrintSupport_PackedString vqs);
void QPrintPreviewDialog_ShowDefault(void* ptr);
void QPrintPreviewDialog_ShowFullScreenDefault(void* ptr);
void QPrintPreviewDialog_ShowMaximizedDefault(void* ptr);
void QPrintPreviewDialog_ShowMinimizedDefault(void* ptr);
void QPrintPreviewDialog_ShowNormalDefault(void* ptr);
void QPrintPreviewDialog_TabletEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_UpdateDefault(void* ptr);
void QPrintPreviewDialog_UpdateMicroFocusDefault(void* ptr);
void QPrintPreviewDialog_WheelEventDefault(void* ptr, void* event);
void* QPrintPreviewDialog_PaintEngineDefault(void* ptr);
void* QPrintPreviewDialog_InputMethodQueryDefault(void* ptr, long long query);
char QPrintPreviewDialog_HasHeightForWidthDefault(void* ptr);
int QPrintPreviewDialog_HeightForWidthDefault(void* ptr, int w);
int QPrintPreviewDialog_MetricDefault(void* ptr, long long m);
void QPrintPreviewDialog_ChildEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewDialog_CustomEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DeleteLaterDefault(void* ptr);
void QPrintPreviewDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewDialog_TimerEventDefault(void* ptr, void* event);
void* QPrintPreviewDialog_MetaObjectDefault(void* ptr);
void* QPrintPreviewWidget_NewQPrintPreviewWidget(void* printer, void* parent, long long flags);
void* QPrintPreviewWidget_NewQPrintPreviewWidget2(void* parent, long long flags);
void QPrintPreviewWidget_FitInView(void* ptr);
void QPrintPreviewWidget_FitInViewDefault(void* ptr);
void QPrintPreviewWidget_FitToWidth(void* ptr);
void QPrintPreviewWidget_FitToWidthDefault(void* ptr);
void QPrintPreviewWidget_ConnectPaintRequested(void* ptr);
void QPrintPreviewWidget_DisconnectPaintRequested(void* ptr);
void QPrintPreviewWidget_PaintRequested(void* ptr, void* printer);
void QPrintPreviewWidget_ConnectPreviewChanged(void* ptr);
void QPrintPreviewWidget_DisconnectPreviewChanged(void* ptr);
void QPrintPreviewWidget_PreviewChanged(void* ptr);
void QPrintPreviewWidget_Print(void* ptr);
void QPrintPreviewWidget_PrintDefault(void* ptr);
void QPrintPreviewWidget_SetAllPagesViewMode(void* ptr);
void QPrintPreviewWidget_SetAllPagesViewModeDefault(void* ptr);
void QPrintPreviewWidget_SetCurrentPage(void* ptr, int page);
void QPrintPreviewWidget_SetCurrentPageDefault(void* ptr, int page);
void QPrintPreviewWidget_SetFacingPagesViewMode(void* ptr);
void QPrintPreviewWidget_SetFacingPagesViewModeDefault(void* ptr);
void QPrintPreviewWidget_SetLandscapeOrientation(void* ptr);
void QPrintPreviewWidget_SetLandscapeOrientationDefault(void* ptr);
void QPrintPreviewWidget_SetOrientation(void* ptr, long long orientation);
void QPrintPreviewWidget_SetOrientationDefault(void* ptr, long long orientation);
void QPrintPreviewWidget_SetPortraitOrientation(void* ptr);
void QPrintPreviewWidget_SetPortraitOrientationDefault(void* ptr);
void QPrintPreviewWidget_SetSinglePageViewMode(void* ptr);
void QPrintPreviewWidget_SetSinglePageViewModeDefault(void* ptr);
void QPrintPreviewWidget_SetViewMode(void* ptr, long long mode);
void QPrintPreviewWidget_SetViewModeDefault(void* ptr, long long mode);
void QPrintPreviewWidget_SetVisible(void* ptr, char visible);
void QPrintPreviewWidget_SetVisibleDefault(void* ptr, char visible);
void QPrintPreviewWidget_SetZoomFactor(void* ptr, double factor);
void QPrintPreviewWidget_SetZoomFactorDefault(void* ptr, double factor);
void QPrintPreviewWidget_SetZoomMode(void* ptr, long long zoomMode);
void QPrintPreviewWidget_SetZoomModeDefault(void* ptr, long long zoomMode);
void QPrintPreviewWidget_UpdatePreview(void* ptr);
void QPrintPreviewWidget_UpdatePreviewDefault(void* ptr);
void QPrintPreviewWidget_ZoomIn(void* ptr, double factor);
void QPrintPreviewWidget_ZoomInDefault(void* ptr, double factor);
void QPrintPreviewWidget_ZoomOut(void* ptr, double factor);
void QPrintPreviewWidget_ZoomOutDefault(void* ptr, double factor);
void QPrintPreviewWidget_DestroyQPrintPreviewWidget(void* ptr);
long long QPrintPreviewWidget_Orientation(void* ptr);
long long QPrintPreviewWidget_ViewMode(void* ptr);
long long QPrintPreviewWidget_ZoomMode(void* ptr);
int QPrintPreviewWidget_CurrentPage(void* ptr);
int QPrintPreviewWidget_PageCount(void* ptr);
double QPrintPreviewWidget_ZoomFactor(void* ptr);
void* QPrintPreviewWidget___addActions_actions_atList(void* ptr, int i);
void QPrintPreviewWidget___addActions_actions_setList(void* ptr, void* i);
void* QPrintPreviewWidget___addActions_actions_newList(void* ptr);
void* QPrintPreviewWidget___insertActions_actions_atList(void* ptr, int i);
void QPrintPreviewWidget___insertActions_actions_setList(void* ptr, void* i);
void* QPrintPreviewWidget___insertActions_actions_newList(void* ptr);
void* QPrintPreviewWidget___actions_atList(void* ptr, int i);
void QPrintPreviewWidget___actions_setList(void* ptr, void* i);
void* QPrintPreviewWidget___actions_newList(void* ptr);
void* QPrintPreviewWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QPrintPreviewWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QPrintPreviewWidget___dynamicPropertyNames_newList(void* ptr);
void* QPrintPreviewWidget___findChildren_atList2(void* ptr, int i);
void QPrintPreviewWidget___findChildren_setList2(void* ptr, void* i);
void* QPrintPreviewWidget___findChildren_newList2(void* ptr);
void* QPrintPreviewWidget___findChildren_atList3(void* ptr, int i);
void QPrintPreviewWidget___findChildren_setList3(void* ptr, void* i);
void* QPrintPreviewWidget___findChildren_newList3(void* ptr);
void* QPrintPreviewWidget___findChildren_atList(void* ptr, int i);
void QPrintPreviewWidget___findChildren_setList(void* ptr, void* i);
void* QPrintPreviewWidget___findChildren_newList(void* ptr);
void* QPrintPreviewWidget___children_atList(void* ptr, int i);
void QPrintPreviewWidget___children_setList(void* ptr, void* i);
void* QPrintPreviewWidget___children_newList(void* ptr);
char QPrintPreviewWidget_CloseDefault(void* ptr);
char QPrintPreviewWidget_EventDefault(void* ptr, void* event);
char QPrintPreviewWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QPrintPreviewWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPrintPreviewWidget_ActionEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ChangeEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_CloseEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ContextMenuEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragEnterEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragLeaveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragMoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DropEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_EnterEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_FocusInEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_FocusOutEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_HideDefault(void* ptr);
void QPrintPreviewWidget_HideEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_InputMethodEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_KeyPressEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_LeaveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_LowerDefault(void* ptr);
void QPrintPreviewWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MouseMoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MousePressEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MouseReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_PaintEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_RaiseDefault(void* ptr);
void QPrintPreviewWidget_RepaintDefault(void* ptr);
void QPrintPreviewWidget_ResizeEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_SetDisabledDefault(void* ptr, char disable);
void QPrintPreviewWidget_SetEnabledDefault(void* ptr, char vbo);
void QPrintPreviewWidget_SetFocus2Default(void* ptr);
void QPrintPreviewWidget_SetHiddenDefault(void* ptr, char hidden);
void QPrintPreviewWidget_SetStyleSheetDefault(void* ptr, struct QtPrintSupport_PackedString styleSheet);
void QPrintPreviewWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QPrintPreviewWidget_SetWindowTitleDefault(void* ptr, struct QtPrintSupport_PackedString vqs);
void QPrintPreviewWidget_ShowDefault(void* ptr);
void QPrintPreviewWidget_ShowEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ShowFullScreenDefault(void* ptr);
void QPrintPreviewWidget_ShowMaximizedDefault(void* ptr);
void QPrintPreviewWidget_ShowMinimizedDefault(void* ptr);
void QPrintPreviewWidget_ShowNormalDefault(void* ptr);
void QPrintPreviewWidget_TabletEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_UpdateDefault(void* ptr);
void QPrintPreviewWidget_UpdateMicroFocusDefault(void* ptr);
void QPrintPreviewWidget_WheelEventDefault(void* ptr, void* event);
void* QPrintPreviewWidget_PaintEngineDefault(void* ptr);
void* QPrintPreviewWidget_MinimumSizeHintDefault(void* ptr);
void* QPrintPreviewWidget_SizeHintDefault(void* ptr);
void* QPrintPreviewWidget_InputMethodQueryDefault(void* ptr, long long query);
char QPrintPreviewWidget_HasHeightForWidthDefault(void* ptr);
int QPrintPreviewWidget_HeightForWidthDefault(void* ptr, int w);
int QPrintPreviewWidget_MetricDefault(void* ptr, long long m);
char QPrintPreviewWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QPrintPreviewWidget_ChildEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewWidget_CustomEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DeleteLaterDefault(void* ptr);
void QPrintPreviewWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewWidget_TimerEventDefault(void* ptr, void* event);
void* QPrintPreviewWidget_MetaObjectDefault(void* ptr);
void* QPrinter_NewQPrinter(long long mode);
void* QPrinter_NewQPrinter2(void* printer, long long mode);
char QPrinter_Abort(void* ptr);
char QPrinter_NewPage(void* ptr);
char QPrinter_NewPageDefault(void* ptr);
void QPrinter_SetCollateCopies(void* ptr, char collate);
void QPrinter_SetColorMode(void* ptr, long long newColorMode);
void QPrinter_SetCopyCount(void* ptr, int count);
void QPrinter_SetCreator(void* ptr, struct QtPrintSupport_PackedString creator);
void QPrinter_SetDocName(void* ptr, struct QtPrintSupport_PackedString name);
void QPrinter_SetDuplex(void* ptr, long long duplex);
void QPrinter_SetEngines(void* ptr, void* printEngine, void* paintEngine);
void QPrinter_SetFontEmbeddingEnabled(void* ptr, char enable);
void QPrinter_SetFromTo(void* ptr, int from, int to);
void QPrinter_SetFullPage(void* ptr, char fp);
void QPrinter_SetOutputFileName(void* ptr, struct QtPrintSupport_PackedString fileName);
void QPrinter_SetOutputFormat(void* ptr, long long format);
void QPrinter_SetPageOrder(void* ptr, long long pageOrder);
void QPrinter_SetPaperSource(void* ptr, long long source);
void QPrinter_SetPrintProgram(void* ptr, struct QtPrintSupport_PackedString printProg);
void QPrinter_SetPrintRange(void* ptr, long long ran);
void QPrinter_SetPrinterName(void* ptr, struct QtPrintSupport_PackedString name);
void QPrinter_SetPrinterSelectionOption(void* ptr, struct QtPrintSupport_PackedString option);
void QPrinter_SetResolution(void* ptr, int dpi);
void QPrinter_DestroyQPrinter(void* ptr);
long long QPrinter_ColorMode(void* ptr);
long long QPrinter_Duplex(void* ptr);
long long QPrinter_OutputFormat(void* ptr);
long long QPrinter_PageOrder(void* ptr);
long long QPrinter_PaperSource(void* ptr);
long long QPrinter_PrintRange(void* ptr);
long long QPrinter_PrinterState(void* ptr);
struct QtPrintSupport_PackedList QPrinter_SupportedResolutions(void* ptr);
void* QPrinter_PaintEngine(void* ptr);
void* QPrinter_PaintEngineDefault(void* ptr);
void* QPrinter_PrintEngine(void* ptr);
void* QPrinter_PageRect(void* ptr, long long unit);
void* QPrinter_PaperRect(void* ptr, long long unit);
struct QtPrintSupport_PackedString QPrinter_Creator(void* ptr);
struct QtPrintSupport_PackedString QPrinter_DocName(void* ptr);
struct QtPrintSupport_PackedString QPrinter_OutputFileName(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrintProgram(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrinterName(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrinterSelectionOption(void* ptr);
char QPrinter_CollateCopies(void* ptr);
char QPrinter_FontEmbeddingEnabled(void* ptr);
char QPrinter_FullPage(void* ptr);
char QPrinter_IsValid(void* ptr);
char QPrinter_SupportsMultipleCopies(void* ptr);
int QPrinter_CopyCount(void* ptr);
int QPrinter_FromPage(void* ptr);
int QPrinter_Resolution(void* ptr);
int QPrinter_ToPage(void* ptr);
int QPrinter___supportedResolutions_atList(void* ptr, int i);
void QPrinter___supportedResolutions_setList(void* ptr, int i);
void* QPrinter___supportedResolutions_newList(void* ptr);
void QPrinter_SetPageSize2Default(void* ptr, long long size);
void QPrinter_SetPageSizeMMDefault(void* ptr, void* size);
int QPrinter_MetricDefault(void* ptr, long long metric);
struct QtPrintSupport_PackedList QPrinterInfo_QPrinterInfo_AvailablePrinters();
void* QPrinterInfo_QPrinterInfo_DefaultPrinter();
void* QPrinterInfo_QPrinterInfo_PrinterInfo(struct QtPrintSupport_PackedString printerName);
void* QPrinterInfo_NewQPrinterInfo();
void* QPrinterInfo_NewQPrinterInfo3(void* printer);
void* QPrinterInfo_NewQPrinterInfo2(void* other);
struct QtPrintSupport_PackedString QPrinterInfo_QPrinterInfo_DefaultPrinterName();
struct QtPrintSupport_PackedString QPrinterInfo_QPrinterInfo_AvailablePrinterNames();
void QPrinterInfo_DestroyQPrinterInfo(void* ptr);
struct QtPrintSupport_PackedList QPrinterInfo_SupportedPageSizes(void* ptr);
struct QtPrintSupport_PackedList QPrinterInfo_SupportedDuplexModes(void* ptr);
struct QtPrintSupport_PackedList QPrinterInfo_SupportedResolutions(void* ptr);
void* QPrinterInfo_DefaultPageSize(void* ptr);
void* QPrinterInfo_MaximumPhysicalPageSize(void* ptr);
void* QPrinterInfo_MinimumPhysicalPageSize(void* ptr);
long long QPrinterInfo_DefaultDuplexMode(void* ptr);
long long QPrinterInfo_State(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_Description(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_Location(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_MakeAndModel(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_PrinterName(void* ptr);
char QPrinterInfo_IsDefault(void* ptr);
char QPrinterInfo_IsNull(void* ptr);
char QPrinterInfo_IsRemote(void* ptr);
char QPrinterInfo_SupportsCustomPageSizes(void* ptr);
void* QPrinterInfo___availablePrinters_atList(void* ptr, int i);
void QPrinterInfo___availablePrinters_setList(void* ptr, void* i);
void* QPrinterInfo___availablePrinters_newList(void* ptr);
void* QPrinterInfo___supportedPageSizes_atList(void* ptr, int i);
void QPrinterInfo___supportedPageSizes_setList(void* ptr, void* i);
void* QPrinterInfo___supportedPageSizes_newList(void* ptr);
long long QPrinterInfo___supportedDuplexModes_atList(void* ptr, int i);
void QPrinterInfo___supportedDuplexModes_setList(void* ptr, long long i);
void* QPrinterInfo___supportedDuplexModes_newList(void* ptr);
void* QPrinterInfo___supportedPaperSizes_newList(void* ptr);
int QPrinterInfo___supportedResolutions_atList(void* ptr, int i);
void QPrinterInfo___supportedResolutions_setList(void* ptr, int i);
void* QPrinterInfo___supportedResolutions_newList(void* ptr);

#ifdef __cplusplus
}
#endif

#endif