// +build !minimal

#pragma once

#ifndef GO_QTPRINTSUPPORT_H
#define GO_QTPRINTSUPPORT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct QtPrintSupport_PackedString { char* data; long long len; };
struct QtPrintSupport_PackedList { void* data; long long len; };
void* QAbstractPrintDialog_NewQAbstractPrintDialog(void* printer, void* parent);
int QAbstractPrintDialog_Exec(void* ptr);
int QAbstractPrintDialog_FromPage(void* ptr);
int QAbstractPrintDialog_MaxPage(void* ptr);
int QAbstractPrintDialog_MinPage(void* ptr);
long long QAbstractPrintDialog_PrintRange(void* ptr);
void* QAbstractPrintDialog_Printer(void* ptr);
void QAbstractPrintDialog_SetFromTo(void* ptr, int from, int to);
void QAbstractPrintDialog_SetMinMax(void* ptr, int min, int max);
void QAbstractPrintDialog_SetPrintRange(void* ptr, long long ran);
int QAbstractPrintDialog_ToPage(void* ptr);
void QAbstractPrintDialog_Accept(void* ptr);
void QAbstractPrintDialog_AcceptDefault(void* ptr);
void QAbstractPrintDialog_CloseEvent(void* ptr, void* e);
void QAbstractPrintDialog_CloseEventDefault(void* ptr, void* e);
void QAbstractPrintDialog_ContextMenuEvent(void* ptr, void* e);
void QAbstractPrintDialog_ContextMenuEventDefault(void* ptr, void* e);
void QAbstractPrintDialog_Done(void* ptr, int r);
void QAbstractPrintDialog_DoneDefault(void* ptr, int r);
void QAbstractPrintDialog_KeyPressEvent(void* ptr, void* e);
void QAbstractPrintDialog_KeyPressEventDefault(void* ptr, void* e);
void* QAbstractPrintDialog_MinimumSizeHint(void* ptr);
void* QAbstractPrintDialog_MinimumSizeHintDefault(void* ptr);
void QAbstractPrintDialog_Open(void* ptr);
void QAbstractPrintDialog_OpenDefault(void* ptr);
void QAbstractPrintDialog_Reject(void* ptr);
void QAbstractPrintDialog_RejectDefault(void* ptr);
void QAbstractPrintDialog_ResizeEvent(void* ptr, void* vqr);
void QAbstractPrintDialog_ResizeEventDefault(void* ptr, void* vqr);
void QAbstractPrintDialog_SetVisible(void* ptr, char visible);
void QAbstractPrintDialog_SetVisibleDefault(void* ptr, char visible);
void QAbstractPrintDialog_ShowEvent(void* ptr, void* event);
void QAbstractPrintDialog_ShowEventDefault(void* ptr, void* event);
void* QAbstractPrintDialog_SizeHint(void* ptr);
void* QAbstractPrintDialog_SizeHintDefault(void* ptr);
void QAbstractPrintDialog_ActionEvent(void* ptr, void* event);
void QAbstractPrintDialog_ActionEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragEnterEvent(void* ptr, void* event);
void QAbstractPrintDialog_DragEnterEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragLeaveEvent(void* ptr, void* event);
void QAbstractPrintDialog_DragLeaveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DragMoveEvent(void* ptr, void* event);
void QAbstractPrintDialog_DragMoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DropEvent(void* ptr, void* event);
void QAbstractPrintDialog_DropEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_EnterEvent(void* ptr, void* event);
void QAbstractPrintDialog_EnterEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_FocusInEvent(void* ptr, void* event);
void QAbstractPrintDialog_FocusInEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_FocusOutEvent(void* ptr, void* event);
void QAbstractPrintDialog_FocusOutEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_HideEvent(void* ptr, void* event);
void QAbstractPrintDialog_HideEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_LeaveEvent(void* ptr, void* event);
void QAbstractPrintDialog_LeaveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MoveEvent(void* ptr, void* event);
void QAbstractPrintDialog_MoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_PaintEvent(void* ptr, void* event);
void QAbstractPrintDialog_PaintEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_SetEnabled(void* ptr, char vbo);
void QAbstractPrintDialog_SetEnabledDefault(void* ptr, char vbo);
void QAbstractPrintDialog_SetStyleSheet(void* ptr, char* styleSheet);
void QAbstractPrintDialog_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QAbstractPrintDialog_SetWindowModified(void* ptr, char vbo);
void QAbstractPrintDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QAbstractPrintDialog_SetWindowTitle(void* ptr, char* vqs);
void QAbstractPrintDialog_SetWindowTitleDefault(void* ptr, char* vqs);
void QAbstractPrintDialog_ChangeEvent(void* ptr, void* event);
void QAbstractPrintDialog_ChangeEventDefault(void* ptr, void* event);
char QAbstractPrintDialog_Close(void* ptr);
char QAbstractPrintDialog_CloseDefault(void* ptr);
char QAbstractPrintDialog_FocusNextPrevChild(void* ptr, char next);
char QAbstractPrintDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QAbstractPrintDialog_HasHeightForWidth(void* ptr);
char QAbstractPrintDialog_HasHeightForWidthDefault(void* ptr);
int QAbstractPrintDialog_HeightForWidth(void* ptr, int w);
int QAbstractPrintDialog_HeightForWidthDefault(void* ptr, int w);
void QAbstractPrintDialog_Hide(void* ptr);
void QAbstractPrintDialog_HideDefault(void* ptr);
void QAbstractPrintDialog_InputMethodEvent(void* ptr, void* event);
void QAbstractPrintDialog_InputMethodEventDefault(void* ptr, void* event);
void* QAbstractPrintDialog_InputMethodQuery(void* ptr, long long query);
void* QAbstractPrintDialog_InputMethodQueryDefault(void* ptr, long long query);
void QAbstractPrintDialog_KeyReleaseEvent(void* ptr, void* event);
void QAbstractPrintDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_Lower(void* ptr);
void QAbstractPrintDialog_LowerDefault(void* ptr);
void QAbstractPrintDialog_MouseDoubleClickEvent(void* ptr, void* event);
void QAbstractPrintDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MouseMoveEvent(void* ptr, void* event);
void QAbstractPrintDialog_MouseMoveEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MousePressEvent(void* ptr, void* event);
void QAbstractPrintDialog_MousePressEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_MouseReleaseEvent(void* ptr, void* event);
void QAbstractPrintDialog_MouseReleaseEventDefault(void* ptr, void* event);
char QAbstractPrintDialog_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QAbstractPrintDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QAbstractPrintDialog_Raise(void* ptr);
void QAbstractPrintDialog_RaiseDefault(void* ptr);
void QAbstractPrintDialog_Repaint(void* ptr);
void QAbstractPrintDialog_RepaintDefault(void* ptr);
void QAbstractPrintDialog_SetDisabled(void* ptr, char disable);
void QAbstractPrintDialog_SetDisabledDefault(void* ptr, char disable);
void QAbstractPrintDialog_SetFocus2(void* ptr);
void QAbstractPrintDialog_SetFocus2Default(void* ptr);
void QAbstractPrintDialog_SetHidden(void* ptr, char hidden);
void QAbstractPrintDialog_SetHiddenDefault(void* ptr, char hidden);
void QAbstractPrintDialog_Show(void* ptr);
void QAbstractPrintDialog_ShowDefault(void* ptr);
void QAbstractPrintDialog_ShowFullScreen(void* ptr);
void QAbstractPrintDialog_ShowFullScreenDefault(void* ptr);
void QAbstractPrintDialog_ShowMaximized(void* ptr);
void QAbstractPrintDialog_ShowMaximizedDefault(void* ptr);
void QAbstractPrintDialog_ShowMinimized(void* ptr);
void QAbstractPrintDialog_ShowMinimizedDefault(void* ptr);
void QAbstractPrintDialog_ShowNormal(void* ptr);
void QAbstractPrintDialog_ShowNormalDefault(void* ptr);
void QAbstractPrintDialog_TabletEvent(void* ptr, void* event);
void QAbstractPrintDialog_TabletEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_Update(void* ptr);
void QAbstractPrintDialog_UpdateDefault(void* ptr);
void QAbstractPrintDialog_UpdateMicroFocus(void* ptr);
void QAbstractPrintDialog_UpdateMicroFocusDefault(void* ptr);
void QAbstractPrintDialog_WheelEvent(void* ptr, void* event);
void QAbstractPrintDialog_WheelEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_TimerEvent(void* ptr, void* event);
void QAbstractPrintDialog_TimerEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_ChildEvent(void* ptr, void* event);
void QAbstractPrintDialog_ChildEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_ConnectNotify(void* ptr, void* sign);
void QAbstractPrintDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QAbstractPrintDialog_CustomEvent(void* ptr, void* event);
void QAbstractPrintDialog_CustomEventDefault(void* ptr, void* event);
void QAbstractPrintDialog_DeleteLater(void* ptr);
void QAbstractPrintDialog_DeleteLaterDefault(void* ptr);
void QAbstractPrintDialog_DisconnectNotify(void* ptr, void* sign);
void QAbstractPrintDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void* QAbstractPrintDialog_MetaObject(void* ptr);
void* QAbstractPrintDialog_MetaObjectDefault(void* ptr);
void* QPageSetupDialog_Printer(void* ptr);
void QPageSetupDialog_DestroyQPageSetupDialog(void* ptr);
void QPageSetupDialog_Done(void* ptr, int result);
void QPageSetupDialog_Open(void* ptr, void* receiver, char* member);
void* QPageSetupDialog_NewQPageSetupDialog(void* printer, void* parent);
void* QPageSetupDialog_NewQPageSetupDialog2(void* parent);
int QPageSetupDialog_Exec(void* ptr);
void QPageSetupDialog_SetVisible(void* ptr, char visible);
void QPageSetupDialog_Accept(void* ptr);
void QPageSetupDialog_AcceptDefault(void* ptr);
void QPageSetupDialog_CloseEvent(void* ptr, void* e);
void QPageSetupDialog_CloseEventDefault(void* ptr, void* e);
void QPageSetupDialog_ContextMenuEvent(void* ptr, void* e);
void QPageSetupDialog_ContextMenuEventDefault(void* ptr, void* e);
void QPageSetupDialog_KeyPressEvent(void* ptr, void* e);
void QPageSetupDialog_KeyPressEventDefault(void* ptr, void* e);
void* QPageSetupDialog_MinimumSizeHint(void* ptr);
void* QPageSetupDialog_MinimumSizeHintDefault(void* ptr);
void QPageSetupDialog_Reject(void* ptr);
void QPageSetupDialog_RejectDefault(void* ptr);
void QPageSetupDialog_ResizeEvent(void* ptr, void* vqr);
void QPageSetupDialog_ResizeEventDefault(void* ptr, void* vqr);
void QPageSetupDialog_ShowEvent(void* ptr, void* event);
void QPageSetupDialog_ShowEventDefault(void* ptr, void* event);
void* QPageSetupDialog_SizeHint(void* ptr);
void* QPageSetupDialog_SizeHintDefault(void* ptr);
void QPageSetupDialog_ActionEvent(void* ptr, void* event);
void QPageSetupDialog_ActionEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragEnterEvent(void* ptr, void* event);
void QPageSetupDialog_DragEnterEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragLeaveEvent(void* ptr, void* event);
void QPageSetupDialog_DragLeaveEventDefault(void* ptr, void* event);
void QPageSetupDialog_DragMoveEvent(void* ptr, void* event);
void QPageSetupDialog_DragMoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_DropEvent(void* ptr, void* event);
void QPageSetupDialog_DropEventDefault(void* ptr, void* event);
void QPageSetupDialog_EnterEvent(void* ptr, void* event);
void QPageSetupDialog_EnterEventDefault(void* ptr, void* event);
void QPageSetupDialog_FocusInEvent(void* ptr, void* event);
void QPageSetupDialog_FocusInEventDefault(void* ptr, void* event);
void QPageSetupDialog_FocusOutEvent(void* ptr, void* event);
void QPageSetupDialog_FocusOutEventDefault(void* ptr, void* event);
void QPageSetupDialog_HideEvent(void* ptr, void* event);
void QPageSetupDialog_HideEventDefault(void* ptr, void* event);
void QPageSetupDialog_LeaveEvent(void* ptr, void* event);
void QPageSetupDialog_LeaveEventDefault(void* ptr, void* event);
void QPageSetupDialog_MoveEvent(void* ptr, void* event);
void QPageSetupDialog_MoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_PaintEvent(void* ptr, void* event);
void QPageSetupDialog_PaintEventDefault(void* ptr, void* event);
void QPageSetupDialog_SetEnabled(void* ptr, char vbo);
void QPageSetupDialog_SetEnabledDefault(void* ptr, char vbo);
void QPageSetupDialog_SetStyleSheet(void* ptr, char* styleSheet);
void QPageSetupDialog_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QPageSetupDialog_SetWindowModified(void* ptr, char vbo);
void QPageSetupDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QPageSetupDialog_SetWindowTitle(void* ptr, char* vqs);
void QPageSetupDialog_SetWindowTitleDefault(void* ptr, char* vqs);
void QPageSetupDialog_ChangeEvent(void* ptr, void* event);
void QPageSetupDialog_ChangeEventDefault(void* ptr, void* event);
char QPageSetupDialog_Close(void* ptr);
char QPageSetupDialog_CloseDefault(void* ptr);
char QPageSetupDialog_FocusNextPrevChild(void* ptr, char next);
char QPageSetupDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QPageSetupDialog_HasHeightForWidth(void* ptr);
char QPageSetupDialog_HasHeightForWidthDefault(void* ptr);
int QPageSetupDialog_HeightForWidth(void* ptr, int w);
int QPageSetupDialog_HeightForWidthDefault(void* ptr, int w);
void QPageSetupDialog_Hide(void* ptr);
void QPageSetupDialog_HideDefault(void* ptr);
void QPageSetupDialog_InputMethodEvent(void* ptr, void* event);
void QPageSetupDialog_InputMethodEventDefault(void* ptr, void* event);
void* QPageSetupDialog_InputMethodQuery(void* ptr, long long query);
void* QPageSetupDialog_InputMethodQueryDefault(void* ptr, long long query);
void QPageSetupDialog_KeyReleaseEvent(void* ptr, void* event);
void QPageSetupDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QPageSetupDialog_Lower(void* ptr);
void QPageSetupDialog_LowerDefault(void* ptr);
void QPageSetupDialog_MouseDoubleClickEvent(void* ptr, void* event);
void QPageSetupDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPageSetupDialog_MouseMoveEvent(void* ptr, void* event);
void QPageSetupDialog_MouseMoveEventDefault(void* ptr, void* event);
void QPageSetupDialog_MousePressEvent(void* ptr, void* event);
void QPageSetupDialog_MousePressEventDefault(void* ptr, void* event);
void QPageSetupDialog_MouseReleaseEvent(void* ptr, void* event);
void QPageSetupDialog_MouseReleaseEventDefault(void* ptr, void* event);
char QPageSetupDialog_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QPageSetupDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPageSetupDialog_Raise(void* ptr);
void QPageSetupDialog_RaiseDefault(void* ptr);
void QPageSetupDialog_Repaint(void* ptr);
void QPageSetupDialog_RepaintDefault(void* ptr);
void QPageSetupDialog_SetDisabled(void* ptr, char disable);
void QPageSetupDialog_SetDisabledDefault(void* ptr, char disable);
void QPageSetupDialog_SetFocus2(void* ptr);
void QPageSetupDialog_SetFocus2Default(void* ptr);
void QPageSetupDialog_SetHidden(void* ptr, char hidden);
void QPageSetupDialog_SetHiddenDefault(void* ptr, char hidden);
void QPageSetupDialog_Show(void* ptr);
void QPageSetupDialog_ShowDefault(void* ptr);
void QPageSetupDialog_ShowFullScreen(void* ptr);
void QPageSetupDialog_ShowFullScreenDefault(void* ptr);
void QPageSetupDialog_ShowMaximized(void* ptr);
void QPageSetupDialog_ShowMaximizedDefault(void* ptr);
void QPageSetupDialog_ShowMinimized(void* ptr);
void QPageSetupDialog_ShowMinimizedDefault(void* ptr);
void QPageSetupDialog_ShowNormal(void* ptr);
void QPageSetupDialog_ShowNormalDefault(void* ptr);
void QPageSetupDialog_TabletEvent(void* ptr, void* event);
void QPageSetupDialog_TabletEventDefault(void* ptr, void* event);
void QPageSetupDialog_Update(void* ptr);
void QPageSetupDialog_UpdateDefault(void* ptr);
void QPageSetupDialog_UpdateMicroFocus(void* ptr);
void QPageSetupDialog_UpdateMicroFocusDefault(void* ptr);
void QPageSetupDialog_WheelEvent(void* ptr, void* event);
void QPageSetupDialog_WheelEventDefault(void* ptr, void* event);
void QPageSetupDialog_TimerEvent(void* ptr, void* event);
void QPageSetupDialog_TimerEventDefault(void* ptr, void* event);
void QPageSetupDialog_ChildEvent(void* ptr, void* event);
void QPageSetupDialog_ChildEventDefault(void* ptr, void* event);
void QPageSetupDialog_ConnectNotify(void* ptr, void* sign);
void QPageSetupDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QPageSetupDialog_CustomEvent(void* ptr, void* event);
void QPageSetupDialog_CustomEventDefault(void* ptr, void* event);
void QPageSetupDialog_DeleteLater(void* ptr);
void QPageSetupDialog_DeleteLaterDefault(void* ptr);
void QPageSetupDialog_DisconnectNotify(void* ptr, void* sign);
void QPageSetupDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void* QPageSetupDialog_MetaObject(void* ptr);
void* QPageSetupDialog_MetaObjectDefault(void* ptr);
long long QPrintDialog_Options(void* ptr);
void QPrintDialog_SetOptions(void* ptr, long long options);
void QPrintDialog_ConnectAccepted(void* ptr);
void QPrintDialog_DisconnectAccepted(void* ptr);
void QPrintDialog_Accepted(void* ptr, void* printer);
void QPrintDialog_Done(void* ptr, int result);
void QPrintDialog_Open(void* ptr, void* receiver, char* member);
void* QPrintDialog_Printer(void* ptr);
void QPrintDialog_SetOption(void* ptr, long long option, char on);
char QPrintDialog_TestOption(void* ptr, long long option);
void* QPrintDialog_NewQPrintDialog(void* printer, void* parent);
void* QPrintDialog_NewQPrintDialog2(void* parent);
int QPrintDialog_Exec(void* ptr);
int QPrintDialog_ExecDefault(void* ptr);
void QPrintDialog_SetVisible(void* ptr, char visible);
void QPrintDialog_DestroyQPrintDialog(void* ptr);
void QPrintDialog_Accept(void* ptr);
void QPrintDialog_AcceptDefault(void* ptr);
void QPrintDialog_CloseEvent(void* ptr, void* e);
void QPrintDialog_CloseEventDefault(void* ptr, void* e);
void QPrintDialog_ContextMenuEvent(void* ptr, void* e);
void QPrintDialog_ContextMenuEventDefault(void* ptr, void* e);
void QPrintDialog_KeyPressEvent(void* ptr, void* e);
void QPrintDialog_KeyPressEventDefault(void* ptr, void* e);
void* QPrintDialog_MinimumSizeHint(void* ptr);
void* QPrintDialog_MinimumSizeHintDefault(void* ptr);
void QPrintDialog_Reject(void* ptr);
void QPrintDialog_RejectDefault(void* ptr);
void QPrintDialog_ResizeEvent(void* ptr, void* vqr);
void QPrintDialog_ResizeEventDefault(void* ptr, void* vqr);
void QPrintDialog_ShowEvent(void* ptr, void* event);
void QPrintDialog_ShowEventDefault(void* ptr, void* event);
void* QPrintDialog_SizeHint(void* ptr);
void* QPrintDialog_SizeHintDefault(void* ptr);
void QPrintDialog_ActionEvent(void* ptr, void* event);
void QPrintDialog_ActionEventDefault(void* ptr, void* event);
void QPrintDialog_DragEnterEvent(void* ptr, void* event);
void QPrintDialog_DragEnterEventDefault(void* ptr, void* event);
void QPrintDialog_DragLeaveEvent(void* ptr, void* event);
void QPrintDialog_DragLeaveEventDefault(void* ptr, void* event);
void QPrintDialog_DragMoveEvent(void* ptr, void* event);
void QPrintDialog_DragMoveEventDefault(void* ptr, void* event);
void QPrintDialog_DropEvent(void* ptr, void* event);
void QPrintDialog_DropEventDefault(void* ptr, void* event);
void QPrintDialog_EnterEvent(void* ptr, void* event);
void QPrintDialog_EnterEventDefault(void* ptr, void* event);
void QPrintDialog_FocusInEvent(void* ptr, void* event);
void QPrintDialog_FocusInEventDefault(void* ptr, void* event);
void QPrintDialog_FocusOutEvent(void* ptr, void* event);
void QPrintDialog_FocusOutEventDefault(void* ptr, void* event);
void QPrintDialog_HideEvent(void* ptr, void* event);
void QPrintDialog_HideEventDefault(void* ptr, void* event);
void QPrintDialog_LeaveEvent(void* ptr, void* event);
void QPrintDialog_LeaveEventDefault(void* ptr, void* event);
void QPrintDialog_MoveEvent(void* ptr, void* event);
void QPrintDialog_MoveEventDefault(void* ptr, void* event);
void QPrintDialog_PaintEvent(void* ptr, void* event);
void QPrintDialog_PaintEventDefault(void* ptr, void* event);
void QPrintDialog_SetEnabled(void* ptr, char vbo);
void QPrintDialog_SetEnabledDefault(void* ptr, char vbo);
void QPrintDialog_SetStyleSheet(void* ptr, char* styleSheet);
void QPrintDialog_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QPrintDialog_SetWindowModified(void* ptr, char vbo);
void QPrintDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QPrintDialog_SetWindowTitle(void* ptr, char* vqs);
void QPrintDialog_SetWindowTitleDefault(void* ptr, char* vqs);
void QPrintDialog_ChangeEvent(void* ptr, void* event);
void QPrintDialog_ChangeEventDefault(void* ptr, void* event);
char QPrintDialog_Close(void* ptr);
char QPrintDialog_CloseDefault(void* ptr);
char QPrintDialog_FocusNextPrevChild(void* ptr, char next);
char QPrintDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QPrintDialog_HasHeightForWidth(void* ptr);
char QPrintDialog_HasHeightForWidthDefault(void* ptr);
int QPrintDialog_HeightForWidth(void* ptr, int w);
int QPrintDialog_HeightForWidthDefault(void* ptr, int w);
void QPrintDialog_Hide(void* ptr);
void QPrintDialog_HideDefault(void* ptr);
void QPrintDialog_InputMethodEvent(void* ptr, void* event);
void QPrintDialog_InputMethodEventDefault(void* ptr, void* event);
void* QPrintDialog_InputMethodQuery(void* ptr, long long query);
void* QPrintDialog_InputMethodQueryDefault(void* ptr, long long query);
void QPrintDialog_KeyReleaseEvent(void* ptr, void* event);
void QPrintDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QPrintDialog_Lower(void* ptr);
void QPrintDialog_LowerDefault(void* ptr);
void QPrintDialog_MouseDoubleClickEvent(void* ptr, void* event);
void QPrintDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPrintDialog_MouseMoveEvent(void* ptr, void* event);
void QPrintDialog_MouseMoveEventDefault(void* ptr, void* event);
void QPrintDialog_MousePressEvent(void* ptr, void* event);
void QPrintDialog_MousePressEventDefault(void* ptr, void* event);
void QPrintDialog_MouseReleaseEvent(void* ptr, void* event);
void QPrintDialog_MouseReleaseEventDefault(void* ptr, void* event);
char QPrintDialog_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QPrintDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPrintDialog_Raise(void* ptr);
void QPrintDialog_RaiseDefault(void* ptr);
void QPrintDialog_Repaint(void* ptr);
void QPrintDialog_RepaintDefault(void* ptr);
void QPrintDialog_SetDisabled(void* ptr, char disable);
void QPrintDialog_SetDisabledDefault(void* ptr, char disable);
void QPrintDialog_SetFocus2(void* ptr);
void QPrintDialog_SetFocus2Default(void* ptr);
void QPrintDialog_SetHidden(void* ptr, char hidden);
void QPrintDialog_SetHiddenDefault(void* ptr, char hidden);
void QPrintDialog_Show(void* ptr);
void QPrintDialog_ShowDefault(void* ptr);
void QPrintDialog_ShowFullScreen(void* ptr);
void QPrintDialog_ShowFullScreenDefault(void* ptr);
void QPrintDialog_ShowMaximized(void* ptr);
void QPrintDialog_ShowMaximizedDefault(void* ptr);
void QPrintDialog_ShowMinimized(void* ptr);
void QPrintDialog_ShowMinimizedDefault(void* ptr);
void QPrintDialog_ShowNormal(void* ptr);
void QPrintDialog_ShowNormalDefault(void* ptr);
void QPrintDialog_TabletEvent(void* ptr, void* event);
void QPrintDialog_TabletEventDefault(void* ptr, void* event);
void QPrintDialog_Update(void* ptr);
void QPrintDialog_UpdateDefault(void* ptr);
void QPrintDialog_UpdateMicroFocus(void* ptr);
void QPrintDialog_UpdateMicroFocusDefault(void* ptr);
void QPrintDialog_WheelEvent(void* ptr, void* event);
void QPrintDialog_WheelEventDefault(void* ptr, void* event);
void QPrintDialog_TimerEvent(void* ptr, void* event);
void QPrintDialog_TimerEventDefault(void* ptr, void* event);
void QPrintDialog_ChildEvent(void* ptr, void* event);
void QPrintDialog_ChildEventDefault(void* ptr, void* event);
void QPrintDialog_ConnectNotify(void* ptr, void* sign);
void QPrintDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QPrintDialog_CustomEvent(void* ptr, void* event);
void QPrintDialog_CustomEventDefault(void* ptr, void* event);
void QPrintDialog_DeleteLater(void* ptr);
void QPrintDialog_DeleteLaterDefault(void* ptr);
void QPrintDialog_DisconnectNotify(void* ptr, void* sign);
void QPrintDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void* QPrintDialog_MetaObject(void* ptr);
void* QPrintDialog_MetaObjectDefault(void* ptr);
char QPrintEngine_Abort(void* ptr);
int QPrintEngine_Metric(void* ptr, long long id);
char QPrintEngine_NewPage(void* ptr);
long long QPrintEngine_PrinterState(void* ptr);
void* QPrintEngine_Property(void* ptr, long long key);
void QPrintEngine_SetProperty(void* ptr, long long key, void* value);
void QPrintEngine_DestroyQPrintEngine(void* ptr);
void QPrintEngine_DestroyQPrintEngineDefault(void* ptr);
void* QPrintPreviewDialog_NewQPrintPreviewDialog2(void* parent, long long flags);
void* QPrintPreviewDialog_NewQPrintPreviewDialog(void* printer, void* parent, long long flags);
void QPrintPreviewDialog_Done(void* ptr, int result);
void QPrintPreviewDialog_Open(void* ptr, void* receiver, char* member);
void QPrintPreviewDialog_ConnectPaintRequested(void* ptr);
void QPrintPreviewDialog_DisconnectPaintRequested(void* ptr);
void QPrintPreviewDialog_PaintRequested(void* ptr, void* printer);
void* QPrintPreviewDialog_Printer(void* ptr);
void QPrintPreviewDialog_SetVisible(void* ptr, char visible);
void QPrintPreviewDialog_DestroyQPrintPreviewDialog(void* ptr);
void QPrintPreviewDialog_Accept(void* ptr);
void QPrintPreviewDialog_AcceptDefault(void* ptr);
void QPrintPreviewDialog_CloseEvent(void* ptr, void* e);
void QPrintPreviewDialog_CloseEventDefault(void* ptr, void* e);
void QPrintPreviewDialog_ContextMenuEvent(void* ptr, void* e);
void QPrintPreviewDialog_ContextMenuEventDefault(void* ptr, void* e);
int QPrintPreviewDialog_Exec(void* ptr);
int QPrintPreviewDialog_ExecDefault(void* ptr);
void QPrintPreviewDialog_KeyPressEvent(void* ptr, void* e);
void QPrintPreviewDialog_KeyPressEventDefault(void* ptr, void* e);
void* QPrintPreviewDialog_MinimumSizeHint(void* ptr);
void* QPrintPreviewDialog_MinimumSizeHintDefault(void* ptr);
void QPrintPreviewDialog_Reject(void* ptr);
void QPrintPreviewDialog_RejectDefault(void* ptr);
void QPrintPreviewDialog_ResizeEvent(void* ptr, void* vqr);
void QPrintPreviewDialog_ResizeEventDefault(void* ptr, void* vqr);
void QPrintPreviewDialog_ShowEvent(void* ptr, void* event);
void QPrintPreviewDialog_ShowEventDefault(void* ptr, void* event);
void* QPrintPreviewDialog_SizeHint(void* ptr);
void* QPrintPreviewDialog_SizeHintDefault(void* ptr);
void QPrintPreviewDialog_ActionEvent(void* ptr, void* event);
void QPrintPreviewDialog_ActionEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragEnterEvent(void* ptr, void* event);
void QPrintPreviewDialog_DragEnterEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragLeaveEvent(void* ptr, void* event);
void QPrintPreviewDialog_DragLeaveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DragMoveEvent(void* ptr, void* event);
void QPrintPreviewDialog_DragMoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DropEvent(void* ptr, void* event);
void QPrintPreviewDialog_DropEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_EnterEvent(void* ptr, void* event);
void QPrintPreviewDialog_EnterEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_FocusInEvent(void* ptr, void* event);
void QPrintPreviewDialog_FocusInEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_FocusOutEvent(void* ptr, void* event);
void QPrintPreviewDialog_FocusOutEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_HideEvent(void* ptr, void* event);
void QPrintPreviewDialog_HideEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_LeaveEvent(void* ptr, void* event);
void QPrintPreviewDialog_LeaveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MoveEvent(void* ptr, void* event);
void QPrintPreviewDialog_MoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_PaintEvent(void* ptr, void* event);
void QPrintPreviewDialog_PaintEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_SetEnabled(void* ptr, char vbo);
void QPrintPreviewDialog_SetEnabledDefault(void* ptr, char vbo);
void QPrintPreviewDialog_SetStyleSheet(void* ptr, char* styleSheet);
void QPrintPreviewDialog_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QPrintPreviewDialog_SetWindowModified(void* ptr, char vbo);
void QPrintPreviewDialog_SetWindowModifiedDefault(void* ptr, char vbo);
void QPrintPreviewDialog_SetWindowTitle(void* ptr, char* vqs);
void QPrintPreviewDialog_SetWindowTitleDefault(void* ptr, char* vqs);
void QPrintPreviewDialog_ChangeEvent(void* ptr, void* event);
void QPrintPreviewDialog_ChangeEventDefault(void* ptr, void* event);
char QPrintPreviewDialog_Close(void* ptr);
char QPrintPreviewDialog_CloseDefault(void* ptr);
char QPrintPreviewDialog_FocusNextPrevChild(void* ptr, char next);
char QPrintPreviewDialog_FocusNextPrevChildDefault(void* ptr, char next);
char QPrintPreviewDialog_HasHeightForWidth(void* ptr);
char QPrintPreviewDialog_HasHeightForWidthDefault(void* ptr);
int QPrintPreviewDialog_HeightForWidth(void* ptr, int w);
int QPrintPreviewDialog_HeightForWidthDefault(void* ptr, int w);
void QPrintPreviewDialog_Hide(void* ptr);
void QPrintPreviewDialog_HideDefault(void* ptr);
void QPrintPreviewDialog_InputMethodEvent(void* ptr, void* event);
void QPrintPreviewDialog_InputMethodEventDefault(void* ptr, void* event);
void* QPrintPreviewDialog_InputMethodQuery(void* ptr, long long query);
void* QPrintPreviewDialog_InputMethodQueryDefault(void* ptr, long long query);
void QPrintPreviewDialog_KeyReleaseEvent(void* ptr, void* event);
void QPrintPreviewDialog_KeyReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_Lower(void* ptr);
void QPrintPreviewDialog_LowerDefault(void* ptr);
void QPrintPreviewDialog_MouseDoubleClickEvent(void* ptr, void* event);
void QPrintPreviewDialog_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MouseMoveEvent(void* ptr, void* event);
void QPrintPreviewDialog_MouseMoveEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MousePressEvent(void* ptr, void* event);
void QPrintPreviewDialog_MousePressEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_MouseReleaseEvent(void* ptr, void* event);
void QPrintPreviewDialog_MouseReleaseEventDefault(void* ptr, void* event);
char QPrintPreviewDialog_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QPrintPreviewDialog_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPrintPreviewDialog_Raise(void* ptr);
void QPrintPreviewDialog_RaiseDefault(void* ptr);
void QPrintPreviewDialog_Repaint(void* ptr);
void QPrintPreviewDialog_RepaintDefault(void* ptr);
void QPrintPreviewDialog_SetDisabled(void* ptr, char disable);
void QPrintPreviewDialog_SetDisabledDefault(void* ptr, char disable);
void QPrintPreviewDialog_SetFocus2(void* ptr);
void QPrintPreviewDialog_SetFocus2Default(void* ptr);
void QPrintPreviewDialog_SetHidden(void* ptr, char hidden);
void QPrintPreviewDialog_SetHiddenDefault(void* ptr, char hidden);
void QPrintPreviewDialog_Show(void* ptr);
void QPrintPreviewDialog_ShowDefault(void* ptr);
void QPrintPreviewDialog_ShowFullScreen(void* ptr);
void QPrintPreviewDialog_ShowFullScreenDefault(void* ptr);
void QPrintPreviewDialog_ShowMaximized(void* ptr);
void QPrintPreviewDialog_ShowMaximizedDefault(void* ptr);
void QPrintPreviewDialog_ShowMinimized(void* ptr);
void QPrintPreviewDialog_ShowMinimizedDefault(void* ptr);
void QPrintPreviewDialog_ShowNormal(void* ptr);
void QPrintPreviewDialog_ShowNormalDefault(void* ptr);
void QPrintPreviewDialog_TabletEvent(void* ptr, void* event);
void QPrintPreviewDialog_TabletEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_Update(void* ptr);
void QPrintPreviewDialog_UpdateDefault(void* ptr);
void QPrintPreviewDialog_UpdateMicroFocus(void* ptr);
void QPrintPreviewDialog_UpdateMicroFocusDefault(void* ptr);
void QPrintPreviewDialog_WheelEvent(void* ptr, void* event);
void QPrintPreviewDialog_WheelEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_TimerEvent(void* ptr, void* event);
void QPrintPreviewDialog_TimerEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_ChildEvent(void* ptr, void* event);
void QPrintPreviewDialog_ChildEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_ConnectNotify(void* ptr, void* sign);
void QPrintPreviewDialog_ConnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewDialog_CustomEvent(void* ptr, void* event);
void QPrintPreviewDialog_CustomEventDefault(void* ptr, void* event);
void QPrintPreviewDialog_DeleteLater(void* ptr);
void QPrintPreviewDialog_DeleteLaterDefault(void* ptr);
void QPrintPreviewDialog_DisconnectNotify(void* ptr, void* sign);
void QPrintPreviewDialog_DisconnectNotifyDefault(void* ptr, void* sign);
void* QPrintPreviewDialog_MetaObject(void* ptr);
void* QPrintPreviewDialog_MetaObjectDefault(void* ptr);
void* QPrintPreviewWidget_NewQPrintPreviewWidget(void* printer, void* parent, long long flags);
void* QPrintPreviewWidget_NewQPrintPreviewWidget2(void* parent, long long flags);
int QPrintPreviewWidget_CurrentPage(void* ptr);
void QPrintPreviewWidget_FitInView(void* ptr);
void QPrintPreviewWidget_FitToWidth(void* ptr);
long long QPrintPreviewWidget_Orientation(void* ptr);
int QPrintPreviewWidget_PageCount(void* ptr);
void QPrintPreviewWidget_ConnectPaintRequested(void* ptr);
void QPrintPreviewWidget_DisconnectPaintRequested(void* ptr);
void QPrintPreviewWidget_PaintRequested(void* ptr, void* printer);
void QPrintPreviewWidget_ConnectPreviewChanged(void* ptr);
void QPrintPreviewWidget_DisconnectPreviewChanged(void* ptr);
void QPrintPreviewWidget_PreviewChanged(void* ptr);
void QPrintPreviewWidget_Print(void* ptr);
void QPrintPreviewWidget_SetAllPagesViewMode(void* ptr);
void QPrintPreviewWidget_SetCurrentPage(void* ptr, int page);
void QPrintPreviewWidget_SetFacingPagesViewMode(void* ptr);
void QPrintPreviewWidget_SetLandscapeOrientation(void* ptr);
void QPrintPreviewWidget_SetOrientation(void* ptr, long long orientation);
void QPrintPreviewWidget_SetPortraitOrientation(void* ptr);
void QPrintPreviewWidget_SetSinglePageViewMode(void* ptr);
void QPrintPreviewWidget_SetViewMode(void* ptr, long long mode);
void QPrintPreviewWidget_SetVisible(void* ptr, char visible);
void QPrintPreviewWidget_SetZoomFactor(void* ptr, double factor);
void QPrintPreviewWidget_SetZoomMode(void* ptr, long long zoomMode);
void QPrintPreviewWidget_UpdatePreview(void* ptr);
long long QPrintPreviewWidget_ViewMode(void* ptr);
double QPrintPreviewWidget_ZoomFactor(void* ptr);
void QPrintPreviewWidget_ZoomIn(void* ptr, double factor);
long long QPrintPreviewWidget_ZoomMode(void* ptr);
void QPrintPreviewWidget_ZoomOut(void* ptr, double factor);
void QPrintPreviewWidget_DestroyQPrintPreviewWidget(void* ptr);
void QPrintPreviewWidget_ActionEvent(void* ptr, void* event);
void QPrintPreviewWidget_ActionEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragEnterEvent(void* ptr, void* event);
void QPrintPreviewWidget_DragEnterEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragLeaveEvent(void* ptr, void* event);
void QPrintPreviewWidget_DragLeaveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DragMoveEvent(void* ptr, void* event);
void QPrintPreviewWidget_DragMoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DropEvent(void* ptr, void* event);
void QPrintPreviewWidget_DropEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_EnterEvent(void* ptr, void* event);
void QPrintPreviewWidget_EnterEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_FocusInEvent(void* ptr, void* event);
void QPrintPreviewWidget_FocusInEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_FocusOutEvent(void* ptr, void* event);
void QPrintPreviewWidget_FocusOutEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_HideEvent(void* ptr, void* event);
void QPrintPreviewWidget_HideEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_LeaveEvent(void* ptr, void* event);
void QPrintPreviewWidget_LeaveEventDefault(void* ptr, void* event);
void* QPrintPreviewWidget_MinimumSizeHint(void* ptr);
void* QPrintPreviewWidget_MinimumSizeHintDefault(void* ptr);
void QPrintPreviewWidget_MoveEvent(void* ptr, void* event);
void QPrintPreviewWidget_MoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_PaintEvent(void* ptr, void* event);
void QPrintPreviewWidget_PaintEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_SetEnabled(void* ptr, char vbo);
void QPrintPreviewWidget_SetEnabledDefault(void* ptr, char vbo);
void QPrintPreviewWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QPrintPreviewWidget_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QPrintPreviewWidget_SetWindowModified(void* ptr, char vbo);
void QPrintPreviewWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QPrintPreviewWidget_SetWindowTitle(void* ptr, char* vqs);
void QPrintPreviewWidget_SetWindowTitleDefault(void* ptr, char* vqs);
void QPrintPreviewWidget_ShowEvent(void* ptr, void* event);
void QPrintPreviewWidget_ShowEventDefault(void* ptr, void* event);
void* QPrintPreviewWidget_SizeHint(void* ptr);
void* QPrintPreviewWidget_SizeHintDefault(void* ptr);
void QPrintPreviewWidget_ChangeEvent(void* ptr, void* event);
void QPrintPreviewWidget_ChangeEventDefault(void* ptr, void* event);
char QPrintPreviewWidget_Close(void* ptr);
char QPrintPreviewWidget_CloseDefault(void* ptr);
void QPrintPreviewWidget_CloseEvent(void* ptr, void* event);
void QPrintPreviewWidget_CloseEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ContextMenuEvent(void* ptr, void* event);
void QPrintPreviewWidget_ContextMenuEventDefault(void* ptr, void* event);
char QPrintPreviewWidget_FocusNextPrevChild(void* ptr, char next);
char QPrintPreviewWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QPrintPreviewWidget_HasHeightForWidth(void* ptr);
char QPrintPreviewWidget_HasHeightForWidthDefault(void* ptr);
int QPrintPreviewWidget_HeightForWidth(void* ptr, int w);
int QPrintPreviewWidget_HeightForWidthDefault(void* ptr, int w);
void QPrintPreviewWidget_Hide(void* ptr);
void QPrintPreviewWidget_HideDefault(void* ptr);
void QPrintPreviewWidget_InputMethodEvent(void* ptr, void* event);
void QPrintPreviewWidget_InputMethodEventDefault(void* ptr, void* event);
void* QPrintPreviewWidget_InputMethodQuery(void* ptr, long long query);
void* QPrintPreviewWidget_InputMethodQueryDefault(void* ptr, long long query);
void QPrintPreviewWidget_KeyPressEvent(void* ptr, void* event);
void QPrintPreviewWidget_KeyPressEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_KeyReleaseEvent(void* ptr, void* event);
void QPrintPreviewWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_Lower(void* ptr);
void QPrintPreviewWidget_LowerDefault(void* ptr);
void QPrintPreviewWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QPrintPreviewWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MouseMoveEvent(void* ptr, void* event);
void QPrintPreviewWidget_MouseMoveEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MousePressEvent(void* ptr, void* event);
void QPrintPreviewWidget_MousePressEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_MouseReleaseEvent(void* ptr, void* event);
void QPrintPreviewWidget_MouseReleaseEventDefault(void* ptr, void* event);
char QPrintPreviewWidget_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QPrintPreviewWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QPrintPreviewWidget_Raise(void* ptr);
void QPrintPreviewWidget_RaiseDefault(void* ptr);
void QPrintPreviewWidget_Repaint(void* ptr);
void QPrintPreviewWidget_RepaintDefault(void* ptr);
void QPrintPreviewWidget_ResizeEvent(void* ptr, void* event);
void QPrintPreviewWidget_ResizeEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_SetDisabled(void* ptr, char disable);
void QPrintPreviewWidget_SetDisabledDefault(void* ptr, char disable);
void QPrintPreviewWidget_SetFocus2(void* ptr);
void QPrintPreviewWidget_SetFocus2Default(void* ptr);
void QPrintPreviewWidget_SetHidden(void* ptr, char hidden);
void QPrintPreviewWidget_SetHiddenDefault(void* ptr, char hidden);
void QPrintPreviewWidget_Show(void* ptr);
void QPrintPreviewWidget_ShowDefault(void* ptr);
void QPrintPreviewWidget_ShowFullScreen(void* ptr);
void QPrintPreviewWidget_ShowFullScreenDefault(void* ptr);
void QPrintPreviewWidget_ShowMaximized(void* ptr);
void QPrintPreviewWidget_ShowMaximizedDefault(void* ptr);
void QPrintPreviewWidget_ShowMinimized(void* ptr);
void QPrintPreviewWidget_ShowMinimizedDefault(void* ptr);
void QPrintPreviewWidget_ShowNormal(void* ptr);
void QPrintPreviewWidget_ShowNormalDefault(void* ptr);
void QPrintPreviewWidget_TabletEvent(void* ptr, void* event);
void QPrintPreviewWidget_TabletEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_Update(void* ptr);
void QPrintPreviewWidget_UpdateDefault(void* ptr);
void QPrintPreviewWidget_UpdateMicroFocus(void* ptr);
void QPrintPreviewWidget_UpdateMicroFocusDefault(void* ptr);
void QPrintPreviewWidget_WheelEvent(void* ptr, void* event);
void QPrintPreviewWidget_WheelEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_TimerEvent(void* ptr, void* event);
void QPrintPreviewWidget_TimerEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ChildEvent(void* ptr, void* event);
void QPrintPreviewWidget_ChildEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_ConnectNotify(void* ptr, void* sign);
void QPrintPreviewWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QPrintPreviewWidget_CustomEvent(void* ptr, void* event);
void QPrintPreviewWidget_CustomEventDefault(void* ptr, void* event);
void QPrintPreviewWidget_DeleteLater(void* ptr);
void QPrintPreviewWidget_DeleteLaterDefault(void* ptr);
void QPrintPreviewWidget_DisconnectNotify(void* ptr, void* sign);
void QPrintPreviewWidget_DisconnectNotifyDefault(void* ptr, void* sign);
char QPrintPreviewWidget_EventFilter(void* ptr, void* watched, void* event);
char QPrintPreviewWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void* QPrintPreviewWidget_MetaObject(void* ptr);
void* QPrintPreviewWidget_MetaObjectDefault(void* ptr);
int QPrinter_FromPage(void* ptr);
struct QtPrintSupport_PackedString QPrinter_OutputFileName(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrinterSelectionOption(void* ptr);
void QPrinter_SetPrinterSelectionOption(void* ptr, char* option);
void* QPrinter_NewQPrinter(long long mode);
void* QPrinter_NewQPrinter2(void* printer, long long mode);
char QPrinter_Abort(void* ptr);
char QPrinter_CollateCopies(void* ptr);
long long QPrinter_ColorMode(void* ptr);
int QPrinter_CopyCount(void* ptr);
struct QtPrintSupport_PackedString QPrinter_Creator(void* ptr);
struct QtPrintSupport_PackedString QPrinter_DocName(void* ptr);
long long QPrinter_Duplex(void* ptr);
char QPrinter_FontEmbeddingEnabled(void* ptr);
char QPrinter_FullPage(void* ptr);
char QPrinter_IsValid(void* ptr);
char QPrinter_NewPage(void* ptr);
long long QPrinter_OutputFormat(void* ptr);
void* QPrinter_PageLayout(void* ptr);
long long QPrinter_PageOrder(void* ptr);
void* QPrinter_PageRect(void* ptr, long long unit);
void* QPrinter_PaintEngine(void* ptr);
void* QPrinter_PaperRect(void* ptr, long long unit);
long long QPrinter_PaperSource(void* ptr);
void* QPrinter_PrintEngine(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrintProgram(void* ptr);
long long QPrinter_PrintRange(void* ptr);
struct QtPrintSupport_PackedString QPrinter_PrinterName(void* ptr);
long long QPrinter_PrinterState(void* ptr);
int QPrinter_Resolution(void* ptr);
void QPrinter_SetCollateCopies(void* ptr, char collate);
void QPrinter_SetColorMode(void* ptr, long long newColorMode);
void QPrinter_SetCopyCount(void* ptr, int count);
void QPrinter_SetCreator(void* ptr, char* creator);
void QPrinter_SetDocName(void* ptr, char* name);
void QPrinter_SetDuplex(void* ptr, long long duplex);
void QPrinter_SetEngines(void* ptr, void* printEngine, void* paintEngine);
void QPrinter_SetFontEmbeddingEnabled(void* ptr, char enable);
void QPrinter_SetFromTo(void* ptr, int from, int to);
void QPrinter_SetFullPage(void* ptr, char fp);
void QPrinter_SetOutputFileName(void* ptr, char* fileName);
void QPrinter_SetOutputFormat(void* ptr, long long format);
char QPrinter_SetPageLayout(void* ptr, void* newLayout);
char QPrinter_SetPageMargins(void* ptr, void* margins);
char QPrinter_SetPageMargins2(void* ptr, void* margins, long long units);
void QPrinter_SetPageOrder(void* ptr, long long pageOrder);
char QPrinter_SetPageOrientation(void* ptr, long long orientation);
char QPrinter_SetPageSize(void* ptr, void* pageSize);
void QPrinter_SetPaperSource(void* ptr, long long source);
void QPrinter_SetPrintProgram(void* ptr, char* printProg);
void QPrinter_SetPrintRange(void* ptr, long long ran);
void QPrinter_SetPrinterName(void* ptr, char* name);
void QPrinter_SetResolution(void* ptr, int dpi);
char QPrinter_SupportsMultipleCopies(void* ptr);
int QPrinter_ToPage(void* ptr);
void QPrinter_DestroyQPrinter(void* ptr);
void QPrinter_SetPageSize2(void* ptr, long long size);
void QPrinter_SetPageSize2Default(void* ptr, long long size);
void QPrinter_SetPageSizeMM(void* ptr, void* size);
void QPrinter_SetPageSizeMMDefault(void* ptr, void* size);
int QPrinter_Metric(void* ptr, long long metric);
int QPrinter_MetricDefault(void* ptr, long long metric);
void* QPrinterInfo_NewQPrinterInfo();
void* QPrinterInfo_NewQPrinterInfo3(void* printer);
void* QPrinterInfo_NewQPrinterInfo2(void* other);
struct QtPrintSupport_PackedString QPrinterInfo_QPrinterInfo_AvailablePrinterNames();
struct QtPrintSupport_PackedList QPrinterInfo_QPrinterInfo_AvailablePrinters();
long long QPrinterInfo_DefaultDuplexMode(void* ptr);
void* QPrinterInfo_DefaultPageSize(void* ptr);
void* QPrinterInfo_QPrinterInfo_DefaultPrinter();
struct QtPrintSupport_PackedString QPrinterInfo_QPrinterInfo_DefaultPrinterName();
struct QtPrintSupport_PackedString QPrinterInfo_Description(void* ptr);
char QPrinterInfo_IsDefault(void* ptr);
char QPrinterInfo_IsNull(void* ptr);
char QPrinterInfo_IsRemote(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_Location(void* ptr);
struct QtPrintSupport_PackedString QPrinterInfo_MakeAndModel(void* ptr);
void* QPrinterInfo_MaximumPhysicalPageSize(void* ptr);
void* QPrinterInfo_MinimumPhysicalPageSize(void* ptr);
void* QPrinterInfo_QPrinterInfo_PrinterInfo(char* printerName);
struct QtPrintSupport_PackedString QPrinterInfo_PrinterName(void* ptr);
long long QPrinterInfo_State(void* ptr);
struct QtPrintSupport_PackedList QPrinterInfo_SupportedPageSizes(void* ptr);
char QPrinterInfo_SupportsCustomPageSizes(void* ptr);
void QPrinterInfo_DestroyQPrinterInfo(void* ptr);
void* QPrinterInfo_availablePrinters_atList(void* ptr, int i);
void* QPrinterInfo_supportedPageSizes_atList(void* ptr, int i);

#ifdef __cplusplus
}
#endif

#endif