// +build !minimal

#pragma once

#ifndef GO_QTHELP_H
#define GO_QTHELP_H

#include <stdint.h>

#ifdef __cplusplus
int QHelpContentModel_QHelpContentModel_QRegisterMetaType();
int QHelpContentWidget_QHelpContentWidget_QRegisterMetaType();
int QHelpEngine_QHelpEngine_QRegisterMetaType();
int QHelpEngineCore_QHelpEngineCore_QRegisterMetaType();
int QHelpIndexModel_QHelpIndexModel_QRegisterMetaType();
int QHelpIndexWidget_QHelpIndexWidget_QRegisterMetaType();
int QHelpSearchEngine_QHelpSearchEngine_QRegisterMetaType();
int QHelpSearchQueryWidget_QHelpSearchQueryWidget_QRegisterMetaType();
int QHelpSearchResultWidget_QHelpSearchResultWidget_QRegisterMetaType();
extern "C" {
#endif

struct QtHelp_PackedString { char* data; long long len; };
struct QtHelp_PackedList { void* data; long long len; };
void QHelpContentItem_DestroyQHelpContentItem(void* ptr);
void* QHelpContentItem_Child(void* ptr, int row);
void* QHelpContentItem_Parent(void* ptr);
struct QtHelp_PackedString QHelpContentItem_Title(void* ptr);
void* QHelpContentItem_Url(void* ptr);
int QHelpContentItem_ChildCount(void* ptr);
int QHelpContentItem_ChildPosition(void* ptr, void* child);
int QHelpContentItem_Row(void* ptr);
void QHelpContentModel_ConnectContentsCreated(void* ptr);
void QHelpContentModel_DisconnectContentsCreated(void* ptr);
void QHelpContentModel_ContentsCreated(void* ptr);
void QHelpContentModel_ConnectContentsCreationStarted(void* ptr);
void QHelpContentModel_DisconnectContentsCreationStarted(void* ptr);
void QHelpContentModel_ContentsCreationStarted(void* ptr);
void QHelpContentModel_CreateContents(void* ptr, struct QtHelp_PackedString customFilterName);
void QHelpContentModel_DestroyQHelpContentModel(void* ptr);
void* QHelpContentModel_ContentItemAt(void* ptr, void* index);
void* QHelpContentModel_Index(void* ptr, int row, int column, void* parent);
void* QHelpContentModel_IndexDefault(void* ptr, int row, int column, void* parent);
void* QHelpContentModel_Parent(void* ptr, void* index);
void* QHelpContentModel_ParentDefault(void* ptr, void* index);
void* QHelpContentModel_Data(void* ptr, void* index, int role);
void* QHelpContentModel_DataDefault(void* ptr, void* index, int role);
char QHelpContentModel_IsCreatingContents(void* ptr);
int QHelpContentModel_ColumnCount(void* ptr, void* parent);
int QHelpContentModel_ColumnCountDefault(void* ptr, void* parent);
int QHelpContentModel_RowCount(void* ptr, void* parent);
int QHelpContentModel_RowCountDefault(void* ptr, void* parent);
void* QHelpContentModel___setItemData_roles_atList(void* ptr, int i);
void QHelpContentModel___setItemData_roles_setList(void* ptr, int key, void* i);
void* QHelpContentModel___setItemData_roles_newList(void* ptr);
struct QtHelp_PackedList QHelpContentModel___setItemData_keyList(void* ptr);
void* QHelpContentModel___changePersistentIndexList_from_atList(void* ptr, int i);
void QHelpContentModel___changePersistentIndexList_from_setList(void* ptr, void* i);
void* QHelpContentModel___changePersistentIndexList_from_newList(void* ptr);
void* QHelpContentModel___changePersistentIndexList_to_atList(void* ptr, int i);
void QHelpContentModel___changePersistentIndexList_to_setList(void* ptr, void* i);
void* QHelpContentModel___changePersistentIndexList_to_newList(void* ptr);
int QHelpContentModel___dataChanged_roles_atList(void* ptr, int i);
void QHelpContentModel___dataChanged_roles_setList(void* ptr, int i);
void* QHelpContentModel___dataChanged_roles_newList(void* ptr);
void* QHelpContentModel___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void QHelpContentModel___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* QHelpContentModel___layoutAboutToBeChanged_parents_newList(void* ptr);
void* QHelpContentModel___layoutChanged_parents_atList(void* ptr, int i);
void QHelpContentModel___layoutChanged_parents_setList(void* ptr, void* i);
void* QHelpContentModel___layoutChanged_parents_newList(void* ptr);
void* QHelpContentModel___roleNames_atList(void* ptr, int i);
void QHelpContentModel___roleNames_setList(void* ptr, int key, void* i);
void* QHelpContentModel___roleNames_newList(void* ptr);
struct QtHelp_PackedList QHelpContentModel___roleNames_keyList(void* ptr);
void* QHelpContentModel___itemData_atList(void* ptr, int i);
void QHelpContentModel___itemData_setList(void* ptr, int key, void* i);
void* QHelpContentModel___itemData_newList(void* ptr);
struct QtHelp_PackedList QHelpContentModel___itemData_keyList(void* ptr);
void* QHelpContentModel___mimeData_indexes_atList(void* ptr, int i);
void QHelpContentModel___mimeData_indexes_setList(void* ptr, void* i);
void* QHelpContentModel___mimeData_indexes_newList(void* ptr);
void* QHelpContentModel___match_atList(void* ptr, int i);
void QHelpContentModel___match_setList(void* ptr, void* i);
void* QHelpContentModel___match_newList(void* ptr);
void* QHelpContentModel___persistentIndexList_atList(void* ptr, int i);
void QHelpContentModel___persistentIndexList_setList(void* ptr, void* i);
void* QHelpContentModel___persistentIndexList_newList(void* ptr);
int QHelpContentModel_____setItemData_keyList_atList(void* ptr, int i);
void QHelpContentModel_____setItemData_keyList_setList(void* ptr, int i);
void* QHelpContentModel_____setItemData_keyList_newList(void* ptr);
int QHelpContentModel_____doSetRoleNames_keyList_atList(void* ptr, int i);
void QHelpContentModel_____doSetRoleNames_keyList_setList(void* ptr, int i);
void* QHelpContentModel_____doSetRoleNames_keyList_newList(void* ptr);
int QHelpContentModel_____setRoleNames_keyList_atList(void* ptr, int i);
void QHelpContentModel_____setRoleNames_keyList_setList(void* ptr, int i);
void* QHelpContentModel_____setRoleNames_keyList_newList(void* ptr);
int QHelpContentModel_____roleNames_keyList_atList(void* ptr, int i);
void QHelpContentModel_____roleNames_keyList_setList(void* ptr, int i);
void* QHelpContentModel_____roleNames_keyList_newList(void* ptr);
int QHelpContentModel_____itemData_keyList_atList(void* ptr, int i);
void QHelpContentModel_____itemData_keyList_setList(void* ptr, int i);
void* QHelpContentModel_____itemData_keyList_newList(void* ptr);
void* QHelpContentModel___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpContentModel___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpContentModel___dynamicPropertyNames_newList(void* ptr);
void* QHelpContentModel___findChildren_atList2(void* ptr, int i);
void QHelpContentModel___findChildren_setList2(void* ptr, void* i);
void* QHelpContentModel___findChildren_newList2(void* ptr);
void* QHelpContentModel___findChildren_atList3(void* ptr, int i);
void QHelpContentModel___findChildren_setList3(void* ptr, void* i);
void* QHelpContentModel___findChildren_newList3(void* ptr);
void* QHelpContentModel___findChildren_atList(void* ptr, int i);
void QHelpContentModel___findChildren_setList(void* ptr, void* i);
void* QHelpContentModel___findChildren_newList(void* ptr);
void* QHelpContentModel___children_atList(void* ptr, int i);
void QHelpContentModel___children_setList(void* ptr, void* i);
void* QHelpContentModel___children_newList(void* ptr);
char QHelpContentModel_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char QHelpContentModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char QHelpContentModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
char QHelpContentModel_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char QHelpContentModel_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
char QHelpContentModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char QHelpContentModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
char QHelpContentModel_SetDataDefault(void* ptr, void* index, void* value, int role);
char QHelpContentModel_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char QHelpContentModel_SetItemDataDefault(void* ptr, void* index, void* roles);
char QHelpContentModel_SubmitDefault(void* ptr);
void QHelpContentModel_FetchMoreDefault(void* ptr, void* parent);
void QHelpContentModel_ResetInternalDataDefault(void* ptr);
void QHelpContentModel_RevertDefault(void* ptr);
void QHelpContentModel_SortDefault(void* ptr, int column, long long order);
struct QtHelp_PackedList QHelpContentModel_RoleNamesDefault(void* ptr);
struct QtHelp_PackedList QHelpContentModel_ItemDataDefault(void* ptr, void* index);
void* QHelpContentModel_MimeDataDefault(void* ptr, void* indexes);
void* QHelpContentModel_BuddyDefault(void* ptr, void* index);
void* QHelpContentModel_SiblingDefault(void* ptr, int row, int column, void* index);
struct QtHelp_PackedList QHelpContentModel_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* QHelpContentModel_SpanDefault(void* ptr, void* index);
struct QtHelp_PackedString QHelpContentModel_MimeTypesDefault(void* ptr);
void* QHelpContentModel_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
long long QHelpContentModel_SupportedDragActionsDefault(void* ptr);
long long QHelpContentModel_SupportedDropActionsDefault(void* ptr);
long long QHelpContentModel_FlagsDefault(void* ptr, void* index);
char QHelpContentModel_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char QHelpContentModel_CanFetchMoreDefault(void* ptr, void* parent);
char QHelpContentModel_HasChildrenDefault(void* ptr, void* parent);
char QHelpContentModel_EventDefault(void* ptr, void* e);
char QHelpContentModel_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpContentModel_ChildEventDefault(void* ptr, void* event);
void QHelpContentModel_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpContentModel_CustomEventDefault(void* ptr, void* event);
void QHelpContentModel_DeleteLaterDefault(void* ptr);
void QHelpContentModel_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpContentModel_TimerEventDefault(void* ptr, void* event);
void* QHelpContentModel_MetaObjectDefault(void* ptr);
void* QHelpContentWidget_IndexOf(void* ptr, void* link);
void QHelpContentWidget_ConnectLinkActivated(void* ptr);
void QHelpContentWidget_DisconnectLinkActivated(void* ptr);
void QHelpContentWidget_LinkActivated(void* ptr, void* link);
int QHelpContentWidget___dataChanged_roles_atList(void* ptr, int i);
void QHelpContentWidget___dataChanged_roles_setList(void* ptr, int i);
void* QHelpContentWidget___dataChanged_roles_newList(void* ptr);
void* QHelpContentWidget___selectedIndexes_atList(void* ptr, int i);
void QHelpContentWidget___selectedIndexes_setList(void* ptr, void* i);
void* QHelpContentWidget___selectedIndexes_newList(void* ptr);
void* QHelpContentWidget___scrollBarWidgets_atList(void* ptr, int i);
void QHelpContentWidget___scrollBarWidgets_setList(void* ptr, void* i);
void* QHelpContentWidget___scrollBarWidgets_newList(void* ptr);
void* QHelpContentWidget___addActions_actions_atList(void* ptr, int i);
void QHelpContentWidget___addActions_actions_setList(void* ptr, void* i);
void* QHelpContentWidget___addActions_actions_newList(void* ptr);
void* QHelpContentWidget___insertActions_actions_atList(void* ptr, int i);
void QHelpContentWidget___insertActions_actions_setList(void* ptr, void* i);
void* QHelpContentWidget___insertActions_actions_newList(void* ptr);
void* QHelpContentWidget___actions_atList(void* ptr, int i);
void QHelpContentWidget___actions_setList(void* ptr, void* i);
void* QHelpContentWidget___actions_newList(void* ptr);
void* QHelpContentWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpContentWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpContentWidget___dynamicPropertyNames_newList(void* ptr);
void* QHelpContentWidget___findChildren_atList2(void* ptr, int i);
void QHelpContentWidget___findChildren_setList2(void* ptr, void* i);
void* QHelpContentWidget___findChildren_newList2(void* ptr);
void* QHelpContentWidget___findChildren_atList3(void* ptr, int i);
void QHelpContentWidget___findChildren_setList3(void* ptr, void* i);
void* QHelpContentWidget___findChildren_newList3(void* ptr);
void* QHelpContentWidget___findChildren_atList(void* ptr, int i);
void QHelpContentWidget___findChildren_setList(void* ptr, void* i);
void* QHelpContentWidget___findChildren_newList(void* ptr);
void* QHelpContentWidget___children_atList(void* ptr, int i);
void QHelpContentWidget___children_setList(void* ptr, void* i);
void* QHelpContentWidget___children_newList(void* ptr);
void* QHelpContentWidget_MoveCursorDefault(void* ptr, long long cursorAction, long long modifiers);
char QHelpContentWidget_ViewportEventDefault(void* ptr, void* event);
void QHelpContentWidget_CollapseDefault(void* ptr, void* index);
void QHelpContentWidget_CollapseAllDefault(void* ptr);
void QHelpContentWidget_ColumnCountChangedDefault(void* ptr, int oldCount, int newCount);
void QHelpContentWidget_ColumnMovedDefault(void* ptr);
void QHelpContentWidget_ColumnResizedDefault(void* ptr, int column, int oldSize, int newSize);
void QHelpContentWidget_CurrentChangedDefault(void* ptr, void* current, void* previous);
void QHelpContentWidget_DataChangedDefault(void* ptr, void* topLeft, void* bottomRight, void* roles);
void QHelpContentWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_ExpandDefault(void* ptr, void* index);
void QHelpContentWidget_ExpandAllDefault(void* ptr);
void QHelpContentWidget_ExpandToDepthDefault(void* ptr, int depth);
void QHelpContentWidget_HideColumnDefault(void* ptr, int column);
void QHelpContentWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpContentWidget_KeyboardSearchDefault(void* ptr, struct QtHelp_PackedString search);
void QHelpContentWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpContentWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpContentWidget_MouseReleaseEventDefault(void* ptr, void* event);
void QHelpContentWidget_PaintEventDefault(void* ptr, void* event);
void QHelpContentWidget_ResetDefault(void* ptr);
void QHelpContentWidget_ResizeColumnToContentsDefault(void* ptr, int column);
void QHelpContentWidget_RowsAboutToBeRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsInsertedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_ScrollContentsByDefault(void* ptr, int dx, int dy);
void QHelpContentWidget_ScrollToDefault(void* ptr, void* index, long long hint);
void QHelpContentWidget_SelectAllDefault(void* ptr);
void QHelpContentWidget_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void QHelpContentWidget_SetModelDefault(void* ptr, void* model);
void QHelpContentWidget_SetRootIndexDefault(void* ptr, void* index);
void QHelpContentWidget_SetSelectionDefault(void* ptr, void* rect, long long command);
void QHelpContentWidget_SetSelectionModelDefault(void* ptr, void* selectionModel);
void QHelpContentWidget_ShowColumnDefault(void* ptr, int column);
void QHelpContentWidget_TimerEventDefault(void* ptr, void* event);
void QHelpContentWidget_UpdateGeometriesDefault(void* ptr);
void* QHelpContentWidget_IndexAtDefault(void* ptr, void* point);
;
void* QHelpContentWidget_VisualRectDefault(void* ptr, void* index);
void* QHelpContentWidget_VisualRegionForSelectionDefault(void* ptr, void* selection);
void* QHelpContentWidget_ViewportSizeHintDefault(void* ptr);
char QHelpContentWidget_IsIndexHiddenDefault(void* ptr, void* index);
int QHelpContentWidget_HorizontalOffsetDefault(void* ptr);
int QHelpContentWidget_SizeHintForColumnDefault(void* ptr, int column);
int QHelpContentWidget_VerticalOffsetDefault(void* ptr);
void QHelpContentWidget_DrawBranchesDefault(void* ptr, void* painter, void* rect, void* index);
void QHelpContentWidget_DrawRowDefault(void* ptr, void* painter, void* option, void* index);
char QHelpContentWidget_Edit2Default(void* ptr, void* index, long long trigger, void* event);
char QHelpContentWidget_EventDefault(void* ptr, void* event);
char QHelpContentWidget_FocusNextPrevChildDefault(void* ptr, char next);
void QHelpContentWidget_ClearSelectionDefault(void* ptr);
void QHelpContentWidget_CloseEditorDefault(void* ptr, void* editor, long long hint);
void QHelpContentWidget_CommitDataDefault(void* ptr, void* editor);
void QHelpContentWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpContentWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpContentWidget_DropEventDefault(void* ptr, void* event);
void QHelpContentWidget_EditDefault(void* ptr, void* index);
void QHelpContentWidget_EditorDestroyedDefault(void* ptr, void* editor);
void QHelpContentWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpContentWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpContentWidget_InputMethodEventDefault(void* ptr, void* event);
void QHelpContentWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpContentWidget_ScrollToBottomDefault(void* ptr);
void QHelpContentWidget_ScrollToTopDefault(void* ptr);
void QHelpContentWidget_SetCurrentIndexDefault(void* ptr, void* index);
void QHelpContentWidget_StartDragDefault(void* ptr, long long supportedActions);
void QHelpContentWidget_UpdateDefault(void* ptr, void* index);
long long QHelpContentWidget_SelectionCommandDefault(void* ptr, void* index, void* event);
void* QHelpContentWidget_ViewOptionsDefault(void* ptr);
void* QHelpContentWidget_InputMethodQueryDefault(void* ptr, long long query);
int QHelpContentWidget_SizeHintForRowDefault(void* ptr, int row);
void QHelpContentWidget_ContextMenuEventDefault(void* ptr, void* e);
void QHelpContentWidget_SetupViewportDefault(void* ptr, void* viewport);
void QHelpContentWidget_WheelEventDefault(void* ptr, void* e);
void* QHelpContentWidget_MinimumSizeHintDefault(void* ptr);
void* QHelpContentWidget_SizeHintDefault(void* ptr);
void QHelpContentWidget_ChangeEventDefault(void* ptr, void* ev);
char QHelpContentWidget_CloseDefault(void* ptr);
char QHelpContentWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QHelpContentWidget_ActionEventDefault(void* ptr, void* event);
void QHelpContentWidget_CloseEventDefault(void* ptr, void* event);
void QHelpContentWidget_EnterEventDefault(void* ptr, void* event);
void QHelpContentWidget_HideDefault(void* ptr);
void QHelpContentWidget_HideEventDefault(void* ptr, void* event);
void QHelpContentWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpContentWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpContentWidget_LowerDefault(void* ptr);
void QHelpContentWidget_MoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_RaiseDefault(void* ptr);
void QHelpContentWidget_RepaintDefault(void* ptr);
void QHelpContentWidget_SetDisabledDefault(void* ptr, char disable);
void QHelpContentWidget_SetEnabledDefault(void* ptr, char vbo);
void QHelpContentWidget_SetFocus2Default(void* ptr);
void QHelpContentWidget_SetHiddenDefault(void* ptr, char hidden);
void QHelpContentWidget_SetStyleSheetDefault(void* ptr, struct QtHelp_PackedString styleSheet);
void QHelpContentWidget_SetVisibleDefault(void* ptr, char visible);
void QHelpContentWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QHelpContentWidget_SetWindowTitleDefault(void* ptr, struct QtHelp_PackedString vqs);
void QHelpContentWidget_ShowDefault(void* ptr);
void QHelpContentWidget_ShowEventDefault(void* ptr, void* event);
void QHelpContentWidget_ShowFullScreenDefault(void* ptr);
void QHelpContentWidget_ShowMaximizedDefault(void* ptr);
void QHelpContentWidget_ShowMinimizedDefault(void* ptr);
void QHelpContentWidget_ShowNormalDefault(void* ptr);
void QHelpContentWidget_TabletEventDefault(void* ptr, void* event);
void QHelpContentWidget_UpdateMicroFocusDefault(void* ptr);
void* QHelpContentWidget_PaintEngineDefault(void* ptr);
char QHelpContentWidget_HasHeightForWidthDefault(void* ptr);
int QHelpContentWidget_HeightForWidthDefault(void* ptr, int w);
int QHelpContentWidget_MetricDefault(void* ptr, long long m);
char QHelpContentWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpContentWidget_ChildEventDefault(void* ptr, void* event);
void QHelpContentWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpContentWidget_CustomEventDefault(void* ptr, void* event);
void QHelpContentWidget_DeleteLaterDefault(void* ptr);
void QHelpContentWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void* QHelpContentWidget_MetaObjectDefault(void* ptr);
void* QHelpEngine_ContentWidget(void* ptr);
void* QHelpEngine_NewQHelpEngine(struct QtHelp_PackedString collectionFile, void* parent);
void* QHelpEngine_IndexWidget(void* ptr);
void* QHelpEngine_SearchEngine(void* ptr);
void QHelpEngine_DestroyQHelpEngine(void* ptr);
void* QHelpEngine_ContentModel(void* ptr);
void* QHelpEngine_IndexModel(void* ptr);
void* QHelpEngineCore_NewQHelpEngineCore(struct QtHelp_PackedString collectionFile, void* parent);
struct QtHelp_PackedList QHelpEngineCore_Files(void* ptr, struct QtHelp_PackedString namespaceName, struct QtHelp_PackedString filterAttributes, struct QtHelp_PackedString extensionFilter);
struct QtHelp_PackedString QHelpEngineCore_DocumentationFileName(void* ptr, struct QtHelp_PackedString namespaceName);
struct QtHelp_PackedString QHelpEngineCore_QHelpEngineCore_NamespaceName(struct QtHelp_PackedString documentationFileName);
void* QHelpEngineCore_QHelpEngineCore_MetaData(struct QtHelp_PackedString documentationFileName, struct QtHelp_PackedString name);
char QHelpEngineCore_AddCustomFilter(void* ptr, struct QtHelp_PackedString filterName, struct QtHelp_PackedString attributes);
char QHelpEngineCore_CopyCollectionFile(void* ptr, struct QtHelp_PackedString fileName);
char QHelpEngineCore_RegisterDocumentation(void* ptr, struct QtHelp_PackedString documentationFileName);
char QHelpEngineCore_RemoveCustomFilter(void* ptr, struct QtHelp_PackedString filterName);
char QHelpEngineCore_RemoveCustomValue(void* ptr, struct QtHelp_PackedString key);
char QHelpEngineCore_SetCustomValue(void* ptr, struct QtHelp_PackedString key, void* value);
char QHelpEngineCore_SetupData(void* ptr);
char QHelpEngineCore_UnregisterDocumentation(void* ptr, struct QtHelp_PackedString namespaceName);
void QHelpEngineCore_ConnectCurrentFilterChanged(void* ptr);
void QHelpEngineCore_DisconnectCurrentFilterChanged(void* ptr);
void QHelpEngineCore_CurrentFilterChanged(void* ptr, struct QtHelp_PackedString newFilter);
void QHelpEngineCore_ConnectReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_DisconnectReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_ReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_SetAutoSaveFilter(void* ptr, char save);
void QHelpEngineCore_SetCollectionFile(void* ptr, struct QtHelp_PackedString fileName);
void QHelpEngineCore_SetCurrentFilter(void* ptr, struct QtHelp_PackedString filterName);
void QHelpEngineCore_ConnectSetupFinished(void* ptr);
void QHelpEngineCore_DisconnectSetupFinished(void* ptr);
void QHelpEngineCore_SetupFinished(void* ptr);
void QHelpEngineCore_ConnectSetupStarted(void* ptr);
void QHelpEngineCore_DisconnectSetupStarted(void* ptr);
void QHelpEngineCore_SetupStarted(void* ptr);
void QHelpEngineCore_ConnectWarning(void* ptr);
void QHelpEngineCore_DisconnectWarning(void* ptr);
void QHelpEngineCore_Warning(void* ptr, struct QtHelp_PackedString msg);
void QHelpEngineCore_DestroyQHelpEngineCore(void* ptr);
void QHelpEngineCore_DestroyQHelpEngineCoreDefault(void* ptr);
void* QHelpEngineCore_FileData(void* ptr, void* url);
struct QtHelp_PackedList QHelpEngineCore_LinksForIdentifier(void* ptr, struct QtHelp_PackedString id);
struct QtHelp_PackedList QHelpEngineCore_LinksForKeyword(void* ptr, struct QtHelp_PackedString keyword);
struct QtHelp_PackedString QHelpEngineCore_CollectionFile(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_CurrentFilter(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_Error(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_CustomFilters(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_FilterAttributes(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_FilterAttributes2(void* ptr, struct QtHelp_PackedString filterName);
struct QtHelp_PackedString QHelpEngineCore_RegisteredDocumentations(void* ptr);
void* QHelpEngineCore_FindFile(void* ptr, void* url);
void* QHelpEngineCore_CustomValue(void* ptr, struct QtHelp_PackedString key, void* defaultValue);
char QHelpEngineCore_AutoSaveFilter(void* ptr);
void* QHelpEngineCore___files_atList(void* ptr, int i);
void QHelpEngineCore___files_setList(void* ptr, void* i);
void* QHelpEngineCore___files_newList(void* ptr);
struct QtHelp_PackedString QHelpEngineCore___filterAttributeSets_atList(void* ptr, int i);
void QHelpEngineCore___filterAttributeSets_setList(void* ptr, struct QtHelp_PackedString i);
void* QHelpEngineCore___filterAttributeSets_newList(void* ptr);
void* QHelpEngineCore___linksForIdentifier_atList(void* ptr, struct QtHelp_PackedString i);
void QHelpEngineCore___linksForIdentifier_setList(void* ptr, struct QtHelp_PackedString key, void* i);
void* QHelpEngineCore___linksForIdentifier_newList(void* ptr);
struct QtHelp_PackedList QHelpEngineCore___linksForIdentifier_keyList(void* ptr);
void* QHelpEngineCore___linksForKeyword_atList(void* ptr, struct QtHelp_PackedString i);
void QHelpEngineCore___linksForKeyword_setList(void* ptr, struct QtHelp_PackedString key, void* i);
void* QHelpEngineCore___linksForKeyword_newList(void* ptr);
struct QtHelp_PackedList QHelpEngineCore___linksForKeyword_keyList(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_____linksForIdentifier_keyList_atList(void* ptr, int i);
void QHelpEngineCore_____linksForIdentifier_keyList_setList(void* ptr, struct QtHelp_PackedString i);
void* QHelpEngineCore_____linksForIdentifier_keyList_newList(void* ptr);
struct QtHelp_PackedString QHelpEngineCore_____linksForKeyword_keyList_atList(void* ptr, int i);
void QHelpEngineCore_____linksForKeyword_keyList_setList(void* ptr, struct QtHelp_PackedString i);
void* QHelpEngineCore_____linksForKeyword_keyList_newList(void* ptr);
void* QHelpEngineCore___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpEngineCore___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpEngineCore___dynamicPropertyNames_newList(void* ptr);
void* QHelpEngineCore___findChildren_atList2(void* ptr, int i);
void QHelpEngineCore___findChildren_setList2(void* ptr, void* i);
void* QHelpEngineCore___findChildren_newList2(void* ptr);
void* QHelpEngineCore___findChildren_atList3(void* ptr, int i);
void QHelpEngineCore___findChildren_setList3(void* ptr, void* i);
void* QHelpEngineCore___findChildren_newList3(void* ptr);
void* QHelpEngineCore___findChildren_atList(void* ptr, int i);
void QHelpEngineCore___findChildren_setList(void* ptr, void* i);
void* QHelpEngineCore___findChildren_newList(void* ptr);
void* QHelpEngineCore___children_atList(void* ptr, int i);
void QHelpEngineCore___children_setList(void* ptr, void* i);
void* QHelpEngineCore___children_newList(void* ptr);
char QHelpEngineCore_EventDefault(void* ptr, void* e);
char QHelpEngineCore_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpEngineCore_ChildEventDefault(void* ptr, void* event);
void QHelpEngineCore_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpEngineCore_CustomEventDefault(void* ptr, void* event);
void QHelpEngineCore_DeleteLaterDefault(void* ptr);
void QHelpEngineCore_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpEngineCore_TimerEventDefault(void* ptr, void* event);
void* QHelpEngineCore_MetaObjectDefault(void* ptr);
void* QHelpIndexModel_Filter(void* ptr, struct QtHelp_PackedString filter, struct QtHelp_PackedString wildcard);
void QHelpIndexModel_CreateIndex(void* ptr, struct QtHelp_PackedString customFilterName);
void QHelpIndexModel_ConnectIndexCreated(void* ptr);
void QHelpIndexModel_DisconnectIndexCreated(void* ptr);
void QHelpIndexModel_IndexCreated(void* ptr);
void QHelpIndexModel_ConnectIndexCreationStarted(void* ptr);
void QHelpIndexModel_DisconnectIndexCreationStarted(void* ptr);
void QHelpIndexModel_IndexCreationStarted(void* ptr);
char QHelpIndexModel_IsCreatingIndex(void* ptr);
void* QHelpIndexModel___linksForKeyword_atList(void* ptr, struct QtHelp_PackedString i);
void QHelpIndexModel___linksForKeyword_setList(void* ptr, struct QtHelp_PackedString key, void* i);
void* QHelpIndexModel___linksForKeyword_newList(void* ptr);
struct QtHelp_PackedList QHelpIndexModel___linksForKeyword_keyList(void* ptr);
struct QtHelp_PackedString QHelpIndexModel_____linksForKeyword_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____linksForKeyword_keyList_setList(void* ptr, struct QtHelp_PackedString i);
void* QHelpIndexModel_____linksForKeyword_keyList_newList(void* ptr);
int QHelpIndexModel_____setItemData_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____setItemData_keyList_setList(void* ptr, int i);
void* QHelpIndexModel_____setItemData_keyList_newList(void* ptr);
int QHelpIndexModel_____roleNames_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____roleNames_keyList_setList(void* ptr, int i);
void* QHelpIndexModel_____roleNames_keyList_newList(void* ptr);
int QHelpIndexModel_____itemData_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____itemData_keyList_setList(void* ptr, int i);
void* QHelpIndexModel_____itemData_keyList_newList(void* ptr);
void* QHelpIndexModel___setItemData_roles_atList(void* ptr, int i);
void QHelpIndexModel___setItemData_roles_setList(void* ptr, int key, void* i);
void* QHelpIndexModel___setItemData_roles_newList(void* ptr);
struct QtHelp_PackedList QHelpIndexModel___setItemData_keyList(void* ptr);
void* QHelpIndexModel___changePersistentIndexList_from_atList(void* ptr, int i);
void QHelpIndexModel___changePersistentIndexList_from_setList(void* ptr, void* i);
void* QHelpIndexModel___changePersistentIndexList_from_newList(void* ptr);
void* QHelpIndexModel___changePersistentIndexList_to_atList(void* ptr, int i);
void QHelpIndexModel___changePersistentIndexList_to_setList(void* ptr, void* i);
void* QHelpIndexModel___changePersistentIndexList_to_newList(void* ptr);
int QHelpIndexModel___dataChanged_roles_atList(void* ptr, int i);
void QHelpIndexModel___dataChanged_roles_setList(void* ptr, int i);
void* QHelpIndexModel___dataChanged_roles_newList(void* ptr);
void* QHelpIndexModel___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void QHelpIndexModel___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* QHelpIndexModel___layoutAboutToBeChanged_parents_newList(void* ptr);
void* QHelpIndexModel___layoutChanged_parents_atList(void* ptr, int i);
void QHelpIndexModel___layoutChanged_parents_setList(void* ptr, void* i);
void* QHelpIndexModel___layoutChanged_parents_newList(void* ptr);
void* QHelpIndexModel___roleNames_atList(void* ptr, int i);
void QHelpIndexModel___roleNames_setList(void* ptr, int key, void* i);
void* QHelpIndexModel___roleNames_newList(void* ptr);
struct QtHelp_PackedList QHelpIndexModel___roleNames_keyList(void* ptr);
void* QHelpIndexModel___itemData_atList(void* ptr, int i);
void QHelpIndexModel___itemData_setList(void* ptr, int key, void* i);
void* QHelpIndexModel___itemData_newList(void* ptr);
struct QtHelp_PackedList QHelpIndexModel___itemData_keyList(void* ptr);
void* QHelpIndexModel___mimeData_indexes_atList(void* ptr, int i);
void QHelpIndexModel___mimeData_indexes_setList(void* ptr, void* i);
void* QHelpIndexModel___mimeData_indexes_newList(void* ptr);
void* QHelpIndexModel___match_atList(void* ptr, int i);
void QHelpIndexModel___match_setList(void* ptr, void* i);
void* QHelpIndexModel___match_newList(void* ptr);
void* QHelpIndexModel___persistentIndexList_atList(void* ptr, int i);
void QHelpIndexModel___persistentIndexList_setList(void* ptr, void* i);
void* QHelpIndexModel___persistentIndexList_newList(void* ptr);
int QHelpIndexModel_____doSetRoleNames_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____doSetRoleNames_keyList_setList(void* ptr, int i);
void* QHelpIndexModel_____doSetRoleNames_keyList_newList(void* ptr);
int QHelpIndexModel_____setRoleNames_keyList_atList(void* ptr, int i);
void QHelpIndexModel_____setRoleNames_keyList_setList(void* ptr, int i);
void* QHelpIndexModel_____setRoleNames_keyList_newList(void* ptr);
void* QHelpIndexModel___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpIndexModel___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpIndexModel___dynamicPropertyNames_newList(void* ptr);
void* QHelpIndexModel___findChildren_atList2(void* ptr, int i);
void QHelpIndexModel___findChildren_setList2(void* ptr, void* i);
void* QHelpIndexModel___findChildren_newList2(void* ptr);
void* QHelpIndexModel___findChildren_atList3(void* ptr, int i);
void QHelpIndexModel___findChildren_setList3(void* ptr, void* i);
void* QHelpIndexModel___findChildren_newList3(void* ptr);
void* QHelpIndexModel___findChildren_atList(void* ptr, int i);
void QHelpIndexModel___findChildren_setList(void* ptr, void* i);
void* QHelpIndexModel___findChildren_newList(void* ptr);
void* QHelpIndexModel___children_atList(void* ptr, int i);
void QHelpIndexModel___children_setList(void* ptr, void* i);
void* QHelpIndexModel___children_newList(void* ptr);
char QHelpIndexModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
char QHelpIndexModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
char QHelpIndexModel_SetDataDefault(void* ptr, void* index, void* value, int role);
void QHelpIndexModel_SortDefault(void* ptr, int column, long long order);
void* QHelpIndexModel_SiblingDefault(void* ptr, int row, int column, void* idx);
void* QHelpIndexModel_DataDefault(void* ptr, void* index, int role);
long long QHelpIndexModel_SupportedDropActionsDefault(void* ptr);
long long QHelpIndexModel_FlagsDefault(void* ptr, void* index);
int QHelpIndexModel_RowCountDefault(void* ptr, void* parent);
char QHelpIndexModel_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
void* QHelpIndexModel_IndexDefault(void* ptr, int row, int column, void* parent);
char QHelpIndexModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char QHelpIndexModel_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char QHelpIndexModel_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
char QHelpIndexModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char QHelpIndexModel_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char QHelpIndexModel_SetItemDataDefault(void* ptr, void* index, void* roles);
char QHelpIndexModel_SubmitDefault(void* ptr);
void QHelpIndexModel_FetchMoreDefault(void* ptr, void* parent);
void QHelpIndexModel_ResetInternalDataDefault(void* ptr);
void QHelpIndexModel_RevertDefault(void* ptr);
struct QtHelp_PackedList QHelpIndexModel_RoleNamesDefault(void* ptr);
struct QtHelp_PackedList QHelpIndexModel_ItemDataDefault(void* ptr, void* index);
void* QHelpIndexModel_MimeDataDefault(void* ptr, void* indexes);
void* QHelpIndexModel_BuddyDefault(void* ptr, void* index);
void* QHelpIndexModel_ParentDefault(void* ptr, void* index);
struct QtHelp_PackedList QHelpIndexModel_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* QHelpIndexModel_SpanDefault(void* ptr, void* index);
struct QtHelp_PackedString QHelpIndexModel_MimeTypesDefault(void* ptr);
void* QHelpIndexModel_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
long long QHelpIndexModel_SupportedDragActionsDefault(void* ptr);
char QHelpIndexModel_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char QHelpIndexModel_CanFetchMoreDefault(void* ptr, void* parent);
char QHelpIndexModel_HasChildrenDefault(void* ptr, void* parent);
int QHelpIndexModel_ColumnCountDefault(void* ptr, void* parent);
char QHelpIndexModel_EventDefault(void* ptr, void* e);
char QHelpIndexModel_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpIndexModel_ChildEventDefault(void* ptr, void* event);
void QHelpIndexModel_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpIndexModel_CustomEventDefault(void* ptr, void* event);
void QHelpIndexModel_DeleteLaterDefault(void* ptr);
void QHelpIndexModel_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpIndexModel_TimerEventDefault(void* ptr, void* event);
void* QHelpIndexModel_MetaObjectDefault(void* ptr);
void QHelpIndexWidget_ActivateCurrentItem(void* ptr);
void QHelpIndexWidget_ActivateCurrentItemDefault(void* ptr);
void QHelpIndexWidget_FilterIndices(void* ptr, struct QtHelp_PackedString filter, struct QtHelp_PackedString wildcard);
void QHelpIndexWidget_FilterIndicesDefault(void* ptr, struct QtHelp_PackedString filter, struct QtHelp_PackedString wildcard);
void QHelpIndexWidget_ConnectLinkActivated(void* ptr);
void QHelpIndexWidget_DisconnectLinkActivated(void* ptr);
void QHelpIndexWidget_LinkActivated(void* ptr, void* link, struct QtHelp_PackedString keyword);
void QHelpIndexWidget_ConnectLinksActivated(void* ptr);
void QHelpIndexWidget_DisconnectLinksActivated(void* ptr);
void QHelpIndexWidget_LinksActivated(void* ptr, void* links, struct QtHelp_PackedString keyword);
void* QHelpIndexWidget___linksActivated_links_atList(void* ptr, struct QtHelp_PackedString i);
void QHelpIndexWidget___linksActivated_links_setList(void* ptr, struct QtHelp_PackedString key, void* i);
void* QHelpIndexWidget___linksActivated_links_newList(void* ptr);
struct QtHelp_PackedList QHelpIndexWidget___linksActivated_keyList(void* ptr);
struct QtHelp_PackedString QHelpIndexWidget_____linksActivated_keyList_atList(void* ptr, int i);
void QHelpIndexWidget_____linksActivated_keyList_setList(void* ptr, struct QtHelp_PackedString i);
void* QHelpIndexWidget_____linksActivated_keyList_newList(void* ptr);
int QHelpIndexWidget___dataChanged_roles_atList(void* ptr, int i);
void QHelpIndexWidget___dataChanged_roles_setList(void* ptr, int i);
void* QHelpIndexWidget___dataChanged_roles_newList(void* ptr);
void* QHelpIndexWidget___indexesMoved_indexes_atList(void* ptr, int i);
void QHelpIndexWidget___indexesMoved_indexes_setList(void* ptr, void* i);
void* QHelpIndexWidget___indexesMoved_indexes_newList(void* ptr);
void* QHelpIndexWidget___selectedIndexes_atList(void* ptr, int i);
void QHelpIndexWidget___selectedIndexes_setList(void* ptr, void* i);
void* QHelpIndexWidget___selectedIndexes_newList(void* ptr);
void* QHelpIndexWidget___scrollBarWidgets_atList(void* ptr, int i);
void QHelpIndexWidget___scrollBarWidgets_setList(void* ptr, void* i);
void* QHelpIndexWidget___scrollBarWidgets_newList(void* ptr);
void* QHelpIndexWidget___addActions_actions_atList(void* ptr, int i);
void QHelpIndexWidget___addActions_actions_setList(void* ptr, void* i);
void* QHelpIndexWidget___addActions_actions_newList(void* ptr);
void* QHelpIndexWidget___insertActions_actions_atList(void* ptr, int i);
void QHelpIndexWidget___insertActions_actions_setList(void* ptr, void* i);
void* QHelpIndexWidget___insertActions_actions_newList(void* ptr);
void* QHelpIndexWidget___actions_atList(void* ptr, int i);
void QHelpIndexWidget___actions_setList(void* ptr, void* i);
void* QHelpIndexWidget___actions_newList(void* ptr);
void* QHelpIndexWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpIndexWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpIndexWidget___dynamicPropertyNames_newList(void* ptr);
void* QHelpIndexWidget___findChildren_atList2(void* ptr, int i);
void QHelpIndexWidget___findChildren_setList2(void* ptr, void* i);
void* QHelpIndexWidget___findChildren_newList2(void* ptr);
void* QHelpIndexWidget___findChildren_atList3(void* ptr, int i);
void QHelpIndexWidget___findChildren_setList3(void* ptr, void* i);
void* QHelpIndexWidget___findChildren_newList3(void* ptr);
void* QHelpIndexWidget___findChildren_atList(void* ptr, int i);
void QHelpIndexWidget___findChildren_setList(void* ptr, void* i);
void* QHelpIndexWidget___findChildren_newList(void* ptr);
void* QHelpIndexWidget___children_atList(void* ptr, int i);
void QHelpIndexWidget___children_setList(void* ptr, void* i);
void* QHelpIndexWidget___children_newList(void* ptr);
void* QHelpIndexWidget_MoveCursorDefault(void* ptr, long long cursorAction, long long modifiers);
char QHelpIndexWidget_EventDefault(void* ptr, void* e);
void QHelpIndexWidget_CurrentChangedDefault(void* ptr, void* current, void* previous);
void QHelpIndexWidget_DataChangedDefault(void* ptr, void* topLeft, void* bottomRight, void* roles);
void QHelpIndexWidget_DragLeaveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_DragMoveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_DropEventDefault(void* ptr, void* e);
void QHelpIndexWidget_MouseMoveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_MouseReleaseEventDefault(void* ptr, void* e);
void QHelpIndexWidget_PaintEventDefault(void* ptr, void* e);
void QHelpIndexWidget_ResizeEventDefault(void* ptr, void* e);
void QHelpIndexWidget_RowsAboutToBeRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_RowsInsertedDefault(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_ScrollToDefault(void* ptr, void* index, long long hint);
void QHelpIndexWidget_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void QHelpIndexWidget_SetSelectionDefault(void* ptr, void* rect, long long command);
void QHelpIndexWidget_StartDragDefault(void* ptr, long long supportedActions);
void QHelpIndexWidget_TimerEventDefault(void* ptr, void* e);
void QHelpIndexWidget_UpdateGeometriesDefault(void* ptr);
void QHelpIndexWidget_WheelEventDefault(void* ptr, void* e);
void* QHelpIndexWidget_IndexAtDefault(void* ptr, void* p);
struct QtHelp_PackedList QHelpIndexWidget_SelectedIndexesDefault(void* ptr);
void* QHelpIndexWidget_VisualRectDefault(void* ptr, void* index);
void* QHelpIndexWidget_VisualRegionForSelectionDefault(void* ptr, void* selection);
void* QHelpIndexWidget_ViewportSizeHintDefault(void* ptr);
void* QHelpIndexWidget_ViewOptionsDefault(void* ptr);
char QHelpIndexWidget_IsIndexHiddenDefault(void* ptr, void* index);
int QHelpIndexWidget_HorizontalOffsetDefault(void* ptr);
int QHelpIndexWidget_VerticalOffsetDefault(void* ptr);
char QHelpIndexWidget_Edit2Default(void* ptr, void* index, long long trigger, void* event);
char QHelpIndexWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QHelpIndexWidget_ViewportEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ClearSelectionDefault(void* ptr);
void QHelpIndexWidget_CloseEditorDefault(void* ptr, void* editor, long long hint);
void QHelpIndexWidget_CommitDataDefault(void* ptr, void* editor);
void QHelpIndexWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpIndexWidget_EditDefault(void* ptr, void* index);
void QHelpIndexWidget_EditorDestroyedDefault(void* ptr, void* editor);
void QHelpIndexWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpIndexWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpIndexWidget_InputMethodEventDefault(void* ptr, void* event);
void QHelpIndexWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpIndexWidget_KeyboardSearchDefault(void* ptr, struct QtHelp_PackedString search);
void QHelpIndexWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpIndexWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ResetDefault(void* ptr);
void QHelpIndexWidget_ScrollToBottomDefault(void* ptr);
void QHelpIndexWidget_ScrollToTopDefault(void* ptr);
void QHelpIndexWidget_SelectAllDefault(void* ptr);
void QHelpIndexWidget_SetCurrentIndexDefault(void* ptr, void* index);
void QHelpIndexWidget_SetModelDefault(void* ptr, void* model);
void QHelpIndexWidget_SetRootIndexDefault(void* ptr, void* index);
void QHelpIndexWidget_SetSelectionModelDefault(void* ptr, void* selectionModel);
void QHelpIndexWidget_UpdateDefault(void* ptr, void* index);
long long QHelpIndexWidget_SelectionCommandDefault(void* ptr, void* index, void* event);
void* QHelpIndexWidget_InputMethodQueryDefault(void* ptr, long long query);
int QHelpIndexWidget_SizeHintForColumnDefault(void* ptr, int column);
int QHelpIndexWidget_SizeHintForRowDefault(void* ptr, int row);
void QHelpIndexWidget_ContextMenuEventDefault(void* ptr, void* e);
void QHelpIndexWidget_ScrollContentsByDefault(void* ptr, int dx, int dy);
void QHelpIndexWidget_SetupViewportDefault(void* ptr, void* viewport);
void* QHelpIndexWidget_MinimumSizeHintDefault(void* ptr);
void* QHelpIndexWidget_SizeHintDefault(void* ptr);
void QHelpIndexWidget_ChangeEventDefault(void* ptr, void* ev);
char QHelpIndexWidget_CloseDefault(void* ptr);
char QHelpIndexWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QHelpIndexWidget_ActionEventDefault(void* ptr, void* event);
void QHelpIndexWidget_CloseEventDefault(void* ptr, void* event);
void QHelpIndexWidget_EnterEventDefault(void* ptr, void* event);
void QHelpIndexWidget_HideDefault(void* ptr);
void QHelpIndexWidget_HideEventDefault(void* ptr, void* event);
void QHelpIndexWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpIndexWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpIndexWidget_LowerDefault(void* ptr);
void QHelpIndexWidget_MoveEventDefault(void* ptr, void* event);
void QHelpIndexWidget_RaiseDefault(void* ptr);
void QHelpIndexWidget_RepaintDefault(void* ptr);
void QHelpIndexWidget_SetDisabledDefault(void* ptr, char disable);
void QHelpIndexWidget_SetEnabledDefault(void* ptr, char vbo);
void QHelpIndexWidget_SetFocus2Default(void* ptr);
void QHelpIndexWidget_SetHiddenDefault(void* ptr, char hidden);
void QHelpIndexWidget_SetStyleSheetDefault(void* ptr, struct QtHelp_PackedString styleSheet);
void QHelpIndexWidget_SetVisibleDefault(void* ptr, char visible);
void QHelpIndexWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QHelpIndexWidget_SetWindowTitleDefault(void* ptr, struct QtHelp_PackedString vqs);
void QHelpIndexWidget_ShowDefault(void* ptr);
void QHelpIndexWidget_ShowEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ShowFullScreenDefault(void* ptr);
void QHelpIndexWidget_ShowMaximizedDefault(void* ptr);
void QHelpIndexWidget_ShowMinimizedDefault(void* ptr);
void QHelpIndexWidget_ShowNormalDefault(void* ptr);
void QHelpIndexWidget_TabletEventDefault(void* ptr, void* event);
void QHelpIndexWidget_UpdateMicroFocusDefault(void* ptr);
void* QHelpIndexWidget_PaintEngineDefault(void* ptr);
char QHelpIndexWidget_HasHeightForWidthDefault(void* ptr);
int QHelpIndexWidget_HeightForWidthDefault(void* ptr, int w);
int QHelpIndexWidget_MetricDefault(void* ptr, long long m);
char QHelpIndexWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpIndexWidget_ChildEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpIndexWidget_CustomEventDefault(void* ptr, void* event);
void QHelpIndexWidget_DeleteLaterDefault(void* ptr);
void QHelpIndexWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void* QHelpIndexWidget_MetaObjectDefault(void* ptr);
void QHelpSearchEngine_CancelIndexing(void* ptr);
void QHelpSearchEngine_CancelIndexingDefault(void* ptr);
void QHelpSearchEngine_CancelSearching(void* ptr);
void QHelpSearchEngine_CancelSearchingDefault(void* ptr);
void* QHelpSearchEngine_NewQHelpSearchEngine(void* helpEngine, void* parent);
void* QHelpSearchEngine_QueryWidget(void* ptr);
void* QHelpSearchEngine_ResultWidget(void* ptr);
void QHelpSearchEngine_ConnectIndexingFinished(void* ptr);
void QHelpSearchEngine_DisconnectIndexingFinished(void* ptr);
void QHelpSearchEngine_IndexingFinished(void* ptr);
void QHelpSearchEngine_ConnectIndexingStarted(void* ptr);
void QHelpSearchEngine_DisconnectIndexingStarted(void* ptr);
void QHelpSearchEngine_IndexingStarted(void* ptr);
void QHelpSearchEngine_ReindexDocumentation(void* ptr);
void QHelpSearchEngine_ReindexDocumentationDefault(void* ptr);
void QHelpSearchEngine_Search(void* ptr, struct QtHelp_PackedString searchInput);
void QHelpSearchEngine_SearchDefault(void* ptr, struct QtHelp_PackedString searchInput);
void QHelpSearchEngine_ConnectSearchingFinished(void* ptr);
void QHelpSearchEngine_DisconnectSearchingFinished(void* ptr);
void QHelpSearchEngine_SearchingFinished(void* ptr, int searchResultCount);
void QHelpSearchEngine_ConnectSearchingStarted(void* ptr);
void QHelpSearchEngine_DisconnectSearchingStarted(void* ptr);
void QHelpSearchEngine_SearchingStarted(void* ptr);
void QHelpSearchEngine_DestroyQHelpSearchEngine(void* ptr);
struct QtHelp_PackedString QHelpSearchEngine_SearchInput(void* ptr);
struct QtHelp_PackedList QHelpSearchEngine_SearchResults(void* ptr, int start, int end);
int QHelpSearchEngine_SearchResultCount(void* ptr);
void* QHelpSearchEngine___search_queryList_newList(void* ptr);
void* QHelpSearchEngine___query_newList(void* ptr);
void* QHelpSearchEngine___searchResults_atList(void* ptr, int i);
void QHelpSearchEngine___searchResults_setList(void* ptr, void* i);
void* QHelpSearchEngine___searchResults_newList(void* ptr);
void* QHelpSearchEngine___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpSearchEngine___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpSearchEngine___dynamicPropertyNames_newList(void* ptr);
void* QHelpSearchEngine___findChildren_atList2(void* ptr, int i);
void QHelpSearchEngine___findChildren_setList2(void* ptr, void* i);
void* QHelpSearchEngine___findChildren_newList2(void* ptr);
void* QHelpSearchEngine___findChildren_atList3(void* ptr, int i);
void QHelpSearchEngine___findChildren_setList3(void* ptr, void* i);
void* QHelpSearchEngine___findChildren_newList3(void* ptr);
void* QHelpSearchEngine___findChildren_atList(void* ptr, int i);
void QHelpSearchEngine___findChildren_setList(void* ptr, void* i);
void* QHelpSearchEngine___findChildren_newList(void* ptr);
void* QHelpSearchEngine___children_atList(void* ptr, int i);
void QHelpSearchEngine___children_setList(void* ptr, void* i);
void* QHelpSearchEngine___children_newList(void* ptr);
char QHelpSearchEngine_EventDefault(void* ptr, void* e);
char QHelpSearchEngine_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpSearchEngine_ChildEventDefault(void* ptr, void* event);
void QHelpSearchEngine_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchEngine_CustomEventDefault(void* ptr, void* event);
void QHelpSearchEngine_DeleteLaterDefault(void* ptr);
void QHelpSearchEngine_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchEngine_TimerEventDefault(void* ptr, void* event);
void* QHelpSearchEngine_MetaObjectDefault(void* ptr);
void* QHelpSearchQueryWidget_NewQHelpSearchQueryWidget(void* parent);
void QHelpSearchQueryWidget_CollapseExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ExpandExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ConnectSearch(void* ptr);
void QHelpSearchQueryWidget_DisconnectSearch(void* ptr);
void QHelpSearchQueryWidget_Search(void* ptr);
void QHelpSearchQueryWidget_SetSearchInput(void* ptr, struct QtHelp_PackedString searchInput);
void QHelpSearchQueryWidget_DestroyQHelpSearchQueryWidget(void* ptr);
struct QtHelp_PackedString QHelpSearchQueryWidget_SearchInput(void* ptr);
char QHelpSearchQueryWidget_IsCompactMode(void* ptr);
void* QHelpSearchQueryWidget___setQuery_queryList_newList(void* ptr);
void* QHelpSearchQueryWidget___query_newList(void* ptr);
void* QHelpSearchQueryWidget___addActions_actions_atList(void* ptr, int i);
void QHelpSearchQueryWidget___addActions_actions_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___addActions_actions_newList(void* ptr);
void* QHelpSearchQueryWidget___insertActions_actions_atList(void* ptr, int i);
void QHelpSearchQueryWidget___insertActions_actions_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___insertActions_actions_newList(void* ptr);
void* QHelpSearchQueryWidget___actions_atList(void* ptr, int i);
void QHelpSearchQueryWidget___actions_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___actions_newList(void* ptr);
void* QHelpSearchQueryWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpSearchQueryWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___dynamicPropertyNames_newList(void* ptr);
void* QHelpSearchQueryWidget___findChildren_atList2(void* ptr, int i);
void QHelpSearchQueryWidget___findChildren_setList2(void* ptr, void* i);
void* QHelpSearchQueryWidget___findChildren_newList2(void* ptr);
void* QHelpSearchQueryWidget___findChildren_atList3(void* ptr, int i);
void QHelpSearchQueryWidget___findChildren_setList3(void* ptr, void* i);
void* QHelpSearchQueryWidget___findChildren_newList3(void* ptr);
void* QHelpSearchQueryWidget___findChildren_atList(void* ptr, int i);
void QHelpSearchQueryWidget___findChildren_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___findChildren_newList(void* ptr);
void* QHelpSearchQueryWidget___children_atList(void* ptr, int i);
void QHelpSearchQueryWidget___children_setList(void* ptr, void* i);
void* QHelpSearchQueryWidget___children_newList(void* ptr);
char QHelpSearchQueryWidget_CloseDefault(void* ptr);
char QHelpSearchQueryWidget_EventDefault(void* ptr, void* event);
char QHelpSearchQueryWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QHelpSearchQueryWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QHelpSearchQueryWidget_ActionEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ChangeEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_CloseEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ContextMenuEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DropEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_EnterEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_HideDefault(void* ptr);
void QHelpSearchQueryWidget_HideEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_InputMethodEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_LowerDefault(void* ptr);
void QHelpSearchQueryWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseReleaseEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_PaintEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_RaiseDefault(void* ptr);
void QHelpSearchQueryWidget_RepaintDefault(void* ptr);
void QHelpSearchQueryWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_SetDisabledDefault(void* ptr, char disable);
void QHelpSearchQueryWidget_SetEnabledDefault(void* ptr, char vbo);
void QHelpSearchQueryWidget_SetFocus2Default(void* ptr);
void QHelpSearchQueryWidget_SetHiddenDefault(void* ptr, char hidden);
void QHelpSearchQueryWidget_SetStyleSheetDefault(void* ptr, struct QtHelp_PackedString styleSheet);
void QHelpSearchQueryWidget_SetVisibleDefault(void* ptr, char visible);
void QHelpSearchQueryWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QHelpSearchQueryWidget_SetWindowTitleDefault(void* ptr, struct QtHelp_PackedString vqs);
void QHelpSearchQueryWidget_ShowDefault(void* ptr);
void QHelpSearchQueryWidget_ShowEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ShowFullScreenDefault(void* ptr);
void QHelpSearchQueryWidget_ShowMaximizedDefault(void* ptr);
void QHelpSearchQueryWidget_ShowMinimizedDefault(void* ptr);
void QHelpSearchQueryWidget_ShowNormalDefault(void* ptr);
void QHelpSearchQueryWidget_TabletEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_UpdateDefault(void* ptr);
void QHelpSearchQueryWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpSearchQueryWidget_WheelEventDefault(void* ptr, void* event);
void* QHelpSearchQueryWidget_PaintEngineDefault(void* ptr);
void* QHelpSearchQueryWidget_MinimumSizeHintDefault(void* ptr);
void* QHelpSearchQueryWidget_SizeHintDefault(void* ptr);
void* QHelpSearchQueryWidget_InputMethodQueryDefault(void* ptr, long long query);
char QHelpSearchQueryWidget_HasHeightForWidthDefault(void* ptr);
int QHelpSearchQueryWidget_HeightForWidthDefault(void* ptr, int w);
int QHelpSearchQueryWidget_MetricDefault(void* ptr, long long m);
char QHelpSearchQueryWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpSearchQueryWidget_ChildEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchQueryWidget_CustomEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DeleteLaterDefault(void* ptr);
void QHelpSearchQueryWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchQueryWidget_TimerEventDefault(void* ptr, void* event);
void* QHelpSearchQueryWidget_MetaObjectDefault(void* ptr);
void* QHelpSearchResult_NewQHelpSearchResult();
void* QHelpSearchResult_NewQHelpSearchResult2(void* other);
void* QHelpSearchResult_NewQHelpSearchResult3(void* url, struct QtHelp_PackedString title, struct QtHelp_PackedString snippet);
void QHelpSearchResult_DestroyQHelpSearchResult(void* ptr);
struct QtHelp_PackedString QHelpSearchResult_Snippet(void* ptr);
struct QtHelp_PackedString QHelpSearchResult_Title(void* ptr);
void* QHelpSearchResult_Url(void* ptr);
void* QHelpSearchResultWidget_LinkAt(void* ptr, void* point);
void QHelpSearchResultWidget_ConnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_DisconnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_RequestShowLink(void* ptr, void* link);
void QHelpSearchResultWidget_DestroyQHelpSearchResultWidget(void* ptr);
void* QHelpSearchResultWidget___addActions_actions_atList(void* ptr, int i);
void QHelpSearchResultWidget___addActions_actions_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___addActions_actions_newList(void* ptr);
void* QHelpSearchResultWidget___insertActions_actions_atList(void* ptr, int i);
void QHelpSearchResultWidget___insertActions_actions_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___insertActions_actions_newList(void* ptr);
void* QHelpSearchResultWidget___actions_atList(void* ptr, int i);
void QHelpSearchResultWidget___actions_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___actions_newList(void* ptr);
void* QHelpSearchResultWidget___dynamicPropertyNames_atList(void* ptr, int i);
void QHelpSearchResultWidget___dynamicPropertyNames_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___dynamicPropertyNames_newList(void* ptr);
void* QHelpSearchResultWidget___findChildren_atList2(void* ptr, int i);
void QHelpSearchResultWidget___findChildren_setList2(void* ptr, void* i);
void* QHelpSearchResultWidget___findChildren_newList2(void* ptr);
void* QHelpSearchResultWidget___findChildren_atList3(void* ptr, int i);
void QHelpSearchResultWidget___findChildren_setList3(void* ptr, void* i);
void* QHelpSearchResultWidget___findChildren_newList3(void* ptr);
void* QHelpSearchResultWidget___findChildren_atList(void* ptr, int i);
void QHelpSearchResultWidget___findChildren_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___findChildren_newList(void* ptr);
void* QHelpSearchResultWidget___children_atList(void* ptr, int i);
void QHelpSearchResultWidget___children_setList(void* ptr, void* i);
void* QHelpSearchResultWidget___children_newList(void* ptr);
char QHelpSearchResultWidget_CloseDefault(void* ptr);
char QHelpSearchResultWidget_EventDefault(void* ptr, void* event);
char QHelpSearchResultWidget_FocusNextPrevChildDefault(void* ptr, char next);
char QHelpSearchResultWidget_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QHelpSearchResultWidget_ActionEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ChangeEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_CloseEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ContextMenuEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DropEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_EnterEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_HideDefault(void* ptr);
void QHelpSearchResultWidget_HideEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_InputMethodEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_LowerDefault(void* ptr);
void QHelpSearchResultWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MouseReleaseEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_PaintEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_RaiseDefault(void* ptr);
void QHelpSearchResultWidget_RepaintDefault(void* ptr);
void QHelpSearchResultWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_SetDisabledDefault(void* ptr, char disable);
void QHelpSearchResultWidget_SetEnabledDefault(void* ptr, char vbo);
void QHelpSearchResultWidget_SetFocus2Default(void* ptr);
void QHelpSearchResultWidget_SetHiddenDefault(void* ptr, char hidden);
void QHelpSearchResultWidget_SetStyleSheetDefault(void* ptr, struct QtHelp_PackedString styleSheet);
void QHelpSearchResultWidget_SetVisibleDefault(void* ptr, char visible);
void QHelpSearchResultWidget_SetWindowModifiedDefault(void* ptr, char vbo);
void QHelpSearchResultWidget_SetWindowTitleDefault(void* ptr, struct QtHelp_PackedString vqs);
void QHelpSearchResultWidget_ShowDefault(void* ptr);
void QHelpSearchResultWidget_ShowEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ShowFullScreenDefault(void* ptr);
void QHelpSearchResultWidget_ShowMaximizedDefault(void* ptr);
void QHelpSearchResultWidget_ShowMinimizedDefault(void* ptr);
void QHelpSearchResultWidget_ShowNormalDefault(void* ptr);
void QHelpSearchResultWidget_TabletEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_UpdateDefault(void* ptr);
void QHelpSearchResultWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpSearchResultWidget_WheelEventDefault(void* ptr, void* event);
void* QHelpSearchResultWidget_PaintEngineDefault(void* ptr);
void* QHelpSearchResultWidget_MinimumSizeHintDefault(void* ptr);
void* QHelpSearchResultWidget_SizeHintDefault(void* ptr);
void* QHelpSearchResultWidget_InputMethodQueryDefault(void* ptr, long long query);
char QHelpSearchResultWidget_HasHeightForWidthDefault(void* ptr);
int QHelpSearchResultWidget_HeightForWidthDefault(void* ptr, int w);
int QHelpSearchResultWidget_MetricDefault(void* ptr, long long m);
char QHelpSearchResultWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void QHelpSearchResultWidget_ChildEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchResultWidget_CustomEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DeleteLaterDefault(void* ptr);
void QHelpSearchResultWidget_DisconnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchResultWidget_TimerEventDefault(void* ptr, void* event);
void* QHelpSearchResultWidget_MetaObjectDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif