#pragma once

#ifndef GO_QTHELP_H
#define GO_QTHELP_H

#ifdef __cplusplus
extern "C" {
#endif

void* QHelpContentItem_Child(void* ptr, int row);
int QHelpContentItem_ChildCount(void* ptr);
int QHelpContentItem_ChildPosition(void* ptr, void* child);
void* QHelpContentItem_Parent(void* ptr);
int QHelpContentItem_Row(void* ptr);
char* QHelpContentItem_Title(void* ptr);
void* QHelpContentItem_Url(void* ptr);
void QHelpContentItem_DestroyQHelpContentItem(void* ptr);
int QHelpContentModel_ColumnCount(void* ptr, void* parent);
void* QHelpContentModel_ContentItemAt(void* ptr, void* index);
void QHelpContentModel_ConnectContentsCreated(void* ptr);
void QHelpContentModel_DisconnectContentsCreated(void* ptr);
void QHelpContentModel_ContentsCreated(void* ptr);
void QHelpContentModel_ConnectContentsCreationStarted(void* ptr);
void QHelpContentModel_DisconnectContentsCreationStarted(void* ptr);
void QHelpContentModel_ContentsCreationStarted(void* ptr);
void QHelpContentModel_CreateContents(void* ptr, char* customFilterName);
void* QHelpContentModel_Data(void* ptr, void* index, int role);
void* QHelpContentModel_Index(void* ptr, int row, int column, void* parent);
int QHelpContentModel_IsCreatingContents(void* ptr);
void* QHelpContentModel_Parent(void* ptr, void* index);
int QHelpContentModel_RowCount(void* ptr, void* parent);
void QHelpContentModel_DestroyQHelpContentModel(void* ptr);
void* QHelpContentModel_Sibling(void* ptr, int row, int column, void* index);
void* QHelpContentModel_SiblingDefault(void* ptr, int row, int column, void* index);
void* QHelpContentModel_Buddy(void* ptr, void* index);
void* QHelpContentModel_BuddyDefault(void* ptr, void* index);
int QHelpContentModel_CanDropMimeData(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpContentModel_CanDropMimeDataDefault(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpContentModel_CanFetchMore(void* ptr, void* parent);
int QHelpContentModel_CanFetchMoreDefault(void* ptr, void* parent);
int QHelpContentModel_DropMimeData(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpContentModel_DropMimeDataDefault(void* ptr, void* data, int action, int row, int column, void* parent);
void QHelpContentModel_FetchMore(void* ptr, void* parent);
void QHelpContentModel_FetchMoreDefault(void* ptr, void* parent);
int QHelpContentModel_Flags(void* ptr, void* index);
int QHelpContentModel_FlagsDefault(void* ptr, void* index);
int QHelpContentModel_HasChildren(void* ptr, void* parent);
int QHelpContentModel_HasChildrenDefault(void* ptr, void* parent);
void* QHelpContentModel_HeaderData(void* ptr, int section, int orientation, int role);
void* QHelpContentModel_HeaderDataDefault(void* ptr, int section, int orientation, int role);
int QHelpContentModel_InsertColumns(void* ptr, int column, int count, void* parent);
int QHelpContentModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
int QHelpContentModel_InsertRows(void* ptr, int row, int count, void* parent);
int QHelpContentModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
char* QHelpContentModel_MimeTypes(void* ptr);
char* QHelpContentModel_MimeTypesDefault(void* ptr);
int QHelpContentModel_MoveColumns(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
int QHelpContentModel_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
int QHelpContentModel_MoveRows(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
int QHelpContentModel_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
int QHelpContentModel_RemoveColumns(void* ptr, int column, int count, void* parent);
int QHelpContentModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
int QHelpContentModel_RemoveRows(void* ptr, int row, int count, void* parent);
int QHelpContentModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void QHelpContentModel_ResetInternalData(void* ptr);
void QHelpContentModel_ResetInternalDataDefault(void* ptr);
void QHelpContentModel_Revert(void* ptr);
void QHelpContentModel_RevertDefault(void* ptr);
int QHelpContentModel_SetData(void* ptr, void* index, void* value, int role);
int QHelpContentModel_SetDataDefault(void* ptr, void* index, void* value, int role);
int QHelpContentModel_SetHeaderData(void* ptr, int section, int orientation, void* value, int role);
int QHelpContentModel_SetHeaderDataDefault(void* ptr, int section, int orientation, void* value, int role);
void QHelpContentModel_Sort(void* ptr, int column, int order);
void QHelpContentModel_SortDefault(void* ptr, int column, int order);
void* QHelpContentModel_Span(void* ptr, void* index);
void* QHelpContentModel_SpanDefault(void* ptr, void* index);
int QHelpContentModel_Submit(void* ptr);
int QHelpContentModel_SubmitDefault(void* ptr);
int QHelpContentModel_SupportedDragActions(void* ptr);
int QHelpContentModel_SupportedDragActionsDefault(void* ptr);
int QHelpContentModel_SupportedDropActions(void* ptr);
int QHelpContentModel_SupportedDropActionsDefault(void* ptr);
void QHelpContentModel_TimerEvent(void* ptr, void* event);
void QHelpContentModel_TimerEventDefault(void* ptr, void* event);
void QHelpContentModel_ChildEvent(void* ptr, void* event);
void QHelpContentModel_ChildEventDefault(void* ptr, void* event);
void QHelpContentModel_ConnectNotify(void* ptr, void* sign);
void QHelpContentModel_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpContentModel_CustomEvent(void* ptr, void* event);
void QHelpContentModel_CustomEventDefault(void* ptr, void* event);
void QHelpContentModel_DeleteLater(void* ptr);
void QHelpContentModel_DeleteLaterDefault(void* ptr);
void QHelpContentModel_DisconnectNotify(void* ptr, void* sign);
void QHelpContentModel_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpContentModel_Event(void* ptr, void* e);
int QHelpContentModel_EventDefault(void* ptr, void* e);
int QHelpContentModel_EventFilter(void* ptr, void* watched, void* event);
int QHelpContentModel_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpContentModel_MetaObject(void* ptr);
void* QHelpContentModel_MetaObjectDefault(void* ptr);
void* QHelpContentWidget_IndexOf(void* ptr, void* link);
void QHelpContentWidget_ConnectLinkActivated(void* ptr);
void QHelpContentWidget_DisconnectLinkActivated(void* ptr);
void QHelpContentWidget_LinkActivated(void* ptr, void* link);
void QHelpContentWidget_Collapse(void* ptr, void* index);
void QHelpContentWidget_CollapseDefault(void* ptr, void* index);
void QHelpContentWidget_Expand(void* ptr, void* index);
void QHelpContentWidget_ExpandDefault(void* ptr, void* index);
void QHelpContentWidget_CollapseAll(void* ptr);
void QHelpContentWidget_CollapseAllDefault(void* ptr);
void QHelpContentWidget_ColumnCountChanged(void* ptr, int oldCount, int newCount);
void QHelpContentWidget_ColumnCountChangedDefault(void* ptr, int oldCount, int newCount);
void QHelpContentWidget_ColumnMoved(void* ptr);
void QHelpContentWidget_ColumnMovedDefault(void* ptr);
void QHelpContentWidget_ColumnResized(void* ptr, int column, int oldSize, int newSize);
void QHelpContentWidget_ColumnResizedDefault(void* ptr, int column, int oldSize, int newSize);
void QHelpContentWidget_CurrentChanged(void* ptr, void* current, void* previous);
void QHelpContentWidget_CurrentChangedDefault(void* ptr, void* current, void* previous);
void QHelpContentWidget_DragMoveEvent(void* ptr, void* event);
void QHelpContentWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_DrawBranches(void* ptr, void* painter, void* rect, void* index);
void QHelpContentWidget_DrawBranchesDefault(void* ptr, void* painter, void* rect, void* index);
void QHelpContentWidget_DrawRow(void* ptr, void* painter, void* option, void* index);
void QHelpContentWidget_DrawRowDefault(void* ptr, void* painter, void* option, void* index);
void QHelpContentWidget_ExpandAll(void* ptr);
void QHelpContentWidget_ExpandAllDefault(void* ptr);
void QHelpContentWidget_ExpandToDepth(void* ptr, int depth);
void QHelpContentWidget_ExpandToDepthDefault(void* ptr, int depth);
void QHelpContentWidget_HideColumn(void* ptr, int column);
void QHelpContentWidget_HideColumnDefault(void* ptr, int column);
int QHelpContentWidget_HorizontalOffset(void* ptr);
int QHelpContentWidget_HorizontalOffsetDefault(void* ptr);
void* QHelpContentWidget_IndexAt(void* ptr, void* point);
void* QHelpContentWidget_IndexAtDefault(void* ptr, void* point);
int QHelpContentWidget_IsIndexHidden(void* ptr, void* index);
int QHelpContentWidget_IsIndexHiddenDefault(void* ptr, void* index);
void QHelpContentWidget_KeyPressEvent(void* ptr, void* event);
void QHelpContentWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpContentWidget_KeyboardSearch(void* ptr, char* search);
void QHelpContentWidget_KeyboardSearchDefault(void* ptr, char* search);
void QHelpContentWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QHelpContentWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpContentWidget_MouseMoveEvent(void* ptr, void* event);
void QHelpContentWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_MousePressEvent(void* ptr, void* event);
void QHelpContentWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpContentWidget_MouseReleaseEvent(void* ptr, void* event);
void QHelpContentWidget_MouseReleaseEventDefault(void* ptr, void* event);
void* QHelpContentWidget_MoveCursor(void* ptr, int cursorAction, int modifiers);
void* QHelpContentWidget_MoveCursorDefault(void* ptr, int cursorAction, int modifiers);
void QHelpContentWidget_PaintEvent(void* ptr, void* event);
void QHelpContentWidget_PaintEventDefault(void* ptr, void* event);
void QHelpContentWidget_Reset(void* ptr);
void QHelpContentWidget_ResetDefault(void* ptr);
void QHelpContentWidget_ResizeColumnToContents(void* ptr, int column);
void QHelpContentWidget_ResizeColumnToContentsDefault(void* ptr, int column);
void QHelpContentWidget_RowsAboutToBeRemoved(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsAboutToBeRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsInserted(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsInsertedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsRemoved(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_RowsRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpContentWidget_ScrollContentsBy(void* ptr, int dx, int dy);
void QHelpContentWidget_ScrollContentsByDefault(void* ptr, int dx, int dy);
void QHelpContentWidget_ScrollTo(void* ptr, void* index, int hint);
void QHelpContentWidget_ScrollToDefault(void* ptr, void* index, int hint);
void QHelpContentWidget_SelectAll(void* ptr);
void QHelpContentWidget_SelectAllDefault(void* ptr);
void QHelpContentWidget_SelectionChanged(void* ptr, void* selected, void* deselected);
void QHelpContentWidget_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void QHelpContentWidget_SetModel(void* ptr, void* model);
void QHelpContentWidget_SetModelDefault(void* ptr, void* model);
void QHelpContentWidget_SetRootIndex(void* ptr, void* index);
void QHelpContentWidget_SetRootIndexDefault(void* ptr, void* index);
void QHelpContentWidget_SetSelection(void* ptr, void* rect, int command);
void QHelpContentWidget_SetSelectionDefault(void* ptr, void* rect, int command);
void QHelpContentWidget_SetSelectionModel(void* ptr, void* selectionModel);
void QHelpContentWidget_SetSelectionModelDefault(void* ptr, void* selectionModel);
void QHelpContentWidget_ShowColumn(void* ptr, int column);
void QHelpContentWidget_ShowColumnDefault(void* ptr, int column);
int QHelpContentWidget_SizeHintForColumn(void* ptr, int column);
int QHelpContentWidget_SizeHintForColumnDefault(void* ptr, int column);
void QHelpContentWidget_UpdateGeometries(void* ptr);
void QHelpContentWidget_UpdateGeometriesDefault(void* ptr);
int QHelpContentWidget_VerticalOffset(void* ptr);
int QHelpContentWidget_VerticalOffsetDefault(void* ptr);
int QHelpContentWidget_ViewportEvent(void* ptr, void* event);
int QHelpContentWidget_ViewportEventDefault(void* ptr, void* event);
void* QHelpContentWidget_ViewportSizeHint(void* ptr);
void* QHelpContentWidget_ViewportSizeHintDefault(void* ptr);
void* QHelpContentWidget_VisualRect(void* ptr, void* index);
void* QHelpContentWidget_VisualRectDefault(void* ptr, void* index);
void* QHelpContentWidget_VisualRegionForSelection(void* ptr, void* selection);
void* QHelpContentWidget_VisualRegionForSelectionDefault(void* ptr, void* selection);
void QHelpContentWidget_DragLeaveEvent(void* ptr, void* event);
void QHelpContentWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpContentWidget_ClearSelection(void* ptr);
void QHelpContentWidget_ClearSelectionDefault(void* ptr);
void QHelpContentWidget_CloseEditor(void* ptr, void* editor, int hint);
void QHelpContentWidget_CloseEditorDefault(void* ptr, void* editor, int hint);
void QHelpContentWidget_CommitData(void* ptr, void* editor);
void QHelpContentWidget_CommitDataDefault(void* ptr, void* editor);
void QHelpContentWidget_DragEnterEvent(void* ptr, void* event);
void QHelpContentWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpContentWidget_DropEvent(void* ptr, void* event);
void QHelpContentWidget_DropEventDefault(void* ptr, void* event);
void QHelpContentWidget_Edit(void* ptr, void* index);
void QHelpContentWidget_EditDefault(void* ptr, void* index);
int QHelpContentWidget_Edit2(void* ptr, void* index, int trigger, void* event);
int QHelpContentWidget_Edit2Default(void* ptr, void* index, int trigger, void* event);
void QHelpContentWidget_EditorDestroyed(void* ptr, void* editor);
void QHelpContentWidget_EditorDestroyedDefault(void* ptr, void* editor);
void QHelpContentWidget_FocusInEvent(void* ptr, void* event);
void QHelpContentWidget_FocusInEventDefault(void* ptr, void* event);
int QHelpContentWidget_FocusNextPrevChild(void* ptr, int next);
int QHelpContentWidget_FocusNextPrevChildDefault(void* ptr, int next);
void QHelpContentWidget_FocusOutEvent(void* ptr, void* event);
void QHelpContentWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpContentWidget_InputMethodEvent(void* ptr, void* event);
void QHelpContentWidget_InputMethodEventDefault(void* ptr, void* event);
void* QHelpContentWidget_InputMethodQuery(void* ptr, int query);
void* QHelpContentWidget_InputMethodQueryDefault(void* ptr, int query);
void QHelpContentWidget_ResizeEvent(void* ptr, void* event);
void QHelpContentWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpContentWidget_ScrollToBottom(void* ptr);
void QHelpContentWidget_ScrollToBottomDefault(void* ptr);
void QHelpContentWidget_ScrollToTop(void* ptr);
void QHelpContentWidget_ScrollToTopDefault(void* ptr);
int QHelpContentWidget_SelectionCommand(void* ptr, void* index, void* event);
int QHelpContentWidget_SelectionCommandDefault(void* ptr, void* index, void* event);
void QHelpContentWidget_SetCurrentIndex(void* ptr, void* index);
void QHelpContentWidget_SetCurrentIndexDefault(void* ptr, void* index);
int QHelpContentWidget_SizeHintForRow(void* ptr, int row);
int QHelpContentWidget_SizeHintForRowDefault(void* ptr, int row);
void QHelpContentWidget_StartDrag(void* ptr, int supportedActions);
void QHelpContentWidget_StartDragDefault(void* ptr, int supportedActions);
void QHelpContentWidget_Update(void* ptr, void* index);
void QHelpContentWidget_UpdateDefault(void* ptr, void* index);
void* QHelpContentWidget_ViewOptions(void* ptr);
void* QHelpContentWidget_ViewOptionsDefault(void* ptr);
void QHelpContentWidget_ContextMenuEvent(void* ptr, void* e);
void QHelpContentWidget_ContextMenuEventDefault(void* ptr, void* e);
void* QHelpContentWidget_MinimumSizeHint(void* ptr);
void* QHelpContentWidget_MinimumSizeHintDefault(void* ptr);
void QHelpContentWidget_SetupViewport(void* ptr, void* viewport);
void QHelpContentWidget_SetupViewportDefault(void* ptr, void* viewport);
void* QHelpContentWidget_SizeHint(void* ptr);
void* QHelpContentWidget_SizeHintDefault(void* ptr);
void QHelpContentWidget_WheelEvent(void* ptr, void* e);
void QHelpContentWidget_WheelEventDefault(void* ptr, void* e);
void QHelpContentWidget_ChangeEvent(void* ptr, void* ev);
void QHelpContentWidget_ChangeEventDefault(void* ptr, void* ev);
void QHelpContentWidget_ActionEvent(void* ptr, void* event);
void QHelpContentWidget_ActionEventDefault(void* ptr, void* event);
void QHelpContentWidget_EnterEvent(void* ptr, void* event);
void QHelpContentWidget_EnterEventDefault(void* ptr, void* event);
void QHelpContentWidget_HideEvent(void* ptr, void* event);
void QHelpContentWidget_HideEventDefault(void* ptr, void* event);
void QHelpContentWidget_LeaveEvent(void* ptr, void* event);
void QHelpContentWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpContentWidget_MoveEvent(void* ptr, void* event);
void QHelpContentWidget_MoveEventDefault(void* ptr, void* event);
void QHelpContentWidget_SetEnabled(void* ptr, int vbo);
void QHelpContentWidget_SetEnabledDefault(void* ptr, int vbo);
void QHelpContentWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QHelpContentWidget_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QHelpContentWidget_SetVisible(void* ptr, int visible);
void QHelpContentWidget_SetVisibleDefault(void* ptr, int visible);
void QHelpContentWidget_SetWindowModified(void* ptr, int vbo);
void QHelpContentWidget_SetWindowModifiedDefault(void* ptr, int vbo);
void QHelpContentWidget_SetWindowTitle(void* ptr, char* vqs);
void QHelpContentWidget_SetWindowTitleDefault(void* ptr, char* vqs);
void QHelpContentWidget_ShowEvent(void* ptr, void* event);
void QHelpContentWidget_ShowEventDefault(void* ptr, void* event);
int QHelpContentWidget_Close(void* ptr);
int QHelpContentWidget_CloseDefault(void* ptr);
void QHelpContentWidget_CloseEvent(void* ptr, void* event);
void QHelpContentWidget_CloseEventDefault(void* ptr, void* event);
int QHelpContentWidget_HasHeightForWidth(void* ptr);
int QHelpContentWidget_HasHeightForWidthDefault(void* ptr);
int QHelpContentWidget_HeightForWidth(void* ptr, int w);
int QHelpContentWidget_HeightForWidthDefault(void* ptr, int w);
void QHelpContentWidget_Hide(void* ptr);
void QHelpContentWidget_HideDefault(void* ptr);
void QHelpContentWidget_KeyReleaseEvent(void* ptr, void* event);
void QHelpContentWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpContentWidget_Lower(void* ptr);
void QHelpContentWidget_LowerDefault(void* ptr);
int QHelpContentWidget_NativeEvent(void* ptr, char* eventType, void* message, long result);
int QHelpContentWidget_NativeEventDefault(void* ptr, char* eventType, void* message, long result);
void QHelpContentWidget_Raise(void* ptr);
void QHelpContentWidget_RaiseDefault(void* ptr);
void QHelpContentWidget_Repaint(void* ptr);
void QHelpContentWidget_RepaintDefault(void* ptr);
void QHelpContentWidget_SetDisabled(void* ptr, int disable);
void QHelpContentWidget_SetDisabledDefault(void* ptr, int disable);
void QHelpContentWidget_SetFocus2(void* ptr);
void QHelpContentWidget_SetFocus2Default(void* ptr);
void QHelpContentWidget_SetHidden(void* ptr, int hidden);
void QHelpContentWidget_SetHiddenDefault(void* ptr, int hidden);
void QHelpContentWidget_Show(void* ptr);
void QHelpContentWidget_ShowDefault(void* ptr);
void QHelpContentWidget_ShowFullScreen(void* ptr);
void QHelpContentWidget_ShowFullScreenDefault(void* ptr);
void QHelpContentWidget_ShowMaximized(void* ptr);
void QHelpContentWidget_ShowMaximizedDefault(void* ptr);
void QHelpContentWidget_ShowMinimized(void* ptr);
void QHelpContentWidget_ShowMinimizedDefault(void* ptr);
void QHelpContentWidget_ShowNormal(void* ptr);
void QHelpContentWidget_ShowNormalDefault(void* ptr);
void QHelpContentWidget_TabletEvent(void* ptr, void* event);
void QHelpContentWidget_TabletEventDefault(void* ptr, void* event);
void QHelpContentWidget_UpdateMicroFocus(void* ptr);
void QHelpContentWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpContentWidget_ChildEvent(void* ptr, void* event);
void QHelpContentWidget_ChildEventDefault(void* ptr, void* event);
void QHelpContentWidget_ConnectNotify(void* ptr, void* sign);
void QHelpContentWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpContentWidget_CustomEvent(void* ptr, void* event);
void QHelpContentWidget_CustomEventDefault(void* ptr, void* event);
void QHelpContentWidget_DeleteLater(void* ptr);
void QHelpContentWidget_DeleteLaterDefault(void* ptr);
void QHelpContentWidget_DisconnectNotify(void* ptr, void* sign);
void QHelpContentWidget_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpContentWidget_EventFilter(void* ptr, void* watched, void* event);
int QHelpContentWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpContentWidget_MetaObject(void* ptr);
void* QHelpContentWidget_MetaObjectDefault(void* ptr);
void* QHelpEngine_NewQHelpEngine(char* collectionFile, void* parent);
void* QHelpEngine_ContentModel(void* ptr);
void* QHelpEngine_ContentWidget(void* ptr);
void* QHelpEngine_IndexModel(void* ptr);
void* QHelpEngine_IndexWidget(void* ptr);
void* QHelpEngine_SearchEngine(void* ptr);
void QHelpEngine_DestroyQHelpEngine(void* ptr);
void QHelpEngine_TimerEvent(void* ptr, void* event);
void QHelpEngine_TimerEventDefault(void* ptr, void* event);
void QHelpEngine_ChildEvent(void* ptr, void* event);
void QHelpEngine_ChildEventDefault(void* ptr, void* event);
void QHelpEngine_ConnectNotify(void* ptr, void* sign);
void QHelpEngine_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpEngine_CustomEvent(void* ptr, void* event);
void QHelpEngine_CustomEventDefault(void* ptr, void* event);
void QHelpEngine_DeleteLater(void* ptr);
void QHelpEngine_DeleteLaterDefault(void* ptr);
void QHelpEngine_DisconnectNotify(void* ptr, void* sign);
void QHelpEngine_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpEngine_Event(void* ptr, void* e);
int QHelpEngine_EventDefault(void* ptr, void* e);
int QHelpEngine_EventFilter(void* ptr, void* watched, void* event);
int QHelpEngine_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpEngine_MetaObject(void* ptr);
void* QHelpEngine_MetaObjectDefault(void* ptr);
int QHelpEngineCore_AutoSaveFilter(void* ptr);
char* QHelpEngineCore_CollectionFile(void* ptr);
char* QHelpEngineCore_CurrentFilter(void* ptr);
void QHelpEngineCore_SetAutoSaveFilter(void* ptr, int save);
void QHelpEngineCore_SetCollectionFile(void* ptr, char* fileName);
void QHelpEngineCore_SetCurrentFilter(void* ptr, char* filterName);
void* QHelpEngineCore_NewQHelpEngineCore(char* collectionFile, void* parent);
int QHelpEngineCore_AddCustomFilter(void* ptr, char* filterName, char* attributes);
int QHelpEngineCore_CopyCollectionFile(void* ptr, char* fileName);
void QHelpEngineCore_ConnectCurrentFilterChanged(void* ptr);
void QHelpEngineCore_DisconnectCurrentFilterChanged(void* ptr);
void QHelpEngineCore_CurrentFilterChanged(void* ptr, char* newFilter);
char* QHelpEngineCore_CustomFilters(void* ptr);
void* QHelpEngineCore_CustomValue(void* ptr, char* key, void* defaultValue);
char* QHelpEngineCore_DocumentationFileName(void* ptr, char* namespaceName);
char* QHelpEngineCore_Error(void* ptr);
char* QHelpEngineCore_FileData(void* ptr, void* url);
char* QHelpEngineCore_FilterAttributes(void* ptr);
char* QHelpEngineCore_FilterAttributes2(void* ptr, char* filterName);
void* QHelpEngineCore_FindFile(void* ptr, void* url);
void* QHelpEngineCore_QHelpEngineCore_MetaData(char* documentationFileName, char* name);
char* QHelpEngineCore_QHelpEngineCore_NamespaceName(char* documentationFileName);
void QHelpEngineCore_ConnectReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_DisconnectReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_ReadersAboutToBeInvalidated(void* ptr);
int QHelpEngineCore_RegisterDocumentation(void* ptr, char* documentationFileName);
char* QHelpEngineCore_RegisteredDocumentations(void* ptr);
int QHelpEngineCore_RemoveCustomFilter(void* ptr, char* filterName);
int QHelpEngineCore_RemoveCustomValue(void* ptr, char* key);
int QHelpEngineCore_SetCustomValue(void* ptr, char* key, void* value);
int QHelpEngineCore_SetupData(void* ptr);
void QHelpEngineCore_ConnectSetupFinished(void* ptr);
void QHelpEngineCore_DisconnectSetupFinished(void* ptr);
void QHelpEngineCore_SetupFinished(void* ptr);
void QHelpEngineCore_ConnectSetupStarted(void* ptr);
void QHelpEngineCore_DisconnectSetupStarted(void* ptr);
void QHelpEngineCore_SetupStarted(void* ptr);
int QHelpEngineCore_UnregisterDocumentation(void* ptr, char* namespaceName);
void QHelpEngineCore_ConnectWarning(void* ptr);
void QHelpEngineCore_DisconnectWarning(void* ptr);
void QHelpEngineCore_Warning(void* ptr, char* msg);
void QHelpEngineCore_DestroyQHelpEngineCore(void* ptr);
void QHelpEngineCore_TimerEvent(void* ptr, void* event);
void QHelpEngineCore_TimerEventDefault(void* ptr, void* event);
void QHelpEngineCore_ChildEvent(void* ptr, void* event);
void QHelpEngineCore_ChildEventDefault(void* ptr, void* event);
void QHelpEngineCore_ConnectNotify(void* ptr, void* sign);
void QHelpEngineCore_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpEngineCore_CustomEvent(void* ptr, void* event);
void QHelpEngineCore_CustomEventDefault(void* ptr, void* event);
void QHelpEngineCore_DeleteLater(void* ptr);
void QHelpEngineCore_DeleteLaterDefault(void* ptr);
void QHelpEngineCore_DisconnectNotify(void* ptr, void* sign);
void QHelpEngineCore_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpEngineCore_Event(void* ptr, void* e);
int QHelpEngineCore_EventDefault(void* ptr, void* e);
int QHelpEngineCore_EventFilter(void* ptr, void* watched, void* event);
int QHelpEngineCore_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpEngineCore_MetaObject(void* ptr);
void* QHelpEngineCore_MetaObjectDefault(void* ptr);
void QHelpIndexModel_CreateIndex(void* ptr, char* customFilterName);
void* QHelpIndexModel_Filter(void* ptr, char* filter, char* wildcard);
void QHelpIndexModel_ConnectIndexCreated(void* ptr);
void QHelpIndexModel_DisconnectIndexCreated(void* ptr);
void QHelpIndexModel_IndexCreated(void* ptr);
void QHelpIndexModel_ConnectIndexCreationStarted(void* ptr);
void QHelpIndexModel_DisconnectIndexCreationStarted(void* ptr);
void QHelpIndexModel_IndexCreationStarted(void* ptr);
int QHelpIndexModel_IsCreatingIndex(void* ptr);
void* QHelpIndexModel_Data(void* ptr, void* index, int role);
void* QHelpIndexModel_DataDefault(void* ptr, void* index, int role);
int QHelpIndexModel_Flags(void* ptr, void* index);
int QHelpIndexModel_FlagsDefault(void* ptr, void* index);
int QHelpIndexModel_InsertRows(void* ptr, int row, int count, void* parent);
int QHelpIndexModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
int QHelpIndexModel_RemoveRows(void* ptr, int row, int count, void* parent);
int QHelpIndexModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
int QHelpIndexModel_RowCount(void* ptr, void* parent);
int QHelpIndexModel_RowCountDefault(void* ptr, void* parent);
int QHelpIndexModel_SetData(void* ptr, void* index, void* value, int role);
int QHelpIndexModel_SetDataDefault(void* ptr, void* index, void* value, int role);
void* QHelpIndexModel_Sibling(void* ptr, int row, int column, void* idx);
void* QHelpIndexModel_SiblingDefault(void* ptr, int row, int column, void* idx);
void QHelpIndexModel_Sort(void* ptr, int column, int order);
void QHelpIndexModel_SortDefault(void* ptr, int column, int order);
int QHelpIndexModel_SupportedDropActions(void* ptr);
int QHelpIndexModel_SupportedDropActionsDefault(void* ptr);
void* QHelpIndexModel_Index(void* ptr, int row, int column, void* parent);
void* QHelpIndexModel_IndexDefault(void* ptr, int row, int column, void* parent);
int QHelpIndexModel_DropMimeData(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpIndexModel_DropMimeDataDefault(void* ptr, void* data, int action, int row, int column, void* parent);
void* QHelpIndexModel_Buddy(void* ptr, void* index);
void* QHelpIndexModel_BuddyDefault(void* ptr, void* index);
int QHelpIndexModel_CanDropMimeData(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpIndexModel_CanDropMimeDataDefault(void* ptr, void* data, int action, int row, int column, void* parent);
int QHelpIndexModel_CanFetchMore(void* ptr, void* parent);
int QHelpIndexModel_CanFetchMoreDefault(void* ptr, void* parent);
int QHelpIndexModel_ColumnCount(void* ptr, void* parent);
int QHelpIndexModel_ColumnCountDefault(void* ptr, void* parent);
void QHelpIndexModel_FetchMore(void* ptr, void* parent);
void QHelpIndexModel_FetchMoreDefault(void* ptr, void* parent);
int QHelpIndexModel_HasChildren(void* ptr, void* parent);
int QHelpIndexModel_HasChildrenDefault(void* ptr, void* parent);
void* QHelpIndexModel_HeaderData(void* ptr, int section, int orientation, int role);
void* QHelpIndexModel_HeaderDataDefault(void* ptr, int section, int orientation, int role);
int QHelpIndexModel_InsertColumns(void* ptr, int column, int count, void* parent);
int QHelpIndexModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char* QHelpIndexModel_MimeTypes(void* ptr);
char* QHelpIndexModel_MimeTypesDefault(void* ptr);
int QHelpIndexModel_MoveColumns(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
int QHelpIndexModel_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
int QHelpIndexModel_MoveRows(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
int QHelpIndexModel_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* QHelpIndexModel_Parent(void* ptr, void* index);
void* QHelpIndexModel_ParentDefault(void* ptr, void* index);
int QHelpIndexModel_RemoveColumns(void* ptr, int column, int count, void* parent);
int QHelpIndexModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
void QHelpIndexModel_ResetInternalData(void* ptr);
void QHelpIndexModel_ResetInternalDataDefault(void* ptr);
void QHelpIndexModel_Revert(void* ptr);
void QHelpIndexModel_RevertDefault(void* ptr);
int QHelpIndexModel_SetHeaderData(void* ptr, int section, int orientation, void* value, int role);
int QHelpIndexModel_SetHeaderDataDefault(void* ptr, int section, int orientation, void* value, int role);
void* QHelpIndexModel_Span(void* ptr, void* index);
void* QHelpIndexModel_SpanDefault(void* ptr, void* index);
int QHelpIndexModel_Submit(void* ptr);
int QHelpIndexModel_SubmitDefault(void* ptr);
int QHelpIndexModel_SupportedDragActions(void* ptr);
int QHelpIndexModel_SupportedDragActionsDefault(void* ptr);
void QHelpIndexModel_TimerEvent(void* ptr, void* event);
void QHelpIndexModel_TimerEventDefault(void* ptr, void* event);
void QHelpIndexModel_ChildEvent(void* ptr, void* event);
void QHelpIndexModel_ChildEventDefault(void* ptr, void* event);
void QHelpIndexModel_ConnectNotify(void* ptr, void* sign);
void QHelpIndexModel_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpIndexModel_CustomEvent(void* ptr, void* event);
void QHelpIndexModel_CustomEventDefault(void* ptr, void* event);
void QHelpIndexModel_DeleteLater(void* ptr);
void QHelpIndexModel_DeleteLaterDefault(void* ptr);
void QHelpIndexModel_DisconnectNotify(void* ptr, void* sign);
void QHelpIndexModel_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpIndexModel_Event(void* ptr, void* e);
int QHelpIndexModel_EventDefault(void* ptr, void* e);
int QHelpIndexModel_EventFilter(void* ptr, void* watched, void* event);
int QHelpIndexModel_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpIndexModel_MetaObject(void* ptr);
void* QHelpIndexModel_MetaObjectDefault(void* ptr);
void QHelpIndexWidget_ActivateCurrentItem(void* ptr);
void QHelpIndexWidget_FilterIndices(void* ptr, char* filter, char* wildcard);
void QHelpIndexWidget_ConnectLinkActivated(void* ptr);
void QHelpIndexWidget_DisconnectLinkActivated(void* ptr);
void QHelpIndexWidget_LinkActivated(void* ptr, void* link, char* keyword);
void QHelpIndexWidget_CurrentChanged(void* ptr, void* current, void* previous);
void QHelpIndexWidget_CurrentChangedDefault(void* ptr, void* current, void* previous);
void QHelpIndexWidget_DragLeaveEvent(void* ptr, void* e);
void QHelpIndexWidget_DragLeaveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_DragMoveEvent(void* ptr, void* e);
void QHelpIndexWidget_DragMoveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_DropEvent(void* ptr, void* e);
void QHelpIndexWidget_DropEventDefault(void* ptr, void* e);
int QHelpIndexWidget_HorizontalOffset(void* ptr);
int QHelpIndexWidget_HorizontalOffsetDefault(void* ptr);
void* QHelpIndexWidget_IndexAt(void* ptr, void* p);
void* QHelpIndexWidget_IndexAtDefault(void* ptr, void* p);
int QHelpIndexWidget_IsIndexHidden(void* ptr, void* index);
int QHelpIndexWidget_IsIndexHiddenDefault(void* ptr, void* index);
void QHelpIndexWidget_MouseMoveEvent(void* ptr, void* e);
void QHelpIndexWidget_MouseMoveEventDefault(void* ptr, void* e);
void QHelpIndexWidget_MouseReleaseEvent(void* ptr, void* e);
void QHelpIndexWidget_MouseReleaseEventDefault(void* ptr, void* e);
void* QHelpIndexWidget_MoveCursor(void* ptr, int cursorAction, int modifiers);
void* QHelpIndexWidget_MoveCursorDefault(void* ptr, int cursorAction, int modifiers);
void QHelpIndexWidget_PaintEvent(void* ptr, void* e);
void QHelpIndexWidget_PaintEventDefault(void* ptr, void* e);
void QHelpIndexWidget_ResizeEvent(void* ptr, void* e);
void QHelpIndexWidget_ResizeEventDefault(void* ptr, void* e);
void QHelpIndexWidget_RowsAboutToBeRemoved(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_RowsAboutToBeRemovedDefault(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_RowsInserted(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_RowsInsertedDefault(void* ptr, void* parent, int start, int end);
void QHelpIndexWidget_ScrollTo(void* ptr, void* index, int hint);
void QHelpIndexWidget_ScrollToDefault(void* ptr, void* index, int hint);
void QHelpIndexWidget_SelectionChanged(void* ptr, void* selected, void* deselected);
void QHelpIndexWidget_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void QHelpIndexWidget_SetSelection(void* ptr, void* rect, int command);
void QHelpIndexWidget_SetSelectionDefault(void* ptr, void* rect, int command);
void QHelpIndexWidget_StartDrag(void* ptr, int supportedActions);
void QHelpIndexWidget_StartDragDefault(void* ptr, int supportedActions);
void QHelpIndexWidget_UpdateGeometries(void* ptr);
void QHelpIndexWidget_UpdateGeometriesDefault(void* ptr);
int QHelpIndexWidget_VerticalOffset(void* ptr);
int QHelpIndexWidget_VerticalOffsetDefault(void* ptr);
void* QHelpIndexWidget_ViewOptions(void* ptr);
void* QHelpIndexWidget_ViewOptionsDefault(void* ptr);
void* QHelpIndexWidget_ViewportSizeHint(void* ptr);
void* QHelpIndexWidget_ViewportSizeHintDefault(void* ptr);
void* QHelpIndexWidget_VisualRect(void* ptr, void* index);
void* QHelpIndexWidget_VisualRectDefault(void* ptr, void* index);
void* QHelpIndexWidget_VisualRegionForSelection(void* ptr, void* selection);
void* QHelpIndexWidget_VisualRegionForSelectionDefault(void* ptr, void* selection);
void QHelpIndexWidget_WheelEvent(void* ptr, void* e);
void QHelpIndexWidget_WheelEventDefault(void* ptr, void* e);
int QHelpIndexWidget_ViewportEvent(void* ptr, void* event);
int QHelpIndexWidget_ViewportEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ClearSelection(void* ptr);
void QHelpIndexWidget_ClearSelectionDefault(void* ptr);
void QHelpIndexWidget_CloseEditor(void* ptr, void* editor, int hint);
void QHelpIndexWidget_CloseEditorDefault(void* ptr, void* editor, int hint);
void QHelpIndexWidget_CommitData(void* ptr, void* editor);
void QHelpIndexWidget_CommitDataDefault(void* ptr, void* editor);
void QHelpIndexWidget_DragEnterEvent(void* ptr, void* event);
void QHelpIndexWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpIndexWidget_Edit(void* ptr, void* index);
void QHelpIndexWidget_EditDefault(void* ptr, void* index);
int QHelpIndexWidget_Edit2(void* ptr, void* index, int trigger, void* event);
int QHelpIndexWidget_Edit2Default(void* ptr, void* index, int trigger, void* event);
void QHelpIndexWidget_EditorDestroyed(void* ptr, void* editor);
void QHelpIndexWidget_EditorDestroyedDefault(void* ptr, void* editor);
void QHelpIndexWidget_FocusInEvent(void* ptr, void* event);
void QHelpIndexWidget_FocusInEventDefault(void* ptr, void* event);
int QHelpIndexWidget_FocusNextPrevChild(void* ptr, int next);
int QHelpIndexWidget_FocusNextPrevChildDefault(void* ptr, int next);
void QHelpIndexWidget_FocusOutEvent(void* ptr, void* event);
void QHelpIndexWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpIndexWidget_InputMethodEvent(void* ptr, void* event);
void QHelpIndexWidget_InputMethodEventDefault(void* ptr, void* event);
void* QHelpIndexWidget_InputMethodQuery(void* ptr, int query);
void* QHelpIndexWidget_InputMethodQueryDefault(void* ptr, int query);
void QHelpIndexWidget_KeyPressEvent(void* ptr, void* event);
void QHelpIndexWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpIndexWidget_KeyboardSearch(void* ptr, char* search);
void QHelpIndexWidget_KeyboardSearchDefault(void* ptr, char* search);
void QHelpIndexWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QHelpIndexWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpIndexWidget_MousePressEvent(void* ptr, void* event);
void QHelpIndexWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpIndexWidget_Reset(void* ptr);
void QHelpIndexWidget_ResetDefault(void* ptr);
void QHelpIndexWidget_ScrollToBottom(void* ptr);
void QHelpIndexWidget_ScrollToBottomDefault(void* ptr);
void QHelpIndexWidget_ScrollToTop(void* ptr);
void QHelpIndexWidget_ScrollToTopDefault(void* ptr);
void QHelpIndexWidget_SelectAll(void* ptr);
void QHelpIndexWidget_SelectAllDefault(void* ptr);
int QHelpIndexWidget_SelectionCommand(void* ptr, void* index, void* event);
int QHelpIndexWidget_SelectionCommandDefault(void* ptr, void* index, void* event);
void QHelpIndexWidget_SetCurrentIndex(void* ptr, void* index);
void QHelpIndexWidget_SetCurrentIndexDefault(void* ptr, void* index);
void QHelpIndexWidget_SetModel(void* ptr, void* model);
void QHelpIndexWidget_SetModelDefault(void* ptr, void* model);
void QHelpIndexWidget_SetRootIndex(void* ptr, void* index);
void QHelpIndexWidget_SetRootIndexDefault(void* ptr, void* index);
void QHelpIndexWidget_SetSelectionModel(void* ptr, void* selectionModel);
void QHelpIndexWidget_SetSelectionModelDefault(void* ptr, void* selectionModel);
int QHelpIndexWidget_SizeHintForColumn(void* ptr, int column);
int QHelpIndexWidget_SizeHintForColumnDefault(void* ptr, int column);
int QHelpIndexWidget_SizeHintForRow(void* ptr, int row);
int QHelpIndexWidget_SizeHintForRowDefault(void* ptr, int row);
void QHelpIndexWidget_Update(void* ptr, void* index);
void QHelpIndexWidget_UpdateDefault(void* ptr, void* index);
void QHelpIndexWidget_ContextMenuEvent(void* ptr, void* e);
void QHelpIndexWidget_ContextMenuEventDefault(void* ptr, void* e);
void* QHelpIndexWidget_MinimumSizeHint(void* ptr);
void* QHelpIndexWidget_MinimumSizeHintDefault(void* ptr);
void QHelpIndexWidget_ScrollContentsBy(void* ptr, int dx, int dy);
void QHelpIndexWidget_ScrollContentsByDefault(void* ptr, int dx, int dy);
void QHelpIndexWidget_SetupViewport(void* ptr, void* viewport);
void QHelpIndexWidget_SetupViewportDefault(void* ptr, void* viewport);
void* QHelpIndexWidget_SizeHint(void* ptr);
void* QHelpIndexWidget_SizeHintDefault(void* ptr);
void QHelpIndexWidget_ChangeEvent(void* ptr, void* ev);
void QHelpIndexWidget_ChangeEventDefault(void* ptr, void* ev);
void QHelpIndexWidget_ActionEvent(void* ptr, void* event);
void QHelpIndexWidget_ActionEventDefault(void* ptr, void* event);
void QHelpIndexWidget_EnterEvent(void* ptr, void* event);
void QHelpIndexWidget_EnterEventDefault(void* ptr, void* event);
void QHelpIndexWidget_HideEvent(void* ptr, void* event);
void QHelpIndexWidget_HideEventDefault(void* ptr, void* event);
void QHelpIndexWidget_LeaveEvent(void* ptr, void* event);
void QHelpIndexWidget_LeaveEventDefault(void* ptr, void* event);
void QHelpIndexWidget_MoveEvent(void* ptr, void* event);
void QHelpIndexWidget_MoveEventDefault(void* ptr, void* event);
void QHelpIndexWidget_SetEnabled(void* ptr, int vbo);
void QHelpIndexWidget_SetEnabledDefault(void* ptr, int vbo);
void QHelpIndexWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QHelpIndexWidget_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QHelpIndexWidget_SetVisible(void* ptr, int visible);
void QHelpIndexWidget_SetVisibleDefault(void* ptr, int visible);
void QHelpIndexWidget_SetWindowModified(void* ptr, int vbo);
void QHelpIndexWidget_SetWindowModifiedDefault(void* ptr, int vbo);
void QHelpIndexWidget_SetWindowTitle(void* ptr, char* vqs);
void QHelpIndexWidget_SetWindowTitleDefault(void* ptr, char* vqs);
void QHelpIndexWidget_ShowEvent(void* ptr, void* event);
void QHelpIndexWidget_ShowEventDefault(void* ptr, void* event);
int QHelpIndexWidget_Close(void* ptr);
int QHelpIndexWidget_CloseDefault(void* ptr);
void QHelpIndexWidget_CloseEvent(void* ptr, void* event);
void QHelpIndexWidget_CloseEventDefault(void* ptr, void* event);
int QHelpIndexWidget_HasHeightForWidth(void* ptr);
int QHelpIndexWidget_HasHeightForWidthDefault(void* ptr);
int QHelpIndexWidget_HeightForWidth(void* ptr, int w);
int QHelpIndexWidget_HeightForWidthDefault(void* ptr, int w);
void QHelpIndexWidget_Hide(void* ptr);
void QHelpIndexWidget_HideDefault(void* ptr);
void QHelpIndexWidget_KeyReleaseEvent(void* ptr, void* event);
void QHelpIndexWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpIndexWidget_Lower(void* ptr);
void QHelpIndexWidget_LowerDefault(void* ptr);
int QHelpIndexWidget_NativeEvent(void* ptr, char* eventType, void* message, long result);
int QHelpIndexWidget_NativeEventDefault(void* ptr, char* eventType, void* message, long result);
void QHelpIndexWidget_Raise(void* ptr);
void QHelpIndexWidget_RaiseDefault(void* ptr);
void QHelpIndexWidget_Repaint(void* ptr);
void QHelpIndexWidget_RepaintDefault(void* ptr);
void QHelpIndexWidget_SetDisabled(void* ptr, int disable);
void QHelpIndexWidget_SetDisabledDefault(void* ptr, int disable);
void QHelpIndexWidget_SetFocus2(void* ptr);
void QHelpIndexWidget_SetFocus2Default(void* ptr);
void QHelpIndexWidget_SetHidden(void* ptr, int hidden);
void QHelpIndexWidget_SetHiddenDefault(void* ptr, int hidden);
void QHelpIndexWidget_Show(void* ptr);
void QHelpIndexWidget_ShowDefault(void* ptr);
void QHelpIndexWidget_ShowFullScreen(void* ptr);
void QHelpIndexWidget_ShowFullScreenDefault(void* ptr);
void QHelpIndexWidget_ShowMaximized(void* ptr);
void QHelpIndexWidget_ShowMaximizedDefault(void* ptr);
void QHelpIndexWidget_ShowMinimized(void* ptr);
void QHelpIndexWidget_ShowMinimizedDefault(void* ptr);
void QHelpIndexWidget_ShowNormal(void* ptr);
void QHelpIndexWidget_ShowNormalDefault(void* ptr);
void QHelpIndexWidget_TabletEvent(void* ptr, void* event);
void QHelpIndexWidget_TabletEventDefault(void* ptr, void* event);
void QHelpIndexWidget_UpdateMicroFocus(void* ptr);
void QHelpIndexWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpIndexWidget_ChildEvent(void* ptr, void* event);
void QHelpIndexWidget_ChildEventDefault(void* ptr, void* event);
void QHelpIndexWidget_ConnectNotify(void* ptr, void* sign);
void QHelpIndexWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpIndexWidget_CustomEvent(void* ptr, void* event);
void QHelpIndexWidget_CustomEventDefault(void* ptr, void* event);
void QHelpIndexWidget_DeleteLater(void* ptr);
void QHelpIndexWidget_DeleteLaterDefault(void* ptr);
void QHelpIndexWidget_DisconnectNotify(void* ptr, void* sign);
void QHelpIndexWidget_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpIndexWidget_EventFilter(void* ptr, void* watched, void* event);
int QHelpIndexWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpIndexWidget_MetaObject(void* ptr);
void* QHelpIndexWidget_MetaObjectDefault(void* ptr);
void* QHelpSearchEngine_NewQHelpSearchEngine(void* helpEngine, void* parent);
void QHelpSearchEngine_CancelIndexing(void* ptr);
void QHelpSearchEngine_CancelSearching(void* ptr);
int QHelpSearchEngine_HitCount(void* ptr);
void QHelpSearchEngine_ConnectIndexingFinished(void* ptr);
void QHelpSearchEngine_DisconnectIndexingFinished(void* ptr);
void QHelpSearchEngine_IndexingFinished(void* ptr);
void QHelpSearchEngine_ConnectIndexingStarted(void* ptr);
void QHelpSearchEngine_DisconnectIndexingStarted(void* ptr);
void QHelpSearchEngine_IndexingStarted(void* ptr);
void* QHelpSearchEngine_QueryWidget(void* ptr);
void QHelpSearchEngine_ReindexDocumentation(void* ptr);
void* QHelpSearchEngine_ResultWidget(void* ptr);
void QHelpSearchEngine_ConnectSearchingFinished(void* ptr);
void QHelpSearchEngine_DisconnectSearchingFinished(void* ptr);
void QHelpSearchEngine_SearchingFinished(void* ptr, int hits);
void QHelpSearchEngine_ConnectSearchingStarted(void* ptr);
void QHelpSearchEngine_DisconnectSearchingStarted(void* ptr);
void QHelpSearchEngine_SearchingStarted(void* ptr);
void QHelpSearchEngine_DestroyQHelpSearchEngine(void* ptr);
void QHelpSearchEngine_TimerEvent(void* ptr, void* event);
void QHelpSearchEngine_TimerEventDefault(void* ptr, void* event);
void QHelpSearchEngine_ChildEvent(void* ptr, void* event);
void QHelpSearchEngine_ChildEventDefault(void* ptr, void* event);
void QHelpSearchEngine_ConnectNotify(void* ptr, void* sign);
void QHelpSearchEngine_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchEngine_CustomEvent(void* ptr, void* event);
void QHelpSearchEngine_CustomEventDefault(void* ptr, void* event);
void QHelpSearchEngine_DeleteLater(void* ptr);
void QHelpSearchEngine_DeleteLaterDefault(void* ptr);
void QHelpSearchEngine_DisconnectNotify(void* ptr, void* sign);
void QHelpSearchEngine_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpSearchEngine_Event(void* ptr, void* e);
int QHelpSearchEngine_EventDefault(void* ptr, void* e);
int QHelpSearchEngine_EventFilter(void* ptr, void* watched, void* event);
int QHelpSearchEngine_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpSearchEngine_MetaObject(void* ptr);
void* QHelpSearchEngine_MetaObjectDefault(void* ptr);
void* QHelpSearchQuery_NewQHelpSearchQuery();
void* QHelpSearchQuery_NewQHelpSearchQuery2(int field, char* wordList);
int QHelpSearchQueryWidget_IsCompactMode(void* ptr);
void* QHelpSearchQueryWidget_NewQHelpSearchQueryWidget(void* parent);
void QHelpSearchQueryWidget_CollapseExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ExpandExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ConnectSearch(void* ptr);
void QHelpSearchQueryWidget_DisconnectSearch(void* ptr);
void QHelpSearchQueryWidget_Search(void* ptr);
void QHelpSearchQueryWidget_DestroyQHelpSearchQueryWidget(void* ptr);
void QHelpSearchQueryWidget_ActionEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ActionEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragEnterEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragLeaveEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DragMoveEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DropEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_DropEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_EnterEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_EnterEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusInEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusOutEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_HideEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_HideEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_LeaveEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_LeaveEventDefault(void* ptr, void* event);
void* QHelpSearchQueryWidget_MinimumSizeHint(void* ptr);
void* QHelpSearchQueryWidget_MinimumSizeHintDefault(void* ptr);
void QHelpSearchQueryWidget_MoveEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_MoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_PaintEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_PaintEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_SetEnabled(void* ptr, int vbo);
void QHelpSearchQueryWidget_SetEnabledDefault(void* ptr, int vbo);
void QHelpSearchQueryWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QHelpSearchQueryWidget_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QHelpSearchQueryWidget_SetVisible(void* ptr, int visible);
void QHelpSearchQueryWidget_SetVisibleDefault(void* ptr, int visible);
void QHelpSearchQueryWidget_SetWindowModified(void* ptr, int vbo);
void QHelpSearchQueryWidget_SetWindowModifiedDefault(void* ptr, int vbo);
void QHelpSearchQueryWidget_SetWindowTitle(void* ptr, char* vqs);
void QHelpSearchQueryWidget_SetWindowTitleDefault(void* ptr, char* vqs);
void QHelpSearchQueryWidget_ShowEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ShowEventDefault(void* ptr, void* event);
void* QHelpSearchQueryWidget_SizeHint(void* ptr);
void* QHelpSearchQueryWidget_SizeHintDefault(void* ptr);
void QHelpSearchQueryWidget_ChangeEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ChangeEventDefault(void* ptr, void* event);
int QHelpSearchQueryWidget_Close(void* ptr);
int QHelpSearchQueryWidget_CloseDefault(void* ptr);
void QHelpSearchQueryWidget_CloseEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_CloseEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ContextMenuEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ContextMenuEventDefault(void* ptr, void* event);
int QHelpSearchQueryWidget_FocusNextPrevChild(void* ptr, int next);
int QHelpSearchQueryWidget_FocusNextPrevChildDefault(void* ptr, int next);
int QHelpSearchQueryWidget_HasHeightForWidth(void* ptr);
int QHelpSearchQueryWidget_HasHeightForWidthDefault(void* ptr);
int QHelpSearchQueryWidget_HeightForWidth(void* ptr, int w);
int QHelpSearchQueryWidget_HeightForWidthDefault(void* ptr, int w);
void QHelpSearchQueryWidget_Hide(void* ptr);
void QHelpSearchQueryWidget_HideDefault(void* ptr);
void QHelpSearchQueryWidget_InputMethodEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_InputMethodEventDefault(void* ptr, void* event);
void* QHelpSearchQueryWidget_InputMethodQuery(void* ptr, int query);
void* QHelpSearchQueryWidget_InputMethodQueryDefault(void* ptr, int query);
void QHelpSearchQueryWidget_KeyPressEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_KeyReleaseEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_Lower(void* ptr);
void QHelpSearchQueryWidget_LowerDefault(void* ptr);
void QHelpSearchQueryWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseMoveEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MousePressEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseReleaseEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_MouseReleaseEventDefault(void* ptr, void* event);
int QHelpSearchQueryWidget_NativeEvent(void* ptr, char* eventType, void* message, long result);
int QHelpSearchQueryWidget_NativeEventDefault(void* ptr, char* eventType, void* message, long result);
void QHelpSearchQueryWidget_Raise(void* ptr);
void QHelpSearchQueryWidget_RaiseDefault(void* ptr);
void QHelpSearchQueryWidget_Repaint(void* ptr);
void QHelpSearchQueryWidget_RepaintDefault(void* ptr);
void QHelpSearchQueryWidget_ResizeEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_SetDisabled(void* ptr, int disable);
void QHelpSearchQueryWidget_SetDisabledDefault(void* ptr, int disable);
void QHelpSearchQueryWidget_SetFocus2(void* ptr);
void QHelpSearchQueryWidget_SetFocus2Default(void* ptr);
void QHelpSearchQueryWidget_SetHidden(void* ptr, int hidden);
void QHelpSearchQueryWidget_SetHiddenDefault(void* ptr, int hidden);
void QHelpSearchQueryWidget_Show(void* ptr);
void QHelpSearchQueryWidget_ShowDefault(void* ptr);
void QHelpSearchQueryWidget_ShowFullScreen(void* ptr);
void QHelpSearchQueryWidget_ShowFullScreenDefault(void* ptr);
void QHelpSearchQueryWidget_ShowMaximized(void* ptr);
void QHelpSearchQueryWidget_ShowMaximizedDefault(void* ptr);
void QHelpSearchQueryWidget_ShowMinimized(void* ptr);
void QHelpSearchQueryWidget_ShowMinimizedDefault(void* ptr);
void QHelpSearchQueryWidget_ShowNormal(void* ptr);
void QHelpSearchQueryWidget_ShowNormalDefault(void* ptr);
void QHelpSearchQueryWidget_TabletEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_TabletEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_Update(void* ptr);
void QHelpSearchQueryWidget_UpdateDefault(void* ptr);
void QHelpSearchQueryWidget_UpdateMicroFocus(void* ptr);
void QHelpSearchQueryWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpSearchQueryWidget_WheelEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_WheelEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_TimerEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_TimerEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ChildEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_ChildEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_ConnectNotify(void* ptr, void* sign);
void QHelpSearchQueryWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchQueryWidget_CustomEvent(void* ptr, void* event);
void QHelpSearchQueryWidget_CustomEventDefault(void* ptr, void* event);
void QHelpSearchQueryWidget_DeleteLater(void* ptr);
void QHelpSearchQueryWidget_DeleteLaterDefault(void* ptr);
void QHelpSearchQueryWidget_DisconnectNotify(void* ptr, void* sign);
void QHelpSearchQueryWidget_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpSearchQueryWidget_EventFilter(void* ptr, void* watched, void* event);
int QHelpSearchQueryWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpSearchQueryWidget_MetaObject(void* ptr);
void* QHelpSearchQueryWidget_MetaObjectDefault(void* ptr);
void* QHelpSearchResultWidget_LinkAt(void* ptr, void* point);
void QHelpSearchResultWidget_ConnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_DisconnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_RequestShowLink(void* ptr, void* link);
void QHelpSearchResultWidget_DestroyQHelpSearchResultWidget(void* ptr);
void QHelpSearchResultWidget_ActionEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ActionEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragEnterEvent(void* ptr, void* event);
void QHelpSearchResultWidget_DragEnterEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragLeaveEvent(void* ptr, void* event);
void QHelpSearchResultWidget_DragLeaveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DragMoveEvent(void* ptr, void* event);
void QHelpSearchResultWidget_DragMoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DropEvent(void* ptr, void* event);
void QHelpSearchResultWidget_DropEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_EnterEvent(void* ptr, void* event);
void QHelpSearchResultWidget_EnterEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_FocusInEvent(void* ptr, void* event);
void QHelpSearchResultWidget_FocusInEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_FocusOutEvent(void* ptr, void* event);
void QHelpSearchResultWidget_FocusOutEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_HideEvent(void* ptr, void* event);
void QHelpSearchResultWidget_HideEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_LeaveEvent(void* ptr, void* event);
void QHelpSearchResultWidget_LeaveEventDefault(void* ptr, void* event);
void* QHelpSearchResultWidget_MinimumSizeHint(void* ptr);
void* QHelpSearchResultWidget_MinimumSizeHintDefault(void* ptr);
void QHelpSearchResultWidget_MoveEvent(void* ptr, void* event);
void QHelpSearchResultWidget_MoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_PaintEvent(void* ptr, void* event);
void QHelpSearchResultWidget_PaintEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_SetEnabled(void* ptr, int vbo);
void QHelpSearchResultWidget_SetEnabledDefault(void* ptr, int vbo);
void QHelpSearchResultWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QHelpSearchResultWidget_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QHelpSearchResultWidget_SetVisible(void* ptr, int visible);
void QHelpSearchResultWidget_SetVisibleDefault(void* ptr, int visible);
void QHelpSearchResultWidget_SetWindowModified(void* ptr, int vbo);
void QHelpSearchResultWidget_SetWindowModifiedDefault(void* ptr, int vbo);
void QHelpSearchResultWidget_SetWindowTitle(void* ptr, char* vqs);
void QHelpSearchResultWidget_SetWindowTitleDefault(void* ptr, char* vqs);
void QHelpSearchResultWidget_ShowEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ShowEventDefault(void* ptr, void* event);
void* QHelpSearchResultWidget_SizeHint(void* ptr);
void* QHelpSearchResultWidget_SizeHintDefault(void* ptr);
void QHelpSearchResultWidget_ChangeEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ChangeEventDefault(void* ptr, void* event);
int QHelpSearchResultWidget_Close(void* ptr);
int QHelpSearchResultWidget_CloseDefault(void* ptr);
void QHelpSearchResultWidget_CloseEvent(void* ptr, void* event);
void QHelpSearchResultWidget_CloseEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ContextMenuEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ContextMenuEventDefault(void* ptr, void* event);
int QHelpSearchResultWidget_FocusNextPrevChild(void* ptr, int next);
int QHelpSearchResultWidget_FocusNextPrevChildDefault(void* ptr, int next);
int QHelpSearchResultWidget_HasHeightForWidth(void* ptr);
int QHelpSearchResultWidget_HasHeightForWidthDefault(void* ptr);
int QHelpSearchResultWidget_HeightForWidth(void* ptr, int w);
int QHelpSearchResultWidget_HeightForWidthDefault(void* ptr, int w);
void QHelpSearchResultWidget_Hide(void* ptr);
void QHelpSearchResultWidget_HideDefault(void* ptr);
void QHelpSearchResultWidget_InputMethodEvent(void* ptr, void* event);
void QHelpSearchResultWidget_InputMethodEventDefault(void* ptr, void* event);
void* QHelpSearchResultWidget_InputMethodQuery(void* ptr, int query);
void* QHelpSearchResultWidget_InputMethodQueryDefault(void* ptr, int query);
void QHelpSearchResultWidget_KeyPressEvent(void* ptr, void* event);
void QHelpSearchResultWidget_KeyPressEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_KeyReleaseEvent(void* ptr, void* event);
void QHelpSearchResultWidget_KeyReleaseEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_Lower(void* ptr);
void QHelpSearchResultWidget_LowerDefault(void* ptr);
void QHelpSearchResultWidget_MouseDoubleClickEvent(void* ptr, void* event);
void QHelpSearchResultWidget_MouseDoubleClickEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MouseMoveEvent(void* ptr, void* event);
void QHelpSearchResultWidget_MouseMoveEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MousePressEvent(void* ptr, void* event);
void QHelpSearchResultWidget_MousePressEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_MouseReleaseEvent(void* ptr, void* event);
void QHelpSearchResultWidget_MouseReleaseEventDefault(void* ptr, void* event);
int QHelpSearchResultWidget_NativeEvent(void* ptr, char* eventType, void* message, long result);
int QHelpSearchResultWidget_NativeEventDefault(void* ptr, char* eventType, void* message, long result);
void QHelpSearchResultWidget_Raise(void* ptr);
void QHelpSearchResultWidget_RaiseDefault(void* ptr);
void QHelpSearchResultWidget_Repaint(void* ptr);
void QHelpSearchResultWidget_RepaintDefault(void* ptr);
void QHelpSearchResultWidget_ResizeEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ResizeEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_SetDisabled(void* ptr, int disable);
void QHelpSearchResultWidget_SetDisabledDefault(void* ptr, int disable);
void QHelpSearchResultWidget_SetFocus2(void* ptr);
void QHelpSearchResultWidget_SetFocus2Default(void* ptr);
void QHelpSearchResultWidget_SetHidden(void* ptr, int hidden);
void QHelpSearchResultWidget_SetHiddenDefault(void* ptr, int hidden);
void QHelpSearchResultWidget_Show(void* ptr);
void QHelpSearchResultWidget_ShowDefault(void* ptr);
void QHelpSearchResultWidget_ShowFullScreen(void* ptr);
void QHelpSearchResultWidget_ShowFullScreenDefault(void* ptr);
void QHelpSearchResultWidget_ShowMaximized(void* ptr);
void QHelpSearchResultWidget_ShowMaximizedDefault(void* ptr);
void QHelpSearchResultWidget_ShowMinimized(void* ptr);
void QHelpSearchResultWidget_ShowMinimizedDefault(void* ptr);
void QHelpSearchResultWidget_ShowNormal(void* ptr);
void QHelpSearchResultWidget_ShowNormalDefault(void* ptr);
void QHelpSearchResultWidget_TabletEvent(void* ptr, void* event);
void QHelpSearchResultWidget_TabletEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_Update(void* ptr);
void QHelpSearchResultWidget_UpdateDefault(void* ptr);
void QHelpSearchResultWidget_UpdateMicroFocus(void* ptr);
void QHelpSearchResultWidget_UpdateMicroFocusDefault(void* ptr);
void QHelpSearchResultWidget_WheelEvent(void* ptr, void* event);
void QHelpSearchResultWidget_WheelEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_TimerEvent(void* ptr, void* event);
void QHelpSearchResultWidget_TimerEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ChildEvent(void* ptr, void* event);
void QHelpSearchResultWidget_ChildEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_ConnectNotify(void* ptr, void* sign);
void QHelpSearchResultWidget_ConnectNotifyDefault(void* ptr, void* sign);
void QHelpSearchResultWidget_CustomEvent(void* ptr, void* event);
void QHelpSearchResultWidget_CustomEventDefault(void* ptr, void* event);
void QHelpSearchResultWidget_DeleteLater(void* ptr);
void QHelpSearchResultWidget_DeleteLaterDefault(void* ptr);
void QHelpSearchResultWidget_DisconnectNotify(void* ptr, void* sign);
void QHelpSearchResultWidget_DisconnectNotifyDefault(void* ptr, void* sign);
int QHelpSearchResultWidget_EventFilter(void* ptr, void* watched, void* event);
int QHelpSearchResultWidget_EventFilterDefault(void* ptr, void* watched, void* event);
void* QHelpSearchResultWidget_MetaObject(void* ptr);
void* QHelpSearchResultWidget_MetaObjectDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif