#ifdef __cplusplus
extern "C" {
#endif

void* QHelpContentItem_Child(void* ptr, int row);
int QHelpContentItem_ChildCount(void* ptr);
int QHelpContentItem_ChildPosition(void* ptr, void* child);
void* QHelpContentItem_Parent(void* ptr);
int QHelpContentItem_Row(void* ptr);
char* QHelpContentItem_Title(void* ptr);
void* QHelpContentItem_Url(void* ptr);
void QHelpContentItem_DestroyQHelpContentItem(void* ptr);
int QHelpContentModel_ColumnCount(void* ptr, void* parent);
void* QHelpContentModel_ContentItemAt(void* ptr, void* index);
void QHelpContentModel_ConnectContentsCreated(void* ptr);
void QHelpContentModel_DisconnectContentsCreated(void* ptr);
void QHelpContentModel_ConnectContentsCreationStarted(void* ptr);
void QHelpContentModel_DisconnectContentsCreationStarted(void* ptr);
void QHelpContentModel_CreateContents(void* ptr, char* customFilterName);
void* QHelpContentModel_Data(void* ptr, void* index, int role);
void* QHelpContentModel_Index(void* ptr, int row, int column, void* parent);
int QHelpContentModel_IsCreatingContents(void* ptr);
void* QHelpContentModel_Parent(void* ptr, void* index);
int QHelpContentModel_RowCount(void* ptr, void* parent);
void QHelpContentModel_DestroyQHelpContentModel(void* ptr);
void* QHelpContentWidget_IndexOf(void* ptr, void* link);
void QHelpContentWidget_ConnectLinkActivated(void* ptr);
void QHelpContentWidget_DisconnectLinkActivated(void* ptr);
void* QHelpEngine_NewQHelpEngine(char* collectionFile, void* parent);
void* QHelpEngine_ContentModel(void* ptr);
void* QHelpEngine_ContentWidget(void* ptr);
void* QHelpEngine_IndexModel(void* ptr);
void* QHelpEngine_IndexWidget(void* ptr);
void* QHelpEngine_SearchEngine(void* ptr);
void QHelpEngine_DestroyQHelpEngine(void* ptr);
int QHelpEngineCore_AutoSaveFilter(void* ptr);
char* QHelpEngineCore_CollectionFile(void* ptr);
char* QHelpEngineCore_CurrentFilter(void* ptr);
void QHelpEngineCore_SetAutoSaveFilter(void* ptr, int save);
void QHelpEngineCore_SetCollectionFile(void* ptr, char* fileName);
void QHelpEngineCore_SetCurrentFilter(void* ptr, char* filterName);
void* QHelpEngineCore_NewQHelpEngineCore(char* collectionFile, void* parent);
int QHelpEngineCore_AddCustomFilter(void* ptr, char* filterName, char* attributes);
int QHelpEngineCore_CopyCollectionFile(void* ptr, char* fileName);
void QHelpEngineCore_ConnectCurrentFilterChanged(void* ptr);
void QHelpEngineCore_DisconnectCurrentFilterChanged(void* ptr);
char* QHelpEngineCore_CustomFilters(void* ptr);
void* QHelpEngineCore_CustomValue(void* ptr, char* key, void* defaultValue);
char* QHelpEngineCore_DocumentationFileName(void* ptr, char* namespaceName);
char* QHelpEngineCore_Error(void* ptr);
void* QHelpEngineCore_FileData(void* ptr, void* url);
char* QHelpEngineCore_FilterAttributes(void* ptr);
char* QHelpEngineCore_FilterAttributes2(void* ptr, char* filterName);
void* QHelpEngineCore_FindFile(void* ptr, void* url);
void* QHelpEngineCore_QHelpEngineCore_MetaData(char* documentationFileName, char* name);
char* QHelpEngineCore_QHelpEngineCore_NamespaceName(char* documentationFileName);
void QHelpEngineCore_ConnectReadersAboutToBeInvalidated(void* ptr);
void QHelpEngineCore_DisconnectReadersAboutToBeInvalidated(void* ptr);
int QHelpEngineCore_RegisterDocumentation(void* ptr, char* documentationFileName);
char* QHelpEngineCore_RegisteredDocumentations(void* ptr);
int QHelpEngineCore_RemoveCustomFilter(void* ptr, char* filterName);
int QHelpEngineCore_RemoveCustomValue(void* ptr, char* key);
int QHelpEngineCore_SetCustomValue(void* ptr, char* key, void* value);
int QHelpEngineCore_SetupData(void* ptr);
void QHelpEngineCore_ConnectSetupFinished(void* ptr);
void QHelpEngineCore_DisconnectSetupFinished(void* ptr);
void QHelpEngineCore_ConnectSetupStarted(void* ptr);
void QHelpEngineCore_DisconnectSetupStarted(void* ptr);
int QHelpEngineCore_UnregisterDocumentation(void* ptr, char* namespaceName);
void QHelpEngineCore_ConnectWarning(void* ptr);
void QHelpEngineCore_DisconnectWarning(void* ptr);
void QHelpEngineCore_DestroyQHelpEngineCore(void* ptr);
void QHelpIndexModel_CreateIndex(void* ptr, char* customFilterName);
void* QHelpIndexModel_Filter(void* ptr, char* filter, char* wildcard);
void QHelpIndexModel_ConnectIndexCreated(void* ptr);
void QHelpIndexModel_DisconnectIndexCreated(void* ptr);
void QHelpIndexModel_ConnectIndexCreationStarted(void* ptr);
void QHelpIndexModel_DisconnectIndexCreationStarted(void* ptr);
int QHelpIndexModel_IsCreatingIndex(void* ptr);
void QHelpIndexWidget_ActivateCurrentItem(void* ptr);
void QHelpIndexWidget_FilterIndices(void* ptr, char* filter, char* wildcard);
void QHelpIndexWidget_ConnectLinkActivated(void* ptr);
void QHelpIndexWidget_DisconnectLinkActivated(void* ptr);
void* QHelpSearchEngine_NewQHelpSearchEngine(void* helpEngine, void* parent);
void QHelpSearchEngine_CancelIndexing(void* ptr);
void QHelpSearchEngine_CancelSearching(void* ptr);
int QHelpSearchEngine_HitCount(void* ptr);
void QHelpSearchEngine_ConnectIndexingFinished(void* ptr);
void QHelpSearchEngine_DisconnectIndexingFinished(void* ptr);
void QHelpSearchEngine_ConnectIndexingStarted(void* ptr);
void QHelpSearchEngine_DisconnectIndexingStarted(void* ptr);
void* QHelpSearchEngine_QueryWidget(void* ptr);
void QHelpSearchEngine_ReindexDocumentation(void* ptr);
void* QHelpSearchEngine_ResultWidget(void* ptr);
void QHelpSearchEngine_ConnectSearchingFinished(void* ptr);
void QHelpSearchEngine_DisconnectSearchingFinished(void* ptr);
void QHelpSearchEngine_ConnectSearchingStarted(void* ptr);
void QHelpSearchEngine_DisconnectSearchingStarted(void* ptr);
void QHelpSearchEngine_DestroyQHelpSearchEngine(void* ptr);
void* QHelpSearchQuery_NewQHelpSearchQuery();
void* QHelpSearchQuery_NewQHelpSearchQuery2(int field, char* wordList);
int QHelpSearchQueryWidget_IsCompactMode(void* ptr);
void* QHelpSearchQueryWidget_NewQHelpSearchQueryWidget(void* parent);
void QHelpSearchQueryWidget_CollapseExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ExpandExtendedSearch(void* ptr);
void QHelpSearchQueryWidget_ConnectSearch(void* ptr);
void QHelpSearchQueryWidget_DisconnectSearch(void* ptr);
void QHelpSearchQueryWidget_DestroyQHelpSearchQueryWidget(void* ptr);
void* QHelpSearchResultWidget_LinkAt(void* ptr, void* point);
void QHelpSearchResultWidget_ConnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_DisconnectRequestShowLink(void* ptr);
void QHelpSearchResultWidget_DestroyQHelpSearchResultWidget(void* ptr);

#ifdef __cplusplus
}
#endif