#ifdef __cplusplus
extern "C" {
#endif
#include "../cgoutil.h"

QtObjectPtr QOpenGLFunctions_4_4_Compatibility_NewQOpenGLFunctions_4_4_Compatibility();
int QOpenGLFunctions_4_4_Compatibility_InitializeOpenGLFunctions(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_DestroyQOpenGLFunctions_4_4_Compatibility(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlEnd(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlEndConditionalRender(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlEndList(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlEndTransformFeedback(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlFinish(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlFlush(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlInitNames(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlLoadIdentity(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPauseTransformFeedback(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPopAttrib(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPopClientAttrib(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPopDebugGroup(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPopMatrix(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPopName(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlPushMatrix(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlReleaseShaderCompiler(QtObjectPtr ptr);
void QOpenGLFunctions_4_4_Compatibility_GlResumeTransformFeedback(QtObjectPtr ptr);

#ifdef __cplusplus
}
#endif