#ifdef __cplusplus
extern "C" {
#endif
#include "../cgoutil.h"

QtObjectPtr QPainter_NewQPainter2(QtObjectPtr device);
int QPainter_Begin(QtObjectPtr ptr, QtObjectPtr device);
void QPainter_DrawArc(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawChord(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawConvexPolygon2(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawConvexPolygon(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawEllipse2(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_DrawEllipse(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_DrawGlyphRun(QtObjectPtr ptr, QtObjectPtr position, QtObjectPtr glyphs);
void QPainter_DrawImage3(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr image);
void QPainter_DrawImage(QtObjectPtr ptr, QtObjectPtr target, QtObjectPtr image, QtObjectPtr source, int flags);
void QPainter_DrawLines2(QtObjectPtr ptr, QtObjectPtr lines, int lineCount);
void QPainter_DrawPicture(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr picture);
void QPainter_DrawPie(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawPixmap5(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr pixmap);
void QPainter_DrawPixmap(QtObjectPtr ptr, QtObjectPtr target, QtObjectPtr pixmap, QtObjectPtr source);
void QPainter_DrawRects2(QtObjectPtr ptr, QtObjectPtr rectangles, int rectCount);
void QPainter_DrawRects(QtObjectPtr ptr, QtObjectPtr rectangles, int rectCount);
void QPainter_DrawText(QtObjectPtr ptr, QtObjectPtr position, char* text);
void QPainter_DrawText5(QtObjectPtr ptr, QtObjectPtr rectangle, int flags, char* text, QtObjectPtr boundingRect);
void QPainter_DrawText8(QtObjectPtr ptr, QtObjectPtr rectangle, char* text, QtObjectPtr option);
void QPainter_DrawText4(QtObjectPtr ptr, QtObjectPtr rectangle, int flags, char* text, QtObjectPtr boundingRect);
void QPainter_DrawTiledPixmap(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr pixmap, QtObjectPtr position);
void QPainter_EraseRect(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_FillRect5(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr brush);
void QPainter_FillRect6(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr color);
void QPainter_FillRect(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr brush);
void QPainter_FillRect7(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr color);
void QPainter_SetBackground(QtObjectPtr ptr, QtObjectPtr brush);
void QPainter_SetBrushOrigin(QtObjectPtr ptr, QtObjectPtr position);
void QPainter_SetClipPath(QtObjectPtr ptr, QtObjectPtr path, int operation);
void QPainter_SetClipRect3(QtObjectPtr ptr, QtObjectPtr rectangle, int operation);
void QPainter_SetClipRect(QtObjectPtr ptr, QtObjectPtr rectangle, int operation);
void QPainter_SetClipRegion(QtObjectPtr ptr, QtObjectPtr region, int operation);
void QPainter_SetViewport(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_SetWindow(QtObjectPtr ptr, QtObjectPtr rectangle);
QtObjectPtr QPainter_NewQPainter();
int QPainter_BackgroundMode(QtObjectPtr ptr);
void QPainter_BeginNativePainting(QtObjectPtr ptr);
int QPainter_CompositionMode(QtObjectPtr ptr);
QtObjectPtr QPainter_Device(QtObjectPtr ptr);
void QPainter_DrawArc2(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawArc3(QtObjectPtr ptr, int x, int y, int width, int height, int startAngle, int spanAngle);
void QPainter_DrawChord2(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawChord3(QtObjectPtr ptr, int x, int y, int width, int height, int startAngle, int spanAngle);
void QPainter_DrawConvexPolygon4(QtObjectPtr ptr, QtObjectPtr polygon);
void QPainter_DrawConvexPolygon3(QtObjectPtr ptr, QtObjectPtr polygon);
void QPainter_DrawEllipse5(QtObjectPtr ptr, QtObjectPtr center, int rx, int ry);
void QPainter_DrawEllipse3(QtObjectPtr ptr, int x, int y, int width, int height);
void QPainter_DrawImage4(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr image);
void QPainter_DrawImage6(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr image, QtObjectPtr source, int flags);
void QPainter_DrawImage5(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr image, QtObjectPtr source, int flags);
void QPainter_DrawImage8(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr image);
void QPainter_DrawImage2(QtObjectPtr ptr, QtObjectPtr target, QtObjectPtr image, QtObjectPtr source, int flags);
void QPainter_DrawImage7(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr image);
void QPainter_DrawImage9(QtObjectPtr ptr, int x, int y, QtObjectPtr image, int sx, int sy, int sw, int sh, int flags);
void QPainter_DrawLine2(QtObjectPtr ptr, QtObjectPtr line);
void QPainter_DrawLine(QtObjectPtr ptr, QtObjectPtr line);
void QPainter_DrawLine3(QtObjectPtr ptr, QtObjectPtr p1, QtObjectPtr p2);
void QPainter_DrawLine4(QtObjectPtr ptr, QtObjectPtr p1, QtObjectPtr p2);
void QPainter_DrawLine5(QtObjectPtr ptr, int x1, int y1, int x2, int y2);
void QPainter_DrawLines(QtObjectPtr ptr, QtObjectPtr lines, int lineCount);
void QPainter_DrawLines4(QtObjectPtr ptr, QtObjectPtr pointPairs, int lineCount);
void QPainter_DrawLines3(QtObjectPtr ptr, QtObjectPtr pointPairs, int lineCount);
void QPainter_DrawPath(QtObjectPtr ptr, QtObjectPtr path);
void QPainter_DrawPicture2(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr picture);
void QPainter_DrawPicture3(QtObjectPtr ptr, int x, int y, QtObjectPtr picture);
void QPainter_DrawPie2(QtObjectPtr ptr, QtObjectPtr rectangle, int startAngle, int spanAngle);
void QPainter_DrawPie3(QtObjectPtr ptr, int x, int y, int width, int height, int startAngle, int spanAngle);
void QPainter_DrawPixmap6(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr pixmap);
void QPainter_DrawPixmap4(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr pixmap, QtObjectPtr source);
void QPainter_DrawPixmap3(QtObjectPtr ptr, QtObjectPtr point, QtObjectPtr pixmap, QtObjectPtr source);
void QPainter_DrawPixmap8(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr pixmap);
void QPainter_DrawPixmap2(QtObjectPtr ptr, QtObjectPtr target, QtObjectPtr pixmap, QtObjectPtr source);
void QPainter_DrawPixmap7(QtObjectPtr ptr, int x, int y, QtObjectPtr pixmap);
void QPainter_DrawPixmap11(QtObjectPtr ptr, int x, int y, QtObjectPtr pixmap, int sx, int sy, int sw, int sh);
void QPainter_DrawPixmap10(QtObjectPtr ptr, int x, int y, int w, int h, QtObjectPtr pixmap, int sx, int sy, int sw, int sh);
void QPainter_DrawPixmap9(QtObjectPtr ptr, int x, int y, int width, int height, QtObjectPtr pixmap);
void QPainter_DrawPoint2(QtObjectPtr ptr, QtObjectPtr position);
void QPainter_DrawPoint(QtObjectPtr ptr, QtObjectPtr position);
void QPainter_DrawPoint3(QtObjectPtr ptr, int x, int y);
void QPainter_DrawPoints2(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawPoints(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawPoints4(QtObjectPtr ptr, QtObjectPtr points);
void QPainter_DrawPoints3(QtObjectPtr ptr, QtObjectPtr points);
void QPainter_DrawPolygon2(QtObjectPtr ptr, QtObjectPtr points, int pointCount, int fillRule);
void QPainter_DrawPolygon(QtObjectPtr ptr, QtObjectPtr points, int pointCount, int fillRule);
void QPainter_DrawPolygon4(QtObjectPtr ptr, QtObjectPtr points, int fillRule);
void QPainter_DrawPolygon3(QtObjectPtr ptr, QtObjectPtr points, int fillRule);
void QPainter_DrawPolyline2(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawPolyline(QtObjectPtr ptr, QtObjectPtr points, int pointCount);
void QPainter_DrawPolyline4(QtObjectPtr ptr, QtObjectPtr points);
void QPainter_DrawPolyline3(QtObjectPtr ptr, QtObjectPtr points);
void QPainter_DrawRect2(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_DrawRect(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_DrawRect3(QtObjectPtr ptr, int x, int y, int width, int height);
void QPainter_DrawStaticText2(QtObjectPtr ptr, QtObjectPtr topLeftPosition, QtObjectPtr staticText);
void QPainter_DrawStaticText(QtObjectPtr ptr, QtObjectPtr topLeftPosition, QtObjectPtr staticText);
void QPainter_DrawStaticText3(QtObjectPtr ptr, int left, int top, QtObjectPtr staticText);
void QPainter_DrawText3(QtObjectPtr ptr, QtObjectPtr position, char* text);
void QPainter_DrawText6(QtObjectPtr ptr, int x, int y, char* text);
void QPainter_DrawText7(QtObjectPtr ptr, int x, int y, int width, int height, int flags, char* text, QtObjectPtr boundingRect);
void QPainter_DrawTiledPixmap2(QtObjectPtr ptr, QtObjectPtr rectangle, QtObjectPtr pixmap, QtObjectPtr position);
void QPainter_DrawTiledPixmap3(QtObjectPtr ptr, int x, int y, int width, int height, QtObjectPtr pixmap, int sx, int sy);
int QPainter_End(QtObjectPtr ptr);
void QPainter_EndNativePainting(QtObjectPtr ptr);
void QPainter_EraseRect2(QtObjectPtr ptr, QtObjectPtr rectangle);
void QPainter_EraseRect3(QtObjectPtr ptr, int x, int y, int width, int height);
void QPainter_FillPath(QtObjectPtr ptr, QtObjectPtr path, QtObjectPtr brush);
void QPainter_FillRect3(QtObjectPtr ptr, QtObjectPtr rectangle, int style);
void QPainter_FillRect11(QtObjectPtr ptr, QtObjectPtr rectangle, int color);
void QPainter_FillRect4(QtObjectPtr ptr, QtObjectPtr rectangle, int style);
void QPainter_FillRect12(QtObjectPtr ptr, QtObjectPtr rectangle, int color);
void QPainter_FillRect2(QtObjectPtr ptr, int x, int y, int width, int height, int style);
void QPainter_FillRect10(QtObjectPtr ptr, int x, int y, int width, int height, int color);
void QPainter_FillRect8(QtObjectPtr ptr, int x, int y, int width, int height, QtObjectPtr brush);
void QPainter_FillRect9(QtObjectPtr ptr, int x, int y, int width, int height, QtObjectPtr color);
int QPainter_HasClipping(QtObjectPtr ptr);
int QPainter_IsActive(QtObjectPtr ptr);
int QPainter_LayoutDirection(QtObjectPtr ptr);
QtObjectPtr QPainter_PaintEngine(QtObjectPtr ptr);
int QPainter_RenderHints(QtObjectPtr ptr);
void QPainter_ResetTransform(QtObjectPtr ptr);
void QPainter_Restore(QtObjectPtr ptr);
void QPainter_Save(QtObjectPtr ptr);
void QPainter_SetBackgroundMode(QtObjectPtr ptr, int mode);
void QPainter_SetBrush2(QtObjectPtr ptr, int style);
void QPainter_SetBrush(QtObjectPtr ptr, QtObjectPtr brush);
void QPainter_SetBrushOrigin2(QtObjectPtr ptr, QtObjectPtr position);
void QPainter_SetBrushOrigin3(QtObjectPtr ptr, int x, int y);
void QPainter_SetClipRect2(QtObjectPtr ptr, int x, int y, int width, int height, int operation);
void QPainter_SetClipping(QtObjectPtr ptr, int enable);
void QPainter_SetCompositionMode(QtObjectPtr ptr, int mode);
void QPainter_SetFont(QtObjectPtr ptr, QtObjectPtr font);
void QPainter_SetLayoutDirection(QtObjectPtr ptr, int direction);
void QPainter_SetPen3(QtObjectPtr ptr, int style);
void QPainter_SetPen2(QtObjectPtr ptr, QtObjectPtr color);
void QPainter_SetPen(QtObjectPtr ptr, QtObjectPtr pen);
void QPainter_SetRenderHint(QtObjectPtr ptr, int hint, int on);
void QPainter_SetRenderHints(QtObjectPtr ptr, int hints, int on);
void QPainter_SetTransform(QtObjectPtr ptr, QtObjectPtr transform, int combine);
void QPainter_SetViewTransformEnabled(QtObjectPtr ptr, int enable);
void QPainter_SetViewport2(QtObjectPtr ptr, int x, int y, int width, int height);
void QPainter_SetWindow2(QtObjectPtr ptr, int x, int y, int width, int height);
void QPainter_SetWorldMatrixEnabled(QtObjectPtr ptr, int enable);
void QPainter_SetWorldTransform(QtObjectPtr ptr, QtObjectPtr matrix, int combine);
void QPainter_StrokePath(QtObjectPtr ptr, QtObjectPtr path, QtObjectPtr pen);
int QPainter_TestRenderHint(QtObjectPtr ptr, int hint);
void QPainter_Translate2(QtObjectPtr ptr, QtObjectPtr offset);
void QPainter_Translate(QtObjectPtr ptr, QtObjectPtr offset);
int QPainter_ViewTransformEnabled(QtObjectPtr ptr);
int QPainter_WorldMatrixEnabled(QtObjectPtr ptr);
void QPainter_DestroyQPainter(QtObjectPtr ptr);

#ifdef __cplusplus
}
#endif