#ifdef __cplusplus
extern "C" {
#endif
#include "../cgoutil.h"

int QWindow_ContentOrientation(QtObjectPtr ptr);
int QWindow_Flags(QtObjectPtr ptr);
int QWindow_IsVisible(QtObjectPtr ptr);
int QWindow_Modality(QtObjectPtr ptr);
void QWindow_ReportContentOrientationChange(QtObjectPtr ptr, int orientation);
void QWindow_SetFlags(QtObjectPtr ptr, int flags);
void QWindow_SetHeight(QtObjectPtr ptr, int arg);
void QWindow_SetMaximumHeight(QtObjectPtr ptr, int h);
void QWindow_SetMaximumWidth(QtObjectPtr ptr, int w);
void QWindow_SetMinimumHeight(QtObjectPtr ptr, int h);
void QWindow_SetMinimumWidth(QtObjectPtr ptr, int w);
void QWindow_SetModality(QtObjectPtr ptr, int modality);
void QWindow_SetTitle(QtObjectPtr ptr, char* v);
void QWindow_SetVisibility(QtObjectPtr ptr, int v);
void QWindow_SetVisible(QtObjectPtr ptr, int visible);
void QWindow_SetWidth(QtObjectPtr ptr, int arg);
void QWindow_SetX(QtObjectPtr ptr, int arg);
void QWindow_SetY(QtObjectPtr ptr, int arg);
char* QWindow_Title(QtObjectPtr ptr);
int QWindow_Visibility(QtObjectPtr ptr);
QtObjectPtr QWindow_NewQWindow(QtObjectPtr targetScreen);
QtObjectPtr QWindow_NewQWindow2(QtObjectPtr parent);
void QWindow_ConnectActiveChanged(QtObjectPtr ptr);
void QWindow_DisconnectActiveChanged(QtObjectPtr ptr);
void QWindow_Alert(QtObjectPtr ptr, int msec);
int QWindow_Close(QtObjectPtr ptr);
void QWindow_ConnectContentOrientationChanged(QtObjectPtr ptr);
void QWindow_DisconnectContentOrientationChanged(QtObjectPtr ptr);
void QWindow_Create(QtObjectPtr ptr);
void QWindow_Destroy(QtObjectPtr ptr);
char* QWindow_FilePath(QtObjectPtr ptr);
QtObjectPtr QWindow_FocusObject(QtObjectPtr ptr);
void QWindow_ConnectFocusObjectChanged(QtObjectPtr ptr);
void QWindow_DisconnectFocusObjectChanged(QtObjectPtr ptr);
int QWindow_Height(QtObjectPtr ptr);
void QWindow_ConnectHeightChanged(QtObjectPtr ptr);
void QWindow_DisconnectHeightChanged(QtObjectPtr ptr);
void QWindow_Hide(QtObjectPtr ptr);
int QWindow_IsActive(QtObjectPtr ptr);
int QWindow_IsAncestorOf(QtObjectPtr ptr, QtObjectPtr child, int mode);
int QWindow_IsExposed(QtObjectPtr ptr);
int QWindow_IsModal(QtObjectPtr ptr);
int QWindow_IsTopLevel(QtObjectPtr ptr);
void QWindow_Lower(QtObjectPtr ptr);
int QWindow_MaximumHeight(QtObjectPtr ptr);
void QWindow_ConnectMaximumHeightChanged(QtObjectPtr ptr);
void QWindow_DisconnectMaximumHeightChanged(QtObjectPtr ptr);
int QWindow_MaximumWidth(QtObjectPtr ptr);
void QWindow_ConnectMaximumWidthChanged(QtObjectPtr ptr);
void QWindow_DisconnectMaximumWidthChanged(QtObjectPtr ptr);
int QWindow_MinimumHeight(QtObjectPtr ptr);
void QWindow_ConnectMinimumHeightChanged(QtObjectPtr ptr);
void QWindow_DisconnectMinimumHeightChanged(QtObjectPtr ptr);
int QWindow_MinimumWidth(QtObjectPtr ptr);
void QWindow_ConnectMinimumWidthChanged(QtObjectPtr ptr);
void QWindow_DisconnectMinimumWidthChanged(QtObjectPtr ptr);
void QWindow_ConnectModalityChanged(QtObjectPtr ptr);
void QWindow_DisconnectModalityChanged(QtObjectPtr ptr);
QtObjectPtr QWindow_Parent(QtObjectPtr ptr);
void QWindow_Raise(QtObjectPtr ptr);
void QWindow_RequestActivate(QtObjectPtr ptr);
void QWindow_RequestUpdate(QtObjectPtr ptr);
void QWindow_Resize(QtObjectPtr ptr, QtObjectPtr newSize);
void QWindow_Resize2(QtObjectPtr ptr, int w, int h);
QtObjectPtr QWindow_Screen(QtObjectPtr ptr);
void QWindow_ConnectScreenChanged(QtObjectPtr ptr);
void QWindow_DisconnectScreenChanged(QtObjectPtr ptr);
void QWindow_SetBaseSize(QtObjectPtr ptr, QtObjectPtr size);
void QWindow_SetCursor(QtObjectPtr ptr, QtObjectPtr cursor);
void QWindow_SetFilePath(QtObjectPtr ptr, char* filePath);
void QWindow_SetFormat(QtObjectPtr ptr, QtObjectPtr format);
void QWindow_SetFramePosition(QtObjectPtr ptr, QtObjectPtr point);
void QWindow_SetGeometry2(QtObjectPtr ptr, QtObjectPtr rect);
void QWindow_SetGeometry(QtObjectPtr ptr, int posx, int posy, int w, int h);
void QWindow_SetIcon(QtObjectPtr ptr, QtObjectPtr icon);
int QWindow_SetKeyboardGrabEnabled(QtObjectPtr ptr, int grab);
void QWindow_SetMask(QtObjectPtr ptr, QtObjectPtr region);
void QWindow_SetMaximumSize(QtObjectPtr ptr, QtObjectPtr size);
void QWindow_SetMinimumSize(QtObjectPtr ptr, QtObjectPtr size);
int QWindow_SetMouseGrabEnabled(QtObjectPtr ptr, int grab);
void QWindow_SetParent(QtObjectPtr ptr, QtObjectPtr parent);
void QWindow_SetPosition(QtObjectPtr ptr, QtObjectPtr pt);
void QWindow_SetPosition2(QtObjectPtr ptr, int posx, int posy);
void QWindow_SetScreen(QtObjectPtr ptr, QtObjectPtr newScreen);
void QWindow_SetSizeIncrement(QtObjectPtr ptr, QtObjectPtr size);
void QWindow_SetSurfaceType(QtObjectPtr ptr, int surfaceType);
void QWindow_SetTransientParent(QtObjectPtr ptr, QtObjectPtr parent);
void QWindow_SetWindowState(QtObjectPtr ptr, int state);
void QWindow_Show(QtObjectPtr ptr);
void QWindow_ShowFullScreen(QtObjectPtr ptr);
void QWindow_ShowMaximized(QtObjectPtr ptr);
void QWindow_ShowMinimized(QtObjectPtr ptr);
void QWindow_ShowNormal(QtObjectPtr ptr);
int QWindow_SurfaceType(QtObjectPtr ptr);
QtObjectPtr QWindow_TransientParent(QtObjectPtr ptr);
int QWindow_Type(QtObjectPtr ptr);
void QWindow_UnsetCursor(QtObjectPtr ptr);
void QWindow_ConnectVisibilityChanged(QtObjectPtr ptr);
void QWindow_DisconnectVisibilityChanged(QtObjectPtr ptr);
void QWindow_ConnectVisibleChanged(QtObjectPtr ptr);
void QWindow_DisconnectVisibleChanged(QtObjectPtr ptr);
int QWindow_Width(QtObjectPtr ptr);
void QWindow_ConnectWidthChanged(QtObjectPtr ptr);
void QWindow_DisconnectWidthChanged(QtObjectPtr ptr);
int QWindow_WindowState(QtObjectPtr ptr);
void QWindow_ConnectWindowStateChanged(QtObjectPtr ptr);
void QWindow_DisconnectWindowStateChanged(QtObjectPtr ptr);
void QWindow_ConnectWindowTitleChanged(QtObjectPtr ptr);
void QWindow_DisconnectWindowTitleChanged(QtObjectPtr ptr);
int QWindow_X(QtObjectPtr ptr);
void QWindow_ConnectXChanged(QtObjectPtr ptr);
void QWindow_DisconnectXChanged(QtObjectPtr ptr);
int QWindow_Y(QtObjectPtr ptr);
void QWindow_ConnectYChanged(QtObjectPtr ptr);
void QWindow_DisconnectYChanged(QtObjectPtr ptr);
void QWindow_DestroyQWindow(QtObjectPtr ptr);

#ifdef __cplusplus
}
#endif