#ifdef __cplusplus
extern "C" {
#endif

int QWindow_ContentOrientation(void* ptr);
int QWindow_Flags(void* ptr);
int QWindow_IsVisible(void* ptr);
int QWindow_Modality(void* ptr);
double QWindow_Opacity(void* ptr);
void QWindow_ReportContentOrientationChange(void* ptr, int orientation);
void QWindow_SetFlags(void* ptr, int flags);
void QWindow_SetHeight(void* ptr, int arg);
void QWindow_SetMaximumHeight(void* ptr, int h);
void QWindow_SetMaximumWidth(void* ptr, int w);
void QWindow_SetMinimumHeight(void* ptr, int h);
void QWindow_SetMinimumWidth(void* ptr, int w);
void QWindow_SetModality(void* ptr, int modality);
void QWindow_SetOpacity(void* ptr, double level);
void QWindow_SetTitle(void* ptr, char* v);
void QWindow_SetVisibility(void* ptr, int v);
void QWindow_SetVisible(void* ptr, int visible);
void QWindow_SetWidth(void* ptr, int arg);
void QWindow_SetX(void* ptr, int arg);
void QWindow_SetY(void* ptr, int arg);
char* QWindow_Title(void* ptr);
int QWindow_Visibility(void* ptr);
void* QWindow_NewQWindow(void* targetScreen);
void* QWindow_NewQWindow2(void* parent);
void QWindow_ConnectActiveChanged(void* ptr);
void QWindow_DisconnectActiveChanged(void* ptr);
void QWindow_Alert(void* ptr, int msec);
int QWindow_Close(void* ptr);
void QWindow_ConnectContentOrientationChanged(void* ptr);
void QWindow_DisconnectContentOrientationChanged(void* ptr);
void QWindow_Create(void* ptr);
void QWindow_Destroy(void* ptr);
double QWindow_DevicePixelRatio(void* ptr);
char* QWindow_FilePath(void* ptr);
void* QWindow_FocusObject(void* ptr);
void QWindow_ConnectFocusObjectChanged(void* ptr);
void QWindow_DisconnectFocusObjectChanged(void* ptr);
int QWindow_Height(void* ptr);
void QWindow_ConnectHeightChanged(void* ptr);
void QWindow_DisconnectHeightChanged(void* ptr);
void QWindow_Hide(void* ptr);
int QWindow_IsActive(void* ptr);
int QWindow_IsAncestorOf(void* ptr, void* child, int mode);
int QWindow_IsExposed(void* ptr);
int QWindow_IsModal(void* ptr);
int QWindow_IsTopLevel(void* ptr);
void QWindow_Lower(void* ptr);
void* QWindow_Mask(void* ptr);
int QWindow_MaximumHeight(void* ptr);
void QWindow_ConnectMaximumHeightChanged(void* ptr);
void QWindow_DisconnectMaximumHeightChanged(void* ptr);
int QWindow_MaximumWidth(void* ptr);
void QWindow_ConnectMaximumWidthChanged(void* ptr);
void QWindow_DisconnectMaximumWidthChanged(void* ptr);
int QWindow_MinimumHeight(void* ptr);
void QWindow_ConnectMinimumHeightChanged(void* ptr);
void QWindow_DisconnectMinimumHeightChanged(void* ptr);
int QWindow_MinimumWidth(void* ptr);
void QWindow_ConnectMinimumWidthChanged(void* ptr);
void QWindow_DisconnectMinimumWidthChanged(void* ptr);
void QWindow_ConnectModalityChanged(void* ptr);
void QWindow_DisconnectModalityChanged(void* ptr);
void* QWindow_Parent(void* ptr);
void QWindow_Raise(void* ptr);
void QWindow_RequestActivate(void* ptr);
void QWindow_RequestUpdate(void* ptr);
void QWindow_Resize(void* ptr, void* newSize);
void QWindow_Resize2(void* ptr, int w, int h);
void* QWindow_Screen(void* ptr);
void QWindow_ConnectScreenChanged(void* ptr);
void QWindow_DisconnectScreenChanged(void* ptr);
void QWindow_SetBaseSize(void* ptr, void* size);
void QWindow_SetCursor(void* ptr, void* cursor);
void QWindow_SetFilePath(void* ptr, char* filePath);
void QWindow_SetFormat(void* ptr, void* format);
void QWindow_SetFramePosition(void* ptr, void* point);
void QWindow_SetGeometry2(void* ptr, void* rect);
void QWindow_SetGeometry(void* ptr, int posx, int posy, int w, int h);
void QWindow_SetIcon(void* ptr, void* icon);
int QWindow_SetKeyboardGrabEnabled(void* ptr, int grab);
void QWindow_SetMask(void* ptr, void* region);
void QWindow_SetMaximumSize(void* ptr, void* size);
void QWindow_SetMinimumSize(void* ptr, void* size);
int QWindow_SetMouseGrabEnabled(void* ptr, int grab);
void QWindow_SetParent(void* ptr, void* parent);
void QWindow_SetPosition(void* ptr, void* pt);
void QWindow_SetPosition2(void* ptr, int posx, int posy);
void QWindow_SetScreen(void* ptr, void* newScreen);
void QWindow_SetSizeIncrement(void* ptr, void* size);
void QWindow_SetSurfaceType(void* ptr, int surfaceType);
void QWindow_SetTransientParent(void* ptr, void* parent);
void QWindow_SetWindowState(void* ptr, int state);
void QWindow_Show(void* ptr);
void QWindow_ShowFullScreen(void* ptr);
void QWindow_ShowMaximized(void* ptr);
void QWindow_ShowMinimized(void* ptr);
void QWindow_ShowNormal(void* ptr);
int QWindow_SurfaceType(void* ptr);
void* QWindow_TransientParent(void* ptr);
int QWindow_Type(void* ptr);
void QWindow_UnsetCursor(void* ptr);
void QWindow_ConnectVisibilityChanged(void* ptr);
void QWindow_DisconnectVisibilityChanged(void* ptr);
void QWindow_ConnectVisibleChanged(void* ptr);
void QWindow_DisconnectVisibleChanged(void* ptr);
int QWindow_Width(void* ptr);
void QWindow_ConnectWidthChanged(void* ptr);
void QWindow_DisconnectWidthChanged(void* ptr);
int QWindow_WindowState(void* ptr);
void QWindow_ConnectWindowStateChanged(void* ptr);
void QWindow_DisconnectWindowStateChanged(void* ptr);
void QWindow_ConnectWindowTitleChanged(void* ptr);
void QWindow_DisconnectWindowTitleChanged(void* ptr);
int QWindow_X(void* ptr);
void QWindow_ConnectXChanged(void* ptr);
void QWindow_DisconnectXChanged(void* ptr);
int QWindow_Y(void* ptr);
void QWindow_ConnectYChanged(void* ptr);
void QWindow_DisconnectYChanged(void* ptr);
void QWindow_DestroyQWindow(void* ptr);

#ifdef __cplusplus
}
#endif