#pragma once

#ifndef GO_QTNETWORK_H
#define GO_QTNETWORK_H

#ifdef __cplusplus
extern "C" {
#endif

long long QAbstractNetworkCache_CacheSize(void* ptr);
void QAbstractNetworkCache_Clear(void* ptr);
void* QAbstractNetworkCache_Data(void* ptr, void* url);
void* QAbstractNetworkCache_MetaData(void* ptr, void* url);
void* QAbstractNetworkCache_Prepare(void* ptr, void* metaData);
void QAbstractNetworkCache_UpdateMetaData(void* ptr, void* metaData);
void QAbstractNetworkCache_DestroyQAbstractNetworkCache(void* ptr);
void QAbstractNetworkCache_TimerEvent(void* ptr, void* event);
void QAbstractNetworkCache_TimerEventDefault(void* ptr, void* event);
void QAbstractNetworkCache_ChildEvent(void* ptr, void* event);
void QAbstractNetworkCache_ChildEventDefault(void* ptr, void* event);
void QAbstractNetworkCache_CustomEvent(void* ptr, void* event);
void QAbstractNetworkCache_CustomEventDefault(void* ptr, void* event);
void* QAbstractSocket_NewQAbstractSocket(int socketType, void* parent);
void QAbstractSocket_Abort(void* ptr);
int QAbstractSocket_AtEnd(void* ptr);
int QAbstractSocket_AtEndDefault(void* ptr);
long long QAbstractSocket_BytesAvailable(void* ptr);
long long QAbstractSocket_BytesAvailableDefault(void* ptr);
long long QAbstractSocket_BytesToWrite(void* ptr);
long long QAbstractSocket_BytesToWriteDefault(void* ptr);
int QAbstractSocket_CanReadLine(void* ptr);
int QAbstractSocket_CanReadLineDefault(void* ptr);
void QAbstractSocket_Close(void* ptr);
void QAbstractSocket_CloseDefault(void* ptr);
void QAbstractSocket_ConnectConnected(void* ptr);
void QAbstractSocket_DisconnectConnected(void* ptr);
void QAbstractSocket_Connected(void* ptr);
void QAbstractSocket_DisconnectFromHost(void* ptr);
void QAbstractSocket_DisconnectFromHostDefault(void* ptr);
void QAbstractSocket_ConnectDisconnected(void* ptr);
void QAbstractSocket_DisconnectDisconnected(void* ptr);
void QAbstractSocket_Disconnected(void* ptr);
void QAbstractSocket_ConnectError2(void* ptr);
void QAbstractSocket_DisconnectError2(void* ptr);
void QAbstractSocket_Error2(void* ptr, int socketError);
int QAbstractSocket_Error(void* ptr);
int QAbstractSocket_Flush(void* ptr);
void QAbstractSocket_ConnectHostFound(void* ptr);
void QAbstractSocket_DisconnectHostFound(void* ptr);
void QAbstractSocket_HostFound(void* ptr);
int QAbstractSocket_IsSequential(void* ptr);
int QAbstractSocket_IsSequentialDefault(void* ptr);
int QAbstractSocket_IsValid(void* ptr);
void* QAbstractSocket_LocalAddress(void* ptr);
int QAbstractSocket_PauseMode(void* ptr);
void* QAbstractSocket_PeerAddress(void* ptr);
char* QAbstractSocket_PeerName(void* ptr);
void* QAbstractSocket_Proxy(void* ptr);
void QAbstractSocket_ConnectProxyAuthenticationRequired(void* ptr);
void QAbstractSocket_DisconnectProxyAuthenticationRequired(void* ptr);
void QAbstractSocket_ProxyAuthenticationRequired(void* ptr, void* proxy, void* authenticator);
long long QAbstractSocket_ReadBufferSize(void* ptr);
long long QAbstractSocket_ReadData(void* ptr, char* data, long long maxSize);
long long QAbstractSocket_ReadDataDefault(void* ptr, char* data, long long maxSize);
long long QAbstractSocket_ReadLineData(void* ptr, char* data, long long maxlen);
long long QAbstractSocket_ReadLineDataDefault(void* ptr, char* data, long long maxlen);
void QAbstractSocket_Resume(void* ptr);
void QAbstractSocket_ResumeDefault(void* ptr);
void QAbstractSocket_SetPauseMode(void* ptr, int pauseMode);
void QAbstractSocket_SetProxy(void* ptr, void* networkProxy);
void QAbstractSocket_SetReadBufferSize(void* ptr, long long size);
void QAbstractSocket_SetReadBufferSizeDefault(void* ptr, long long size);
void QAbstractSocket_SetSocketOption(void* ptr, int option, void* value);
void QAbstractSocket_SetSocketOptionDefault(void* ptr, int option, void* value);
void* QAbstractSocket_SocketOption(void* ptr, int option);
void* QAbstractSocket_SocketOptionDefault(void* ptr, int option);
int QAbstractSocket_SocketType(void* ptr);
int QAbstractSocket_State(void* ptr);
void QAbstractSocket_ConnectStateChanged(void* ptr);
void QAbstractSocket_DisconnectStateChanged(void* ptr);
void QAbstractSocket_StateChanged(void* ptr, int socketState);
int QAbstractSocket_WaitForBytesWritten(void* ptr, int msecs);
int QAbstractSocket_WaitForBytesWrittenDefault(void* ptr, int msecs);
int QAbstractSocket_WaitForConnected(void* ptr, int msecs);
int QAbstractSocket_WaitForConnectedDefault(void* ptr, int msecs);
int QAbstractSocket_WaitForDisconnected(void* ptr, int msecs);
int QAbstractSocket_WaitForDisconnectedDefault(void* ptr, int msecs);
int QAbstractSocket_WaitForReadyRead(void* ptr, int msecs);
int QAbstractSocket_WaitForReadyReadDefault(void* ptr, int msecs);
long long QAbstractSocket_WriteData(void* ptr, char* data, long long size);
long long QAbstractSocket_WriteDataDefault(void* ptr, char* data, long long size);
void QAbstractSocket_DestroyQAbstractSocket(void* ptr);
void QAbstractSocket_TimerEvent(void* ptr, void* event);
void QAbstractSocket_TimerEventDefault(void* ptr, void* event);
void QAbstractSocket_ChildEvent(void* ptr, void* event);
void QAbstractSocket_ChildEventDefault(void* ptr, void* event);
void QAbstractSocket_CustomEvent(void* ptr, void* event);
void QAbstractSocket_CustomEventDefault(void* ptr, void* event);
void* QAuthenticator_NewQAuthenticator();
void* QAuthenticator_NewQAuthenticator2(void* other);
int QAuthenticator_IsNull(void* ptr);
void* QAuthenticator_Option(void* ptr, char* opt);
char* QAuthenticator_Password(void* ptr);
char* QAuthenticator_Realm(void* ptr);
void QAuthenticator_SetOption(void* ptr, char* opt, void* value);
void QAuthenticator_SetPassword(void* ptr, char* password);
void QAuthenticator_SetUser(void* ptr, char* user);
char* QAuthenticator_User(void* ptr);
void QAuthenticator_DestroyQAuthenticator(void* ptr);
void* QDnsDomainNameRecord_NewQDnsDomainNameRecord();
void* QDnsDomainNameRecord_NewQDnsDomainNameRecord2(void* other);
char* QDnsDomainNameRecord_Name(void* ptr);
void QDnsDomainNameRecord_Swap(void* ptr, void* other);
char* QDnsDomainNameRecord_Value(void* ptr);
void QDnsDomainNameRecord_DestroyQDnsDomainNameRecord(void* ptr);
void* QDnsHostAddressRecord_NewQDnsHostAddressRecord();
void* QDnsHostAddressRecord_NewQDnsHostAddressRecord2(void* other);
char* QDnsHostAddressRecord_Name(void* ptr);
void QDnsHostAddressRecord_Swap(void* ptr, void* other);
void* QDnsHostAddressRecord_Value(void* ptr);
void QDnsHostAddressRecord_DestroyQDnsHostAddressRecord(void* ptr);
void* QDnsLookup_NewQDnsLookup3(int ty, char* name, void* nameserver, void* parent);
int QDnsLookup_Error(void* ptr);
char* QDnsLookup_ErrorString(void* ptr);
char* QDnsLookup_Name(void* ptr);
void* QDnsLookup_Nameserver(void* ptr);
void QDnsLookup_SetName(void* ptr, char* name);
void QDnsLookup_SetNameserver(void* ptr, void* nameserver);
void QDnsLookup_SetType(void* ptr, int v);
int QDnsLookup_Type(void* ptr);
void* QDnsLookup_NewQDnsLookup(void* parent);
void* QDnsLookup_NewQDnsLookup2(int ty, char* name, void* parent);
void QDnsLookup_Abort(void* ptr);
void QDnsLookup_ConnectFinished(void* ptr);
void QDnsLookup_DisconnectFinished(void* ptr);
void QDnsLookup_Finished(void* ptr);
int QDnsLookup_IsFinished(void* ptr);
void QDnsLookup_Lookup(void* ptr);
void QDnsLookup_ConnectNameChanged(void* ptr);
void QDnsLookup_DisconnectNameChanged(void* ptr);
void QDnsLookup_NameChanged(void* ptr, char* name);
void QDnsLookup_ConnectNameserverChanged(void* ptr);
void QDnsLookup_DisconnectNameserverChanged(void* ptr);
void QDnsLookup_NameserverChanged(void* ptr, void* nameserver);
void QDnsLookup_ConnectTypeChanged(void* ptr);
void QDnsLookup_DisconnectTypeChanged(void* ptr);
void QDnsLookup_TypeChanged(void* ptr, int ty);
void QDnsLookup_DestroyQDnsLookup(void* ptr);
void QDnsLookup_TimerEvent(void* ptr, void* event);
void QDnsLookup_TimerEventDefault(void* ptr, void* event);
void QDnsLookup_ChildEvent(void* ptr, void* event);
void QDnsLookup_ChildEventDefault(void* ptr, void* event);
void QDnsLookup_CustomEvent(void* ptr, void* event);
void QDnsLookup_CustomEventDefault(void* ptr, void* event);
void* QDnsMailExchangeRecord_NewQDnsMailExchangeRecord();
void* QDnsMailExchangeRecord_NewQDnsMailExchangeRecord2(void* other);
char* QDnsMailExchangeRecord_Exchange(void* ptr);
char* QDnsMailExchangeRecord_Name(void* ptr);
void QDnsMailExchangeRecord_Swap(void* ptr, void* other);
void QDnsMailExchangeRecord_DestroyQDnsMailExchangeRecord(void* ptr);
void* QDnsServiceRecord_NewQDnsServiceRecord();
void* QDnsServiceRecord_NewQDnsServiceRecord2(void* other);
char* QDnsServiceRecord_Name(void* ptr);
void QDnsServiceRecord_Swap(void* ptr, void* other);
char* QDnsServiceRecord_Target(void* ptr);
void QDnsServiceRecord_DestroyQDnsServiceRecord(void* ptr);
void* QDnsTextRecord_NewQDnsTextRecord();
void* QDnsTextRecord_NewQDnsTextRecord2(void* other);
char* QDnsTextRecord_Name(void* ptr);
void QDnsTextRecord_Swap(void* ptr, void* other);
void QDnsTextRecord_DestroyQDnsTextRecord(void* ptr);
void* QHostAddress_NewQHostAddress();
void* QHostAddress_NewQHostAddress9(int address);
void* QHostAddress_NewQHostAddress8(void* address);
void* QHostAddress_NewQHostAddress7(char* address);
void QHostAddress_Clear(void* ptr);
int QHostAddress_IsInSubnet(void* ptr, void* subnet, int netmask);
int QHostAddress_IsLoopback(void* ptr);
int QHostAddress_IsNull(void* ptr);
int QHostAddress_Protocol(void* ptr);
char* QHostAddress_ScopeId(void* ptr);
int QHostAddress_SetAddress5(void* ptr, char* address);
void QHostAddress_SetScopeId(void* ptr, char* id);
char* QHostAddress_ToString(void* ptr);
void QHostAddress_DestroyQHostAddress(void* ptr);
void* QHostInfo_NewQHostInfo2(void* other);
void* QHostInfo_NewQHostInfo(int id);
void QHostInfo_QHostInfo_AbortHostLookup(int id);
int QHostInfo_Error(void* ptr);
char* QHostInfo_ErrorString(void* ptr);
void* QHostInfo_QHostInfo_FromName(char* name);
char* QHostInfo_HostName(void* ptr);
int QHostInfo_QHostInfo_LookupHost(char* name, void* receiver, char* member);
int QHostInfo_LookupId(void* ptr);
void QHostInfo_SetError(void* ptr, int error);
void QHostInfo_SetErrorString(void* ptr, char* str);
void QHostInfo_SetHostName(void* ptr, char* hostName);
void QHostInfo_SetLookupId(void* ptr, int id);
void QHostInfo_DestroyQHostInfo(void* ptr);
char* QHostInfo_QHostInfo_LocalHostName();
char* QHostInfo_QHostInfo_LocalDomainName();
void* QHttpMultiPart_NewQHttpMultiPart2(int contentType, void* parent);
void* QHttpMultiPart_NewQHttpMultiPart(void* parent);
void QHttpMultiPart_Append(void* ptr, void* httpPart);
char* QHttpMultiPart_Boundary(void* ptr);
void QHttpMultiPart_SetBoundary(void* ptr, char* boundary);
void QHttpMultiPart_SetContentType(void* ptr, int contentType);
void QHttpMultiPart_DestroyQHttpMultiPart(void* ptr);
void QHttpMultiPart_TimerEvent(void* ptr, void* event);
void QHttpMultiPart_TimerEventDefault(void* ptr, void* event);
void QHttpMultiPart_ChildEvent(void* ptr, void* event);
void QHttpMultiPart_ChildEventDefault(void* ptr, void* event);
void QHttpMultiPart_CustomEvent(void* ptr, void* event);
void QHttpMultiPart_CustomEventDefault(void* ptr, void* event);
void* QHttpPart_NewQHttpPart();
void* QHttpPart_NewQHttpPart2(void* other);
void QHttpPart_SetBody(void* ptr, char* body);
void QHttpPart_SetBodyDevice(void* ptr, void* device);
void QHttpPart_SetHeader(void* ptr, int header, void* value);
void QHttpPart_SetRawHeader(void* ptr, char* headerName, char* headerValue);
void QHttpPart_Swap(void* ptr, void* other);
void QHttpPart_DestroyQHttpPart(void* ptr);
void QLocalServer_SetSocketOptions(void* ptr, int options);
void* QLocalServer_NewQLocalServer(void* parent);
void QLocalServer_Close(void* ptr);
char* QLocalServer_ErrorString(void* ptr);
char* QLocalServer_FullServerName(void* ptr);
int QLocalServer_HasPendingConnections(void* ptr);
int QLocalServer_HasPendingConnectionsDefault(void* ptr);
int QLocalServer_IsListening(void* ptr);
int QLocalServer_Listen(void* ptr, char* name);
int QLocalServer_MaxPendingConnections(void* ptr);
void QLocalServer_ConnectNewConnection(void* ptr);
void QLocalServer_DisconnectNewConnection(void* ptr);
void QLocalServer_NewConnection(void* ptr);
void* QLocalServer_NextPendingConnection(void* ptr);
void* QLocalServer_NextPendingConnectionDefault(void* ptr);
int QLocalServer_QLocalServer_RemoveServer(char* name);
int QLocalServer_ServerError(void* ptr);
char* QLocalServer_ServerName(void* ptr);
void QLocalServer_SetMaxPendingConnections(void* ptr, int numConnections);
int QLocalServer_SocketOptions(void* ptr);
int QLocalServer_WaitForNewConnection(void* ptr, int msec, int timedOut);
void QLocalServer_DestroyQLocalServer(void* ptr);
void QLocalServer_TimerEvent(void* ptr, void* event);
void QLocalServer_TimerEventDefault(void* ptr, void* event);
void QLocalServer_ChildEvent(void* ptr, void* event);
void QLocalServer_ChildEventDefault(void* ptr, void* event);
void QLocalServer_CustomEvent(void* ptr, void* event);
void QLocalServer_CustomEventDefault(void* ptr, void* event);
int QLocalSocket_Open(void* ptr, int openMode);
int QLocalSocket_OpenDefault(void* ptr, int openMode);
void* QLocalSocket_NewQLocalSocket(void* parent);
void QLocalSocket_ConnectToServer2(void* ptr, char* name, int openMode);
void QLocalSocket_ConnectConnected(void* ptr);
void QLocalSocket_DisconnectConnected(void* ptr);
void QLocalSocket_Connected(void* ptr);
void QLocalSocket_ConnectDisconnected(void* ptr);
void QLocalSocket_DisconnectDisconnected(void* ptr);
void QLocalSocket_Disconnected(void* ptr);
void QLocalSocket_ConnectError2(void* ptr);
void QLocalSocket_DisconnectError2(void* ptr);
void QLocalSocket_Error2(void* ptr, int socketError);
char* QLocalSocket_FullServerName(void* ptr);
int QLocalSocket_IsSequential(void* ptr);
int QLocalSocket_IsSequentialDefault(void* ptr);
char* QLocalSocket_ServerName(void* ptr);
void QLocalSocket_SetServerName(void* ptr, char* name);
int QLocalSocket_State(void* ptr);
void QLocalSocket_ConnectStateChanged(void* ptr);
void QLocalSocket_DisconnectStateChanged(void* ptr);
void QLocalSocket_StateChanged(void* ptr, int socketState);
void QLocalSocket_DestroyQLocalSocket(void* ptr);
void QLocalSocket_Abort(void* ptr);
long long QLocalSocket_BytesAvailable(void* ptr);
long long QLocalSocket_BytesAvailableDefault(void* ptr);
long long QLocalSocket_BytesToWrite(void* ptr);
long long QLocalSocket_BytesToWriteDefault(void* ptr);
int QLocalSocket_CanReadLine(void* ptr);
int QLocalSocket_CanReadLineDefault(void* ptr);
void QLocalSocket_Close(void* ptr);
void QLocalSocket_CloseDefault(void* ptr);
void QLocalSocket_ConnectToServer(void* ptr, int openMode);
void QLocalSocket_DisconnectFromServer(void* ptr);
int QLocalSocket_Error(void* ptr);
int QLocalSocket_Flush(void* ptr);
int QLocalSocket_IsValid(void* ptr);
long long QLocalSocket_ReadBufferSize(void* ptr);
long long QLocalSocket_ReadData(void* ptr, char* data, long long c);
long long QLocalSocket_ReadDataDefault(void* ptr, char* data, long long c);
void QLocalSocket_SetReadBufferSize(void* ptr, long long size);
int QLocalSocket_WaitForBytesWritten(void* ptr, int msecs);
int QLocalSocket_WaitForBytesWrittenDefault(void* ptr, int msecs);
int QLocalSocket_WaitForConnected(void* ptr, int msecs);
int QLocalSocket_WaitForDisconnected(void* ptr, int msecs);
int QLocalSocket_WaitForReadyRead(void* ptr, int msecs);
int QLocalSocket_WaitForReadyReadDefault(void* ptr, int msecs);
long long QLocalSocket_WriteData(void* ptr, char* data, long long c);
long long QLocalSocket_WriteDataDefault(void* ptr, char* data, long long c);
void QLocalSocket_TimerEvent(void* ptr, void* event);
void QLocalSocket_TimerEventDefault(void* ptr, void* event);
void QLocalSocket_ChildEvent(void* ptr, void* event);
void QLocalSocket_ChildEventDefault(void* ptr, void* event);
void QLocalSocket_CustomEvent(void* ptr, void* event);
void QLocalSocket_CustomEventDefault(void* ptr, void* event);
void* QNetworkAccessManager_ProxyFactory(void* ptr);
void* QNetworkAccessManager_NewQNetworkAccessManager(void* parent);
void* QNetworkAccessManager_ActiveConfiguration(void* ptr);
void QNetworkAccessManager_ConnectAuthenticationRequired(void* ptr);
void QNetworkAccessManager_DisconnectAuthenticationRequired(void* ptr);
void QNetworkAccessManager_AuthenticationRequired(void* ptr, void* reply, void* authenticator);
void* QNetworkAccessManager_Cache(void* ptr);
void QNetworkAccessManager_ClearAccessCache(void* ptr);
void* QNetworkAccessManager_Configuration(void* ptr);
void* QNetworkAccessManager_CookieJar(void* ptr);
void* QNetworkAccessManager_CreateRequest(void* ptr, int op, void* req, void* outgoingData);
void* QNetworkAccessManager_CreateRequestDefault(void* ptr, int op, void* req, void* outgoingData);
void* QNetworkAccessManager_DeleteResource(void* ptr, void* request);
void QNetworkAccessManager_ConnectEncrypted(void* ptr);
void QNetworkAccessManager_DisconnectEncrypted(void* ptr);
void QNetworkAccessManager_Encrypted(void* ptr, void* reply);
void QNetworkAccessManager_ConnectFinished(void* ptr);
void QNetworkAccessManager_DisconnectFinished(void* ptr);
void QNetworkAccessManager_Finished(void* ptr, void* reply);
void* QNetworkAccessManager_Get(void* ptr, void* request);
void* QNetworkAccessManager_Head(void* ptr, void* request);
int QNetworkAccessManager_NetworkAccessible(void* ptr);
void QNetworkAccessManager_ConnectNetworkAccessibleChanged(void* ptr);
void QNetworkAccessManager_DisconnectNetworkAccessibleChanged(void* ptr);
void QNetworkAccessManager_NetworkAccessibleChanged(void* ptr, int accessible);
void* QNetworkAccessManager_Post3(void* ptr, void* request, void* multiPart);
void* QNetworkAccessManager_Post(void* ptr, void* request, void* data);
void* QNetworkAccessManager_Post2(void* ptr, void* request, char* data);
void QNetworkAccessManager_ConnectPreSharedKeyAuthenticationRequired(void* ptr);
void QNetworkAccessManager_DisconnectPreSharedKeyAuthenticationRequired(void* ptr);
void QNetworkAccessManager_PreSharedKeyAuthenticationRequired(void* ptr, void* reply, void* authenticator);
void* QNetworkAccessManager_Proxy(void* ptr);
void QNetworkAccessManager_ConnectProxyAuthenticationRequired(void* ptr);
void QNetworkAccessManager_DisconnectProxyAuthenticationRequired(void* ptr);
void QNetworkAccessManager_ProxyAuthenticationRequired(void* ptr, void* proxy, void* authenticator);
void* QNetworkAccessManager_Put2(void* ptr, void* request, void* multiPart);
void* QNetworkAccessManager_Put(void* ptr, void* request, void* data);
void* QNetworkAccessManager_Put3(void* ptr, void* request, char* data);
void* QNetworkAccessManager_SendCustomRequest(void* ptr, void* request, char* verb, void* data);
void QNetworkAccessManager_SetCache(void* ptr, void* cache);
void QNetworkAccessManager_SetConfiguration(void* ptr, void* config);
void QNetworkAccessManager_SetCookieJar(void* ptr, void* cookieJar);
void QNetworkAccessManager_SetNetworkAccessible(void* ptr, int accessible);
void QNetworkAccessManager_SetProxy(void* ptr, void* proxy);
void QNetworkAccessManager_SetProxyFactory(void* ptr, void* factory);
char* QNetworkAccessManager_SupportedSchemes(void* ptr);
void QNetworkAccessManager_DestroyQNetworkAccessManager(void* ptr);
void QNetworkAccessManager_TimerEvent(void* ptr, void* event);
void QNetworkAccessManager_TimerEventDefault(void* ptr, void* event);
void QNetworkAccessManager_ChildEvent(void* ptr, void* event);
void QNetworkAccessManager_ChildEventDefault(void* ptr, void* event);
void QNetworkAccessManager_CustomEvent(void* ptr, void* event);
void QNetworkAccessManager_CustomEventDefault(void* ptr, void* event);
void* QNetworkAddressEntry_NewQNetworkAddressEntry();
void* QNetworkAddressEntry_NewQNetworkAddressEntry2(void* other);
void* QNetworkAddressEntry_Broadcast(void* ptr);
void* QNetworkAddressEntry_Ip(void* ptr);
void* QNetworkAddressEntry_Netmask(void* ptr);
int QNetworkAddressEntry_PrefixLength(void* ptr);
void QNetworkAddressEntry_SetBroadcast(void* ptr, void* newBroadcast);
void QNetworkAddressEntry_SetIp(void* ptr, void* newIp);
void QNetworkAddressEntry_SetNetmask(void* ptr, void* newNetmask);
void QNetworkAddressEntry_SetPrefixLength(void* ptr, int length);
void QNetworkAddressEntry_Swap(void* ptr, void* other);
void QNetworkAddressEntry_DestroyQNetworkAddressEntry(void* ptr);
void* QNetworkCacheMetaData_NewQNetworkCacheMetaData();
void* QNetworkCacheMetaData_NewQNetworkCacheMetaData2(void* other);
void* QNetworkCacheMetaData_ExpirationDate(void* ptr);
int QNetworkCacheMetaData_IsValid(void* ptr);
void* QNetworkCacheMetaData_LastModified(void* ptr);
int QNetworkCacheMetaData_SaveToDisk(void* ptr);
void QNetworkCacheMetaData_SetExpirationDate(void* ptr, void* dateTime);
void QNetworkCacheMetaData_SetLastModified(void* ptr, void* dateTime);
void QNetworkCacheMetaData_SetSaveToDisk(void* ptr, int allow);
void QNetworkCacheMetaData_SetUrl(void* ptr, void* url);
void QNetworkCacheMetaData_Swap(void* ptr, void* other);
void* QNetworkCacheMetaData_Url(void* ptr);
void QNetworkCacheMetaData_DestroyQNetworkCacheMetaData(void* ptr);
void* QNetworkConfiguration_NewQNetworkConfiguration();
void* QNetworkConfiguration_NewQNetworkConfiguration2(void* other);
int QNetworkConfiguration_BearerType(void* ptr);
int QNetworkConfiguration_BearerTypeFamily(void* ptr);
char* QNetworkConfiguration_BearerTypeName(void* ptr);
char* QNetworkConfiguration_Identifier(void* ptr);
int QNetworkConfiguration_IsRoamingAvailable(void* ptr);
int QNetworkConfiguration_IsValid(void* ptr);
char* QNetworkConfiguration_Name(void* ptr);
int QNetworkConfiguration_Purpose(void* ptr);
int QNetworkConfiguration_State(void* ptr);
void QNetworkConfiguration_Swap(void* ptr, void* other);
int QNetworkConfiguration_Type(void* ptr);
void QNetworkConfiguration_DestroyQNetworkConfiguration(void* ptr);
void* QNetworkConfigurationManager_NewQNetworkConfigurationManager(void* parent);
int QNetworkConfigurationManager_Capabilities(void* ptr);
void QNetworkConfigurationManager_ConnectConfigurationAdded(void* ptr);
void QNetworkConfigurationManager_DisconnectConfigurationAdded(void* ptr);
void QNetworkConfigurationManager_ConfigurationAdded(void* ptr, void* config);
void QNetworkConfigurationManager_ConnectConfigurationChanged(void* ptr);
void QNetworkConfigurationManager_DisconnectConfigurationChanged(void* ptr);
void QNetworkConfigurationManager_ConfigurationChanged(void* ptr, void* config);
void* QNetworkConfigurationManager_ConfigurationFromIdentifier(void* ptr, char* identifier);
void QNetworkConfigurationManager_ConnectConfigurationRemoved(void* ptr);
void QNetworkConfigurationManager_DisconnectConfigurationRemoved(void* ptr);
void QNetworkConfigurationManager_ConfigurationRemoved(void* ptr, void* config);
void* QNetworkConfigurationManager_DefaultConfiguration(void* ptr);
int QNetworkConfigurationManager_IsOnline(void* ptr);
void QNetworkConfigurationManager_ConnectOnlineStateChanged(void* ptr);
void QNetworkConfigurationManager_DisconnectOnlineStateChanged(void* ptr);
void QNetworkConfigurationManager_OnlineStateChanged(void* ptr, int isOnline);
void QNetworkConfigurationManager_ConnectUpdateCompleted(void* ptr);
void QNetworkConfigurationManager_DisconnectUpdateCompleted(void* ptr);
void QNetworkConfigurationManager_UpdateCompleted(void* ptr);
void QNetworkConfigurationManager_UpdateConfigurations(void* ptr);
void QNetworkConfigurationManager_DestroyQNetworkConfigurationManager(void* ptr);
void QNetworkConfigurationManager_TimerEvent(void* ptr, void* event);
void QNetworkConfigurationManager_TimerEventDefault(void* ptr, void* event);
void QNetworkConfigurationManager_ChildEvent(void* ptr, void* event);
void QNetworkConfigurationManager_ChildEventDefault(void* ptr, void* event);
void QNetworkConfigurationManager_CustomEvent(void* ptr, void* event);
void QNetworkConfigurationManager_CustomEventDefault(void* ptr, void* event);
void* QNetworkCookie_NewQNetworkCookie(char* name, char* value);
void* QNetworkCookie_NewQNetworkCookie2(void* other);
char* QNetworkCookie_Domain(void* ptr);
void* QNetworkCookie_ExpirationDate(void* ptr);
int QNetworkCookie_HasSameIdentifier(void* ptr, void* other);
int QNetworkCookie_IsHttpOnly(void* ptr);
int QNetworkCookie_IsSecure(void* ptr);
int QNetworkCookie_IsSessionCookie(void* ptr);
char* QNetworkCookie_Name(void* ptr);
void QNetworkCookie_Normalize(void* ptr, void* url);
char* QNetworkCookie_Path(void* ptr);
void QNetworkCookie_SetDomain(void* ptr, char* domain);
void QNetworkCookie_SetExpirationDate(void* ptr, void* date);
void QNetworkCookie_SetHttpOnly(void* ptr, int enable);
void QNetworkCookie_SetName(void* ptr, char* cookieName);
void QNetworkCookie_SetPath(void* ptr, char* path);
void QNetworkCookie_SetSecure(void* ptr, int enable);
void QNetworkCookie_SetValue(void* ptr, char* value);
void QNetworkCookie_Swap(void* ptr, void* other);
char* QNetworkCookie_ToRawForm(void* ptr, int form);
char* QNetworkCookie_Value(void* ptr);
void QNetworkCookie_DestroyQNetworkCookie(void* ptr);
void* QNetworkCookieJar_NewQNetworkCookieJar(void* parent);
int QNetworkCookieJar_DeleteCookie(void* ptr, void* cookie);
int QNetworkCookieJar_DeleteCookieDefault(void* ptr, void* cookie);
int QNetworkCookieJar_InsertCookie(void* ptr, void* cookie);
int QNetworkCookieJar_InsertCookieDefault(void* ptr, void* cookie);
int QNetworkCookieJar_UpdateCookie(void* ptr, void* cookie);
int QNetworkCookieJar_UpdateCookieDefault(void* ptr, void* cookie);
int QNetworkCookieJar_ValidateCookie(void* ptr, void* cookie, void* url);
int QNetworkCookieJar_ValidateCookieDefault(void* ptr, void* cookie, void* url);
void QNetworkCookieJar_DestroyQNetworkCookieJar(void* ptr);
void QNetworkCookieJar_TimerEvent(void* ptr, void* event);
void QNetworkCookieJar_TimerEventDefault(void* ptr, void* event);
void QNetworkCookieJar_ChildEvent(void* ptr, void* event);
void QNetworkCookieJar_ChildEventDefault(void* ptr, void* event);
void QNetworkCookieJar_CustomEvent(void* ptr, void* event);
void QNetworkCookieJar_CustomEventDefault(void* ptr, void* event);
void* QNetworkDiskCache_NewQNetworkDiskCache(void* parent);
char* QNetworkDiskCache_CacheDirectory(void* ptr);
long long QNetworkDiskCache_CacheSize(void* ptr);
long long QNetworkDiskCache_CacheSizeDefault(void* ptr);
void QNetworkDiskCache_Clear(void* ptr);
void QNetworkDiskCache_ClearDefault(void* ptr);
void* QNetworkDiskCache_Data(void* ptr, void* url);
void* QNetworkDiskCache_DataDefault(void* ptr, void* url);
long long QNetworkDiskCache_Expire(void* ptr);
long long QNetworkDiskCache_ExpireDefault(void* ptr);
void* QNetworkDiskCache_FileMetaData(void* ptr, char* fileName);
long long QNetworkDiskCache_MaximumCacheSize(void* ptr);
void* QNetworkDiskCache_MetaData(void* ptr, void* url);
void* QNetworkDiskCache_MetaDataDefault(void* ptr, void* url);
void* QNetworkDiskCache_Prepare(void* ptr, void* metaData);
void* QNetworkDiskCache_PrepareDefault(void* ptr, void* metaData);
void QNetworkDiskCache_SetCacheDirectory(void* ptr, char* cacheDir);
void QNetworkDiskCache_SetMaximumCacheSize(void* ptr, long long size);
void QNetworkDiskCache_UpdateMetaData(void* ptr, void* metaData);
void QNetworkDiskCache_UpdateMetaDataDefault(void* ptr, void* metaData);
void QNetworkDiskCache_DestroyQNetworkDiskCache(void* ptr);
void QNetworkDiskCache_TimerEvent(void* ptr, void* event);
void QNetworkDiskCache_TimerEventDefault(void* ptr, void* event);
void QNetworkDiskCache_ChildEvent(void* ptr, void* event);
void QNetworkDiskCache_ChildEventDefault(void* ptr, void* event);
void QNetworkDiskCache_CustomEvent(void* ptr, void* event);
void QNetworkDiskCache_CustomEventDefault(void* ptr, void* event);
void* QNetworkInterface_NewQNetworkInterface();
void* QNetworkInterface_NewQNetworkInterface2(void* other);
int QNetworkInterface_Flags(void* ptr);
char* QNetworkInterface_HardwareAddress(void* ptr);
char* QNetworkInterface_HumanReadableName(void* ptr);
int QNetworkInterface_Index(void* ptr);
void* QNetworkInterface_QNetworkInterface_InterfaceFromIndex(int index);
void* QNetworkInterface_QNetworkInterface_InterfaceFromName(char* name);
int QNetworkInterface_IsValid(void* ptr);
char* QNetworkInterface_Name(void* ptr);
void QNetworkInterface_Swap(void* ptr, void* other);
void QNetworkInterface_DestroyQNetworkInterface(void* ptr);
void* QNetworkProxy_NewQNetworkProxy();
void* QNetworkProxy_NewQNetworkProxy3(void* other);
void* QNetworkProxy_QNetworkProxy_ApplicationProxy();
int QNetworkProxy_Capabilities(void* ptr);
int QNetworkProxy_HasRawHeader(void* ptr, char* headerName);
void* QNetworkProxy_Header(void* ptr, int header);
char* QNetworkProxy_HostName(void* ptr);
int QNetworkProxy_IsCachingProxy(void* ptr);
int QNetworkProxy_IsTransparentProxy(void* ptr);
char* QNetworkProxy_Password(void* ptr);
char* QNetworkProxy_RawHeader(void* ptr, char* headerName);
void QNetworkProxy_QNetworkProxy_SetApplicationProxy(void* networkProxy);
void QNetworkProxy_SetCapabilities(void* ptr, int capabilities);
void QNetworkProxy_SetHeader(void* ptr, int header, void* value);
void QNetworkProxy_SetHostName(void* ptr, char* hostName);
void QNetworkProxy_SetPassword(void* ptr, char* password);
void QNetworkProxy_SetRawHeader(void* ptr, char* headerName, char* headerValue);
void QNetworkProxy_SetType(void* ptr, int ty);
void QNetworkProxy_SetUser(void* ptr, char* user);
void QNetworkProxy_Swap(void* ptr, void* other);
int QNetworkProxy_Type(void* ptr);
char* QNetworkProxy_User(void* ptr);
void QNetworkProxy_DestroyQNetworkProxy(void* ptr);
void QNetworkProxyFactory_QNetworkProxyFactory_SetApplicationProxyFactory(void* factory);
void QNetworkProxyFactory_QNetworkProxyFactory_SetUseSystemConfiguration(int enable);
void QNetworkProxyFactory_DestroyQNetworkProxyFactory(void* ptr);
char* QNetworkProxyFactory_ObjectNameAbs(void* ptr);
void QNetworkProxyFactory_SetObjectNameAbs(void* ptr, char* name);
void* QNetworkProxyQuery_NewQNetworkProxyQuery();
void* QNetworkProxyQuery_NewQNetworkProxyQuery7(void* networkConfiguration, char* hostname, int port, char* protocolTag, int queryType);
void* QNetworkProxyQuery_NewQNetworkProxyQuery6(void* networkConfiguration, void* requestUrl, int queryType);
void* QNetworkProxyQuery_NewQNetworkProxyQuery5(void* other);
void* QNetworkProxyQuery_NewQNetworkProxyQuery3(char* hostname, int port, char* protocolTag, int queryType);
void* QNetworkProxyQuery_NewQNetworkProxyQuery2(void* requestUrl, int queryType);
int QNetworkProxyQuery_LocalPort(void* ptr);
void* QNetworkProxyQuery_NetworkConfiguration(void* ptr);
char* QNetworkProxyQuery_PeerHostName(void* ptr);
int QNetworkProxyQuery_PeerPort(void* ptr);
char* QNetworkProxyQuery_ProtocolTag(void* ptr);
int QNetworkProxyQuery_QueryType(void* ptr);
void QNetworkProxyQuery_SetLocalPort(void* ptr, int port);
void QNetworkProxyQuery_SetNetworkConfiguration(void* ptr, void* networkConfiguration);
void QNetworkProxyQuery_SetPeerHostName(void* ptr, char* hostname);
void QNetworkProxyQuery_SetPeerPort(void* ptr, int port);
void QNetworkProxyQuery_SetProtocolTag(void* ptr, char* protocolTag);
void QNetworkProxyQuery_SetQueryType(void* ptr, int ty);
void QNetworkProxyQuery_SetUrl(void* ptr, void* url);
void QNetworkProxyQuery_Swap(void* ptr, void* other);
void* QNetworkProxyQuery_Url(void* ptr);
void QNetworkProxyQuery_DestroyQNetworkProxyQuery(void* ptr);
void QNetworkReply_SetSslConfigurationImplementation(void* ptr, void* configuration);
void QNetworkReply_SetSslConfigurationImplementationDefault(void* ptr, void* configuration);
void QNetworkReply_SslConfigurationImplementation(void* ptr, void* configuration);
void QNetworkReply_SslConfigurationImplementationDefault(void* ptr, void* configuration);
void QNetworkReply_Abort(void* ptr);
void* QNetworkReply_Attribute(void* ptr, int code);
void QNetworkReply_Close(void* ptr);
void QNetworkReply_CloseDefault(void* ptr);
void QNetworkReply_ConnectDownloadProgress(void* ptr);
void QNetworkReply_DisconnectDownloadProgress(void* ptr);
void QNetworkReply_DownloadProgress(void* ptr, long long bytesReceived, long long bytesTotal);
void QNetworkReply_ConnectEncrypted(void* ptr);
void QNetworkReply_DisconnectEncrypted(void* ptr);
void QNetworkReply_Encrypted(void* ptr);
void QNetworkReply_ConnectError2(void* ptr);
void QNetworkReply_DisconnectError2(void* ptr);
void QNetworkReply_Error2(void* ptr, int code);
int QNetworkReply_Error(void* ptr);
void QNetworkReply_ConnectFinished(void* ptr);
void QNetworkReply_DisconnectFinished(void* ptr);
void QNetworkReply_Finished(void* ptr);
int QNetworkReply_HasRawHeader(void* ptr, char* headerName);
void* QNetworkReply_Header(void* ptr, int header);
void QNetworkReply_IgnoreSslErrors(void* ptr);
void QNetworkReply_IgnoreSslErrorsDefault(void* ptr);
int QNetworkReply_IsFinished(void* ptr);
int QNetworkReply_IsRunning(void* ptr);
void* QNetworkReply_Manager(void* ptr);
void QNetworkReply_ConnectMetaDataChanged(void* ptr);
void QNetworkReply_DisconnectMetaDataChanged(void* ptr);
void QNetworkReply_MetaDataChanged(void* ptr);
int QNetworkReply_Operation(void* ptr);
void QNetworkReply_ConnectPreSharedKeyAuthenticationRequired(void* ptr);
void QNetworkReply_DisconnectPreSharedKeyAuthenticationRequired(void* ptr);
void QNetworkReply_PreSharedKeyAuthenticationRequired(void* ptr, void* authenticator);
char* QNetworkReply_RawHeader(void* ptr, char* headerName);
long long QNetworkReply_ReadBufferSize(void* ptr);
void* QNetworkReply_Request(void* ptr);
void QNetworkReply_SetReadBufferSize(void* ptr, long long size);
void QNetworkReply_SetReadBufferSizeDefault(void* ptr, long long size);
void QNetworkReply_SetSslConfiguration(void* ptr, void* config);
void* QNetworkReply_SslConfiguration(void* ptr);
void QNetworkReply_ConnectUploadProgress(void* ptr);
void QNetworkReply_DisconnectUploadProgress(void* ptr);
void QNetworkReply_UploadProgress(void* ptr, long long bytesSent, long long bytesTotal);
void* QNetworkReply_Url(void* ptr);
void QNetworkReply_DestroyQNetworkReply(void* ptr);
void QNetworkReply_TimerEvent(void* ptr, void* event);
void QNetworkReply_TimerEventDefault(void* ptr, void* event);
void QNetworkReply_ChildEvent(void* ptr, void* event);
void QNetworkReply_ChildEventDefault(void* ptr, void* event);
void QNetworkReply_CustomEvent(void* ptr, void* event);
void QNetworkReply_CustomEventDefault(void* ptr, void* event);
void* QNetworkRequest_NewQNetworkRequest2(void* other);
void* QNetworkRequest_NewQNetworkRequest(void* url);
void* QNetworkRequest_Attribute(void* ptr, int code, void* defaultValue);
int QNetworkRequest_HasRawHeader(void* ptr, char* headerName);
void* QNetworkRequest_Header(void* ptr, int header);
void* QNetworkRequest_OriginatingObject(void* ptr);
int QNetworkRequest_Priority(void* ptr);
char* QNetworkRequest_RawHeader(void* ptr, char* headerName);
void QNetworkRequest_SetAttribute(void* ptr, int code, void* value);
void QNetworkRequest_SetHeader(void* ptr, int header, void* value);
void QNetworkRequest_SetOriginatingObject(void* ptr, void* object);
void QNetworkRequest_SetPriority(void* ptr, int priority);
void QNetworkRequest_SetRawHeader(void* ptr, char* headerName, char* headerValue);
void QNetworkRequest_SetSslConfiguration(void* ptr, void* config);
void QNetworkRequest_SetUrl(void* ptr, void* url);
void* QNetworkRequest_SslConfiguration(void* ptr);
void QNetworkRequest_Swap(void* ptr, void* other);
void* QNetworkRequest_Url(void* ptr);
void QNetworkRequest_DestroyQNetworkRequest(void* ptr);
void* QNetworkSession_NewQNetworkSession(void* connectionConfig, void* parent);
void QNetworkSession_Accept(void* ptr);
void QNetworkSession_Close(void* ptr);
void QNetworkSession_ConnectClosed(void* ptr);
void QNetworkSession_DisconnectClosed(void* ptr);
void QNetworkSession_Closed(void* ptr);
void* QNetworkSession_Configuration(void* ptr);
void QNetworkSession_ConnectError2(void* ptr);
void QNetworkSession_DisconnectError2(void* ptr);
void QNetworkSession_Error2(void* ptr, int error);
int QNetworkSession_Error(void* ptr);
char* QNetworkSession_ErrorString(void* ptr);
void QNetworkSession_Ignore(void* ptr);
void* QNetworkSession_Interface(void* ptr);
int QNetworkSession_IsOpen(void* ptr);
void QNetworkSession_Migrate(void* ptr);
void QNetworkSession_ConnectNewConfigurationActivated(void* ptr);
void QNetworkSession_DisconnectNewConfigurationActivated(void* ptr);
void QNetworkSession_NewConfigurationActivated(void* ptr);
void QNetworkSession_Open(void* ptr);
void QNetworkSession_ConnectOpened(void* ptr);
void QNetworkSession_DisconnectOpened(void* ptr);
void QNetworkSession_Opened(void* ptr);
void QNetworkSession_ConnectPreferredConfigurationChanged(void* ptr);
void QNetworkSession_DisconnectPreferredConfigurationChanged(void* ptr);
void QNetworkSession_PreferredConfigurationChanged(void* ptr, void* config, int isSeamless);
void QNetworkSession_Reject(void* ptr);
void* QNetworkSession_SessionProperty(void* ptr, char* key);
void QNetworkSession_SetSessionProperty(void* ptr, char* key, void* value);
int QNetworkSession_State(void* ptr);
void QNetworkSession_ConnectStateChanged(void* ptr);
void QNetworkSession_DisconnectStateChanged(void* ptr);
void QNetworkSession_StateChanged(void* ptr, int state);
void QNetworkSession_Stop(void* ptr);
int QNetworkSession_UsagePolicies(void* ptr);
void QNetworkSession_ConnectUsagePoliciesChanged(void* ptr);
void QNetworkSession_DisconnectUsagePoliciesChanged(void* ptr);
void QNetworkSession_UsagePoliciesChanged(void* ptr, int usagePolicies);
int QNetworkSession_WaitForOpened(void* ptr, int msecs);
void QNetworkSession_DestroyQNetworkSession(void* ptr);
void QNetworkSession_TimerEvent(void* ptr, void* event);
void QNetworkSession_TimerEventDefault(void* ptr, void* event);
void QNetworkSession_ChildEvent(void* ptr, void* event);
void QNetworkSession_ChildEventDefault(void* ptr, void* event);
void QNetworkSession_CustomEvent(void* ptr, void* event);
void QNetworkSession_CustomEventDefault(void* ptr, void* event);
void* QSslCertificate_NewQSslCertificate3(void* other);
void QSslCertificate_Clear(void* ptr);
char* QSslCertificate_Digest(void* ptr, int algorithm);
int QSslCertificate_IsBlacklisted(void* ptr);
void QSslCertificate_Swap(void* ptr, void* other);
void QSslCertificate_DestroyQSslCertificate(void* ptr);
void* QSslCertificate_EffectiveDate(void* ptr);
void* QSslCertificate_ExpiryDate(void* ptr);
int QSslCertificate_IsNull(void* ptr);
int QSslCertificate_IsSelfSigned(void* ptr);
char* QSslCertificate_IssuerInfo(void* ptr, int subject);
char* QSslCertificate_IssuerInfo2(void* ptr, char* attribute);
void* QSslCertificate_PublicKey(void* ptr);
char* QSslCertificate_SerialNumber(void* ptr);
char* QSslCertificate_SubjectInfo(void* ptr, int subject);
char* QSslCertificate_SubjectInfo2(void* ptr, char* attribute);
char* QSslCertificate_ToDer(void* ptr);
char* QSslCertificate_ToPem(void* ptr);
char* QSslCertificate_ToText(void* ptr);
char* QSslCertificate_Version(void* ptr);
void* QSslCertificateExtension_NewQSslCertificateExtension();
void* QSslCertificateExtension_NewQSslCertificateExtension2(void* other);
int QSslCertificateExtension_IsCritical(void* ptr);
int QSslCertificateExtension_IsSupported(void* ptr);
char* QSslCertificateExtension_Name(void* ptr);
char* QSslCertificateExtension_Oid(void* ptr);
void QSslCertificateExtension_Swap(void* ptr, void* other);
void* QSslCertificateExtension_Value(void* ptr);
void QSslCertificateExtension_DestroyQSslCertificateExtension(void* ptr);
void* QSslCipher_NewQSslCipher();
void* QSslCipher_NewQSslCipher4(void* other);
void* QSslCipher_NewQSslCipher2(char* name);
char* QSslCipher_AuthenticationMethod(void* ptr);
char* QSslCipher_EncryptionMethod(void* ptr);
int QSslCipher_IsNull(void* ptr);
char* QSslCipher_KeyExchangeMethod(void* ptr);
char* QSslCipher_Name(void* ptr);
char* QSslCipher_ProtocolString(void* ptr);
int QSslCipher_SupportedBits(void* ptr);
void QSslCipher_Swap(void* ptr, void* other);
int QSslCipher_UsedBits(void* ptr);
void QSslCipher_DestroyQSslCipher(void* ptr);
void* QSslConfiguration_NewQSslConfiguration();
void* QSslConfiguration_NewQSslConfiguration2(void* other);
void* QSslConfiguration_QSslConfiguration_DefaultConfiguration();
int QSslConfiguration_IsNull(void* ptr);
void* QSslConfiguration_LocalCertificate(void* ptr);
char* QSslConfiguration_NextNegotiatedProtocol(void* ptr);
int QSslConfiguration_NextProtocolNegotiationStatus(void* ptr);
void* QSslConfiguration_PeerCertificate(void* ptr);
int QSslConfiguration_PeerVerifyDepth(void* ptr);
int QSslConfiguration_PeerVerifyMode(void* ptr);
void* QSslConfiguration_PrivateKey(void* ptr);
void* QSslConfiguration_SessionCipher(void* ptr);
char* QSslConfiguration_SessionTicket(void* ptr);
int QSslConfiguration_SessionTicketLifeTimeHint(void* ptr);
void QSslConfiguration_QSslConfiguration_SetDefaultConfiguration(void* configuration);
void QSslConfiguration_SetLocalCertificate(void* ptr, void* certificate);
void QSslConfiguration_SetPeerVerifyDepth(void* ptr, int depth);
void QSslConfiguration_SetPeerVerifyMode(void* ptr, int mode);
void QSslConfiguration_SetPrivateKey(void* ptr, void* key);
void QSslConfiguration_SetSessionTicket(void* ptr, char* sessionTicket);
void QSslConfiguration_Swap(void* ptr, void* other);
void QSslConfiguration_DestroyQSslConfiguration(void* ptr);
void* QSslEllipticCurve_NewQSslEllipticCurve();
int QSslEllipticCurve_IsValid(void* ptr);
int QSslEllipticCurve_IsTlsNamedCurve(void* ptr);
char* QSslEllipticCurve_LongName(void* ptr);
char* QSslEllipticCurve_ShortName(void* ptr);
void* QSslError_NewQSslError();
void* QSslError_NewQSslError2(int error);
void* QSslError_NewQSslError3(int error, void* certificate);
void* QSslError_NewQSslError4(void* other);
void* QSslError_Certificate(void* ptr);
int QSslError_Error(void* ptr);
char* QSslError_ErrorString(void* ptr);
void QSslError_Swap(void* ptr, void* other);
void QSslError_DestroyQSslError(void* ptr);
void* QSslKey_NewQSslKey();
void* QSslKey_NewQSslKey5(void* other);
void QSslKey_Clear(void* ptr);
int QSslKey_IsNull(void* ptr);
int QSslKey_Length(void* ptr);
void QSslKey_Swap(void* ptr, void* other);
char* QSslKey_ToDer(void* ptr, char* passPhrase);
char* QSslKey_ToPem(void* ptr, char* passPhrase);
void QSslKey_DestroyQSslKey(void* ptr);
void* QSslPreSharedKeyAuthenticator_NewQSslPreSharedKeyAuthenticator();
void* QSslPreSharedKeyAuthenticator_NewQSslPreSharedKeyAuthenticator2(void* authenticator);
char* QSslPreSharedKeyAuthenticator_Identity(void* ptr);
char* QSslPreSharedKeyAuthenticator_IdentityHint(void* ptr);
int QSslPreSharedKeyAuthenticator_MaximumIdentityLength(void* ptr);
int QSslPreSharedKeyAuthenticator_MaximumPreSharedKeyLength(void* ptr);
char* QSslPreSharedKeyAuthenticator_PreSharedKey(void* ptr);
void QSslPreSharedKeyAuthenticator_SetIdentity(void* ptr, char* identity);
void QSslPreSharedKeyAuthenticator_SetPreSharedKey(void* ptr, char* preSharedKey);
void QSslPreSharedKeyAuthenticator_Swap(void* ptr, void* authenticator);
void QSslPreSharedKeyAuthenticator_DestroyQSslPreSharedKeyAuthenticator(void* ptr);
void* QSslSocket_NewQSslSocket(void* parent);
void QSslSocket_Abort(void* ptr);
void QSslSocket_AddCaCertificate(void* ptr, void* certificate);
void QSslSocket_QSslSocket_AddDefaultCaCertificate(void* certificate);
int QSslSocket_AtEnd(void* ptr);
int QSslSocket_AtEndDefault(void* ptr);
long long QSslSocket_BytesAvailable(void* ptr);
long long QSslSocket_BytesAvailableDefault(void* ptr);
long long QSslSocket_BytesToWrite(void* ptr);
long long QSslSocket_BytesToWriteDefault(void* ptr);
int QSslSocket_CanReadLine(void* ptr);
int QSslSocket_CanReadLineDefault(void* ptr);
void QSslSocket_Close(void* ptr);
void QSslSocket_CloseDefault(void* ptr);
void QSslSocket_ConnectEncrypted(void* ptr);
void QSslSocket_DisconnectEncrypted(void* ptr);
void QSslSocket_Encrypted(void* ptr);
long long QSslSocket_EncryptedBytesAvailable(void* ptr);
long long QSslSocket_EncryptedBytesToWrite(void* ptr);
void QSslSocket_ConnectEncryptedBytesWritten(void* ptr);
void QSslSocket_DisconnectEncryptedBytesWritten(void* ptr);
void QSslSocket_EncryptedBytesWritten(void* ptr, long long written);
int QSslSocket_Flush(void* ptr);
void QSslSocket_IgnoreSslErrors(void* ptr);
int QSslSocket_IsEncrypted(void* ptr);
void* QSslSocket_LocalCertificate(void* ptr);
int QSslSocket_Mode(void* ptr);
void QSslSocket_ConnectModeChanged(void* ptr);
void QSslSocket_DisconnectModeChanged(void* ptr);
void QSslSocket_ModeChanged(void* ptr, int mode);
void* QSslSocket_PeerCertificate(void* ptr);
int QSslSocket_PeerVerifyDepth(void* ptr);
void QSslSocket_ConnectPeerVerifyError(void* ptr);
void QSslSocket_DisconnectPeerVerifyError(void* ptr);
void QSslSocket_PeerVerifyError(void* ptr, void* error);
int QSslSocket_PeerVerifyMode(void* ptr);
char* QSslSocket_PeerVerifyName(void* ptr);
void QSslSocket_ConnectPreSharedKeyAuthenticationRequired(void* ptr);
void QSslSocket_DisconnectPreSharedKeyAuthenticationRequired(void* ptr);
void QSslSocket_PreSharedKeyAuthenticationRequired(void* ptr, void* authenticator);
void* QSslSocket_PrivateKey(void* ptr);
long long QSslSocket_ReadData(void* ptr, char* data, long long maxlen);
long long QSslSocket_ReadDataDefault(void* ptr, char* data, long long maxlen);
void QSslSocket_Resume(void* ptr);
void QSslSocket_ResumeDefault(void* ptr);
void* QSslSocket_SessionCipher(void* ptr);
void QSslSocket_SetLocalCertificate(void* ptr, void* certificate);
void QSslSocket_SetPeerVerifyDepth(void* ptr, int depth);
void QSslSocket_SetPeerVerifyMode(void* ptr, int mode);
void QSslSocket_SetPeerVerifyName(void* ptr, char* hostName);
void QSslSocket_SetPrivateKey(void* ptr, void* key);
void QSslSocket_SetReadBufferSize(void* ptr, long long size);
void QSslSocket_SetReadBufferSizeDefault(void* ptr, long long size);
void QSslSocket_SetSocketOption(void* ptr, int option, void* value);
void QSslSocket_SetSocketOptionDefault(void* ptr, int option, void* value);
void QSslSocket_SetSslConfiguration(void* ptr, void* configuration);
void* QSslSocket_SocketOption(void* ptr, int option);
void* QSslSocket_SocketOptionDefault(void* ptr, int option);
void* QSslSocket_SslConfiguration(void* ptr);
char* QSslSocket_QSslSocket_SslLibraryBuildVersionString();
char* QSslSocket_QSslSocket_SslLibraryVersionString();
void QSslSocket_StartClientEncryption(void* ptr);
void QSslSocket_StartServerEncryption(void* ptr);
int QSslSocket_QSslSocket_SupportsSsl();
int QSslSocket_WaitForBytesWritten(void* ptr, int msecs);
int QSslSocket_WaitForBytesWrittenDefault(void* ptr, int msecs);
int QSslSocket_WaitForConnected(void* ptr, int msecs);
int QSslSocket_WaitForConnectedDefault(void* ptr, int msecs);
int QSslSocket_WaitForDisconnected(void* ptr, int msecs);
int QSslSocket_WaitForDisconnectedDefault(void* ptr, int msecs);
int QSslSocket_WaitForEncrypted(void* ptr, int msecs);
int QSslSocket_WaitForReadyRead(void* ptr, int msecs);
int QSslSocket_WaitForReadyReadDefault(void* ptr, int msecs);
long long QSslSocket_WriteData(void* ptr, char* data, long long len);
long long QSslSocket_WriteDataDefault(void* ptr, char* data, long long len);
void QSslSocket_DestroyQSslSocket(void* ptr);
void QSslSocket_DisconnectFromHost(void* ptr);
void QSslSocket_DisconnectFromHostDefault(void* ptr);
void QSslSocket_TimerEvent(void* ptr, void* event);
void QSslSocket_TimerEventDefault(void* ptr, void* event);
void QSslSocket_ChildEvent(void* ptr, void* event);
void QSslSocket_ChildEventDefault(void* ptr, void* event);
void QSslSocket_CustomEvent(void* ptr, void* event);
void QSslSocket_CustomEventDefault(void* ptr, void* event);
void* QTcpServer_NewQTcpServer(void* parent);
void QTcpServer_ConnectAcceptError(void* ptr);
void QTcpServer_DisconnectAcceptError(void* ptr);
void QTcpServer_AcceptError(void* ptr, int socketError);
void QTcpServer_Close(void* ptr);
char* QTcpServer_ErrorString(void* ptr);
int QTcpServer_HasPendingConnections(void* ptr);
int QTcpServer_HasPendingConnectionsDefault(void* ptr);
int QTcpServer_IsListening(void* ptr);
int QTcpServer_MaxPendingConnections(void* ptr);
void QTcpServer_ConnectNewConnection(void* ptr);
void QTcpServer_DisconnectNewConnection(void* ptr);
void QTcpServer_NewConnection(void* ptr);
void* QTcpServer_NextPendingConnection(void* ptr);
void* QTcpServer_NextPendingConnectionDefault(void* ptr);
void QTcpServer_PauseAccepting(void* ptr);
void* QTcpServer_Proxy(void* ptr);
void QTcpServer_ResumeAccepting(void* ptr);
void* QTcpServer_ServerAddress(void* ptr);
int QTcpServer_ServerError(void* ptr);
void QTcpServer_SetMaxPendingConnections(void* ptr, int numConnections);
void QTcpServer_SetProxy(void* ptr, void* networkProxy);
int QTcpServer_WaitForNewConnection(void* ptr, int msec, int timedOut);
void QTcpServer_DestroyQTcpServer(void* ptr);
void QTcpServer_TimerEvent(void* ptr, void* event);
void QTcpServer_TimerEventDefault(void* ptr, void* event);
void QTcpServer_ChildEvent(void* ptr, void* event);
void QTcpServer_ChildEventDefault(void* ptr, void* event);
void QTcpServer_CustomEvent(void* ptr, void* event);
void QTcpServer_CustomEventDefault(void* ptr, void* event);
void* QTcpSocket_NewQTcpSocket(void* parent);
void QTcpSocket_DestroyQTcpSocket(void* ptr);
void QTcpSocket_Close(void* ptr);
void QTcpSocket_CloseDefault(void* ptr);
void QTcpSocket_DisconnectFromHost(void* ptr);
void QTcpSocket_DisconnectFromHostDefault(void* ptr);
void QTcpSocket_Resume(void* ptr);
void QTcpSocket_ResumeDefault(void* ptr);
void QTcpSocket_SetReadBufferSize(void* ptr, long long size);
void QTcpSocket_SetReadBufferSizeDefault(void* ptr, long long size);
void QTcpSocket_SetSocketOption(void* ptr, int option, void* value);
void QTcpSocket_SetSocketOptionDefault(void* ptr, int option, void* value);
void QTcpSocket_TimerEvent(void* ptr, void* event);
void QTcpSocket_TimerEventDefault(void* ptr, void* event);
void QTcpSocket_ChildEvent(void* ptr, void* event);
void QTcpSocket_ChildEventDefault(void* ptr, void* event);
void QTcpSocket_CustomEvent(void* ptr, void* event);
void QTcpSocket_CustomEventDefault(void* ptr, void* event);
void* QUdpSocket_NewQUdpSocket(void* parent);
int QUdpSocket_HasPendingDatagrams(void* ptr);
int QUdpSocket_JoinMulticastGroup(void* ptr, void* groupAddress);
int QUdpSocket_JoinMulticastGroup2(void* ptr, void* groupAddress, void* iface);
int QUdpSocket_LeaveMulticastGroup(void* ptr, void* groupAddress);
int QUdpSocket_LeaveMulticastGroup2(void* ptr, void* groupAddress, void* iface);
void* QUdpSocket_MulticastInterface(void* ptr);
long long QUdpSocket_PendingDatagramSize(void* ptr);
void QUdpSocket_SetMulticastInterface(void* ptr, void* iface);
void QUdpSocket_DestroyQUdpSocket(void* ptr);
void QUdpSocket_Close(void* ptr);
void QUdpSocket_CloseDefault(void* ptr);
void QUdpSocket_DisconnectFromHost(void* ptr);
void QUdpSocket_DisconnectFromHostDefault(void* ptr);
void QUdpSocket_Resume(void* ptr);
void QUdpSocket_ResumeDefault(void* ptr);
void QUdpSocket_SetReadBufferSize(void* ptr, long long size);
void QUdpSocket_SetReadBufferSizeDefault(void* ptr, long long size);
void QUdpSocket_SetSocketOption(void* ptr, int option, void* value);
void QUdpSocket_SetSocketOptionDefault(void* ptr, int option, void* value);
void QUdpSocket_TimerEvent(void* ptr, void* event);
void QUdpSocket_TimerEventDefault(void* ptr, void* event);
void QUdpSocket_ChildEvent(void* ptr, void* event);
void QUdpSocket_ChildEventDefault(void* ptr, void* event);
void QUdpSocket_CustomEvent(void* ptr, void* event);
void QUdpSocket_CustomEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif