FROM therecipe/qt:windows_32_static_base_1
LABEL maintainer therecipe

RUN cd /usr/lib/mxe && make MXE_TARGETS='i686-w64-mingw32.static' icu4c bzip2 libpng freetype-bootstrap fontconfig freetds pixman cairo harfbuzz freetype jpeg cmake cmake-conf libmysqlclient pcre2 pthreads postgresql sqlite
