FROM therecipe/qt:js_base_3
LABEL maintainer therecipe

RUN git clone -b 5.12.0 https://code.qt.io/qt/qtcharts.git /opt/qtcharts
RUN git clone -b 5.12.0 https://code.qt.io/qt/qtxmlpatterns.git /opt/qtxmlpatterns
RUN git clone -b 5.12.0 https://code.qt.io/qt/qtcanvas3d.git /opt/qtcanvas3d
RUN git clone -b 5.12.0 https://code.qt.io/qt/qtdatavis3d.git /opt/qtdatavis3d
RUN git clone -b 5.12.0 https://code.qt.io/qt/qtmultimedia.git /opt/qtmultimedia

RUN echo "#!/bin/bash\nsource $HOME/emsdk/emsdk_env.sh \
	&& cd /opt/qtcharts && /usr/local/Qt-5.12.0/bin/qmake *.pro && make && make install \
	&& cd /opt/qtxmlpatterns && /usr/local/Qt-5.12.0/bin/qmake *.pro && make && make install \
	&& cd /opt/qtcanvas3d && /usr/local/Qt-5.12.0/bin/qmake *.pro && make && make install \
	&& cd /opt/qtdatavis3d && /usr/local/Qt-5.12.0/bin/qmake *.pro && make && make install \
	&& cd /opt/qtmultimedia && /usr/local/Qt-5.12.0/bin/qmake *.pro && make && make install" > $HOME/build.sh \
	&& chmod +x $HOME/build.sh && $HOME/build.sh
