FROM therecipe/qt:windows_32_shared_base_5
LABEL maintainer therecipe

RUN cd /usr/lib/mxe && make MXE_TARGETS='i686-w64-mingw32.shared' qtactiveqt qtcanvas3d qtmultimedia qtcharts qtconnectivity qtdatavis3d qtgraphicaleffects jasper xz tiff lcms libmng libwebp qtimageformats qtlocation
