FROM ubuntu:16.04
LABEL maintainer therecipe

RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install ca-certificates git
RUN git clone https://github.com/mxe/mxe.git /usr/lib/mxe
RUN apt-get -qq update && apt-get --no-install-recommends -qq -y install autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils
RUN cd /usr/lib/mxe && make MXE_TARGETS='i686-w64-mingw32.shared' gcc gettext openssl glib lzo
