FROM therecipe/qt:windows_32_shared_base_6 as base

RUN cd /usr/lib/mxe && make MXE_TARGETS='i686-w64-mingw32.shared' EXCLUDE_PKGS='qtwebkit' qt5
RUN rm -rf /usr/lib/mxe/log && rm -rf /usr/lib/mxe/pkg
