// +build !minimal

#pragma once

#ifndef GO_QTBLUETOOTH_H
#define GO_QTBLUETOOTH_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct QtBluetooth_PackedString { char* data; long long len; };
struct QtBluetooth_PackedList { void* data; long long len; };
void* QBluetoothAddress_NewQBluetoothAddress();
void* QBluetoothAddress_NewQBluetoothAddress4(void* other);
void* QBluetoothAddress_NewQBluetoothAddress3(char* address);
void* QBluetoothAddress_NewQBluetoothAddress2(unsigned long long address);
void QBluetoothAddress_Clear(void* ptr);
char QBluetoothAddress_IsNull(void* ptr);
struct QtBluetooth_PackedString QBluetoothAddress_ToString(void* ptr);
unsigned long long QBluetoothAddress_ToUInt64(void* ptr);
void QBluetoothAddress_DestroyQBluetoothAddress(void* ptr);
void QBluetoothDeviceDiscoveryAgent_ConnectCanceled(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectCanceled(void* ptr);
void QBluetoothDeviceDiscoveryAgent_Canceled(void* ptr);
void QBluetoothDeviceDiscoveryAgent_ConnectDeviceDiscovered(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectDeviceDiscovered(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DeviceDiscovered(void* ptr, void* info);
void QBluetoothDeviceDiscoveryAgent_ConnectError2(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectError2(void* ptr);
void QBluetoothDeviceDiscoveryAgent_Error2(void* ptr, long long error);
void QBluetoothDeviceDiscoveryAgent_ConnectFinished(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectFinished(void* ptr);
void QBluetoothDeviceDiscoveryAgent_Finished(void* ptr);
void* QBluetoothDeviceDiscoveryAgent_NewQBluetoothDeviceDiscoveryAgent(void* parent);
void* QBluetoothDeviceDiscoveryAgent_NewQBluetoothDeviceDiscoveryAgent2(void* deviceAdapter, void* parent);
struct QtBluetooth_PackedList QBluetoothDeviceDiscoveryAgent_DiscoveredDevices(void* ptr);
long long QBluetoothDeviceDiscoveryAgent_Error(void* ptr);
struct QtBluetooth_PackedString QBluetoothDeviceDiscoveryAgent_ErrorString(void* ptr);
long long QBluetoothDeviceDiscoveryAgent_InquiryType(void* ptr);
char QBluetoothDeviceDiscoveryAgent_IsActive(void* ptr);
void QBluetoothDeviceDiscoveryAgent_SetInquiryType(void* ptr, long long ty);
void QBluetoothDeviceDiscoveryAgent_Start(void* ptr);
void QBluetoothDeviceDiscoveryAgent_StartDefault(void* ptr);
void QBluetoothDeviceDiscoveryAgent_Stop(void* ptr);
void QBluetoothDeviceDiscoveryAgent_StopDefault(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DestroyQBluetoothDeviceDiscoveryAgent(void* ptr);
void* QBluetoothDeviceDiscoveryAgent_discoveredDevices_atList(void* ptr, int i);
void QBluetoothDeviceDiscoveryAgent_TimerEvent(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_TimerEventDefault(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_ChildEvent(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_ChildEventDefault(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_ConnectNotify(void* ptr, void* sign);
void QBluetoothDeviceDiscoveryAgent_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothDeviceDiscoveryAgent_CustomEvent(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_CustomEventDefault(void* ptr, void* event);
void QBluetoothDeviceDiscoveryAgent_DeleteLater(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DeleteLaterDefault(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectNotify(void* ptr, void* sign);
void QBluetoothDeviceDiscoveryAgent_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothDeviceDiscoveryAgent_Event(void* ptr, void* e);
char QBluetoothDeviceDiscoveryAgent_EventDefault(void* ptr, void* e);
char QBluetoothDeviceDiscoveryAgent_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothDeviceDiscoveryAgent_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothDeviceDiscoveryAgent_MetaObject(void* ptr);
void* QBluetoothDeviceDiscoveryAgent_MetaObjectDefault(void* ptr);
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo();
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo2(void* address, char* name, unsigned int classOfDevice);
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo4(void* other);
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo3(void* uuid, char* name, unsigned int classOfDevice);
void* QBluetoothDeviceInfo_Address(void* ptr);
long long QBluetoothDeviceInfo_CoreConfigurations(void* ptr);
void* QBluetoothDeviceInfo_DeviceUuid(void* ptr);
char QBluetoothDeviceInfo_IsCached(void* ptr);
char QBluetoothDeviceInfo_IsValid(void* ptr);
long long QBluetoothDeviceInfo_MajorDeviceClass(void* ptr);
struct QtBluetooth_PackedString QBluetoothDeviceInfo_MinorDeviceClass(void* ptr);
struct QtBluetooth_PackedString QBluetoothDeviceInfo_Name(void* ptr);
short QBluetoothDeviceInfo_Rssi(void* ptr);
long long QBluetoothDeviceInfo_ServiceClasses(void* ptr);
long long QBluetoothDeviceInfo_ServiceUuidsCompleteness(void* ptr);
void QBluetoothDeviceInfo_SetCached(void* ptr, char cached);
void QBluetoothDeviceInfo_SetCoreConfigurations(void* ptr, long long coreConfigs);
void QBluetoothDeviceInfo_SetDeviceUuid(void* ptr, void* uuid);
void QBluetoothDeviceInfo_SetRssi(void* ptr, short sign);
void QBluetoothDeviceInfo_DestroyQBluetoothDeviceInfo(void* ptr);
void* QBluetoothDeviceInfo_serviceUuids_atList(void* ptr, int i);
void* QBluetoothHostInfo_NewQBluetoothHostInfo();
void* QBluetoothHostInfo_NewQBluetoothHostInfo2(void* other);
void* QBluetoothHostInfo_Address(void* ptr);
struct QtBluetooth_PackedString QBluetoothHostInfo_Name(void* ptr);
void QBluetoothHostInfo_SetAddress(void* ptr, void* address);
void QBluetoothHostInfo_SetName(void* ptr, char* name);
void QBluetoothHostInfo_DestroyQBluetoothHostInfo(void* ptr);
void QBluetoothLocalDevice_ConnectDeviceConnected(void* ptr);
void QBluetoothLocalDevice_DisconnectDeviceConnected(void* ptr);
void QBluetoothLocalDevice_DeviceConnected(void* ptr, void* address);
void QBluetoothLocalDevice_ConnectDeviceDisconnected(void* ptr);
void QBluetoothLocalDevice_DisconnectDeviceDisconnected(void* ptr);
void QBluetoothLocalDevice_DeviceDisconnected(void* ptr, void* address);
void QBluetoothLocalDevice_ConnectError(void* ptr);
void QBluetoothLocalDevice_DisconnectError(void* ptr);
void QBluetoothLocalDevice_Error(void* ptr, long long error);
void QBluetoothLocalDevice_ConnectHostModeStateChanged(void* ptr);
void QBluetoothLocalDevice_DisconnectHostModeStateChanged(void* ptr);
void QBluetoothLocalDevice_HostModeStateChanged(void* ptr, long long state);
void QBluetoothLocalDevice_ConnectPairingDisplayConfirmation(void* ptr);
void QBluetoothLocalDevice_DisconnectPairingDisplayConfirmation(void* ptr);
void QBluetoothLocalDevice_PairingDisplayConfirmation(void* ptr, void* address, char* pin);
void QBluetoothLocalDevice_ConnectPairingDisplayPinCode(void* ptr);
void QBluetoothLocalDevice_DisconnectPairingDisplayPinCode(void* ptr);
void QBluetoothLocalDevice_PairingDisplayPinCode(void* ptr, void* address, char* pin);
void QBluetoothLocalDevice_ConnectPairingFinished(void* ptr);
void QBluetoothLocalDevice_DisconnectPairingFinished(void* ptr);
void QBluetoothLocalDevice_PairingFinished(void* ptr, void* address, long long pairing);
char QBluetoothLocalDevice_IsValid(void* ptr);
void QBluetoothLocalDevice_DestroyQBluetoothLocalDevice(void* ptr);
void QBluetoothLocalDevice_DestroyQBluetoothLocalDeviceDefault(void* ptr);
void* QBluetoothLocalDevice_NewQBluetoothLocalDevice(void* parent);
void* QBluetoothLocalDevice_NewQBluetoothLocalDevice2(void* address, void* parent);
void* QBluetoothLocalDevice_Address(void* ptr);
struct QtBluetooth_PackedList QBluetoothLocalDevice_QBluetoothLocalDevice_AllDevices();
struct QtBluetooth_PackedList QBluetoothLocalDevice_ConnectedDevices(void* ptr);
long long QBluetoothLocalDevice_HostMode(void* ptr);
struct QtBluetooth_PackedString QBluetoothLocalDevice_Name(void* ptr);
void QBluetoothLocalDevice_PairingConfirmation(void* ptr, char accept);
void QBluetoothLocalDevice_PairingConfirmationDefault(void* ptr, char accept);
long long QBluetoothLocalDevice_PairingStatus(void* ptr, void* address);
void QBluetoothLocalDevice_PowerOn(void* ptr);
void QBluetoothLocalDevice_RequestPairing(void* ptr, void* address, long long pairing);
void QBluetoothLocalDevice_SetHostMode(void* ptr, long long mode);
void* QBluetoothLocalDevice_allDevices_atList(void* ptr, int i);
void* QBluetoothLocalDevice_connectedDevices_atList(void* ptr, int i);
void QBluetoothLocalDevice_TimerEvent(void* ptr, void* event);
void QBluetoothLocalDevice_TimerEventDefault(void* ptr, void* event);
void QBluetoothLocalDevice_ChildEvent(void* ptr, void* event);
void QBluetoothLocalDevice_ChildEventDefault(void* ptr, void* event);
void QBluetoothLocalDevice_ConnectNotify(void* ptr, void* sign);
void QBluetoothLocalDevice_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothLocalDevice_CustomEvent(void* ptr, void* event);
void QBluetoothLocalDevice_CustomEventDefault(void* ptr, void* event);
void QBluetoothLocalDevice_DeleteLater(void* ptr);
void QBluetoothLocalDevice_DeleteLaterDefault(void* ptr);
void QBluetoothLocalDevice_DisconnectNotify(void* ptr, void* sign);
void QBluetoothLocalDevice_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothLocalDevice_Event(void* ptr, void* e);
char QBluetoothLocalDevice_EventDefault(void* ptr, void* e);
char QBluetoothLocalDevice_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothLocalDevice_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothLocalDevice_MetaObject(void* ptr);
void* QBluetoothLocalDevice_MetaObjectDefault(void* ptr);
void* QBluetoothServer_NewQBluetoothServer(long long serverType, void* parent);
void QBluetoothServer_ConnectError2(void* ptr);
void QBluetoothServer_DisconnectError2(void* ptr);
void QBluetoothServer_Error2(void* ptr, long long error);
void QBluetoothServer_ConnectNewConnection(void* ptr);
void QBluetoothServer_DisconnectNewConnection(void* ptr);
void QBluetoothServer_NewConnection(void* ptr);
long long QBluetoothServer_Error(void* ptr);
char QBluetoothServer_IsListening(void* ptr);
void* QBluetoothServer_Listen2(void* ptr, void* uuid, char* serviceName);
int QBluetoothServer_MaxPendingConnections(void* ptr);
long long QBluetoothServer_ServerType(void* ptr);
void QBluetoothServer_DestroyQBluetoothServer(void* ptr);
void QBluetoothServer_Close(void* ptr);
char QBluetoothServer_HasPendingConnections(void* ptr);
char QBluetoothServer_Listen(void* ptr, void* address, unsigned short port);
void* QBluetoothServer_NextPendingConnection(void* ptr);
long long QBluetoothServer_SecurityFlags(void* ptr);
void* QBluetoothServer_ServerAddress(void* ptr);
unsigned short QBluetoothServer_ServerPort(void* ptr);
void QBluetoothServer_SetMaxPendingConnections(void* ptr, int numConnections);
void QBluetoothServer_SetSecurityFlags(void* ptr, long long security);
void QBluetoothServer_TimerEvent(void* ptr, void* event);
void QBluetoothServer_TimerEventDefault(void* ptr, void* event);
void QBluetoothServer_ChildEvent(void* ptr, void* event);
void QBluetoothServer_ChildEventDefault(void* ptr, void* event);
void QBluetoothServer_ConnectNotify(void* ptr, void* sign);
void QBluetoothServer_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothServer_CustomEvent(void* ptr, void* event);
void QBluetoothServer_CustomEventDefault(void* ptr, void* event);
void QBluetoothServer_DeleteLater(void* ptr);
void QBluetoothServer_DeleteLaterDefault(void* ptr);
void QBluetoothServer_DisconnectNotify(void* ptr, void* sign);
void QBluetoothServer_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothServer_Event(void* ptr, void* e);
char QBluetoothServer_EventDefault(void* ptr, void* e);
char QBluetoothServer_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothServer_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothServer_MetaObject(void* ptr);
void* QBluetoothServer_MetaObjectDefault(void* ptr);
void QBluetoothServiceDiscoveryAgent_ConnectCanceled(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectCanceled(void* ptr);
void QBluetoothServiceDiscoveryAgent_Canceled(void* ptr);
void QBluetoothServiceDiscoveryAgent_ConnectError2(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectError2(void* ptr);
void QBluetoothServiceDiscoveryAgent_Error2(void* ptr, long long error);
void QBluetoothServiceDiscoveryAgent_ConnectFinished(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectFinished(void* ptr);
void QBluetoothServiceDiscoveryAgent_Finished(void* ptr);
void QBluetoothServiceDiscoveryAgent_ConnectServiceDiscovered(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectServiceDiscovered(void* ptr);
void QBluetoothServiceDiscoveryAgent_ServiceDiscovered(void* ptr, void* info);
void* QBluetoothServiceDiscoveryAgent_NewQBluetoothServiceDiscoveryAgent(void* parent);
void* QBluetoothServiceDiscoveryAgent_NewQBluetoothServiceDiscoveryAgent2(void* deviceAdapter, void* parent);
void QBluetoothServiceDiscoveryAgent_Clear(void* ptr);
void QBluetoothServiceDiscoveryAgent_ClearDefault(void* ptr);
struct QtBluetooth_PackedList QBluetoothServiceDiscoveryAgent_DiscoveredServices(void* ptr);
long long QBluetoothServiceDiscoveryAgent_Error(void* ptr);
struct QtBluetooth_PackedString QBluetoothServiceDiscoveryAgent_ErrorString(void* ptr);
char QBluetoothServiceDiscoveryAgent_IsActive(void* ptr);
void* QBluetoothServiceDiscoveryAgent_RemoteAddress(void* ptr);
char QBluetoothServiceDiscoveryAgent_SetRemoteAddress(void* ptr, void* address);
void QBluetoothServiceDiscoveryAgent_SetUuidFilter2(void* ptr, void* uuid);
void QBluetoothServiceDiscoveryAgent_Start(void* ptr, long long mode);
void QBluetoothServiceDiscoveryAgent_StartDefault(void* ptr, long long mode);
void QBluetoothServiceDiscoveryAgent_Stop(void* ptr);
void QBluetoothServiceDiscoveryAgent_StopDefault(void* ptr);
struct QtBluetooth_PackedList QBluetoothServiceDiscoveryAgent_UuidFilter(void* ptr);
void QBluetoothServiceDiscoveryAgent_DestroyQBluetoothServiceDiscoveryAgent(void* ptr);
void* QBluetoothServiceDiscoveryAgent_discoveredServices_atList(void* ptr, int i);
void* QBluetoothServiceDiscoveryAgent_uuidFilter_atList(void* ptr, int i);
void QBluetoothServiceDiscoveryAgent_TimerEvent(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_TimerEventDefault(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_ChildEvent(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_ChildEventDefault(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_ConnectNotify(void* ptr, void* sign);
void QBluetoothServiceDiscoveryAgent_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothServiceDiscoveryAgent_CustomEvent(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_CustomEventDefault(void* ptr, void* event);
void QBluetoothServiceDiscoveryAgent_DeleteLater(void* ptr);
void QBluetoothServiceDiscoveryAgent_DeleteLaterDefault(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectNotify(void* ptr, void* sign);
void QBluetoothServiceDiscoveryAgent_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothServiceDiscoveryAgent_Event(void* ptr, void* e);
char QBluetoothServiceDiscoveryAgent_EventDefault(void* ptr, void* e);
char QBluetoothServiceDiscoveryAgent_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothServiceDiscoveryAgent_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothServiceDiscoveryAgent_MetaObject(void* ptr);
void* QBluetoothServiceDiscoveryAgent_MetaObjectDefault(void* ptr);
int QBluetoothServiceInfo_ServiceName_Type();
int QBluetoothServiceInfo_ServiceDescription_Type();
int QBluetoothServiceInfo_ServiceProvider_Type();
struct QtBluetooth_PackedString QBluetoothServiceInfo_ServiceAvailability(void* ptr);
struct QtBluetooth_PackedString QBluetoothServiceInfo_ServiceDescription(void* ptr);
struct QtBluetooth_PackedString QBluetoothServiceInfo_ServiceName(void* ptr);
struct QtBluetooth_PackedString QBluetoothServiceInfo_ServiceProvider(void* ptr);
void* QBluetoothServiceInfo_ServiceUuid(void* ptr);
void QBluetoothServiceInfo_SetAttribute2(void* ptr, unsigned short attributeId, void* value);
void QBluetoothServiceInfo_SetServiceAvailability(void* ptr, char* availability);
void QBluetoothServiceInfo_SetServiceDescription(void* ptr, char* description);
void QBluetoothServiceInfo_SetServiceName(void* ptr, char* name);
void QBluetoothServiceInfo_SetServiceProvider(void* ptr, char* provider);
void QBluetoothServiceInfo_SetServiceUuid(void* ptr, void* uuid);
void* QBluetoothServiceInfo_NewQBluetoothServiceInfo();
void* QBluetoothServiceInfo_NewQBluetoothServiceInfo2(void* other);
void* QBluetoothServiceInfo_Attribute(void* ptr, unsigned short attributeId);
char QBluetoothServiceInfo_Contains(void* ptr, unsigned short attributeId);
void* QBluetoothServiceInfo_Device(void* ptr);
char QBluetoothServiceInfo_IsComplete(void* ptr);
char QBluetoothServiceInfo_IsRegistered(void* ptr);
char QBluetoothServiceInfo_IsValid(void* ptr);
int QBluetoothServiceInfo_ProtocolServiceMultiplexer(void* ptr);
char QBluetoothServiceInfo_RegisterService(void* ptr, void* localAdapter);
void QBluetoothServiceInfo_RemoveAttribute(void* ptr, unsigned short attributeId);
int QBluetoothServiceInfo_ServerChannel(void* ptr);
struct QtBluetooth_PackedList QBluetoothServiceInfo_ServiceClassUuids(void* ptr);
void QBluetoothServiceInfo_SetAttribute(void* ptr, unsigned short attributeId, void* value);
void QBluetoothServiceInfo_SetDevice(void* ptr, void* device);
long long QBluetoothServiceInfo_SocketProtocol(void* ptr);
char QBluetoothServiceInfo_UnregisterService(void* ptr);
void QBluetoothServiceInfo_DestroyQBluetoothServiceInfo(void* ptr);
void* QBluetoothServiceInfo_serviceClassUuids_atList(void* ptr, int i);
void QBluetoothSocket_ConnectConnected(void* ptr);
void QBluetoothSocket_DisconnectConnected(void* ptr);
void QBluetoothSocket_Connected(void* ptr);
void QBluetoothSocket_ConnectDisconnected(void* ptr);
void QBluetoothSocket_DisconnectDisconnected(void* ptr);
void QBluetoothSocket_Disconnected(void* ptr);
void QBluetoothSocket_ConnectError2(void* ptr);
void QBluetoothSocket_DisconnectError2(void* ptr);
void QBluetoothSocket_Error2(void* ptr, long long error);
void QBluetoothSocket_ConnectStateChanged(void* ptr);
void QBluetoothSocket_DisconnectStateChanged(void* ptr);
void QBluetoothSocket_StateChanged(void* ptr, long long state);
void* QBluetoothSocket_NewQBluetoothSocket(long long socketType, void* parent);
void* QBluetoothSocket_NewQBluetoothSocket2(void* parent);
void QBluetoothSocket_Abort(void* ptr);
long long QBluetoothSocket_BytesAvailable(void* ptr);
long long QBluetoothSocket_BytesAvailableDefault(void* ptr);
long long QBluetoothSocket_BytesToWrite(void* ptr);
long long QBluetoothSocket_BytesToWriteDefault(void* ptr);
char QBluetoothSocket_CanReadLine(void* ptr);
char QBluetoothSocket_CanReadLineDefault(void* ptr);
void QBluetoothSocket_Close(void* ptr);
void QBluetoothSocket_CloseDefault(void* ptr);
void QBluetoothSocket_ConnectToService2(void* ptr, void* address, void* uuid, long long openMode);
void QBluetoothSocket_ConnectToService3(void* ptr, void* address, unsigned short port, long long openMode);
void QBluetoothSocket_ConnectToService(void* ptr, void* service, long long openMode);
void QBluetoothSocket_DisconnectFromService(void* ptr);
void QBluetoothSocket_DoDeviceDiscovery(void* ptr, void* service, long long openMode);
long long QBluetoothSocket_Error(void* ptr);
struct QtBluetooth_PackedString QBluetoothSocket_ErrorString(void* ptr);
char QBluetoothSocket_IsSequential(void* ptr);
char QBluetoothSocket_IsSequentialDefault(void* ptr);
void* QBluetoothSocket_LocalAddress(void* ptr);
struct QtBluetooth_PackedString QBluetoothSocket_LocalName(void* ptr);
unsigned short QBluetoothSocket_LocalPort(void* ptr);
void* QBluetoothSocket_PeerAddress(void* ptr);
struct QtBluetooth_PackedString QBluetoothSocket_PeerName(void* ptr);
unsigned short QBluetoothSocket_PeerPort(void* ptr);
long long QBluetoothSocket_PreferredSecurityFlags(void* ptr);
long long QBluetoothSocket_ReadData(void* ptr, char* data, long long maxSize);
long long QBluetoothSocket_ReadDataDefault(void* ptr, char* data, long long maxSize);
void QBluetoothSocket_SetPreferredSecurityFlags(void* ptr, long long flags);
char QBluetoothSocket_SetSocketDescriptor(void* ptr, int socketDescriptor, long long socketType, long long socketState, long long openMode);
void QBluetoothSocket_SetSocketError(void* ptr, long long error_);
void QBluetoothSocket_SetSocketState(void* ptr, long long state);
int QBluetoothSocket_SocketDescriptor(void* ptr);
long long QBluetoothSocket_SocketType(void* ptr);
long long QBluetoothSocket_State(void* ptr);
long long QBluetoothSocket_WriteData(void* ptr, char* data, long long maxSize);
long long QBluetoothSocket_WriteDataDefault(void* ptr, char* data, long long maxSize);
void QBluetoothSocket_DestroyQBluetoothSocket(void* ptr);
void QBluetoothSocket_DestroyQBluetoothSocketDefault(void* ptr);
char QBluetoothSocket_AtEnd(void* ptr);
char QBluetoothSocket_AtEndDefault(void* ptr);
char QBluetoothSocket_Open(void* ptr, long long mode);
char QBluetoothSocket_OpenDefault(void* ptr, long long mode);
long long QBluetoothSocket_Pos(void* ptr);
long long QBluetoothSocket_PosDefault(void* ptr);
long long QBluetoothSocket_ReadLineData(void* ptr, char* data, long long maxSize);
long long QBluetoothSocket_ReadLineDataDefault(void* ptr, char* data, long long maxSize);
char QBluetoothSocket_Reset(void* ptr);
char QBluetoothSocket_ResetDefault(void* ptr);
char QBluetoothSocket_Seek(void* ptr, long long pos);
char QBluetoothSocket_SeekDefault(void* ptr, long long pos);
long long QBluetoothSocket_Size(void* ptr);
long long QBluetoothSocket_SizeDefault(void* ptr);
char QBluetoothSocket_WaitForBytesWritten(void* ptr, int msecs);
char QBluetoothSocket_WaitForBytesWrittenDefault(void* ptr, int msecs);
char QBluetoothSocket_WaitForReadyRead(void* ptr, int msecs);
char QBluetoothSocket_WaitForReadyReadDefault(void* ptr, int msecs);
void QBluetoothSocket_TimerEvent(void* ptr, void* event);
void QBluetoothSocket_TimerEventDefault(void* ptr, void* event);
void QBluetoothSocket_ChildEvent(void* ptr, void* event);
void QBluetoothSocket_ChildEventDefault(void* ptr, void* event);
void QBluetoothSocket_ConnectNotify(void* ptr, void* sign);
void QBluetoothSocket_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothSocket_CustomEvent(void* ptr, void* event);
void QBluetoothSocket_CustomEventDefault(void* ptr, void* event);
void QBluetoothSocket_DeleteLater(void* ptr);
void QBluetoothSocket_DeleteLaterDefault(void* ptr);
void QBluetoothSocket_DisconnectNotify(void* ptr, void* sign);
void QBluetoothSocket_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothSocket_Event(void* ptr, void* e);
char QBluetoothSocket_EventDefault(void* ptr, void* e);
char QBluetoothSocket_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothSocket_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothSocket_MetaObject(void* ptr);
void* QBluetoothSocket_MetaObjectDefault(void* ptr);
void* QBluetoothTransferManager_Put(void* ptr, void* request, void* data);
void* QBluetoothTransferManager_NewQBluetoothTransferManager(void* parent);
void QBluetoothTransferManager_ConnectFinished(void* ptr);
void QBluetoothTransferManager_DisconnectFinished(void* ptr);
void QBluetoothTransferManager_Finished(void* ptr, void* reply);
void QBluetoothTransferManager_DestroyQBluetoothTransferManager(void* ptr);
void QBluetoothTransferManager_TimerEvent(void* ptr, void* event);
void QBluetoothTransferManager_TimerEventDefault(void* ptr, void* event);
void QBluetoothTransferManager_ChildEvent(void* ptr, void* event);
void QBluetoothTransferManager_ChildEventDefault(void* ptr, void* event);
void QBluetoothTransferManager_ConnectNotify(void* ptr, void* sign);
void QBluetoothTransferManager_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothTransferManager_CustomEvent(void* ptr, void* event);
void QBluetoothTransferManager_CustomEventDefault(void* ptr, void* event);
void QBluetoothTransferManager_DeleteLater(void* ptr);
void QBluetoothTransferManager_DeleteLaterDefault(void* ptr);
void QBluetoothTransferManager_DisconnectNotify(void* ptr, void* sign);
void QBluetoothTransferManager_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothTransferManager_Event(void* ptr, void* e);
char QBluetoothTransferManager_EventDefault(void* ptr, void* e);
char QBluetoothTransferManager_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothTransferManager_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothTransferManager_MetaObject(void* ptr);
void* QBluetoothTransferManager_MetaObjectDefault(void* ptr);
void QBluetoothTransferReply_Abort(void* ptr);
void QBluetoothTransferReply_AbortDefault(void* ptr);
void QBluetoothTransferReply_SetManager(void* ptr, void* manager);
void QBluetoothTransferReply_SetRequest(void* ptr, void* request);
void* QBluetoothTransferReply_NewQBluetoothTransferReply(void* parent);
void QBluetoothTransferReply_ConnectError2(void* ptr);
void QBluetoothTransferReply_DisconnectError2(void* ptr);
void QBluetoothTransferReply_Error2(void* ptr, long long errorType);
long long QBluetoothTransferReply_Error(void* ptr);
struct QtBluetooth_PackedString QBluetoothTransferReply_ErrorString(void* ptr);
void QBluetoothTransferReply_ConnectFinished(void* ptr);
void QBluetoothTransferReply_DisconnectFinished(void* ptr);
void QBluetoothTransferReply_Finished(void* ptr, void* reply);
char QBluetoothTransferReply_IsFinished(void* ptr);
char QBluetoothTransferReply_IsRunning(void* ptr);
void* QBluetoothTransferReply_Manager(void* ptr);
void* QBluetoothTransferReply_Request(void* ptr);
void QBluetoothTransferReply_ConnectTransferProgress(void* ptr);
void QBluetoothTransferReply_DisconnectTransferProgress(void* ptr);
void QBluetoothTransferReply_TransferProgress(void* ptr, long long bytesTransferred, long long bytesTotal);
void QBluetoothTransferReply_DestroyQBluetoothTransferReply(void* ptr);
void QBluetoothTransferReply_TimerEvent(void* ptr, void* event);
void QBluetoothTransferReply_TimerEventDefault(void* ptr, void* event);
void QBluetoothTransferReply_ChildEvent(void* ptr, void* event);
void QBluetoothTransferReply_ChildEventDefault(void* ptr, void* event);
void QBluetoothTransferReply_ConnectNotify(void* ptr, void* sign);
void QBluetoothTransferReply_ConnectNotifyDefault(void* ptr, void* sign);
void QBluetoothTransferReply_CustomEvent(void* ptr, void* event);
void QBluetoothTransferReply_CustomEventDefault(void* ptr, void* event);
void QBluetoothTransferReply_DeleteLater(void* ptr);
void QBluetoothTransferReply_DeleteLaterDefault(void* ptr);
void QBluetoothTransferReply_DisconnectNotify(void* ptr, void* sign);
void QBluetoothTransferReply_DisconnectNotifyDefault(void* ptr, void* sign);
char QBluetoothTransferReply_Event(void* ptr, void* e);
char QBluetoothTransferReply_EventDefault(void* ptr, void* e);
char QBluetoothTransferReply_EventFilter(void* ptr, void* watched, void* event);
char QBluetoothTransferReply_EventFilterDefault(void* ptr, void* watched, void* event);
void* QBluetoothTransferReply_MetaObject(void* ptr);
void* QBluetoothTransferReply_MetaObjectDefault(void* ptr);
void* QBluetoothTransferRequest_NewQBluetoothTransferRequest(void* address);
void* QBluetoothTransferRequest_NewQBluetoothTransferRequest2(void* other);
void* QBluetoothTransferRequest_Address(void* ptr);
void* QBluetoothTransferRequest_Attribute(void* ptr, long long code, void* defaultValue);
void QBluetoothTransferRequest_SetAttribute(void* ptr, long long code, void* value);
void QBluetoothTransferRequest_DestroyQBluetoothTransferRequest(void* ptr);
void* QBluetoothUuid_NewQBluetoothUuid();
void* QBluetoothUuid_NewQBluetoothUuid4(long long uuid);
void* QBluetoothUuid_NewQBluetoothUuid5(long long uuid);
void* QBluetoothUuid_NewQBluetoothUuid2(long long uuid);
void* QBluetoothUuid_NewQBluetoothUuid3(long long uuid);
void* QBluetoothUuid_NewQBluetoothUuid10(void* uuid);
void* QBluetoothUuid_NewQBluetoothUuid9(char* uuid);
void* QBluetoothUuid_NewQBluetoothUuid11(void* uuid);
void* QBluetoothUuid_NewQBluetoothUuid6(unsigned short uuid);
void* QBluetoothUuid_NewQBluetoothUuid7(unsigned int uuid);
struct QtBluetooth_PackedString QBluetoothUuid_QBluetoothUuid_CharacteristicToString(long long uuid);
struct QtBluetooth_PackedString QBluetoothUuid_QBluetoothUuid_DescriptorToString(long long uuid);
int QBluetoothUuid_MinimumSize(void* ptr);
struct QtBluetooth_PackedString QBluetoothUuid_QBluetoothUuid_ProtocolToString(long long uuid);
struct QtBluetooth_PackedString QBluetoothUuid_QBluetoothUuid_ServiceClassToString(long long uuid);
unsigned short QBluetoothUuid_ToUInt16(void* ptr, char ok);
unsigned int QBluetoothUuid_ToUInt32(void* ptr, char ok);
void QBluetoothUuid_DestroyQBluetoothUuid(void* ptr);
void* QLowEnergyAdvertisingData_NewQLowEnergyAdvertisingData();
void* QLowEnergyAdvertisingData_NewQLowEnergyAdvertisingData2(void* other);
long long QLowEnergyAdvertisingData_Discoverability(void* ptr);
char QLowEnergyAdvertisingData_IncludePowerLevel(void* ptr);
unsigned short QLowEnergyAdvertisingData_QLowEnergyAdvertisingData_InvalidManufacturerId();
struct QtBluetooth_PackedString QLowEnergyAdvertisingData_LocalName(void* ptr);
void* QLowEnergyAdvertisingData_ManufacturerData(void* ptr);
unsigned short QLowEnergyAdvertisingData_ManufacturerId(void* ptr);
void* QLowEnergyAdvertisingData_RawData(void* ptr);
struct QtBluetooth_PackedList QLowEnergyAdvertisingData_Services(void* ptr);
void QLowEnergyAdvertisingData_SetDiscoverability(void* ptr, long long mode);
void QLowEnergyAdvertisingData_SetIncludePowerLevel(void* ptr, char doInclude);
void QLowEnergyAdvertisingData_SetLocalName(void* ptr, char* name);
void QLowEnergyAdvertisingData_SetManufacturerData(void* ptr, unsigned short id, void* data);
void QLowEnergyAdvertisingData_SetRawData(void* ptr, void* data);
void QLowEnergyAdvertisingData_Swap(void* ptr, void* other);
void QLowEnergyAdvertisingData_DestroyQLowEnergyAdvertisingData(void* ptr);
void* QLowEnergyAdvertisingData_services_atList(void* ptr, int i);
void* QLowEnergyAdvertisingParameters_NewQLowEnergyAdvertisingParameters();
void* QLowEnergyAdvertisingParameters_NewQLowEnergyAdvertisingParameters2(void* other);
long long QLowEnergyAdvertisingParameters_FilterPolicy(void* ptr);
int QLowEnergyAdvertisingParameters_MaximumInterval(void* ptr);
int QLowEnergyAdvertisingParameters_MinimumInterval(void* ptr);
long long QLowEnergyAdvertisingParameters_Mode(void* ptr);
void QLowEnergyAdvertisingParameters_SetInterval(void* ptr, unsigned short minimum, unsigned short maximum);
void QLowEnergyAdvertisingParameters_SetMode(void* ptr, long long mode);
void QLowEnergyAdvertisingParameters_Swap(void* ptr, void* other);
void QLowEnergyAdvertisingParameters_DestroyQLowEnergyAdvertisingParameters(void* ptr);
void* QLowEnergyCharacteristic_NewQLowEnergyCharacteristic();
void* QLowEnergyCharacteristic_NewQLowEnergyCharacteristic2(void* other);
void* QLowEnergyCharacteristic_Descriptor(void* ptr, void* uuid);
struct QtBluetooth_PackedList QLowEnergyCharacteristic_Descriptors(void* ptr);
char QLowEnergyCharacteristic_IsValid(void* ptr);
struct QtBluetooth_PackedString QLowEnergyCharacteristic_Name(void* ptr);
long long QLowEnergyCharacteristic_Properties(void* ptr);
void* QLowEnergyCharacteristic_Uuid(void* ptr);
void* QLowEnergyCharacteristic_Value(void* ptr);
void QLowEnergyCharacteristic_DestroyQLowEnergyCharacteristic(void* ptr);
void* QLowEnergyCharacteristic_descriptors_atList(void* ptr, int i);
void* QLowEnergyCharacteristicData_NewQLowEnergyCharacteristicData();
void* QLowEnergyCharacteristicData_NewQLowEnergyCharacteristicData2(void* other);
void QLowEnergyCharacteristicData_AddDescriptor(void* ptr, void* descriptor);
struct QtBluetooth_PackedList QLowEnergyCharacteristicData_Descriptors(void* ptr);
char QLowEnergyCharacteristicData_IsValid(void* ptr);
int QLowEnergyCharacteristicData_MaximumValueLength(void* ptr);
int QLowEnergyCharacteristicData_MinimumValueLength(void* ptr);
long long QLowEnergyCharacteristicData_Properties(void* ptr);
long long QLowEnergyCharacteristicData_ReadConstraints(void* ptr);
void QLowEnergyCharacteristicData_SetProperties(void* ptr, long long properties);
void QLowEnergyCharacteristicData_SetReadConstraints(void* ptr, long long constraints);
void QLowEnergyCharacteristicData_SetUuid(void* ptr, void* uuid);
void QLowEnergyCharacteristicData_SetValue(void* ptr, void* value);
void QLowEnergyCharacteristicData_SetValueLength(void* ptr, int minimum, int maximum);
void QLowEnergyCharacteristicData_SetWriteConstraints(void* ptr, long long constraints);
void QLowEnergyCharacteristicData_Swap(void* ptr, void* other);
void* QLowEnergyCharacteristicData_Uuid(void* ptr);
void* QLowEnergyCharacteristicData_Value(void* ptr);
long long QLowEnergyCharacteristicData_WriteConstraints(void* ptr);
void QLowEnergyCharacteristicData_DestroyQLowEnergyCharacteristicData(void* ptr);
void* QLowEnergyCharacteristicData_descriptors_atList(void* ptr, int i);
void* QLowEnergyConnectionParameters_NewQLowEnergyConnectionParameters();
void* QLowEnergyConnectionParameters_NewQLowEnergyConnectionParameters2(void* other);
int QLowEnergyConnectionParameters_Latency(void* ptr);
double QLowEnergyConnectionParameters_MaximumInterval(void* ptr);
double QLowEnergyConnectionParameters_MinimumInterval(void* ptr);
void QLowEnergyConnectionParameters_SetIntervalRange(void* ptr, double minimum, double maximum);
void QLowEnergyConnectionParameters_SetLatency(void* ptr, int latency);
void QLowEnergyConnectionParameters_SetSupervisionTimeout(void* ptr, int timeout);
int QLowEnergyConnectionParameters_SupervisionTimeout(void* ptr);
void QLowEnergyConnectionParameters_Swap(void* ptr, void* other);
void QLowEnergyConnectionParameters_DestroyQLowEnergyConnectionParameters(void* ptr);
void QLowEnergyController_ConnectConnected(void* ptr);
void QLowEnergyController_DisconnectConnected(void* ptr);
void QLowEnergyController_Connected(void* ptr);
void QLowEnergyController_ConnectConnectionUpdated(void* ptr);
void QLowEnergyController_DisconnectConnectionUpdated(void* ptr);
void QLowEnergyController_ConnectionUpdated(void* ptr, void* newParameters);
void QLowEnergyController_ConnectDisconnected(void* ptr);
void QLowEnergyController_DisconnectDisconnected(void* ptr);
void QLowEnergyController_Disconnected(void* ptr);
void QLowEnergyController_ConnectDiscoveryFinished(void* ptr);
void QLowEnergyController_DisconnectDiscoveryFinished(void* ptr);
void QLowEnergyController_DiscoveryFinished(void* ptr);
void QLowEnergyController_ConnectError2(void* ptr);
void QLowEnergyController_DisconnectError2(void* ptr);
void QLowEnergyController_Error2(void* ptr, long long newError);
void QLowEnergyController_ConnectServiceDiscovered(void* ptr);
void QLowEnergyController_DisconnectServiceDiscovered(void* ptr);
void QLowEnergyController_ServiceDiscovered(void* ptr, void* newService);
void QLowEnergyController_ConnectStateChanged(void* ptr);
void QLowEnergyController_DisconnectStateChanged(void* ptr);
void QLowEnergyController_StateChanged(void* ptr, long long state);
void* QLowEnergyController_AddService(void* ptr, void* service, void* parent);
void QLowEnergyController_ConnectToDevice(void* ptr);
void* QLowEnergyController_QLowEnergyController_CreateCentral(void* remoteDevice, void* parent);
void* QLowEnergyController_QLowEnergyController_CreatePeripheral(void* parent);
void* QLowEnergyController_CreateServiceObject(void* ptr, void* serviceUuid, void* parent);
void QLowEnergyController_DisconnectFromDevice(void* ptr);
void QLowEnergyController_DiscoverServices(void* ptr);
long long QLowEnergyController_Error(void* ptr);
struct QtBluetooth_PackedString QLowEnergyController_ErrorString(void* ptr);
void* QLowEnergyController_LocalAddress(void* ptr);
void* QLowEnergyController_RemoteAddress(void* ptr);
long long QLowEnergyController_RemoteAddressType(void* ptr);
struct QtBluetooth_PackedString QLowEnergyController_RemoteName(void* ptr);
void QLowEnergyController_RequestConnectionUpdate(void* ptr, void* parameters);
long long QLowEnergyController_Role(void* ptr);
struct QtBluetooth_PackedList QLowEnergyController_Services(void* ptr);
void QLowEnergyController_SetRemoteAddressType(void* ptr, long long ty);
void QLowEnergyController_StartAdvertising(void* ptr, void* parameters, void* advertisingData, void* scanResponseData);
long long QLowEnergyController_State(void* ptr);
void QLowEnergyController_StopAdvertising(void* ptr);
void QLowEnergyController_DestroyQLowEnergyController(void* ptr);
void* QLowEnergyController_services_atList(void* ptr, int i);
void QLowEnergyController_TimerEvent(void* ptr, void* event);
void QLowEnergyController_TimerEventDefault(void* ptr, void* event);
void QLowEnergyController_ChildEvent(void* ptr, void* event);
void QLowEnergyController_ChildEventDefault(void* ptr, void* event);
void QLowEnergyController_ConnectNotify(void* ptr, void* sign);
void QLowEnergyController_ConnectNotifyDefault(void* ptr, void* sign);
void QLowEnergyController_CustomEvent(void* ptr, void* event);
void QLowEnergyController_CustomEventDefault(void* ptr, void* event);
void QLowEnergyController_DeleteLater(void* ptr);
void QLowEnergyController_DeleteLaterDefault(void* ptr);
void QLowEnergyController_DisconnectNotify(void* ptr, void* sign);
void QLowEnergyController_DisconnectNotifyDefault(void* ptr, void* sign);
char QLowEnergyController_Event(void* ptr, void* e);
char QLowEnergyController_EventDefault(void* ptr, void* e);
char QLowEnergyController_EventFilter(void* ptr, void* watched, void* event);
char QLowEnergyController_EventFilterDefault(void* ptr, void* watched, void* event);
void* QLowEnergyController_MetaObject(void* ptr);
void* QLowEnergyController_MetaObjectDefault(void* ptr);
void* QLowEnergyDescriptor_NewQLowEnergyDescriptor();
void* QLowEnergyDescriptor_NewQLowEnergyDescriptor2(void* other);
char QLowEnergyDescriptor_IsValid(void* ptr);
struct QtBluetooth_PackedString QLowEnergyDescriptor_Name(void* ptr);
long long QLowEnergyDescriptor_Type(void* ptr);
void* QLowEnergyDescriptor_Uuid(void* ptr);
void* QLowEnergyDescriptor_Value(void* ptr);
void QLowEnergyDescriptor_DestroyQLowEnergyDescriptor(void* ptr);
void* QLowEnergyDescriptorData_NewQLowEnergyDescriptorData();
void* QLowEnergyDescriptorData_NewQLowEnergyDescriptorData2(void* uuid, void* value);
void* QLowEnergyDescriptorData_NewQLowEnergyDescriptorData3(void* other);
char QLowEnergyDescriptorData_IsReadable(void* ptr);
char QLowEnergyDescriptorData_IsValid(void* ptr);
char QLowEnergyDescriptorData_IsWritable(void* ptr);
long long QLowEnergyDescriptorData_ReadConstraints(void* ptr);
void QLowEnergyDescriptorData_SetReadPermissions(void* ptr, char readable, long long constraints);
void QLowEnergyDescriptorData_SetUuid(void* ptr, void* uuid);
void QLowEnergyDescriptorData_SetValue(void* ptr, void* value);
void QLowEnergyDescriptorData_SetWritePermissions(void* ptr, char writable, long long constraints);
void QLowEnergyDescriptorData_Swap(void* ptr, void* other);
void* QLowEnergyDescriptorData_Uuid(void* ptr);
void* QLowEnergyDescriptorData_Value(void* ptr);
long long QLowEnergyDescriptorData_WriteConstraints(void* ptr);
void QLowEnergyDescriptorData_DestroyQLowEnergyDescriptorData(void* ptr);
void QLowEnergyService_ConnectCharacteristicChanged(void* ptr);
void QLowEnergyService_DisconnectCharacteristicChanged(void* ptr);
void QLowEnergyService_CharacteristicChanged(void* ptr, void* characteristic, void* newValue);
void QLowEnergyService_ConnectCharacteristicRead(void* ptr);
void QLowEnergyService_DisconnectCharacteristicRead(void* ptr);
void QLowEnergyService_CharacteristicRead(void* ptr, void* characteristic, void* value);
void QLowEnergyService_ConnectCharacteristicWritten(void* ptr);
void QLowEnergyService_DisconnectCharacteristicWritten(void* ptr);
void QLowEnergyService_CharacteristicWritten(void* ptr, void* characteristic, void* newValue);
void QLowEnergyService_ConnectDescriptorRead(void* ptr);
void QLowEnergyService_DisconnectDescriptorRead(void* ptr);
void QLowEnergyService_DescriptorRead(void* ptr, void* descriptor, void* value);
void QLowEnergyService_ConnectDescriptorWritten(void* ptr);
void QLowEnergyService_DisconnectDescriptorWritten(void* ptr);
void QLowEnergyService_DescriptorWritten(void* ptr, void* descriptor, void* newValue);
void QLowEnergyService_ConnectError2(void* ptr);
void QLowEnergyService_DisconnectError2(void* ptr);
void QLowEnergyService_Error2(void* ptr, long long newError);
void QLowEnergyService_ConnectStateChanged(void* ptr);
void QLowEnergyService_DisconnectStateChanged(void* ptr);
void QLowEnergyService_StateChanged(void* ptr, long long newState);
void* QLowEnergyService_Characteristic(void* ptr, void* uuid);
struct QtBluetooth_PackedList QLowEnergyService_Characteristics(void* ptr);
char QLowEnergyService_Contains(void* ptr, void* characteristic);
char QLowEnergyService_Contains2(void* ptr, void* descriptor);
void QLowEnergyService_DiscoverDetails(void* ptr);
long long QLowEnergyService_Error(void* ptr);
struct QtBluetooth_PackedList QLowEnergyService_IncludedServices(void* ptr);
void QLowEnergyService_ReadCharacteristic(void* ptr, void* characteristic);
void QLowEnergyService_ReadDescriptor(void* ptr, void* descriptor);
struct QtBluetooth_PackedString QLowEnergyService_ServiceName(void* ptr);
void* QLowEnergyService_ServiceUuid(void* ptr);
long long QLowEnergyService_State(void* ptr);
long long QLowEnergyService_Type(void* ptr);
void QLowEnergyService_WriteCharacteristic(void* ptr, void* characteristic, void* newValue, long long mode);
void QLowEnergyService_WriteDescriptor(void* ptr, void* descriptor, void* newValue);
void QLowEnergyService_DestroyQLowEnergyService(void* ptr);
void* QLowEnergyService_characteristics_atList(void* ptr, int i);
void* QLowEnergyService_includedServices_atList(void* ptr, int i);
void QLowEnergyService_TimerEvent(void* ptr, void* event);
void QLowEnergyService_TimerEventDefault(void* ptr, void* event);
void QLowEnergyService_ChildEvent(void* ptr, void* event);
void QLowEnergyService_ChildEventDefault(void* ptr, void* event);
void QLowEnergyService_ConnectNotify(void* ptr, void* sign);
void QLowEnergyService_ConnectNotifyDefault(void* ptr, void* sign);
void QLowEnergyService_CustomEvent(void* ptr, void* event);
void QLowEnergyService_CustomEventDefault(void* ptr, void* event);
void QLowEnergyService_DeleteLater(void* ptr);
void QLowEnergyService_DeleteLaterDefault(void* ptr);
void QLowEnergyService_DisconnectNotify(void* ptr, void* sign);
void QLowEnergyService_DisconnectNotifyDefault(void* ptr, void* sign);
char QLowEnergyService_Event(void* ptr, void* e);
char QLowEnergyService_EventDefault(void* ptr, void* e);
char QLowEnergyService_EventFilter(void* ptr, void* watched, void* event);
char QLowEnergyService_EventFilterDefault(void* ptr, void* watched, void* event);
void* QLowEnergyService_MetaObject(void* ptr);
void* QLowEnergyService_MetaObjectDefault(void* ptr);
void* QLowEnergyServiceData_NewQLowEnergyServiceData();
void* QLowEnergyServiceData_NewQLowEnergyServiceData2(void* other);
void QLowEnergyServiceData_AddCharacteristic(void* ptr, void* characteristic);
void QLowEnergyServiceData_AddIncludedService(void* ptr, void* service);
struct QtBluetooth_PackedList QLowEnergyServiceData_Characteristics(void* ptr);
struct QtBluetooth_PackedList QLowEnergyServiceData_IncludedServices(void* ptr);
char QLowEnergyServiceData_IsValid(void* ptr);
void QLowEnergyServiceData_SetType(void* ptr, long long ty);
void QLowEnergyServiceData_SetUuid(void* ptr, void* uuid);
void QLowEnergyServiceData_Swap(void* ptr, void* other);
long long QLowEnergyServiceData_Type(void* ptr);
void* QLowEnergyServiceData_Uuid(void* ptr);
void QLowEnergyServiceData_DestroyQLowEnergyServiceData(void* ptr);
void* QLowEnergyServiceData_characteristics_atList(void* ptr, int i);
void* QLowEnergyServiceData_includedServices_atList(void* ptr, int i);

#ifdef __cplusplus
}
#endif

#endif