#ifdef __cplusplus
extern "C" {
#endif

void* QBluetoothAddress_NewQBluetoothAddress();
void* QBluetoothAddress_NewQBluetoothAddress4(void* other);
void* QBluetoothAddress_NewQBluetoothAddress3(char* address);
void QBluetoothAddress_Clear(void* ptr);
int QBluetoothAddress_IsNull(void* ptr);
char* QBluetoothAddress_ToString(void* ptr);
void QBluetoothAddress_DestroyQBluetoothAddress(void* ptr);
void QBluetoothDeviceDiscoveryAgent_ConnectCanceled(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectCanceled(void* ptr);
void QBluetoothDeviceDiscoveryAgent_ConnectFinished(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DisconnectFinished(void* ptr);
void* QBluetoothDeviceDiscoveryAgent_NewQBluetoothDeviceDiscoveryAgent(void* parent);
void* QBluetoothDeviceDiscoveryAgent_NewQBluetoothDeviceDiscoveryAgent2(void* deviceAdapter, void* parent);
int QBluetoothDeviceDiscoveryAgent_Error(void* ptr);
char* QBluetoothDeviceDiscoveryAgent_ErrorString(void* ptr);
int QBluetoothDeviceDiscoveryAgent_InquiryType(void* ptr);
int QBluetoothDeviceDiscoveryAgent_IsActive(void* ptr);
void QBluetoothDeviceDiscoveryAgent_SetInquiryType(void* ptr, int ty);
void QBluetoothDeviceDiscoveryAgent_Start(void* ptr);
void QBluetoothDeviceDiscoveryAgent_Stop(void* ptr);
void QBluetoothDeviceDiscoveryAgent_DestroyQBluetoothDeviceDiscoveryAgent(void* ptr);
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo();
void* QBluetoothDeviceInfo_NewQBluetoothDeviceInfo4(void* other);
int QBluetoothDeviceInfo_CoreConfigurations(void* ptr);
int QBluetoothDeviceInfo_IsCached(void* ptr);
int QBluetoothDeviceInfo_IsValid(void* ptr);
int QBluetoothDeviceInfo_MajorDeviceClass(void* ptr);
char* QBluetoothDeviceInfo_Name(void* ptr);
int QBluetoothDeviceInfo_ServiceClasses(void* ptr);
int QBluetoothDeviceInfo_ServiceUuidsCompleteness(void* ptr);
void QBluetoothDeviceInfo_SetCached(void* ptr, int cached);
void QBluetoothDeviceInfo_SetCoreConfigurations(void* ptr, int coreConfigs);
void QBluetoothDeviceInfo_SetDeviceUuid(void* ptr, void* uuid);
void QBluetoothDeviceInfo_DestroyQBluetoothDeviceInfo(void* ptr);
void* QBluetoothHostInfo_NewQBluetoothHostInfo();
void* QBluetoothHostInfo_NewQBluetoothHostInfo2(void* other);
char* QBluetoothHostInfo_Name(void* ptr);
void QBluetoothHostInfo_SetAddress(void* ptr, void* address);
void QBluetoothHostInfo_SetName(void* ptr, char* name);
void QBluetoothHostInfo_DestroyQBluetoothHostInfo(void* ptr);
void QBluetoothLocalDevice_ConnectError(void* ptr);
void QBluetoothLocalDevice_DisconnectError(void* ptr);
void QBluetoothLocalDevice_ConnectHostModeStateChanged(void* ptr);
void QBluetoothLocalDevice_DisconnectHostModeStateChanged(void* ptr);
int QBluetoothLocalDevice_IsValid(void* ptr);
void QBluetoothLocalDevice_DestroyQBluetoothLocalDevice(void* ptr);
void* QBluetoothLocalDevice_NewQBluetoothLocalDevice(void* parent);
void* QBluetoothLocalDevice_NewQBluetoothLocalDevice2(void* address, void* parent);
int QBluetoothLocalDevice_HostMode(void* ptr);
char* QBluetoothLocalDevice_Name(void* ptr);
void QBluetoothLocalDevice_PairingConfirmation(void* ptr, int accept);
int QBluetoothLocalDevice_PairingStatus(void* ptr, void* address);
void QBluetoothLocalDevice_PowerOn(void* ptr);
void QBluetoothLocalDevice_RequestPairing(void* ptr, void* address, int pairing);
void QBluetoothLocalDevice_SetHostMode(void* ptr, int mode);
void* QBluetoothServer_NewQBluetoothServer(int serverType, void* parent);
void QBluetoothServer_ConnectNewConnection(void* ptr);
void QBluetoothServer_DisconnectNewConnection(void* ptr);
int QBluetoothServer_Error(void* ptr);
int QBluetoothServer_IsListening(void* ptr);
int QBluetoothServer_MaxPendingConnections(void* ptr);
int QBluetoothServer_ServerType(void* ptr);
void QBluetoothServer_DestroyQBluetoothServer(void* ptr);
void QBluetoothServer_Close(void* ptr);
int QBluetoothServer_HasPendingConnections(void* ptr);
void* QBluetoothServer_NextPendingConnection(void* ptr);
void QBluetoothServer_SetMaxPendingConnections(void* ptr, int numConnections);
void QBluetoothServiceDiscoveryAgent_ConnectCanceled(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectCanceled(void* ptr);
void QBluetoothServiceDiscoveryAgent_ConnectFinished(void* ptr);
void QBluetoothServiceDiscoveryAgent_DisconnectFinished(void* ptr);
void* QBluetoothServiceDiscoveryAgent_NewQBluetoothServiceDiscoveryAgent(void* parent);
void* QBluetoothServiceDiscoveryAgent_NewQBluetoothServiceDiscoveryAgent2(void* deviceAdapter, void* parent);
void QBluetoothServiceDiscoveryAgent_Clear(void* ptr);
int QBluetoothServiceDiscoveryAgent_Error(void* ptr);
char* QBluetoothServiceDiscoveryAgent_ErrorString(void* ptr);
int QBluetoothServiceDiscoveryAgent_IsActive(void* ptr);
int QBluetoothServiceDiscoveryAgent_SetRemoteAddress(void* ptr, void* address);
void QBluetoothServiceDiscoveryAgent_SetUuidFilter2(void* ptr, void* uuid);
void QBluetoothServiceDiscoveryAgent_Start(void* ptr, int mode);
void QBluetoothServiceDiscoveryAgent_Stop(void* ptr);
void QBluetoothServiceDiscoveryAgent_DestroyQBluetoothServiceDiscoveryAgent(void* ptr);
int QBluetoothServiceInfo_ServiceName_Type();
int QBluetoothServiceInfo_ServiceDescription_Type();
int QBluetoothServiceInfo_ServiceProvider_Type();
char* QBluetoothServiceInfo_ServiceDescription(void* ptr);
char* QBluetoothServiceInfo_ServiceName(void* ptr);
char* QBluetoothServiceInfo_ServiceProvider(void* ptr);
void QBluetoothServiceInfo_SetServiceDescription(void* ptr, char* description);
void QBluetoothServiceInfo_SetServiceName(void* ptr, char* name);
void QBluetoothServiceInfo_SetServiceProvider(void* ptr, char* provider);
void QBluetoothServiceInfo_SetServiceUuid(void* ptr, void* uuid);
void* QBluetoothServiceInfo_NewQBluetoothServiceInfo();
void* QBluetoothServiceInfo_NewQBluetoothServiceInfo2(void* other);
int QBluetoothServiceInfo_IsComplete(void* ptr);
int QBluetoothServiceInfo_IsRegistered(void* ptr);
int QBluetoothServiceInfo_IsValid(void* ptr);
int QBluetoothServiceInfo_ProtocolServiceMultiplexer(void* ptr);
int QBluetoothServiceInfo_RegisterService(void* ptr, void* localAdapter);
int QBluetoothServiceInfo_ServerChannel(void* ptr);
void QBluetoothServiceInfo_SetDevice(void* ptr, void* device);
int QBluetoothServiceInfo_SocketProtocol(void* ptr);
int QBluetoothServiceInfo_UnregisterService(void* ptr);
void QBluetoothServiceInfo_DestroyQBluetoothServiceInfo(void* ptr);
void QBluetoothSocket_ConnectConnected(void* ptr);
void QBluetoothSocket_DisconnectConnected(void* ptr);
void QBluetoothSocket_ConnectDisconnected(void* ptr);
void QBluetoothSocket_DisconnectDisconnected(void* ptr);
void QBluetoothSocket_ConnectStateChanged(void* ptr);
void QBluetoothSocket_DisconnectStateChanged(void* ptr);
void* QBluetoothSocket_NewQBluetoothSocket(int socketType, void* parent);
void* QBluetoothSocket_NewQBluetoothSocket2(void* parent);
void QBluetoothSocket_Abort(void* ptr);
int QBluetoothSocket_CanReadLine(void* ptr);
void QBluetoothSocket_Close(void* ptr);
void QBluetoothSocket_ConnectToService2(void* ptr, void* address, void* uuid, int openMode);
void QBluetoothSocket_ConnectToService(void* ptr, void* service, int openMode);
void QBluetoothSocket_DisconnectFromService(void* ptr);
int QBluetoothSocket_Error(void* ptr);
char* QBluetoothSocket_ErrorString(void* ptr);
int QBluetoothSocket_IsSequential(void* ptr);
char* QBluetoothSocket_LocalName(void* ptr);
char* QBluetoothSocket_PeerName(void* ptr);
int QBluetoothSocket_SetSocketDescriptor(void* ptr, int socketDescriptor, int socketType, int socketState, int openMode);
int QBluetoothSocket_SocketDescriptor(void* ptr);
int QBluetoothSocket_SocketType(void* ptr);
void QBluetoothSocket_DestroyQBluetoothSocket(void* ptr);
void* QBluetoothTransferManager_Put(void* ptr, void* request, void* data);
void* QBluetoothTransferManager_NewQBluetoothTransferManager(void* parent);
void QBluetoothTransferManager_ConnectFinished(void* ptr);
void QBluetoothTransferManager_DisconnectFinished(void* ptr);
void QBluetoothTransferManager_DestroyQBluetoothTransferManager(void* ptr);
void QBluetoothTransferReply_Abort(void* ptr);
int QBluetoothTransferReply_Error(void* ptr);
char* QBluetoothTransferReply_ErrorString(void* ptr);
void QBluetoothTransferReply_ConnectFinished(void* ptr);
void QBluetoothTransferReply_DisconnectFinished(void* ptr);
int QBluetoothTransferReply_IsFinished(void* ptr);
int QBluetoothTransferReply_IsRunning(void* ptr);
void* QBluetoothTransferReply_Manager(void* ptr);
void QBluetoothTransferReply_DestroyQBluetoothTransferReply(void* ptr);
void* QBluetoothTransferRequest_NewQBluetoothTransferRequest(void* address);
void* QBluetoothTransferRequest_NewQBluetoothTransferRequest2(void* other);
void* QBluetoothTransferRequest_Attribute(void* ptr, int code, void* defaultValue);
void QBluetoothTransferRequest_SetAttribute(void* ptr, int code, void* value);
void QBluetoothTransferRequest_DestroyQBluetoothTransferRequest(void* ptr);
void* QBluetoothUuid_NewQBluetoothUuid();
void* QBluetoothUuid_NewQBluetoothUuid4(int uuid);
void* QBluetoothUuid_NewQBluetoothUuid5(int uuid);
void* QBluetoothUuid_NewQBluetoothUuid2(int uuid);
void* QBluetoothUuid_NewQBluetoothUuid3(int uuid);
void* QBluetoothUuid_NewQBluetoothUuid10(void* uuid);
void* QBluetoothUuid_NewQBluetoothUuid9(char* uuid);
void* QBluetoothUuid_NewQBluetoothUuid11(void* uuid);
char* QBluetoothUuid_QBluetoothUuid_CharacteristicToString(int uuid);
char* QBluetoothUuid_QBluetoothUuid_DescriptorToString(int uuid);
int QBluetoothUuid_MinimumSize(void* ptr);
char* QBluetoothUuid_QBluetoothUuid_ProtocolToString(int uuid);
char* QBluetoothUuid_QBluetoothUuid_ServiceClassToString(int uuid);
void QBluetoothUuid_DestroyQBluetoothUuid(void* ptr);
void* QLowEnergyCharacteristic_NewQLowEnergyCharacteristic();
void* QLowEnergyCharacteristic_NewQLowEnergyCharacteristic2(void* other);
int QLowEnergyCharacteristic_IsValid(void* ptr);
char* QLowEnergyCharacteristic_Name(void* ptr);
int QLowEnergyCharacteristic_Properties(void* ptr);
void* QLowEnergyCharacteristic_Value(void* ptr);
void QLowEnergyCharacteristic_DestroyQLowEnergyCharacteristic(void* ptr);
void QLowEnergyController_ConnectConnected(void* ptr);
void QLowEnergyController_DisconnectConnected(void* ptr);
void QLowEnergyController_ConnectDisconnected(void* ptr);
void QLowEnergyController_DisconnectDisconnected(void* ptr);
void QLowEnergyController_ConnectDiscoveryFinished(void* ptr);
void QLowEnergyController_DisconnectDiscoveryFinished(void* ptr);
void QLowEnergyController_ConnectStateChanged(void* ptr);
void QLowEnergyController_DisconnectStateChanged(void* ptr);
void* QLowEnergyController_NewQLowEnergyController(void* remoteDeviceInfo, void* parent);
void QLowEnergyController_ConnectToDevice(void* ptr);
void* QLowEnergyController_CreateServiceObject(void* ptr, void* serviceUuid, void* parent);
void QLowEnergyController_DisconnectFromDevice(void* ptr);
void QLowEnergyController_DiscoverServices(void* ptr);
int QLowEnergyController_Error(void* ptr);
char* QLowEnergyController_ErrorString(void* ptr);
int QLowEnergyController_RemoteAddressType(void* ptr);
char* QLowEnergyController_RemoteName(void* ptr);
void QLowEnergyController_SetRemoteAddressType(void* ptr, int ty);
void QLowEnergyController_DestroyQLowEnergyController(void* ptr);
void* QLowEnergyDescriptor_NewQLowEnergyDescriptor();
void* QLowEnergyDescriptor_NewQLowEnergyDescriptor2(void* other);
int QLowEnergyDescriptor_IsValid(void* ptr);
char* QLowEnergyDescriptor_Name(void* ptr);
int QLowEnergyDescriptor_Type(void* ptr);
void* QLowEnergyDescriptor_Value(void* ptr);
void QLowEnergyDescriptor_DestroyQLowEnergyDescriptor(void* ptr);
void QLowEnergyService_ConnectStateChanged(void* ptr);
void QLowEnergyService_DisconnectStateChanged(void* ptr);
int QLowEnergyService_Contains(void* ptr, void* characteristic);
int QLowEnergyService_Contains2(void* ptr, void* descriptor);
void QLowEnergyService_DiscoverDetails(void* ptr);
int QLowEnergyService_Error(void* ptr);
void QLowEnergyService_ReadCharacteristic(void* ptr, void* characteristic);
void QLowEnergyService_ReadDescriptor(void* ptr, void* descriptor);
char* QLowEnergyService_ServiceName(void* ptr);
int QLowEnergyService_Type(void* ptr);
void QLowEnergyService_WriteCharacteristic(void* ptr, void* characteristic, void* newValue, int mode);
void QLowEnergyService_WriteDescriptor(void* ptr, void* descriptor, void* newValue);
void QLowEnergyService_DestroyQLowEnergyService(void* ptr);

#ifdef __cplusplus
}
#endif