// +build !minimal

#pragma once

#ifndef GO_QTCHARTS_H
#define GO_QTCHARTS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct QtCharts_PackedString { char* data; long long len; };
struct QtCharts_PackedList { void* data; long long len; };
long long QAbstractAxis_Alignment(void* ptr);
void* QAbstractAxis_GridLineColor(void* ptr);
char QAbstractAxis_IsGridLineVisible(void* ptr);
char QAbstractAxis_IsLineVisible(void* ptr);
char QAbstractAxis_IsMinorGridLineVisible(void* ptr);
char QAbstractAxis_IsReverse(void* ptr);
char QAbstractAxis_IsTitleVisible(void* ptr);
char QAbstractAxis_IsVisible(void* ptr);
int QAbstractAxis_LabelsAngle(void* ptr);
void* QAbstractAxis_LabelsColor(void* ptr);
char QAbstractAxis_LabelsVisible(void* ptr);
void* QAbstractAxis_LinePenColor(void* ptr);
void* QAbstractAxis_MinorGridLineColor(void* ptr);
void* QAbstractAxis_MinorGridLinePen(void* ptr);
void QAbstractAxis_SetGridLineColor(void* ptr, void* color);
void QAbstractAxis_SetGridLineVisible(void* ptr, char visible);
void QAbstractAxis_SetLabelsAngle(void* ptr, int angle);
void QAbstractAxis_SetLabelsColor(void* ptr, void* color);
void QAbstractAxis_SetLabelsVisible(void* ptr, char visible);
void QAbstractAxis_SetLinePenColor(void* ptr, void* color);
void QAbstractAxis_SetMinorGridLineColor(void* ptr, void* color);
void QAbstractAxis_SetMinorGridLinePen(void* ptr, void* pen);
void QAbstractAxis_SetMinorGridLineVisible(void* ptr, char visible);
void QAbstractAxis_SetReverse(void* ptr, char reverse);
void QAbstractAxis_SetShadesBorderColor(void* ptr, void* color);
void QAbstractAxis_SetShadesColor(void* ptr, void* color);
void QAbstractAxis_SetShadesVisible(void* ptr, char visible);
void QAbstractAxis_SetTitleText(void* ptr, char* title);
void QAbstractAxis_SetTitleVisible(void* ptr, char visible);
void* QAbstractAxis_ShadesBorderColor(void* ptr);
void* QAbstractAxis_ShadesColor(void* ptr);
char QAbstractAxis_ShadesVisible(void* ptr);
struct QtCharts_PackedString QAbstractAxis_TitleText(void* ptr);
void QAbstractAxis_ConnectColorChanged(void* ptr);
void QAbstractAxis_DisconnectColorChanged(void* ptr);
void QAbstractAxis_ColorChanged(void* ptr, void* color);
void QAbstractAxis_ConnectGridLineColorChanged(void* ptr);
void QAbstractAxis_DisconnectGridLineColorChanged(void* ptr);
void QAbstractAxis_GridLineColorChanged(void* ptr, void* color);
void* QAbstractAxis_GridLinePen(void* ptr);
void QAbstractAxis_ConnectGridLinePenChanged(void* ptr);
void QAbstractAxis_DisconnectGridLinePenChanged(void* ptr);
void QAbstractAxis_GridLinePenChanged(void* ptr, void* pen);
void QAbstractAxis_ConnectGridVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectGridVisibleChanged(void* ptr);
void QAbstractAxis_GridVisibleChanged(void* ptr, char visible);
void QAbstractAxis_Hide(void* ptr);
void QAbstractAxis_ConnectLabelsAngleChanged(void* ptr);
void QAbstractAxis_DisconnectLabelsAngleChanged(void* ptr);
void QAbstractAxis_LabelsAngleChanged(void* ptr, int angle);
void* QAbstractAxis_LabelsBrush(void* ptr);
void QAbstractAxis_ConnectLabelsBrushChanged(void* ptr);
void QAbstractAxis_DisconnectLabelsBrushChanged(void* ptr);
void QAbstractAxis_LabelsBrushChanged(void* ptr, void* brush);
void QAbstractAxis_ConnectLabelsColorChanged(void* ptr);
void QAbstractAxis_DisconnectLabelsColorChanged(void* ptr);
void QAbstractAxis_LabelsColorChanged(void* ptr, void* color);
void* QAbstractAxis_LabelsFont(void* ptr);
void QAbstractAxis_ConnectLabelsFontChanged(void* ptr);
void QAbstractAxis_DisconnectLabelsFontChanged(void* ptr);
void QAbstractAxis_LabelsFontChanged(void* ptr, void* font);
void QAbstractAxis_ConnectLabelsVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectLabelsVisibleChanged(void* ptr);
void QAbstractAxis_LabelsVisibleChanged(void* ptr, char visible);
void* QAbstractAxis_LinePen(void* ptr);
void QAbstractAxis_ConnectLinePenChanged(void* ptr);
void QAbstractAxis_DisconnectLinePenChanged(void* ptr);
void QAbstractAxis_LinePenChanged(void* ptr, void* pen);
void QAbstractAxis_ConnectLineVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectLineVisibleChanged(void* ptr);
void QAbstractAxis_LineVisibleChanged(void* ptr, char visible);
void QAbstractAxis_ConnectMinorGridLineColorChanged(void* ptr);
void QAbstractAxis_DisconnectMinorGridLineColorChanged(void* ptr);
void QAbstractAxis_MinorGridLineColorChanged(void* ptr, void* color);
void QAbstractAxis_ConnectMinorGridLinePenChanged(void* ptr);
void QAbstractAxis_DisconnectMinorGridLinePenChanged(void* ptr);
void QAbstractAxis_MinorGridLinePenChanged(void* ptr, void* pen);
void QAbstractAxis_ConnectMinorGridVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectMinorGridVisibleChanged(void* ptr);
void QAbstractAxis_MinorGridVisibleChanged(void* ptr, char visible);
long long QAbstractAxis_Orientation(void* ptr);
void QAbstractAxis_ConnectReverseChanged(void* ptr);
void QAbstractAxis_DisconnectReverseChanged(void* ptr);
void QAbstractAxis_ReverseChanged(void* ptr, char reverse);
void QAbstractAxis_SetGridLinePen(void* ptr, void* pen);
void QAbstractAxis_SetLabelsBrush(void* ptr, void* brush);
void QAbstractAxis_SetLabelsFont(void* ptr, void* font);
void QAbstractAxis_SetLinePen(void* ptr, void* pen);
void QAbstractAxis_SetLineVisible(void* ptr, char visible);
void QAbstractAxis_SetMax(void* ptr, void* max);
void QAbstractAxis_SetMin(void* ptr, void* min);
void QAbstractAxis_SetRange(void* ptr, void* min, void* max);
void QAbstractAxis_SetShadesBrush(void* ptr, void* brush);
void QAbstractAxis_SetShadesPen(void* ptr, void* pen);
void QAbstractAxis_SetTitleBrush(void* ptr, void* brush);
void QAbstractAxis_SetTitleFont(void* ptr, void* font);
void QAbstractAxis_SetVisible(void* ptr, char visible);
void QAbstractAxis_ConnectShadesBorderColorChanged(void* ptr);
void QAbstractAxis_DisconnectShadesBorderColorChanged(void* ptr);
void QAbstractAxis_ShadesBorderColorChanged(void* ptr, void* color);
void* QAbstractAxis_ShadesBrush(void* ptr);
void QAbstractAxis_ConnectShadesBrushChanged(void* ptr);
void QAbstractAxis_DisconnectShadesBrushChanged(void* ptr);
void QAbstractAxis_ShadesBrushChanged(void* ptr, void* brush);
void QAbstractAxis_ConnectShadesColorChanged(void* ptr);
void QAbstractAxis_DisconnectShadesColorChanged(void* ptr);
void QAbstractAxis_ShadesColorChanged(void* ptr, void* color);
void* QAbstractAxis_ShadesPen(void* ptr);
void QAbstractAxis_ConnectShadesPenChanged(void* ptr);
void QAbstractAxis_DisconnectShadesPenChanged(void* ptr);
void QAbstractAxis_ShadesPenChanged(void* ptr, void* pen);
void QAbstractAxis_ConnectShadesVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectShadesVisibleChanged(void* ptr);
void QAbstractAxis_ShadesVisibleChanged(void* ptr, char visible);
void QAbstractAxis_Show(void* ptr);
void* QAbstractAxis_TitleBrush(void* ptr);
void QAbstractAxis_ConnectTitleBrushChanged(void* ptr);
void QAbstractAxis_DisconnectTitleBrushChanged(void* ptr);
void QAbstractAxis_TitleBrushChanged(void* ptr, void* brush);
void* QAbstractAxis_TitleFont(void* ptr);
void QAbstractAxis_ConnectTitleFontChanged(void* ptr);
void QAbstractAxis_DisconnectTitleFontChanged(void* ptr);
void QAbstractAxis_TitleFontChanged(void* ptr, void* font);
void QAbstractAxis_ConnectTitleTextChanged(void* ptr);
void QAbstractAxis_DisconnectTitleTextChanged(void* ptr);
void QAbstractAxis_TitleTextChanged(void* ptr, char* text);
void QAbstractAxis_ConnectTitleVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectTitleVisibleChanged(void* ptr);
void QAbstractAxis_TitleVisibleChanged(void* ptr, char visible);
long long QAbstractAxis_Type(void* ptr);
void QAbstractAxis_ConnectVisibleChanged(void* ptr);
void QAbstractAxis_DisconnectVisibleChanged(void* ptr);
void QAbstractAxis_VisibleChanged(void* ptr, char visible);
void QAbstractAxis_DestroyQAbstractAxis(void* ptr);
double QAbstractBarSeries_LabelsAngle(void* ptr);
struct QtCharts_PackedString QAbstractBarSeries_LabelsFormat(void* ptr);
long long QAbstractBarSeries_LabelsPosition(void* ptr);
void QAbstractBarSeries_SetLabelsAngle(void* ptr, double angle);
void QAbstractBarSeries_SetLabelsFormat(void* ptr, char* format);
void QAbstractBarSeries_SetLabelsPosition(void* ptr, long long position);
char QAbstractBarSeries_Append(void* ptr, void* set);
char QAbstractBarSeries_Append2(void* ptr, void* sets);
struct QtCharts_PackedList QAbstractBarSeries_BarSets(void* ptr);
double QAbstractBarSeries_BarWidth(void* ptr);
void QAbstractBarSeries_ConnectBarsetsAdded(void* ptr);
void QAbstractBarSeries_DisconnectBarsetsAdded(void* ptr);
void QAbstractBarSeries_BarsetsAdded(void* ptr, void* sets);
void QAbstractBarSeries_ConnectBarsetsRemoved(void* ptr);
void QAbstractBarSeries_DisconnectBarsetsRemoved(void* ptr);
void QAbstractBarSeries_BarsetsRemoved(void* ptr, void* sets);
void QAbstractBarSeries_Clear(void* ptr);
void QAbstractBarSeries_ConnectClicked(void* ptr);
void QAbstractBarSeries_DisconnectClicked(void* ptr);
void QAbstractBarSeries_Clicked(void* ptr, int index, void* barset);
int QAbstractBarSeries_Count(void* ptr);
void QAbstractBarSeries_ConnectCountChanged(void* ptr);
void QAbstractBarSeries_DisconnectCountChanged(void* ptr);
void QAbstractBarSeries_CountChanged(void* ptr);
void QAbstractBarSeries_ConnectDoubleClicked(void* ptr);
void QAbstractBarSeries_DisconnectDoubleClicked(void* ptr);
void QAbstractBarSeries_DoubleClicked(void* ptr, int index, void* barset);
void QAbstractBarSeries_ConnectHovered(void* ptr);
void QAbstractBarSeries_DisconnectHovered(void* ptr);
void QAbstractBarSeries_Hovered(void* ptr, char status, int index, void* barset);
char QAbstractBarSeries_Insert(void* ptr, int index, void* set);
char QAbstractBarSeries_IsLabelsVisible(void* ptr);
void QAbstractBarSeries_ConnectLabelsAngleChanged(void* ptr);
void QAbstractBarSeries_DisconnectLabelsAngleChanged(void* ptr);
void QAbstractBarSeries_LabelsAngleChanged(void* ptr, double angle);
void QAbstractBarSeries_ConnectLabelsFormatChanged(void* ptr);
void QAbstractBarSeries_DisconnectLabelsFormatChanged(void* ptr);
void QAbstractBarSeries_LabelsFormatChanged(void* ptr, char* format);
void QAbstractBarSeries_ConnectLabelsPositionChanged(void* ptr);
void QAbstractBarSeries_DisconnectLabelsPositionChanged(void* ptr);
void QAbstractBarSeries_LabelsPositionChanged(void* ptr, long long position);
void QAbstractBarSeries_ConnectLabelsVisibleChanged(void* ptr);
void QAbstractBarSeries_DisconnectLabelsVisibleChanged(void* ptr);
void QAbstractBarSeries_LabelsVisibleChanged(void* ptr);
void QAbstractBarSeries_ConnectPressed(void* ptr);
void QAbstractBarSeries_DisconnectPressed(void* ptr);
void QAbstractBarSeries_Pressed(void* ptr, int index, void* barset);
void QAbstractBarSeries_ConnectReleased(void* ptr);
void QAbstractBarSeries_DisconnectReleased(void* ptr);
void QAbstractBarSeries_Released(void* ptr, int index, void* barset);
char QAbstractBarSeries_Remove(void* ptr, void* set);
void QAbstractBarSeries_SetBarWidth(void* ptr, double width);
void QAbstractBarSeries_SetLabelsVisible(void* ptr, char visible);
char QAbstractBarSeries_Take(void* ptr, void* set);
void QAbstractBarSeries_DestroyQAbstractBarSeries(void* ptr);
void QAbstractBarSeries_DestroyQAbstractBarSeriesDefault(void* ptr);
void* QAbstractBarSeries___append_sets_atList2(void* ptr, int i);
void QAbstractBarSeries___append_sets_setList2(void* ptr, void* i);
void* QAbstractBarSeries___append_sets_newList2(void* ptr);
void* QAbstractBarSeries___barSets_atList(void* ptr, int i);
void QAbstractBarSeries___barSets_setList(void* ptr, void* i);
void* QAbstractBarSeries___barSets_newList(void* ptr);
void* QAbstractBarSeries___barsetsAdded_sets_atList(void* ptr, int i);
void QAbstractBarSeries___barsetsAdded_sets_setList(void* ptr, void* i);
void* QAbstractBarSeries___barsetsAdded_sets_newList(void* ptr);
void* QAbstractBarSeries___barsetsRemoved_sets_atList(void* ptr, int i);
void QAbstractBarSeries___barsetsRemoved_sets_setList(void* ptr, void* i);
void* QAbstractBarSeries___barsetsRemoved_sets_newList(void* ptr);
char QAbstractSeries_IsVisible(void* ptr);
struct QtCharts_PackedString QAbstractSeries_Name(void* ptr);
double QAbstractSeries_Opacity(void* ptr);
void QAbstractSeries_SetName(void* ptr, char* name);
void QAbstractSeries_SetOpacity(void* ptr, double opacity);
void QAbstractSeries_SetUseOpenGL(void* ptr, char enable);
void QAbstractSeries_SetVisible(void* ptr, char visible);
char QAbstractSeries_UseOpenGL(void* ptr);
char QAbstractSeries_AttachAxis(void* ptr, void* axis);
struct QtCharts_PackedList QAbstractSeries_AttachedAxes(void* ptr);
void* QAbstractSeries_Chart(void* ptr);
char QAbstractSeries_DetachAxis(void* ptr, void* axis);
void QAbstractSeries_Hide(void* ptr);
void QAbstractSeries_ConnectNameChanged(void* ptr);
void QAbstractSeries_DisconnectNameChanged(void* ptr);
void QAbstractSeries_NameChanged(void* ptr);
void QAbstractSeries_ConnectOpacityChanged(void* ptr);
void QAbstractSeries_DisconnectOpacityChanged(void* ptr);
void QAbstractSeries_OpacityChanged(void* ptr);
void QAbstractSeries_Show(void* ptr);
long long QAbstractSeries_Type(void* ptr);
void QAbstractSeries_ConnectUseOpenGLChanged(void* ptr);
void QAbstractSeries_DisconnectUseOpenGLChanged(void* ptr);
void QAbstractSeries_UseOpenGLChanged(void* ptr);
void QAbstractSeries_ConnectVisibleChanged(void* ptr);
void QAbstractSeries_DisconnectVisibleChanged(void* ptr);
void QAbstractSeries_VisibleChanged(void* ptr);
void QAbstractSeries_DestroyQAbstractSeries(void* ptr);
void* QAbstractSeries___attachedAxes_atList(void* ptr, int i);
void QAbstractSeries___attachedAxes_setList(void* ptr, void* i);
void* QAbstractSeries___attachedAxes_newList(void* ptr);
void* QAreaLegendMarker_Series(void* ptr);
void* QAreaLegendMarker_SeriesDefault(void* ptr);
void QAreaLegendMarker_DestroyQAreaLegendMarker(void* ptr);
void QAreaLegendMarker_DestroyQAreaLegendMarkerDefault(void* ptr);
void* QAreaSeries_BorderColor(void* ptr);
void* QAreaSeries_Brush(void* ptr);
void* QAreaSeries_Color(void* ptr);
void* QAreaSeries_LowerSeries(void* ptr);
void* QAreaSeries_Pen(void* ptr);
char QAreaSeries_PointLabelsClipping(void* ptr);
void* QAreaSeries_PointLabelsColor(void* ptr);
void* QAreaSeries_PointLabelsFont(void* ptr);
struct QtCharts_PackedString QAreaSeries_PointLabelsFormat(void* ptr);
char QAreaSeries_PointLabelsVisible(void* ptr);
void QAreaSeries_SetBorderColor(void* ptr, void* color);
void QAreaSeries_SetColor(void* ptr, void* color);
void QAreaSeries_SetPointLabelsClipping(void* ptr, char enabled);
void QAreaSeries_SetPointLabelsColor(void* ptr, void* color);
void QAreaSeries_SetPointLabelsFont(void* ptr, void* font);
void QAreaSeries_SetPointLabelsFormat(void* ptr, char* format);
void QAreaSeries_SetPointLabelsVisible(void* ptr, char visible);
void* QAreaSeries_UpperSeries(void* ptr);
void* QAreaSeries_NewQAreaSeries2(void* upperSeries, void* lowerSeries);
void* QAreaSeries_NewQAreaSeries(void* parent);
void QAreaSeries_ConnectBorderColorChanged(void* ptr);
void QAreaSeries_DisconnectBorderColorChanged(void* ptr);
void QAreaSeries_BorderColorChanged(void* ptr, void* color);
void QAreaSeries_ConnectClicked(void* ptr);
void QAreaSeries_DisconnectClicked(void* ptr);
void QAreaSeries_Clicked(void* ptr, void* point);
void QAreaSeries_ConnectColorChanged(void* ptr);
void QAreaSeries_DisconnectColorChanged(void* ptr);
void QAreaSeries_ColorChanged(void* ptr, void* color);
void QAreaSeries_ConnectDoubleClicked(void* ptr);
void QAreaSeries_DisconnectDoubleClicked(void* ptr);
void QAreaSeries_DoubleClicked(void* ptr, void* point);
void QAreaSeries_ConnectHovered(void* ptr);
void QAreaSeries_DisconnectHovered(void* ptr);
void QAreaSeries_Hovered(void* ptr, void* point, char state);
void QAreaSeries_ConnectPointLabelsClippingChanged(void* ptr);
void QAreaSeries_DisconnectPointLabelsClippingChanged(void* ptr);
void QAreaSeries_PointLabelsClippingChanged(void* ptr, char clipping);
void QAreaSeries_ConnectPointLabelsColorChanged(void* ptr);
void QAreaSeries_DisconnectPointLabelsColorChanged(void* ptr);
void QAreaSeries_PointLabelsColorChanged(void* ptr, void* color);
void QAreaSeries_ConnectPointLabelsFontChanged(void* ptr);
void QAreaSeries_DisconnectPointLabelsFontChanged(void* ptr);
void QAreaSeries_PointLabelsFontChanged(void* ptr, void* font);
void QAreaSeries_ConnectPointLabelsFormatChanged(void* ptr);
void QAreaSeries_DisconnectPointLabelsFormatChanged(void* ptr);
void QAreaSeries_PointLabelsFormatChanged(void* ptr, char* format);
void QAreaSeries_ConnectPointLabelsVisibilityChanged(void* ptr);
void QAreaSeries_DisconnectPointLabelsVisibilityChanged(void* ptr);
void QAreaSeries_PointLabelsVisibilityChanged(void* ptr, char visible);
char QAreaSeries_PointsVisible(void* ptr);
void QAreaSeries_ConnectPressed(void* ptr);
void QAreaSeries_DisconnectPressed(void* ptr);
void QAreaSeries_Pressed(void* ptr, void* point);
void QAreaSeries_ConnectReleased(void* ptr);
void QAreaSeries_DisconnectReleased(void* ptr);
void QAreaSeries_Released(void* ptr, void* point);
void QAreaSeries_ConnectSelected(void* ptr);
void QAreaSeries_DisconnectSelected(void* ptr);
void QAreaSeries_Selected(void* ptr);
void QAreaSeries_SetBrush(void* ptr, void* brush);
void QAreaSeries_SetLowerSeries(void* ptr, void* series);
void QAreaSeries_SetPen(void* ptr, void* pen);
void QAreaSeries_SetPointsVisible(void* ptr, char visible);
void QAreaSeries_SetUpperSeries(void* ptr, void* series);
long long QAreaSeries_Type(void* ptr);
long long QAreaSeries_TypeDefault(void* ptr);
void QAreaSeries_DestroyQAreaSeries(void* ptr);
void* QBarCategoryAxis_NewQBarCategoryAxis(void* parent);
void QBarCategoryAxis_Append2(void* ptr, char* category);
void QBarCategoryAxis_Append(void* ptr, char* categories);
struct QtCharts_PackedString QBarCategoryAxis_At(void* ptr, int index);
struct QtCharts_PackedString QBarCategoryAxis_Categories(void* ptr);
void QBarCategoryAxis_ConnectCategoriesChanged(void* ptr);
void QBarCategoryAxis_DisconnectCategoriesChanged(void* ptr);
void QBarCategoryAxis_CategoriesChanged(void* ptr);
void QBarCategoryAxis_Clear(void* ptr);
int QBarCategoryAxis_Count(void* ptr);
void QBarCategoryAxis_ConnectCountChanged(void* ptr);
void QBarCategoryAxis_DisconnectCountChanged(void* ptr);
void QBarCategoryAxis_CountChanged(void* ptr);
void QBarCategoryAxis_Insert(void* ptr, int index, char* category);
struct QtCharts_PackedString QBarCategoryAxis_Max(void* ptr);
void QBarCategoryAxis_ConnectMaxChanged(void* ptr);
void QBarCategoryAxis_DisconnectMaxChanged(void* ptr);
void QBarCategoryAxis_MaxChanged(void* ptr, char* max);
struct QtCharts_PackedString QBarCategoryAxis_Min(void* ptr);
void QBarCategoryAxis_ConnectMinChanged(void* ptr);
void QBarCategoryAxis_DisconnectMinChanged(void* ptr);
void QBarCategoryAxis_MinChanged(void* ptr, char* min);
void QBarCategoryAxis_ConnectRangeChanged(void* ptr);
void QBarCategoryAxis_DisconnectRangeChanged(void* ptr);
void QBarCategoryAxis_RangeChanged(void* ptr, char* min, char* max);
void QBarCategoryAxis_Remove(void* ptr, char* category);
void QBarCategoryAxis_Replace(void* ptr, char* oldCategory, char* newCategory);
void QBarCategoryAxis_SetCategories(void* ptr, char* categories);
void QBarCategoryAxis_SetMax(void* ptr, char* max);
void QBarCategoryAxis_SetMin(void* ptr, char* min);
void QBarCategoryAxis_SetRange(void* ptr, char* minCategory, char* maxCategory);
void QBarCategoryAxis_DestroyQBarCategoryAxis(void* ptr);
void* QBarLegendMarker_Barset(void* ptr);
void* QBarLegendMarker_Series(void* ptr);
void* QBarLegendMarker_SeriesDefault(void* ptr);
void QBarLegendMarker_DestroyQBarLegendMarker(void* ptr);
void QBarLegendMarker_DestroyQBarLegendMarkerDefault(void* ptr);
void* QBarSeries_NewQBarSeries(void* parent);
long long QBarSeries_Type(void* ptr);
long long QBarSeries_TypeDefault(void* ptr);
void QBarSeries_DestroyQBarSeries(void* ptr);
void* QBarSet_NewQBarSet(char* label, void* parent);
void QBarSet_Append2(void* ptr, void* values);
void QBarSet_Append(void* ptr, double value);
double QBarSet_At(void* ptr, int index);
void* QBarSet_BorderColor(void* ptr);
void QBarSet_ConnectBorderColorChanged(void* ptr);
void QBarSet_DisconnectBorderColorChanged(void* ptr);
void QBarSet_BorderColorChanged(void* ptr, void* color);
void* QBarSet_Brush(void* ptr);
void QBarSet_ConnectBrushChanged(void* ptr);
void QBarSet_DisconnectBrushChanged(void* ptr);
void QBarSet_BrushChanged(void* ptr);
void QBarSet_ConnectClicked(void* ptr);
void QBarSet_DisconnectClicked(void* ptr);
void QBarSet_Clicked(void* ptr, int index);
void* QBarSet_Color(void* ptr);
void QBarSet_ConnectColorChanged(void* ptr);
void QBarSet_DisconnectColorChanged(void* ptr);
void QBarSet_ColorChanged(void* ptr, void* color);
int QBarSet_Count(void* ptr);
void QBarSet_ConnectDoubleClicked(void* ptr);
void QBarSet_DisconnectDoubleClicked(void* ptr);
void QBarSet_DoubleClicked(void* ptr, int index);
void QBarSet_ConnectHovered(void* ptr);
void QBarSet_DisconnectHovered(void* ptr);
void QBarSet_Hovered(void* ptr, char status, int index);
void QBarSet_Insert(void* ptr, int index, double value);
struct QtCharts_PackedString QBarSet_Label(void* ptr);
void* QBarSet_LabelBrush(void* ptr);
void QBarSet_ConnectLabelBrushChanged(void* ptr);
void QBarSet_DisconnectLabelBrushChanged(void* ptr);
void QBarSet_LabelBrushChanged(void* ptr);
void QBarSet_ConnectLabelChanged(void* ptr);
void QBarSet_DisconnectLabelChanged(void* ptr);
void QBarSet_LabelChanged(void* ptr);
void* QBarSet_LabelColor(void* ptr);
void QBarSet_ConnectLabelColorChanged(void* ptr);
void QBarSet_DisconnectLabelColorChanged(void* ptr);
void QBarSet_LabelColorChanged(void* ptr, void* color);
void* QBarSet_LabelFont(void* ptr);
void QBarSet_ConnectLabelFontChanged(void* ptr);
void QBarSet_DisconnectLabelFontChanged(void* ptr);
void QBarSet_LabelFontChanged(void* ptr);
void* QBarSet_Pen(void* ptr);
void QBarSet_ConnectPenChanged(void* ptr);
void QBarSet_DisconnectPenChanged(void* ptr);
void QBarSet_PenChanged(void* ptr);
void QBarSet_ConnectPressed(void* ptr);
void QBarSet_DisconnectPressed(void* ptr);
void QBarSet_Pressed(void* ptr, int index);
void QBarSet_ConnectReleased(void* ptr);
void QBarSet_DisconnectReleased(void* ptr);
void QBarSet_Released(void* ptr, int index);
void QBarSet_Remove(void* ptr, int index, int count);
void QBarSet_Replace(void* ptr, int index, double value);
void QBarSet_SetBorderColor(void* ptr, void* color);
void QBarSet_SetBrush(void* ptr, void* brush);
void QBarSet_SetColor(void* ptr, void* color);
void QBarSet_SetLabel(void* ptr, char* label);
void QBarSet_SetLabelBrush(void* ptr, void* brush);
void QBarSet_SetLabelColor(void* ptr, void* color);
void QBarSet_SetLabelFont(void* ptr, void* font);
void QBarSet_SetPen(void* ptr, void* pen);
double QBarSet_Sum(void* ptr);
void QBarSet_ConnectValueChanged(void* ptr);
void QBarSet_DisconnectValueChanged(void* ptr);
void QBarSet_ValueChanged(void* ptr, int index);
void QBarSet_ConnectValuesAdded(void* ptr);
void QBarSet_DisconnectValuesAdded(void* ptr);
void QBarSet_ValuesAdded(void* ptr, int index, int count);
void QBarSet_ConnectValuesRemoved(void* ptr);
void QBarSet_DisconnectValuesRemoved(void* ptr);
void QBarSet_ValuesRemoved(void* ptr, int index, int count);
void QBarSet_DestroyQBarSet(void* ptr);
void QBarSet_DestroyQBarSetDefault(void* ptr);
double QBarSet___append_values_atList2(void* ptr, int i);
void QBarSet___append_values_setList2(void* ptr, double i);
void* QBarSet___append_values_newList2(void* ptr);
void* QBoxPlotLegendMarker_Series(void* ptr);
void* QBoxPlotLegendMarker_SeriesDefault(void* ptr);
void QBoxPlotLegendMarker_DestroyQBoxPlotLegendMarker(void* ptr);
void QBoxPlotLegendMarker_DestroyQBoxPlotLegendMarkerDefault(void* ptr);
char QBoxPlotSeries_BoxOutlineVisible(void* ptr);
double QBoxPlotSeries_BoxWidth(void* ptr);
void* QBoxPlotSeries_Brush(void* ptr);
void* QBoxPlotSeries_Pen(void* ptr);
void QBoxPlotSeries_SetBoxOutlineVisible(void* ptr, char visible);
void QBoxPlotSeries_SetBoxWidth(void* ptr, double width);
void QBoxPlotSeries_SetBrush(void* ptr, void* brush);
void QBoxPlotSeries_SetPen(void* ptr, void* pen);
long long QBoxPlotSeries_Type(void* ptr);
long long QBoxPlotSeries_TypeDefault(void* ptr);
void* QBoxPlotSeries_NewQBoxPlotSeries(void* parent);
char QBoxPlotSeries_Append(void* ptr, void* set);
char QBoxPlotSeries_Append2(void* ptr, void* sets);
void QBoxPlotSeries_ConnectBoxOutlineVisibilityChanged(void* ptr);
void QBoxPlotSeries_DisconnectBoxOutlineVisibilityChanged(void* ptr);
void QBoxPlotSeries_BoxOutlineVisibilityChanged(void* ptr);
struct QtCharts_PackedList QBoxPlotSeries_BoxSets(void* ptr);
void QBoxPlotSeries_ConnectBoxWidthChanged(void* ptr);
void QBoxPlotSeries_DisconnectBoxWidthChanged(void* ptr);
void QBoxPlotSeries_BoxWidthChanged(void* ptr);
void QBoxPlotSeries_ConnectBoxsetsAdded(void* ptr);
void QBoxPlotSeries_DisconnectBoxsetsAdded(void* ptr);
void QBoxPlotSeries_BoxsetsAdded(void* ptr, void* sets);
void QBoxPlotSeries_ConnectBoxsetsRemoved(void* ptr);
void QBoxPlotSeries_DisconnectBoxsetsRemoved(void* ptr);
void QBoxPlotSeries_BoxsetsRemoved(void* ptr, void* sets);
void QBoxPlotSeries_ConnectBrushChanged(void* ptr);
void QBoxPlotSeries_DisconnectBrushChanged(void* ptr);
void QBoxPlotSeries_BrushChanged(void* ptr);
void QBoxPlotSeries_Clear(void* ptr);
void QBoxPlotSeries_ConnectClicked(void* ptr);
void QBoxPlotSeries_DisconnectClicked(void* ptr);
void QBoxPlotSeries_Clicked(void* ptr, void* boxset);
int QBoxPlotSeries_Count(void* ptr);
void QBoxPlotSeries_ConnectCountChanged(void* ptr);
void QBoxPlotSeries_DisconnectCountChanged(void* ptr);
void QBoxPlotSeries_CountChanged(void* ptr);
void QBoxPlotSeries_ConnectDoubleClicked(void* ptr);
void QBoxPlotSeries_DisconnectDoubleClicked(void* ptr);
void QBoxPlotSeries_DoubleClicked(void* ptr, void* boxset);
void QBoxPlotSeries_ConnectHovered(void* ptr);
void QBoxPlotSeries_DisconnectHovered(void* ptr);
void QBoxPlotSeries_Hovered(void* ptr, char status, void* boxset);
char QBoxPlotSeries_Insert(void* ptr, int index, void* set);
void QBoxPlotSeries_ConnectPenChanged(void* ptr);
void QBoxPlotSeries_DisconnectPenChanged(void* ptr);
void QBoxPlotSeries_PenChanged(void* ptr);
void QBoxPlotSeries_ConnectPressed(void* ptr);
void QBoxPlotSeries_DisconnectPressed(void* ptr);
void QBoxPlotSeries_Pressed(void* ptr, void* boxset);
void QBoxPlotSeries_ConnectReleased(void* ptr);
void QBoxPlotSeries_DisconnectReleased(void* ptr);
void QBoxPlotSeries_Released(void* ptr, void* boxset);
char QBoxPlotSeries_Remove(void* ptr, void* set);
char QBoxPlotSeries_Take(void* ptr, void* set);
void QBoxPlotSeries_DestroyQBoxPlotSeries(void* ptr);
void* QBoxPlotSeries___append_sets_atList2(void* ptr, int i);
void QBoxPlotSeries___append_sets_setList2(void* ptr, void* i);
void* QBoxPlotSeries___append_sets_newList2(void* ptr);
void* QBoxPlotSeries___boxSets_atList(void* ptr, int i);
void QBoxPlotSeries___boxSets_setList(void* ptr, void* i);
void* QBoxPlotSeries___boxSets_newList(void* ptr);
void* QBoxPlotSeries___boxsetsAdded_sets_atList(void* ptr, int i);
void QBoxPlotSeries___boxsetsAdded_sets_setList(void* ptr, void* i);
void* QBoxPlotSeries___boxsetsAdded_sets_newList(void* ptr);
void* QBoxPlotSeries___boxsetsRemoved_sets_atList(void* ptr, int i);
void QBoxPlotSeries___boxsetsRemoved_sets_setList(void* ptr, void* i);
void* QBoxPlotSeries___boxsetsRemoved_sets_newList(void* ptr);
void* QBoxSet_NewQBoxSet(char* label, void* parent);
void* QBoxSet_NewQBoxSet2(double le, double lq, double m, double uq, double ue, char* label, void* parent);
void QBoxSet_Append2(void* ptr, void* values);
void QBoxSet_Append(void* ptr, double value);
double QBoxSet_At(void* ptr, int index);
void* QBoxSet_Brush(void* ptr);
void QBoxSet_ConnectBrushChanged(void* ptr);
void QBoxSet_DisconnectBrushChanged(void* ptr);
void QBoxSet_BrushChanged(void* ptr);
void QBoxSet_Clear(void* ptr);
void QBoxSet_ConnectCleared(void* ptr);
void QBoxSet_DisconnectCleared(void* ptr);
void QBoxSet_Cleared(void* ptr);
void QBoxSet_ConnectClicked(void* ptr);
void QBoxSet_DisconnectClicked(void* ptr);
void QBoxSet_Clicked(void* ptr);
int QBoxSet_Count(void* ptr);
void QBoxSet_ConnectDoubleClicked(void* ptr);
void QBoxSet_DisconnectDoubleClicked(void* ptr);
void QBoxSet_DoubleClicked(void* ptr);
void QBoxSet_ConnectHovered(void* ptr);
void QBoxSet_DisconnectHovered(void* ptr);
void QBoxSet_Hovered(void* ptr, char status);
struct QtCharts_PackedString QBoxSet_Label(void* ptr);
void* QBoxSet_Pen(void* ptr);
void QBoxSet_ConnectPenChanged(void* ptr);
void QBoxSet_DisconnectPenChanged(void* ptr);
void QBoxSet_PenChanged(void* ptr);
void QBoxSet_ConnectPressed(void* ptr);
void QBoxSet_DisconnectPressed(void* ptr);
void QBoxSet_Pressed(void* ptr);
void QBoxSet_ConnectReleased(void* ptr);
void QBoxSet_DisconnectReleased(void* ptr);
void QBoxSet_Released(void* ptr);
void QBoxSet_SetBrush(void* ptr, void* brush);
void QBoxSet_SetLabel(void* ptr, char* label);
void QBoxSet_SetPen(void* ptr, void* pen);
void QBoxSet_SetValue(void* ptr, int index, double value);
void QBoxSet_ConnectValueChanged(void* ptr);
void QBoxSet_DisconnectValueChanged(void* ptr);
void QBoxSet_ValueChanged(void* ptr, int index);
void QBoxSet_ConnectValuesChanged(void* ptr);
void QBoxSet_DisconnectValuesChanged(void* ptr);
void QBoxSet_ValuesChanged(void* ptr);
void QBoxSet_DestroyQBoxSet(void* ptr);
void QBoxSet_DestroyQBoxSetDefault(void* ptr);
double QBoxSet___append_values_atList2(void* ptr, int i);
void QBoxSet___append_values_setList2(void* ptr, double i);
void* QBoxSet___append_values_newList2(void* ptr);
long long QCategoryAxis_LabelsPosition(void* ptr);
void QCategoryAxis_SetLabelsPosition(void* ptr, long long position);
void* QCategoryAxis_NewQCategoryAxis(void* parent);
void QCategoryAxis_Append(void* ptr, char* categoryLabel, double categoryEndValue);
void QCategoryAxis_ConnectCategoriesChanged(void* ptr);
void QCategoryAxis_DisconnectCategoriesChanged(void* ptr);
void QCategoryAxis_CategoriesChanged(void* ptr);
struct QtCharts_PackedString QCategoryAxis_CategoriesLabels(void* ptr);
int QCategoryAxis_Count(void* ptr);
double QCategoryAxis_EndValue(void* ptr, char* categoryLabel);
void QCategoryAxis_ConnectLabelsPositionChanged(void* ptr);
void QCategoryAxis_DisconnectLabelsPositionChanged(void* ptr);
void QCategoryAxis_LabelsPositionChanged(void* ptr, long long position);
void QCategoryAxis_Remove(void* ptr, char* categoryLabel);
void QCategoryAxis_ReplaceLabel(void* ptr, char* oldLabel, char* newLabel);
void QCategoryAxis_SetStartValue(void* ptr, double min);
double QCategoryAxis_StartValue(void* ptr, char* categoryLabel);
void QCategoryAxis_DestroyQCategoryAxis(void* ptr);
int QChart_AnimationDuration(void* ptr);
void* QChart_AnimationEasingCurve(void* ptr);
long long QChart_AnimationOptions(void* ptr);
double QChart_BackgroundRoundness(void* ptr);
long long QChart_ChartType(void* ptr);
char QChart_IsBackgroundVisible(void* ptr);
char QChart_IsDropShadowEnabled(void* ptr);
char QChart_IsPlotAreaBackgroundVisible(void* ptr);
void* QChart_Locale(void* ptr);
char QChart_LocalizeNumbers(void* ptr);
void* QChart_Margins(void* ptr);
void* QChart_PlotArea(void* ptr);
void QChart_SetAnimationDuration(void* ptr, int msecs);
void QChart_SetAnimationEasingCurve(void* ptr, void* curve);
void QChart_SetAnimationOptions(void* ptr, long long options);
void QChart_SetBackgroundRoundness(void* ptr, double diameter);
void QChart_SetBackgroundVisible(void* ptr, char visible);
void QChart_SetDropShadowEnabled(void* ptr, char enabled);
void QChart_SetLocale(void* ptr, void* locale);
void QChart_SetLocalizeNumbers(void* ptr, char localize);
void QChart_SetMargins(void* ptr, void* margins);
void QChart_SetPlotAreaBackgroundVisible(void* ptr, char visible);
void QChart_SetTheme(void* ptr, long long theme);
void QChart_SetTitle(void* ptr, char* title);
long long QChart_Theme(void* ptr);
struct QtCharts_PackedString QChart_Title(void* ptr);
void* QChart_NewQChart(void* parent, long long wFlags);
void QChart_AddAxis(void* ptr, void* axis, long long alignment);
void QChart_AddSeries(void* ptr, void* series);
struct QtCharts_PackedList QChart_Axes(void* ptr, long long orientation, void* series);
void* QChart_AxisX(void* ptr, void* series);
void* QChart_AxisY(void* ptr, void* series);
void* QChart_BackgroundBrush(void* ptr);
void* QChart_BackgroundPen(void* ptr);
void QChart_CreateDefaultAxes(void* ptr);
char QChart_IsZoomed(void* ptr);
void* QChart_Legend(void* ptr);
void* QChart_MapToPosition(void* ptr, void* value, void* series);
void* QChart_MapToValue(void* ptr, void* position, void* series);
void* QChart_PlotAreaBackgroundBrush(void* ptr);
void* QChart_PlotAreaBackgroundPen(void* ptr);
void QChart_ConnectPlotAreaChanged(void* ptr);
void QChart_DisconnectPlotAreaChanged(void* ptr);
void QChart_PlotAreaChanged(void* ptr, void* plotArea);
void QChart_RemoveAllSeries(void* ptr);
void QChart_RemoveAxis(void* ptr, void* axis);
void QChart_RemoveSeries(void* ptr, void* series);
void QChart_Scroll(void* ptr, double dx, double dy);
struct QtCharts_PackedList QChart_Series(void* ptr);
void QChart_SetAxisX(void* ptr, void* axis, void* series);
void QChart_SetAxisY(void* ptr, void* axis, void* series);
void QChart_SetBackgroundBrush(void* ptr, void* brush);
void QChart_SetBackgroundPen(void* ptr, void* pen);
void QChart_SetPlotAreaBackgroundBrush(void* ptr, void* brush);
void QChart_SetPlotAreaBackgroundPen(void* ptr, void* pen);
void QChart_SetTitleBrush(void* ptr, void* brush);
void QChart_SetTitleFont(void* ptr, void* font);
void* QChart_TitleBrush(void* ptr);
void* QChart_TitleFont(void* ptr);
void QChart_Zoom(void* ptr, double factor);
void QChart_ZoomIn(void* ptr);
void QChart_ZoomIn2(void* ptr, void* rect);
void QChart_ZoomOut(void* ptr);
void QChart_ZoomReset(void* ptr);
void QChart_DestroyQChart(void* ptr);
void* QChart___axes_atList(void* ptr, int i);
void QChart___axes_setList(void* ptr, void* i);
void* QChart___axes_newList(void* ptr);
void* QChart___series_atList(void* ptr, int i);
void QChart___series_setList(void* ptr, void* i);
void* QChart___series_newList(void* ptr);
void* QChartView_NewQChartView2(void* chart, void* parent);
void* QChartView_NewQChartView(void* parent);
void* QChartView_Chart(void* ptr);
void QChartView_MouseMoveEvent(void* ptr, void* event);
void QChartView_MousePressEvent(void* ptr, void* event);
void QChartView_MouseReleaseEvent(void* ptr, void* event);
void QChartView_ResizeEvent(void* ptr, void* event);
long long QChartView_RubberBand(void* ptr);
void QChartView_SetChart(void* ptr, void* chart);
void QChartView_SetRubberBand(void* ptr, long long rubberBand);
void QChartView_DestroyQChartView(void* ptr);
struct QtCharts_PackedString QDateTimeAxis_Format(void* ptr);
void* QDateTimeAxis_Max(void* ptr);
void* QDateTimeAxis_Min(void* ptr);
void QDateTimeAxis_SetFormat(void* ptr, char* format);
void QDateTimeAxis_SetMax(void* ptr, void* max);
void QDateTimeAxis_SetMin(void* ptr, void* min);
int QDateTimeAxis_TickCount(void* ptr);
void* QDateTimeAxis_NewQDateTimeAxis(void* parent);
void QDateTimeAxis_ConnectFormatChanged(void* ptr);
void QDateTimeAxis_DisconnectFormatChanged(void* ptr);
void QDateTimeAxis_FormatChanged(void* ptr, char* format);
void QDateTimeAxis_ConnectMaxChanged(void* ptr);
void QDateTimeAxis_DisconnectMaxChanged(void* ptr);
void QDateTimeAxis_MaxChanged(void* ptr, void* max);
void QDateTimeAxis_ConnectMinChanged(void* ptr);
void QDateTimeAxis_DisconnectMinChanged(void* ptr);
void QDateTimeAxis_MinChanged(void* ptr, void* min);
void QDateTimeAxis_ConnectRangeChanged(void* ptr);
void QDateTimeAxis_DisconnectRangeChanged(void* ptr);
void QDateTimeAxis_RangeChanged(void* ptr, void* min, void* max);
void QDateTimeAxis_SetRange(void* ptr, void* min, void* max);
void QDateTimeAxis_SetTickCount(void* ptr, int count);
void QDateTimeAxis_ConnectTickCountChanged(void* ptr);
void QDateTimeAxis_DisconnectTickCountChanged(void* ptr);
void QDateTimeAxis_TickCountChanged(void* ptr, int tickCount);
void QDateTimeAxis_DestroyQDateTimeAxis(void* ptr);
int QHBarModelMapper_ColumnCount(void* ptr);
int QHBarModelMapper_FirstBarSetRow(void* ptr);
int QHBarModelMapper_FirstColumn(void* ptr);
int QHBarModelMapper_LastBarSetRow(void* ptr);
void* QHBarModelMapper_Model(void* ptr);
void* QHBarModelMapper_Series(void* ptr);
void QHBarModelMapper_SetColumnCount(void* ptr, int columnCount);
void QHBarModelMapper_SetFirstBarSetRow(void* ptr, int firstBarSetRow);
void QHBarModelMapper_SetFirstColumn(void* ptr, int firstColumn);
void QHBarModelMapper_SetLastBarSetRow(void* ptr, int lastBarSetRow);
void QHBarModelMapper_SetModel(void* ptr, void* model);
void QHBarModelMapper_SetSeries(void* ptr, void* series);
void* QHBarModelMapper_NewQHBarModelMapper(void* parent);
void QHBarModelMapper_ConnectColumnCountChanged(void* ptr);
void QHBarModelMapper_DisconnectColumnCountChanged(void* ptr);
void QHBarModelMapper_ColumnCountChanged(void* ptr);
void QHBarModelMapper_ConnectFirstBarSetRowChanged(void* ptr);
void QHBarModelMapper_DisconnectFirstBarSetRowChanged(void* ptr);
void QHBarModelMapper_FirstBarSetRowChanged(void* ptr);
void QHBarModelMapper_ConnectFirstColumnChanged(void* ptr);
void QHBarModelMapper_DisconnectFirstColumnChanged(void* ptr);
void QHBarModelMapper_FirstColumnChanged(void* ptr);
void QHBarModelMapper_ConnectLastBarSetRowChanged(void* ptr);
void QHBarModelMapper_DisconnectLastBarSetRowChanged(void* ptr);
void QHBarModelMapper_LastBarSetRowChanged(void* ptr);
void QHBarModelMapper_ConnectModelReplaced(void* ptr);
void QHBarModelMapper_DisconnectModelReplaced(void* ptr);
void QHBarModelMapper_ModelReplaced(void* ptr);
void QHBarModelMapper_ConnectSeriesReplaced(void* ptr);
void QHBarModelMapper_DisconnectSeriesReplaced(void* ptr);
void QHBarModelMapper_SeriesReplaced(void* ptr);
int QHPieModelMapper_ColumnCount(void* ptr);
int QHPieModelMapper_FirstColumn(void* ptr);
void* QHPieModelMapper_Model(void* ptr);
void* QHPieModelMapper_Series(void* ptr);
void QHPieModelMapper_SetColumnCount(void* ptr, int columnCount);
void QHPieModelMapper_SetFirstColumn(void* ptr, int firstColumn);
void QHPieModelMapper_SetModel(void* ptr, void* model);
void QHPieModelMapper_SetSeries(void* ptr, void* series);
void* QHPieModelMapper_NewQHPieModelMapper(void* parent);
void QHPieModelMapper_ConnectColumnCountChanged(void* ptr);
void QHPieModelMapper_DisconnectColumnCountChanged(void* ptr);
void QHPieModelMapper_ColumnCountChanged(void* ptr);
void QHPieModelMapper_ConnectFirstColumnChanged(void* ptr);
void QHPieModelMapper_DisconnectFirstColumnChanged(void* ptr);
void QHPieModelMapper_FirstColumnChanged(void* ptr);
int QHPieModelMapper_LabelsRow(void* ptr);
void QHPieModelMapper_ConnectLabelsRowChanged(void* ptr);
void QHPieModelMapper_DisconnectLabelsRowChanged(void* ptr);
void QHPieModelMapper_LabelsRowChanged(void* ptr);
void QHPieModelMapper_ConnectModelReplaced(void* ptr);
void QHPieModelMapper_DisconnectModelReplaced(void* ptr);
void QHPieModelMapper_ModelReplaced(void* ptr);
void QHPieModelMapper_ConnectSeriesReplaced(void* ptr);
void QHPieModelMapper_DisconnectSeriesReplaced(void* ptr);
void QHPieModelMapper_SeriesReplaced(void* ptr);
void QHPieModelMapper_SetLabelsRow(void* ptr, int labelsRow);
void QHPieModelMapper_SetValuesRow(void* ptr, int valuesRow);
int QHPieModelMapper_ValuesRow(void* ptr);
void QHPieModelMapper_ConnectValuesRowChanged(void* ptr);
void QHPieModelMapper_DisconnectValuesRowChanged(void* ptr);
void QHPieModelMapper_ValuesRowChanged(void* ptr);
int QHXYModelMapper_ColumnCount(void* ptr);
int QHXYModelMapper_FirstColumn(void* ptr);
void* QHXYModelMapper_Model(void* ptr);
void* QHXYModelMapper_Series(void* ptr);
void QHXYModelMapper_SetColumnCount(void* ptr, int columnCount);
void QHXYModelMapper_SetFirstColumn(void* ptr, int firstColumn);
void QHXYModelMapper_SetModel(void* ptr, void* model);
void QHXYModelMapper_SetSeries(void* ptr, void* series);
void QHXYModelMapper_SetXRow(void* ptr, int xRow);
void QHXYModelMapper_SetYRow(void* ptr, int yRow);
int QHXYModelMapper_XRow(void* ptr);
int QHXYModelMapper_YRow(void* ptr);
void* QHXYModelMapper_NewQHXYModelMapper(void* parent);
void QHXYModelMapper_ConnectColumnCountChanged(void* ptr);
void QHXYModelMapper_DisconnectColumnCountChanged(void* ptr);
void QHXYModelMapper_ColumnCountChanged(void* ptr);
void QHXYModelMapper_ConnectFirstColumnChanged(void* ptr);
void QHXYModelMapper_DisconnectFirstColumnChanged(void* ptr);
void QHXYModelMapper_FirstColumnChanged(void* ptr);
void QHXYModelMapper_ConnectModelReplaced(void* ptr);
void QHXYModelMapper_DisconnectModelReplaced(void* ptr);
void QHXYModelMapper_ModelReplaced(void* ptr);
void QHXYModelMapper_ConnectSeriesReplaced(void* ptr);
void QHXYModelMapper_DisconnectSeriesReplaced(void* ptr);
void QHXYModelMapper_SeriesReplaced(void* ptr);
void QHXYModelMapper_ConnectXRowChanged(void* ptr);
void QHXYModelMapper_DisconnectXRowChanged(void* ptr);
void QHXYModelMapper_XRowChanged(void* ptr);
void QHXYModelMapper_ConnectYRowChanged(void* ptr);
void QHXYModelMapper_DisconnectYRowChanged(void* ptr);
void QHXYModelMapper_YRowChanged(void* ptr);
void* QHorizontalBarSeries_NewQHorizontalBarSeries(void* parent);
long long QHorizontalBarSeries_Type(void* ptr);
long long QHorizontalBarSeries_TypeDefault(void* ptr);
void QHorizontalBarSeries_DestroyQHorizontalBarSeries(void* ptr);
void* QHorizontalPercentBarSeries_NewQHorizontalPercentBarSeries(void* parent);
long long QHorizontalPercentBarSeries_Type(void* ptr);
long long QHorizontalPercentBarSeries_TypeDefault(void* ptr);
void QHorizontalPercentBarSeries_DestroyQHorizontalPercentBarSeries(void* ptr);
void* QHorizontalStackedBarSeries_NewQHorizontalStackedBarSeries(void* parent);
long long QHorizontalStackedBarSeries_Type(void* ptr);
long long QHorizontalStackedBarSeries_TypeDefault(void* ptr);
void QHorizontalStackedBarSeries_DestroyQHorizontalStackedBarSeries(void* ptr);
long long QLegend_Alignment(void* ptr);
void* QLegend_BorderColor(void* ptr);
void* QLegend_Color(void* ptr);
void* QLegend_Font(void* ptr);
void* QLegend_LabelColor(void* ptr);
char QLegend_ReverseMarkers(void* ptr);
void QLegend_SetAlignment(void* ptr, long long alignment);
void QLegend_SetBorderColor(void* ptr, void* color);
void QLegend_SetColor(void* ptr, void* color);
void QLegend_SetFont(void* ptr, void* font);
void QLegend_SetLabelColor(void* ptr, void* color);
void QLegend_SetReverseMarkers(void* ptr, char reverseMarkers);
void QLegend_AttachToChart(void* ptr);
void QLegend_ConnectBackgroundVisibleChanged(void* ptr);
void QLegend_DisconnectBackgroundVisibleChanged(void* ptr);
void QLegend_BackgroundVisibleChanged(void* ptr, char visible);
void QLegend_ConnectBorderColorChanged(void* ptr);
void QLegend_DisconnectBorderColorChanged(void* ptr);
void QLegend_BorderColorChanged(void* ptr, void* color);
void* QLegend_Brush(void* ptr);
void QLegend_ConnectColorChanged(void* ptr);
void QLegend_DisconnectColorChanged(void* ptr);
void QLegend_ColorChanged(void* ptr, void* color);
void QLegend_DetachFromChart(void* ptr);
void QLegend_ConnectFontChanged(void* ptr);
void QLegend_DisconnectFontChanged(void* ptr);
void QLegend_FontChanged(void* ptr, void* font);
char QLegend_IsBackgroundVisible(void* ptr);
struct QtCharts_PackedList QLegend_Markers(void* ptr, void* series);
char QLegend_IsAttachedToChart(void* ptr);
void* QLegend_LabelBrush(void* ptr);
void QLegend_ConnectLabelColorChanged(void* ptr);
void QLegend_DisconnectLabelColorChanged(void* ptr);
void QLegend_LabelColorChanged(void* ptr, void* color);
void* QLegend_Pen(void* ptr);
void QLegend_ConnectReverseMarkersChanged(void* ptr);
void QLegend_DisconnectReverseMarkersChanged(void* ptr);
void QLegend_ReverseMarkersChanged(void* ptr, char reverseMarkers);
void QLegend_SetBackgroundVisible(void* ptr, char visible);
void QLegend_SetBrush(void* ptr, void* brush);
void QLegend_SetLabelBrush(void* ptr, void* brush);
void QLegend_SetPen(void* ptr, void* pen);
void QLegend_SetShowToolTips(void* ptr, char show);
char QLegend_ShowToolTips(void* ptr);
void QLegend_ConnectShowToolTipsChanged(void* ptr);
void QLegend_DisconnectShowToolTipsChanged(void* ptr);
void QLegend_ShowToolTipsChanged(void* ptr, char showToolTips);
void QLegend_DestroyQLegend(void* ptr);
void* QLegend___markers_atList(void* ptr, int i);
void QLegend___markers_setList(void* ptr, void* i);
void* QLegend___markers_newList(void* ptr);
void* QLegendMarker_Brush(void* ptr);
void QLegendMarker_ConnectBrushChanged(void* ptr);
void QLegendMarker_DisconnectBrushChanged(void* ptr);
void QLegendMarker_BrushChanged(void* ptr);
void QLegendMarker_ConnectClicked(void* ptr);
void QLegendMarker_DisconnectClicked(void* ptr);
void QLegendMarker_Clicked(void* ptr);
void* QLegendMarker_Font(void* ptr);
void QLegendMarker_ConnectFontChanged(void* ptr);
void QLegendMarker_DisconnectFontChanged(void* ptr);
void QLegendMarker_FontChanged(void* ptr);
void QLegendMarker_ConnectHovered(void* ptr);
void QLegendMarker_DisconnectHovered(void* ptr);
void QLegendMarker_Hovered(void* ptr, char status);
char QLegendMarker_IsVisible(void* ptr);
struct QtCharts_PackedString QLegendMarker_Label(void* ptr);
void* QLegendMarker_LabelBrush(void* ptr);
void QLegendMarker_ConnectLabelBrushChanged(void* ptr);
void QLegendMarker_DisconnectLabelBrushChanged(void* ptr);
void QLegendMarker_LabelBrushChanged(void* ptr);
void QLegendMarker_ConnectLabelChanged(void* ptr);
void QLegendMarker_DisconnectLabelChanged(void* ptr);
void QLegendMarker_LabelChanged(void* ptr);
void* QLegendMarker_Pen(void* ptr);
void QLegendMarker_ConnectPenChanged(void* ptr);
void QLegendMarker_DisconnectPenChanged(void* ptr);
void QLegendMarker_PenChanged(void* ptr);
void* QLegendMarker_Series(void* ptr);
void QLegendMarker_SetBrush(void* ptr, void* brush);
void QLegendMarker_SetFont(void* ptr, void* font);
void QLegendMarker_SetLabel(void* ptr, char* label);
void QLegendMarker_SetLabelBrush(void* ptr, void* brush);
void QLegendMarker_SetPen(void* ptr, void* pen);
void QLegendMarker_SetVisible(void* ptr, char visible);
long long QLegendMarker_Type(void* ptr);
void QLegendMarker_ConnectVisibleChanged(void* ptr);
void QLegendMarker_DisconnectVisibleChanged(void* ptr);
void QLegendMarker_VisibleChanged(void* ptr);
void QLegendMarker_DestroyQLegendMarker(void* ptr);
void QLegendMarker_DestroyQLegendMarkerDefault(void* ptr);
long long QLineSeries_Type(void* ptr);
long long QLineSeries_TypeDefault(void* ptr);
void* QLineSeries_NewQLineSeries(void* parent);
void QLineSeries_DestroyQLineSeries(void* ptr);
double QLogValueAxis_Base(void* ptr);
struct QtCharts_PackedString QLogValueAxis_LabelFormat(void* ptr);
double QLogValueAxis_Max(void* ptr);
double QLogValueAxis_Min(void* ptr);
void QLogValueAxis_SetBase(void* ptr, double base);
void QLogValueAxis_SetLabelFormat(void* ptr, char* format);
void QLogValueAxis_SetMax(void* ptr, double max);
void QLogValueAxis_SetMin(void* ptr, double min);
void* QLogValueAxis_NewQLogValueAxis(void* parent);
void QLogValueAxis_ConnectBaseChanged(void* ptr);
void QLogValueAxis_DisconnectBaseChanged(void* ptr);
void QLogValueAxis_BaseChanged(void* ptr, double base);
void QLogValueAxis_ConnectLabelFormatChanged(void* ptr);
void QLogValueAxis_DisconnectLabelFormatChanged(void* ptr);
void QLogValueAxis_LabelFormatChanged(void* ptr, char* format);
void QLogValueAxis_ConnectMaxChanged(void* ptr);
void QLogValueAxis_DisconnectMaxChanged(void* ptr);
void QLogValueAxis_MaxChanged(void* ptr, double max);
void QLogValueAxis_ConnectMinChanged(void* ptr);
void QLogValueAxis_DisconnectMinChanged(void* ptr);
void QLogValueAxis_MinChanged(void* ptr, double min);
void QLogValueAxis_ConnectRangeChanged(void* ptr);
void QLogValueAxis_DisconnectRangeChanged(void* ptr);
void QLogValueAxis_RangeChanged(void* ptr, double min, double max);
void QLogValueAxis_SetRange(void* ptr, double min, double max);
void QLogValueAxis_DestroyQLogValueAxis(void* ptr);
void* QPercentBarSeries_NewQPercentBarSeries(void* parent);
long long QPercentBarSeries_Type(void* ptr);
long long QPercentBarSeries_TypeDefault(void* ptr);
void QPercentBarSeries_DestroyQPercentBarSeries(void* ptr);
void* QPieLegendMarker_Series(void* ptr);
void* QPieLegendMarker_SeriesDefault(void* ptr);
void* QPieLegendMarker_Slice(void* ptr);
void QPieLegendMarker_DestroyQPieLegendMarker(void* ptr);
void QPieLegendMarker_DestroyQPieLegendMarkerDefault(void* ptr);
double QPieSeries_HoleSize(void* ptr);
double QPieSeries_HorizontalPosition(void* ptr);
double QPieSeries_PieSize(void* ptr);
double QPieSeries_PieStartAngle(void* ptr);
void QPieSeries_SetHoleSize(void* ptr, double holeSize);
void QPieSeries_SetHorizontalPosition(void* ptr, double relativePosition);
void QPieSeries_SetPieSize(void* ptr, double relativeSize);
void QPieSeries_SetPieStartAngle(void* ptr, double startAngle);
void QPieSeries_SetVerticalPosition(void* ptr, double relativePosition);
double QPieSeries_VerticalPosition(void* ptr);
void* QPieSeries_NewQPieSeries(void* parent);
void QPieSeries_ConnectAdded(void* ptr);
void QPieSeries_DisconnectAdded(void* ptr);
void QPieSeries_Added(void* ptr, void* slices);
void* QPieSeries_Append3(void* ptr, char* label, double value);
char QPieSeries_Append2(void* ptr, void* slices);
char QPieSeries_Append(void* ptr, void* slice);
void QPieSeries_Clear(void* ptr);
void QPieSeries_ConnectClicked(void* ptr);
void QPieSeries_DisconnectClicked(void* ptr);
void QPieSeries_Clicked(void* ptr, void* slice);
int QPieSeries_Count(void* ptr);
void QPieSeries_ConnectCountChanged(void* ptr);
void QPieSeries_DisconnectCountChanged(void* ptr);
void QPieSeries_CountChanged(void* ptr);
void QPieSeries_ConnectDoubleClicked(void* ptr);
void QPieSeries_DisconnectDoubleClicked(void* ptr);
void QPieSeries_DoubleClicked(void* ptr, void* slice);
void QPieSeries_ConnectHovered(void* ptr);
void QPieSeries_DisconnectHovered(void* ptr);
void QPieSeries_Hovered(void* ptr, void* slice, char state);
char QPieSeries_Insert(void* ptr, int index, void* slice);
char QPieSeries_IsEmpty(void* ptr);
double QPieSeries_PieEndAngle(void* ptr);
void QPieSeries_ConnectPressed(void* ptr);
void QPieSeries_DisconnectPressed(void* ptr);
void QPieSeries_Pressed(void* ptr, void* slice);
void QPieSeries_ConnectReleased(void* ptr);
void QPieSeries_DisconnectReleased(void* ptr);
void QPieSeries_Released(void* ptr, void* slice);
char QPieSeries_Remove(void* ptr, void* slice);
void QPieSeries_ConnectRemoved(void* ptr);
void QPieSeries_DisconnectRemoved(void* ptr);
void QPieSeries_Removed(void* ptr, void* slices);
void QPieSeries_SetLabelsPosition(void* ptr, long long position);
void QPieSeries_SetLabelsVisible(void* ptr, char visible);
void QPieSeries_SetPieEndAngle(void* ptr, double angle);
struct QtCharts_PackedList QPieSeries_Slices(void* ptr);
double QPieSeries_Sum(void* ptr);
void QPieSeries_ConnectSumChanged(void* ptr);
void QPieSeries_DisconnectSumChanged(void* ptr);
void QPieSeries_SumChanged(void* ptr);
char QPieSeries_Take(void* ptr, void* slice);
long long QPieSeries_Type(void* ptr);
long long QPieSeries_TypeDefault(void* ptr);
void QPieSeries_DestroyQPieSeries(void* ptr);
void QPieSeries_DestroyQPieSeriesDefault(void* ptr);
void* QPieSeries___added_slices_atList(void* ptr, int i);
void QPieSeries___added_slices_setList(void* ptr, void* i);
void* QPieSeries___added_slices_newList(void* ptr);
void* QPieSeries___append_slices_atList2(void* ptr, int i);
void QPieSeries___append_slices_setList2(void* ptr, void* i);
void* QPieSeries___append_slices_newList2(void* ptr);
void* QPieSeries___removed_slices_atList(void* ptr, int i);
void QPieSeries___removed_slices_setList(void* ptr, void* i);
void* QPieSeries___removed_slices_newList(void* ptr);
void* QPieSeries___slices_atList(void* ptr, int i);
void QPieSeries___slices_setList(void* ptr, void* i);
void* QPieSeries___slices_newList(void* ptr);
double QPieSlice_AngleSpan(void* ptr);
void* QPieSlice_BorderColor(void* ptr);
int QPieSlice_BorderWidth(void* ptr);
void* QPieSlice_Brush(void* ptr);
void* QPieSlice_Color(void* ptr);
double QPieSlice_ExplodeDistanceFactor(void* ptr);
char QPieSlice_IsExploded(void* ptr);
char QPieSlice_IsLabelVisible(void* ptr);
struct QtCharts_PackedString QPieSlice_Label(void* ptr);
double QPieSlice_LabelArmLengthFactor(void* ptr);
void* QPieSlice_LabelBrush(void* ptr);
void* QPieSlice_LabelColor(void* ptr);
void* QPieSlice_LabelFont(void* ptr);
long long QPieSlice_LabelPosition(void* ptr);
void* QPieSlice_Pen(void* ptr);
double QPieSlice_Percentage(void* ptr);
void QPieSlice_SetBorderColor(void* ptr, void* color);
void QPieSlice_SetBorderWidth(void* ptr, int width);
void QPieSlice_SetBrush(void* ptr, void* brush);
void QPieSlice_SetColor(void* ptr, void* color);
void QPieSlice_SetExplodeDistanceFactor(void* ptr, double factor);
void QPieSlice_SetExploded(void* ptr, char exploded);
void QPieSlice_SetLabel(void* ptr, char* label);
void QPieSlice_SetLabelArmLengthFactor(void* ptr, double factor);
void QPieSlice_SetLabelBrush(void* ptr, void* brush);
void QPieSlice_SetLabelColor(void* ptr, void* color);
void QPieSlice_SetLabelFont(void* ptr, void* font);
void QPieSlice_SetLabelPosition(void* ptr, long long position);
void QPieSlice_SetLabelVisible(void* ptr, char visible);
void QPieSlice_SetPen(void* ptr, void* pen);
void QPieSlice_SetValue(void* ptr, double value);
double QPieSlice_StartAngle(void* ptr);
double QPieSlice_Value(void* ptr);
void* QPieSlice_NewQPieSlice(void* parent);
void* QPieSlice_NewQPieSlice2(char* label, double value, void* parent);
void QPieSlice_ConnectAngleSpanChanged(void* ptr);
void QPieSlice_DisconnectAngleSpanChanged(void* ptr);
void QPieSlice_AngleSpanChanged(void* ptr);
void QPieSlice_ConnectBorderColorChanged(void* ptr);
void QPieSlice_DisconnectBorderColorChanged(void* ptr);
void QPieSlice_BorderColorChanged(void* ptr);
void QPieSlice_ConnectBorderWidthChanged(void* ptr);
void QPieSlice_DisconnectBorderWidthChanged(void* ptr);
void QPieSlice_BorderWidthChanged(void* ptr);
void QPieSlice_ConnectBrushChanged(void* ptr);
void QPieSlice_DisconnectBrushChanged(void* ptr);
void QPieSlice_BrushChanged(void* ptr);
void QPieSlice_ConnectClicked(void* ptr);
void QPieSlice_DisconnectClicked(void* ptr);
void QPieSlice_Clicked(void* ptr);
void QPieSlice_ConnectColorChanged(void* ptr);
void QPieSlice_DisconnectColorChanged(void* ptr);
void QPieSlice_ColorChanged(void* ptr);
void QPieSlice_ConnectDoubleClicked(void* ptr);
void QPieSlice_DisconnectDoubleClicked(void* ptr);
void QPieSlice_DoubleClicked(void* ptr);
void QPieSlice_ConnectHovered(void* ptr);
void QPieSlice_DisconnectHovered(void* ptr);
void QPieSlice_Hovered(void* ptr, char state);
void QPieSlice_ConnectLabelBrushChanged(void* ptr);
void QPieSlice_DisconnectLabelBrushChanged(void* ptr);
void QPieSlice_LabelBrushChanged(void* ptr);
void QPieSlice_ConnectLabelChanged(void* ptr);
void QPieSlice_DisconnectLabelChanged(void* ptr);
void QPieSlice_LabelChanged(void* ptr);
void QPieSlice_ConnectLabelColorChanged(void* ptr);
void QPieSlice_DisconnectLabelColorChanged(void* ptr);
void QPieSlice_LabelColorChanged(void* ptr);
void QPieSlice_ConnectLabelFontChanged(void* ptr);
void QPieSlice_DisconnectLabelFontChanged(void* ptr);
void QPieSlice_LabelFontChanged(void* ptr);
void QPieSlice_ConnectLabelVisibleChanged(void* ptr);
void QPieSlice_DisconnectLabelVisibleChanged(void* ptr);
void QPieSlice_LabelVisibleChanged(void* ptr);
void QPieSlice_ConnectPenChanged(void* ptr);
void QPieSlice_DisconnectPenChanged(void* ptr);
void QPieSlice_PenChanged(void* ptr);
void QPieSlice_ConnectPercentageChanged(void* ptr);
void QPieSlice_DisconnectPercentageChanged(void* ptr);
void QPieSlice_PercentageChanged(void* ptr);
void QPieSlice_ConnectPressed(void* ptr);
void QPieSlice_DisconnectPressed(void* ptr);
void QPieSlice_Pressed(void* ptr);
void QPieSlice_ConnectReleased(void* ptr);
void QPieSlice_DisconnectReleased(void* ptr);
void QPieSlice_Released(void* ptr);
void* QPieSlice_Series(void* ptr);
void QPieSlice_ConnectStartAngleChanged(void* ptr);
void QPieSlice_DisconnectStartAngleChanged(void* ptr);
void QPieSlice_StartAngleChanged(void* ptr);
void QPieSlice_ConnectValueChanged(void* ptr);
void QPieSlice_DisconnectValueChanged(void* ptr);
void QPieSlice_ValueChanged(void* ptr);
void QPieSlice_DestroyQPieSlice(void* ptr);
void QPieSlice_DestroyQPieSliceDefault(void* ptr);
void* QPolarChart_NewQPolarChart(void* parent, long long wFlags);
void QPolarChart_AddAxis(void* ptr, void* axis, long long polarOrientation);
struct QtCharts_PackedList QPolarChart_Axes(void* ptr, long long polarOrientation, void* series);
long long QPolarChart_QPolarChart_AxisPolarOrientation(void* axis);
void QPolarChart_DestroyQPolarChart(void* ptr);
void* QPolarChart___axes_atList(void* ptr, int i);
void QPolarChart___axes_setList(void* ptr, void* i);
void* QPolarChart___axes_newList(void* ptr);
void* QScatterSeries_BorderColor(void* ptr);
void* QScatterSeries_Brush(void* ptr);
void* QScatterSeries_Color(void* ptr);
void* QScatterSeries_ColorDefault(void* ptr);
long long QScatterSeries_MarkerShape(void* ptr);
double QScatterSeries_MarkerSize(void* ptr);
void QScatterSeries_SetBorderColor(void* ptr, void* color);
void QScatterSeries_SetColor(void* ptr, void* color);
void QScatterSeries_SetColorDefault(void* ptr, void* color);
void QScatterSeries_SetMarkerShape(void* ptr, long long shape);
void QScatterSeries_SetMarkerSize(void* ptr, double size);
long long QScatterSeries_Type(void* ptr);
long long QScatterSeries_TypeDefault(void* ptr);
void* QScatterSeries_NewQScatterSeries(void* parent);
void QScatterSeries_ConnectBorderColorChanged(void* ptr);
void QScatterSeries_DisconnectBorderColorChanged(void* ptr);
void QScatterSeries_BorderColorChanged(void* ptr, void* color);
void QScatterSeries_ConnectColorChanged(void* ptr);
void QScatterSeries_DisconnectColorChanged(void* ptr);
void QScatterSeries_ColorChanged(void* ptr, void* color);
void QScatterSeries_ConnectMarkerShapeChanged(void* ptr);
void QScatterSeries_DisconnectMarkerShapeChanged(void* ptr);
void QScatterSeries_MarkerShapeChanged(void* ptr, long long shape);
void QScatterSeries_ConnectMarkerSizeChanged(void* ptr);
void QScatterSeries_DisconnectMarkerSizeChanged(void* ptr);
void QScatterSeries_MarkerSizeChanged(void* ptr, double size);
void QScatterSeries_SetBrush(void* ptr, void* brush);
void QScatterSeries_SetBrushDefault(void* ptr, void* brush);
void QScatterSeries_SetPen(void* ptr, void* pen);
void QScatterSeries_SetPenDefault(void* ptr, void* pen);
void QScatterSeries_DestroyQScatterSeries(void* ptr);
long long QSplineSeries_Type(void* ptr);
long long QSplineSeries_TypeDefault(void* ptr);
void* QSplineSeries_NewQSplineSeries(void* parent);
void QSplineSeries_DestroyQSplineSeries(void* ptr);
void* QStackedBarSeries_NewQStackedBarSeries(void* parent);
long long QStackedBarSeries_Type(void* ptr);
long long QStackedBarSeries_TypeDefault(void* ptr);
void QStackedBarSeries_DestroyQStackedBarSeries(void* ptr);
int QVBarModelMapper_FirstBarSetColumn(void* ptr);
int QVBarModelMapper_FirstRow(void* ptr);
int QVBarModelMapper_LastBarSetColumn(void* ptr);
void* QVBarModelMapper_Model(void* ptr);
int QVBarModelMapper_RowCount(void* ptr);
void* QVBarModelMapper_Series(void* ptr);
void QVBarModelMapper_SetFirstBarSetColumn(void* ptr, int firstBarSetColumn);
void QVBarModelMapper_SetFirstRow(void* ptr, int firstRow);
void QVBarModelMapper_SetLastBarSetColumn(void* ptr, int lastBarSetColumn);
void QVBarModelMapper_SetModel(void* ptr, void* model);
void QVBarModelMapper_SetRowCount(void* ptr, int rowCount);
void QVBarModelMapper_SetSeries(void* ptr, void* series);
void* QVBarModelMapper_NewQVBarModelMapper(void* parent);
void QVBarModelMapper_ConnectFirstBarSetColumnChanged(void* ptr);
void QVBarModelMapper_DisconnectFirstBarSetColumnChanged(void* ptr);
void QVBarModelMapper_FirstBarSetColumnChanged(void* ptr);
void QVBarModelMapper_ConnectFirstRowChanged(void* ptr);
void QVBarModelMapper_DisconnectFirstRowChanged(void* ptr);
void QVBarModelMapper_FirstRowChanged(void* ptr);
void QVBarModelMapper_ConnectLastBarSetColumnChanged(void* ptr);
void QVBarModelMapper_DisconnectLastBarSetColumnChanged(void* ptr);
void QVBarModelMapper_LastBarSetColumnChanged(void* ptr);
void QVBarModelMapper_ConnectModelReplaced(void* ptr);
void QVBarModelMapper_DisconnectModelReplaced(void* ptr);
void QVBarModelMapper_ModelReplaced(void* ptr);
void QVBarModelMapper_ConnectRowCountChanged(void* ptr);
void QVBarModelMapper_DisconnectRowCountChanged(void* ptr);
void QVBarModelMapper_RowCountChanged(void* ptr);
void QVBarModelMapper_ConnectSeriesReplaced(void* ptr);
void QVBarModelMapper_DisconnectSeriesReplaced(void* ptr);
void QVBarModelMapper_SeriesReplaced(void* ptr);
int QVBoxPlotModelMapper_FirstBoxSetColumn(void* ptr);
int QVBoxPlotModelMapper_FirstRow(void* ptr);
int QVBoxPlotModelMapper_LastBoxSetColumn(void* ptr);
void* QVBoxPlotModelMapper_Model(void* ptr);
int QVBoxPlotModelMapper_RowCount(void* ptr);
void* QVBoxPlotModelMapper_Series(void* ptr);
void QVBoxPlotModelMapper_SetFirstBoxSetColumn(void* ptr, int firstBoxSetColumn);
void QVBoxPlotModelMapper_SetFirstRow(void* ptr, int firstRow);
void QVBoxPlotModelMapper_SetLastBoxSetColumn(void* ptr, int lastBoxSetColumn);
void QVBoxPlotModelMapper_SetModel(void* ptr, void* model);
void QVBoxPlotModelMapper_SetRowCount(void* ptr, int rowCount);
void QVBoxPlotModelMapper_SetSeries(void* ptr, void* series);
void* QVBoxPlotModelMapper_NewQVBoxPlotModelMapper(void* parent);
void QVBoxPlotModelMapper_ConnectFirstBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_DisconnectFirstBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_FirstBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_ConnectFirstRowChanged(void* ptr);
void QVBoxPlotModelMapper_DisconnectFirstRowChanged(void* ptr);
void QVBoxPlotModelMapper_FirstRowChanged(void* ptr);
void QVBoxPlotModelMapper_ConnectLastBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_DisconnectLastBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_LastBoxSetColumnChanged(void* ptr);
void QVBoxPlotModelMapper_ConnectModelReplaced(void* ptr);
void QVBoxPlotModelMapper_DisconnectModelReplaced(void* ptr);
void QVBoxPlotModelMapper_ModelReplaced(void* ptr);
void QVBoxPlotModelMapper_ConnectRowCountChanged(void* ptr);
void QVBoxPlotModelMapper_DisconnectRowCountChanged(void* ptr);
void QVBoxPlotModelMapper_RowCountChanged(void* ptr);
void QVBoxPlotModelMapper_ConnectSeriesReplaced(void* ptr);
void QVBoxPlotModelMapper_DisconnectSeriesReplaced(void* ptr);
void QVBoxPlotModelMapper_SeriesReplaced(void* ptr);
int QVPieModelMapper_FirstRow(void* ptr);
void* QVPieModelMapper_Model(void* ptr);
int QVPieModelMapper_RowCount(void* ptr);
void* QVPieModelMapper_Series(void* ptr);
void QVPieModelMapper_SetFirstRow(void* ptr, int firstRow);
void QVPieModelMapper_SetModel(void* ptr, void* model);
void QVPieModelMapper_SetRowCount(void* ptr, int rowCount);
void QVPieModelMapper_SetSeries(void* ptr, void* series);
void* QVPieModelMapper_NewQVPieModelMapper(void* parent);
void QVPieModelMapper_ConnectFirstRowChanged(void* ptr);
void QVPieModelMapper_DisconnectFirstRowChanged(void* ptr);
void QVPieModelMapper_FirstRowChanged(void* ptr);
int QVPieModelMapper_LabelsColumn(void* ptr);
void QVPieModelMapper_ConnectLabelsColumnChanged(void* ptr);
void QVPieModelMapper_DisconnectLabelsColumnChanged(void* ptr);
void QVPieModelMapper_LabelsColumnChanged(void* ptr);
void QVPieModelMapper_ConnectModelReplaced(void* ptr);
void QVPieModelMapper_DisconnectModelReplaced(void* ptr);
void QVPieModelMapper_ModelReplaced(void* ptr);
void QVPieModelMapper_ConnectRowCountChanged(void* ptr);
void QVPieModelMapper_DisconnectRowCountChanged(void* ptr);
void QVPieModelMapper_RowCountChanged(void* ptr);
void QVPieModelMapper_ConnectSeriesReplaced(void* ptr);
void QVPieModelMapper_DisconnectSeriesReplaced(void* ptr);
void QVPieModelMapper_SeriesReplaced(void* ptr);
void QVPieModelMapper_SetLabelsColumn(void* ptr, int labelsColumn);
void QVPieModelMapper_SetValuesColumn(void* ptr, int valuesColumn);
int QVPieModelMapper_ValuesColumn(void* ptr);
void QVPieModelMapper_ConnectValuesColumnChanged(void* ptr);
void QVPieModelMapper_DisconnectValuesColumnChanged(void* ptr);
void QVPieModelMapper_ValuesColumnChanged(void* ptr);
int QVXYModelMapper_FirstRow(void* ptr);
void* QVXYModelMapper_Model(void* ptr);
int QVXYModelMapper_RowCount(void* ptr);
void* QVXYModelMapper_Series(void* ptr);
void QVXYModelMapper_SetFirstRow(void* ptr, int firstRow);
void QVXYModelMapper_SetModel(void* ptr, void* model);
void QVXYModelMapper_SetRowCount(void* ptr, int rowCount);
void QVXYModelMapper_SetSeries(void* ptr, void* series);
void QVXYModelMapper_SetXColumn(void* ptr, int xColumn);
void QVXYModelMapper_SetYColumn(void* ptr, int yColumn);
int QVXYModelMapper_XColumn(void* ptr);
int QVXYModelMapper_YColumn(void* ptr);
void* QVXYModelMapper_NewQVXYModelMapper(void* parent);
void QVXYModelMapper_ConnectFirstRowChanged(void* ptr);
void QVXYModelMapper_DisconnectFirstRowChanged(void* ptr);
void QVXYModelMapper_FirstRowChanged(void* ptr);
void QVXYModelMapper_ConnectModelReplaced(void* ptr);
void QVXYModelMapper_DisconnectModelReplaced(void* ptr);
void QVXYModelMapper_ModelReplaced(void* ptr);
void QVXYModelMapper_ConnectRowCountChanged(void* ptr);
void QVXYModelMapper_DisconnectRowCountChanged(void* ptr);
void QVXYModelMapper_RowCountChanged(void* ptr);
void QVXYModelMapper_ConnectSeriesReplaced(void* ptr);
void QVXYModelMapper_DisconnectSeriesReplaced(void* ptr);
void QVXYModelMapper_SeriesReplaced(void* ptr);
void QVXYModelMapper_ConnectXColumnChanged(void* ptr);
void QVXYModelMapper_DisconnectXColumnChanged(void* ptr);
void QVXYModelMapper_XColumnChanged(void* ptr);
void QVXYModelMapper_ConnectYColumnChanged(void* ptr);
void QVXYModelMapper_DisconnectYColumnChanged(void* ptr);
void QVXYModelMapper_YColumnChanged(void* ptr);
struct QtCharts_PackedString QValueAxis_LabelFormat(void* ptr);
double QValueAxis_Max(void* ptr);
double QValueAxis_Min(void* ptr);
int QValueAxis_MinorTickCount(void* ptr);
void QValueAxis_SetLabelFormat(void* ptr, char* format);
void QValueAxis_SetMax(void* ptr, double max);
void QValueAxis_SetMin(void* ptr, double min);
void QValueAxis_SetMinorTickCount(void* ptr, int count);
void QValueAxis_SetTickCount(void* ptr, int count);
int QValueAxis_TickCount(void* ptr);
void* QValueAxis_NewQValueAxis(void* parent);
void QValueAxis_ApplyNiceNumbers(void* ptr);
void QValueAxis_ApplyNiceNumbersDefault(void* ptr);
void QValueAxis_ConnectLabelFormatChanged(void* ptr);
void QValueAxis_DisconnectLabelFormatChanged(void* ptr);
void QValueAxis_LabelFormatChanged(void* ptr, char* format);
void QValueAxis_ConnectMaxChanged(void* ptr);
void QValueAxis_DisconnectMaxChanged(void* ptr);
void QValueAxis_MaxChanged(void* ptr, double max);
void QValueAxis_ConnectMinChanged(void* ptr);
void QValueAxis_DisconnectMinChanged(void* ptr);
void QValueAxis_MinChanged(void* ptr, double min);
void QValueAxis_ConnectMinorTickCountChanged(void* ptr);
void QValueAxis_DisconnectMinorTickCountChanged(void* ptr);
void QValueAxis_MinorTickCountChanged(void* ptr, int minorTickCount);
void QValueAxis_ConnectRangeChanged(void* ptr);
void QValueAxis_DisconnectRangeChanged(void* ptr);
void QValueAxis_RangeChanged(void* ptr, double min, double max);
void QValueAxis_SetRange(void* ptr, double min, double max);
void QValueAxis_ConnectTickCountChanged(void* ptr);
void QValueAxis_DisconnectTickCountChanged(void* ptr);
void QValueAxis_TickCountChanged(void* ptr, int tickCount);
void QValueAxis_DestroyQValueAxis(void* ptr);
void* QXYLegendMarker_Series(void* ptr);
void* QXYLegendMarker_SeriesDefault(void* ptr);
void QXYLegendMarker_DestroyQXYLegendMarker(void* ptr);
void QXYLegendMarker_DestroyQXYLegendMarkerDefault(void* ptr);
void* QXYSeries_Brush(void* ptr);
void* QXYSeries_Color(void* ptr);
void* QXYSeries_ColorDefault(void* ptr);
void* QXYSeries_Pen(void* ptr);
char QXYSeries_PointLabelsClipping(void* ptr);
void* QXYSeries_PointLabelsColor(void* ptr);
void* QXYSeries_PointLabelsFont(void* ptr);
struct QtCharts_PackedString QXYSeries_PointLabelsFormat(void* ptr);
char QXYSeries_PointLabelsVisible(void* ptr);
char QXYSeries_PointsVisible(void* ptr);
void QXYSeries_SetColor(void* ptr, void* color);
void QXYSeries_SetColorDefault(void* ptr, void* color);
void QXYSeries_SetPointLabelsClipping(void* ptr, char enabled);
void QXYSeries_SetPointLabelsColor(void* ptr, void* color);
void QXYSeries_SetPointLabelsFont(void* ptr, void* font);
void QXYSeries_SetPointLabelsFormat(void* ptr, char* format);
void QXYSeries_SetPointLabelsVisible(void* ptr, char visible);
void QXYSeries_SetPointsVisible(void* ptr, char visible);
void QXYSeries_Append3(void* ptr, void* points);
void QXYSeries_Append2(void* ptr, void* point);
void QXYSeries_Append(void* ptr, double x, double y);
void* QXYSeries_At(void* ptr, int index);
void QXYSeries_Clear(void* ptr);
void QXYSeries_ConnectClicked(void* ptr);
void QXYSeries_DisconnectClicked(void* ptr);
void QXYSeries_Clicked(void* ptr, void* point);
void QXYSeries_ConnectColorChanged(void* ptr);
void QXYSeries_DisconnectColorChanged(void* ptr);
void QXYSeries_ColorChanged(void* ptr, void* color);
int QXYSeries_Count(void* ptr);
void QXYSeries_ConnectDoubleClicked(void* ptr);
void QXYSeries_DisconnectDoubleClicked(void* ptr);
void QXYSeries_DoubleClicked(void* ptr, void* point);
void QXYSeries_ConnectHovered(void* ptr);
void QXYSeries_DisconnectHovered(void* ptr);
void QXYSeries_Hovered(void* ptr, void* point, char state);
void QXYSeries_Insert(void* ptr, int index, void* point);
void QXYSeries_ConnectPenChanged(void* ptr);
void QXYSeries_DisconnectPenChanged(void* ptr);
void QXYSeries_PenChanged(void* ptr, void* pen);
void QXYSeries_ConnectPointAdded(void* ptr);
void QXYSeries_DisconnectPointAdded(void* ptr);
void QXYSeries_PointAdded(void* ptr, int index);
void QXYSeries_ConnectPointLabelsClippingChanged(void* ptr);
void QXYSeries_DisconnectPointLabelsClippingChanged(void* ptr);
void QXYSeries_PointLabelsClippingChanged(void* ptr, char clipping);
void QXYSeries_ConnectPointLabelsColorChanged(void* ptr);
void QXYSeries_DisconnectPointLabelsColorChanged(void* ptr);
void QXYSeries_PointLabelsColorChanged(void* ptr, void* color);
void QXYSeries_ConnectPointLabelsFontChanged(void* ptr);
void QXYSeries_DisconnectPointLabelsFontChanged(void* ptr);
void QXYSeries_PointLabelsFontChanged(void* ptr, void* font);
void QXYSeries_ConnectPointLabelsFormatChanged(void* ptr);
void QXYSeries_DisconnectPointLabelsFormatChanged(void* ptr);
void QXYSeries_PointLabelsFormatChanged(void* ptr, char* format);
void QXYSeries_ConnectPointLabelsVisibilityChanged(void* ptr);
void QXYSeries_DisconnectPointLabelsVisibilityChanged(void* ptr);
void QXYSeries_PointLabelsVisibilityChanged(void* ptr, char visible);
void QXYSeries_ConnectPointRemoved(void* ptr);
void QXYSeries_DisconnectPointRemoved(void* ptr);
void QXYSeries_PointRemoved(void* ptr, int index);
void QXYSeries_ConnectPointReplaced(void* ptr);
void QXYSeries_DisconnectPointReplaced(void* ptr);
void QXYSeries_PointReplaced(void* ptr, int index);
struct QtCharts_PackedList QXYSeries_Points(void* ptr);
void QXYSeries_ConnectPointsRemoved(void* ptr);
void QXYSeries_DisconnectPointsRemoved(void* ptr);
void QXYSeries_PointsRemoved(void* ptr, int index, int count);
void QXYSeries_ConnectPointsReplaced(void* ptr);
void QXYSeries_DisconnectPointsReplaced(void* ptr);
void QXYSeries_PointsReplaced(void* ptr);
struct QtCharts_PackedList QXYSeries_PointsVector(void* ptr);
void QXYSeries_ConnectPressed(void* ptr);
void QXYSeries_DisconnectPressed(void* ptr);
void QXYSeries_Pressed(void* ptr, void* point);
void QXYSeries_ConnectReleased(void* ptr);
void QXYSeries_DisconnectReleased(void* ptr);
void QXYSeries_Released(void* ptr, void* point);
void QXYSeries_Remove2(void* ptr, void* point);
void QXYSeries_Remove3(void* ptr, int index);
void QXYSeries_Remove(void* ptr, double x, double y);
void QXYSeries_RemovePoints(void* ptr, int index, int count);
void QXYSeries_Replace5(void* ptr, void* points);
void QXYSeries_Replace6(void* ptr, void* points);
void QXYSeries_Replace2(void* ptr, void* oldPoint, void* newPoint);
void QXYSeries_Replace4(void* ptr, int index, void* newPoint);
void QXYSeries_Replace3(void* ptr, int index, double newX, double newY);
void QXYSeries_Replace(void* ptr, double oldX, double oldY, double newX, double newY);
void QXYSeries_SetBrush(void* ptr, void* brush);
void QXYSeries_SetBrushDefault(void* ptr, void* brush);
void QXYSeries_SetPen(void* ptr, void* pen);
void QXYSeries_SetPenDefault(void* ptr, void* pen);
void QXYSeries_DestroyQXYSeries(void* ptr);
void* QXYSeries___append_points_atList3(void* ptr, int i);
void QXYSeries___append_points_setList3(void* ptr, void* i);
void* QXYSeries___append_points_newList3(void* ptr);
void* QXYSeries___points_atList(void* ptr, int i);
void QXYSeries___points_setList(void* ptr, void* i);
void* QXYSeries___points_newList(void* ptr);
void* QXYSeries___pointsVector_atList(void* ptr, int i);
void QXYSeries___pointsVector_setList(void* ptr, void* i);
void* QXYSeries___pointsVector_newList(void* ptr);
void* QXYSeries___replace_points_atList5(void* ptr, int i);
void QXYSeries___replace_points_setList5(void* ptr, void* i);
void* QXYSeries___replace_points_newList5(void* ptr);
void* QXYSeries___replace_points_atList6(void* ptr, int i);
void QXYSeries___replace_points_setList6(void* ptr, void* i);
void* QXYSeries___replace_points_newList6(void* ptr);

#ifdef __cplusplus
}
#endif

#endif