#ifdef __cplusplus
extern "C" {
#endif

int QHeaderView_CascadingSectionResizes(void* ptr);
int QHeaderView_DefaultAlignment(void* ptr);
int QHeaderView_DefaultSectionSize(void* ptr);
int QHeaderView_HighlightSections(void* ptr);
int QHeaderView_IsSortIndicatorShown(void* ptr);
int QHeaderView_MaximumSectionSize(void* ptr);
int QHeaderView_MinimumSectionSize(void* ptr);
void QHeaderView_ResetDefaultSectionSize(void* ptr);
void QHeaderView_ResizeSection(void* ptr, int logicalIndex, int size);
void QHeaderView_SetCascadingSectionResizes(void* ptr, int enable);
void QHeaderView_SetDefaultAlignment(void* ptr, int alignment);
void QHeaderView_SetDefaultSectionSize(void* ptr, int size);
void QHeaderView_SetHighlightSections(void* ptr, int highlight);
void QHeaderView_SetMaximumSectionSize(void* ptr, int size);
void QHeaderView_SetMinimumSectionSize(void* ptr, int size);
void QHeaderView_SetOffset(void* ptr, int offset);
void QHeaderView_SetSortIndicatorShown(void* ptr, int show);
void QHeaderView_SetStretchLastSection(void* ptr, int stretch);
int QHeaderView_StretchLastSection(void* ptr);
int QHeaderView_Count(void* ptr);
void QHeaderView_ConnectGeometriesChanged(void* ptr);
void QHeaderView_DisconnectGeometriesChanged(void* ptr);
void QHeaderView_HeaderDataChanged(void* ptr, int orientation, int logicalFirst, int logicalLast);
int QHeaderView_HiddenSectionCount(void* ptr);
void QHeaderView_HideSection(void* ptr, int logicalIndex);
int QHeaderView_IsSectionHidden(void* ptr, int logicalIndex);
int QHeaderView_Length(void* ptr);
int QHeaderView_LogicalIndex(void* ptr, int visualIndex);
int QHeaderView_LogicalIndexAt3(void* ptr, void* pos);
int QHeaderView_LogicalIndexAt(void* ptr, int position);
int QHeaderView_LogicalIndexAt2(void* ptr, int x, int y);
void QHeaderView_MoveSection(void* ptr, int from, int to);
int QHeaderView_Offset(void* ptr);
int QHeaderView_Orientation(void* ptr);
void QHeaderView_Reset(void* ptr);
int QHeaderView_ResizeContentsPrecision(void* ptr);
void QHeaderView_ResizeSections(void* ptr, int mode);
int QHeaderView_RestoreState(void* ptr, void* state);
void* QHeaderView_SaveState(void* ptr);
void QHeaderView_ConnectSectionClicked(void* ptr);
void QHeaderView_DisconnectSectionClicked(void* ptr);
void QHeaderView_ConnectSectionCountChanged(void* ptr);
void QHeaderView_DisconnectSectionCountChanged(void* ptr);
void QHeaderView_ConnectSectionDoubleClicked(void* ptr);
void QHeaderView_DisconnectSectionDoubleClicked(void* ptr);
void QHeaderView_ConnectSectionEntered(void* ptr);
void QHeaderView_DisconnectSectionEntered(void* ptr);
void QHeaderView_ConnectSectionHandleDoubleClicked(void* ptr);
void QHeaderView_DisconnectSectionHandleDoubleClicked(void* ptr);
void QHeaderView_ConnectSectionMoved(void* ptr);
void QHeaderView_DisconnectSectionMoved(void* ptr);
int QHeaderView_SectionPosition(void* ptr, int logicalIndex);
void QHeaderView_ConnectSectionPressed(void* ptr);
void QHeaderView_DisconnectSectionPressed(void* ptr);
int QHeaderView_SectionResizeMode(void* ptr, int logicalIndex);
void QHeaderView_ConnectSectionResized(void* ptr);
void QHeaderView_DisconnectSectionResized(void* ptr);
int QHeaderView_SectionSize(void* ptr, int logicalIndex);
int QHeaderView_SectionSizeHint(void* ptr, int logicalIndex);
int QHeaderView_SectionViewportPosition(void* ptr, int logicalIndex);
int QHeaderView_SectionsClickable(void* ptr);
int QHeaderView_SectionsHidden(void* ptr);
int QHeaderView_SectionsMovable(void* ptr);
int QHeaderView_SectionsMoved(void* ptr);
void QHeaderView_SetModel(void* ptr, void* model);
void QHeaderView_SetOffsetToLastSection(void* ptr);
void QHeaderView_SetOffsetToSectionPosition(void* ptr, int visualSectionNumber);
void QHeaderView_SetResizeContentsPrecision(void* ptr, int precision);
void QHeaderView_SetSectionHidden(void* ptr, int logicalIndex, int hide);
void QHeaderView_SetSectionResizeMode(void* ptr, int mode);
void QHeaderView_SetSectionResizeMode2(void* ptr, int logicalIndex, int mode);
void QHeaderView_SetSectionsClickable(void* ptr, int clickable);
void QHeaderView_SetSectionsMovable(void* ptr, int movable);
void QHeaderView_SetSortIndicator(void* ptr, int logicalIndex, int order);
void QHeaderView_SetVisible(void* ptr, int v);
void QHeaderView_ShowSection(void* ptr, int logicalIndex);
void QHeaderView_ConnectSortIndicatorChanged(void* ptr);
void QHeaderView_DisconnectSortIndicatorChanged(void* ptr);
int QHeaderView_SortIndicatorOrder(void* ptr);
int QHeaderView_SortIndicatorSection(void* ptr);
int QHeaderView_StretchSectionCount(void* ptr);
void QHeaderView_SwapSections(void* ptr, int first, int second);
int QHeaderView_VisualIndex(void* ptr, int logicalIndex);
int QHeaderView_VisualIndexAt(void* ptr, int position);
void QHeaderView_DestroyQHeaderView(void* ptr);

#ifdef __cplusplus
}
#endif