#ifdef __cplusplus
extern "C" {
#endif
#include "../cgoutil.h"

int QStyle_PM_MdiSubWindowMinimizedWidth_Type();
int QStyle_PM_HeaderMargin_Type();
int QStyle_PM_HeaderMarkSize_Type();
int QStyle_PM_HeaderGripMargin_Type();
int QStyle_PM_TabBarTabShiftHorizontal_Type();
int QStyle_PM_TabBarTabShiftVertical_Type();
int QStyle_PM_TabBarScrollButtonWidth_Type();
int QStyle_PM_ToolBarFrameWidth_Type();
int QStyle_PM_ToolBarHandleExtent_Type();
int QStyle_PM_ToolBarItemSpacing_Type();
int QStyle_PM_ToolBarItemMargin_Type();
int QStyle_PM_ToolBarSeparatorExtent_Type();
int QStyle_PM_ToolBarExtensionExtent_Type();
int QStyle_PM_SpinBoxSliderHeight_Type();
int QStyle_PM_DefaultTopLevelMargin_Type();
int QStyle_PM_DefaultChildMargin_Type();
int QStyle_PM_DefaultLayoutSpacing_Type();
int QStyle_PM_ToolBarIconSize_Type();
int QStyle_PM_ListViewIconSize_Type();
int QStyle_PM_IconViewIconSize_Type();
int QStyle_PM_SmallIconSize_Type();
int QStyle_PM_LargeIconSize_Type();
int QStyle_PM_FocusFrameVMargin_Type();
int QStyle_PM_FocusFrameHMargin_Type();
int QStyle_PM_ToolTipLabelFrameWidth_Type();
int QStyle_PM_CheckBoxLabelSpacing_Type();
int QStyle_PM_TabBarIconSize_Type();
int QStyle_PM_SizeGripSize_Type();
int QStyle_PM_DockWidgetTitleMargin_Type();
int QStyle_PM_MessageBoxIconSize_Type();
int QStyle_PM_ButtonIconSize_Type();
int QStyle_PM_DockWidgetTitleBarButtonMargin_Type();
int QStyle_PM_RadioButtonLabelSpacing_Type();
int QStyle_PM_LayoutLeftMargin_Type();
int QStyle_PM_LayoutTopMargin_Type();
int QStyle_PM_LayoutRightMargin_Type();
int QStyle_PM_LayoutBottomMargin_Type();
int QStyle_PM_LayoutHorizontalSpacing_Type();
int QStyle_PM_LayoutVerticalSpacing_Type();
int QStyle_PM_TabBar_ScrollButtonOverlap_Type();
int QStyle_PM_TextCursorWidth_Type();
int QStyle_PM_TabCloseIndicatorWidth_Type();
int QStyle_PM_TabCloseIndicatorHeight_Type();
int QStyle_PM_ScrollView_ScrollBarSpacing_Type();
int QStyle_PM_ScrollView_ScrollBarOverlap_Type();
int QStyle_PM_SubMenuOverlap_Type();
int QStyle_PM_TreeViewIndentation_Type();
int QStyle_PM_HeaderDefaultSectionSizeHorizontal_Type();
int QStyle_PM_HeaderDefaultSectionSizeVertical_Type();
int QStyle_PE_FrameTabWidget_Type();
int QStyle_PE_FrameWindow_Type();
int QStyle_PE_FrameButtonBevel_Type();
int QStyle_PE_FrameButtonTool_Type();
int QStyle_PE_FrameTabBarBase_Type();
int QStyle_PE_PanelButtonCommand_Type();
int QStyle_PE_PanelButtonBevel_Type();
int QStyle_PE_PanelButtonTool_Type();
int QStyle_PE_PanelMenuBar_Type();
int QStyle_PE_PanelToolBar_Type();
int QStyle_PE_PanelLineEdit_Type();
int QStyle_PE_IndicatorArrowDown_Type();
int QStyle_PE_IndicatorArrowLeft_Type();
int QStyle_PE_IndicatorArrowRight_Type();
int QStyle_PE_IndicatorArrowUp_Type();
int QStyle_PE_IndicatorBranch_Type();
int QStyle_PE_IndicatorButtonDropDown_Type();
int QStyle_PE_IndicatorViewItemCheck_Type();
int QStyle_PE_IndicatorCheckBox_Type();
int QStyle_PE_IndicatorDockWidgetResizeHandle_Type();
int QStyle_PE_IndicatorHeaderArrow_Type();
int QStyle_PE_IndicatorMenuCheckMark_Type();
int QStyle_PE_IndicatorProgressChunk_Type();
int QStyle_PE_IndicatorRadioButton_Type();
int QStyle_PE_IndicatorSpinDown_Type();
int QStyle_PE_IndicatorSpinMinus_Type();
int QStyle_PE_IndicatorSpinPlus_Type();
int QStyle_PE_IndicatorSpinUp_Type();
int QStyle_PE_IndicatorToolBarHandle_Type();
int QStyle_PE_IndicatorToolBarSeparator_Type();
int QStyle_PE_PanelTipLabel_Type();
int QStyle_PE_IndicatorTabTear_Type();
int QStyle_PE_PanelScrollAreaCorner_Type();
int QStyle_PE_Widget_Type();
int QStyle_PE_IndicatorColumnViewArrow_Type();
int QStyle_PE_IndicatorItemViewItemDrop_Type();
int QStyle_PE_PanelItemViewItem_Type();
int QStyle_PE_PanelItemViewRow_Type();
int QStyle_PE_PanelStatusBar_Type();
int QStyle_PE_IndicatorTabClose_Type();
int QStyle_PE_PanelMenu_Type();
int QStyle_SH_BlinkCursorWhenTextSelected_Type();
int QStyle_SH_RichText_FullWidthSelection_Type();
int QStyle_SH_Menu_Scrollable_Type();
int QStyle_SH_GroupBox_TextLabelVerticalAlignment_Type();
int QStyle_SH_GroupBox_TextLabelColor_Type();
int QStyle_SH_Menu_SloppySubMenus_Type();
int QStyle_SH_Table_GridLineColor_Type();
int QStyle_SH_LineEdit_PasswordCharacter_Type();
int QStyle_SH_DialogButtons_DefaultButton_Type();
int QStyle_SH_ToolBox_SelectedPageTitleBold_Type();
int QStyle_SH_TabBar_PreferNoArrows_Type();
int QStyle_SH_ScrollBar_LeftClickAbsolutePosition_Type();
int QStyle_SH_ListViewExpand_SelectMouseType_Type();
int QStyle_SH_UnderlineShortcut_Type();
int QStyle_SH_SpinBox_AnimateButton_Type();
int QStyle_SH_SpinBox_KeyPressAutoRepeatRate_Type();
int QStyle_SH_SpinBox_ClickAutoRepeatRate_Type();
int QStyle_SH_Menu_FillScreenWithScroll_Type();
int QStyle_SH_ToolTipLabel_Opacity_Type();
int QStyle_SH_DrawMenuBarSeparator_Type();
int QStyle_SH_TitleBar_ModifyNotification_Type();
int QStyle_SH_Button_FocusPolicy_Type();
int QStyle_SH_MessageBox_UseBorderForButtonSpacing_Type();
int QStyle_SH_TitleBar_AutoRaise_Type();
int QStyle_SH_ToolButton_PopupDelay_Type();
int QStyle_SH_FocusFrame_Mask_Type();
int QStyle_SH_RubberBand_Mask_Type();
int QStyle_SH_WindowFrame_Mask_Type();
int QStyle_SH_SpinControls_DisableOnBounds_Type();
int QStyle_SH_Dial_BackgroundRole_Type();
int QStyle_SH_ComboBox_LayoutDirection_Type();
int QStyle_SH_ItemView_EllipsisLocation_Type();
int QStyle_SH_ItemView_ShowDecorationSelected_Type();
int QStyle_SH_ItemView_ActivateItemOnSingleClick_Type();
int QStyle_SH_ScrollBar_ContextMenu_Type();
int QStyle_SH_ScrollBar_RollBetweenButtons_Type();
int QStyle_SH_Slider_AbsoluteSetButtons_Type();
int QStyle_SH_Slider_PageSetButtons_Type();
int QStyle_SH_Menu_KeyboardSearch_Type();
int QStyle_SH_TabBar_ElideMode_Type();
int QStyle_SH_DialogButtonLayout_Type();
int QStyle_SH_ComboBox_PopupFrameStyle_Type();
int QStyle_SH_MessageBox_TextInteractionFlags_Type();
int QStyle_SH_DialogButtonBox_ButtonsHaveIcons_Type();
int QStyle_SH_SpellCheckUnderlineStyle_Type();
int QStyle_SH_MessageBox_CenterButtons_Type();
int QStyle_SH_Menu_SelectionWrap_Type();
int QStyle_SH_ItemView_MovementWithoutUpdatingSelection_Type();
int QStyle_SH_ToolTip_Mask_Type();
int QStyle_SH_FocusFrame_AboveWidget_Type();
int QStyle_SH_TextControl_FocusIndicatorTextCharFormat_Type();
int QStyle_SH_WizardStyle_Type();
int QStyle_SH_ItemView_ArrowKeysNavigateIntoChildren_Type();
int QStyle_SH_Menu_Mask_Type();
int QStyle_SH_Menu_FlashTriggeredItem_Type();
int QStyle_SH_Menu_FadeOutOnHide_Type();
int QStyle_SH_SpinBox_ClickAutoRepeatThreshold_Type();
int QStyle_SH_ItemView_PaintAlternatingRowColorsForEmptyArea_Type();
int QStyle_SH_FormLayoutWrapPolicy_Type();
int QStyle_SH_TabWidget_DefaultTabPosition_Type();
int QStyle_SH_ToolBar_Movable_Type();
int QStyle_SH_FormLayoutFieldGrowthPolicy_Type();
int QStyle_SH_FormLayoutFormAlignment_Type();
int QStyle_SH_FormLayoutLabelAlignment_Type();
int QStyle_SH_ItemView_DrawDelegateFrame_Type();
int QStyle_SH_TabBar_CloseButtonPosition_Type();
int QStyle_SH_DockWidget_ButtonsHaveFrame_Type();
int QStyle_SH_ToolButtonStyle_Type();
int QStyle_SH_RequestSoftwareInputPanel_Type();
int QStyle_SH_ScrollBar_Transient_Type();
int QStyle_SH_Menu_SupportsSections_Type();
int QStyle_SH_ToolTip_WakeUpDelay_Type();
int QStyle_SH_ToolTip_FallAsleepDelay_Type();
int QStyle_SH_Widget_Animate_Type();
int QStyle_SH_Splitter_OpaqueResize_Type();
int QStyle_SH_ComboBox_UseNativePopup_Type();
int QStyle_SH_LineEdit_PasswordMaskDelay_Type();
int QStyle_SH_TabBar_ChangeCurrentDelay_Type();
int QStyle_SH_Menu_SubMenuUniDirection_Type();
int QStyle_SH_Menu_SubMenuUniDirectionFailCount_Type();
int QStyle_SH_Menu_SubMenuSloppySelectOtherActions_Type();
int QStyle_SH_Menu_SubMenuSloppyCloseTimeout_Type();
int QStyle_SH_Menu_SubMenuResetWhenReenteringParent_Type();
int QStyle_SH_Menu_SubMenuDontStartSloppyOnLeave_Type();
int QStyle_SE_TabBarTearIndicator_Type();
int QStyle_SE_TreeViewDisclosureItem_Type();
int QStyle_SE_LineEditContents_Type();
int QStyle_SE_FrameContents_Type();
int QStyle_SE_DockWidgetCloseButton_Type();
int QStyle_SE_DockWidgetFloatButton_Type();
int QStyle_SE_DockWidgetTitleBarText_Type();
int QStyle_SE_DockWidgetIcon_Type();
int QStyle_SE_CheckBoxLayoutItem_Type();
int QStyle_SE_ComboBoxLayoutItem_Type();
int QStyle_SE_DateTimeEditLayoutItem_Type();
int QStyle_SE_DialogButtonBoxLayoutItem_Type();
int QStyle_SE_LabelLayoutItem_Type();
int QStyle_SE_ProgressBarLayoutItem_Type();
int QStyle_SE_PushButtonLayoutItem_Type();
int QStyle_SE_RadioButtonLayoutItem_Type();
int QStyle_SE_SliderLayoutItem_Type();
int QStyle_SE_SpinBoxLayoutItem_Type();
int QStyle_SE_ToolButtonLayoutItem_Type();
int QStyle_SE_FrameLayoutItem_Type();
int QStyle_SE_GroupBoxLayoutItem_Type();
int QStyle_SE_TabWidgetLayoutItem_Type();
int QStyle_SE_ItemViewItemDecoration_Type();
int QStyle_SE_ItemViewItemText_Type();
int QStyle_SE_ItemViewItemFocusRect_Type();
int QStyle_SE_TabBarTabLeftButton_Type();
int QStyle_SE_TabBarTabRightButton_Type();
int QStyle_SE_TabBarTabText_Type();
int QStyle_SE_ShapedFrameContents_Type();
int QStyle_SE_ToolBarHandle_Type();
void QStyle_DrawItemPixmap(QtObjectPtr ptr, QtObjectPtr painter, QtObjectPtr rectangle, int alignment, QtObjectPtr pixmap);
void QStyle_DrawItemText(QtObjectPtr ptr, QtObjectPtr painter, QtObjectPtr rectangle, int alignment, QtObjectPtr palette, int enabled, char* text, int textRole);
void QStyle_Polish2(QtObjectPtr ptr, QtObjectPtr application);
void QStyle_Polish3(QtObjectPtr ptr, QtObjectPtr palette);
QtObjectPtr QStyle_Proxy(QtObjectPtr ptr);
int QStyle_QStyle_SliderValueFromPosition(int min, int max, int position, int span, int upsideDown);
void QStyle_Unpolish2(QtObjectPtr ptr, QtObjectPtr application);
int QStyle_CombinedLayoutSpacing(QtObjectPtr ptr, int controls1, int controls2, int orientation, QtObjectPtr option, QtObjectPtr widget);
void QStyle_DrawComplexControl(QtObjectPtr ptr, int control, QtObjectPtr option, QtObjectPtr painter, QtObjectPtr widget);
void QStyle_DrawControl(QtObjectPtr ptr, int element, QtObjectPtr option, QtObjectPtr painter, QtObjectPtr widget);
void QStyle_DrawPrimitive(QtObjectPtr ptr, int element, QtObjectPtr option, QtObjectPtr painter, QtObjectPtr widget);
int QStyle_HitTestComplexControl(QtObjectPtr ptr, int control, QtObjectPtr option, QtObjectPtr position, QtObjectPtr widget);
int QStyle_LayoutSpacing(QtObjectPtr ptr, int control1, int control2, int orientation, QtObjectPtr option, QtObjectPtr widget);
int QStyle_PixelMetric(QtObjectPtr ptr, int metric, QtObjectPtr option, QtObjectPtr widget);
void QStyle_Polish(QtObjectPtr ptr, QtObjectPtr widget);
int QStyle_QStyle_SliderPositionFromValue(int min, int max, int logicalValue, int span, int upsideDown);
int QStyle_StyleHint(QtObjectPtr ptr, int hint, QtObjectPtr option, QtObjectPtr widget, QtObjectPtr returnData);
void QStyle_Unpolish(QtObjectPtr ptr, QtObjectPtr widget);
int QStyle_QStyle_VisualAlignment(int direction, int alignment);
void QStyle_DestroyQStyle(QtObjectPtr ptr);

#ifdef __cplusplus
}
#endif