#ifdef __cplusplus
extern "C" {
#endif

int QTextEdit_AcceptRichText(void* ptr);
int QTextEdit_AutoFormatting(void* ptr);
int QTextEdit_CursorWidth(void* ptr);
void* QTextEdit_Document(void* ptr);
int QTextEdit_IsReadOnly(void* ptr);
int QTextEdit_LineWrapColumnOrWidth(void* ptr);
int QTextEdit_LineWrapMode(void* ptr);
int QTextEdit_OverwriteMode(void* ptr);
char* QTextEdit_PlaceholderText(void* ptr);
void QTextEdit_Redo(void* ptr);
void QTextEdit_SetAcceptRichText(void* ptr, int accept);
void QTextEdit_SetAutoFormatting(void* ptr, int features);
void QTextEdit_SetCursorWidth(void* ptr, int width);
void QTextEdit_SetDocument(void* ptr, void* document);
void QTextEdit_SetFontWeight(void* ptr, int weight);
void QTextEdit_SetHtml(void* ptr, char* text);
void QTextEdit_SetLineWrapColumnOrWidth(void* ptr, int w);
void QTextEdit_SetLineWrapMode(void* ptr, int mode);
void QTextEdit_SetOverwriteMode(void* ptr, int overwrite);
void QTextEdit_SetPlaceholderText(void* ptr, char* placeholderText);
void QTextEdit_SetReadOnly(void* ptr, int ro);
void QTextEdit_SetTabChangesFocus(void* ptr, int b);
void QTextEdit_SetTabStopWidth(void* ptr, int width);
void QTextEdit_SetTextInteractionFlags(void* ptr, int flags);
void QTextEdit_SetWordWrapMode(void* ptr, int policy);
int QTextEdit_TabChangesFocus(void* ptr);
int QTextEdit_TabStopWidth(void* ptr);
int QTextEdit_TextInteractionFlags(void* ptr);
char* QTextEdit_ToHtml(void* ptr);
int QTextEdit_WordWrapMode(void* ptr);
void QTextEdit_ZoomIn(void* ptr, int ran);
void QTextEdit_ZoomOut(void* ptr, int ran);
void* QTextEdit_NewQTextEdit(void* parent);
void* QTextEdit_NewQTextEdit2(char* text, void* parent);
int QTextEdit_Alignment(void* ptr);
char* QTextEdit_AnchorAt(void* ptr, void* pos);
void QTextEdit_Append(void* ptr, char* text);
int QTextEdit_CanPaste(void* ptr);
void QTextEdit_Clear(void* ptr);
void QTextEdit_Copy(void* ptr);
void QTextEdit_ConnectCopyAvailable(void* ptr);
void QTextEdit_DisconnectCopyAvailable(void* ptr);
void* QTextEdit_CreateStandardContextMenu(void* ptr);
void* QTextEdit_CreateStandardContextMenu2(void* ptr, void* position);
void QTextEdit_ConnectCursorPositionChanged(void* ptr);
void QTextEdit_DisconnectCursorPositionChanged(void* ptr);
void QTextEdit_Cut(void* ptr);
char* QTextEdit_DocumentTitle(void* ptr);
void QTextEdit_EnsureCursorVisible(void* ptr);
char* QTextEdit_FontFamily(void* ptr);
int QTextEdit_FontItalic(void* ptr);
double QTextEdit_FontPointSize(void* ptr);
int QTextEdit_FontUnderline(void* ptr);
int QTextEdit_FontWeight(void* ptr);
void* QTextEdit_InputMethodQuery(void* ptr, int property);
void QTextEdit_InsertHtml(void* ptr, char* text);
void QTextEdit_InsertPlainText(void* ptr, char* text);
int QTextEdit_IsUndoRedoEnabled(void* ptr);
void* QTextEdit_LoadResource(void* ptr, int ty, void* name);
void QTextEdit_MergeCurrentCharFormat(void* ptr, void* modifier);
void QTextEdit_MoveCursor(void* ptr, int operation, int mode);
void QTextEdit_Paste(void* ptr);
void QTextEdit_Print(void* ptr, void* printer);
void QTextEdit_ConnectRedoAvailable(void* ptr);
void QTextEdit_DisconnectRedoAvailable(void* ptr);
void QTextEdit_ScrollToAnchor(void* ptr, char* name);
void QTextEdit_SelectAll(void* ptr);
void QTextEdit_ConnectSelectionChanged(void* ptr);
void QTextEdit_DisconnectSelectionChanged(void* ptr);
void QTextEdit_SetAlignment(void* ptr, int a);
void QTextEdit_SetCurrentCharFormat(void* ptr, void* format);
void QTextEdit_SetCurrentFont(void* ptr, void* f);
void QTextEdit_SetDocumentTitle(void* ptr, char* title);
void QTextEdit_SetFontFamily(void* ptr, char* fontFamily);
void QTextEdit_SetFontItalic(void* ptr, int italic);
void QTextEdit_SetFontPointSize(void* ptr, double s);
void QTextEdit_SetFontUnderline(void* ptr, int underline);
void QTextEdit_SetPlainText(void* ptr, char* text);
void QTextEdit_SetText(void* ptr, char* text);
void QTextEdit_SetTextBackgroundColor(void* ptr, void* c);
void QTextEdit_SetTextColor(void* ptr, void* c);
void QTextEdit_SetTextCursor(void* ptr, void* cursor);
void QTextEdit_SetUndoRedoEnabled(void* ptr, int enable);
void* QTextEdit_TextBackgroundColor(void* ptr);
void QTextEdit_ConnectTextChanged(void* ptr);
void QTextEdit_DisconnectTextChanged(void* ptr);
void* QTextEdit_TextColor(void* ptr);
char* QTextEdit_ToPlainText(void* ptr);
void QTextEdit_Undo(void* ptr);
void QTextEdit_ConnectUndoAvailable(void* ptr);
void QTextEdit_DisconnectUndoAvailable(void* ptr);
void QTextEdit_DestroyQTextEdit(void* ptr);

#ifdef __cplusplus
}
#endif