#ifdef __cplusplus
extern "C" {
#endif

int QWidget_AcceptDrops(void* ptr);
char* QWidget_AccessibleDescription(void* ptr);
char* QWidget_AccessibleName(void* ptr);
void QWidget_ActivateWindow(void* ptr);
int QWidget_AutoFillBackground(void* ptr);
void* QWidget_ChildrenRegion(void* ptr);
void QWidget_ClearMask(void* ptr);
int QWidget_ContextMenuPolicy(void* ptr);
int QWidget_FocusPolicy(void* ptr);
void QWidget_GrabKeyboard(void* ptr);
void QWidget_GrabMouse(void* ptr);
void QWidget_GrabMouse2(void* ptr, void* cursor);
int QWidget_HasFocus(void* ptr);
int QWidget_InputMethodHints(void* ptr);
int QWidget_IsActiveWindow(void* ptr);
int QWidget_IsFullScreen(void* ptr);
int QWidget_IsMaximized(void* ptr);
int QWidget_IsMinimized(void* ptr);
int QWidget_IsWindowModified(void* ptr);
void* QWidget_QWidget_KeyboardGrabber();
int QWidget_LayoutDirection(void* ptr);
void* QWidget_QWidget_MouseGrabber();
void QWidget_Move(void* ptr, void* v);
void* QWidget_PaintEngine(void* ptr);
void QWidget_ReleaseKeyboard(void* ptr);
void QWidget_ReleaseMouse(void* ptr);
void QWidget_Resize(void* ptr, void* v);
void QWidget_SetAcceptDrops(void* ptr, int on);
void QWidget_SetAccessibleDescription(void* ptr, char* description);
void QWidget_SetAccessibleName(void* ptr, char* name);
void QWidget_SetAutoFillBackground(void* ptr, int enabled);
void QWidget_SetContextMenuPolicy(void* ptr, int policy);
void QWidget_SetCursor(void* ptr, void* v);
void QWidget_SetEnabled(void* ptr, int v);
void QWidget_SetFixedSize2(void* ptr, int w, int h);
void QWidget_SetFocusPolicy(void* ptr, int policy);
void QWidget_SetFont(void* ptr, void* v);
void QWidget_SetGeometry(void* ptr, void* v);
void QWidget_SetInputMethodHints(void* ptr, int hints);
void QWidget_SetLayout(void* ptr, void* layout);
void QWidget_SetLayoutDirection(void* ptr, int direction);
void QWidget_SetLocale(void* ptr, void* locale);
void QWidget_SetMask(void* ptr, void* bitmap);
void QWidget_SetMask2(void* ptr, void* region);
void QWidget_SetMaximumHeight(void* ptr, int maxh);
void QWidget_SetMaximumWidth(void* ptr, int maxw);
void QWidget_SetMinimumHeight(void* ptr, int minh);
void QWidget_SetMinimumWidth(void* ptr, int minw);
void QWidget_SetPalette(void* ptr, void* v);
void QWidget_SetSizePolicy(void* ptr, void* v);
void QWidget_SetStatusTip(void* ptr, char* v);
void QWidget_SetStyleSheet(void* ptr, char* styleSheet);
void QWidget_SetToolTip(void* ptr, char* v);
void QWidget_SetToolTipDuration(void* ptr, int msec);
void QWidget_SetUpdatesEnabled(void* ptr, int enable);
void QWidget_SetVisible(void* ptr, int visible);
void QWidget_SetWhatsThis(void* ptr, char* v);
void QWidget_SetWindowFilePath(void* ptr, char* filePath);
void QWidget_SetWindowFlags(void* ptr, int ty);
void QWidget_SetWindowIcon(void* ptr, void* icon);
void QWidget_SetWindowIconText(void* ptr, char* v);
void QWidget_SetWindowModality(void* ptr, int windowModality);
void QWidget_SetWindowModified(void* ptr, int v);
void QWidget_SetWindowOpacity(void* ptr, double level);
void QWidget_SetWindowState(void* ptr, int windowState);
void QWidget_SetWindowTitle(void* ptr, char* v);
char* QWidget_StatusTip(void* ptr);
char* QWidget_StyleSheet(void* ptr);
char* QWidget_ToolTip(void* ptr);
int QWidget_ToolTipDuration(void* ptr);
void QWidget_UnsetCursor(void* ptr);
void QWidget_UnsetLayoutDirection(void* ptr);
void QWidget_UnsetLocale(void* ptr);
char* QWidget_WhatsThis(void* ptr);
char* QWidget_WindowFilePath(void* ptr);
char* QWidget_WindowIconText(void* ptr);
int QWidget_WindowModality(void* ptr);
double QWidget_WindowOpacity(void* ptr);
char* QWidget_WindowTitle(void* ptr);
int QWidget_X(void* ptr);
int QWidget_Y(void* ptr);
void* QWidget_NewQWidget(void* parent, int f);
void QWidget_AddAction(void* ptr, void* action);
void QWidget_AdjustSize(void* ptr);
int QWidget_BackgroundRole(void* ptr);
void* QWidget_BackingStore(void* ptr);
void* QWidget_ChildAt2(void* ptr, void* p);
void* QWidget_ChildAt(void* ptr, int x, int y);
void QWidget_ClearFocus(void* ptr);
int QWidget_Close(void* ptr);
void QWidget_EnsurePolished(void* ptr);
void* QWidget_FocusProxy(void* ptr);
void* QWidget_FocusWidget(void* ptr);
int QWidget_ForegroundRole(void* ptr);
void QWidget_GetContentsMargins(void* ptr, int left, int top, int right, int bottom);
void QWidget_GrabGesture(void* ptr, int gesture, int flags);
int QWidget_GrabShortcut(void* ptr, void* key, int context);
void* QWidget_GraphicsEffect(void* ptr);
void* QWidget_GraphicsProxyWidget(void* ptr);
int QWidget_HasHeightForWidth(void* ptr);
int QWidget_HasMouseTracking(void* ptr);
int QWidget_Height(void* ptr);
int QWidget_HeightForWidth(void* ptr, int w);
void QWidget_Hide(void* ptr);
void* QWidget_InputMethodQuery(void* ptr, int query);
void QWidget_InsertAction(void* ptr, void* before, void* action);
int QWidget_IsAncestorOf(void* ptr, void* child);
int QWidget_IsEnabled(void* ptr);
int QWidget_IsEnabledTo(void* ptr, void* ancestor);
int QWidget_IsHidden(void* ptr);
int QWidget_IsModal(void* ptr);
int QWidget_IsVisible(void* ptr);
int QWidget_IsVisibleTo(void* ptr, void* ancestor);
int QWidget_IsWindow(void* ptr);
void* QWidget_Layout(void* ptr);
void QWidget_Lower(void* ptr);
void* QWidget_Mask(void* ptr);
int QWidget_MaximumHeight(void* ptr);
int QWidget_MaximumWidth(void* ptr);
int QWidget_MinimumHeight(void* ptr);
int QWidget_MinimumWidth(void* ptr);
void QWidget_Move2(void* ptr, int x, int y);
void* QWidget_NativeParentWidget(void* ptr);
void* QWidget_NextInFocusChain(void* ptr);
void QWidget_OverrideWindowFlags(void* ptr, int flags);
void* QWidget_ParentWidget(void* ptr);
void* QWidget_PreviousInFocusChain(void* ptr);
void QWidget_Raise(void* ptr);
void QWidget_ReleaseShortcut(void* ptr, int id);
void QWidget_RemoveAction(void* ptr, void* action);
void QWidget_Render(void* ptr, void* target, void* targetOffset, void* sourceRegion, int renderFlags);
void QWidget_Render2(void* ptr, void* painter, void* targetOffset, void* sourceRegion, int renderFlags);
void QWidget_Repaint(void* ptr);
void QWidget_Repaint3(void* ptr, void* rect);
void QWidget_Repaint4(void* ptr, void* rgn);
void QWidget_Repaint2(void* ptr, int x, int y, int w, int h);
void QWidget_Resize2(void* ptr, int w, int h);
int QWidget_RestoreGeometry(void* ptr, void* geometry);
void* QWidget_SaveGeometry(void* ptr);
void QWidget_Scroll(void* ptr, int dx, int dy);
void QWidget_Scroll2(void* ptr, int dx, int dy, void* r);
void QWidget_SetAttribute(void* ptr, int attribute, int on);
void QWidget_SetBackgroundRole(void* ptr, int role);
void QWidget_SetBaseSize(void* ptr, void* v);
void QWidget_SetBaseSize2(void* ptr, int basew, int baseh);
void QWidget_SetContentsMargins2(void* ptr, void* margins);
void QWidget_SetContentsMargins(void* ptr, int left, int top, int right, int bottom);
void QWidget_SetDisabled(void* ptr, int disable);
void QWidget_SetFixedHeight(void* ptr, int h);
void QWidget_SetFixedSize(void* ptr, void* s);
void QWidget_SetFixedWidth(void* ptr, int w);
void QWidget_SetFocus2(void* ptr);
void QWidget_SetFocus(void* ptr, int reason);
void QWidget_SetFocusProxy(void* ptr, void* w);
void QWidget_SetForegroundRole(void* ptr, int role);
void QWidget_SetGeometry2(void* ptr, int x, int y, int w, int h);
void QWidget_SetGraphicsEffect(void* ptr, void* effect);
void QWidget_SetHidden(void* ptr, int hidden);
void QWidget_SetMaximumSize(void* ptr, void* v);
void QWidget_SetMaximumSize2(void* ptr, int maxw, int maxh);
void QWidget_SetMinimumSize(void* ptr, void* v);
void QWidget_SetMinimumSize2(void* ptr, int minw, int minh);
void QWidget_SetMouseTracking(void* ptr, int enable);
void QWidget_SetParent(void* ptr, void* parent);
void QWidget_SetParent2(void* ptr, void* parent, int f);
void QWidget_SetShortcutAutoRepeat(void* ptr, int id, int enable);
void QWidget_SetShortcutEnabled(void* ptr, int id, int enable);
void QWidget_SetSizeIncrement(void* ptr, void* v);
void QWidget_SetSizeIncrement2(void* ptr, int w, int h);
void QWidget_SetSizePolicy2(void* ptr, int horizontal, int vertical);
void QWidget_SetStyle(void* ptr, void* style);
void QWidget_QWidget_SetTabOrder(void* first, void* second);
void QWidget_SetWindowRole(void* ptr, char* role);
void QWidget_Show(void* ptr);
void QWidget_ShowFullScreen(void* ptr);
void QWidget_ShowMaximized(void* ptr);
void QWidget_ShowMinimized(void* ptr);
void QWidget_ShowNormal(void* ptr);
void QWidget_StackUnder(void* ptr, void* w);
void* QWidget_Style(void* ptr);
int QWidget_TestAttribute(void* ptr, int attribute);
int QWidget_UnderMouse(void* ptr);
void QWidget_UngrabGesture(void* ptr, int gesture);
void QWidget_Update(void* ptr);
void QWidget_Update3(void* ptr, void* rect);
void QWidget_Update4(void* ptr, void* rgn);
void QWidget_Update2(void* ptr, int x, int y, int w, int h);
void QWidget_UpdateGeometry(void* ptr);
int QWidget_UpdatesEnabled(void* ptr);
void* QWidget_VisibleRegion(void* ptr);
int QWidget_Width(void* ptr);
void* QWidget_Window(void* ptr);
int QWidget_WindowFlags(void* ptr);
void* QWidget_WindowHandle(void* ptr);
void QWidget_ConnectWindowIconTextChanged(void* ptr);
void QWidget_DisconnectWindowIconTextChanged(void* ptr);
char* QWidget_WindowRole(void* ptr);
int QWidget_WindowState(void* ptr);
void QWidget_ConnectWindowTitleChanged(void* ptr);
void QWidget_DisconnectWindowTitleChanged(void* ptr);
int QWidget_WindowType(void* ptr);
void QWidget_DestroyQWidget(void* ptr);
void* QWidget_QWidget_CreateWindowContainer(void* window, void* parent, int flags);

#ifdef __cplusplus
}
#endif