#pragma once

#ifndef GO_QTWEBENGINE_H
#define GO_QTWEBENGINE_H

#ifdef __cplusplus
extern "C" {
#endif

char* QQuickWebEngineProfile_CachePath(void* ptr);
char* QQuickWebEngineProfile_HttpAcceptLanguage(void* ptr);
int QQuickWebEngineProfile_HttpCacheMaximumSize(void* ptr);
int QQuickWebEngineProfile_HttpCacheType(void* ptr);
char* QQuickWebEngineProfile_HttpUserAgent(void* ptr);
int QQuickWebEngineProfile_IsOffTheRecord(void* ptr);
int QQuickWebEngineProfile_PersistentCookiesPolicy(void* ptr);
char* QQuickWebEngineProfile_PersistentStoragePath(void* ptr);
void QQuickWebEngineProfile_SetCachePath(void* ptr, char* path);
void QQuickWebEngineProfile_SetHttpAcceptLanguage(void* ptr, char* httpAcceptLanguage);
void QQuickWebEngineProfile_SetHttpCacheMaximumSize(void* ptr, int maxSize);
void QQuickWebEngineProfile_SetHttpCacheType(void* ptr, int vqq);
void QQuickWebEngineProfile_SetHttpUserAgent(void* ptr, char* userAgent);
void QQuickWebEngineProfile_SetOffTheRecord(void* ptr, int offTheRecord);
void QQuickWebEngineProfile_SetPersistentCookiesPolicy(void* ptr, int vqq);
void QQuickWebEngineProfile_SetPersistentStoragePath(void* ptr, char* path);
void QQuickWebEngineProfile_SetStorageName(void* ptr, char* name);
char* QQuickWebEngineProfile_StorageName(void* ptr);
void* QQuickWebEngineProfile_NewQQuickWebEngineProfile(void* parent);
void QQuickWebEngineProfile_ConnectCachePathChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectCachePathChanged(void* ptr);
void QQuickWebEngineProfile_CachePathChanged(void* ptr);
void* QQuickWebEngineProfile_CookieStore(void* ptr);
void* QQuickWebEngineProfile_QQuickWebEngineProfile_DefaultProfile();
void QQuickWebEngineProfile_ConnectHttpAcceptLanguageChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpAcceptLanguageChanged(void* ptr);
void QQuickWebEngineProfile_HttpAcceptLanguageChanged(void* ptr);
void QQuickWebEngineProfile_ConnectHttpCacheMaximumSizeChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpCacheMaximumSizeChanged(void* ptr);
void QQuickWebEngineProfile_HttpCacheMaximumSizeChanged(void* ptr);
void QQuickWebEngineProfile_ConnectHttpCacheTypeChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpCacheTypeChanged(void* ptr);
void QQuickWebEngineProfile_HttpCacheTypeChanged(void* ptr);
void QQuickWebEngineProfile_ConnectHttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_HttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_InstallUrlSchemeHandler(void* ptr, char* scheme, void* handler);
void QQuickWebEngineProfile_ConnectOffTheRecordChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectOffTheRecordChanged(void* ptr);
void QQuickWebEngineProfile_OffTheRecordChanged(void* ptr);
void QQuickWebEngineProfile_ConnectPersistentCookiesPolicyChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectPersistentCookiesPolicyChanged(void* ptr);
void QQuickWebEngineProfile_PersistentCookiesPolicyChanged(void* ptr);
void QQuickWebEngineProfile_ConnectPersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectPersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_PersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_RemoveAllUrlSchemeHandlers(void* ptr);
void QQuickWebEngineProfile_RemoveUrlScheme(void* ptr, char* scheme);
void QQuickWebEngineProfile_RemoveUrlSchemeHandler(void* ptr, void* handler);
void QQuickWebEngineProfile_SetRequestInterceptor(void* ptr, void* interceptor);
void QQuickWebEngineProfile_ConnectStorageNameChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectStorageNameChanged(void* ptr);
void QQuickWebEngineProfile_StorageNameChanged(void* ptr);
void* QQuickWebEngineProfile_UrlSchemeHandler(void* ptr, char* scheme);
void QQuickWebEngineProfile_TimerEvent(void* ptr, void* event);
void QQuickWebEngineProfile_TimerEventDefault(void* ptr, void* event);
void QQuickWebEngineProfile_ChildEvent(void* ptr, void* event);
void QQuickWebEngineProfile_ChildEventDefault(void* ptr, void* event);
void QQuickWebEngineProfile_ConnectNotify(void* ptr, void* sign);
void QQuickWebEngineProfile_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickWebEngineProfile_CustomEvent(void* ptr, void* event);
void QQuickWebEngineProfile_CustomEventDefault(void* ptr, void* event);
void QQuickWebEngineProfile_DeleteLater(void* ptr);
void QQuickWebEngineProfile_DeleteLaterDefault(void* ptr);
void QQuickWebEngineProfile_DisconnectNotify(void* ptr, void* sign);
void QQuickWebEngineProfile_DisconnectNotifyDefault(void* ptr, void* sign);
int QQuickWebEngineProfile_Event(void* ptr, void* e);
int QQuickWebEngineProfile_EventDefault(void* ptr, void* e);
int QQuickWebEngineProfile_EventFilter(void* ptr, void* watched, void* event);
int QQuickWebEngineProfile_EventFilterDefault(void* ptr, void* watched, void* event);
void* QQuickWebEngineProfile_MetaObject(void* ptr);
void* QQuickWebEngineProfile_MetaObjectDefault(void* ptr);
int QWebEngineCertificateError_Error(void* ptr);
char* QWebEngineCertificateError_ErrorDescription(void* ptr);
int QWebEngineCertificateError_IsOverridable(void* ptr);
void* QWebEngineCertificateError_Url(void* ptr);
void QWebEngineCookieStore_ConnectCookieAdded(void* ptr);
void QWebEngineCookieStore_DisconnectCookieAdded(void* ptr);
void QWebEngineCookieStore_CookieAdded(void* ptr, void* cookie);
void QWebEngineCookieStore_ConnectCookieRemoved(void* ptr);
void QWebEngineCookieStore_DisconnectCookieRemoved(void* ptr);
void QWebEngineCookieStore_CookieRemoved(void* ptr, void* cookie);
void QWebEngineCookieStore_DeleteAllCookies(void* ptr);
void QWebEngineCookieStore_DeleteCookie(void* ptr, void* cookie, void* origin);
void QWebEngineCookieStore_DeleteSessionCookies(void* ptr);
void QWebEngineCookieStore_LoadAllCookies(void* ptr);
void QWebEngineCookieStore_SetCookie(void* ptr, void* cookie, void* origin);
void QWebEngineCookieStore_DestroyQWebEngineCookieStore(void* ptr);
void QWebEngineCookieStore_TimerEvent(void* ptr, void* event);
void QWebEngineCookieStore_TimerEventDefault(void* ptr, void* event);
void QWebEngineCookieStore_ChildEvent(void* ptr, void* event);
void QWebEngineCookieStore_ChildEventDefault(void* ptr, void* event);
void QWebEngineCookieStore_ConnectNotify(void* ptr, void* sign);
void QWebEngineCookieStore_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineCookieStore_CustomEvent(void* ptr, void* event);
void QWebEngineCookieStore_CustomEventDefault(void* ptr, void* event);
void QWebEngineCookieStore_DeleteLater(void* ptr);
void QWebEngineCookieStore_DeleteLaterDefault(void* ptr);
void QWebEngineCookieStore_DisconnectNotify(void* ptr, void* sign);
void QWebEngineCookieStore_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineCookieStore_Event(void* ptr, void* e);
int QWebEngineCookieStore_EventDefault(void* ptr, void* e);
int QWebEngineCookieStore_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineCookieStore_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineCookieStore_MetaObject(void* ptr);
void* QWebEngineCookieStore_MetaObjectDefault(void* ptr);
void QWebEngineDownloadItem_Accept(void* ptr);
void QWebEngineDownloadItem_Cancel(void* ptr);
void QWebEngineDownloadItem_ConnectDownloadProgress(void* ptr);
void QWebEngineDownloadItem_DisconnectDownloadProgress(void* ptr);
void QWebEngineDownloadItem_DownloadProgress(void* ptr, long long bytesReceived, long long bytesTotal);
void QWebEngineDownloadItem_ConnectFinished(void* ptr);
void QWebEngineDownloadItem_DisconnectFinished(void* ptr);
void QWebEngineDownloadItem_Finished(void* ptr);
int QWebEngineDownloadItem_IsFinished(void* ptr);
char* QWebEngineDownloadItem_MimeType(void* ptr);
char* QWebEngineDownloadItem_Path(void* ptr);
long long QWebEngineDownloadItem_ReceivedBytes(void* ptr);
void QWebEngineDownloadItem_SetPath(void* ptr, char* path);
int QWebEngineDownloadItem_State(void* ptr);
void QWebEngineDownloadItem_ConnectStateChanged(void* ptr);
void QWebEngineDownloadItem_DisconnectStateChanged(void* ptr);
void QWebEngineDownloadItem_StateChanged(void* ptr, int state);
long long QWebEngineDownloadItem_TotalBytes(void* ptr);
void* QWebEngineDownloadItem_Url(void* ptr);
void QWebEngineDownloadItem_TimerEvent(void* ptr, void* event);
void QWebEngineDownloadItem_TimerEventDefault(void* ptr, void* event);
void QWebEngineDownloadItem_ChildEvent(void* ptr, void* event);
void QWebEngineDownloadItem_ChildEventDefault(void* ptr, void* event);
void QWebEngineDownloadItem_ConnectNotify(void* ptr, void* sign);
void QWebEngineDownloadItem_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineDownloadItem_CustomEvent(void* ptr, void* event);
void QWebEngineDownloadItem_CustomEventDefault(void* ptr, void* event);
void QWebEngineDownloadItem_DeleteLater(void* ptr);
void QWebEngineDownloadItem_DeleteLaterDefault(void* ptr);
void QWebEngineDownloadItem_DisconnectNotify(void* ptr, void* sign);
void QWebEngineDownloadItem_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineDownloadItem_Event(void* ptr, void* e);
int QWebEngineDownloadItem_EventDefault(void* ptr, void* e);
int QWebEngineDownloadItem_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineDownloadItem_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineDownloadItem_MetaObject(void* ptr);
void* QWebEngineDownloadItem_MetaObjectDefault(void* ptr);
void QWebEngineHistory_Back(void* ptr);
void* QWebEngineHistory_BackItem(void* ptr);
int QWebEngineHistory_CanGoBack(void* ptr);
int QWebEngineHistory_CanGoForward(void* ptr);
void QWebEngineHistory_Clear(void* ptr);
int QWebEngineHistory_Count(void* ptr);
void* QWebEngineHistory_CurrentItem(void* ptr);
int QWebEngineHistory_CurrentItemIndex(void* ptr);
void QWebEngineHistory_Forward(void* ptr);
void* QWebEngineHistory_ForwardItem(void* ptr);
void QWebEngineHistory_GoToItem(void* ptr, void* item);
void* QWebEngineHistory_ItemAt(void* ptr, int i);
void* QWebEngineHistoryItem_NewQWebEngineHistoryItem(void* other);
int QWebEngineHistoryItem_IsValid(void* ptr);
void* QWebEngineHistoryItem_LastVisited(void* ptr);
void* QWebEngineHistoryItem_OriginalUrl(void* ptr);
char* QWebEngineHistoryItem_Title(void* ptr);
void* QWebEngineHistoryItem_Url(void* ptr);
void QWebEngineHistoryItem_DestroyQWebEngineHistoryItem(void* ptr);
void* QWebEngineHistoryItem_IconUrl(void* ptr);
void QWebEngineHistoryItem_Swap(void* ptr, void* other);
void* QWebEnginePage_NewQWebEnginePage(void* parent);
int QWebEnginePage_AcceptNavigationRequest(void* ptr, void* url, int ty, int isMainFrame);
int QWebEnginePage_AcceptNavigationRequestDefault(void* ptr, void* url, int ty, int isMainFrame);
void* QWebEnginePage_Action(void* ptr, int action);
void* QWebEnginePage_BackgroundColor(void* ptr);
char* QWebEnginePage_ChooseFiles(void* ptr, int mode, char* oldFiles, char* acceptedMimeTypes);
char* QWebEnginePage_ChooseFilesDefault(void* ptr, int mode, char* oldFiles, char* acceptedMimeTypes);
void* QWebEnginePage_CreateStandardContextMenu(void* ptr);
void* QWebEnginePage_CreateWindow(void* ptr, int ty);
void* QWebEnginePage_CreateWindowDefault(void* ptr, int ty);
int QWebEnginePage_HasSelection(void* ptr);
void* QWebEnginePage_History(void* ptr);
void* QWebEnginePage_IconUrl(void* ptr);
void QWebEnginePage_JavaScriptAlert(void* ptr, void* securityOrigin, char* msg);
void QWebEnginePage_JavaScriptAlertDefault(void* ptr, void* securityOrigin, char* msg);
int QWebEnginePage_JavaScriptConfirm(void* ptr, void* securityOrigin, char* msg);
int QWebEnginePage_JavaScriptConfirmDefault(void* ptr, void* securityOrigin, char* msg);
void QWebEnginePage_JavaScriptConsoleMessage(void* ptr, int level, char* message, int lineNumber, char* sourceID);
void QWebEnginePage_JavaScriptConsoleMessageDefault(void* ptr, int level, char* message, int lineNumber, char* sourceID);
int QWebEnginePage_JavaScriptPrompt(void* ptr, void* securityOrigin, char* msg, char* defaultValue, char* result);
int QWebEnginePage_JavaScriptPromptDefault(void* ptr, void* securityOrigin, char* msg, char* defaultValue, char* result);
void QWebEnginePage_Load(void* ptr, void* url);
void* QWebEnginePage_RequestedUrl(void* ptr);
void QWebEnginePage_RunJavaScript2(void* ptr, char* scriptSource);
char* QWebEnginePage_SelectedText(void* ptr);
void QWebEnginePage_SetBackgroundColor(void* ptr, void* color);
void QWebEnginePage_SetContent(void* ptr, char* data, char* mimeType, void* baseUrl);
void QWebEnginePage_SetFeaturePermission(void* ptr, void* securityOrigin, int feature, int policy);
void QWebEnginePage_SetHtml(void* ptr, char* html, void* baseUrl);
void QWebEnginePage_SetUrl(void* ptr, void* url);
void QWebEnginePage_SetView(void* ptr, void* view);
void QWebEnginePage_SetZoomFactor(void* ptr, double factor);
void* QWebEnginePage_Settings(void* ptr);
char* QWebEnginePage_Title(void* ptr);
void QWebEnginePage_TriggerAction(void* ptr, int action, int checked);
void QWebEnginePage_TriggerActionDefault(void* ptr, int action, int checked);
void* QWebEnginePage_Url(void* ptr);
void* QWebEnginePage_View(void* ptr);
double QWebEnginePage_ZoomFactor(void* ptr);
void QWebEnginePage_DestroyQWebEnginePage(void* ptr);
void* QWebEnginePage_NewQWebEnginePage2(void* profile, void* parent);
void QWebEnginePage_ConnectAuthenticationRequired(void* ptr);
void QWebEnginePage_DisconnectAuthenticationRequired(void* ptr);
void QWebEnginePage_AuthenticationRequired(void* ptr, void* requestUrl, void* authenticator);
int QWebEnginePage_Event(void* ptr, void* e);
int QWebEnginePage_EventDefault(void* ptr, void* e);
void QWebEnginePage_ConnectFeaturePermissionRequestCanceled(void* ptr);
void QWebEnginePage_DisconnectFeaturePermissionRequestCanceled(void* ptr);
void QWebEnginePage_FeaturePermissionRequestCanceled(void* ptr, void* securityOrigin, int feature);
void QWebEnginePage_ConnectFeaturePermissionRequested(void* ptr);
void QWebEnginePage_DisconnectFeaturePermissionRequested(void* ptr);
void QWebEnginePage_FeaturePermissionRequested(void* ptr, void* securityOrigin, int feature);
void QWebEnginePage_FindText(void* ptr, char* subString, int options);
void QWebEnginePage_ConnectGeometryChangeRequested(void* ptr);
void QWebEnginePage_DisconnectGeometryChangeRequested(void* ptr);
void QWebEnginePage_GeometryChangeRequested(void* ptr, void* geom);
void QWebEnginePage_ConnectIconUrlChanged(void* ptr);
void QWebEnginePage_DisconnectIconUrlChanged(void* ptr);
void QWebEnginePage_IconUrlChanged(void* ptr, void* url);
void QWebEnginePage_ConnectLinkHovered(void* ptr);
void QWebEnginePage_DisconnectLinkHovered(void* ptr);
void QWebEnginePage_LinkHovered(void* ptr, char* url);
void QWebEnginePage_ConnectLoadFinished(void* ptr);
void QWebEnginePage_DisconnectLoadFinished(void* ptr);
void QWebEnginePage_LoadFinished(void* ptr, int ok);
void QWebEnginePage_ConnectLoadProgress(void* ptr);
void QWebEnginePage_DisconnectLoadProgress(void* ptr);
void QWebEnginePage_LoadProgress(void* ptr, int progress);
void QWebEnginePage_ConnectLoadStarted(void* ptr);
void QWebEnginePage_DisconnectLoadStarted(void* ptr);
void QWebEnginePage_LoadStarted(void* ptr);
void* QWebEnginePage_Profile(void* ptr);
void QWebEnginePage_ConnectProxyAuthenticationRequired(void* ptr);
void QWebEnginePage_DisconnectProxyAuthenticationRequired(void* ptr);
void QWebEnginePage_ProxyAuthenticationRequired(void* ptr, void* requestUrl, void* authenticator, char* proxyHost);
void QWebEnginePage_ConnectRenderProcessTerminated(void* ptr);
void QWebEnginePage_DisconnectRenderProcessTerminated(void* ptr);
void QWebEnginePage_RenderProcessTerminated(void* ptr, int terminationStatus, int exitCode);
void QWebEnginePage_ConnectSelectionChanged(void* ptr);
void QWebEnginePage_DisconnectSelectionChanged(void* ptr);
void QWebEnginePage_SelectionChanged(void* ptr);
void QWebEnginePage_SetWebChannel(void* ptr, void* channel);
void QWebEnginePage_ConnectTitleChanged(void* ptr);
void QWebEnginePage_DisconnectTitleChanged(void* ptr);
void QWebEnginePage_TitleChanged(void* ptr, char* title);
void QWebEnginePage_ConnectUrlChanged(void* ptr);
void QWebEnginePage_DisconnectUrlChanged(void* ptr);
void QWebEnginePage_UrlChanged(void* ptr, void* url);
void* QWebEnginePage_WebChannel(void* ptr);
void QWebEnginePage_ConnectWindowCloseRequested(void* ptr);
void QWebEnginePage_DisconnectWindowCloseRequested(void* ptr);
void QWebEnginePage_WindowCloseRequested(void* ptr);
void QWebEnginePage_TimerEvent(void* ptr, void* event);
void QWebEnginePage_TimerEventDefault(void* ptr, void* event);
void QWebEnginePage_ChildEvent(void* ptr, void* event);
void QWebEnginePage_ChildEventDefault(void* ptr, void* event);
void QWebEnginePage_ConnectNotify(void* ptr, void* sign);
void QWebEnginePage_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEnginePage_CustomEvent(void* ptr, void* event);
void QWebEnginePage_CustomEventDefault(void* ptr, void* event);
void QWebEnginePage_DeleteLater(void* ptr);
void QWebEnginePage_DeleteLaterDefault(void* ptr);
void QWebEnginePage_DisconnectNotify(void* ptr, void* sign);
void QWebEnginePage_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEnginePage_EventFilter(void* ptr, void* watched, void* event);
int QWebEnginePage_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEnginePage_MetaObject(void* ptr);
void* QWebEnginePage_MetaObjectDefault(void* ptr);
void* QWebEngineProfile_NewQWebEngineProfile(void* parent);
void* QWebEngineProfile_NewQWebEngineProfile2(char* storageName, void* parent);
char* QWebEngineProfile_CachePath(void* ptr);
void QWebEngineProfile_ClearAllVisitedLinks(void* ptr);
void* QWebEngineProfile_CookieStore(void* ptr);
void* QWebEngineProfile_QWebEngineProfile_DefaultProfile();
void QWebEngineProfile_ConnectDownloadRequested(void* ptr);
void QWebEngineProfile_DisconnectDownloadRequested(void* ptr);
void QWebEngineProfile_DownloadRequested(void* ptr, void* download);
char* QWebEngineProfile_HttpAcceptLanguage(void* ptr);
int QWebEngineProfile_HttpCacheMaximumSize(void* ptr);
int QWebEngineProfile_HttpCacheType(void* ptr);
char* QWebEngineProfile_HttpUserAgent(void* ptr);
void QWebEngineProfile_InstallUrlSchemeHandler(void* ptr, char* scheme, void* handler);
int QWebEngineProfile_IsOffTheRecord(void* ptr);
int QWebEngineProfile_PersistentCookiesPolicy(void* ptr);
char* QWebEngineProfile_PersistentStoragePath(void* ptr);
void QWebEngineProfile_RemoveAllUrlSchemeHandlers(void* ptr);
void QWebEngineProfile_RemoveUrlScheme(void* ptr, char* scheme);
void QWebEngineProfile_RemoveUrlSchemeHandler(void* ptr, void* handler);
void* QWebEngineProfile_Scripts(void* ptr);
void QWebEngineProfile_SetCachePath(void* ptr, char* path);
void QWebEngineProfile_SetHttpAcceptLanguage(void* ptr, char* httpAcceptLanguage);
void QWebEngineProfile_SetHttpCacheMaximumSize(void* ptr, int maxSize);
void QWebEngineProfile_SetHttpCacheType(void* ptr, int httpCacheType);
void QWebEngineProfile_SetHttpUserAgent(void* ptr, char* userAgent);
void QWebEngineProfile_SetPersistentCookiesPolicy(void* ptr, int newPersistentCookiesPolicy);
void QWebEngineProfile_SetPersistentStoragePath(void* ptr, char* path);
void QWebEngineProfile_SetRequestInterceptor(void* ptr, void* interceptor);
void* QWebEngineProfile_Settings(void* ptr);
char* QWebEngineProfile_StorageName(void* ptr);
void* QWebEngineProfile_UrlSchemeHandler(void* ptr, char* scheme);
int QWebEngineProfile_VisitedLinksContainsUrl(void* ptr, void* url);
void QWebEngineProfile_TimerEvent(void* ptr, void* event);
void QWebEngineProfile_TimerEventDefault(void* ptr, void* event);
void QWebEngineProfile_ChildEvent(void* ptr, void* event);
void QWebEngineProfile_ChildEventDefault(void* ptr, void* event);
void QWebEngineProfile_ConnectNotify(void* ptr, void* sign);
void QWebEngineProfile_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineProfile_CustomEvent(void* ptr, void* event);
void QWebEngineProfile_CustomEventDefault(void* ptr, void* event);
void QWebEngineProfile_DeleteLater(void* ptr);
void QWebEngineProfile_DeleteLaterDefault(void* ptr);
void QWebEngineProfile_DisconnectNotify(void* ptr, void* sign);
void QWebEngineProfile_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineProfile_Event(void* ptr, void* e);
int QWebEngineProfile_EventDefault(void* ptr, void* e);
int QWebEngineProfile_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineProfile_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineProfile_MetaObject(void* ptr);
void* QWebEngineProfile_MetaObjectDefault(void* ptr);
void* QWebEngineScript_NewQWebEngineScript();
void* QWebEngineScript_NewQWebEngineScript2(void* other);
int QWebEngineScript_InjectionPoint(void* ptr);
int QWebEngineScript_IsNull(void* ptr);
char* QWebEngineScript_Name(void* ptr);
int QWebEngineScript_RunsOnSubFrames(void* ptr);
void QWebEngineScript_SetInjectionPoint(void* ptr, int p);
void QWebEngineScript_SetName(void* ptr, char* scriptName);
void QWebEngineScript_SetRunsOnSubFrames(void* ptr, int on);
void QWebEngineScript_SetSourceCode(void* ptr, char* scriptSource);
char* QWebEngineScript_SourceCode(void* ptr);
void QWebEngineScript_Swap(void* ptr, void* other);
void QWebEngineScript_DestroyQWebEngineScript(void* ptr);
void QWebEngineScriptCollection_Clear(void* ptr);
int QWebEngineScriptCollection_Contains(void* ptr, void* value);
int QWebEngineScriptCollection_Count(void* ptr);
void* QWebEngineScriptCollection_FindScript(void* ptr, char* name);
void QWebEngineScriptCollection_Insert(void* ptr, void* s);
int QWebEngineScriptCollection_IsEmpty(void* ptr);
int QWebEngineScriptCollection_Remove(void* ptr, void* script);
int QWebEngineScriptCollection_Size(void* ptr);
void QWebEngineScriptCollection_DestroyQWebEngineScriptCollection(void* ptr);
char* QWebEngineSettings_DefaultTextEncoding(void* ptr);
char* QWebEngineSettings_FontFamily(void* ptr, int which);
int QWebEngineSettings_FontSize(void* ptr, int ty);
void* QWebEngineSettings_QWebEngineSettings_GlobalSettings();
void QWebEngineSettings_ResetAttribute(void* ptr, int attribute);
void QWebEngineSettings_ResetFontFamily(void* ptr, int which);
void QWebEngineSettings_ResetFontSize(void* ptr, int ty);
void QWebEngineSettings_SetAttribute(void* ptr, int attribute, int on);
void QWebEngineSettings_SetDefaultTextEncoding(void* ptr, char* encoding);
void QWebEngineSettings_SetFontFamily(void* ptr, int which, char* family);
void QWebEngineSettings_SetFontSize(void* ptr, int ty, int size);
int QWebEngineSettings_TestAttribute(void* ptr, int attribute);
void* QWebEngineSettings_QWebEngineSettings_DefaultSettings();
void QWebEngineUrlRequestInfo_Block(void* ptr, int shouldBlock);
void* QWebEngineUrlRequestInfo_FirstPartyUrl(void* ptr);
int QWebEngineUrlRequestInfo_NavigationType(void* ptr);
void QWebEngineUrlRequestInfo_Redirect(void* ptr, void* url);
char* QWebEngineUrlRequestInfo_RequestMethod(void* ptr);
void* QWebEngineUrlRequestInfo_RequestUrl(void* ptr);
int QWebEngineUrlRequestInfo_ResourceType(void* ptr);
void QWebEngineUrlRequestInfo_SetHttpHeader(void* ptr, char* name, char* value);
void QWebEngineUrlRequestInterceptor_TimerEvent(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_TimerEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_ChildEvent(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_ConnectNotify(void* ptr, void* sign);
void QWebEngineUrlRequestInterceptor_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlRequestInterceptor_CustomEvent(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_DeleteLater(void* ptr);
void QWebEngineUrlRequestInterceptor_DeleteLaterDefault(void* ptr);
void QWebEngineUrlRequestInterceptor_DisconnectNotify(void* ptr, void* sign);
void QWebEngineUrlRequestInterceptor_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineUrlRequestInterceptor_Event(void* ptr, void* e);
int QWebEngineUrlRequestInterceptor_EventDefault(void* ptr, void* e);
int QWebEngineUrlRequestInterceptor_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineUrlRequestInterceptor_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineUrlRequestInterceptor_MetaObject(void* ptr);
void* QWebEngineUrlRequestInterceptor_MetaObjectDefault(void* ptr);
void QWebEngineUrlRequestJob_Fail(void* ptr, int r);
void QWebEngineUrlRequestJob_Redirect(void* ptr, void* url);
void QWebEngineUrlRequestJob_Reply(void* ptr, char* contentType, void* device);
char* QWebEngineUrlRequestJob_RequestMethod(void* ptr);
void* QWebEngineUrlRequestJob_RequestUrl(void* ptr);
void QWebEngineUrlRequestJob_TimerEvent(void* ptr, void* event);
void QWebEngineUrlRequestJob_TimerEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_ChildEvent(void* ptr, void* event);
void QWebEngineUrlRequestJob_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_ConnectNotify(void* ptr, void* sign);
void QWebEngineUrlRequestJob_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlRequestJob_CustomEvent(void* ptr, void* event);
void QWebEngineUrlRequestJob_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_DeleteLater(void* ptr);
void QWebEngineUrlRequestJob_DeleteLaterDefault(void* ptr);
void QWebEngineUrlRequestJob_DisconnectNotify(void* ptr, void* sign);
void QWebEngineUrlRequestJob_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineUrlRequestJob_Event(void* ptr, void* e);
int QWebEngineUrlRequestJob_EventDefault(void* ptr, void* e);
int QWebEngineUrlRequestJob_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineUrlRequestJob_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineUrlRequestJob_MetaObject(void* ptr);
void* QWebEngineUrlRequestJob_MetaObjectDefault(void* ptr);
void* QWebEngineUrlSchemeHandler_NewQWebEngineUrlSchemeHandler(void* parent);
void QWebEngineUrlSchemeHandler_RequestStarted(void* ptr, void* request);
void QWebEngineUrlSchemeHandler_DestroyQWebEngineUrlSchemeHandler(void* ptr);
void QWebEngineUrlSchemeHandler_TimerEvent(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_TimerEventDefault(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_ChildEvent(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_ConnectNotify(void* ptr, void* sign);
void QWebEngineUrlSchemeHandler_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlSchemeHandler_CustomEvent(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_DeleteLater(void* ptr);
void QWebEngineUrlSchemeHandler_DeleteLaterDefault(void* ptr);
void QWebEngineUrlSchemeHandler_DisconnectNotify(void* ptr, void* sign);
void QWebEngineUrlSchemeHandler_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineUrlSchemeHandler_Event(void* ptr, void* e);
int QWebEngineUrlSchemeHandler_EventDefault(void* ptr, void* e);
int QWebEngineUrlSchemeHandler_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineUrlSchemeHandler_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineUrlSchemeHandler_MetaObject(void* ptr);
void* QWebEngineUrlSchemeHandler_MetaObjectDefault(void* ptr);
void* QWebEngineView_NewQWebEngineView(void* parent);
void QWebEngineView_Back(void* ptr);
void* QWebEngineView_CreateWindow(void* ptr, int ty);
void* QWebEngineView_CreateWindowDefault(void* ptr, int ty);
void QWebEngineView_Forward(void* ptr);
int QWebEngineView_HasSelection(void* ptr);
void* QWebEngineView_History(void* ptr);
void* QWebEngineView_IconUrl(void* ptr);
void QWebEngineView_Load(void* ptr, void* url);
void* QWebEngineView_Page(void* ptr);
void* QWebEngineView_PageAction(void* ptr, int action);
void QWebEngineView_Reload(void* ptr);
char* QWebEngineView_SelectedText(void* ptr);
void QWebEngineView_SetContent(void* ptr, char* data, char* mimeType, void* baseUrl);
void QWebEngineView_SetHtml(void* ptr, char* html, void* baseUrl);
void QWebEngineView_SetPage(void* ptr, void* page);
void QWebEngineView_SetUrl(void* ptr, void* url);
void QWebEngineView_SetZoomFactor(void* ptr, double factor);
void* QWebEngineView_Settings(void* ptr);
void QWebEngineView_Stop(void* ptr);
char* QWebEngineView_Title(void* ptr);
void QWebEngineView_TriggerPageAction(void* ptr, int action, int checked);
void* QWebEngineView_Url(void* ptr);
double QWebEngineView_ZoomFactor(void* ptr);
void QWebEngineView_DestroyQWebEngineView(void* ptr);
void QWebEngineView_ContextMenuEvent(void* ptr, void* event);
void QWebEngineView_ContextMenuEventDefault(void* ptr, void* event);
int QWebEngineView_Event(void* ptr, void* ev);
int QWebEngineView_EventDefault(void* ptr, void* ev);
void QWebEngineView_FindText(void* ptr, char* subString, int options);
void QWebEngineView_HideEvent(void* ptr, void* event);
void QWebEngineView_HideEventDefault(void* ptr, void* event);
void QWebEngineView_ConnectIconUrlChanged(void* ptr);
void QWebEngineView_DisconnectIconUrlChanged(void* ptr);
void QWebEngineView_IconUrlChanged(void* ptr, void* url);
void QWebEngineView_ConnectLoadFinished(void* ptr);
void QWebEngineView_DisconnectLoadFinished(void* ptr);
void QWebEngineView_LoadFinished(void* ptr, int ok);
void QWebEngineView_ConnectLoadProgress(void* ptr);
void QWebEngineView_DisconnectLoadProgress(void* ptr);
void QWebEngineView_LoadProgress(void* ptr, int progress);
void QWebEngineView_ConnectLoadStarted(void* ptr);
void QWebEngineView_DisconnectLoadStarted(void* ptr);
void QWebEngineView_LoadStarted(void* ptr);
void QWebEngineView_ConnectRenderProcessTerminated(void* ptr);
void QWebEngineView_DisconnectRenderProcessTerminated(void* ptr);
void QWebEngineView_RenderProcessTerminated(void* ptr, int terminationStatus, int exitCode);
void QWebEngineView_ConnectSelectionChanged(void* ptr);
void QWebEngineView_DisconnectSelectionChanged(void* ptr);
void QWebEngineView_SelectionChanged(void* ptr);
void QWebEngineView_ShowEvent(void* ptr, void* event);
void QWebEngineView_ShowEventDefault(void* ptr, void* event);
void* QWebEngineView_SizeHint(void* ptr);
void* QWebEngineView_SizeHintDefault(void* ptr);
void QWebEngineView_ConnectTitleChanged(void* ptr);
void QWebEngineView_DisconnectTitleChanged(void* ptr);
void QWebEngineView_TitleChanged(void* ptr, char* title);
void QWebEngineView_ConnectUrlChanged(void* ptr);
void QWebEngineView_DisconnectUrlChanged(void* ptr);
void QWebEngineView_UrlChanged(void* ptr, void* url);
void QWebEngineView_ActionEvent(void* ptr, void* event);
void QWebEngineView_ActionEventDefault(void* ptr, void* event);
void QWebEngineView_DragEnterEvent(void* ptr, void* event);
void QWebEngineView_DragEnterEventDefault(void* ptr, void* event);
void QWebEngineView_DragLeaveEvent(void* ptr, void* event);
void QWebEngineView_DragLeaveEventDefault(void* ptr, void* event);
void QWebEngineView_DragMoveEvent(void* ptr, void* event);
void QWebEngineView_DragMoveEventDefault(void* ptr, void* event);
void QWebEngineView_DropEvent(void* ptr, void* event);
void QWebEngineView_DropEventDefault(void* ptr, void* event);
void QWebEngineView_EnterEvent(void* ptr, void* event);
void QWebEngineView_EnterEventDefault(void* ptr, void* event);
void QWebEngineView_FocusInEvent(void* ptr, void* event);
void QWebEngineView_FocusInEventDefault(void* ptr, void* event);
void QWebEngineView_FocusOutEvent(void* ptr, void* event);
void QWebEngineView_FocusOutEventDefault(void* ptr, void* event);
void QWebEngineView_LeaveEvent(void* ptr, void* event);
void QWebEngineView_LeaveEventDefault(void* ptr, void* event);
void* QWebEngineView_MinimumSizeHint(void* ptr);
void* QWebEngineView_MinimumSizeHintDefault(void* ptr);
void QWebEngineView_MoveEvent(void* ptr, void* event);
void QWebEngineView_MoveEventDefault(void* ptr, void* event);
void QWebEngineView_PaintEvent(void* ptr, void* event);
void QWebEngineView_PaintEventDefault(void* ptr, void* event);
void QWebEngineView_SetEnabled(void* ptr, int vbo);
void QWebEngineView_SetEnabledDefault(void* ptr, int vbo);
void QWebEngineView_SetStyleSheet(void* ptr, char* styleSheet);
void QWebEngineView_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QWebEngineView_SetVisible(void* ptr, int visible);
void QWebEngineView_SetVisibleDefault(void* ptr, int visible);
void QWebEngineView_SetWindowModified(void* ptr, int vbo);
void QWebEngineView_SetWindowModifiedDefault(void* ptr, int vbo);
void QWebEngineView_SetWindowTitle(void* ptr, char* vqs);
void QWebEngineView_SetWindowTitleDefault(void* ptr, char* vqs);
void QWebEngineView_ChangeEvent(void* ptr, void* event);
void QWebEngineView_ChangeEventDefault(void* ptr, void* event);
int QWebEngineView_Close(void* ptr);
int QWebEngineView_CloseDefault(void* ptr);
void QWebEngineView_CloseEvent(void* ptr, void* event);
void QWebEngineView_CloseEventDefault(void* ptr, void* event);
int QWebEngineView_FocusNextPrevChild(void* ptr, int next);
int QWebEngineView_FocusNextPrevChildDefault(void* ptr, int next);
int QWebEngineView_HasHeightForWidth(void* ptr);
int QWebEngineView_HasHeightForWidthDefault(void* ptr);
int QWebEngineView_HeightForWidth(void* ptr, int w);
int QWebEngineView_HeightForWidthDefault(void* ptr, int w);
void QWebEngineView_Hide(void* ptr);
void QWebEngineView_HideDefault(void* ptr);
void QWebEngineView_InputMethodEvent(void* ptr, void* event);
void QWebEngineView_InputMethodEventDefault(void* ptr, void* event);
void* QWebEngineView_InputMethodQuery(void* ptr, int query);
void* QWebEngineView_InputMethodQueryDefault(void* ptr, int query);
void QWebEngineView_KeyPressEvent(void* ptr, void* event);
void QWebEngineView_KeyPressEventDefault(void* ptr, void* event);
void QWebEngineView_KeyReleaseEvent(void* ptr, void* event);
void QWebEngineView_KeyReleaseEventDefault(void* ptr, void* event);
void QWebEngineView_Lower(void* ptr);
void QWebEngineView_LowerDefault(void* ptr);
void QWebEngineView_MouseDoubleClickEvent(void* ptr, void* event);
void QWebEngineView_MouseDoubleClickEventDefault(void* ptr, void* event);
void QWebEngineView_MouseMoveEvent(void* ptr, void* event);
void QWebEngineView_MouseMoveEventDefault(void* ptr, void* event);
void QWebEngineView_MousePressEvent(void* ptr, void* event);
void QWebEngineView_MousePressEventDefault(void* ptr, void* event);
void QWebEngineView_MouseReleaseEvent(void* ptr, void* event);
void QWebEngineView_MouseReleaseEventDefault(void* ptr, void* event);
int QWebEngineView_NativeEvent(void* ptr, char* eventType, void* message, long result);
int QWebEngineView_NativeEventDefault(void* ptr, char* eventType, void* message, long result);
void QWebEngineView_Raise(void* ptr);
void QWebEngineView_RaiseDefault(void* ptr);
void QWebEngineView_Repaint(void* ptr);
void QWebEngineView_RepaintDefault(void* ptr);
void QWebEngineView_ResizeEvent(void* ptr, void* event);
void QWebEngineView_ResizeEventDefault(void* ptr, void* event);
void QWebEngineView_SetDisabled(void* ptr, int disable);
void QWebEngineView_SetDisabledDefault(void* ptr, int disable);
void QWebEngineView_SetFocus2(void* ptr);
void QWebEngineView_SetFocus2Default(void* ptr);
void QWebEngineView_SetHidden(void* ptr, int hidden);
void QWebEngineView_SetHiddenDefault(void* ptr, int hidden);
void QWebEngineView_Show(void* ptr);
void QWebEngineView_ShowDefault(void* ptr);
void QWebEngineView_ShowFullScreen(void* ptr);
void QWebEngineView_ShowFullScreenDefault(void* ptr);
void QWebEngineView_ShowMaximized(void* ptr);
void QWebEngineView_ShowMaximizedDefault(void* ptr);
void QWebEngineView_ShowMinimized(void* ptr);
void QWebEngineView_ShowMinimizedDefault(void* ptr);
void QWebEngineView_ShowNormal(void* ptr);
void QWebEngineView_ShowNormalDefault(void* ptr);
void QWebEngineView_TabletEvent(void* ptr, void* event);
void QWebEngineView_TabletEventDefault(void* ptr, void* event);
void QWebEngineView_Update(void* ptr);
void QWebEngineView_UpdateDefault(void* ptr);
void QWebEngineView_UpdateMicroFocus(void* ptr);
void QWebEngineView_UpdateMicroFocusDefault(void* ptr);
void QWebEngineView_WheelEvent(void* ptr, void* event);
void QWebEngineView_WheelEventDefault(void* ptr, void* event);
void QWebEngineView_TimerEvent(void* ptr, void* event);
void QWebEngineView_TimerEventDefault(void* ptr, void* event);
void QWebEngineView_ChildEvent(void* ptr, void* event);
void QWebEngineView_ChildEventDefault(void* ptr, void* event);
void QWebEngineView_ConnectNotify(void* ptr, void* sign);
void QWebEngineView_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineView_CustomEvent(void* ptr, void* event);
void QWebEngineView_CustomEventDefault(void* ptr, void* event);
void QWebEngineView_DeleteLater(void* ptr);
void QWebEngineView_DeleteLaterDefault(void* ptr);
void QWebEngineView_DisconnectNotify(void* ptr, void* sign);
void QWebEngineView_DisconnectNotifyDefault(void* ptr, void* sign);
int QWebEngineView_EventFilter(void* ptr, void* watched, void* event);
int QWebEngineView_EventFilterDefault(void* ptr, void* watched, void* event);
void* QWebEngineView_MetaObject(void* ptr);
void* QWebEngineView_MetaObjectDefault(void* ptr);

#ifdef __cplusplus
}
#endif

#endif