// +build !minimal

#pragma once

#ifndef GO_QTWEBENGINE_H
#define GO_QTWEBENGINE_H

#include <stdint.h>

#ifdef __cplusplus
int QQuickWebEngineProfile_QQuickWebEngineProfile_QRegisterMetaType();
int QQuickWebEngineScript_QQuickWebEngineScript_QRegisterMetaType();
int QWebEngineCookieStore_QWebEngineCookieStore_QRegisterMetaType();
int QWebEngineNotification_QWebEngineNotification_QRegisterMetaType();
int QWebEnginePage_QWebEnginePage_QRegisterMetaType();
int QWebEngineProfile_QWebEngineProfile_QRegisterMetaType();
int QWebEngineUrlRequestInterceptor_QWebEngineUrlRequestInterceptor_QRegisterMetaType();
int QWebEngineUrlRequestJob_QWebEngineUrlRequestJob_QRegisterMetaType();
int QWebEngineUrlSchemeHandler_QWebEngineUrlSchemeHandler_QRegisterMetaType();
int QWebEngineView_QWebEngineView_QRegisterMetaType();
extern "C" {
#endif

struct QtWebEngine_PackedString { char* data; long long len; };
struct QtWebEngine_PackedList { void* data; long long len; };
void* QQuickWebEngineProfile_NewQQuickWebEngineProfile(void* parent);
struct QtWebEngine_PackedString QQuickWebEngineProfile_CachePath(void* ptr);
void QQuickWebEngineProfile_ConnectCachePathChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectCachePathChanged(void* ptr);
void QQuickWebEngineProfile_CachePathChanged(void* ptr);
void QQuickWebEngineProfile_ClearHttpCache(void* ptr);
void* QQuickWebEngineProfile_ClientCertificateStore(void* ptr);
void* QQuickWebEngineProfile_CookieStore(void* ptr);
void* QQuickWebEngineProfile_QQuickWebEngineProfile_DefaultProfile();
struct QtWebEngine_PackedString QQuickWebEngineProfile_DownloadPath(void* ptr);
void QQuickWebEngineProfile_ConnectDownloadPathChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectDownloadPathChanged(void* ptr);
void QQuickWebEngineProfile_DownloadPathChanged(void* ptr);
struct QtWebEngine_PackedString QQuickWebEngineProfile_HttpAcceptLanguage(void* ptr);
void QQuickWebEngineProfile_ConnectHttpAcceptLanguageChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpAcceptLanguageChanged(void* ptr);
void QQuickWebEngineProfile_HttpAcceptLanguageChanged(void* ptr);
int QQuickWebEngineProfile_HttpCacheMaximumSize(void* ptr);
void QQuickWebEngineProfile_ConnectHttpCacheMaximumSizeChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpCacheMaximumSizeChanged(void* ptr);
void QQuickWebEngineProfile_HttpCacheMaximumSizeChanged(void* ptr);
long long QQuickWebEngineProfile_HttpCacheType(void* ptr);
void QQuickWebEngineProfile_ConnectHttpCacheTypeChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpCacheTypeChanged(void* ptr);
void QQuickWebEngineProfile_HttpCacheTypeChanged(void* ptr);
struct QtWebEngine_PackedString QQuickWebEngineProfile_HttpUserAgent(void* ptr);
void QQuickWebEngineProfile_ConnectHttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectHttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_HttpUserAgentChanged(void* ptr);
void QQuickWebEngineProfile_InstallUrlSchemeHandler(void* ptr, void* scheme, void* handler);
char QQuickWebEngineProfile_IsOffTheRecord(void* ptr);
char QQuickWebEngineProfile_IsSpellCheckEnabled(void* ptr);
char QQuickWebEngineProfile_IsUsedForGlobalCertificateVerification(void* ptr);
void QQuickWebEngineProfile_ConnectOffTheRecordChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectOffTheRecordChanged(void* ptr);
void QQuickWebEngineProfile_OffTheRecordChanged(void* ptr);
long long QQuickWebEngineProfile_PersistentCookiesPolicy(void* ptr);
void QQuickWebEngineProfile_ConnectPersistentCookiesPolicyChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectPersistentCookiesPolicyChanged(void* ptr);
void QQuickWebEngineProfile_PersistentCookiesPolicyChanged(void* ptr);
struct QtWebEngine_PackedString QQuickWebEngineProfile_PersistentStoragePath(void* ptr);
void QQuickWebEngineProfile_ConnectPersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectPersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_PersistentStoragePathChanged(void* ptr);
void QQuickWebEngineProfile_ConnectPresentNotification(void* ptr);
void QQuickWebEngineProfile_DisconnectPresentNotification(void* ptr);
void QQuickWebEngineProfile_PresentNotification(void* ptr, void* notification);
void QQuickWebEngineProfile_RemoveAllUrlSchemeHandlers(void* ptr);
void QQuickWebEngineProfile_RemoveUrlScheme(void* ptr, void* scheme);
void QQuickWebEngineProfile_RemoveUrlSchemeHandler(void* ptr, void* handler);
void QQuickWebEngineProfile_SetCachePath(void* ptr, struct QtWebEngine_PackedString path);
void QQuickWebEngineProfile_SetDownloadPath(void* ptr, struct QtWebEngine_PackedString path);
void QQuickWebEngineProfile_SetHttpAcceptLanguage(void* ptr, struct QtWebEngine_PackedString httpAcceptLanguage);
void QQuickWebEngineProfile_SetHttpCacheMaximumSize(void* ptr, int maxSize);
void QQuickWebEngineProfile_SetHttpCacheType(void* ptr, long long vqq);
void QQuickWebEngineProfile_SetHttpUserAgent(void* ptr, struct QtWebEngine_PackedString userAgent);
void QQuickWebEngineProfile_SetOffTheRecord(void* ptr, char offTheRecord);
void QQuickWebEngineProfile_SetPersistentCookiesPolicy(void* ptr, long long vqq);
void QQuickWebEngineProfile_SetPersistentStoragePath(void* ptr, struct QtWebEngine_PackedString path);
void QQuickWebEngineProfile_SetSpellCheckEnabled(void* ptr, char enabled);
void QQuickWebEngineProfile_SetSpellCheckLanguages(void* ptr, struct QtWebEngine_PackedString languages);
void QQuickWebEngineProfile_SetStorageName(void* ptr, struct QtWebEngine_PackedString name);
void QQuickWebEngineProfile_SetUrlRequestInterceptor(void* ptr, void* interceptor);
void QQuickWebEngineProfile_SetUseForGlobalCertificateVerification(void* ptr, char b);
void QQuickWebEngineProfile_ConnectSpellCheckEnabledChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectSpellCheckEnabledChanged(void* ptr);
void QQuickWebEngineProfile_SpellCheckEnabledChanged(void* ptr);
struct QtWebEngine_PackedString QQuickWebEngineProfile_SpellCheckLanguages(void* ptr);
void QQuickWebEngineProfile_ConnectSpellCheckLanguagesChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectSpellCheckLanguagesChanged(void* ptr);
void QQuickWebEngineProfile_SpellCheckLanguagesChanged(void* ptr);
struct QtWebEngine_PackedString QQuickWebEngineProfile_StorageName(void* ptr);
void QQuickWebEngineProfile_ConnectStorageNameChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectStorageNameChanged(void* ptr);
void QQuickWebEngineProfile_StorageNameChanged(void* ptr);
void* QQuickWebEngineProfile_UrlSchemeHandler(void* ptr, void* scheme);
void QQuickWebEngineProfile_ConnectUseForGlobalCertificateVerificationChanged(void* ptr);
void QQuickWebEngineProfile_DisconnectUseForGlobalCertificateVerificationChanged(void* ptr);
void QQuickWebEngineProfile_UseForGlobalCertificateVerificationChanged(void* ptr);
void* QQuickWebEngineProfile___children_atList(void* ptr, int i);
void QQuickWebEngineProfile___children_setList(void* ptr, void* i);
void* QQuickWebEngineProfile___children_newList(void* ptr);
void* QQuickWebEngineProfile___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickWebEngineProfile___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickWebEngineProfile___dynamicPropertyNames_newList(void* ptr);
void* QQuickWebEngineProfile___findChildren_atList(void* ptr, int i);
void QQuickWebEngineProfile___findChildren_setList(void* ptr, void* i);
void* QQuickWebEngineProfile___findChildren_newList(void* ptr);
void* QQuickWebEngineProfile___findChildren_atList3(void* ptr, int i);
void QQuickWebEngineProfile___findChildren_setList3(void* ptr, void* i);
void* QQuickWebEngineProfile___findChildren_newList3(void* ptr);
void* QQuickWebEngineProfile___qFindChildren_atList2(void* ptr, int i);
void QQuickWebEngineProfile___qFindChildren_setList2(void* ptr, void* i);
void* QQuickWebEngineProfile___qFindChildren_newList2(void* ptr);
void QQuickWebEngineProfile_ChildEventDefault(void* ptr, void* event);
void QQuickWebEngineProfile_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickWebEngineProfile_CustomEventDefault(void* ptr, void* event);
void QQuickWebEngineProfile_DeleteLaterDefault(void* ptr);
void QQuickWebEngineProfile_DisconnectNotifyDefault(void* ptr, void* sign);
char QQuickWebEngineProfile_EventDefault(void* ptr, void* e);
char QQuickWebEngineProfile_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickWebEngineProfile_TimerEventDefault(void* ptr, void* event);
void* QQuickWebEngineScript_NewQQuickWebEngineScript(void* parent);
long long QQuickWebEngineScript_InjectionPoint(void* ptr);
void QQuickWebEngineScript_ConnectInjectionPointChanged(void* ptr);
void QQuickWebEngineScript_DisconnectInjectionPointChanged(void* ptr);
void QQuickWebEngineScript_InjectionPointChanged(void* ptr, long long injectionPoint);
struct QtWebEngine_PackedString QQuickWebEngineScript_Name(void* ptr);
void QQuickWebEngineScript_ConnectNameChanged(void* ptr);
void QQuickWebEngineScript_DisconnectNameChanged(void* ptr);
void QQuickWebEngineScript_NameChanged(void* ptr, struct QtWebEngine_PackedString name);
char QQuickWebEngineScript_RunOnSubframes(void* ptr);
void QQuickWebEngineScript_ConnectRunOnSubframesChanged(void* ptr);
void QQuickWebEngineScript_DisconnectRunOnSubframesChanged(void* ptr);
void QQuickWebEngineScript_RunOnSubframesChanged(void* ptr, char on);
void QQuickWebEngineScript_SetInjectionPoint(void* ptr, long long injectionPoint);
void QQuickWebEngineScript_SetName(void* ptr, struct QtWebEngine_PackedString name);
void QQuickWebEngineScript_SetRunOnSubframes(void* ptr, char on);
void QQuickWebEngineScript_SetSourceCode(void* ptr, struct QtWebEngine_PackedString code);
void QQuickWebEngineScript_SetSourceUrl(void* ptr, void* url);
void QQuickWebEngineScript_SetWorldId(void* ptr, long long scriptWorldId);
struct QtWebEngine_PackedString QQuickWebEngineScript_SourceCode(void* ptr);
void QQuickWebEngineScript_ConnectSourceCodeChanged(void* ptr);
void QQuickWebEngineScript_DisconnectSourceCodeChanged(void* ptr);
void QQuickWebEngineScript_SourceCodeChanged(void* ptr, struct QtWebEngine_PackedString code);
void* QQuickWebEngineScript_SourceUrl(void* ptr);
void QQuickWebEngineScript_ConnectSourceUrlChanged(void* ptr);
void QQuickWebEngineScript_DisconnectSourceUrlChanged(void* ptr);
void QQuickWebEngineScript_SourceUrlChanged(void* ptr, void* url);
struct QtWebEngine_PackedString QQuickWebEngineScript_ToString(void* ptr);
long long QQuickWebEngineScript_WorldId(void* ptr);
void QQuickWebEngineScript_ConnectWorldIdChanged(void* ptr);
void QQuickWebEngineScript_DisconnectWorldIdChanged(void* ptr);
void QQuickWebEngineScript_WorldIdChanged(void* ptr, long long scriptWorldId);
void* QQuickWebEngineScript___children_atList(void* ptr, int i);
void QQuickWebEngineScript___children_setList(void* ptr, void* i);
void* QQuickWebEngineScript___children_newList(void* ptr);
void* QQuickWebEngineScript___dynamicPropertyNames_atList(void* ptr, int i);
void QQuickWebEngineScript___dynamicPropertyNames_setList(void* ptr, void* i);
void* QQuickWebEngineScript___dynamicPropertyNames_newList(void* ptr);
void* QQuickWebEngineScript___findChildren_atList(void* ptr, int i);
void QQuickWebEngineScript___findChildren_setList(void* ptr, void* i);
void* QQuickWebEngineScript___findChildren_newList(void* ptr);
void* QQuickWebEngineScript___findChildren_atList3(void* ptr, int i);
void QQuickWebEngineScript___findChildren_setList3(void* ptr, void* i);
void* QQuickWebEngineScript___findChildren_newList3(void* ptr);
void* QQuickWebEngineScript___qFindChildren_atList2(void* ptr, int i);
void QQuickWebEngineScript___qFindChildren_setList2(void* ptr, void* i);
void* QQuickWebEngineScript___qFindChildren_newList2(void* ptr);
void QQuickWebEngineScript_ChildEventDefault(void* ptr, void* event);
void QQuickWebEngineScript_ConnectNotifyDefault(void* ptr, void* sign);
void QQuickWebEngineScript_CustomEventDefault(void* ptr, void* event);
void QQuickWebEngineScript_DeleteLaterDefault(void* ptr);
void QQuickWebEngineScript_DisconnectNotifyDefault(void* ptr, void* sign);
char QQuickWebEngineScript_EventDefault(void* ptr, void* e);
char QQuickWebEngineScript_EventFilterDefault(void* ptr, void* watched, void* event);
void QQuickWebEngineScript_TimerEventDefault(void* ptr, void* event);
long long QWebEngineCertificateError_Error(void* ptr);
struct QtWebEngine_PackedString QWebEngineCertificateError_ErrorDescription(void* ptr);
char QWebEngineCertificateError_IsOverridable(void* ptr);
void* QWebEngineCertificateError_Url(void* ptr);
void QWebEngineClientCertificateStore_Add(void* ptr, void* certificate, void* privateKey);
struct QtWebEngine_PackedList QWebEngineClientCertificateStore_Certificates(void* ptr);
void QWebEngineClientCertificateStore_Clear(void* ptr);
void QWebEngineClientCertificateStore_Remove(void* ptr, void* certificate);
void* QWebEngineClientCertificateStore___certificates_atList(void* ptr, int i);
void QWebEngineClientCertificateStore___certificates_setList(void* ptr, void* i);
void* QWebEngineClientCertificateStore___certificates_newList(void* ptr);
void QWebEngineCookieStore_ConnectCookieAdded(void* ptr);
void QWebEngineCookieStore_DisconnectCookieAdded(void* ptr);
void QWebEngineCookieStore_CookieAdded(void* ptr, void* cookie);
void QWebEngineCookieStore_ConnectCookieRemoved(void* ptr);
void QWebEngineCookieStore_DisconnectCookieRemoved(void* ptr);
void QWebEngineCookieStore_CookieRemoved(void* ptr, void* cookie);
void QWebEngineCookieStore_DeleteAllCookies(void* ptr);
void QWebEngineCookieStore_DeleteCookie(void* ptr, void* cookie, void* origin);
void QWebEngineCookieStore_DeleteSessionCookies(void* ptr);
void QWebEngineCookieStore_LoadAllCookies(void* ptr);
void QWebEngineCookieStore_SetCookie(void* ptr, void* cookie, void* origin);
void QWebEngineCookieStore_DestroyQWebEngineCookieStore(void* ptr);
void QWebEngineCookieStore_DestroyQWebEngineCookieStoreDefault(void* ptr);
void* QWebEngineCookieStore___children_atList(void* ptr, int i);
void QWebEngineCookieStore___children_setList(void* ptr, void* i);
void* QWebEngineCookieStore___children_newList(void* ptr);
void* QWebEngineCookieStore___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineCookieStore___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineCookieStore___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineCookieStore___findChildren_atList(void* ptr, int i);
void QWebEngineCookieStore___findChildren_setList(void* ptr, void* i);
void* QWebEngineCookieStore___findChildren_newList(void* ptr);
void* QWebEngineCookieStore___findChildren_atList3(void* ptr, int i);
void QWebEngineCookieStore___findChildren_setList3(void* ptr, void* i);
void* QWebEngineCookieStore___findChildren_newList3(void* ptr);
void* QWebEngineCookieStore___qFindChildren_atList2(void* ptr, int i);
void QWebEngineCookieStore___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineCookieStore___qFindChildren_newList2(void* ptr);
void QWebEngineCookieStore_ChildEventDefault(void* ptr, void* event);
void QWebEngineCookieStore_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineCookieStore_CustomEventDefault(void* ptr, void* event);
void QWebEngineCookieStore_DeleteLaterDefault(void* ptr);
void QWebEngineCookieStore_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineCookieStore_EventDefault(void* ptr, void* e);
char QWebEngineCookieStore_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineCookieStore_TimerEventDefault(void* ptr, void* event);
void* QWebEngineHttpRequest_NewQWebEngineHttpRequest(void* url, long long method);
void* QWebEngineHttpRequest_NewQWebEngineHttpRequest2(void* other);
char QWebEngineHttpRequest_HasHeader(void* ptr, void* headerName);
void* QWebEngineHttpRequest_Header(void* ptr, void* headerName);
struct QtWebEngine_PackedList QWebEngineHttpRequest_Headers(void* ptr);
long long QWebEngineHttpRequest_Method(void* ptr);
void* QWebEngineHttpRequest_PostData(void* ptr);
void* QWebEngineHttpRequest_QWebEngineHttpRequest_PostRequest(void* url, void* postData);
void QWebEngineHttpRequest_SetHeader(void* ptr, void* headerName, void* headerValue);
void QWebEngineHttpRequest_SetMethod(void* ptr, long long method);
void QWebEngineHttpRequest_SetPostData(void* ptr, void* postData);
void QWebEngineHttpRequest_SetUrl(void* ptr, void* url);
void QWebEngineHttpRequest_Swap(void* ptr, void* other);
void QWebEngineHttpRequest_UnsetHeader(void* ptr, void* key);
void* QWebEngineHttpRequest_Url(void* ptr);
void QWebEngineHttpRequest_DestroyQWebEngineHttpRequest(void* ptr);
void* QWebEngineHttpRequest___headers_atList(void* ptr, int i);
void QWebEngineHttpRequest___headers_setList(void* ptr, void* i);
void* QWebEngineHttpRequest___headers_newList(void* ptr);
struct QtWebEngine_PackedString QWebEngineHttpRequest___postRequest_postData_atList(void* ptr, struct QtWebEngine_PackedString v, int i);
void QWebEngineHttpRequest___postRequest_postData_setList(void* ptr, struct QtWebEngine_PackedString key, struct QtWebEngine_PackedString i);
void* QWebEngineHttpRequest___postRequest_postData_newList(void* ptr);
struct QtWebEngine_PackedList QWebEngineHttpRequest___postRequest_postData_keyList(void* ptr);
struct QtWebEngine_PackedString QWebEngineHttpRequest_____postRequest_postData_keyList_atList(void* ptr, int i);
void QWebEngineHttpRequest_____postRequest_postData_keyList_setList(void* ptr, struct QtWebEngine_PackedString i);
void* QWebEngineHttpRequest_____postRequest_postData_keyList_newList(void* ptr);
void QWebEngineNotification_Click(void* ptr);
void QWebEngineNotification_ClickDefault(void* ptr);
void QWebEngineNotification_Close(void* ptr);
void QWebEngineNotification_CloseDefault(void* ptr);
void QWebEngineNotification_ConnectClosed(void* ptr);
void QWebEngineNotification_DisconnectClosed(void* ptr);
void QWebEngineNotification_Closed(void* ptr);
long long QWebEngineNotification_Direction(void* ptr);
void* QWebEngineNotification_Icon(void* ptr);
struct QtWebEngine_PackedString QWebEngineNotification_Language(void* ptr);
char QWebEngineNotification_Matches(void* ptr, void* other);
struct QtWebEngine_PackedString QWebEngineNotification_Message(void* ptr);
void* QWebEngineNotification_Origin(void* ptr);
void QWebEngineNotification_Show(void* ptr);
void QWebEngineNotification_ShowDefault(void* ptr);
struct QtWebEngine_PackedString QWebEngineNotification_Tag(void* ptr);
struct QtWebEngine_PackedString QWebEngineNotification_Title(void* ptr);
void* QWebEngineNotification___children_atList(void* ptr, int i);
void QWebEngineNotification___children_setList(void* ptr, void* i);
void* QWebEngineNotification___children_newList(void* ptr);
void* QWebEngineNotification___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineNotification___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineNotification___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineNotification___findChildren_atList(void* ptr, int i);
void QWebEngineNotification___findChildren_setList(void* ptr, void* i);
void* QWebEngineNotification___findChildren_newList(void* ptr);
void* QWebEngineNotification___findChildren_atList3(void* ptr, int i);
void QWebEngineNotification___findChildren_setList3(void* ptr, void* i);
void* QWebEngineNotification___findChildren_newList3(void* ptr);
void* QWebEngineNotification___qFindChildren_atList2(void* ptr, int i);
void QWebEngineNotification___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineNotification___qFindChildren_newList2(void* ptr);
void QWebEngineNotification_ChildEventDefault(void* ptr, void* event);
void QWebEngineNotification_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineNotification_CustomEventDefault(void* ptr, void* event);
void QWebEngineNotification_DeleteLaterDefault(void* ptr);
void QWebEngineNotification_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineNotification_EventDefault(void* ptr, void* e);
char QWebEngineNotification_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineNotification_TimerEventDefault(void* ptr, void* event);
void QWebEnginePage_ConnectAudioMutedChanged(void* ptr);
void QWebEnginePage_DisconnectAudioMutedChanged(void* ptr);
void QWebEnginePage_AudioMutedChanged(void* ptr, char muted);
void* QWebEnginePage_BackgroundColor(void* ptr);
void* QWebEnginePage_ContentsSize(void* ptr);
void QWebEnginePage_ConnectContentsSizeChanged(void* ptr);
void QWebEnginePage_DisconnectContentsSizeChanged(void* ptr);
void QWebEnginePage_ContentsSizeChanged(void* ptr, void* size);
char QWebEnginePage_HasSelection(void* ptr);
void* QWebEnginePage_Icon(void* ptr);
void QWebEnginePage_ConnectIconChanged(void* ptr);
void QWebEnginePage_DisconnectIconChanged(void* ptr);
void QWebEnginePage_IconChanged(void* ptr, void* icon);
void* QWebEnginePage_IconUrl(void* ptr);
void QWebEnginePage_ConnectIconUrlChanged(void* ptr);
void QWebEnginePage_DisconnectIconUrlChanged(void* ptr);
void QWebEnginePage_IconUrlChanged(void* ptr, void* url);
char QWebEnginePage_IsAudioMuted(void* ptr);
char QWebEnginePage_RecentlyAudible(void* ptr);
void QWebEnginePage_ConnectRecentlyAudibleChanged(void* ptr);
void QWebEnginePage_DisconnectRecentlyAudibleChanged(void* ptr);
void QWebEnginePage_RecentlyAudibleChanged(void* ptr, char recentlyAudible);
void* QWebEnginePage_RequestedUrl(void* ptr);
void* QWebEnginePage_ScrollPosition(void* ptr);
void QWebEnginePage_ConnectScrollPositionChanged(void* ptr);
void QWebEnginePage_DisconnectScrollPositionChanged(void* ptr);
void QWebEnginePage_ScrollPositionChanged(void* ptr, void* position);
struct QtWebEngine_PackedString QWebEnginePage_SelectedText(void* ptr);
void QWebEnginePage_SetAudioMuted(void* ptr, char muted);
void QWebEnginePage_SetBackgroundColor(void* ptr, void* color);
void QWebEnginePage_SetUrl(void* ptr, void* url);
void QWebEnginePage_SetZoomFactor(void* ptr, double factor);
struct QtWebEngine_PackedString QWebEnginePage_Title(void* ptr);
void* QWebEnginePage_Url(void* ptr);
double QWebEnginePage_ZoomFactor(void* ptr);
void* QWebEnginePage___children_atList(void* ptr, int i);
void QWebEnginePage___children_setList(void* ptr, void* i);
void* QWebEnginePage___children_newList(void* ptr);
void* QWebEnginePage___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEnginePage___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEnginePage___dynamicPropertyNames_newList(void* ptr);
void* QWebEnginePage___findChildren_atList(void* ptr, int i);
void QWebEnginePage___findChildren_setList(void* ptr, void* i);
void* QWebEnginePage___findChildren_newList(void* ptr);
void* QWebEnginePage___findChildren_atList3(void* ptr, int i);
void QWebEnginePage___findChildren_setList3(void* ptr, void* i);
void* QWebEnginePage___findChildren_newList3(void* ptr);
void* QWebEnginePage___qFindChildren_atList2(void* ptr, int i);
void QWebEnginePage___qFindChildren_setList2(void* ptr, void* i);
void* QWebEnginePage___qFindChildren_newList2(void* ptr);
void QWebEnginePage_ChildEventDefault(void* ptr, void* event);
void QWebEnginePage_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEnginePage_CustomEventDefault(void* ptr, void* event);
void QWebEnginePage_DeleteLaterDefault(void* ptr);
void QWebEnginePage_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEnginePage_EventDefault(void* ptr, void* e);
char QWebEnginePage_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEnginePage_TimerEventDefault(void* ptr, void* event);
void* QWebEngineProfile___clearVisitedLinks_urls_atList(void* ptr, int i);
void QWebEngineProfile___clearVisitedLinks_urls_setList(void* ptr, void* i);
void* QWebEngineProfile___clearVisitedLinks_urls_newList(void* ptr);
void* QWebEngineProfile___children_atList(void* ptr, int i);
void QWebEngineProfile___children_setList(void* ptr, void* i);
void* QWebEngineProfile___children_newList(void* ptr);
void* QWebEngineProfile___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineProfile___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineProfile___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineProfile___findChildren_atList(void* ptr, int i);
void QWebEngineProfile___findChildren_setList(void* ptr, void* i);
void* QWebEngineProfile___findChildren_newList(void* ptr);
void* QWebEngineProfile___findChildren_atList3(void* ptr, int i);
void QWebEngineProfile___findChildren_setList3(void* ptr, void* i);
void* QWebEngineProfile___findChildren_newList3(void* ptr);
void* QWebEngineProfile___qFindChildren_atList2(void* ptr, int i);
void QWebEngineProfile___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineProfile___qFindChildren_newList2(void* ptr);
void QWebEngineProfile_ChildEventDefault(void* ptr, void* event);
void QWebEngineProfile_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineProfile_CustomEventDefault(void* ptr, void* event);
void QWebEngineProfile_DeleteLaterDefault(void* ptr);
void QWebEngineProfile_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineProfile_EventDefault(void* ptr, void* e);
char QWebEngineProfile_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineProfile_TimerEventDefault(void* ptr, void* event);
void QWebEngineQuotaRequest_Accept(void* ptr);
void* QWebEngineQuotaRequest_Origin(void* ptr);
void QWebEngineQuotaRequest_Reject(void* ptr);
long long QWebEngineQuotaRequest_RequestedSize(void* ptr);
void QWebEngineRegisterProtocolHandlerRequest_Accept(void* ptr);
void* QWebEngineRegisterProtocolHandlerRequest_Origin(void* ptr);
void QWebEngineRegisterProtocolHandlerRequest_Reject(void* ptr);
struct QtWebEngine_PackedString QWebEngineRegisterProtocolHandlerRequest_Scheme(void* ptr);
void QWebEngineUrlRequestInfo_Block(void* ptr, char shouldBlock);
void* QWebEngineUrlRequestInfo_FirstPartyUrl(void* ptr);
long long QWebEngineUrlRequestInfo_NavigationType(void* ptr);
void QWebEngineUrlRequestInfo_Redirect(void* ptr, void* url);
void* QWebEngineUrlRequestInfo_RequestMethod(void* ptr);
void* QWebEngineUrlRequestInfo_RequestUrl(void* ptr);
long long QWebEngineUrlRequestInfo_ResourceType(void* ptr);
void QWebEngineUrlRequestInfo_SetHttpHeader(void* ptr, void* name, void* value);
void* QWebEngineUrlRequestInterceptor_NewQWebEngineUrlRequestInterceptor2(void* p);
void QWebEngineUrlRequestInterceptor_InterceptRequest(void* ptr, void* info);
void* QWebEngineUrlRequestInterceptor___children_atList(void* ptr, int i);
void QWebEngineUrlRequestInterceptor___children_setList(void* ptr, void* i);
void* QWebEngineUrlRequestInterceptor___children_newList(void* ptr);
void* QWebEngineUrlRequestInterceptor___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineUrlRequestInterceptor___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineUrlRequestInterceptor___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineUrlRequestInterceptor___findChildren_atList(void* ptr, int i);
void QWebEngineUrlRequestInterceptor___findChildren_setList(void* ptr, void* i);
void* QWebEngineUrlRequestInterceptor___findChildren_newList(void* ptr);
void* QWebEngineUrlRequestInterceptor___findChildren_atList3(void* ptr, int i);
void QWebEngineUrlRequestInterceptor___findChildren_setList3(void* ptr, void* i);
void* QWebEngineUrlRequestInterceptor___findChildren_newList3(void* ptr);
void* QWebEngineUrlRequestInterceptor___qFindChildren_atList2(void* ptr, int i);
void QWebEngineUrlRequestInterceptor___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineUrlRequestInterceptor___qFindChildren_newList2(void* ptr);
void QWebEngineUrlRequestInterceptor_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlRequestInterceptor_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestInterceptor_DeleteLaterDefault(void* ptr);
void QWebEngineUrlRequestInterceptor_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineUrlRequestInterceptor_EventDefault(void* ptr, void* e);
char QWebEngineUrlRequestInterceptor_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineUrlRequestInterceptor_TimerEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_Fail(void* ptr, long long r);
void* QWebEngineUrlRequestJob_Initiator(void* ptr);
void QWebEngineUrlRequestJob_Redirect(void* ptr, void* url);
void QWebEngineUrlRequestJob_Reply(void* ptr, void* contentType, void* device);
struct QtWebEngine_PackedList QWebEngineUrlRequestJob_RequestHeaders(void* ptr);
void* QWebEngineUrlRequestJob_RequestMethod(void* ptr);
void* QWebEngineUrlRequestJob_RequestUrl(void* ptr);
void* QWebEngineUrlRequestJob___requestHeaders_atList(void* ptr, void* v, int i);
void QWebEngineUrlRequestJob___requestHeaders_setList(void* ptr, void* key, void* i);
void* QWebEngineUrlRequestJob___requestHeaders_newList(void* ptr);
struct QtWebEngine_PackedList QWebEngineUrlRequestJob___requestHeaders_keyList(void* ptr);
void* QWebEngineUrlRequestJob_____requestHeaders_keyList_atList(void* ptr, int i);
void QWebEngineUrlRequestJob_____requestHeaders_keyList_setList(void* ptr, void* i);
void* QWebEngineUrlRequestJob_____requestHeaders_keyList_newList(void* ptr);
void* QWebEngineUrlRequestJob___children_atList(void* ptr, int i);
void QWebEngineUrlRequestJob___children_setList(void* ptr, void* i);
void* QWebEngineUrlRequestJob___children_newList(void* ptr);
void* QWebEngineUrlRequestJob___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineUrlRequestJob___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineUrlRequestJob___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineUrlRequestJob___findChildren_atList(void* ptr, int i);
void QWebEngineUrlRequestJob___findChildren_setList(void* ptr, void* i);
void* QWebEngineUrlRequestJob___findChildren_newList(void* ptr);
void* QWebEngineUrlRequestJob___findChildren_atList3(void* ptr, int i);
void QWebEngineUrlRequestJob___findChildren_setList3(void* ptr, void* i);
void* QWebEngineUrlRequestJob___findChildren_newList3(void* ptr);
void* QWebEngineUrlRequestJob___qFindChildren_atList2(void* ptr, int i);
void QWebEngineUrlRequestJob___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineUrlRequestJob___qFindChildren_newList2(void* ptr);
void QWebEngineUrlRequestJob_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlRequestJob_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlRequestJob_DeleteLaterDefault(void* ptr);
void QWebEngineUrlRequestJob_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineUrlRequestJob_EventDefault(void* ptr, void* e);
char QWebEngineUrlRequestJob_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineUrlRequestJob_TimerEventDefault(void* ptr, void* event);
void* QWebEngineUrlScheme_NewQWebEngineUrlScheme();
void* QWebEngineUrlScheme_NewQWebEngineUrlScheme2(void* name);
void* QWebEngineUrlScheme_NewQWebEngineUrlScheme3(void* that);
void* QWebEngineUrlScheme_NewQWebEngineUrlScheme4(void* that);
int QWebEngineUrlScheme_DefaultPort(void* ptr);
long long QWebEngineUrlScheme_Flags(void* ptr);
void* QWebEngineUrlScheme_Name(void* ptr);
void QWebEngineUrlScheme_QWebEngineUrlScheme_RegisterScheme(void* scheme);
void* QWebEngineUrlScheme_QWebEngineUrlScheme_SchemeByName(void* name);
void QWebEngineUrlScheme_SetDefaultPort(void* ptr, int newValue);
void QWebEngineUrlScheme_SetFlags(void* ptr, long long newValue);
void QWebEngineUrlScheme_SetName(void* ptr, void* newValue);
void QWebEngineUrlScheme_SetSyntax(void* ptr, long long newValue);
void QWebEngineUrlScheme_DestroyQWebEngineUrlScheme(void* ptr);
void* QWebEngineUrlSchemeHandler_NewQWebEngineUrlSchemeHandler(void* parent);
void QWebEngineUrlSchemeHandler_RequestStarted(void* ptr, void* request);
void QWebEngineUrlSchemeHandler_DestroyQWebEngineUrlSchemeHandler(void* ptr);
void QWebEngineUrlSchemeHandler_DestroyQWebEngineUrlSchemeHandlerDefault(void* ptr);
void* QWebEngineUrlSchemeHandler___children_atList(void* ptr, int i);
void QWebEngineUrlSchemeHandler___children_setList(void* ptr, void* i);
void* QWebEngineUrlSchemeHandler___children_newList(void* ptr);
void* QWebEngineUrlSchemeHandler___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineUrlSchemeHandler___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineUrlSchemeHandler___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineUrlSchemeHandler___findChildren_atList(void* ptr, int i);
void QWebEngineUrlSchemeHandler___findChildren_setList(void* ptr, void* i);
void* QWebEngineUrlSchemeHandler___findChildren_newList(void* ptr);
void* QWebEngineUrlSchemeHandler___findChildren_atList3(void* ptr, int i);
void QWebEngineUrlSchemeHandler___findChildren_setList3(void* ptr, void* i);
void* QWebEngineUrlSchemeHandler___findChildren_newList3(void* ptr);
void* QWebEngineUrlSchemeHandler___qFindChildren_atList2(void* ptr, int i);
void QWebEngineUrlSchemeHandler___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineUrlSchemeHandler___qFindChildren_newList2(void* ptr);
void QWebEngineUrlSchemeHandler_ChildEventDefault(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineUrlSchemeHandler_CustomEventDefault(void* ptr, void* event);
void QWebEngineUrlSchemeHandler_DeleteLaterDefault(void* ptr);
void QWebEngineUrlSchemeHandler_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineUrlSchemeHandler_EventDefault(void* ptr, void* e);
char QWebEngineUrlSchemeHandler_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineUrlSchemeHandler_TimerEventDefault(void* ptr, void* event);
char QWebEngineView_HasSelection(void* ptr);
void* QWebEngineView_Icon(void* ptr);
void QWebEngineView_ConnectIconChanged(void* ptr);
void QWebEngineView_DisconnectIconChanged(void* ptr);
void QWebEngineView_IconChanged(void* ptr, void* vqi);
void* QWebEngineView_IconUrl(void* ptr);
void QWebEngineView_ConnectIconUrlChanged(void* ptr);
void QWebEngineView_DisconnectIconUrlChanged(void* ptr);
void QWebEngineView_IconUrlChanged(void* ptr, void* vqu);
struct QtWebEngine_PackedString QWebEngineView_SelectedText(void* ptr);
void QWebEngineView_SetUrl(void* ptr, void* url);
void QWebEngineView_SetZoomFactor(void* ptr, double factor);
struct QtWebEngine_PackedString QWebEngineView_Title(void* ptr);
void* QWebEngineView_Url(void* ptr);
double QWebEngineView_ZoomFactor(void* ptr);
void* QWebEngineView___actions_atList(void* ptr, int i);
void QWebEngineView___actions_setList(void* ptr, void* i);
void* QWebEngineView___actions_newList(void* ptr);
void* QWebEngineView___addActions_actions_atList(void* ptr, int i);
void QWebEngineView___addActions_actions_setList(void* ptr, void* i);
void* QWebEngineView___addActions_actions_newList(void* ptr);
void* QWebEngineView___insertActions_actions_atList(void* ptr, int i);
void QWebEngineView___insertActions_actions_setList(void* ptr, void* i);
void* QWebEngineView___insertActions_actions_newList(void* ptr);
void* QWebEngineView___children_atList(void* ptr, int i);
void QWebEngineView___children_setList(void* ptr, void* i);
void* QWebEngineView___children_newList(void* ptr);
void* QWebEngineView___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineView___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineView___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineView___findChildren_atList(void* ptr, int i);
void QWebEngineView___findChildren_setList(void* ptr, void* i);
void* QWebEngineView___findChildren_newList(void* ptr);
void* QWebEngineView___findChildren_atList3(void* ptr, int i);
void QWebEngineView___findChildren_setList3(void* ptr, void* i);
void* QWebEngineView___findChildren_newList3(void* ptr);
void* QWebEngineView___qFindChildren_atList2(void* ptr, int i);
void QWebEngineView___qFindChildren_setList2(void* ptr, void* i);
void* QWebEngineView___qFindChildren_newList2(void* ptr);
void QWebEngineView_ActionEventDefault(void* ptr, void* event);
void QWebEngineView_ChangeEventDefault(void* ptr, void* event);
char QWebEngineView_CloseDefault(void* ptr);
void QWebEngineView_CloseEventDefault(void* ptr, void* event);
void QWebEngineView_ContextMenuEventDefault(void* ptr, void* event);
void QWebEngineView_DragEnterEventDefault(void* ptr, void* event);
void QWebEngineView_DragLeaveEventDefault(void* ptr, void* event);
void QWebEngineView_DragMoveEventDefault(void* ptr, void* event);
void QWebEngineView_DropEventDefault(void* ptr, void* event);
void QWebEngineView_EnterEventDefault(void* ptr, void* event);
char QWebEngineView_EventDefault(void* ptr, void* event);
void QWebEngineView_FocusInEventDefault(void* ptr, void* event);
char QWebEngineView_FocusNextPrevChildDefault(void* ptr, char next);
void QWebEngineView_FocusOutEventDefault(void* ptr, void* event);
char QWebEngineView_HasHeightForWidthDefault(void* ptr);
int QWebEngineView_HeightForWidthDefault(void* ptr, int w);
void QWebEngineView_HideDefault(void* ptr);
void QWebEngineView_HideEventDefault(void* ptr, void* event);
void QWebEngineView_InitPainterDefault(void* ptr, void* painter);
void QWebEngineView_InputMethodEventDefault(void* ptr, void* event);
void* QWebEngineView_InputMethodQueryDefault(void* ptr, long long query);
void QWebEngineView_KeyPressEventDefault(void* ptr, void* event);
void QWebEngineView_KeyReleaseEventDefault(void* ptr, void* event);
void QWebEngineView_LeaveEventDefault(void* ptr, void* event);
void QWebEngineView_LowerDefault(void* ptr);
int QWebEngineView_MetricDefault(void* ptr, long long m);
void* QWebEngineView_MinimumSizeHintDefault(void* ptr);
void QWebEngineView_MouseDoubleClickEventDefault(void* ptr, void* event);
void QWebEngineView_MouseMoveEventDefault(void* ptr, void* event);
void QWebEngineView_MousePressEventDefault(void* ptr, void* event);
void QWebEngineView_MouseReleaseEventDefault(void* ptr, void* event);
void QWebEngineView_MoveEventDefault(void* ptr, void* event);
char QWebEngineView_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QWebEngineView_PaintEngineDefault(void* ptr);
void QWebEngineView_PaintEventDefault(void* ptr, void* event);
void QWebEngineView_RaiseDefault(void* ptr);
void QWebEngineView_RepaintDefault(void* ptr);
void QWebEngineView_ResizeEventDefault(void* ptr, void* event);
void QWebEngineView_SetDisabledDefault(void* ptr, char disable);
void QWebEngineView_SetEnabledDefault(void* ptr, char vbo);
void QWebEngineView_SetFocus2Default(void* ptr);
void QWebEngineView_SetHiddenDefault(void* ptr, char hidden);
void QWebEngineView_SetStyleSheetDefault(void* ptr, struct QtWebEngine_PackedString styleSheet);
void QWebEngineView_SetVisibleDefault(void* ptr, char visible);
void QWebEngineView_SetWindowModifiedDefault(void* ptr, char vbo);
void QWebEngineView_SetWindowTitleDefault(void* ptr, struct QtWebEngine_PackedString vqs);
void QWebEngineView_ShowDefault(void* ptr);
void QWebEngineView_ShowEventDefault(void* ptr, void* event);
void QWebEngineView_ShowFullScreenDefault(void* ptr);
void QWebEngineView_ShowMaximizedDefault(void* ptr);
void QWebEngineView_ShowMinimizedDefault(void* ptr);
void QWebEngineView_ShowNormalDefault(void* ptr);
void* QWebEngineView_SizeHintDefault(void* ptr);
void QWebEngineView_TabletEventDefault(void* ptr, void* event);
void QWebEngineView_UpdateDefault(void* ptr);
void QWebEngineView_UpdateMicroFocusDefault(void* ptr);
void QWebEngineView_WheelEventDefault(void* ptr, void* event);
void QWebEngineView_ChildEventDefault(void* ptr, void* event);
void QWebEngineView_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineView_CustomEventDefault(void* ptr, void* event);
void QWebEngineView_DeleteLaterDefault(void* ptr);
void QWebEngineView_DisconnectNotifyDefault(void* ptr, void* sign);
char QWebEngineView_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineView_TimerEventDefault(void* ptr, void* event);
void QtWebEngine_QtWebEngine_Initialize();

#ifdef __cplusplus
}
#endif

#endif