Vagrant.configure("2") do |config|
  #config.vm.synced_folder ENV['GOPATH'], "/media/sf_GOPATH0", SharedFoldersEnableSymlinksCreate: false
  config.ssh.keep_alive = true

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 4096
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.cpus = 1
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  config.vm.define "freebsd11" do |m|
    config.vm.box = "generic/freebsd11"
    m.vm.provision "shell", path: "./freebsd.sh", privileged: false
  end

  config.vm.define "freebsd12" do |m|
    config.vm.box = "generic/freebsd12"
    m.vm.provision "shell", path: "./freebsd.sh", privileged: false
  end
end
