// +build !minimal

#pragma once

#ifndef GO_QTREMOTEOBJECTS_H
#define GO_QTREMOTEOBJECTS_H

#include <stdint.h>

#ifdef __cplusplus
int QAbstractItemModelReplica_QAbstractItemModelReplica_QRegisterMetaType();
int QRemoteObjectAbstractPersistedStore_QRemoteObjectAbstractPersistedStore_QRegisterMetaType();
int QRemoteObjectDynamicReplica_QRemoteObjectDynamicReplica_QRegisterMetaType();
int QRemoteObjectHost_QRemoteObjectHost_QRegisterMetaType();
int QRemoteObjectHostBase_QRemoteObjectHostBase_QRegisterMetaType();
int QRemoteObjectNode_QRemoteObjectNode_QRegisterMetaType();
int QRemoteObjectPendingCallWatcher_QRemoteObjectPendingCallWatcher_QRegisterMetaType();
int QRemoteObjectRegistry_QRemoteObjectRegistry_QRegisterMetaType();
int QRemoteObjectRegistryHost_QRemoteObjectRegistryHost_QRegisterMetaType();
int QRemoteObjectReplica_QRemoteObjectReplica_QRegisterMetaType();
int QRemoteObjectSettingsStore_QRemoteObjectSettingsStore_QRegisterMetaType();
extern "C" {
#endif

struct QtRemoteObjects_PackedString { char* data; long long len; void* ptr; };
struct QtRemoteObjects_PackedList { void* data; long long len; };
int QAbstractItemModelReplica___QAbstractItemModelReplica_rolesHint_atList(void* ptr, int i);
void QAbstractItemModelReplica___QAbstractItemModelReplica_rolesHint_setList(void* ptr, int i);
void* QAbstractItemModelReplica___QAbstractItemModelReplica_rolesHint_newList(void* ptr);
int QAbstractItemModelReplica___availableRoles_atList(void* ptr, int i);
void QAbstractItemModelReplica___availableRoles_setList(void* ptr, int i);
void* QAbstractItemModelReplica___availableRoles_newList(void* ptr);
void* QAbstractItemModelReplica___roleNames_atList(void* ptr, int v, int i);
void QAbstractItemModelReplica___roleNames_setList(void* ptr, int key, void* i);
void* QAbstractItemModelReplica___roleNames_newList(void* ptr);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica___roleNames_keyList(void* ptr);
int QAbstractItemModelReplica_____roleNames_keyList_atList(void* ptr, int i);
void QAbstractItemModelReplica_____roleNames_keyList_setList(void* ptr, int i);
void* QAbstractItemModelReplica_____roleNames_keyList_newList(void* ptr);
void* QAbstractItemModelReplica___changePersistentIndexList_from_atList(void* ptr, int i);
void QAbstractItemModelReplica___changePersistentIndexList_from_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___changePersistentIndexList_from_newList(void* ptr);
void* QAbstractItemModelReplica___changePersistentIndexList_to_atList(void* ptr, int i);
void QAbstractItemModelReplica___changePersistentIndexList_to_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___changePersistentIndexList_to_newList(void* ptr);
int QAbstractItemModelReplica___dataChanged_roles_atList(void* ptr, int i);
void QAbstractItemModelReplica___dataChanged_roles_setList(void* ptr, int i);
void* QAbstractItemModelReplica___dataChanged_roles_newList(void* ptr);
void* QAbstractItemModelReplica___itemData_atList(void* ptr, int v, int i);
void QAbstractItemModelReplica___itemData_setList(void* ptr, int key, void* i);
void* QAbstractItemModelReplica___itemData_newList(void* ptr);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica___itemData_keyList(void* ptr);
void* QAbstractItemModelReplica___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void QAbstractItemModelReplica___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___layoutAboutToBeChanged_parents_newList(void* ptr);
void* QAbstractItemModelReplica___layoutChanged_parents_atList(void* ptr, int i);
void QAbstractItemModelReplica___layoutChanged_parents_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___layoutChanged_parents_newList(void* ptr);
void* QAbstractItemModelReplica___match_atList(void* ptr, int i);
void QAbstractItemModelReplica___match_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___match_newList(void* ptr);
void* QAbstractItemModelReplica___mimeData_indexes_atList(void* ptr, int i);
void QAbstractItemModelReplica___mimeData_indexes_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___mimeData_indexes_newList(void* ptr);
void* QAbstractItemModelReplica___persistentIndexList_atList(void* ptr, int i);
void QAbstractItemModelReplica___persistentIndexList_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___persistentIndexList_newList(void* ptr);
void* QAbstractItemModelReplica___setItemData_roles_atList(void* ptr, int v, int i);
void QAbstractItemModelReplica___setItemData_roles_setList(void* ptr, int key, void* i);
void* QAbstractItemModelReplica___setItemData_roles_newList(void* ptr);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica___setItemData_roles_keyList(void* ptr);
int QAbstractItemModelReplica_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QAbstractItemModelReplica_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QAbstractItemModelReplica_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int QAbstractItemModelReplica_____itemData_keyList_atList(void* ptr, int i);
void QAbstractItemModelReplica_____itemData_keyList_setList(void* ptr, int i);
void* QAbstractItemModelReplica_____itemData_keyList_newList(void* ptr);
int QAbstractItemModelReplica_____setItemData_roles_keyList_atList(void* ptr, int i);
void QAbstractItemModelReplica_____setItemData_roles_keyList_setList(void* ptr, int i);
void* QAbstractItemModelReplica_____setItemData_roles_keyList_newList(void* ptr);
int QAbstractItemModelReplica_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QAbstractItemModelReplica_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QAbstractItemModelReplica_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* QAbstractItemModelReplica___children_atList(void* ptr, int i);
void QAbstractItemModelReplica___children_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___children_newList(void* ptr);
void* QAbstractItemModelReplica___dynamicPropertyNames_atList(void* ptr, int i);
void QAbstractItemModelReplica___dynamicPropertyNames_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___dynamicPropertyNames_newList(void* ptr);
void* QAbstractItemModelReplica___findChildren_atList(void* ptr, int i);
void QAbstractItemModelReplica___findChildren_setList(void* ptr, void* i);
void* QAbstractItemModelReplica___findChildren_newList(void* ptr);
void* QAbstractItemModelReplica___findChildren_atList3(void* ptr, int i);
void QAbstractItemModelReplica___findChildren_setList3(void* ptr, void* i);
void* QAbstractItemModelReplica___findChildren_newList3(void* ptr);
void* QAbstractItemModelReplica_BuddyDefault(void* ptr, void* index);
char QAbstractItemModelReplica_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char QAbstractItemModelReplica_CanFetchMoreDefault(void* ptr, void* parent);
int QAbstractItemModelReplica_ColumnCount(void* ptr, void* parent);
int QAbstractItemModelReplica_ColumnCountDefault(void* ptr, void* parent);
void* QAbstractItemModelReplica_Data(void* ptr, void* index, int role);
void* QAbstractItemModelReplica_DataDefault(void* ptr, void* index, int role);
char QAbstractItemModelReplica_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
void QAbstractItemModelReplica_FetchMoreDefault(void* ptr, void* parent);
long long QAbstractItemModelReplica_FlagsDefault(void* ptr, void* index);
char QAbstractItemModelReplica_HasChildrenDefault(void* ptr, void* parent);
void* QAbstractItemModelReplica_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
void* QAbstractItemModelReplica_Index(void* ptr, int row, int column, void* parent);
void* QAbstractItemModelReplica_IndexDefault(void* ptr, int row, int column, void* parent);
char QAbstractItemModelReplica_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char QAbstractItemModelReplica_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica_ItemDataDefault(void* ptr, void* index);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* QAbstractItemModelReplica_MimeDataDefault(void* ptr, void* indexes);
struct QtRemoteObjects_PackedString QAbstractItemModelReplica_MimeTypesDefault(void* ptr);
char QAbstractItemModelReplica_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char QAbstractItemModelReplica_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* QAbstractItemModelReplica_Parent(void* ptr, void* index);
void* QAbstractItemModelReplica_ParentDefault(void* ptr, void* index);
char QAbstractItemModelReplica_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char QAbstractItemModelReplica_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void QAbstractItemModelReplica_ResetInternalDataDefault(void* ptr);
void QAbstractItemModelReplica_RevertDefault(void* ptr);
struct QtRemoteObjects_PackedList QAbstractItemModelReplica_RoleNamesDefault(void* ptr);
int QAbstractItemModelReplica_RowCount(void* ptr, void* parent);
int QAbstractItemModelReplica_RowCountDefault(void* ptr, void* parent);
char QAbstractItemModelReplica_SetDataDefault(void* ptr, void* index, void* value, int role);
char QAbstractItemModelReplica_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char QAbstractItemModelReplica_SetItemDataDefault(void* ptr, void* index, void* roles);
void* QAbstractItemModelReplica_SiblingDefault(void* ptr, int row, int column, void* index);
void QAbstractItemModelReplica_SortDefault(void* ptr, int column, long long order);
void* QAbstractItemModelReplica_SpanDefault(void* ptr, void* index);
char QAbstractItemModelReplica_SubmitDefault(void* ptr);
long long QAbstractItemModelReplica_SupportedDragActionsDefault(void* ptr);
long long QAbstractItemModelReplica_SupportedDropActionsDefault(void* ptr);
void QAbstractItemModelReplica_ChildEventDefault(void* ptr, void* event);
void QAbstractItemModelReplica_ConnectNotifyDefault(void* ptr, void* sign);
void QAbstractItemModelReplica_CustomEventDefault(void* ptr, void* event);
void QAbstractItemModelReplica_DeleteLaterDefault(void* ptr);
void QAbstractItemModelReplica_DisconnectNotifyDefault(void* ptr, void* sign);
char QAbstractItemModelReplica_EventDefault(void* ptr, void* e);
char QAbstractItemModelReplica_EventFilterDefault(void* ptr, void* watched, void* event);
void* QAbstractItemModelReplica_MetaObjectDefault(void* ptr);
void QAbstractItemModelReplica_TimerEventDefault(void* ptr, void* event);
void* QRemoteObjectAbstractPersistedStore_NewQRemoteObjectAbstractPersistedStore(void* parent);
struct QtRemoteObjects_PackedList QRemoteObjectAbstractPersistedStore_RestoreProperties(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig);
void QRemoteObjectAbstractPersistedStore_SaveProperties(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig, void* values);
void* QRemoteObjectAbstractPersistedStore___restoreProperties_atList(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___restoreProperties_setList(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___restoreProperties_newList(void* ptr);
void* QRemoteObjectAbstractPersistedStore___saveProperties_values_atList(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___saveProperties_values_setList(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___saveProperties_values_newList(void* ptr);
void* QRemoteObjectAbstractPersistedStore___children_atList(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___children_setList(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___children_newList(void* ptr);
void* QRemoteObjectAbstractPersistedStore___dynamicPropertyNames_atList(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___dynamicPropertyNames_setList(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___dynamicPropertyNames_newList(void* ptr);
void* QRemoteObjectAbstractPersistedStore___findChildren_atList(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___findChildren_setList(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___findChildren_newList(void* ptr);
void* QRemoteObjectAbstractPersistedStore___findChildren_atList3(void* ptr, int i);
void QRemoteObjectAbstractPersistedStore___findChildren_setList3(void* ptr, void* i);
void* QRemoteObjectAbstractPersistedStore___findChildren_newList3(void* ptr);
void QRemoteObjectAbstractPersistedStore_ChildEventDefault(void* ptr, void* event);
void QRemoteObjectAbstractPersistedStore_ConnectNotifyDefault(void* ptr, void* sign);
void QRemoteObjectAbstractPersistedStore_CustomEventDefault(void* ptr, void* event);
void QRemoteObjectAbstractPersistedStore_DeleteLaterDefault(void* ptr);
void QRemoteObjectAbstractPersistedStore_DisconnectNotifyDefault(void* ptr, void* sign);
char QRemoteObjectAbstractPersistedStore_EventDefault(void* ptr, void* e);
char QRemoteObjectAbstractPersistedStore_EventFilterDefault(void* ptr, void* watched, void* event);
void* QRemoteObjectAbstractPersistedStore_MetaObjectDefault(void* ptr);
void QRemoteObjectAbstractPersistedStore_TimerEventDefault(void* ptr, void* event);
void QRemoteObjectDynamicReplica_DestroyQRemoteObjectDynamicReplica(void* ptr);
void QRemoteObjectDynamicReplica_DestroyQRemoteObjectDynamicReplicaDefault(void* ptr);
void* QRemoteObjectHost_NewQRemoteObjectHost(void* parent);
void* QRemoteObjectHost_NewQRemoteObjectHost2(void* address, void* registryAddress, long long allowedSchemas, void* parent);
void* QRemoteObjectHost_NewQRemoteObjectHost3(void* address, void* parent);
void* QRemoteObjectHost_HostUrl(void* ptr);
void* QRemoteObjectHost_HostUrlDefault(void* ptr);
char QRemoteObjectHost_SetHostUrl(void* ptr, void* hostAddress, long long allowedSchemas);
char QRemoteObjectHost_SetHostUrlDefault(void* ptr, void* hostAddress, long long allowedSchemas);
void QRemoteObjectHostBase_AddHostSideConnection(void* ptr, void* ioDevice);
char QRemoteObjectHostBase_DisableRemoting(void* ptr, void* remoteObject);
char QRemoteObjectHostBase_EnableRemoting2(void* ptr, void* object, struct QtRemoteObjects_PackedString name);
char QRemoteObjectHostBase_EnableRemoting3(void* ptr, void* model, struct QtRemoteObjects_PackedString name, void* roles, void* selectionModel);
int QRemoteObjectHostBase___enableRemoting_roles_atList3(void* ptr, int i);
void QRemoteObjectHostBase___enableRemoting_roles_setList3(void* ptr, int i);
void* QRemoteObjectHostBase___enableRemoting_roles_newList3(void* ptr);
void* QRemoteObjectNode_NewQRemoteObjectNode(void* parent);
void* QRemoteObjectNode_NewQRemoteObjectNode2(void* registryAddress, void* parent);
void* QRemoteObjectNode_AcquireDynamic(void* ptr, struct QtRemoteObjects_PackedString name);
void QRemoteObjectNode_AddClientSideConnection(void* ptr, void* ioDevice);
char QRemoteObjectNode_ConnectToNode(void* ptr, void* address);
int QRemoteObjectNode_HeartbeatInterval(void* ptr);
void QRemoteObjectNode_ConnectHeartbeatIntervalChanged(void* ptr, long long t);
void QRemoteObjectNode_DisconnectHeartbeatIntervalChanged(void* ptr);
void QRemoteObjectNode_HeartbeatIntervalChanged(void* ptr, int heartbeatInterval);
struct QtRemoteObjects_PackedString QRemoteObjectNode_Instances2(void* ptr, struct QtRemoteObjects_PackedString typeName);
long long QRemoteObjectNode_LastError(void* ptr);
void* QRemoteObjectNode_PersistedStore(void* ptr);
void* QRemoteObjectNode_Registry(void* ptr);
void* QRemoteObjectNode_RegistryUrl(void* ptr);
void QRemoteObjectNode_SetHeartbeatInterval(void* ptr, int interval);
void QRemoteObjectNode_SetName(void* ptr, struct QtRemoteObjects_PackedString name);
void QRemoteObjectNode_SetNameDefault(void* ptr, struct QtRemoteObjects_PackedString name);
void QRemoteObjectNode_SetPersistedStore(void* ptr, void* persistedStore);
char QRemoteObjectNode_SetRegistryUrl(void* ptr, void* registryAddress);
char QRemoteObjectNode_SetRegistryUrlDefault(void* ptr, void* registryAddress);
void QRemoteObjectNode_TimerEventDefault(void* ptr, void* vqt);
char QRemoteObjectNode_WaitForRegistry(void* ptr, int timeout);
int QRemoteObjectNode___acquireModel_rolesHint_atList(void* ptr, int i);
void QRemoteObjectNode___acquireModel_rolesHint_setList(void* ptr, int i);
void* QRemoteObjectNode___acquireModel_rolesHint_newList(void* ptr);
void* QRemoteObjectNode___persistProperties_props_atList(void* ptr, int i);
void QRemoteObjectNode___persistProperties_props_setList(void* ptr, void* i);
void* QRemoteObjectNode___persistProperties_props_newList(void* ptr);
void* QRemoteObjectNode___retrieveProperties_atList(void* ptr, int i);
void QRemoteObjectNode___retrieveProperties_setList(void* ptr, void* i);
void* QRemoteObjectNode___retrieveProperties_newList(void* ptr);
void* QRemoteObjectNode___children_atList(void* ptr, int i);
void QRemoteObjectNode___children_setList(void* ptr, void* i);
void* QRemoteObjectNode___children_newList(void* ptr);
void* QRemoteObjectNode___dynamicPropertyNames_atList(void* ptr, int i);
void QRemoteObjectNode___dynamicPropertyNames_setList(void* ptr, void* i);
void* QRemoteObjectNode___dynamicPropertyNames_newList(void* ptr);
void* QRemoteObjectNode___findChildren_atList(void* ptr, int i);
void QRemoteObjectNode___findChildren_setList(void* ptr, void* i);
void* QRemoteObjectNode___findChildren_newList(void* ptr);
void* QRemoteObjectNode___findChildren_atList3(void* ptr, int i);
void QRemoteObjectNode___findChildren_setList3(void* ptr, void* i);
void* QRemoteObjectNode___findChildren_newList3(void* ptr);
void QRemoteObjectNode_ChildEventDefault(void* ptr, void* event);
void QRemoteObjectNode_ConnectNotifyDefault(void* ptr, void* sign);
void QRemoteObjectNode_CustomEventDefault(void* ptr, void* event);
void QRemoteObjectNode_DeleteLaterDefault(void* ptr);
void QRemoteObjectNode_DisconnectNotifyDefault(void* ptr, void* sign);
char QRemoteObjectNode_EventDefault(void* ptr, void* e);
char QRemoteObjectNode_EventFilterDefault(void* ptr, void* watched, void* event);
void* QRemoteObjectNode_MetaObjectDefault(void* ptr);
void* QRemoteObjectPendingCallWatcher___children_atList(void* ptr, int i);
void QRemoteObjectPendingCallWatcher___children_setList(void* ptr, void* i);
void* QRemoteObjectPendingCallWatcher___children_newList(void* ptr);
void* QRemoteObjectPendingCallWatcher___dynamicPropertyNames_atList(void* ptr, int i);
void QRemoteObjectPendingCallWatcher___dynamicPropertyNames_setList(void* ptr, void* i);
void* QRemoteObjectPendingCallWatcher___dynamicPropertyNames_newList(void* ptr);
void* QRemoteObjectPendingCallWatcher___findChildren_atList(void* ptr, int i);
void QRemoteObjectPendingCallWatcher___findChildren_setList(void* ptr, void* i);
void* QRemoteObjectPendingCallWatcher___findChildren_newList(void* ptr);
void* QRemoteObjectPendingCallWatcher___findChildren_atList3(void* ptr, int i);
void QRemoteObjectPendingCallWatcher___findChildren_setList3(void* ptr, void* i);
void* QRemoteObjectPendingCallWatcher___findChildren_newList3(void* ptr);
void QRemoteObjectPendingCallWatcher_ChildEvent(void* ptr, void* event);
void QRemoteObjectPendingCallWatcher_ChildEventDefault(void* ptr, void* event);
void QRemoteObjectPendingCallWatcher_ConnectNotify(void* ptr, void* sign);
void QRemoteObjectPendingCallWatcher_ConnectNotifyDefault(void* ptr, void* sign);
void QRemoteObjectPendingCallWatcher_CustomEvent(void* ptr, void* event);
void QRemoteObjectPendingCallWatcher_CustomEventDefault(void* ptr, void* event);
void QRemoteObjectPendingCallWatcher_DeleteLater(void* ptr);
void QRemoteObjectPendingCallWatcher_DeleteLaterDefault(void* ptr);
void QRemoteObjectPendingCallWatcher_DisconnectNotify(void* ptr, void* sign);
void QRemoteObjectPendingCallWatcher_DisconnectNotifyDefault(void* ptr, void* sign);
char QRemoteObjectPendingCallWatcher_Event(void* ptr, void* e);
char QRemoteObjectPendingCallWatcher_EventDefault(void* ptr, void* e);
char QRemoteObjectPendingCallWatcher_EventFilter(void* ptr, void* watched, void* event);
char QRemoteObjectPendingCallWatcher_EventFilterDefault(void* ptr, void* watched, void* event);
void* QRemoteObjectPendingCallWatcher_MetaObject(void* ptr);
void* QRemoteObjectPendingCallWatcher_MetaObjectDefault(void* ptr);
void QRemoteObjectPendingCallWatcher_TimerEvent(void* ptr, void* event);
void QRemoteObjectPendingCallWatcher_TimerEventDefault(void* ptr, void* event);
void QRemoteObjectRegistry_DestroyQRemoteObjectRegistry(void* ptr);
void QRemoteObjectRegistry_DestroyQRemoteObjectRegistryDefault(void* ptr);
void* QRemoteObjectRegistryHost_NewQRemoteObjectRegistryHost(void* registryAddress, void* parent);
void QRemoteObjectReplica_ConnectInitialized(void* ptr, long long t);
void QRemoteObjectReplica_DisconnectInitialized(void* ptr);
void QRemoteObjectReplica_Initialized(void* ptr);
char QRemoteObjectReplica_IsInitialized(void* ptr);
char QRemoteObjectReplica_IsReplicaValid(void* ptr);
void* QRemoteObjectReplica_Node(void* ptr);
void QRemoteObjectReplica_SetNode(void* ptr, void* node);
void QRemoteObjectReplica_SetNodeDefault(void* ptr, void* node);
long long QRemoteObjectReplica_State(void* ptr);
void QRemoteObjectReplica_ConnectStateChanged(void* ptr, long long t);
void QRemoteObjectReplica_DisconnectStateChanged(void* ptr);
void QRemoteObjectReplica_StateChanged(void* ptr, long long state, long long oldState);
char QRemoteObjectReplica_WaitForSource(void* ptr, int timeout);
void* QRemoteObjectReplica___persistProperties_props_atList(void* ptr, int i);
void QRemoteObjectReplica___persistProperties_props_setList(void* ptr, void* i);
void* QRemoteObjectReplica___persistProperties_props_newList(void* ptr);
void* QRemoteObjectReplica___retrieveProperties_atList(void* ptr, int i);
void QRemoteObjectReplica___retrieveProperties_setList(void* ptr, void* i);
void* QRemoteObjectReplica___retrieveProperties_newList(void* ptr);
void* QRemoteObjectReplica___send_args_atList(void* ptr, int i);
void QRemoteObjectReplica___send_args_setList(void* ptr, void* i);
void* QRemoteObjectReplica___send_args_newList(void* ptr);
void* QRemoteObjectReplica___sendWithReply_args_atList(void* ptr, int i);
void QRemoteObjectReplica___sendWithReply_args_setList(void* ptr, void* i);
void* QRemoteObjectReplica___sendWithReply_args_newList(void* ptr);
void* QRemoteObjectReplica___setProperties_properties_atList(void* ptr, int i);
void QRemoteObjectReplica___setProperties_properties_setList(void* ptr, void* i);
void* QRemoteObjectReplica___setProperties_properties_newList(void* ptr);
void* QRemoteObjectReplica___children_atList(void* ptr, int i);
void QRemoteObjectReplica___children_setList(void* ptr, void* i);
void* QRemoteObjectReplica___children_newList(void* ptr);
void* QRemoteObjectReplica___dynamicPropertyNames_atList(void* ptr, int i);
void QRemoteObjectReplica___dynamicPropertyNames_setList(void* ptr, void* i);
void* QRemoteObjectReplica___dynamicPropertyNames_newList(void* ptr);
void* QRemoteObjectReplica___findChildren_atList(void* ptr, int i);
void QRemoteObjectReplica___findChildren_setList(void* ptr, void* i);
void* QRemoteObjectReplica___findChildren_newList(void* ptr);
void* QRemoteObjectReplica___findChildren_atList3(void* ptr, int i);
void QRemoteObjectReplica___findChildren_setList3(void* ptr, void* i);
void* QRemoteObjectReplica___findChildren_newList3(void* ptr);
void QRemoteObjectReplica_ChildEventDefault(void* ptr, void* event);
void QRemoteObjectReplica_ConnectNotifyDefault(void* ptr, void* sign);
void QRemoteObjectReplica_CustomEventDefault(void* ptr, void* event);
void QRemoteObjectReplica_DeleteLaterDefault(void* ptr);
void QRemoteObjectReplica_DisconnectNotifyDefault(void* ptr, void* sign);
char QRemoteObjectReplica_EventDefault(void* ptr, void* e);
char QRemoteObjectReplica_EventFilterDefault(void* ptr, void* watched, void* event);
void* QRemoteObjectReplica_MetaObjectDefault(void* ptr);
void QRemoteObjectReplica_TimerEventDefault(void* ptr, void* event);
struct QtRemoteObjects_PackedList QRemoteObjectSettingsStore_RestoreProperties(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig);
struct QtRemoteObjects_PackedList QRemoteObjectSettingsStore_RestorePropertiesDefault(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig);
void QRemoteObjectSettingsStore_SaveProperties(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig, void* values);
void QRemoteObjectSettingsStore_SavePropertiesDefault(void* ptr, struct QtRemoteObjects_PackedString repName, void* repSig, void* values);

#ifdef __cplusplus
}
#endif

#endif