FROM therecipe/qt:base


RUN mkdir /usr/lib/mxe/

ENV PKG mxe-x86-64-w64-mingw32.shared-qt3d_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtactiveqt_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtbase_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtcanvas3d_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtcharts_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtconnectivity_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtdatavis3d_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtdeclarative_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtgamepad_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtgraphicaleffects_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtimageformats_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtlocation_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtmultimedia_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtpurchasing_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtquickcontrols2_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtquickcontrols_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtscript_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtscxml_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtsensors_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtserialbus_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtserialport_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtsvg_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qttools_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qttranslations_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtvirtualkeyboard_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtwebchannel_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtwebkit_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtwebsockets_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtwinextras_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG

ENV PKG mxe-x86-64-w64-mingw32.shared-qtxmlpatterns_5.8.0.tar.xz
RUN curl -sL --retry 10 --retry-delay 10 -o /tmp/$PKG http://pkg.mxe.cc/releases/2017-02-11/tar/mxe-x86-64-w64-mingw32.shared/$PKG && tar xf /tmp/$PKG -C /usr/lib/mxe/ && rm -f /tmp/$PKG


ENV QT_MXE_ARCH amd64
RUN $GOPATH/bin/qtsetup check windows
RUN $GOPATH/bin/qtsetup generate
