// +build !minimal

#pragma once

#ifndef GO_QTVIRTUALKEYBOARD_H
#define GO_QTVIRTUALKEYBOARD_H

#include <stdint.h>

#ifdef __cplusplus
int QVirtualKeyboardAbstractInputMethod_QVirtualKeyboardAbstractInputMethod_QRegisterMetaType();
int QVirtualKeyboardExtensionPlugin_QVirtualKeyboardExtensionPlugin_QRegisterMetaType();
int QVirtualKeyboardInputContext_QVirtualKeyboardInputContext_QRegisterMetaType();
int QVirtualKeyboardInputEngine_QVirtualKeyboardInputEngine_QRegisterMetaType();
int QVirtualKeyboardSelectionListModel_QVirtualKeyboardSelectionListModel_QRegisterMetaType();
int QVirtualKeyboardTrace_QVirtualKeyboardTrace_QRegisterMetaType();
extern "C" {
#endif

struct QtVirtualKeyboard_PackedString { char* data; long long len; void* ptr; };
struct QtVirtualKeyboard_PackedList { void* data; long long len; };
void* QVirtualKeyboardAbstractInputMethod_NewQVirtualKeyboardAbstractInputMethod(void* parent);
char QVirtualKeyboardAbstractInputMethod_ClickPreeditText(void* ptr, int cursorPosition);
char QVirtualKeyboardAbstractInputMethod_ClickPreeditTextDefault(void* ptr, int cursorPosition);
void* QVirtualKeyboardAbstractInputMethod_InputContext(void* ptr);
void* QVirtualKeyboardAbstractInputMethod_InputEngine(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod_InputModes(void* ptr, struct QtVirtualKeyboard_PackedString locale);
char QVirtualKeyboardAbstractInputMethod_KeyEvent(void* ptr, long long key, struct QtVirtualKeyboard_PackedString text, long long modifiers);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod_PatternRecognitionModes(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod_PatternRecognitionModesDefault(void* ptr);
char QVirtualKeyboardAbstractInputMethod_Reselect(void* ptr, int cursorPosition, long long reselectFlags);
char QVirtualKeyboardAbstractInputMethod_ReselectDefault(void* ptr, int cursorPosition, long long reselectFlags);
void QVirtualKeyboardAbstractInputMethod_Reset(void* ptr);
void QVirtualKeyboardAbstractInputMethod_ResetDefault(void* ptr);
void QVirtualKeyboardAbstractInputMethod_ConnectSelectionListActiveItemChanged(void* ptr, long long t);
void QVirtualKeyboardAbstractInputMethod_DisconnectSelectionListActiveItemChanged(void* ptr);
void QVirtualKeyboardAbstractInputMethod_SelectionListActiveItemChanged(void* ptr, long long ty, int index);
void QVirtualKeyboardAbstractInputMethod_ConnectSelectionListChanged(void* ptr, long long t);
void QVirtualKeyboardAbstractInputMethod_DisconnectSelectionListChanged(void* ptr);
void QVirtualKeyboardAbstractInputMethod_SelectionListChanged(void* ptr, long long ty);
void* QVirtualKeyboardAbstractInputMethod_SelectionListData(void* ptr, long long ty, int index, long long role);
void* QVirtualKeyboardAbstractInputMethod_SelectionListDataDefault(void* ptr, long long ty, int index, long long role);
int QVirtualKeyboardAbstractInputMethod_SelectionListItemCount(void* ptr, long long ty);
int QVirtualKeyboardAbstractInputMethod_SelectionListItemCountDefault(void* ptr, long long ty);
void QVirtualKeyboardAbstractInputMethod_SelectionListItemSelected(void* ptr, long long ty, int index);
void QVirtualKeyboardAbstractInputMethod_SelectionListItemSelectedDefault(void* ptr, long long ty, int index);
char QVirtualKeyboardAbstractInputMethod_SelectionListRemoveItem(void* ptr, long long ty, int index);
char QVirtualKeyboardAbstractInputMethod_SelectionListRemoveItemDefault(void* ptr, long long ty, int index);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod_SelectionLists(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod_SelectionListsDefault(void* ptr);
void QVirtualKeyboardAbstractInputMethod_ConnectSelectionListsChanged(void* ptr, long long t);
void QVirtualKeyboardAbstractInputMethod_DisconnectSelectionListsChanged(void* ptr);
void QVirtualKeyboardAbstractInputMethod_SelectionListsChanged(void* ptr);
char QVirtualKeyboardAbstractInputMethod_SetInputMode(void* ptr, struct QtVirtualKeyboard_PackedString locale, long long inputMode);
char QVirtualKeyboardAbstractInputMethod_SetTextCase(void* ptr, long long textCase);
void* QVirtualKeyboardAbstractInputMethod_TraceBegin(void* ptr, int traceId, long long patternRecognitionMode, void* traceCaptureDeviceInfo, void* traceScreenInfo);
void* QVirtualKeyboardAbstractInputMethod_TraceBeginDefault(void* ptr, int traceId, long long patternRecognitionMode, void* traceCaptureDeviceInfo, void* traceScreenInfo);
char QVirtualKeyboardAbstractInputMethod_TraceEnd(void* ptr, void* trace);
char QVirtualKeyboardAbstractInputMethod_TraceEndDefault(void* ptr, void* trace);
void QVirtualKeyboardAbstractInputMethod_Update(void* ptr);
void QVirtualKeyboardAbstractInputMethod_UpdateDefault(void* ptr);
void QVirtualKeyboardAbstractInputMethod_DestroyQVirtualKeyboardAbstractInputMethod(void* ptr);
void QVirtualKeyboardAbstractInputMethod_DestroyQVirtualKeyboardAbstractInputMethodDefault(void* ptr);
long long QVirtualKeyboardAbstractInputMethod___inputModes_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___inputModes_setList(void* ptr, long long i);
void* QVirtualKeyboardAbstractInputMethod___inputModes_newList(void* ptr);
long long QVirtualKeyboardAbstractInputMethod___patternRecognitionModes_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___patternRecognitionModes_setList(void* ptr, long long i);
void* QVirtualKeyboardAbstractInputMethod___patternRecognitionModes_newList(void* ptr);
long long QVirtualKeyboardAbstractInputMethod___selectionLists_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___selectionLists_setList(void* ptr, long long i);
void* QVirtualKeyboardAbstractInputMethod___selectionLists_newList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___traceBegin_traceCaptureDeviceInfo_atList(void* ptr, struct QtVirtualKeyboard_PackedString v, int i);
void QVirtualKeyboardAbstractInputMethod___traceBegin_traceCaptureDeviceInfo_setList(void* ptr, struct QtVirtualKeyboard_PackedString key, void* i);
void* QVirtualKeyboardAbstractInputMethod___traceBegin_traceCaptureDeviceInfo_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod___traceBegin_traceCaptureDeviceInfo_keyList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___traceBegin_traceScreenInfo_atList(void* ptr, struct QtVirtualKeyboard_PackedString v, int i);
void QVirtualKeyboardAbstractInputMethod___traceBegin_traceScreenInfo_setList(void* ptr, struct QtVirtualKeyboard_PackedString key, void* i);
void* QVirtualKeyboardAbstractInputMethod___traceBegin_traceScreenInfo_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardAbstractInputMethod___traceBegin_traceScreenInfo_keyList(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardAbstractInputMethod_____traceBegin_traceCaptureDeviceInfo_keyList_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod_____traceBegin_traceCaptureDeviceInfo_keyList_setList(void* ptr, struct QtVirtualKeyboard_PackedString i);
void* QVirtualKeyboardAbstractInputMethod_____traceBegin_traceCaptureDeviceInfo_keyList_newList(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardAbstractInputMethod_____traceBegin_traceScreenInfo_keyList_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod_____traceBegin_traceScreenInfo_keyList_setList(void* ptr, struct QtVirtualKeyboard_PackedString i);
void* QVirtualKeyboardAbstractInputMethod_____traceBegin_traceScreenInfo_keyList_newList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___children_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___children_setList(void* ptr, void* i);
void* QVirtualKeyboardAbstractInputMethod___children_newList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardAbstractInputMethod___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardAbstractInputMethod___findChildren_newList(void* ptr);
void* QVirtualKeyboardAbstractInputMethod___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardAbstractInputMethod___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardAbstractInputMethod___findChildren_newList3(void* ptr);
void QVirtualKeyboardAbstractInputMethod_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardAbstractInputMethod_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardAbstractInputMethod_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardAbstractInputMethod_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardAbstractInputMethod_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardAbstractInputMethod_EventDefault(void* ptr, void* e);
char QVirtualKeyboardAbstractInputMethod_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardAbstractInputMethod_MetaObjectDefault(void* ptr);
void QVirtualKeyboardAbstractInputMethod_TimerEventDefault(void* ptr, void* event);
void QVirtualKeyboardExtensionPlugin_RegisterTypes(void* ptr, char* uri);
void QVirtualKeyboardExtensionPlugin_RegisterTypesDefault(void* ptr, char* uri);
void* QVirtualKeyboardExtensionPlugin___children_atList(void* ptr, int i);
void QVirtualKeyboardExtensionPlugin___children_setList(void* ptr, void* i);
void* QVirtualKeyboardExtensionPlugin___children_newList(void* ptr);
void* QVirtualKeyboardExtensionPlugin___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardExtensionPlugin___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardExtensionPlugin___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardExtensionPlugin___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardExtensionPlugin___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardExtensionPlugin___findChildren_newList(void* ptr);
void* QVirtualKeyboardExtensionPlugin___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardExtensionPlugin___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardExtensionPlugin___findChildren_newList3(void* ptr);
void QVirtualKeyboardExtensionPlugin_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardExtensionPlugin_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardExtensionPlugin_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardExtensionPlugin_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardExtensionPlugin_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardExtensionPlugin_EventDefault(void* ptr, void* e);
char QVirtualKeyboardExtensionPlugin_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardExtensionPlugin_MetaObjectDefault(void* ptr);
void QVirtualKeyboardExtensionPlugin_TimerEventDefault(void* ptr, void* event);
int QVirtualKeyboardInputContext_AnchorPosition(void* ptr);
void QVirtualKeyboardInputContext_ConnectAnchorPositionChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectAnchorPositionChanged(void* ptr);
void QVirtualKeyboardInputContext_AnchorPositionChanged(void* ptr);
char QVirtualKeyboardInputContext_AnchorRectIntersectsClipRect(void* ptr);
void QVirtualKeyboardInputContext_ConnectAnchorRectIntersectsClipRectChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectAnchorRectIntersectsClipRectChanged(void* ptr);
void QVirtualKeyboardInputContext_AnchorRectIntersectsClipRectChanged(void* ptr);
void* QVirtualKeyboardInputContext_AnchorRectangle(void* ptr);
void QVirtualKeyboardInputContext_ConnectAnchorRectangleChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectAnchorRectangleChanged(void* ptr);
void QVirtualKeyboardInputContext_AnchorRectangleChanged(void* ptr);
void QVirtualKeyboardInputContext_ConnectAnimatingChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectAnimatingChanged(void* ptr);
void QVirtualKeyboardInputContext_AnimatingChanged(void* ptr);
void QVirtualKeyboardInputContext_ConnectCapsLockActiveChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectCapsLockActiveChanged(void* ptr);
void QVirtualKeyboardInputContext_CapsLockActiveChanged(void* ptr);
void QVirtualKeyboardInputContext_Clear(void* ptr);
void QVirtualKeyboardInputContext_Commit(void* ptr);
void QVirtualKeyboardInputContext_Commit2(void* ptr, struct QtVirtualKeyboard_PackedString text, int replaceFrom, int replaceLength);
int QVirtualKeyboardInputContext_CursorPosition(void* ptr);
void QVirtualKeyboardInputContext_ConnectCursorPositionChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectCursorPositionChanged(void* ptr);
void QVirtualKeyboardInputContext_CursorPositionChanged(void* ptr);
char QVirtualKeyboardInputContext_CursorRectIntersectsClipRect(void* ptr);
void QVirtualKeyboardInputContext_ConnectCursorRectIntersectsClipRectChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectCursorRectIntersectsClipRectChanged(void* ptr);
void QVirtualKeyboardInputContext_CursorRectIntersectsClipRectChanged(void* ptr);
void* QVirtualKeyboardInputContext_CursorRectangle(void* ptr);
void QVirtualKeyboardInputContext_ConnectCursorRectangleChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectCursorRectangleChanged(void* ptr);
void QVirtualKeyboardInputContext_CursorRectangleChanged(void* ptr);
void* QVirtualKeyboardInputContext_InputEngine(void* ptr);
void* QVirtualKeyboardInputContext_InputItem(void* ptr);
void QVirtualKeyboardInputContext_ConnectInputItemChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectInputItemChanged(void* ptr);
void QVirtualKeyboardInputContext_InputItemChanged(void* ptr);
long long QVirtualKeyboardInputContext_InputMethodHints(void* ptr);
void QVirtualKeyboardInputContext_ConnectInputMethodHintsChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectInputMethodHintsChanged(void* ptr);
void QVirtualKeyboardInputContext_InputMethodHintsChanged(void* ptr);
char QVirtualKeyboardInputContext_IsAnimating(void* ptr);
char QVirtualKeyboardInputContext_IsCapsLockActive(void* ptr);
char QVirtualKeyboardInputContext_IsSelectionControlVisible(void* ptr);
char QVirtualKeyboardInputContext_IsShiftActive(void* ptr);
char QVirtualKeyboardInputContext_IsUppercase(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputContext_Locale(void* ptr);
void QVirtualKeyboardInputContext_ConnectLocaleChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectLocaleChanged(void* ptr);
void QVirtualKeyboardInputContext_LocaleChanged(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputContext_PreeditText(void* ptr);
void QVirtualKeyboardInputContext_ConnectPreeditTextChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectPreeditTextChanged(void* ptr);
void QVirtualKeyboardInputContext_PreeditTextChanged(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputContext_SelectedText(void* ptr);
void QVirtualKeyboardInputContext_ConnectSelectedTextChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectSelectedTextChanged(void* ptr);
void QVirtualKeyboardInputContext_SelectedTextChanged(void* ptr);
void QVirtualKeyboardInputContext_ConnectSelectionControlVisibleChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectSelectionControlVisibleChanged(void* ptr);
void QVirtualKeyboardInputContext_SelectionControlVisibleChanged(void* ptr);
void QVirtualKeyboardInputContext_SendKeyClick(void* ptr, int key, struct QtVirtualKeyboard_PackedString text, int modifiers);
void QVirtualKeyboardInputContext_SetAnimating(void* ptr, char isAnimating);
void QVirtualKeyboardInputContext_ConnectShiftActiveChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectShiftActiveChanged(void* ptr);
void QVirtualKeyboardInputContext_ShiftActiveChanged(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputContext_SurroundingText(void* ptr);
void QVirtualKeyboardInputContext_ConnectSurroundingTextChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectSurroundingTextChanged(void* ptr);
void QVirtualKeyboardInputContext_SurroundingTextChanged(void* ptr);
void QVirtualKeyboardInputContext_ConnectUppercaseChanged(void* ptr, long long t);
void QVirtualKeyboardInputContext_DisconnectUppercaseChanged(void* ptr);
void QVirtualKeyboardInputContext_UppercaseChanged(void* ptr);
void* QVirtualKeyboardInputContext___preeditTextAttributes_newList(void* ptr);
void* QVirtualKeyboardInputContext___setPreeditText_attributes_newList(void* ptr);
void* QVirtualKeyboardInputContext___children_atList(void* ptr, int i);
void QVirtualKeyboardInputContext___children_setList(void* ptr, void* i);
void* QVirtualKeyboardInputContext___children_newList(void* ptr);
void* QVirtualKeyboardInputContext___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardInputContext___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardInputContext___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardInputContext___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardInputContext___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardInputContext___findChildren_newList(void* ptr);
void* QVirtualKeyboardInputContext___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardInputContext___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardInputContext___findChildren_newList3(void* ptr);
void QVirtualKeyboardInputContext_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardInputContext_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardInputContext_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardInputContext_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardInputContext_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardInputContext_EventDefault(void* ptr, void* e);
char QVirtualKeyboardInputContext_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardInputContext_MetaObjectDefault(void* ptr);
void QVirtualKeyboardInputContext_TimerEventDefault(void* ptr, void* event);
long long QVirtualKeyboardInputEngine_ActiveKey(void* ptr);
void QVirtualKeyboardInputEngine_ConnectActiveKeyChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectActiveKeyChanged(void* ptr);
void QVirtualKeyboardInputEngine_ActiveKeyChanged(void* ptr, long long key);
void* QVirtualKeyboardInputEngine_InputContext(void* ptr);
void* QVirtualKeyboardInputEngine_InputMethod(void* ptr);
void QVirtualKeyboardInputEngine_ConnectInputMethodChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectInputMethodChanged(void* ptr);
void QVirtualKeyboardInputEngine_InputMethodChanged(void* ptr);
void QVirtualKeyboardInputEngine_ConnectInputMethodReset(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectInputMethodReset(void* ptr);
void QVirtualKeyboardInputEngine_InputMethodReset(void* ptr);
void QVirtualKeyboardInputEngine_ConnectInputMethodUpdate(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectInputMethodUpdate(void* ptr);
void QVirtualKeyboardInputEngine_InputMethodUpdate(void* ptr);
long long QVirtualKeyboardInputEngine_InputMode(void* ptr);
void QVirtualKeyboardInputEngine_ConnectInputModeChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectInputModeChanged(void* ptr);
void QVirtualKeyboardInputEngine_InputModeChanged(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardInputEngine_InputModes(void* ptr);
void QVirtualKeyboardInputEngine_ConnectInputModesChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectInputModesChanged(void* ptr);
void QVirtualKeyboardInputEngine_InputModesChanged(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardInputEngine_PatternRecognitionModes(void* ptr);
void QVirtualKeyboardInputEngine_ConnectPatternRecognitionModesChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectPatternRecognitionModesChanged(void* ptr);
void QVirtualKeyboardInputEngine_PatternRecognitionModesChanged(void* ptr);
long long QVirtualKeyboardInputEngine_PreviousKey(void* ptr);
void QVirtualKeyboardInputEngine_ConnectPreviousKeyChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectPreviousKeyChanged(void* ptr);
void QVirtualKeyboardInputEngine_PreviousKeyChanged(void* ptr, long long key);
char QVirtualKeyboardInputEngine_Reselect(void* ptr, int cursorPosition, long long reselectFlags);
void QVirtualKeyboardInputEngine_SetInputMethod(void* ptr, void* inputMethod);
void QVirtualKeyboardInputEngine_SetInputMode(void* ptr, long long inputMode);
void* QVirtualKeyboardInputEngine_TraceBegin(void* ptr, int traceId, long long patternRecognitionMode, void* traceCaptureDeviceInfo, void* traceScreenInfo);
char QVirtualKeyboardInputEngine_TraceEnd(void* ptr, void* trace);
void QVirtualKeyboardInputEngine_VirtualKeyCancel(void* ptr);
char QVirtualKeyboardInputEngine_VirtualKeyClick(void* ptr, long long key, struct QtVirtualKeyboard_PackedString text, long long modifiers);
void QVirtualKeyboardInputEngine_ConnectVirtualKeyClicked(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectVirtualKeyClicked(void* ptr);
void QVirtualKeyboardInputEngine_VirtualKeyClicked(void* ptr, long long key, struct QtVirtualKeyboard_PackedString text, long long modifiers, char isAutoRepeat);
char QVirtualKeyboardInputEngine_VirtualKeyPress(void* ptr, long long key, struct QtVirtualKeyboard_PackedString text, long long modifiers, char repeat);
char QVirtualKeyboardInputEngine_VirtualKeyRelease(void* ptr, long long key, struct QtVirtualKeyboard_PackedString text, long long modifiers);
void* QVirtualKeyboardInputEngine_WordCandidateListModel(void* ptr);
void QVirtualKeyboardInputEngine_ConnectWordCandidateListModelChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectWordCandidateListModelChanged(void* ptr);
void QVirtualKeyboardInputEngine_WordCandidateListModelChanged(void* ptr);
char QVirtualKeyboardInputEngine_WordCandidateListVisibleHint(void* ptr);
void QVirtualKeyboardInputEngine_ConnectWordCandidateListVisibleHintChanged(void* ptr, long long t);
void QVirtualKeyboardInputEngine_DisconnectWordCandidateListVisibleHintChanged(void* ptr);
void QVirtualKeyboardInputEngine_WordCandidateListVisibleHintChanged(void* ptr);
int QVirtualKeyboardInputEngine___inputModes_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine___inputModes_setList(void* ptr, int i);
void* QVirtualKeyboardInputEngine___inputModes_newList(void* ptr);
int QVirtualKeyboardInputEngine___patternRecognitionModes_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine___patternRecognitionModes_setList(void* ptr, int i);
void* QVirtualKeyboardInputEngine___patternRecognitionModes_newList(void* ptr);
void* QVirtualKeyboardInputEngine___traceBegin_traceCaptureDeviceInfo_atList(void* ptr, struct QtVirtualKeyboard_PackedString v, int i);
void QVirtualKeyboardInputEngine___traceBegin_traceCaptureDeviceInfo_setList(void* ptr, struct QtVirtualKeyboard_PackedString key, void* i);
void* QVirtualKeyboardInputEngine___traceBegin_traceCaptureDeviceInfo_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardInputEngine___traceBegin_traceCaptureDeviceInfo_keyList(void* ptr);
void* QVirtualKeyboardInputEngine___traceBegin_traceScreenInfo_atList(void* ptr, struct QtVirtualKeyboard_PackedString v, int i);
void QVirtualKeyboardInputEngine___traceBegin_traceScreenInfo_setList(void* ptr, struct QtVirtualKeyboard_PackedString key, void* i);
void* QVirtualKeyboardInputEngine___traceBegin_traceScreenInfo_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardInputEngine___traceBegin_traceScreenInfo_keyList(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputEngine_____traceBegin_traceCaptureDeviceInfo_keyList_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine_____traceBegin_traceCaptureDeviceInfo_keyList_setList(void* ptr, struct QtVirtualKeyboard_PackedString i);
void* QVirtualKeyboardInputEngine_____traceBegin_traceCaptureDeviceInfo_keyList_newList(void* ptr);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardInputEngine_____traceBegin_traceScreenInfo_keyList_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine_____traceBegin_traceScreenInfo_keyList_setList(void* ptr, struct QtVirtualKeyboard_PackedString i);
void* QVirtualKeyboardInputEngine_____traceBegin_traceScreenInfo_keyList_newList(void* ptr);
void* QVirtualKeyboardInputEngine___children_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine___children_setList(void* ptr, void* i);
void* QVirtualKeyboardInputEngine___children_newList(void* ptr);
void* QVirtualKeyboardInputEngine___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardInputEngine___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardInputEngine___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardInputEngine___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardInputEngine___findChildren_newList(void* ptr);
void* QVirtualKeyboardInputEngine___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardInputEngine___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardInputEngine___findChildren_newList3(void* ptr);
void QVirtualKeyboardInputEngine_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardInputEngine_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardInputEngine_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardInputEngine_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardInputEngine_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardInputEngine_EventDefault(void* ptr, void* e);
char QVirtualKeyboardInputEngine_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardInputEngine_MetaObjectDefault(void* ptr);
void QVirtualKeyboardInputEngine_TimerEventDefault(void* ptr, void* event);
void QVirtualKeyboardSelectionListModel_ConnectActiveItemChanged(void* ptr, long long t);
void QVirtualKeyboardSelectionListModel_DisconnectActiveItemChanged(void* ptr);
void QVirtualKeyboardSelectionListModel_ActiveItemChanged(void* ptr, int index);
void QVirtualKeyboardSelectionListModel_ConnectItemSelected(void* ptr, long long t);
void QVirtualKeyboardSelectionListModel_DisconnectItemSelected(void* ptr);
void QVirtualKeyboardSelectionListModel_ItemSelected(void* ptr, int index);
void QVirtualKeyboardSelectionListModel_RemoveItem(void* ptr, int index);
void QVirtualKeyboardSelectionListModel_SelectItem(void* ptr, int index);
void* QVirtualKeyboardSelectionListModel___roleNames_atList(void* ptr, int v, int i);
void QVirtualKeyboardSelectionListModel___roleNames_setList(void* ptr, int key, void* i);
void* QVirtualKeyboardSelectionListModel___roleNames_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel___roleNames_keyList(void* ptr);
int QVirtualKeyboardSelectionListModel_____roleNames_keyList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel_____roleNames_keyList_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel_____roleNames_keyList_newList(void* ptr);
int QVirtualKeyboardSelectionListModel_____itemData_keyList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel_____itemData_keyList_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel_____itemData_keyList_newList(void* ptr);
int QVirtualKeyboardSelectionListModel_____setItemData_roles_keyList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel_____setItemData_roles_keyList_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel_____setItemData_roles_keyList_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___changePersistentIndexList_from_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___changePersistentIndexList_from_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___changePersistentIndexList_from_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___changePersistentIndexList_to_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___changePersistentIndexList_to_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___changePersistentIndexList_to_newList(void* ptr);
int QVirtualKeyboardSelectionListModel___dataChanged_roles_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___dataChanged_roles_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel___dataChanged_roles_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___itemData_atList(void* ptr, int v, int i);
void QVirtualKeyboardSelectionListModel___itemData_setList(void* ptr, int key, void* i);
void* QVirtualKeyboardSelectionListModel___itemData_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel___itemData_keyList(void* ptr);
void* QVirtualKeyboardSelectionListModel___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___layoutAboutToBeChanged_parents_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___layoutChanged_parents_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___layoutChanged_parents_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___layoutChanged_parents_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___match_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___match_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___match_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___mimeData_indexes_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___mimeData_indexes_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___mimeData_indexes_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___persistentIndexList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___persistentIndexList_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___persistentIndexList_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___setItemData_roles_atList(void* ptr, int v, int i);
void QVirtualKeyboardSelectionListModel___setItemData_roles_setList(void* ptr, int key, void* i);
void* QVirtualKeyboardSelectionListModel___setItemData_roles_newList(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel___setItemData_roles_keyList(void* ptr);
int QVirtualKeyboardSelectionListModel_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int QVirtualKeyboardSelectionListModel_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* QVirtualKeyboardSelectionListModel_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___children_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___children_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___children_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___findChildren_newList(void* ptr);
void* QVirtualKeyboardSelectionListModel___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardSelectionListModel___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardSelectionListModel___findChildren_newList3(void* ptr);
char QVirtualKeyboardSelectionListModel_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long QVirtualKeyboardSelectionListModel_FlagsDefault(void* ptr, void* index);
void* QVirtualKeyboardSelectionListModel_IndexDefault(void* ptr, int row, int column, void* parent);
void* QVirtualKeyboardSelectionListModel_SiblingDefault(void* ptr, int row, int column, void* idx);
void* QVirtualKeyboardSelectionListModel_BuddyDefault(void* ptr, void* index);
char QVirtualKeyboardSelectionListModel_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char QVirtualKeyboardSelectionListModel_CanFetchMoreDefault(void* ptr, void* parent);
int QVirtualKeyboardSelectionListModel_ColumnCountDefault(void* ptr, void* parent);
void* QVirtualKeyboardSelectionListModel_DataDefault(void* ptr, void* index, int role);
void QVirtualKeyboardSelectionListModel_FetchMoreDefault(void* ptr, void* parent);
char QVirtualKeyboardSelectionListModel_HasChildrenDefault(void* ptr, void* parent);
void* QVirtualKeyboardSelectionListModel_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char QVirtualKeyboardSelectionListModel_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char QVirtualKeyboardSelectionListModel_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel_ItemDataDefault(void* ptr, void* index);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* QVirtualKeyboardSelectionListModel_MimeDataDefault(void* ptr, void* indexes);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardSelectionListModel_MimeTypesDefault(void* ptr);
char QVirtualKeyboardSelectionListModel_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char QVirtualKeyboardSelectionListModel_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* QVirtualKeyboardSelectionListModel_ParentDefault(void* ptr, void* index);
char QVirtualKeyboardSelectionListModel_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char QVirtualKeyboardSelectionListModel_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void QVirtualKeyboardSelectionListModel_ResetInternalDataDefault(void* ptr);
void QVirtualKeyboardSelectionListModel_RevertDefault(void* ptr);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardSelectionListModel_RoleNamesDefault(void* ptr);
int QVirtualKeyboardSelectionListModel_RowCountDefault(void* ptr, void* parent);
char QVirtualKeyboardSelectionListModel_SetDataDefault(void* ptr, void* index, void* value, int role);
char QVirtualKeyboardSelectionListModel_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char QVirtualKeyboardSelectionListModel_SetItemDataDefault(void* ptr, void* index, void* roles);
void QVirtualKeyboardSelectionListModel_SortDefault(void* ptr, int column, long long order);
void* QVirtualKeyboardSelectionListModel_SpanDefault(void* ptr, void* index);
char QVirtualKeyboardSelectionListModel_SubmitDefault(void* ptr);
long long QVirtualKeyboardSelectionListModel_SupportedDragActionsDefault(void* ptr);
long long QVirtualKeyboardSelectionListModel_SupportedDropActionsDefault(void* ptr);
void QVirtualKeyboardSelectionListModel_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardSelectionListModel_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardSelectionListModel_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardSelectionListModel_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardSelectionListModel_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardSelectionListModel_EventDefault(void* ptr, void* e);
char QVirtualKeyboardSelectionListModel_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardSelectionListModel_MetaObjectDefault(void* ptr);
void QVirtualKeyboardSelectionListModel_TimerEventDefault(void* ptr, void* event);
int QVirtualKeyboardTrace_AddPoint(void* ptr, void* point);
void QVirtualKeyboardTrace_ConnectCanceledChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectCanceledChanged(void* ptr);
void QVirtualKeyboardTrace_CanceledChanged(void* ptr, char isCanceled);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardTrace_ChannelData(void* ptr, struct QtVirtualKeyboard_PackedString channel, int pos, int count);
struct QtVirtualKeyboard_PackedString QVirtualKeyboardTrace_Channels(void* ptr);
void QVirtualKeyboardTrace_ConnectChannelsChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectChannelsChanged(void* ptr);
void QVirtualKeyboardTrace_ChannelsChanged(void* ptr);
void QVirtualKeyboardTrace_ConnectFinalChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectFinalChanged(void* ptr);
void QVirtualKeyboardTrace_FinalChanged(void* ptr, char isFinal);
char QVirtualKeyboardTrace_IsCanceled(void* ptr);
char QVirtualKeyboardTrace_IsFinal(void* ptr);
int QVirtualKeyboardTrace_Length(void* ptr);
void QVirtualKeyboardTrace_ConnectLengthChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectLengthChanged(void* ptr);
void QVirtualKeyboardTrace_LengthChanged(void* ptr, int length);
double QVirtualKeyboardTrace_Opacity(void* ptr);
void QVirtualKeyboardTrace_ConnectOpacityChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectOpacityChanged(void* ptr);
void QVirtualKeyboardTrace_OpacityChanged(void* ptr, double opacity);
struct QtVirtualKeyboard_PackedList QVirtualKeyboardTrace_Points(void* ptr, int pos, int count);
void QVirtualKeyboardTrace_SetCanceled(void* ptr, char canceled);
void QVirtualKeyboardTrace_SetChannelData(void* ptr, struct QtVirtualKeyboard_PackedString channel, int index, void* data);
void QVirtualKeyboardTrace_SetChannels(void* ptr, struct QtVirtualKeyboard_PackedString channels);
void QVirtualKeyboardTrace_SetFinal(void* ptr, char final);
void QVirtualKeyboardTrace_SetOpacity(void* ptr, double opacity);
void QVirtualKeyboardTrace_SetTraceId(void* ptr, int id);
int QVirtualKeyboardTrace_TraceId(void* ptr);
void QVirtualKeyboardTrace_ConnectTraceIdChanged(void* ptr, long long t);
void QVirtualKeyboardTrace_DisconnectTraceIdChanged(void* ptr);
void QVirtualKeyboardTrace_TraceIdChanged(void* ptr, int traceId);
void* QVirtualKeyboardTrace___channelData_atList(void* ptr, int i);
void QVirtualKeyboardTrace___channelData_setList(void* ptr, void* i);
void* QVirtualKeyboardTrace___channelData_newList(void* ptr);
void* QVirtualKeyboardTrace___points_atList(void* ptr, int i);
void QVirtualKeyboardTrace___points_setList(void* ptr, void* i);
void* QVirtualKeyboardTrace___points_newList(void* ptr);
void* QVirtualKeyboardTrace___children_atList(void* ptr, int i);
void QVirtualKeyboardTrace___children_setList(void* ptr, void* i);
void* QVirtualKeyboardTrace___children_newList(void* ptr);
void* QVirtualKeyboardTrace___dynamicPropertyNames_atList(void* ptr, int i);
void QVirtualKeyboardTrace___dynamicPropertyNames_setList(void* ptr, void* i);
void* QVirtualKeyboardTrace___dynamicPropertyNames_newList(void* ptr);
void* QVirtualKeyboardTrace___findChildren_atList(void* ptr, int i);
void QVirtualKeyboardTrace___findChildren_setList(void* ptr, void* i);
void* QVirtualKeyboardTrace___findChildren_newList(void* ptr);
void* QVirtualKeyboardTrace___findChildren_atList3(void* ptr, int i);
void QVirtualKeyboardTrace___findChildren_setList3(void* ptr, void* i);
void* QVirtualKeyboardTrace___findChildren_newList3(void* ptr);
void QVirtualKeyboardTrace_ChildEventDefault(void* ptr, void* event);
void QVirtualKeyboardTrace_ConnectNotifyDefault(void* ptr, void* sign);
void QVirtualKeyboardTrace_CustomEventDefault(void* ptr, void* event);
void QVirtualKeyboardTrace_DeleteLaterDefault(void* ptr);
void QVirtualKeyboardTrace_DisconnectNotifyDefault(void* ptr, void* sign);
char QVirtualKeyboardTrace_EventDefault(void* ptr, void* e);
char QVirtualKeyboardTrace_EventFilterDefault(void* ptr, void* watched, void* event);
void* QVirtualKeyboardTrace_MetaObjectDefault(void* ptr);
void QVirtualKeyboardTrace_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif