#ifdef __cplusplus
extern "C" {
#endif

void QAbstractPlanarVideoBuffer_DestroyQAbstractPlanarVideoBuffer(void* ptr);
char* QAbstractPlanarVideoBuffer_ObjectNameAbs(void* ptr);
void QAbstractPlanarVideoBuffer_SetObjectNameAbs(void* ptr, char* name);
void* QAbstractVideoBuffer_Handle(void* ptr);
int QAbstractVideoBuffer_HandleType(void* ptr);
int QAbstractVideoBuffer_MapMode(void* ptr);
void QAbstractVideoBuffer_Release(void* ptr);
void QAbstractVideoBuffer_Unmap(void* ptr);
void QAbstractVideoBuffer_DestroyQAbstractVideoBuffer(void* ptr);
char* QAbstractVideoBuffer_ObjectNameAbs(void* ptr);
void QAbstractVideoBuffer_SetObjectNameAbs(void* ptr, char* name);
int QAbstractVideoFilter_IsActive(void* ptr);
void QAbstractVideoFilter_SetActive(void* ptr, int v);
void QAbstractVideoFilter_ConnectActiveChanged(void* ptr);
void QAbstractVideoFilter_DisconnectActiveChanged(void* ptr);
void* QAbstractVideoFilter_CreateFilterRunnable(void* ptr);
void* QAbstractVideoSurface_NativeResolution(void* ptr);
void QAbstractVideoSurface_ConnectActiveChanged(void* ptr);
void QAbstractVideoSurface_DisconnectActiveChanged(void* ptr);
int QAbstractVideoSurface_Error(void* ptr);
int QAbstractVideoSurface_IsActive(void* ptr);
int QAbstractVideoSurface_IsFormatSupported(void* ptr, void* format);
void QAbstractVideoSurface_ConnectNativeResolutionChanged(void* ptr);
void QAbstractVideoSurface_DisconnectNativeResolutionChanged(void* ptr);
int QAbstractVideoSurface_Present(void* ptr, void* frame);
int QAbstractVideoSurface_Start(void* ptr, void* format);
void QAbstractVideoSurface_Stop(void* ptr);
void QAbstractVideoSurface_ConnectSupportedFormatsChanged(void* ptr);
void QAbstractVideoSurface_DisconnectSupportedFormatsChanged(void* ptr);
void QAbstractVideoSurface_DestroyQAbstractVideoSurface(void* ptr);
void* QAudioBuffer_NewQAudioBuffer();
void* QAudioBuffer_NewQAudioBuffer3(void* other);
void* QAudioBuffer_NewQAudioBuffer4(void* data, void* format, long long startTime);
void* QAudioBuffer_NewQAudioBuffer5(int numFrames, void* format, long long startTime);
int QAudioBuffer_ByteCount(void* ptr);
void* QAudioBuffer_ConstData(void* ptr);
void* QAudioBuffer_Data2(void* ptr);
void* QAudioBuffer_Data(void* ptr);
long long QAudioBuffer_Duration(void* ptr);
int QAudioBuffer_FrameCount(void* ptr);
int QAudioBuffer_IsValid(void* ptr);
int QAudioBuffer_SampleCount(void* ptr);
long long QAudioBuffer_StartTime(void* ptr);
void QAudioBuffer_DestroyQAudioBuffer(void* ptr);
char* QAudioDecoder_ErrorString(void* ptr);
int QAudioDecoder_State(void* ptr);
void* QAudioDecoder_NewQAudioDecoder(void* parent);
int QAudioDecoder_BufferAvailable(void* ptr);
void QAudioDecoder_ConnectBufferAvailableChanged(void* ptr);
void QAudioDecoder_DisconnectBufferAvailableChanged(void* ptr);
void QAudioDecoder_ConnectBufferReady(void* ptr);
void QAudioDecoder_DisconnectBufferReady(void* ptr);
long long QAudioDecoder_Duration(void* ptr);
void QAudioDecoder_ConnectDurationChanged(void* ptr);
void QAudioDecoder_DisconnectDurationChanged(void* ptr);
void QAudioDecoder_ConnectError2(void* ptr);
void QAudioDecoder_DisconnectError2(void* ptr);
int QAudioDecoder_Error(void* ptr);
void QAudioDecoder_ConnectFinished(void* ptr);
void QAudioDecoder_DisconnectFinished(void* ptr);
long long QAudioDecoder_Position(void* ptr);
void QAudioDecoder_ConnectPositionChanged(void* ptr);
void QAudioDecoder_DisconnectPositionChanged(void* ptr);
void QAudioDecoder_SetAudioFormat(void* ptr, void* format);
void QAudioDecoder_SetSourceDevice(void* ptr, void* device);
void QAudioDecoder_SetSourceFilename(void* ptr, char* fileName);
void QAudioDecoder_ConnectSourceChanged(void* ptr);
void QAudioDecoder_DisconnectSourceChanged(void* ptr);
void* QAudioDecoder_SourceDevice(void* ptr);
char* QAudioDecoder_SourceFilename(void* ptr);
void QAudioDecoder_Start(void* ptr);
void QAudioDecoder_ConnectStateChanged(void* ptr);
void QAudioDecoder_DisconnectStateChanged(void* ptr);
void QAudioDecoder_Stop(void* ptr);
void QAudioDecoder_DestroyQAudioDecoder(void* ptr);
int QAudioDecoderControl_BufferAvailable(void* ptr);
void QAudioDecoderControl_ConnectBufferAvailableChanged(void* ptr);
void QAudioDecoderControl_DisconnectBufferAvailableChanged(void* ptr);
void QAudioDecoderControl_ConnectBufferReady(void* ptr);
void QAudioDecoderControl_DisconnectBufferReady(void* ptr);
long long QAudioDecoderControl_Duration(void* ptr);
void QAudioDecoderControl_ConnectDurationChanged(void* ptr);
void QAudioDecoderControl_DisconnectDurationChanged(void* ptr);
void QAudioDecoderControl_ConnectError(void* ptr);
void QAudioDecoderControl_DisconnectError(void* ptr);
void QAudioDecoderControl_ConnectFinished(void* ptr);
void QAudioDecoderControl_DisconnectFinished(void* ptr);
long long QAudioDecoderControl_Position(void* ptr);
void QAudioDecoderControl_ConnectPositionChanged(void* ptr);
void QAudioDecoderControl_DisconnectPositionChanged(void* ptr);
void QAudioDecoderControl_SetAudioFormat(void* ptr, void* format);
void QAudioDecoderControl_SetSourceDevice(void* ptr, void* device);
void QAudioDecoderControl_SetSourceFilename(void* ptr, char* fileName);
void QAudioDecoderControl_ConnectSourceChanged(void* ptr);
void QAudioDecoderControl_DisconnectSourceChanged(void* ptr);
void* QAudioDecoderControl_SourceDevice(void* ptr);
char* QAudioDecoderControl_SourceFilename(void* ptr);
void QAudioDecoderControl_Start(void* ptr);
int QAudioDecoderControl_State(void* ptr);
void QAudioDecoderControl_ConnectStateChanged(void* ptr);
void QAudioDecoderControl_DisconnectStateChanged(void* ptr);
void QAudioDecoderControl_Stop(void* ptr);
void QAudioDecoderControl_DestroyQAudioDecoderControl(void* ptr);
void* QAudioDeviceInfo_NewQAudioDeviceInfo();
void* QAudioDeviceInfo_NewQAudioDeviceInfo2(void* other);
char* QAudioDeviceInfo_DeviceName(void* ptr);
int QAudioDeviceInfo_IsFormatSupported(void* ptr, void* settings);
int QAudioDeviceInfo_IsNull(void* ptr);
char* QAudioDeviceInfo_SupportedCodecs(void* ptr);
void QAudioDeviceInfo_DestroyQAudioDeviceInfo(void* ptr);
void* QAudioEncoderSettings_NewQAudioEncoderSettings();
void* QAudioEncoderSettings_NewQAudioEncoderSettings2(void* other);
int QAudioEncoderSettings_BitRate(void* ptr);
int QAudioEncoderSettings_ChannelCount(void* ptr);
char* QAudioEncoderSettings_Codec(void* ptr);
void* QAudioEncoderSettings_EncodingOption(void* ptr, char* option);
int QAudioEncoderSettings_IsNull(void* ptr);
int QAudioEncoderSettings_SampleRate(void* ptr);
void QAudioEncoderSettings_SetBitRate(void* ptr, int rate);
void QAudioEncoderSettings_SetChannelCount(void* ptr, int channels);
void QAudioEncoderSettings_SetCodec(void* ptr, char* codec);
void QAudioEncoderSettings_SetEncodingOption(void* ptr, char* option, void* value);
void QAudioEncoderSettings_SetSampleRate(void* ptr, int rate);
void QAudioEncoderSettings_DestroyQAudioEncoderSettings(void* ptr);
char* QAudioEncoderSettingsControl_CodecDescription(void* ptr, char* codec);
void QAudioEncoderSettingsControl_SetAudioSettings(void* ptr, void* settings);
char* QAudioEncoderSettingsControl_SupportedAudioCodecs(void* ptr);
void QAudioEncoderSettingsControl_DestroyQAudioEncoderSettingsControl(void* ptr);
void* QAudioFormat_NewQAudioFormat();
void* QAudioFormat_NewQAudioFormat2(void* other);
int QAudioFormat_ByteOrder(void* ptr);
int QAudioFormat_BytesPerFrame(void* ptr);
int QAudioFormat_ChannelCount(void* ptr);
char* QAudioFormat_Codec(void* ptr);
int QAudioFormat_IsValid(void* ptr);
int QAudioFormat_SampleRate(void* ptr);
int QAudioFormat_SampleSize(void* ptr);
int QAudioFormat_SampleType(void* ptr);
void QAudioFormat_SetByteOrder(void* ptr, int byteOrder);
void QAudioFormat_SetChannelCount(void* ptr, int channels);
void QAudioFormat_SetCodec(void* ptr, char* codec);
void QAudioFormat_SetSampleRate(void* ptr, int samplerate);
void QAudioFormat_SetSampleSize(void* ptr, int sampleSize);
void QAudioFormat_SetSampleType(void* ptr, int sampleType);
void QAudioFormat_DestroyQAudioFormat(void* ptr);
void* QAudioInput_NewQAudioInput2(void* audioDevice, void* format, void* parent);
void* QAudioInput_NewQAudioInput(void* format, void* parent);
int QAudioInput_BufferSize(void* ptr);
int QAudioInput_BytesReady(void* ptr);
long long QAudioInput_ElapsedUSecs(void* ptr);
void QAudioInput_ConnectNotify(void* ptr);
void QAudioInput_DisconnectNotify(void* ptr);
int QAudioInput_NotifyInterval(void* ptr);
int QAudioInput_PeriodSize(void* ptr);
long long QAudioInput_ProcessedUSecs(void* ptr);
void QAudioInput_Reset(void* ptr);
void QAudioInput_Resume(void* ptr);
void QAudioInput_SetBufferSize(void* ptr, int value);
void QAudioInput_SetNotifyInterval(void* ptr, int ms);
void QAudioInput_SetVolume(void* ptr, double volume);
void* QAudioInput_Start2(void* ptr);
void QAudioInput_Start(void* ptr, void* device);
void QAudioInput_Stop(void* ptr);
void QAudioInput_Suspend(void* ptr);
double QAudioInput_Volume(void* ptr);
void QAudioInput_DestroyQAudioInput(void* ptr);
char* QAudioInputSelectorControl_ActiveInput(void* ptr);
void QAudioInputSelectorControl_ConnectActiveInputChanged(void* ptr);
void QAudioInputSelectorControl_DisconnectActiveInputChanged(void* ptr);
void QAudioInputSelectorControl_ConnectAvailableInputsChanged(void* ptr);
void QAudioInputSelectorControl_DisconnectAvailableInputsChanged(void* ptr);
char* QAudioInputSelectorControl_DefaultInput(void* ptr);
char* QAudioInputSelectorControl_InputDescription(void* ptr, char* name);
void QAudioInputSelectorControl_SetActiveInput(void* ptr, char* name);
void QAudioInputSelectorControl_DestroyQAudioInputSelectorControl(void* ptr);
void* QAudioOutput_NewQAudioOutput2(void* audioDevice, void* format, void* parent);
void* QAudioOutput_NewQAudioOutput(void* format, void* parent);
int QAudioOutput_BufferSize(void* ptr);
int QAudioOutput_BytesFree(void* ptr);
char* QAudioOutput_Category(void* ptr);
long long QAudioOutput_ElapsedUSecs(void* ptr);
void QAudioOutput_ConnectNotify(void* ptr);
void QAudioOutput_DisconnectNotify(void* ptr);
int QAudioOutput_NotifyInterval(void* ptr);
int QAudioOutput_PeriodSize(void* ptr);
long long QAudioOutput_ProcessedUSecs(void* ptr);
void QAudioOutput_Reset(void* ptr);
void QAudioOutput_Resume(void* ptr);
void QAudioOutput_SetBufferSize(void* ptr, int value);
void QAudioOutput_SetCategory(void* ptr, char* category);
void QAudioOutput_SetNotifyInterval(void* ptr, int ms);
void QAudioOutput_SetVolume(void* ptr, double volume);
void* QAudioOutput_Start2(void* ptr);
void QAudioOutput_Start(void* ptr, void* device);
void QAudioOutput_Stop(void* ptr);
void QAudioOutput_Suspend(void* ptr);
double QAudioOutput_Volume(void* ptr);
void QAudioOutput_DestroyQAudioOutput(void* ptr);
char* QAudioOutputSelectorControl_ActiveOutput(void* ptr);
void QAudioOutputSelectorControl_ConnectActiveOutputChanged(void* ptr);
void QAudioOutputSelectorControl_DisconnectActiveOutputChanged(void* ptr);
void QAudioOutputSelectorControl_ConnectAvailableOutputsChanged(void* ptr);
void QAudioOutputSelectorControl_DisconnectAvailableOutputsChanged(void* ptr);
char* QAudioOutputSelectorControl_DefaultOutput(void* ptr);
char* QAudioOutputSelectorControl_OutputDescription(void* ptr, char* name);
void QAudioOutputSelectorControl_SetActiveOutput(void* ptr, char* name);
void QAudioOutputSelectorControl_DestroyQAudioOutputSelectorControl(void* ptr);
void* QAudioProbe_NewQAudioProbe(void* parent);
void QAudioProbe_ConnectFlush(void* ptr);
void QAudioProbe_DisconnectFlush(void* ptr);
int QAudioProbe_IsActive(void* ptr);
int QAudioProbe_SetSource(void* ptr, void* source);
int QAudioProbe_SetSource2(void* ptr, void* mediaRecorder);
void QAudioProbe_DestroyQAudioProbe(void* ptr);
void* QAudioRecorder_NewQAudioRecorder(void* parent);
char* QAudioRecorder_AudioInput(void* ptr);
void QAudioRecorder_ConnectAudioInputChanged(void* ptr);
void QAudioRecorder_DisconnectAudioInputChanged(void* ptr);
char* QAudioRecorder_AudioInputDescription(void* ptr, char* name);
char* QAudioRecorder_AudioInputs(void* ptr);
void QAudioRecorder_ConnectAvailableAudioInputsChanged(void* ptr);
void QAudioRecorder_DisconnectAvailableAudioInputsChanged(void* ptr);
char* QAudioRecorder_DefaultAudioInput(void* ptr);
void QAudioRecorder_SetAudioInput(void* ptr, char* name);
void QAudioRecorder_DestroyQAudioRecorder(void* ptr);
int QCamera_CaptureMode(void* ptr);
void QCamera_SearchAndLock2(void* ptr, int locks);
void QCamera_SetCaptureMode(void* ptr, int mode);
int QCamera_State(void* ptr);
int QCamera_Status(void* ptr);
void* QCamera_NewQCamera4(int position, void* parent);
void* QCamera_NewQCamera(void* parent);
void* QCamera_NewQCamera2(void* deviceName, void* parent);
void* QCamera_NewQCamera3(void* cameraInfo, void* parent);
void QCamera_ConnectCaptureModeChanged(void* ptr);
void QCamera_DisconnectCaptureModeChanged(void* ptr);
void QCamera_ConnectError2(void* ptr);
void QCamera_DisconnectError2(void* ptr);
int QCamera_Error(void* ptr);
char* QCamera_ErrorString(void* ptr);
void* QCamera_Exposure(void* ptr);
void* QCamera_Focus(void* ptr);
void* QCamera_ImageProcessing(void* ptr);
int QCamera_IsCaptureModeSupported(void* ptr, int mode);
void QCamera_Load(void* ptr);
void QCamera_ConnectLockFailed(void* ptr);
void QCamera_DisconnectLockFailed(void* ptr);
int QCamera_LockStatus(void* ptr);
int QCamera_LockStatus2(void* ptr, int lockType);
void QCamera_ConnectLockStatusChanged(void* ptr);
void QCamera_DisconnectLockStatusChanged(void* ptr);
void QCamera_ConnectLockStatusChanged2(void* ptr);
void QCamera_DisconnectLockStatusChanged2(void* ptr);
void QCamera_ConnectLocked(void* ptr);
void QCamera_DisconnectLocked(void* ptr);
int QCamera_RequestedLocks(void* ptr);
void QCamera_SearchAndLock(void* ptr);
void QCamera_SetViewfinder3(void* ptr, void* surface);
void QCamera_SetViewfinder2(void* ptr, void* viewfinder);
void QCamera_SetViewfinder(void* ptr, void* viewfinder);
void QCamera_SetViewfinderSettings(void* ptr, void* settings);
void QCamera_Start(void* ptr);
void QCamera_ConnectStateChanged(void* ptr);
void QCamera_DisconnectStateChanged(void* ptr);
void QCamera_ConnectStatusChanged(void* ptr);
void QCamera_DisconnectStatusChanged(void* ptr);
void QCamera_Stop(void* ptr);
int QCamera_SupportedLocks(void* ptr);
void QCamera_Unload(void* ptr);
void QCamera_Unlock(void* ptr);
void QCamera_Unlock2(void* ptr, int locks);
void QCamera_DestroyQCamera(void* ptr);
int QCameraCaptureBufferFormatControl_BufferFormat(void* ptr);
void QCameraCaptureBufferFormatControl_ConnectBufferFormatChanged(void* ptr);
void QCameraCaptureBufferFormatControl_DisconnectBufferFormatChanged(void* ptr);
void QCameraCaptureBufferFormatControl_SetBufferFormat(void* ptr, int format);
void QCameraCaptureBufferFormatControl_DestroyQCameraCaptureBufferFormatControl(void* ptr);
int QCameraCaptureDestinationControl_CaptureDestination(void* ptr);
void QCameraCaptureDestinationControl_ConnectCaptureDestinationChanged(void* ptr);
void QCameraCaptureDestinationControl_DisconnectCaptureDestinationChanged(void* ptr);
int QCameraCaptureDestinationControl_IsCaptureDestinationSupported(void* ptr, int destination);
void QCameraCaptureDestinationControl_SetCaptureDestination(void* ptr, int destination);
void QCameraCaptureDestinationControl_DestroyQCameraCaptureDestinationControl(void* ptr);
int QCameraControl_CanChangeProperty(void* ptr, int changeType, int status);
int QCameraControl_CaptureMode(void* ptr);
void QCameraControl_ConnectCaptureModeChanged(void* ptr);
void QCameraControl_DisconnectCaptureModeChanged(void* ptr);
void QCameraControl_ConnectError(void* ptr);
void QCameraControl_DisconnectError(void* ptr);
int QCameraControl_IsCaptureModeSupported(void* ptr, int mode);
void QCameraControl_SetCaptureMode(void* ptr, int mode);
void QCameraControl_SetState(void* ptr, int state);
int QCameraControl_State(void* ptr);
void QCameraControl_ConnectStateChanged(void* ptr);
void QCameraControl_DisconnectStateChanged(void* ptr);
int QCameraControl_Status(void* ptr);
void QCameraControl_ConnectStatusChanged(void* ptr);
void QCameraControl_DisconnectStatusChanged(void* ptr);
void QCameraControl_DestroyQCameraControl(void* ptr);
double QCameraExposure_Aperture(void* ptr);
double QCameraExposure_ExposureCompensation(void* ptr);
int QCameraExposure_ExposureMode(void* ptr);
int QCameraExposure_FlashMode(void* ptr);
int QCameraExposure_IsoSensitivity(void* ptr);
int QCameraExposure_MeteringMode(void* ptr);
void QCameraExposure_SetAutoAperture(void* ptr);
void QCameraExposure_SetAutoIsoSensitivity(void* ptr);
void QCameraExposure_SetExposureCompensation(void* ptr, double ev);
void QCameraExposure_SetExposureMode(void* ptr, int mode);
void QCameraExposure_SetFlashMode(void* ptr, int mode);
void QCameraExposure_SetManualAperture(void* ptr, double aperture);
void QCameraExposure_SetManualIsoSensitivity(void* ptr, int iso);
void QCameraExposure_SetMeteringMode(void* ptr, int mode);
void QCameraExposure_SetSpotMeteringPoint(void* ptr, void* point);
void QCameraExposure_ConnectApertureChanged(void* ptr);
void QCameraExposure_DisconnectApertureChanged(void* ptr);
void QCameraExposure_ConnectApertureRangeChanged(void* ptr);
void QCameraExposure_DisconnectApertureRangeChanged(void* ptr);
void QCameraExposure_ConnectExposureCompensationChanged(void* ptr);
void QCameraExposure_DisconnectExposureCompensationChanged(void* ptr);
void QCameraExposure_ConnectFlashReady(void* ptr);
void QCameraExposure_DisconnectFlashReady(void* ptr);
int QCameraExposure_IsAvailable(void* ptr);
int QCameraExposure_IsExposureModeSupported(void* ptr, int mode);
int QCameraExposure_IsFlashModeSupported(void* ptr, int mode);
int QCameraExposure_IsFlashReady(void* ptr);
int QCameraExposure_IsMeteringModeSupported(void* ptr, int mode);
void QCameraExposure_ConnectIsoSensitivityChanged(void* ptr);
void QCameraExposure_DisconnectIsoSensitivityChanged(void* ptr);
double QCameraExposure_RequestedAperture(void* ptr);
int QCameraExposure_RequestedIsoSensitivity(void* ptr);
double QCameraExposure_RequestedShutterSpeed(void* ptr);
void QCameraExposure_SetAutoShutterSpeed(void* ptr);
void QCameraExposure_SetManualShutterSpeed(void* ptr, double seconds);
double QCameraExposure_ShutterSpeed(void* ptr);
void QCameraExposure_ConnectShutterSpeedChanged(void* ptr);
void QCameraExposure_DisconnectShutterSpeedChanged(void* ptr);
void QCameraExposure_ConnectShutterSpeedRangeChanged(void* ptr);
void QCameraExposure_DisconnectShutterSpeedRangeChanged(void* ptr);
void* QCameraExposureControl_ActualValue(void* ptr, int parameter);
void QCameraExposureControl_ConnectActualValueChanged(void* ptr);
void QCameraExposureControl_DisconnectActualValueChanged(void* ptr);
int QCameraExposureControl_IsParameterSupported(void* ptr, int parameter);
void QCameraExposureControl_ConnectParameterRangeChanged(void* ptr);
void QCameraExposureControl_DisconnectParameterRangeChanged(void* ptr);
void* QCameraExposureControl_RequestedValue(void* ptr, int parameter);
void QCameraExposureControl_ConnectRequestedValueChanged(void* ptr);
void QCameraExposureControl_DisconnectRequestedValueChanged(void* ptr);
int QCameraExposureControl_SetValue(void* ptr, int parameter, void* value);
void QCameraExposureControl_DestroyQCameraExposureControl(void* ptr);
int QCameraFeedbackControl_IsEventFeedbackEnabled(void* ptr, int event);
int QCameraFeedbackControl_IsEventFeedbackLocked(void* ptr, int event);
void QCameraFeedbackControl_ResetEventFeedback(void* ptr, int event);
int QCameraFeedbackControl_SetEventFeedbackEnabled(void* ptr, int event, int enabled);
int QCameraFeedbackControl_SetEventFeedbackSound(void* ptr, int event, char* filePath);
void QCameraFeedbackControl_DestroyQCameraFeedbackControl(void* ptr);
int QCameraFlashControl_FlashMode(void* ptr);
void QCameraFlashControl_ConnectFlashReady(void* ptr);
void QCameraFlashControl_DisconnectFlashReady(void* ptr);
int QCameraFlashControl_IsFlashModeSupported(void* ptr, int mode);
int QCameraFlashControl_IsFlashReady(void* ptr);
void QCameraFlashControl_SetFlashMode(void* ptr, int mode);
void QCameraFlashControl_DestroyQCameraFlashControl(void* ptr);
double QCameraFocus_DigitalZoom(void* ptr);
int QCameraFocus_FocusMode(void* ptr);
int QCameraFocus_FocusPointMode(void* ptr);
double QCameraFocus_OpticalZoom(void* ptr);
void QCameraFocus_SetCustomFocusPoint(void* ptr, void* point);
void QCameraFocus_SetFocusMode(void* ptr, int mode);
void QCameraFocus_SetFocusPointMode(void* ptr, int mode);
void QCameraFocus_ConnectDigitalZoomChanged(void* ptr);
void QCameraFocus_DisconnectDigitalZoomChanged(void* ptr);
void QCameraFocus_ConnectFocusZonesChanged(void* ptr);
void QCameraFocus_DisconnectFocusZonesChanged(void* ptr);
int QCameraFocus_IsAvailable(void* ptr);
int QCameraFocus_IsFocusModeSupported(void* ptr, int mode);
int QCameraFocus_IsFocusPointModeSupported(void* ptr, int mode);
double QCameraFocus_MaximumDigitalZoom(void* ptr);
void QCameraFocus_ConnectMaximumDigitalZoomChanged(void* ptr);
void QCameraFocus_DisconnectMaximumDigitalZoomChanged(void* ptr);
double QCameraFocus_MaximumOpticalZoom(void* ptr);
void QCameraFocus_ConnectMaximumOpticalZoomChanged(void* ptr);
void QCameraFocus_DisconnectMaximumOpticalZoomChanged(void* ptr);
void QCameraFocus_ConnectOpticalZoomChanged(void* ptr);
void QCameraFocus_DisconnectOpticalZoomChanged(void* ptr);
void QCameraFocus_ZoomTo(void* ptr, double optical, double digital);
int QCameraFocusControl_FocusMode(void* ptr);
void QCameraFocusControl_ConnectFocusModeChanged(void* ptr);
void QCameraFocusControl_DisconnectFocusModeChanged(void* ptr);
int QCameraFocusControl_FocusPointMode(void* ptr);
void QCameraFocusControl_ConnectFocusPointModeChanged(void* ptr);
void QCameraFocusControl_DisconnectFocusPointModeChanged(void* ptr);
void QCameraFocusControl_ConnectFocusZonesChanged(void* ptr);
void QCameraFocusControl_DisconnectFocusZonesChanged(void* ptr);
int QCameraFocusControl_IsFocusModeSupported(void* ptr, int mode);
int QCameraFocusControl_IsFocusPointModeSupported(void* ptr, int mode);
void QCameraFocusControl_SetCustomFocusPoint(void* ptr, void* point);
void QCameraFocusControl_SetFocusMode(void* ptr, int mode);
void QCameraFocusControl_SetFocusPointMode(void* ptr, int mode);
void QCameraFocusControl_DestroyQCameraFocusControl(void* ptr);
void* QCameraFocusZone_NewQCameraFocusZone(void* other);
int QCameraFocusZone_IsValid(void* ptr);
int QCameraFocusZone_Status(void* ptr);
void QCameraFocusZone_DestroyQCameraFocusZone(void* ptr);
int QCameraImageCapture_IsReadyForCapture(void* ptr);
void* QCameraImageCapture_NewQCameraImageCapture(void* mediaObject, void* parent);
int QCameraImageCapture_BufferFormat(void* ptr);
void QCameraImageCapture_ConnectBufferFormatChanged(void* ptr);
void QCameraImageCapture_DisconnectBufferFormatChanged(void* ptr);
void QCameraImageCapture_CancelCapture(void* ptr);
int QCameraImageCapture_Capture(void* ptr, char* file);
int QCameraImageCapture_CaptureDestination(void* ptr);
void QCameraImageCapture_ConnectCaptureDestinationChanged(void* ptr);
void QCameraImageCapture_DisconnectCaptureDestinationChanged(void* ptr);
void QCameraImageCapture_ConnectError2(void* ptr);
void QCameraImageCapture_DisconnectError2(void* ptr);
int QCameraImageCapture_Error(void* ptr);
char* QCameraImageCapture_ErrorString(void* ptr);
char* QCameraImageCapture_ImageCodecDescription(void* ptr, char* codec);
void QCameraImageCapture_ConnectImageExposed(void* ptr);
void QCameraImageCapture_DisconnectImageExposed(void* ptr);
void QCameraImageCapture_ConnectImageMetadataAvailable(void* ptr);
void QCameraImageCapture_DisconnectImageMetadataAvailable(void* ptr);
void QCameraImageCapture_ConnectImageSaved(void* ptr);
void QCameraImageCapture_DisconnectImageSaved(void* ptr);
int QCameraImageCapture_IsAvailable(void* ptr);
int QCameraImageCapture_IsCaptureDestinationSupported(void* ptr, int destination);
void* QCameraImageCapture_MediaObject(void* ptr);
void QCameraImageCapture_ConnectReadyForCaptureChanged(void* ptr);
void QCameraImageCapture_DisconnectReadyForCaptureChanged(void* ptr);
void QCameraImageCapture_SetBufferFormat(void* ptr, int format);
void QCameraImageCapture_SetCaptureDestination(void* ptr, int destination);
void QCameraImageCapture_SetEncodingSettings(void* ptr, void* settings);
char* QCameraImageCapture_SupportedImageCodecs(void* ptr);
void QCameraImageCapture_DestroyQCameraImageCapture(void* ptr);
void QCameraImageCaptureControl_CancelCapture(void* ptr);
int QCameraImageCaptureControl_Capture(void* ptr, char* fileName);
int QCameraImageCaptureControl_DriveMode(void* ptr);
void QCameraImageCaptureControl_ConnectError(void* ptr);
void QCameraImageCaptureControl_DisconnectError(void* ptr);
void QCameraImageCaptureControl_ConnectImageExposed(void* ptr);
void QCameraImageCaptureControl_DisconnectImageExposed(void* ptr);
void QCameraImageCaptureControl_ConnectImageMetadataAvailable(void* ptr);
void QCameraImageCaptureControl_DisconnectImageMetadataAvailable(void* ptr);
void QCameraImageCaptureControl_ConnectImageSaved(void* ptr);
void QCameraImageCaptureControl_DisconnectImageSaved(void* ptr);
int QCameraImageCaptureControl_IsReadyForCapture(void* ptr);
void QCameraImageCaptureControl_ConnectReadyForCaptureChanged(void* ptr);
void QCameraImageCaptureControl_DisconnectReadyForCaptureChanged(void* ptr);
void QCameraImageCaptureControl_SetDriveMode(void* ptr, int mode);
void QCameraImageCaptureControl_DestroyQCameraImageCaptureControl(void* ptr);
int QCameraImageProcessing_ColorFilter(void* ptr);
double QCameraImageProcessing_Contrast(void* ptr);
double QCameraImageProcessing_DenoisingLevel(void* ptr);
int QCameraImageProcessing_IsAvailable(void* ptr);
int QCameraImageProcessing_IsColorFilterSupported(void* ptr, int filter);
int QCameraImageProcessing_IsWhiteBalanceModeSupported(void* ptr, int mode);
double QCameraImageProcessing_ManualWhiteBalance(void* ptr);
double QCameraImageProcessing_Saturation(void* ptr);
void QCameraImageProcessing_SetColorFilter(void* ptr, int filter);
void QCameraImageProcessing_SetContrast(void* ptr, double value);
void QCameraImageProcessing_SetDenoisingLevel(void* ptr, double level);
void QCameraImageProcessing_SetManualWhiteBalance(void* ptr, double colorTemperature);
void QCameraImageProcessing_SetSaturation(void* ptr, double value);
void QCameraImageProcessing_SetSharpeningLevel(void* ptr, double level);
void QCameraImageProcessing_SetWhiteBalanceMode(void* ptr, int mode);
double QCameraImageProcessing_SharpeningLevel(void* ptr);
int QCameraImageProcessing_WhiteBalanceMode(void* ptr);
int QCameraImageProcessingControl_IsParameterSupported(void* ptr, int parameter);
int QCameraImageProcessingControl_IsParameterValueSupported(void* ptr, int parameter, void* value);
void* QCameraImageProcessingControl_Parameter(void* ptr, int parameter);
void QCameraImageProcessingControl_SetParameter(void* ptr, int parameter, void* value);
void QCameraImageProcessingControl_DestroyQCameraImageProcessingControl(void* ptr);
void* QCameraInfo_NewQCameraInfo(void* name);
void* QCameraInfo_NewQCameraInfo2(void* camera);
void* QCameraInfo_NewQCameraInfo3(void* other);
char* QCameraInfo_Description(void* ptr);
char* QCameraInfo_DeviceName(void* ptr);
int QCameraInfo_IsNull(void* ptr);
int QCameraInfo_Orientation(void* ptr);
int QCameraInfo_Position(void* ptr);
void QCameraInfo_DestroyQCameraInfo(void* ptr);
int QCameraInfoControl_CameraOrientation(void* ptr, char* deviceName);
int QCameraInfoControl_CameraPosition(void* ptr, char* deviceName);
void QCameraInfoControl_DestroyQCameraInfoControl(void* ptr);
int QCameraLocksControl_LockStatus(void* ptr, int lock);
void QCameraLocksControl_ConnectLockStatusChanged(void* ptr);
void QCameraLocksControl_DisconnectLockStatusChanged(void* ptr);
void QCameraLocksControl_SearchAndLock(void* ptr, int locks);
int QCameraLocksControl_SupportedLocks(void* ptr);
void QCameraLocksControl_Unlock(void* ptr, int locks);
void QCameraLocksControl_DestroyQCameraLocksControl(void* ptr);
void* QCameraViewfinderSettings_NewQCameraViewfinderSettings();
void* QCameraViewfinderSettings_NewQCameraViewfinderSettings2(void* other);
int QCameraViewfinderSettings_IsNull(void* ptr);
double QCameraViewfinderSettings_MaximumFrameRate(void* ptr);
double QCameraViewfinderSettings_MinimumFrameRate(void* ptr);
void* QCameraViewfinderSettings_PixelAspectRatio(void* ptr);
int QCameraViewfinderSettings_PixelFormat(void* ptr);
void* QCameraViewfinderSettings_Resolution(void* ptr);
void QCameraViewfinderSettings_SetMaximumFrameRate(void* ptr, double rate);
void QCameraViewfinderSettings_SetMinimumFrameRate(void* ptr, double rate);
void QCameraViewfinderSettings_SetPixelAspectRatio(void* ptr, void* ratio);
void QCameraViewfinderSettings_SetPixelAspectRatio2(void* ptr, int horizontal, int vertical);
void QCameraViewfinderSettings_SetPixelFormat(void* ptr, int format);
void QCameraViewfinderSettings_SetResolution(void* ptr, void* resolution);
void QCameraViewfinderSettings_SetResolution2(void* ptr, int width, int height);
void QCameraViewfinderSettings_Swap(void* ptr, void* other);
void QCameraViewfinderSettings_DestroyQCameraViewfinderSettings(void* ptr);
int QCameraViewfinderSettingsControl_IsViewfinderParameterSupported(void* ptr, int parameter);
void QCameraViewfinderSettingsControl_SetViewfinderParameter(void* ptr, int parameter, void* value);
void* QCameraViewfinderSettingsControl_ViewfinderParameter(void* ptr, int parameter);
void QCameraViewfinderSettingsControl_DestroyQCameraViewfinderSettingsControl(void* ptr);
void QCameraViewfinderSettingsControl2_SetViewfinderSettings(void* ptr, void* settings);
void QCameraViewfinderSettingsControl2_DestroyQCameraViewfinderSettingsControl2(void* ptr);
double QCameraZoomControl_CurrentDigitalZoom(void* ptr);
void QCameraZoomControl_ConnectCurrentDigitalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectCurrentDigitalZoomChanged(void* ptr);
double QCameraZoomControl_CurrentOpticalZoom(void* ptr);
void QCameraZoomControl_ConnectCurrentOpticalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectCurrentOpticalZoomChanged(void* ptr);
double QCameraZoomControl_MaximumDigitalZoom(void* ptr);
void QCameraZoomControl_ConnectMaximumDigitalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectMaximumDigitalZoomChanged(void* ptr);
double QCameraZoomControl_MaximumOpticalZoom(void* ptr);
void QCameraZoomControl_ConnectMaximumOpticalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectMaximumOpticalZoomChanged(void* ptr);
double QCameraZoomControl_RequestedDigitalZoom(void* ptr);
void QCameraZoomControl_ConnectRequestedDigitalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectRequestedDigitalZoomChanged(void* ptr);
double QCameraZoomControl_RequestedOpticalZoom(void* ptr);
void QCameraZoomControl_ConnectRequestedOpticalZoomChanged(void* ptr);
void QCameraZoomControl_DisconnectRequestedOpticalZoomChanged(void* ptr);
void QCameraZoomControl_ZoomTo(void* ptr, double optical, double digital);
void QCameraZoomControl_DestroyQCameraZoomControl(void* ptr);
char* QImageEncoderControl_ImageCodecDescription(void* ptr, char* codec);
void QImageEncoderControl_SetImageSettings(void* ptr, void* settings);
char* QImageEncoderControl_SupportedImageCodecs(void* ptr);
void QImageEncoderControl_DestroyQImageEncoderControl(void* ptr);
void* QImageEncoderSettings_NewQImageEncoderSettings();
void* QImageEncoderSettings_NewQImageEncoderSettings2(void* other);
char* QImageEncoderSettings_Codec(void* ptr);
void* QImageEncoderSettings_EncodingOption(void* ptr, char* option);
int QImageEncoderSettings_IsNull(void* ptr);
void* QImageEncoderSettings_Resolution(void* ptr);
void QImageEncoderSettings_SetCodec(void* ptr, char* codec);
void QImageEncoderSettings_SetEncodingOption(void* ptr, char* option, void* value);
void QImageEncoderSettings_SetResolution(void* ptr, void* resolution);
void QImageEncoderSettings_SetResolution2(void* ptr, int width, int height);
void QImageEncoderSettings_DestroyQImageEncoderSettings(void* ptr);
void QMediaAudioProbeControl_ConnectFlush(void* ptr);
void QMediaAudioProbeControl_DisconnectFlush(void* ptr);
void QMediaAudioProbeControl_DestroyQMediaAudioProbeControl(void* ptr);
void QMediaAvailabilityControl_DestroyQMediaAvailabilityControl(void* ptr);
void* QMediaBindableInterface_MediaObject(void* ptr);
void QMediaBindableInterface_DestroyQMediaBindableInterface(void* ptr);
char* QMediaBindableInterface_ObjectNameAbs(void* ptr);
void QMediaBindableInterface_SetObjectNameAbs(void* ptr, char* name);
char* QMediaContainerControl_ContainerDescription(void* ptr, char* format);
char* QMediaContainerControl_ContainerFormat(void* ptr);
void QMediaContainerControl_SetContainerFormat(void* ptr, char* format);
char* QMediaContainerControl_SupportedContainers(void* ptr);
void QMediaContainerControl_DestroyQMediaContainerControl(void* ptr);
void* QMediaContent_NewQMediaContent();
void* QMediaContent_NewQMediaContent7(void* playlist, void* contentUrl, int takeOwnership);
void* QMediaContent_NewQMediaContent6(void* other);
void* QMediaContent_NewQMediaContent4(void* resource);
void* QMediaContent_NewQMediaContent3(void* request);
void* QMediaContent_NewQMediaContent2(void* url);
void* QMediaContent_CanonicalUrl(void* ptr);
int QMediaContent_IsNull(void* ptr);
void* QMediaContent_Playlist(void* ptr);
void QMediaContent_DestroyQMediaContent(void* ptr);
void QMediaControl_DestroyQMediaControl(void* ptr);
void QMediaGaplessPlaybackControl_ConnectAdvancedToNextMedia(void* ptr);
void QMediaGaplessPlaybackControl_DisconnectAdvancedToNextMedia(void* ptr);
double QMediaGaplessPlaybackControl_CrossfadeTime(void* ptr);
void QMediaGaplessPlaybackControl_ConnectCrossfadeTimeChanged(void* ptr);
void QMediaGaplessPlaybackControl_DisconnectCrossfadeTimeChanged(void* ptr);
int QMediaGaplessPlaybackControl_IsCrossfadeSupported(void* ptr);
void QMediaGaplessPlaybackControl_SetCrossfadeTime(void* ptr, double crossfadeTime);
void QMediaGaplessPlaybackControl_SetNextMedia(void* ptr, void* media);
void QMediaGaplessPlaybackControl_DestroyQMediaGaplessPlaybackControl(void* ptr);
void QMediaNetworkAccessControl_DestroyQMediaNetworkAccessControl(void* ptr);
int QMediaObject_NotifyInterval(void* ptr);
void QMediaObject_SetNotifyInterval(void* ptr, int milliSeconds);
void QMediaObject_ConnectAvailabilityChanged(void* ptr);
void QMediaObject_DisconnectAvailabilityChanged(void* ptr);
char* QMediaObject_AvailableMetaData(void* ptr);
int QMediaObject_Bind(void* ptr, void* object);
int QMediaObject_IsAvailable(void* ptr);
int QMediaObject_IsMetaDataAvailable(void* ptr);
void* QMediaObject_MetaData(void* ptr, char* key);
void QMediaObject_ConnectMetaDataAvailableChanged(void* ptr);
void QMediaObject_DisconnectMetaDataAvailableChanged(void* ptr);
void QMediaObject_ConnectMetaDataChanged(void* ptr);
void QMediaObject_DisconnectMetaDataChanged(void* ptr);
void QMediaObject_ConnectMetaDataChanged2(void* ptr);
void QMediaObject_DisconnectMetaDataChanged2(void* ptr);
void QMediaObject_ConnectNotifyIntervalChanged(void* ptr);
void QMediaObject_DisconnectNotifyIntervalChanged(void* ptr);
void* QMediaObject_Service(void* ptr);
void QMediaObject_Unbind(void* ptr, void* object);
void QMediaObject_DestroyQMediaObject(void* ptr);
int QMediaPlayer_BufferStatus(void* ptr);
long long QMediaPlayer_Duration(void* ptr);
char* QMediaPlayer_ErrorString(void* ptr);
int QMediaPlayer_IsAudioAvailable(void* ptr);
int QMediaPlayer_IsMuted(void* ptr);
int QMediaPlayer_IsSeekable(void* ptr);
int QMediaPlayer_IsVideoAvailable(void* ptr);
int QMediaPlayer_MediaStatus(void* ptr);
double QMediaPlayer_PlaybackRate(void* ptr);
void* QMediaPlayer_Playlist(void* ptr);
long long QMediaPlayer_Position(void* ptr);
void QMediaPlayer_SetMuted(void* ptr, int muted);
void QMediaPlayer_SetPlaybackRate(void* ptr, double rate);
void QMediaPlayer_SetPlaylist(void* ptr, void* playlist);
void QMediaPlayer_SetPosition(void* ptr, long long position);
void QMediaPlayer_SetVideoOutput2(void* ptr, void* output);
void QMediaPlayer_SetVideoOutput(void* ptr, void* output);
void QMediaPlayer_SetVolume(void* ptr, int volume);
int QMediaPlayer_State(void* ptr);
int QMediaPlayer_Volume(void* ptr);
void* QMediaPlayer_NewQMediaPlayer(void* parent, int flags);
void QMediaPlayer_ConnectAudioAvailableChanged(void* ptr);
void QMediaPlayer_DisconnectAudioAvailableChanged(void* ptr);
void QMediaPlayer_ConnectBufferStatusChanged(void* ptr);
void QMediaPlayer_DisconnectBufferStatusChanged(void* ptr);
void QMediaPlayer_ConnectDurationChanged(void* ptr);
void QMediaPlayer_DisconnectDurationChanged(void* ptr);
void QMediaPlayer_ConnectError2(void* ptr);
void QMediaPlayer_DisconnectError2(void* ptr);
int QMediaPlayer_Error(void* ptr);
void QMediaPlayer_ConnectMediaStatusChanged(void* ptr);
void QMediaPlayer_DisconnectMediaStatusChanged(void* ptr);
void* QMediaPlayer_MediaStream(void* ptr);
void QMediaPlayer_ConnectMutedChanged(void* ptr);
void QMediaPlayer_DisconnectMutedChanged(void* ptr);
void QMediaPlayer_Pause(void* ptr);
void QMediaPlayer_Play(void* ptr);
void QMediaPlayer_ConnectPlaybackRateChanged(void* ptr);
void QMediaPlayer_DisconnectPlaybackRateChanged(void* ptr);
void QMediaPlayer_ConnectPositionChanged(void* ptr);
void QMediaPlayer_DisconnectPositionChanged(void* ptr);
void QMediaPlayer_ConnectSeekableChanged(void* ptr);
void QMediaPlayer_DisconnectSeekableChanged(void* ptr);
void QMediaPlayer_SetMedia(void* ptr, void* media, void* stream);
void QMediaPlayer_SetVideoOutput3(void* ptr, void* surface);
void QMediaPlayer_ConnectStateChanged(void* ptr);
void QMediaPlayer_DisconnectStateChanged(void* ptr);
void QMediaPlayer_Stop(void* ptr);
void QMediaPlayer_ConnectVideoAvailableChanged(void* ptr);
void QMediaPlayer_DisconnectVideoAvailableChanged(void* ptr);
void QMediaPlayer_ConnectVolumeChanged(void* ptr);
void QMediaPlayer_DisconnectVolumeChanged(void* ptr);
void QMediaPlayer_DestroyQMediaPlayer(void* ptr);
void QMediaPlayerControl_ConnectAudioAvailableChanged(void* ptr);
void QMediaPlayerControl_DisconnectAudioAvailableChanged(void* ptr);
int QMediaPlayerControl_BufferStatus(void* ptr);
void QMediaPlayerControl_ConnectBufferStatusChanged(void* ptr);
void QMediaPlayerControl_DisconnectBufferStatusChanged(void* ptr);
long long QMediaPlayerControl_Duration(void* ptr);
void QMediaPlayerControl_ConnectDurationChanged(void* ptr);
void QMediaPlayerControl_DisconnectDurationChanged(void* ptr);
void QMediaPlayerControl_ConnectError(void* ptr);
void QMediaPlayerControl_DisconnectError(void* ptr);
int QMediaPlayerControl_IsAudioAvailable(void* ptr);
int QMediaPlayerControl_IsMuted(void* ptr);
int QMediaPlayerControl_IsSeekable(void* ptr);
int QMediaPlayerControl_IsVideoAvailable(void* ptr);
int QMediaPlayerControl_MediaStatus(void* ptr);
void QMediaPlayerControl_ConnectMediaStatusChanged(void* ptr);
void QMediaPlayerControl_DisconnectMediaStatusChanged(void* ptr);
void* QMediaPlayerControl_MediaStream(void* ptr);
void QMediaPlayerControl_ConnectMutedChanged(void* ptr);
void QMediaPlayerControl_DisconnectMutedChanged(void* ptr);
void QMediaPlayerControl_Pause(void* ptr);
void QMediaPlayerControl_Play(void* ptr);
double QMediaPlayerControl_PlaybackRate(void* ptr);
void QMediaPlayerControl_ConnectPlaybackRateChanged(void* ptr);
void QMediaPlayerControl_DisconnectPlaybackRateChanged(void* ptr);
long long QMediaPlayerControl_Position(void* ptr);
void QMediaPlayerControl_ConnectPositionChanged(void* ptr);
void QMediaPlayerControl_DisconnectPositionChanged(void* ptr);
void QMediaPlayerControl_ConnectSeekableChanged(void* ptr);
void QMediaPlayerControl_DisconnectSeekableChanged(void* ptr);
void QMediaPlayerControl_SetMedia(void* ptr, void* media, void* stream);
void QMediaPlayerControl_SetMuted(void* ptr, int mute);
void QMediaPlayerControl_SetPlaybackRate(void* ptr, double rate);
void QMediaPlayerControl_SetPosition(void* ptr, long long position);
void QMediaPlayerControl_SetVolume(void* ptr, int volume);
int QMediaPlayerControl_State(void* ptr);
void QMediaPlayerControl_ConnectStateChanged(void* ptr);
void QMediaPlayerControl_DisconnectStateChanged(void* ptr);
void QMediaPlayerControl_Stop(void* ptr);
void QMediaPlayerControl_ConnectVideoAvailableChanged(void* ptr);
void QMediaPlayerControl_DisconnectVideoAvailableChanged(void* ptr);
int QMediaPlayerControl_Volume(void* ptr);
void QMediaPlayerControl_ConnectVolumeChanged(void* ptr);
void QMediaPlayerControl_DisconnectVolumeChanged(void* ptr);
void QMediaPlayerControl_DestroyQMediaPlayerControl(void* ptr);
int QMediaPlaylist_PlaybackMode(void* ptr);
void QMediaPlaylist_SetPlaybackMode(void* ptr, int mode);
void* QMediaPlaylist_NewQMediaPlaylist(void* parent);
int QMediaPlaylist_AddMedia(void* ptr, void* content);
int QMediaPlaylist_Clear(void* ptr);
int QMediaPlaylist_CurrentIndex(void* ptr);
void QMediaPlaylist_ConnectCurrentIndexChanged(void* ptr);
void QMediaPlaylist_DisconnectCurrentIndexChanged(void* ptr);
int QMediaPlaylist_Error(void* ptr);
char* QMediaPlaylist_ErrorString(void* ptr);
int QMediaPlaylist_InsertMedia(void* ptr, int pos, void* content);
int QMediaPlaylist_IsEmpty(void* ptr);
int QMediaPlaylist_IsReadOnly(void* ptr);
void QMediaPlaylist_Load3(void* ptr, void* device, char* format);
void QMediaPlaylist_Load(void* ptr, void* request, char* format);
void QMediaPlaylist_Load2(void* ptr, void* location, char* format);
void QMediaPlaylist_ConnectLoadFailed(void* ptr);
void QMediaPlaylist_DisconnectLoadFailed(void* ptr);
void QMediaPlaylist_ConnectLoaded(void* ptr);
void QMediaPlaylist_DisconnectLoaded(void* ptr);
void QMediaPlaylist_ConnectMediaAboutToBeInserted(void* ptr);
void QMediaPlaylist_DisconnectMediaAboutToBeInserted(void* ptr);
void QMediaPlaylist_ConnectMediaAboutToBeRemoved(void* ptr);
void QMediaPlaylist_DisconnectMediaAboutToBeRemoved(void* ptr);
void QMediaPlaylist_ConnectMediaChanged(void* ptr);
void QMediaPlaylist_DisconnectMediaChanged(void* ptr);
int QMediaPlaylist_MediaCount(void* ptr);
void QMediaPlaylist_ConnectMediaInserted(void* ptr);
void QMediaPlaylist_DisconnectMediaInserted(void* ptr);
void* QMediaPlaylist_MediaObject(void* ptr);
void QMediaPlaylist_ConnectMediaRemoved(void* ptr);
void QMediaPlaylist_DisconnectMediaRemoved(void* ptr);
void QMediaPlaylist_Next(void* ptr);
int QMediaPlaylist_NextIndex(void* ptr, int steps);
void QMediaPlaylist_ConnectPlaybackModeChanged(void* ptr);
void QMediaPlaylist_DisconnectPlaybackModeChanged(void* ptr);
void QMediaPlaylist_Previous(void* ptr);
int QMediaPlaylist_PreviousIndex(void* ptr, int steps);
int QMediaPlaylist_RemoveMedia(void* ptr, int pos);
int QMediaPlaylist_RemoveMedia2(void* ptr, int start, int end);
int QMediaPlaylist_Save2(void* ptr, void* device, char* format);
int QMediaPlaylist_Save(void* ptr, void* location, char* format);
void QMediaPlaylist_SetCurrentIndex(void* ptr, int playlistPosition);
void QMediaPlaylist_Shuffle(void* ptr);
void QMediaPlaylist_DestroyQMediaPlaylist(void* ptr);
void* QMediaRecorder_ActualLocation(void* ptr);
long long QMediaRecorder_Duration(void* ptr);
int QMediaRecorder_IsMetaDataAvailable(void* ptr);
int QMediaRecorder_IsMetaDataWritable(void* ptr);
int QMediaRecorder_IsMuted(void* ptr);
void* QMediaRecorder_OutputLocation(void* ptr);
void QMediaRecorder_SetMuted(void* ptr, int muted);
int QMediaRecorder_SetOutputLocation(void* ptr, void* location);
void QMediaRecorder_SetVolume(void* ptr, double volume);
double QMediaRecorder_Volume(void* ptr);
void* QMediaRecorder_NewQMediaRecorder(void* mediaObject, void* parent);
void QMediaRecorder_ConnectActualLocationChanged(void* ptr);
void QMediaRecorder_DisconnectActualLocationChanged(void* ptr);
char* QMediaRecorder_AudioCodecDescription(void* ptr, char* codec);
void QMediaRecorder_ConnectAvailabilityChanged(void* ptr);
void QMediaRecorder_DisconnectAvailabilityChanged(void* ptr);
char* QMediaRecorder_AvailableMetaData(void* ptr);
char* QMediaRecorder_ContainerDescription(void* ptr, char* format);
char* QMediaRecorder_ContainerFormat(void* ptr);
void QMediaRecorder_ConnectDurationChanged(void* ptr);
void QMediaRecorder_DisconnectDurationChanged(void* ptr);
void QMediaRecorder_ConnectError2(void* ptr);
void QMediaRecorder_DisconnectError2(void* ptr);
int QMediaRecorder_Error(void* ptr);
char* QMediaRecorder_ErrorString(void* ptr);
int QMediaRecorder_IsAvailable(void* ptr);
void* QMediaRecorder_MediaObject(void* ptr);
void* QMediaRecorder_MetaData(void* ptr, char* key);
void QMediaRecorder_ConnectMetaDataAvailableChanged(void* ptr);
void QMediaRecorder_DisconnectMetaDataAvailableChanged(void* ptr);
void QMediaRecorder_ConnectMetaDataChanged(void* ptr);
void QMediaRecorder_DisconnectMetaDataChanged(void* ptr);
void QMediaRecorder_ConnectMetaDataChanged2(void* ptr);
void QMediaRecorder_DisconnectMetaDataChanged2(void* ptr);
void QMediaRecorder_ConnectMetaDataWritableChanged(void* ptr);
void QMediaRecorder_DisconnectMetaDataWritableChanged(void* ptr);
void QMediaRecorder_ConnectMutedChanged(void* ptr);
void QMediaRecorder_DisconnectMutedChanged(void* ptr);
void QMediaRecorder_Pause(void* ptr);
void QMediaRecorder_Record(void* ptr);
void QMediaRecorder_SetAudioSettings(void* ptr, void* settings);
void QMediaRecorder_SetContainerFormat(void* ptr, char* container);
void QMediaRecorder_SetEncodingSettings(void* ptr, void* audio, void* video, char* container);
void QMediaRecorder_SetMetaData(void* ptr, char* key, void* value);
void QMediaRecorder_SetVideoSettings(void* ptr, void* settings);
int QMediaRecorder_State(void* ptr);
void QMediaRecorder_ConnectStateChanged(void* ptr);
void QMediaRecorder_DisconnectStateChanged(void* ptr);
int QMediaRecorder_Status(void* ptr);
void QMediaRecorder_ConnectStatusChanged(void* ptr);
void QMediaRecorder_DisconnectStatusChanged(void* ptr);
void QMediaRecorder_Stop(void* ptr);
char* QMediaRecorder_SupportedAudioCodecs(void* ptr);
char* QMediaRecorder_SupportedContainers(void* ptr);
char* QMediaRecorder_SupportedVideoCodecs(void* ptr);
char* QMediaRecorder_VideoCodecDescription(void* ptr, char* codec);
void QMediaRecorder_ConnectVolumeChanged(void* ptr);
void QMediaRecorder_DisconnectVolumeChanged(void* ptr);
void QMediaRecorder_DestroyQMediaRecorder(void* ptr);
void QMediaRecorderControl_ConnectActualLocationChanged(void* ptr);
void QMediaRecorderControl_DisconnectActualLocationChanged(void* ptr);
void QMediaRecorderControl_ApplySettings(void* ptr);
long long QMediaRecorderControl_Duration(void* ptr);
void QMediaRecorderControl_ConnectDurationChanged(void* ptr);
void QMediaRecorderControl_DisconnectDurationChanged(void* ptr);
void QMediaRecorderControl_ConnectError(void* ptr);
void QMediaRecorderControl_DisconnectError(void* ptr);
int QMediaRecorderControl_IsMuted(void* ptr);
void QMediaRecorderControl_ConnectMutedChanged(void* ptr);
void QMediaRecorderControl_DisconnectMutedChanged(void* ptr);
void* QMediaRecorderControl_OutputLocation(void* ptr);
void QMediaRecorderControl_SetMuted(void* ptr, int muted);
int QMediaRecorderControl_SetOutputLocation(void* ptr, void* location);
void QMediaRecorderControl_SetState(void* ptr, int state);
void QMediaRecorderControl_SetVolume(void* ptr, double gain);
int QMediaRecorderControl_State(void* ptr);
void QMediaRecorderControl_ConnectStateChanged(void* ptr);
void QMediaRecorderControl_DisconnectStateChanged(void* ptr);
int QMediaRecorderControl_Status(void* ptr);
void QMediaRecorderControl_ConnectStatusChanged(void* ptr);
void QMediaRecorderControl_DisconnectStatusChanged(void* ptr);
double QMediaRecorderControl_Volume(void* ptr);
void QMediaRecorderControl_ConnectVolumeChanged(void* ptr);
void QMediaRecorderControl_DisconnectVolumeChanged(void* ptr);
void QMediaRecorderControl_DestroyQMediaRecorderControl(void* ptr);
void* QMediaResource_NewQMediaResource();
void* QMediaResource_NewQMediaResource4(void* other);
void* QMediaResource_NewQMediaResource3(void* request, char* mimeType);
void* QMediaResource_NewQMediaResource2(void* url, char* mimeType);
int QMediaResource_AudioBitRate(void* ptr);
char* QMediaResource_AudioCodec(void* ptr);
int QMediaResource_ChannelCount(void* ptr);
long long QMediaResource_DataSize(void* ptr);
int QMediaResource_IsNull(void* ptr);
char* QMediaResource_Language(void* ptr);
char* QMediaResource_MimeType(void* ptr);
void* QMediaResource_Resolution(void* ptr);
int QMediaResource_SampleRate(void* ptr);
void QMediaResource_SetAudioBitRate(void* ptr, int rate);
void QMediaResource_SetAudioCodec(void* ptr, char* codec);
void QMediaResource_SetChannelCount(void* ptr, int channels);
void QMediaResource_SetDataSize(void* ptr, long long size);
void QMediaResource_SetLanguage(void* ptr, char* language);
void QMediaResource_SetResolution(void* ptr, void* resolution);
void QMediaResource_SetResolution2(void* ptr, int width, int height);
void QMediaResource_SetSampleRate(void* ptr, int sampleRate);
void QMediaResource_SetVideoBitRate(void* ptr, int rate);
void QMediaResource_SetVideoCodec(void* ptr, char* codec);
void* QMediaResource_Url(void* ptr);
int QMediaResource_VideoBitRate(void* ptr);
char* QMediaResource_VideoCodec(void* ptr);
void QMediaResource_DestroyQMediaResource(void* ptr);
void QMediaService_ReleaseControl(void* ptr, void* control);
void* QMediaService_RequestControl(void* ptr, char* interfa);
void* QMediaService_RequestControl2(void* ptr);
void QMediaService_DestroyQMediaService(void* ptr);
int QMediaServiceCameraInfoInterface_CameraOrientation(void* ptr, void* device);
int QMediaServiceCameraInfoInterface_CameraPosition(void* ptr, void* device);
void QMediaServiceCameraInfoInterface_DestroyQMediaServiceCameraInfoInterface(void* ptr);
char* QMediaServiceCameraInfoInterface_ObjectNameAbs(void* ptr);
void QMediaServiceCameraInfoInterface_SetObjectNameAbs(void* ptr, char* name);
void* QMediaServiceDefaultDeviceInterface_DefaultDevice(void* ptr, void* service);
void QMediaServiceDefaultDeviceInterface_DestroyQMediaServiceDefaultDeviceInterface(void* ptr);
char* QMediaServiceDefaultDeviceInterface_ObjectNameAbs(void* ptr);
void QMediaServiceDefaultDeviceInterface_SetObjectNameAbs(void* ptr, char* name);
void QMediaServiceFeaturesInterface_DestroyQMediaServiceFeaturesInterface(void* ptr);
char* QMediaServiceFeaturesInterface_ObjectNameAbs(void* ptr);
void QMediaServiceFeaturesInterface_SetObjectNameAbs(void* ptr, char* name);
void* QMediaServiceProviderPlugin_Create(void* ptr, char* key);
void QMediaServiceProviderPlugin_Release(void* ptr, void* service);
char* QMediaServiceSupportedDevicesInterface_DeviceDescription(void* ptr, void* service, void* device);
void QMediaServiceSupportedDevicesInterface_DestroyQMediaServiceSupportedDevicesInterface(void* ptr);
char* QMediaServiceSupportedDevicesInterface_ObjectNameAbs(void* ptr);
void QMediaServiceSupportedDevicesInterface_SetObjectNameAbs(void* ptr, char* name);
char* QMediaServiceSupportedFormatsInterface_SupportedMimeTypes(void* ptr);
void QMediaServiceSupportedFormatsInterface_DestroyQMediaServiceSupportedFormatsInterface(void* ptr);
char* QMediaServiceSupportedFormatsInterface_ObjectNameAbs(void* ptr);
void QMediaServiceSupportedFormatsInterface_SetObjectNameAbs(void* ptr, char* name);
void QMediaStreamsControl_ConnectActiveStreamsChanged(void* ptr);
void QMediaStreamsControl_DisconnectActiveStreamsChanged(void* ptr);
int QMediaStreamsControl_IsActive(void* ptr, int stream);
void* QMediaStreamsControl_MetaData(void* ptr, int stream, char* key);
void QMediaStreamsControl_SetActive(void* ptr, int stream, int state);
int QMediaStreamsControl_StreamCount(void* ptr);
int QMediaStreamsControl_StreamType(void* ptr, int stream);
void QMediaStreamsControl_ConnectStreamsChanged(void* ptr);
void QMediaStreamsControl_DisconnectStreamsChanged(void* ptr);
void QMediaStreamsControl_DestroyQMediaStreamsControl(void* ptr);
void* QMediaTimeInterval_NewQMediaTimeInterval();
void* QMediaTimeInterval_NewQMediaTimeInterval3(void* other);
void* QMediaTimeInterval_NewQMediaTimeInterval2(long long start, long long end);
int QMediaTimeInterval_Contains(void* ptr, long long time);
long long QMediaTimeInterval_End(void* ptr);
int QMediaTimeInterval_IsNormal(void* ptr);
long long QMediaTimeInterval_Start(void* ptr);
void* QMediaTimeRange_NewQMediaTimeRange();
void* QMediaTimeRange_NewQMediaTimeRange3(void* interval);
void* QMediaTimeRange_NewQMediaTimeRange4(void* ran);
void* QMediaTimeRange_NewQMediaTimeRange2(long long start, long long end);
void QMediaTimeRange_AddInterval(void* ptr, void* interval);
void QMediaTimeRange_AddInterval2(void* ptr, long long start, long long end);
void QMediaTimeRange_AddTimeRange(void* ptr, void* ran);
void QMediaTimeRange_Clear(void* ptr);
int QMediaTimeRange_Contains(void* ptr, long long time);
long long QMediaTimeRange_EarliestTime(void* ptr);
int QMediaTimeRange_IsContinuous(void* ptr);
int QMediaTimeRange_IsEmpty(void* ptr);
long long QMediaTimeRange_LatestTime(void* ptr);
void QMediaTimeRange_RemoveInterval(void* ptr, void* interval);
void QMediaTimeRange_RemoveInterval2(void* ptr, long long start, long long end);
void QMediaTimeRange_RemoveTimeRange(void* ptr, void* ran);
void QMediaTimeRange_DestroyQMediaTimeRange(void* ptr);
void QMediaVideoProbeControl_ConnectFlush(void* ptr);
void QMediaVideoProbeControl_DisconnectFlush(void* ptr);
void QMediaVideoProbeControl_DestroyQMediaVideoProbeControl(void* ptr);
char* QMetaDataReaderControl_AvailableMetaData(void* ptr);
int QMetaDataReaderControl_IsMetaDataAvailable(void* ptr);
void* QMetaDataReaderControl_MetaData(void* ptr, char* key);
void QMetaDataReaderControl_ConnectMetaDataAvailableChanged(void* ptr);
void QMetaDataReaderControl_DisconnectMetaDataAvailableChanged(void* ptr);
void QMetaDataReaderControl_ConnectMetaDataChanged(void* ptr);
void QMetaDataReaderControl_DisconnectMetaDataChanged(void* ptr);
void QMetaDataReaderControl_ConnectMetaDataChanged2(void* ptr);
void QMetaDataReaderControl_DisconnectMetaDataChanged2(void* ptr);
void QMetaDataReaderControl_DestroyQMetaDataReaderControl(void* ptr);
char* QMetaDataWriterControl_AvailableMetaData(void* ptr);
int QMetaDataWriterControl_IsMetaDataAvailable(void* ptr);
int QMetaDataWriterControl_IsWritable(void* ptr);
void* QMetaDataWriterControl_MetaData(void* ptr, char* key);
void QMetaDataWriterControl_ConnectMetaDataAvailableChanged(void* ptr);
void QMetaDataWriterControl_DisconnectMetaDataAvailableChanged(void* ptr);
void QMetaDataWriterControl_ConnectMetaDataChanged(void* ptr);
void QMetaDataWriterControl_DisconnectMetaDataChanged(void* ptr);
void QMetaDataWriterControl_ConnectMetaDataChanged2(void* ptr);
void QMetaDataWriterControl_DisconnectMetaDataChanged2(void* ptr);
void QMetaDataWriterControl_SetMetaData(void* ptr, char* key, void* value);
void QMetaDataWriterControl_ConnectWritableChanged(void* ptr);
void QMetaDataWriterControl_DisconnectWritableChanged(void* ptr);
void QMetaDataWriterControl_DestroyQMetaDataWriterControl(void* ptr);
int QRadioData_IsAlternativeFrequenciesEnabled(void* ptr);
int QRadioData_ProgramType(void* ptr);
char* QRadioData_ProgramTypeName(void* ptr);
char* QRadioData_RadioText(void* ptr);
void QRadioData_SetAlternativeFrequenciesEnabled(void* ptr, int enabled);
char* QRadioData_StationId(void* ptr);
char* QRadioData_StationName(void* ptr);
void* QRadioData_NewQRadioData(void* mediaObject, void* parent);
void QRadioData_ConnectAlternativeFrequenciesEnabledChanged(void* ptr);
void QRadioData_DisconnectAlternativeFrequenciesEnabledChanged(void* ptr);
void QRadioData_ConnectError2(void* ptr);
void QRadioData_DisconnectError2(void* ptr);
int QRadioData_Error(void* ptr);
char* QRadioData_ErrorString(void* ptr);
void* QRadioData_MediaObject(void* ptr);
void QRadioData_ConnectProgramTypeChanged(void* ptr);
void QRadioData_DisconnectProgramTypeChanged(void* ptr);
void QRadioData_ConnectProgramTypeNameChanged(void* ptr);
void QRadioData_DisconnectProgramTypeNameChanged(void* ptr);
void QRadioData_ConnectRadioTextChanged(void* ptr);
void QRadioData_DisconnectRadioTextChanged(void* ptr);
void QRadioData_ConnectStationIdChanged(void* ptr);
void QRadioData_DisconnectStationIdChanged(void* ptr);
void QRadioData_ConnectStationNameChanged(void* ptr);
void QRadioData_DisconnectStationNameChanged(void* ptr);
void QRadioData_DestroyQRadioData(void* ptr);
void QRadioDataControl_ConnectAlternativeFrequenciesEnabledChanged(void* ptr);
void QRadioDataControl_DisconnectAlternativeFrequenciesEnabledChanged(void* ptr);
void QRadioDataControl_ConnectError2(void* ptr);
void QRadioDataControl_DisconnectError2(void* ptr);
int QRadioDataControl_Error(void* ptr);
char* QRadioDataControl_ErrorString(void* ptr);
int QRadioDataControl_IsAlternativeFrequenciesEnabled(void* ptr);
int QRadioDataControl_ProgramType(void* ptr);
void QRadioDataControl_ConnectProgramTypeChanged(void* ptr);
void QRadioDataControl_DisconnectProgramTypeChanged(void* ptr);
char* QRadioDataControl_ProgramTypeName(void* ptr);
void QRadioDataControl_ConnectProgramTypeNameChanged(void* ptr);
void QRadioDataControl_DisconnectProgramTypeNameChanged(void* ptr);
char* QRadioDataControl_RadioText(void* ptr);
void QRadioDataControl_ConnectRadioTextChanged(void* ptr);
void QRadioDataControl_DisconnectRadioTextChanged(void* ptr);
void QRadioDataControl_SetAlternativeFrequenciesEnabled(void* ptr, int enabled);
char* QRadioDataControl_StationId(void* ptr);
void QRadioDataControl_ConnectStationIdChanged(void* ptr);
void QRadioDataControl_DisconnectStationIdChanged(void* ptr);
char* QRadioDataControl_StationName(void* ptr);
void QRadioDataControl_ConnectStationNameChanged(void* ptr);
void QRadioDataControl_DisconnectStationNameChanged(void* ptr);
void QRadioDataControl_DestroyQRadioDataControl(void* ptr);
int QRadioTuner_Band(void* ptr);
int QRadioTuner_Frequency(void* ptr);
int QRadioTuner_IsAntennaConnected(void* ptr);
int QRadioTuner_IsMuted(void* ptr);
int QRadioTuner_IsSearching(void* ptr);
int QRadioTuner_IsStereo(void* ptr);
void* QRadioTuner_RadioData(void* ptr);
void QRadioTuner_SetMuted(void* ptr, int muted);
void QRadioTuner_SetStereoMode(void* ptr, int mode);
void QRadioTuner_SetVolume(void* ptr, int volume);
int QRadioTuner_SignalStrength(void* ptr);
int QRadioTuner_State(void* ptr);
int QRadioTuner_StereoMode(void* ptr);
int QRadioTuner_Volume(void* ptr);
void* QRadioTuner_NewQRadioTuner(void* parent);
void QRadioTuner_ConnectAntennaConnectedChanged(void* ptr);
void QRadioTuner_DisconnectAntennaConnectedChanged(void* ptr);
void QRadioTuner_ConnectBandChanged(void* ptr);
void QRadioTuner_DisconnectBandChanged(void* ptr);
void QRadioTuner_CancelSearch(void* ptr);
void QRadioTuner_ConnectError2(void* ptr);
void QRadioTuner_DisconnectError2(void* ptr);
int QRadioTuner_Error(void* ptr);
char* QRadioTuner_ErrorString(void* ptr);
void QRadioTuner_ConnectFrequencyChanged(void* ptr);
void QRadioTuner_DisconnectFrequencyChanged(void* ptr);
int QRadioTuner_FrequencyStep(void* ptr, int band);
int QRadioTuner_IsBandSupported(void* ptr, int band);
void QRadioTuner_ConnectMutedChanged(void* ptr);
void QRadioTuner_DisconnectMutedChanged(void* ptr);
void QRadioTuner_SearchAllStations(void* ptr, int searchMode);
void QRadioTuner_SearchBackward(void* ptr);
void QRadioTuner_SearchForward(void* ptr);
void QRadioTuner_ConnectSearchingChanged(void* ptr);
void QRadioTuner_DisconnectSearchingChanged(void* ptr);
void QRadioTuner_SetBand(void* ptr, int band);
void QRadioTuner_SetFrequency(void* ptr, int frequency);
void QRadioTuner_ConnectSignalStrengthChanged(void* ptr);
void QRadioTuner_DisconnectSignalStrengthChanged(void* ptr);
void QRadioTuner_Start(void* ptr);
void QRadioTuner_ConnectStateChanged(void* ptr);
void QRadioTuner_DisconnectStateChanged(void* ptr);
void QRadioTuner_ConnectStationFound(void* ptr);
void QRadioTuner_DisconnectStationFound(void* ptr);
void QRadioTuner_ConnectStereoStatusChanged(void* ptr);
void QRadioTuner_DisconnectStereoStatusChanged(void* ptr);
void QRadioTuner_Stop(void* ptr);
void QRadioTuner_ConnectVolumeChanged(void* ptr);
void QRadioTuner_DisconnectVolumeChanged(void* ptr);
void QRadioTuner_DestroyQRadioTuner(void* ptr);
void QRadioTunerControl_ConnectAntennaConnectedChanged(void* ptr);
void QRadioTunerControl_DisconnectAntennaConnectedChanged(void* ptr);
int QRadioTunerControl_Band(void* ptr);
void QRadioTunerControl_ConnectBandChanged(void* ptr);
void QRadioTunerControl_DisconnectBandChanged(void* ptr);
void QRadioTunerControl_CancelSearch(void* ptr);
void QRadioTunerControl_ConnectError2(void* ptr);
void QRadioTunerControl_DisconnectError2(void* ptr);
int QRadioTunerControl_Error(void* ptr);
char* QRadioTunerControl_ErrorString(void* ptr);
int QRadioTunerControl_Frequency(void* ptr);
void QRadioTunerControl_ConnectFrequencyChanged(void* ptr);
void QRadioTunerControl_DisconnectFrequencyChanged(void* ptr);
int QRadioTunerControl_FrequencyStep(void* ptr, int band);
int QRadioTunerControl_IsAntennaConnected(void* ptr);
int QRadioTunerControl_IsBandSupported(void* ptr, int band);
int QRadioTunerControl_IsMuted(void* ptr);
int QRadioTunerControl_IsSearching(void* ptr);
int QRadioTunerControl_IsStereo(void* ptr);
void QRadioTunerControl_ConnectMutedChanged(void* ptr);
void QRadioTunerControl_DisconnectMutedChanged(void* ptr);
void QRadioTunerControl_SearchAllStations(void* ptr, int searchMode);
void QRadioTunerControl_SearchBackward(void* ptr);
void QRadioTunerControl_SearchForward(void* ptr);
void QRadioTunerControl_ConnectSearchingChanged(void* ptr);
void QRadioTunerControl_DisconnectSearchingChanged(void* ptr);
void QRadioTunerControl_SetBand(void* ptr, int band);
void QRadioTunerControl_SetFrequency(void* ptr, int frequency);
void QRadioTunerControl_SetMuted(void* ptr, int muted);
void QRadioTunerControl_SetStereoMode(void* ptr, int mode);
void QRadioTunerControl_SetVolume(void* ptr, int volume);
int QRadioTunerControl_SignalStrength(void* ptr);
void QRadioTunerControl_ConnectSignalStrengthChanged(void* ptr);
void QRadioTunerControl_DisconnectSignalStrengthChanged(void* ptr);
void QRadioTunerControl_Start(void* ptr);
int QRadioTunerControl_State(void* ptr);
void QRadioTunerControl_ConnectStateChanged(void* ptr);
void QRadioTunerControl_DisconnectStateChanged(void* ptr);
void QRadioTunerControl_ConnectStationFound(void* ptr);
void QRadioTunerControl_DisconnectStationFound(void* ptr);
int QRadioTunerControl_StereoMode(void* ptr);
void QRadioTunerControl_ConnectStereoStatusChanged(void* ptr);
void QRadioTunerControl_DisconnectStereoStatusChanged(void* ptr);
void QRadioTunerControl_Stop(void* ptr);
int QRadioTunerControl_Volume(void* ptr);
void QRadioTunerControl_ConnectVolumeChanged(void* ptr);
void QRadioTunerControl_DisconnectVolumeChanged(void* ptr);
void QRadioTunerControl_DestroyQRadioTunerControl(void* ptr);
void QSound_SetLoops(void* ptr, int number);
void* QSound_NewQSound(char* filename, void* parent);
char* QSound_FileName(void* ptr);
int QSound_IsFinished(void* ptr);
int QSound_Loops(void* ptr);
int QSound_LoopsRemaining(void* ptr);
void QSound_Play2(void* ptr);
void QSound_QSound_Play(char* filename);
void QSound_Stop(void* ptr);
void QSound_DestroyQSound(void* ptr);
int QSoundEffect_IsLoaded(void* ptr);
int QSoundEffect_LoopsRemaining(void* ptr);
void QSoundEffect_Play(void* ptr);
void QSoundEffect_Stop(void* ptr);
char* QSoundEffect_QSoundEffect_SupportedMimeTypes();
void* QSoundEffect_NewQSoundEffect(void* parent);
char* QSoundEffect_Category(void* ptr);
void QSoundEffect_ConnectCategoryChanged(void* ptr);
void QSoundEffect_DisconnectCategoryChanged(void* ptr);
int QSoundEffect_IsMuted(void* ptr);
int QSoundEffect_IsPlaying(void* ptr);
void QSoundEffect_ConnectLoadedChanged(void* ptr);
void QSoundEffect_DisconnectLoadedChanged(void* ptr);
int QSoundEffect_LoopCount(void* ptr);
void QSoundEffect_ConnectLoopCountChanged(void* ptr);
void QSoundEffect_DisconnectLoopCountChanged(void* ptr);
void QSoundEffect_ConnectLoopsRemainingChanged(void* ptr);
void QSoundEffect_DisconnectLoopsRemainingChanged(void* ptr);
void QSoundEffect_ConnectMutedChanged(void* ptr);
void QSoundEffect_DisconnectMutedChanged(void* ptr);
void QSoundEffect_ConnectPlayingChanged(void* ptr);
void QSoundEffect_DisconnectPlayingChanged(void* ptr);
void QSoundEffect_SetCategory(void* ptr, char* category);
void QSoundEffect_SetLoopCount(void* ptr, int loopCount);
void QSoundEffect_SetMuted(void* ptr, int muted);
void QSoundEffect_SetSource(void* ptr, void* url);
void QSoundEffect_SetVolume(void* ptr, double volume);
void* QSoundEffect_Source(void* ptr);
void QSoundEffect_ConnectSourceChanged(void* ptr);
void QSoundEffect_DisconnectSourceChanged(void* ptr);
int QSoundEffect_Status(void* ptr);
void QSoundEffect_ConnectStatusChanged(void* ptr);
void QSoundEffect_DisconnectStatusChanged(void* ptr);
double QSoundEffect_Volume(void* ptr);
void QSoundEffect_ConnectVolumeChanged(void* ptr);
void QSoundEffect_DisconnectVolumeChanged(void* ptr);
void QSoundEffect_DestroyQSoundEffect(void* ptr);
int QVideoDeviceSelectorControl_DefaultDevice(void* ptr);
int QVideoDeviceSelectorControl_DeviceCount(void* ptr);
char* QVideoDeviceSelectorControl_DeviceDescription(void* ptr, int index);
char* QVideoDeviceSelectorControl_DeviceName(void* ptr, int index);
void QVideoDeviceSelectorControl_ConnectDevicesChanged(void* ptr);
void QVideoDeviceSelectorControl_DisconnectDevicesChanged(void* ptr);
int QVideoDeviceSelectorControl_SelectedDevice(void* ptr);
void QVideoDeviceSelectorControl_ConnectSelectedDeviceChanged2(void* ptr);
void QVideoDeviceSelectorControl_DisconnectSelectedDeviceChanged2(void* ptr);
void QVideoDeviceSelectorControl_ConnectSelectedDeviceChanged(void* ptr);
void QVideoDeviceSelectorControl_DisconnectSelectedDeviceChanged(void* ptr);
void QVideoDeviceSelectorControl_SetSelectedDevice(void* ptr, int index);
void QVideoDeviceSelectorControl_DestroyQVideoDeviceSelectorControl(void* ptr);
void QVideoEncoderSettings_SetFrameRate(void* ptr, double rate);
void* QVideoEncoderSettings_NewQVideoEncoderSettings();
void* QVideoEncoderSettings_NewQVideoEncoderSettings2(void* other);
int QVideoEncoderSettings_BitRate(void* ptr);
char* QVideoEncoderSettings_Codec(void* ptr);
void* QVideoEncoderSettings_EncodingOption(void* ptr, char* option);
double QVideoEncoderSettings_FrameRate(void* ptr);
int QVideoEncoderSettings_IsNull(void* ptr);
void* QVideoEncoderSettings_Resolution(void* ptr);
void QVideoEncoderSettings_SetBitRate(void* ptr, int value);
void QVideoEncoderSettings_SetCodec(void* ptr, char* codec);
void QVideoEncoderSettings_SetEncodingOption(void* ptr, char* option, void* value);
void QVideoEncoderSettings_SetResolution(void* ptr, void* resolution);
void QVideoEncoderSettings_SetResolution2(void* ptr, int width, int height);
void QVideoEncoderSettings_DestroyQVideoEncoderSettings(void* ptr);
void QVideoEncoderSettingsControl_SetVideoSettings(void* ptr, void* settings);
char* QVideoEncoderSettingsControl_SupportedVideoCodecs(void* ptr);
char* QVideoEncoderSettingsControl_VideoCodecDescription(void* ptr, char* codec);
void QVideoEncoderSettingsControl_DestroyQVideoEncoderSettingsControl(void* ptr);
void* QVideoFrame_NewQVideoFrame();
void* QVideoFrame_NewQVideoFrame2(void* buffer, void* size, int format);
void* QVideoFrame_NewQVideoFrame4(void* image);
void* QVideoFrame_NewQVideoFrame5(void* other);
void* QVideoFrame_NewQVideoFrame3(int bytes, void* size, int bytesPerLine, int format);
int QVideoFrame_BytesPerLine(void* ptr);
int QVideoFrame_BytesPerLine2(void* ptr, int plane);
long long QVideoFrame_EndTime(void* ptr);
int QVideoFrame_FieldType(void* ptr);
void* QVideoFrame_Handle(void* ptr);
int QVideoFrame_HandleType(void* ptr);
int QVideoFrame_Height(void* ptr);
int QVideoFrame_QVideoFrame_ImageFormatFromPixelFormat(int format);
int QVideoFrame_IsMapped(void* ptr);
int QVideoFrame_IsReadable(void* ptr);
int QVideoFrame_IsValid(void* ptr);
int QVideoFrame_IsWritable(void* ptr);
int QVideoFrame_Map(void* ptr, int mode);
int QVideoFrame_MapMode(void* ptr);
int QVideoFrame_MappedBytes(void* ptr);
void* QVideoFrame_MetaData(void* ptr, char* key);
int QVideoFrame_PixelFormat(void* ptr);
int QVideoFrame_QVideoFrame_PixelFormatFromImageFormat(int format);
int QVideoFrame_PlaneCount(void* ptr);
void QVideoFrame_SetEndTime(void* ptr, long long time);
void QVideoFrame_SetFieldType(void* ptr, int field);
void QVideoFrame_SetMetaData(void* ptr, char* key, void* value);
void QVideoFrame_SetStartTime(void* ptr, long long time);
void* QVideoFrame_Size(void* ptr);
long long QVideoFrame_StartTime(void* ptr);
void QVideoFrame_Unmap(void* ptr);
int QVideoFrame_Width(void* ptr);
void QVideoFrame_DestroyQVideoFrame(void* ptr);
void* QVideoProbe_NewQVideoProbe(void* parent);
void QVideoProbe_ConnectFlush(void* ptr);
void QVideoProbe_DisconnectFlush(void* ptr);
int QVideoProbe_IsActive(void* ptr);
int QVideoProbe_SetSource(void* ptr, void* source);
int QVideoProbe_SetSource2(void* ptr, void* mediaRecorder);
void QVideoProbe_DestroyQVideoProbe(void* ptr);
void QVideoRendererControl_SetSurface(void* ptr, void* surface);
void* QVideoRendererControl_Surface(void* ptr);
void QVideoRendererControl_DestroyQVideoRendererControl(void* ptr);
void* QVideoSurfaceFormat_NewQVideoSurfaceFormat();
void* QVideoSurfaceFormat_NewQVideoSurfaceFormat2(void* size, int format, int ty);
void* QVideoSurfaceFormat_NewQVideoSurfaceFormat3(void* other);
int QVideoSurfaceFormat_FrameHeight(void* ptr);
double QVideoSurfaceFormat_FrameRate(void* ptr);
void* QVideoSurfaceFormat_FrameSize(void* ptr);
int QVideoSurfaceFormat_FrameWidth(void* ptr);
int QVideoSurfaceFormat_HandleType(void* ptr);
int QVideoSurfaceFormat_IsValid(void* ptr);
void* QVideoSurfaceFormat_PixelAspectRatio(void* ptr);
int QVideoSurfaceFormat_PixelFormat(void* ptr);
void* QVideoSurfaceFormat_Property(void* ptr, char* name);
int QVideoSurfaceFormat_ScanLineDirection(void* ptr);
void QVideoSurfaceFormat_SetFrameRate(void* ptr, double rate);
void QVideoSurfaceFormat_SetFrameSize(void* ptr, void* size);
void QVideoSurfaceFormat_SetFrameSize2(void* ptr, int width, int height);
void QVideoSurfaceFormat_SetPixelAspectRatio(void* ptr, void* ratio);
void QVideoSurfaceFormat_SetPixelAspectRatio2(void* ptr, int horizontal, int vertical);
void QVideoSurfaceFormat_SetProperty(void* ptr, char* name, void* value);
void QVideoSurfaceFormat_SetScanLineDirection(void* ptr, int direction);
void QVideoSurfaceFormat_SetViewport(void* ptr, void* viewport);
void QVideoSurfaceFormat_SetYCbCrColorSpace(void* ptr, int space);
void* QVideoSurfaceFormat_SizeHint(void* ptr);
void* QVideoSurfaceFormat_Viewport(void* ptr);
int QVideoSurfaceFormat_YCbCrColorSpace(void* ptr);
void QVideoSurfaceFormat_DestroyQVideoSurfaceFormat(void* ptr);
int QVideoWindowControl_AspectRatioMode(void* ptr);
int QVideoWindowControl_Brightness(void* ptr);
void QVideoWindowControl_ConnectBrightnessChanged(void* ptr);
void QVideoWindowControl_DisconnectBrightnessChanged(void* ptr);
int QVideoWindowControl_Contrast(void* ptr);
void QVideoWindowControl_ConnectContrastChanged(void* ptr);
void QVideoWindowControl_DisconnectContrastChanged(void* ptr);
void* QVideoWindowControl_DisplayRect(void* ptr);
void QVideoWindowControl_ConnectFullScreenChanged(void* ptr);
void QVideoWindowControl_DisconnectFullScreenChanged(void* ptr);
int QVideoWindowControl_Hue(void* ptr);
void QVideoWindowControl_ConnectHueChanged(void* ptr);
void QVideoWindowControl_DisconnectHueChanged(void* ptr);
int QVideoWindowControl_IsFullScreen(void* ptr);
void* QVideoWindowControl_NativeSize(void* ptr);
void QVideoWindowControl_ConnectNativeSizeChanged(void* ptr);
void QVideoWindowControl_DisconnectNativeSizeChanged(void* ptr);
void QVideoWindowControl_Repaint(void* ptr);
int QVideoWindowControl_Saturation(void* ptr);
void QVideoWindowControl_ConnectSaturationChanged(void* ptr);
void QVideoWindowControl_DisconnectSaturationChanged(void* ptr);
void QVideoWindowControl_SetAspectRatioMode(void* ptr, int mode);
void QVideoWindowControl_SetBrightness(void* ptr, int brightness);
void QVideoWindowControl_SetContrast(void* ptr, int contrast);
void QVideoWindowControl_SetDisplayRect(void* ptr, void* rect);
void QVideoWindowControl_SetFullScreen(void* ptr, int fullScreen);
void QVideoWindowControl_SetHue(void* ptr, int hue);
void QVideoWindowControl_SetSaturation(void* ptr, int saturation);
void QVideoWindowControl_DestroyQVideoWindowControl(void* ptr);

#ifdef __cplusplus
}
#endif