// +build !minimal

#pragma once

#ifndef GO_QTDESIGNER_H
#define GO_QTDESIGNER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct QtDesigner_PackedString { char* data; long long len; };
struct QtDesigner_PackedList { void* data; long long len; };
void* QAbstractExtensionFactory_Extension(void* ptr, void* object, char* iid);
void QAbstractExtensionFactory_DestroyQAbstractExtensionFactory(void* ptr);
void QAbstractExtensionFactory_DestroyQAbstractExtensionFactoryDefault(void* ptr);
void* QAbstractExtensionManager_Extension(void* ptr, void* object, char* iid);
void QAbstractExtensionManager_RegisterExtensions(void* ptr, void* factory, char* iid);
void QAbstractExtensionManager_UnregisterExtensions(void* ptr, void* factory, char* iid);
void QAbstractExtensionManager_DestroyQAbstractExtensionManager(void* ptr);
void QAbstractExtensionManager_DestroyQAbstractExtensionManagerDefault(void* ptr);
void* QAbstractFormBuilder_Load(void* ptr, void* device, void* parent);
void* QAbstractFormBuilder_LoadDefault(void* ptr, void* device, void* parent);
void QAbstractFormBuilder_Save(void* ptr, void* device, void* widget);
void QAbstractFormBuilder_SaveDefault(void* ptr, void* device, void* widget);
void* QAbstractFormBuilder_NewQAbstractFormBuilder();
struct QtDesigner_PackedString QAbstractFormBuilder_ErrorString(void* ptr);
void QAbstractFormBuilder_SetWorkingDirectory(void* ptr, void* directory);
void* QAbstractFormBuilder_WorkingDirectory(void* ptr);
void QAbstractFormBuilder_DestroyQAbstractFormBuilder(void* ptr);
void QAbstractFormBuilder_DestroyQAbstractFormBuilderDefault(void* ptr);
void* QDesignerActionEditorInterface_NewQDesignerActionEditorInterface(void* parent, long long flags);
void* QDesignerActionEditorInterface_Core(void* ptr);
void* QDesignerActionEditorInterface_CoreDefault(void* ptr);
void QDesignerActionEditorInterface_ManageAction(void* ptr, void* action);
void QDesignerActionEditorInterface_SetFormWindow(void* ptr, void* formWindow);
void QDesignerActionEditorInterface_UnmanageAction(void* ptr, void* action);
void QDesignerActionEditorInterface_DestroyQDesignerActionEditorInterface(void* ptr);
void QDesignerActionEditorInterface_DestroyQDesignerActionEditorInterfaceDefault(void* ptr);
void QDesignerActionEditorInterface_ActionEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragEnterEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragLeaveEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragMoveEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DropEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_EnterEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_EnterEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_FocusInEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_FocusInEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_FocusOutEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_FocusOutEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_HideEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_LeaveEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_LeaveEventDefault(void* ptr, void* event);
void* QDesignerActionEditorInterface_MinimumSizeHint(void* ptr);
void* QDesignerActionEditorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerActionEditorInterface_MoveEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_MoveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_PaintEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_SetEnabled(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetStyleSheet(void* ptr, char* styleSheet);
void QDesignerActionEditorInterface_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QDesignerActionEditorInterface_SetVisible(void* ptr, char visible);
void QDesignerActionEditorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerActionEditorInterface_SetWindowModified(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetWindowTitle(void* ptr, char* vqs);
void QDesignerActionEditorInterface_SetWindowTitleDefault(void* ptr, char* vqs);
void QDesignerActionEditorInterface_ShowEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ShowEventDefault(void* ptr, void* event);
void* QDesignerActionEditorInterface_SizeHint(void* ptr);
void* QDesignerActionEditorInterface_SizeHintDefault(void* ptr);
void QDesignerActionEditorInterface_ChangeEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_Close(void* ptr);
char QDesignerActionEditorInterface_CloseDefault(void* ptr);
void QDesignerActionEditorInterface_CloseEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ContextMenuEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ContextMenuEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_FocusNextPrevChild(void* ptr, char next);
char QDesignerActionEditorInterface_FocusNextPrevChildDefault(void* ptr, char next);
char QDesignerActionEditorInterface_HasHeightForWidth(void* ptr);
char QDesignerActionEditorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerActionEditorInterface_HeightForWidth(void* ptr, int w);
int QDesignerActionEditorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerActionEditorInterface_Hide(void* ptr);
void QDesignerActionEditorInterface_HideDefault(void* ptr);
void QDesignerActionEditorInterface_InputMethodEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerActionEditorInterface_InputMethodQuery(void* ptr, long long query);
void* QDesignerActionEditorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerActionEditorInterface_KeyPressEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_KeyReleaseEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_Lower(void* ptr);
void QDesignerActionEditorInterface_LowerDefault(void* ptr);
void QDesignerActionEditorInterface_MouseDoubleClickEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseMoveEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MousePressEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseReleaseEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseReleaseEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QDesignerActionEditorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QDesignerActionEditorInterface_Raise(void* ptr);
void QDesignerActionEditorInterface_RaiseDefault(void* ptr);
void QDesignerActionEditorInterface_Repaint(void* ptr);
void QDesignerActionEditorInterface_RepaintDefault(void* ptr);
void QDesignerActionEditorInterface_ResizeEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_SetDisabled(void* ptr, char disable);
void QDesignerActionEditorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerActionEditorInterface_SetFocus2(void* ptr);
void QDesignerActionEditorInterface_SetFocus2Default(void* ptr);
void QDesignerActionEditorInterface_SetHidden(void* ptr, char hidden);
void QDesignerActionEditorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerActionEditorInterface_Show(void* ptr);
void QDesignerActionEditorInterface_ShowDefault(void* ptr);
void QDesignerActionEditorInterface_ShowFullScreen(void* ptr);
void QDesignerActionEditorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerActionEditorInterface_ShowMaximized(void* ptr);
void QDesignerActionEditorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerActionEditorInterface_ShowMinimized(void* ptr);
void QDesignerActionEditorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerActionEditorInterface_ShowNormal(void* ptr);
void QDesignerActionEditorInterface_ShowNormalDefault(void* ptr);
void QDesignerActionEditorInterface_TabletEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_Update(void* ptr);
void QDesignerActionEditorInterface_UpdateDefault(void* ptr);
void QDesignerActionEditorInterface_UpdateMicroFocus(void* ptr);
void QDesignerActionEditorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerActionEditorInterface_WheelEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_TimerEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ChildEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerActionEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerActionEditorInterface_CustomEvent(void* ptr, void* event);
void QDesignerActionEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DeleteLater(void* ptr);
void QDesignerActionEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerActionEditorInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerActionEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerActionEditorInterface_Event(void* ptr, void* e);
char QDesignerActionEditorInterface_EventDefault(void* ptr, void* e);
char QDesignerActionEditorInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerActionEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerActionEditorInterface_MetaObject(void* ptr);
void* QDesignerActionEditorInterface_MetaObjectDefault(void* ptr);
int QDesignerActionEditorInterface_Metric(void* ptr, long long metric);
int QDesignerActionEditorInterface_MetricDefault(void* ptr, long long metric);
void* QDesignerActionEditorInterface_PaintEngine(void* ptr);
void* QDesignerActionEditorInterface_PaintEngineDefault(void* ptr);
void QDesignerContainerExtension_AddWidget(void* ptr, void* page);
char QDesignerContainerExtension_CanAddWidget(void* ptr);
char QDesignerContainerExtension_CanAddWidgetDefault(void* ptr);
char QDesignerContainerExtension_CanRemove(void* ptr, int index);
char QDesignerContainerExtension_CanRemoveDefault(void* ptr, int index);
int QDesignerContainerExtension_Count(void* ptr);
int QDesignerContainerExtension_CurrentIndex(void* ptr);
void QDesignerContainerExtension_InsertWidget(void* ptr, int index, void* page);
void QDesignerContainerExtension_Remove(void* ptr, int index);
void QDesignerContainerExtension_SetCurrentIndex(void* ptr, int index);
void* QDesignerContainerExtension_Widget(void* ptr, int index);
void QDesignerContainerExtension_DestroyQDesignerContainerExtension(void* ptr);
void QDesignerContainerExtension_DestroyQDesignerContainerExtensionDefault(void* ptr);
void QDesignerCustomWidgetCollectionInterface_DestroyQDesignerCustomWidgetCollectionInterface(void* ptr);
void QDesignerCustomWidgetCollectionInterface_DestroyQDesignerCustomWidgetCollectionInterfaceDefault(void* ptr);
void* QDesignerCustomWidgetCollectionInterface_customWidgets_atList(void* ptr, int i);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_CodeTemplate(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_CodeTemplateDefault(void* ptr);
void* QDesignerCustomWidgetInterface_CreateWidget(void* ptr, void* parent);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_DomXml(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_DomXmlDefault(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_Group(void* ptr);
void* QDesignerCustomWidgetInterface_Icon(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_IncludeFile(void* ptr);
void QDesignerCustomWidgetInterface_Initialize(void* ptr, void* formEditor);
void QDesignerCustomWidgetInterface_InitializeDefault(void* ptr, void* formEditor);
char QDesignerCustomWidgetInterface_IsContainer(void* ptr);
char QDesignerCustomWidgetInterface_IsInitialized(void* ptr);
char QDesignerCustomWidgetInterface_IsInitializedDefault(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_Name(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_ToolTip(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_WhatsThis(void* ptr);
void QDesignerCustomWidgetInterface_DestroyQDesignerCustomWidgetInterface(void* ptr);
void QDesignerCustomWidgetInterface_DestroyQDesignerCustomWidgetInterfaceDefault(void* ptr);
int QDesignerDynamicPropertySheetExtension_AddDynamicProperty(void* ptr, char* propertyName, void* value);
char QDesignerDynamicPropertySheetExtension_CanAddDynamicProperty(void* ptr, char* propertyName);
char QDesignerDynamicPropertySheetExtension_DynamicPropertiesAllowed(void* ptr);
char QDesignerDynamicPropertySheetExtension_IsDynamicProperty(void* ptr, int index);
char QDesignerDynamicPropertySheetExtension_RemoveDynamicProperty(void* ptr, int index);
void QDesignerDynamicPropertySheetExtension_DestroyQDesignerDynamicPropertySheetExtension(void* ptr);
void QDesignerDynamicPropertySheetExtension_DestroyQDesignerDynamicPropertySheetExtensionDefault(void* ptr);
void* QDesignerFormEditorInterface_NewQDesignerFormEditorInterface(void* parent);
void* QDesignerFormEditorInterface_ActionEditor(void* ptr);
void* QDesignerFormEditorInterface_ExtensionManager(void* ptr);
void* QDesignerFormEditorInterface_FormWindowManager(void* ptr);
void* QDesignerFormEditorInterface_ObjectInspector(void* ptr);
void* QDesignerFormEditorInterface_PropertyEditor(void* ptr);
void QDesignerFormEditorInterface_SetActionEditor(void* ptr, void* actionEditor);
void QDesignerFormEditorInterface_SetObjectInspector(void* ptr, void* objectInspector);
void QDesignerFormEditorInterface_SetPropertyEditor(void* ptr, void* propertyEditor);
void QDesignerFormEditorInterface_SetWidgetBox(void* ptr, void* widgetBox);
void* QDesignerFormEditorInterface_TopLevel(void* ptr);
void* QDesignerFormEditorInterface_WidgetBox(void* ptr);
void QDesignerFormEditorInterface_DestroyQDesignerFormEditorInterface(void* ptr);
void QDesignerFormEditorInterface_DestroyQDesignerFormEditorInterfaceDefault(void* ptr);
void* QDesignerFormEditorInterface_pluginInstances_atList(void* ptr, int i);
void QDesignerFormEditorInterface_TimerEvent(void* ptr, void* event);
void QDesignerFormEditorInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerFormEditorInterface_ChildEvent(void* ptr, void* event);
void QDesignerFormEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormEditorInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerFormEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormEditorInterface_CustomEvent(void* ptr, void* event);
void QDesignerFormEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormEditorInterface_DeleteLater(void* ptr);
void QDesignerFormEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormEditorInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerFormEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormEditorInterface_Event(void* ptr, void* e);
char QDesignerFormEditorInterface_EventDefault(void* ptr, void* e);
char QDesignerFormEditorInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerFormEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormEditorInterface_MetaObject(void* ptr);
void* QDesignerFormEditorInterface_MetaObjectDefault(void* ptr);
void* QDesignerFormWindowCursorInterface_Current(void* ptr);
void* QDesignerFormWindowCursorInterface_FormWindow(void* ptr);
char QDesignerFormWindowCursorInterface_HasSelection(void* ptr);
char QDesignerFormWindowCursorInterface_IsWidgetSelected(void* ptr, void* widget);
char QDesignerFormWindowCursorInterface_MovePosition(void* ptr, long long operation, long long mode);
int QDesignerFormWindowCursorInterface_Position(void* ptr);
void QDesignerFormWindowCursorInterface_ResetWidgetProperty(void* ptr, void* widget, char* name);
void* QDesignerFormWindowCursorInterface_SelectedWidget(void* ptr, int index);
int QDesignerFormWindowCursorInterface_SelectedWidgetCount(void* ptr);
void QDesignerFormWindowCursorInterface_SetPosition(void* ptr, int position, long long mode);
void QDesignerFormWindowCursorInterface_SetProperty(void* ptr, char* name, void* value);
void QDesignerFormWindowCursorInterface_SetWidgetProperty(void* ptr, void* widget, char* name, void* value);
void* QDesignerFormWindowCursorInterface_Widget(void* ptr, int index);
int QDesignerFormWindowCursorInterface_WidgetCount(void* ptr);
void QDesignerFormWindowCursorInterface_DestroyQDesignerFormWindowCursorInterface(void* ptr);
void QDesignerFormWindowCursorInterface_DestroyQDesignerFormWindowCursorInterfaceDefault(void* ptr);
void* QDesignerFormWindowInterface_QDesignerFormWindowInterface_FindFormWindow2(void* object);
void* QDesignerFormWindowInterface_QDesignerFormWindowInterface_FindFormWindow(void* widget);
void QDesignerFormWindowInterface_ConnectAboutToUnmanageWidget(void* ptr);
void QDesignerFormWindowInterface_DisconnectAboutToUnmanageWidget(void* ptr);
void QDesignerFormWindowInterface_AboutToUnmanageWidget(void* ptr, void* widget);
void* QDesignerFormWindowInterface_AbsoluteDir(void* ptr);
void QDesignerFormWindowInterface_ActivateResourceFilePaths(void* ptr, char* paths, int errorCount, char* errorMessages);
void QDesignerFormWindowInterface_ConnectActivated(void* ptr);
void QDesignerFormWindowInterface_DisconnectActivated(void* ptr);
void QDesignerFormWindowInterface_Activated(void* ptr, void* widget);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ActiveResourceFilePaths(void* ptr);
void QDesignerFormWindowInterface_AddResourceFile(void* ptr, char* path);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Author(void* ptr);
void QDesignerFormWindowInterface_ConnectChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectChanged(void* ptr);
void QDesignerFormWindowInterface_Changed(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_CheckContents(void* ptr);
void QDesignerFormWindowInterface_ClearSelection(void* ptr, char update);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Comment(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Contents(void* ptr);
void* QDesignerFormWindowInterface_Core(void* ptr);
void* QDesignerFormWindowInterface_CoreDefault(void* ptr);
void* QDesignerFormWindowInterface_Cursor(void* ptr);
void QDesignerFormWindowInterface_EmitSelectionChanged(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ExportMacro(void* ptr);
void QDesignerFormWindowInterface_ConnectFeatureChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectFeatureChanged(void* ptr);
void QDesignerFormWindowInterface_FeatureChanged(void* ptr, long long feature);
long long QDesignerFormWindowInterface_Features(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_FileName(void* ptr);
void QDesignerFormWindowInterface_ConnectFileNameChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectFileNameChanged(void* ptr);
void QDesignerFormWindowInterface_FileNameChanged(void* ptr, char* fileName);
void* QDesignerFormWindowInterface_FormContainer(void* ptr);
void QDesignerFormWindowInterface_ConnectGeometryChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectGeometryChanged(void* ptr);
void QDesignerFormWindowInterface_GeometryChanged(void* ptr);
void* QDesignerFormWindowInterface_Grid(void* ptr);
char QDesignerFormWindowInterface_HasFeature(void* ptr, long long feature);
struct QtDesigner_PackedString QDesignerFormWindowInterface_IncludeHints(void* ptr);
char QDesignerFormWindowInterface_IsDirty(void* ptr);
char QDesignerFormWindowInterface_IsManaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_LayoutDefault(void* ptr, int margin, int spacing);
void QDesignerFormWindowInterface_LayoutFunction(void* ptr, char* margin, char* spacing);
void QDesignerFormWindowInterface_ConnectMainContainerChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectMainContainerChanged(void* ptr);
void QDesignerFormWindowInterface_MainContainerChanged(void* ptr, void* mainContainer);
void QDesignerFormWindowInterface_ManageWidget(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectObjectRemoved(void* ptr);
void QDesignerFormWindowInterface_DisconnectObjectRemoved(void* ptr);
void QDesignerFormWindowInterface_ObjectRemoved(void* ptr, void* object);
struct QtDesigner_PackedString QDesignerFormWindowInterface_PixmapFunction(void* ptr);
void QDesignerFormWindowInterface_RemoveResourceFile(void* ptr, char* path);
long long QDesignerFormWindowInterface_ResourceFileSaveMode(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ResourceFiles(void* ptr);
void QDesignerFormWindowInterface_ConnectResourceFilesChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectResourceFilesChanged(void* ptr);
void QDesignerFormWindowInterface_ResourceFilesChanged(void* ptr);
void QDesignerFormWindowInterface_SelectWidget(void* ptr, void* widget, char sele);
void QDesignerFormWindowInterface_ConnectSelectionChanged(void* ptr);
void QDesignerFormWindowInterface_DisconnectSelectionChanged(void* ptr);
void QDesignerFormWindowInterface_SelectionChanged(void* ptr);
void QDesignerFormWindowInterface_SetAuthor(void* ptr, char* author);
void QDesignerFormWindowInterface_SetComment(void* ptr, char* comment);
char QDesignerFormWindowInterface_SetContents(void* ptr, void* device, char* errorMessage);
char QDesignerFormWindowInterface_SetContents2(void* ptr, char* contents);
void QDesignerFormWindowInterface_SetDirty(void* ptr, char dirty);
void QDesignerFormWindowInterface_SetExportMacro(void* ptr, char* exportMacro);
void QDesignerFormWindowInterface_SetFeatures(void* ptr, long long features);
void QDesignerFormWindowInterface_SetFileName(void* ptr, char* fileName);
void QDesignerFormWindowInterface_SetGrid(void* ptr, void* grid);
void QDesignerFormWindowInterface_SetIncludeHints(void* ptr, char* includeHints);
void QDesignerFormWindowInterface_SetLayoutDefault(void* ptr, int margin, int spacing);
void QDesignerFormWindowInterface_SetLayoutFunction(void* ptr, char* margin, char* spacing);
void QDesignerFormWindowInterface_SetMainContainer(void* ptr, void* mainContainer);
void QDesignerFormWindowInterface_SetPixmapFunction(void* ptr, char* pixmapFunction);
void QDesignerFormWindowInterface_SetResourceFileSaveMode(void* ptr, long long behaviour);
void QDesignerFormWindowInterface_UnmanageWidget(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetManaged(void* ptr);
void QDesignerFormWindowInterface_DisconnectWidgetManaged(void* ptr);
void QDesignerFormWindowInterface_WidgetManaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetRemoved(void* ptr);
void QDesignerFormWindowInterface_DisconnectWidgetRemoved(void* ptr);
void QDesignerFormWindowInterface_WidgetRemoved(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetUnmanaged(void* ptr);
void QDesignerFormWindowInterface_DisconnectWidgetUnmanaged(void* ptr);
void QDesignerFormWindowInterface_WidgetUnmanaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_DestroyQDesignerFormWindowInterface(void* ptr);
void QDesignerFormWindowInterface_DestroyQDesignerFormWindowInterfaceDefault(void* ptr);
void QDesignerFormWindowInterface_ActionEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragEnterEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragLeaveEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragMoveEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DropEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_DropEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_EnterEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_EnterEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_FocusInEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_FocusInEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_FocusOutEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_FocusOutEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_HideEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_HideEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_LeaveEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_LeaveEventDefault(void* ptr, void* event);
void* QDesignerFormWindowInterface_MinimumSizeHint(void* ptr);
void* QDesignerFormWindowInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerFormWindowInterface_MoveEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_MoveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_PaintEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_SetEnabled(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetStyleSheet(void* ptr, char* styleSheet);
void QDesignerFormWindowInterface_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QDesignerFormWindowInterface_SetVisible(void* ptr, char visible);
void QDesignerFormWindowInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerFormWindowInterface_SetWindowModified(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetWindowTitle(void* ptr, char* vqs);
void QDesignerFormWindowInterface_SetWindowTitleDefault(void* ptr, char* vqs);
void QDesignerFormWindowInterface_ShowEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ShowEventDefault(void* ptr, void* event);
void* QDesignerFormWindowInterface_SizeHint(void* ptr);
void* QDesignerFormWindowInterface_SizeHintDefault(void* ptr);
void QDesignerFormWindowInterface_ChangeEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_Close(void* ptr);
char QDesignerFormWindowInterface_CloseDefault(void* ptr);
void QDesignerFormWindowInterface_CloseEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ContextMenuEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ContextMenuEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_FocusNextPrevChild(void* ptr, char next);
char QDesignerFormWindowInterface_FocusNextPrevChildDefault(void* ptr, char next);
char QDesignerFormWindowInterface_HasHeightForWidth(void* ptr);
char QDesignerFormWindowInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerFormWindowInterface_HeightForWidth(void* ptr, int w);
int QDesignerFormWindowInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerFormWindowInterface_Hide(void* ptr);
void QDesignerFormWindowInterface_HideDefault(void* ptr);
void QDesignerFormWindowInterface_InputMethodEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerFormWindowInterface_InputMethodQuery(void* ptr, long long query);
void* QDesignerFormWindowInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerFormWindowInterface_KeyPressEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_KeyReleaseEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_Lower(void* ptr);
void QDesignerFormWindowInterface_LowerDefault(void* ptr);
void QDesignerFormWindowInterface_MouseDoubleClickEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseMoveEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MousePressEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseReleaseEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseReleaseEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QDesignerFormWindowInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QDesignerFormWindowInterface_Raise(void* ptr);
void QDesignerFormWindowInterface_RaiseDefault(void* ptr);
void QDesignerFormWindowInterface_Repaint(void* ptr);
void QDesignerFormWindowInterface_RepaintDefault(void* ptr);
void QDesignerFormWindowInterface_ResizeEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_SetDisabled(void* ptr, char disable);
void QDesignerFormWindowInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerFormWindowInterface_SetFocus2(void* ptr);
void QDesignerFormWindowInterface_SetFocus2Default(void* ptr);
void QDesignerFormWindowInterface_SetHidden(void* ptr, char hidden);
void QDesignerFormWindowInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerFormWindowInterface_Show(void* ptr);
void QDesignerFormWindowInterface_ShowDefault(void* ptr);
void QDesignerFormWindowInterface_ShowFullScreen(void* ptr);
void QDesignerFormWindowInterface_ShowFullScreenDefault(void* ptr);
void QDesignerFormWindowInterface_ShowMaximized(void* ptr);
void QDesignerFormWindowInterface_ShowMaximizedDefault(void* ptr);
void QDesignerFormWindowInterface_ShowMinimized(void* ptr);
void QDesignerFormWindowInterface_ShowMinimizedDefault(void* ptr);
void QDesignerFormWindowInterface_ShowNormal(void* ptr);
void QDesignerFormWindowInterface_ShowNormalDefault(void* ptr);
void QDesignerFormWindowInterface_TabletEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_Update(void* ptr);
void QDesignerFormWindowInterface_UpdateDefault(void* ptr);
void QDesignerFormWindowInterface_UpdateMicroFocus(void* ptr);
void QDesignerFormWindowInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerFormWindowInterface_WheelEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_TimerEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ChildEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerFormWindowInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormWindowInterface_CustomEvent(void* ptr, void* event);
void QDesignerFormWindowInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DeleteLater(void* ptr);
void QDesignerFormWindowInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormWindowInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerFormWindowInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormWindowInterface_Event(void* ptr, void* e);
char QDesignerFormWindowInterface_EventDefault(void* ptr, void* e);
char QDesignerFormWindowInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerFormWindowInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormWindowInterface_MetaObject(void* ptr);
void* QDesignerFormWindowInterface_MetaObjectDefault(void* ptr);
int QDesignerFormWindowInterface_Metric(void* ptr, long long metric);
int QDesignerFormWindowInterface_MetricDefault(void* ptr, long long metric);
void* QDesignerFormWindowInterface_PaintEngine(void* ptr);
void* QDesignerFormWindowInterface_PaintEngineDefault(void* ptr);
void* QDesignerFormWindowManagerInterface_Action(void* ptr, long long action);
void* QDesignerFormWindowManagerInterface_ActionGroup(void* ptr, long long actionGroup);
void* QDesignerFormWindowManagerInterface_ActiveFormWindow(void* ptr);
void QDesignerFormWindowManagerInterface_ConnectActiveFormWindowChanged(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectActiveFormWindowChanged(void* ptr);
void QDesignerFormWindowManagerInterface_ActiveFormWindowChanged(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_AddFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_CloseAllPreviews(void* ptr);
void* QDesignerFormWindowManagerInterface_Core(void* ptr);
void* QDesignerFormWindowManagerInterface_CreateFormWindow(void* ptr, void* parent, long long flags);
void* QDesignerFormWindowManagerInterface_CreatePreviewPixmap(void* ptr);
void* QDesignerFormWindowManagerInterface_FormWindow(void* ptr, int index);
void QDesignerFormWindowManagerInterface_ConnectFormWindowAdded(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowAdded(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowAdded(void* ptr, void* formWindow);
int QDesignerFormWindowManagerInterface_FormWindowCount(void* ptr);
void QDesignerFormWindowManagerInterface_ConnectFormWindowRemoved(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowRemoved(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowRemoved(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_ConnectFormWindowSettingsChanged(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowSettingsChanged(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowSettingsChanged(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_RemoveFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_SetActiveFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_ShowPluginDialog(void* ptr);
void QDesignerFormWindowManagerInterface_ShowPreview(void* ptr);
void QDesignerFormWindowManagerInterface_DestroyQDesignerFormWindowManagerInterface(void* ptr);
void QDesignerFormWindowManagerInterface_DestroyQDesignerFormWindowManagerInterfaceDefault(void* ptr);
void QDesignerFormWindowManagerInterface_TimerEvent(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_ChildEvent(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerFormWindowManagerInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormWindowManagerInterface_CustomEvent(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_DeleteLater(void* ptr);
void QDesignerFormWindowManagerInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerFormWindowManagerInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormWindowManagerInterface_Event(void* ptr, void* e);
char QDesignerFormWindowManagerInterface_EventDefault(void* ptr, void* e);
char QDesignerFormWindowManagerInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerFormWindowManagerInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormWindowManagerInterface_MetaObject(void* ptr);
void* QDesignerFormWindowManagerInterface_MetaObjectDefault(void* ptr);
int QDesignerMemberSheetExtension_Count(void* ptr);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_DeclaredInClass(void* ptr, int index);
int QDesignerMemberSheetExtension_IndexOf(void* ptr, char* name);
char QDesignerMemberSheetExtension_InheritedFromWidget(void* ptr, int index);
char QDesignerMemberSheetExtension_IsSignal(void* ptr, int index);
char QDesignerMemberSheetExtension_IsSlot(void* ptr, int index);
char QDesignerMemberSheetExtension_IsVisible(void* ptr, int index);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_MemberGroup(void* ptr, int index);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_MemberName(void* ptr, int index);
void QDesignerMemberSheetExtension_SetMemberGroup(void* ptr, int index, char* group);
void QDesignerMemberSheetExtension_SetVisible(void* ptr, int index, char visible);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_Signature(void* ptr, int index);
void QDesignerMemberSheetExtension_DestroyQDesignerMemberSheetExtension(void* ptr);
void QDesignerMemberSheetExtension_DestroyQDesignerMemberSheetExtensionDefault(void* ptr);
void* QDesignerMemberSheetExtension_parameterNames_atList(void* ptr, int i);
void* QDesignerMemberSheetExtension_parameterTypes_atList(void* ptr, int i);
void* QDesignerObjectInspectorInterface_NewQDesignerObjectInspectorInterface(void* parent, long long flags);
void* QDesignerObjectInspectorInterface_Core(void* ptr);
void* QDesignerObjectInspectorInterface_CoreDefault(void* ptr);
void QDesignerObjectInspectorInterface_SetFormWindow(void* ptr, void* formWindow);
void QDesignerObjectInspectorInterface_DestroyQDesignerObjectInspectorInterface(void* ptr);
void QDesignerObjectInspectorInterface_DestroyQDesignerObjectInspectorInterfaceDefault(void* ptr);
void QDesignerObjectInspectorInterface_ActionEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragEnterEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragLeaveEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragMoveEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DropEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_EnterEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_EnterEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_FocusInEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_FocusInEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_FocusOutEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_FocusOutEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_HideEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_LeaveEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_LeaveEventDefault(void* ptr, void* event);
void* QDesignerObjectInspectorInterface_MinimumSizeHint(void* ptr);
void* QDesignerObjectInspectorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerObjectInspectorInterface_MoveEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MoveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_PaintEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_SetEnabled(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetStyleSheet(void* ptr, char* styleSheet);
void QDesignerObjectInspectorInterface_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QDesignerObjectInspectorInterface_SetVisible(void* ptr, char visible);
void QDesignerObjectInspectorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerObjectInspectorInterface_SetWindowModified(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetWindowTitle(void* ptr, char* vqs);
void QDesignerObjectInspectorInterface_SetWindowTitleDefault(void* ptr, char* vqs);
void QDesignerObjectInspectorInterface_ShowEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ShowEventDefault(void* ptr, void* event);
void* QDesignerObjectInspectorInterface_SizeHint(void* ptr);
void* QDesignerObjectInspectorInterface_SizeHintDefault(void* ptr);
void QDesignerObjectInspectorInterface_ChangeEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_Close(void* ptr);
char QDesignerObjectInspectorInterface_CloseDefault(void* ptr);
void QDesignerObjectInspectorInterface_CloseEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ContextMenuEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ContextMenuEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_FocusNextPrevChild(void* ptr, char next);
char QDesignerObjectInspectorInterface_FocusNextPrevChildDefault(void* ptr, char next);
char QDesignerObjectInspectorInterface_HasHeightForWidth(void* ptr);
char QDesignerObjectInspectorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerObjectInspectorInterface_HeightForWidth(void* ptr, int w);
int QDesignerObjectInspectorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerObjectInspectorInterface_Hide(void* ptr);
void QDesignerObjectInspectorInterface_HideDefault(void* ptr);
void QDesignerObjectInspectorInterface_InputMethodEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerObjectInspectorInterface_InputMethodQuery(void* ptr, long long query);
void* QDesignerObjectInspectorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerObjectInspectorInterface_KeyPressEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_KeyReleaseEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_Lower(void* ptr);
void QDesignerObjectInspectorInterface_LowerDefault(void* ptr);
void QDesignerObjectInspectorInterface_MouseDoubleClickEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseMoveEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MousePressEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseReleaseEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseReleaseEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QDesignerObjectInspectorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QDesignerObjectInspectorInterface_Raise(void* ptr);
void QDesignerObjectInspectorInterface_RaiseDefault(void* ptr);
void QDesignerObjectInspectorInterface_Repaint(void* ptr);
void QDesignerObjectInspectorInterface_RepaintDefault(void* ptr);
void QDesignerObjectInspectorInterface_ResizeEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_SetDisabled(void* ptr, char disable);
void QDesignerObjectInspectorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerObjectInspectorInterface_SetFocus2(void* ptr);
void QDesignerObjectInspectorInterface_SetFocus2Default(void* ptr);
void QDesignerObjectInspectorInterface_SetHidden(void* ptr, char hidden);
void QDesignerObjectInspectorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerObjectInspectorInterface_Show(void* ptr);
void QDesignerObjectInspectorInterface_ShowDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowFullScreen(void* ptr);
void QDesignerObjectInspectorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowMaximized(void* ptr);
void QDesignerObjectInspectorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowMinimized(void* ptr);
void QDesignerObjectInspectorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowNormal(void* ptr);
void QDesignerObjectInspectorInterface_ShowNormalDefault(void* ptr);
void QDesignerObjectInspectorInterface_TabletEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_Update(void* ptr);
void QDesignerObjectInspectorInterface_UpdateDefault(void* ptr);
void QDesignerObjectInspectorInterface_UpdateMicroFocus(void* ptr);
void QDesignerObjectInspectorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerObjectInspectorInterface_WheelEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_TimerEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ChildEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerObjectInspectorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerObjectInspectorInterface_CustomEvent(void* ptr, void* event);
void QDesignerObjectInspectorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DeleteLater(void* ptr);
void QDesignerObjectInspectorInterface_DeleteLaterDefault(void* ptr);
void QDesignerObjectInspectorInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerObjectInspectorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerObjectInspectorInterface_Event(void* ptr, void* e);
char QDesignerObjectInspectorInterface_EventDefault(void* ptr, void* e);
char QDesignerObjectInspectorInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerObjectInspectorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerObjectInspectorInterface_MetaObject(void* ptr);
void* QDesignerObjectInspectorInterface_MetaObjectDefault(void* ptr);
int QDesignerObjectInspectorInterface_Metric(void* ptr, long long metric);
int QDesignerObjectInspectorInterface_MetricDefault(void* ptr, long long metric);
void* QDesignerObjectInspectorInterface_PaintEngine(void* ptr);
void* QDesignerObjectInspectorInterface_PaintEngineDefault(void* ptr);
void* QDesignerPropertyEditorInterface_NewQDesignerPropertyEditorInterface(void* parent, long long flags);
void* QDesignerPropertyEditorInterface_Core(void* ptr);
void* QDesignerPropertyEditorInterface_CoreDefault(void* ptr);
struct QtDesigner_PackedString QDesignerPropertyEditorInterface_CurrentPropertyName(void* ptr);
char QDesignerPropertyEditorInterface_IsReadOnly(void* ptr);
void* QDesignerPropertyEditorInterface_Object(void* ptr);
void QDesignerPropertyEditorInterface_ConnectPropertyChanged(void* ptr);
void QDesignerPropertyEditorInterface_DisconnectPropertyChanged(void* ptr);
void QDesignerPropertyEditorInterface_PropertyChanged(void* ptr, char* name, void* value);
void QDesignerPropertyEditorInterface_SetObject(void* ptr, void* object);
void QDesignerPropertyEditorInterface_SetPropertyValue(void* ptr, char* name, void* value, char changed);
void QDesignerPropertyEditorInterface_SetReadOnly(void* ptr, char readOnly);
void QDesignerPropertyEditorInterface_DestroyQDesignerPropertyEditorInterface(void* ptr);
void QDesignerPropertyEditorInterface_DestroyQDesignerPropertyEditorInterfaceDefault(void* ptr);
void QDesignerPropertyEditorInterface_ActionEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragEnterEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragLeaveEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragMoveEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DropEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_EnterEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_EnterEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_FocusInEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_FocusInEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_FocusOutEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_FocusOutEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_HideEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_LeaveEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_LeaveEventDefault(void* ptr, void* event);
void* QDesignerPropertyEditorInterface_MinimumSizeHint(void* ptr);
void* QDesignerPropertyEditorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerPropertyEditorInterface_MoveEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MoveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_PaintEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_SetEnabled(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetStyleSheet(void* ptr, char* styleSheet);
void QDesignerPropertyEditorInterface_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QDesignerPropertyEditorInterface_SetVisible(void* ptr, char visible);
void QDesignerPropertyEditorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerPropertyEditorInterface_SetWindowModified(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetWindowTitle(void* ptr, char* vqs);
void QDesignerPropertyEditorInterface_SetWindowTitleDefault(void* ptr, char* vqs);
void QDesignerPropertyEditorInterface_ShowEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ShowEventDefault(void* ptr, void* event);
void* QDesignerPropertyEditorInterface_SizeHint(void* ptr);
void* QDesignerPropertyEditorInterface_SizeHintDefault(void* ptr);
void QDesignerPropertyEditorInterface_ChangeEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_Close(void* ptr);
char QDesignerPropertyEditorInterface_CloseDefault(void* ptr);
void QDesignerPropertyEditorInterface_CloseEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ContextMenuEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ContextMenuEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_FocusNextPrevChild(void* ptr, char next);
char QDesignerPropertyEditorInterface_FocusNextPrevChildDefault(void* ptr, char next);
char QDesignerPropertyEditorInterface_HasHeightForWidth(void* ptr);
char QDesignerPropertyEditorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerPropertyEditorInterface_HeightForWidth(void* ptr, int w);
int QDesignerPropertyEditorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerPropertyEditorInterface_Hide(void* ptr);
void QDesignerPropertyEditorInterface_HideDefault(void* ptr);
void QDesignerPropertyEditorInterface_InputMethodEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerPropertyEditorInterface_InputMethodQuery(void* ptr, long long query);
void* QDesignerPropertyEditorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerPropertyEditorInterface_KeyPressEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_KeyReleaseEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_Lower(void* ptr);
void QDesignerPropertyEditorInterface_LowerDefault(void* ptr);
void QDesignerPropertyEditorInterface_MouseDoubleClickEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseMoveEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MousePressEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseReleaseEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseReleaseEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QDesignerPropertyEditorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QDesignerPropertyEditorInterface_Raise(void* ptr);
void QDesignerPropertyEditorInterface_RaiseDefault(void* ptr);
void QDesignerPropertyEditorInterface_Repaint(void* ptr);
void QDesignerPropertyEditorInterface_RepaintDefault(void* ptr);
void QDesignerPropertyEditorInterface_ResizeEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_SetDisabled(void* ptr, char disable);
void QDesignerPropertyEditorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerPropertyEditorInterface_SetFocus2(void* ptr);
void QDesignerPropertyEditorInterface_SetFocus2Default(void* ptr);
void QDesignerPropertyEditorInterface_SetHidden(void* ptr, char hidden);
void QDesignerPropertyEditorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerPropertyEditorInterface_Show(void* ptr);
void QDesignerPropertyEditorInterface_ShowDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowFullScreen(void* ptr);
void QDesignerPropertyEditorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowMaximized(void* ptr);
void QDesignerPropertyEditorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowMinimized(void* ptr);
void QDesignerPropertyEditorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowNormal(void* ptr);
void QDesignerPropertyEditorInterface_ShowNormalDefault(void* ptr);
void QDesignerPropertyEditorInterface_TabletEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_Update(void* ptr);
void QDesignerPropertyEditorInterface_UpdateDefault(void* ptr);
void QDesignerPropertyEditorInterface_UpdateMicroFocus(void* ptr);
void QDesignerPropertyEditorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerPropertyEditorInterface_WheelEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_TimerEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ChildEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerPropertyEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerPropertyEditorInterface_CustomEvent(void* ptr, void* event);
void QDesignerPropertyEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DeleteLater(void* ptr);
void QDesignerPropertyEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerPropertyEditorInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerPropertyEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerPropertyEditorInterface_Event(void* ptr, void* e);
char QDesignerPropertyEditorInterface_EventDefault(void* ptr, void* e);
char QDesignerPropertyEditorInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerPropertyEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerPropertyEditorInterface_MetaObject(void* ptr);
void* QDesignerPropertyEditorInterface_MetaObjectDefault(void* ptr);
int QDesignerPropertyEditorInterface_Metric(void* ptr, long long metric);
int QDesignerPropertyEditorInterface_MetricDefault(void* ptr, long long metric);
void* QDesignerPropertyEditorInterface_PaintEngine(void* ptr);
void* QDesignerPropertyEditorInterface_PaintEngineDefault(void* ptr);
int QDesignerPropertySheetExtension_Count(void* ptr);
char QDesignerPropertySheetExtension_HasReset(void* ptr, int index);
int QDesignerPropertySheetExtension_IndexOf(void* ptr, char* name);
char QDesignerPropertySheetExtension_IsAttribute(void* ptr, int index);
char QDesignerPropertySheetExtension_IsChanged(void* ptr, int index);
char QDesignerPropertySheetExtension_IsEnabled(void* ptr, int index);
char QDesignerPropertySheetExtension_IsEnabledDefault(void* ptr, int index);
char QDesignerPropertySheetExtension_IsVisible(void* ptr, int index);
void* QDesignerPropertySheetExtension_Property(void* ptr, int index);
struct QtDesigner_PackedString QDesignerPropertySheetExtension_PropertyGroup(void* ptr, int index);
struct QtDesigner_PackedString QDesignerPropertySheetExtension_PropertyName(void* ptr, int index);
char QDesignerPropertySheetExtension_Reset(void* ptr, int index);
void QDesignerPropertySheetExtension_SetAttribute(void* ptr, int index, char attribute);
void QDesignerPropertySheetExtension_SetChanged(void* ptr, int index, char changed);
void QDesignerPropertySheetExtension_SetProperty(void* ptr, int index, void* value);
void QDesignerPropertySheetExtension_SetPropertyGroup(void* ptr, int index, char* group);
void QDesignerPropertySheetExtension_SetVisible(void* ptr, int index, char visible);
void QDesignerPropertySheetExtension_DestroyQDesignerPropertySheetExtension(void* ptr);
void QDesignerPropertySheetExtension_DestroyQDesignerPropertySheetExtensionDefault(void* ptr);
void* QDesignerTaskMenuExtension_PreferredEditAction(void* ptr);
void* QDesignerTaskMenuExtension_PreferredEditActionDefault(void* ptr);
void QDesignerTaskMenuExtension_DestroyQDesignerTaskMenuExtension(void* ptr);
void QDesignerTaskMenuExtension_DestroyQDesignerTaskMenuExtensionDefault(void* ptr);
void* QDesignerTaskMenuExtension_taskActions_atList(void* ptr, int i);
struct QtDesigner_PackedString QDesignerWidgetBoxInterface_FileName(void* ptr);
char QDesignerWidgetBoxInterface_Load(void* ptr);
char QDesignerWidgetBoxInterface_Save(void* ptr);
void QDesignerWidgetBoxInterface_SetFileName(void* ptr, char* fileName);
void QDesignerWidgetBoxInterface_DestroyQDesignerWidgetBoxInterface(void* ptr);
void QDesignerWidgetBoxInterface_DestroyQDesignerWidgetBoxInterfaceDefault(void* ptr);
void QDesignerWidgetBoxInterface_ActionEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragEnterEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragLeaveEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragMoveEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DropEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DropEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_EnterEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_EnterEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_FocusInEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_FocusInEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_FocusOutEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_FocusOutEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_HideEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_HideEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_LeaveEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_LeaveEventDefault(void* ptr, void* event);
void* QDesignerWidgetBoxInterface_MinimumSizeHint(void* ptr);
void* QDesignerWidgetBoxInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerWidgetBoxInterface_MoveEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MoveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_PaintEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_SetEnabled(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetStyleSheet(void* ptr, char* styleSheet);
void QDesignerWidgetBoxInterface_SetStyleSheetDefault(void* ptr, char* styleSheet);
void QDesignerWidgetBoxInterface_SetVisible(void* ptr, char visible);
void QDesignerWidgetBoxInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerWidgetBoxInterface_SetWindowModified(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetWindowTitle(void* ptr, char* vqs);
void QDesignerWidgetBoxInterface_SetWindowTitleDefault(void* ptr, char* vqs);
void QDesignerWidgetBoxInterface_ShowEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ShowEventDefault(void* ptr, void* event);
void* QDesignerWidgetBoxInterface_SizeHint(void* ptr);
void* QDesignerWidgetBoxInterface_SizeHintDefault(void* ptr);
void QDesignerWidgetBoxInterface_ChangeEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_Close(void* ptr);
char QDesignerWidgetBoxInterface_CloseDefault(void* ptr);
void QDesignerWidgetBoxInterface_CloseEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ContextMenuEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ContextMenuEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_FocusNextPrevChild(void* ptr, char next);
char QDesignerWidgetBoxInterface_FocusNextPrevChildDefault(void* ptr, char next);
char QDesignerWidgetBoxInterface_HasHeightForWidth(void* ptr);
char QDesignerWidgetBoxInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerWidgetBoxInterface_HeightForWidth(void* ptr, int w);
int QDesignerWidgetBoxInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerWidgetBoxInterface_Hide(void* ptr);
void QDesignerWidgetBoxInterface_HideDefault(void* ptr);
void QDesignerWidgetBoxInterface_InputMethodEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerWidgetBoxInterface_InputMethodQuery(void* ptr, long long query);
void* QDesignerWidgetBoxInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerWidgetBoxInterface_KeyPressEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_KeyReleaseEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_Lower(void* ptr);
void QDesignerWidgetBoxInterface_LowerDefault(void* ptr);
void QDesignerWidgetBoxInterface_MouseDoubleClickEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseMoveEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MousePressEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseReleaseEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseReleaseEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_NativeEvent(void* ptr, void* eventType, void* message, long result);
char QDesignerWidgetBoxInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long result);
void QDesignerWidgetBoxInterface_Raise(void* ptr);
void QDesignerWidgetBoxInterface_RaiseDefault(void* ptr);
void QDesignerWidgetBoxInterface_Repaint(void* ptr);
void QDesignerWidgetBoxInterface_RepaintDefault(void* ptr);
void QDesignerWidgetBoxInterface_ResizeEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_SetDisabled(void* ptr, char disable);
void QDesignerWidgetBoxInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerWidgetBoxInterface_SetFocus2(void* ptr);
void QDesignerWidgetBoxInterface_SetFocus2Default(void* ptr);
void QDesignerWidgetBoxInterface_SetHidden(void* ptr, char hidden);
void QDesignerWidgetBoxInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerWidgetBoxInterface_Show(void* ptr);
void QDesignerWidgetBoxInterface_ShowDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowFullScreen(void* ptr);
void QDesignerWidgetBoxInterface_ShowFullScreenDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowMaximized(void* ptr);
void QDesignerWidgetBoxInterface_ShowMaximizedDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowMinimized(void* ptr);
void QDesignerWidgetBoxInterface_ShowMinimizedDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowNormal(void* ptr);
void QDesignerWidgetBoxInterface_ShowNormalDefault(void* ptr);
void QDesignerWidgetBoxInterface_TabletEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_Update(void* ptr);
void QDesignerWidgetBoxInterface_UpdateDefault(void* ptr);
void QDesignerWidgetBoxInterface_UpdateMicroFocus(void* ptr);
void QDesignerWidgetBoxInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerWidgetBoxInterface_WheelEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_TimerEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ChildEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ConnectNotify(void* ptr, void* sign);
void QDesignerWidgetBoxInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerWidgetBoxInterface_CustomEvent(void* ptr, void* event);
void QDesignerWidgetBoxInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DeleteLater(void* ptr);
void QDesignerWidgetBoxInterface_DeleteLaterDefault(void* ptr);
void QDesignerWidgetBoxInterface_DisconnectNotify(void* ptr, void* sign);
void QDesignerWidgetBoxInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerWidgetBoxInterface_Event(void* ptr, void* e);
char QDesignerWidgetBoxInterface_EventDefault(void* ptr, void* e);
char QDesignerWidgetBoxInterface_EventFilter(void* ptr, void* watched, void* event);
char QDesignerWidgetBoxInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerWidgetBoxInterface_MetaObject(void* ptr);
void* QDesignerWidgetBoxInterface_MetaObjectDefault(void* ptr);
int QDesignerWidgetBoxInterface_Metric(void* ptr, long long metric);
int QDesignerWidgetBoxInterface_MetricDefault(void* ptr, long long metric);
void* QDesignerWidgetBoxInterface_PaintEngine(void* ptr);
void* QDesignerWidgetBoxInterface_PaintEngineDefault(void* ptr);
void* QExtensionFactory_NewQExtensionFactory(void* parent);
void* QExtensionFactory_CreateExtension(void* ptr, void* object, char* iid, void* parent);
void* QExtensionFactory_CreateExtensionDefault(void* ptr, void* object, char* iid, void* parent);
void* QExtensionFactory_Extension(void* ptr, void* object, char* iid);
void* QExtensionFactory_ExtensionDefault(void* ptr, void* object, char* iid);
void* QExtensionFactory_ExtensionManager(void* ptr);
void QExtensionFactory_TimerEvent(void* ptr, void* event);
void QExtensionFactory_TimerEventDefault(void* ptr, void* event);
void QExtensionFactory_ChildEvent(void* ptr, void* event);
void QExtensionFactory_ChildEventDefault(void* ptr, void* event);
void QExtensionFactory_ConnectNotify(void* ptr, void* sign);
void QExtensionFactory_ConnectNotifyDefault(void* ptr, void* sign);
void QExtensionFactory_CustomEvent(void* ptr, void* event);
void QExtensionFactory_CustomEventDefault(void* ptr, void* event);
void QExtensionFactory_DeleteLater(void* ptr);
void QExtensionFactory_DeleteLaterDefault(void* ptr);
void QExtensionFactory_DisconnectNotify(void* ptr, void* sign);
void QExtensionFactory_DisconnectNotifyDefault(void* ptr, void* sign);
char QExtensionFactory_Event(void* ptr, void* e);
char QExtensionFactory_EventDefault(void* ptr, void* e);
char QExtensionFactory_EventFilter(void* ptr, void* watched, void* event);
char QExtensionFactory_EventFilterDefault(void* ptr, void* watched, void* event);
void* QExtensionFactory_MetaObject(void* ptr);
void* QExtensionFactory_MetaObjectDefault(void* ptr);
void* QExtensionManager_NewQExtensionManager(void* parent);
void* QExtensionManager_Extension(void* ptr, void* object, char* iid);
void* QExtensionManager_ExtensionDefault(void* ptr, void* object, char* iid);
void QExtensionManager_RegisterExtensions(void* ptr, void* factory, char* iid);
void QExtensionManager_RegisterExtensionsDefault(void* ptr, void* factory, char* iid);
void QExtensionManager_UnregisterExtensions(void* ptr, void* factory, char* iid);
void QExtensionManager_UnregisterExtensionsDefault(void* ptr, void* factory, char* iid);
void QExtensionManager_DestroyQExtensionManager(void* ptr);
void QExtensionManager_TimerEvent(void* ptr, void* event);
void QExtensionManager_TimerEventDefault(void* ptr, void* event);
void QExtensionManager_ChildEvent(void* ptr, void* event);
void QExtensionManager_ChildEventDefault(void* ptr, void* event);
void QExtensionManager_ConnectNotify(void* ptr, void* sign);
void QExtensionManager_ConnectNotifyDefault(void* ptr, void* sign);
void QExtensionManager_CustomEvent(void* ptr, void* event);
void QExtensionManager_CustomEventDefault(void* ptr, void* event);
void QExtensionManager_DeleteLater(void* ptr);
void QExtensionManager_DeleteLaterDefault(void* ptr);
void QExtensionManager_DisconnectNotify(void* ptr, void* sign);
void QExtensionManager_DisconnectNotifyDefault(void* ptr, void* sign);
char QExtensionManager_Event(void* ptr, void* e);
char QExtensionManager_EventDefault(void* ptr, void* e);
char QExtensionManager_EventFilter(void* ptr, void* watched, void* event);
char QExtensionManager_EventFilterDefault(void* ptr, void* watched, void* event);
void* QExtensionManager_MetaObject(void* ptr);
void* QExtensionManager_MetaObjectDefault(void* ptr);
void* QFormBuilder_NewQFormBuilder();
struct QtDesigner_PackedList QFormBuilder_CustomWidgets(void* ptr);
void QFormBuilder_AddPluginPath(void* ptr, char* pluginPath);
void QFormBuilder_ClearPluginPaths(void* ptr);
struct QtDesigner_PackedString QFormBuilder_PluginPaths(void* ptr);
void QFormBuilder_SetPluginPath(void* ptr, char* pluginPaths);
void QFormBuilder_DestroyQFormBuilder(void* ptr);
void QFormBuilder_DestroyQFormBuilderDefault(void* ptr);
void* QFormBuilder_customWidgets_atList(void* ptr, int i);
void* QFormBuilder_Load(void* ptr, void* device, void* parent);
void* QFormBuilder_LoadDefault(void* ptr, void* device, void* parent);
void QFormBuilder_Save(void* ptr, void* device, void* widget);
void QFormBuilder_SaveDefault(void* ptr, void* device, void* widget);

#ifdef __cplusplus
}
#endif

#endif