// +build !minimal

#pragma once

#ifndef GO_QTDESIGNER_H
#define GO_QTDESIGNER_H

#include <stdint.h>

#ifdef __cplusplus
int QAbstractExtensionManager_QAbstractExtensionManager_QRegisterMetaType();
int QAbstractFormBuilder_QAbstractFormBuilder_QRegisterMetaType();
int QDesignerActionEditorInterface_QDesignerActionEditorInterface_QRegisterMetaType();
int QDesignerContainerExtension_QDesignerContainerExtension_QRegisterMetaType();
int QDesignerCustomWidgetCollectionInterface_QDesignerCustomWidgetCollectionInterface_QRegisterMetaType();
int QDesignerCustomWidgetInterface_QDesignerCustomWidgetInterface_QRegisterMetaType();
int QDesignerDynamicPropertySheetExtension_QDesignerDynamicPropertySheetExtension_QRegisterMetaType();
int QDesignerFormEditorInterface_QDesignerFormEditorInterface_QRegisterMetaType();
int QDesignerFormWindowCursorInterface_QDesignerFormWindowCursorInterface_QRegisterMetaType();
int QDesignerFormWindowInterface_QDesignerFormWindowInterface_QRegisterMetaType();
int QDesignerFormWindowManagerInterface_QDesignerFormWindowManagerInterface_QRegisterMetaType();
int QDesignerMemberSheetExtension_QDesignerMemberSheetExtension_QRegisterMetaType();
int QDesignerObjectInspectorInterface_QDesignerObjectInspectorInterface_QRegisterMetaType();
int QDesignerPropertyEditorInterface_QDesignerPropertyEditorInterface_QRegisterMetaType();
int QDesignerPropertySheetExtension_QDesignerPropertySheetExtension_QRegisterMetaType();
int QDesignerResourceBrowserInterface_QDesignerResourceBrowserInterface_QRegisterMetaType();
int QDesignerTaskMenuExtension_QDesignerTaskMenuExtension_QRegisterMetaType();
int QDesignerWidgetBoxInterface_QDesignerWidgetBoxInterface_QRegisterMetaType();
int QExtensionFactory_QExtensionFactory_QRegisterMetaType();
int QExtensionManager_QExtensionManager_QRegisterMetaType();
int QFormBuilder_QFormBuilder_QRegisterMetaType();
extern "C" {
#endif

struct QtDesigner_PackedString { char* data; long long len; void* ptr; };
struct QtDesigner_PackedList { void* data; long long len; };
void* QAbstractExtensionManager_Extension(void* ptr, void* object, struct QtDesigner_PackedString iid);
void QAbstractExtensionManager_RegisterExtensions(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QAbstractExtensionManager_UnregisterExtensions(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QAbstractExtensionManager_DestroyQAbstractExtensionManager(void* ptr);
void QAbstractExtensionManager_DestroyQAbstractExtensionManagerDefault(void* ptr);
void* QAbstractFormBuilder_NewQAbstractFormBuilder();
struct QtDesigner_PackedString QAbstractFormBuilder_ErrorString(void* ptr);
void* QAbstractFormBuilder_Load(void* ptr, void* device, void* parent);
void* QAbstractFormBuilder_LoadDefault(void* ptr, void* device, void* parent);
void QAbstractFormBuilder_Save(void* ptr, void* device, void* widget);
void QAbstractFormBuilder_SaveDefault(void* ptr, void* device, void* widget);
void QAbstractFormBuilder_SetWorkingDirectory(void* ptr, void* directory);
void* QAbstractFormBuilder_WorkingDirectory(void* ptr);
void QAbstractFormBuilder_DestroyQAbstractFormBuilder(void* ptr);
void QAbstractFormBuilder_DestroyQAbstractFormBuilderDefault(void* ptr);
void* QAbstractFormBuilder___applyProperties_properties_newList(void* ptr);
void* QAbstractFormBuilder___computeProperties_newList(void* ptr);
void* QAbstractFormBuilder___propertyMap_properties_newList(void* ptr);
void* QDesignerActionEditorInterface_NewQDesignerActionEditorInterface(void* parent, long long flags);
void* QDesignerActionEditorInterface_Core(void* ptr);
void* QDesignerActionEditorInterface_CoreDefault(void* ptr);
void QDesignerActionEditorInterface_ManageAction(void* ptr, void* action);
void QDesignerActionEditorInterface_SetFormWindow(void* ptr, void* formWindow);
void QDesignerActionEditorInterface_UnmanageAction(void* ptr, void* action);
void QDesignerActionEditorInterface_DestroyQDesignerActionEditorInterface(void* ptr);
void QDesignerActionEditorInterface_DestroyQDesignerActionEditorInterfaceDefault(void* ptr);
void* QDesignerActionEditorInterface___actions_atList(void* ptr, int i);
void QDesignerActionEditorInterface___actions_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___actions_newList(void* ptr);
void* QDesignerActionEditorInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerActionEditorInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___addActions_actions_newList(void* ptr);
void* QDesignerActionEditorInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerActionEditorInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___insertActions_actions_newList(void* ptr);
void* QDesignerActionEditorInterface___children_atList(void* ptr, int i);
void QDesignerActionEditorInterface___children_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___children_newList(void* ptr);
void* QDesignerActionEditorInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerActionEditorInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerActionEditorInterface___findChildren_atList(void* ptr, int i);
void QDesignerActionEditorInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerActionEditorInterface___findChildren_newList(void* ptr);
void* QDesignerActionEditorInterface___findChildren_atList3(void* ptr, int i);
void QDesignerActionEditorInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerActionEditorInterface___findChildren_newList3(void* ptr);
void QDesignerActionEditorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_CloseDefault(void* ptr);
void QDesignerActionEditorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_EventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerActionEditorInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerActionEditorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerActionEditorInterface_HideDefault(void* ptr);
void QDesignerActionEditorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerActionEditorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerActionEditorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerActionEditorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_LowerDefault(void* ptr);
int QDesignerActionEditorInterface_MetricDefault(void* ptr, long long m);
void* QDesignerActionEditorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerActionEditorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerActionEditorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerActionEditorInterface_PaintEngineDefault(void* ptr);
void QDesignerActionEditorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_RaiseDefault(void* ptr);
void QDesignerActionEditorInterface_RepaintDefault(void* ptr);
void QDesignerActionEditorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerActionEditorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetFocus2Default(void* ptr);
void QDesignerActionEditorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerActionEditorInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerActionEditorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerActionEditorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerActionEditorInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerActionEditorInterface_ShowDefault(void* ptr);
void QDesignerActionEditorInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerActionEditorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerActionEditorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerActionEditorInterface_ShowNormalDefault(void* ptr);
void* QDesignerActionEditorInterface_SizeHintDefault(void* ptr);
void QDesignerActionEditorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_UpdateDefault(void* ptr);
void QDesignerActionEditorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerActionEditorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerActionEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerActionEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerActionEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerActionEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerActionEditorInterface_MetaObjectDefault(void* ptr);
void QDesignerActionEditorInterface_TimerEventDefault(void* ptr, void* event);
void QDesignerContainerExtension_AddWidget(void* ptr, void* page);
char QDesignerContainerExtension_CanAddWidget(void* ptr);
char QDesignerContainerExtension_CanAddWidgetDefault(void* ptr);
char QDesignerContainerExtension_CanRemove(void* ptr, int index);
char QDesignerContainerExtension_CanRemoveDefault(void* ptr, int index);
int QDesignerContainerExtension_Count(void* ptr);
int QDesignerContainerExtension_CurrentIndex(void* ptr);
void QDesignerContainerExtension_InsertWidget(void* ptr, int index, void* page);
void QDesignerContainerExtension_Remove(void* ptr, int index);
void QDesignerContainerExtension_SetCurrentIndex(void* ptr, int index);
void* QDesignerContainerExtension_Widget(void* ptr, int index);
void QDesignerContainerExtension_DestroyQDesignerContainerExtension(void* ptr);
void QDesignerContainerExtension_DestroyQDesignerContainerExtensionDefault(void* ptr);
struct QtDesigner_PackedList QDesignerCustomWidgetCollectionInterface_CustomWidgets(void* ptr);
void QDesignerCustomWidgetCollectionInterface_DestroyQDesignerCustomWidgetCollectionInterface(void* ptr);
void QDesignerCustomWidgetCollectionInterface_DestroyQDesignerCustomWidgetCollectionInterfaceDefault(void* ptr);
void* QDesignerCustomWidgetCollectionInterface___customWidgets_atList(void* ptr, int i);
void QDesignerCustomWidgetCollectionInterface___customWidgets_setList(void* ptr, void* i);
void* QDesignerCustomWidgetCollectionInterface___customWidgets_newList(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_CodeTemplate(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_CodeTemplateDefault(void* ptr);
void* QDesignerCustomWidgetInterface_CreateWidget(void* ptr, void* parent);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_DomXml(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_DomXmlDefault(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_Group(void* ptr);
void* QDesignerCustomWidgetInterface_Icon(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_IncludeFile(void* ptr);
void QDesignerCustomWidgetInterface_Initialize(void* ptr, void* formEditor);
void QDesignerCustomWidgetInterface_InitializeDefault(void* ptr, void* formEditor);
char QDesignerCustomWidgetInterface_IsContainer(void* ptr);
char QDesignerCustomWidgetInterface_IsInitialized(void* ptr);
char QDesignerCustomWidgetInterface_IsInitializedDefault(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_Name(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_ToolTip(void* ptr);
struct QtDesigner_PackedString QDesignerCustomWidgetInterface_WhatsThis(void* ptr);
void QDesignerCustomWidgetInterface_DestroyQDesignerCustomWidgetInterface(void* ptr);
void QDesignerCustomWidgetInterface_DestroyQDesignerCustomWidgetInterfaceDefault(void* ptr);
int QDesignerDynamicPropertySheetExtension_AddDynamicProperty(void* ptr, struct QtDesigner_PackedString propertyName, void* value);
char QDesignerDynamicPropertySheetExtension_CanAddDynamicProperty(void* ptr, struct QtDesigner_PackedString propertyName);
char QDesignerDynamicPropertySheetExtension_DynamicPropertiesAllowed(void* ptr);
char QDesignerDynamicPropertySheetExtension_IsDynamicProperty(void* ptr, int index);
char QDesignerDynamicPropertySheetExtension_RemoveDynamicProperty(void* ptr, int index);
void QDesignerDynamicPropertySheetExtension_DestroyQDesignerDynamicPropertySheetExtension(void* ptr);
void QDesignerDynamicPropertySheetExtension_DestroyQDesignerDynamicPropertySheetExtensionDefault(void* ptr);
void* QDesignerFormEditorInterface_NewQDesignerFormEditorInterface(void* parent);
void* QDesignerFormEditorInterface_ActionEditor(void* ptr);
void* QDesignerFormEditorInterface_ExtensionManager(void* ptr);
void* QDesignerFormEditorInterface_FormWindowManager(void* ptr);
void* QDesignerFormEditorInterface_ObjectInspector(void* ptr);
void* QDesignerFormEditorInterface_PropertyEditor(void* ptr);
void QDesignerFormEditorInterface_SetActionEditor(void* ptr, void* actionEditor);
void QDesignerFormEditorInterface_SetObjectInspector(void* ptr, void* objectInspector);
void QDesignerFormEditorInterface_SetPropertyEditor(void* ptr, void* propertyEditor);
void QDesignerFormEditorInterface_SetWidgetBox(void* ptr, void* widgetBox);
void* QDesignerFormEditorInterface_TopLevel(void* ptr);
void* QDesignerFormEditorInterface_WidgetBox(void* ptr);
void QDesignerFormEditorInterface_DestroyQDesignerFormEditorInterface(void* ptr);
void QDesignerFormEditorInterface_DestroyQDesignerFormEditorInterfaceDefault(void* ptr);
void* QDesignerFormEditorInterface___optionsPages_newList(void* ptr);
void* QDesignerFormEditorInterface___pluginInstances_atList(void* ptr, int i);
void QDesignerFormEditorInterface___pluginInstances_setList(void* ptr, void* i);
void* QDesignerFormEditorInterface___pluginInstances_newList(void* ptr);
void* QDesignerFormEditorInterface___setOptionsPages_optionsPages_newList(void* ptr);
void* QDesignerFormEditorInterface___children_atList(void* ptr, int i);
void QDesignerFormEditorInterface___children_setList(void* ptr, void* i);
void* QDesignerFormEditorInterface___children_newList(void* ptr);
void* QDesignerFormEditorInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerFormEditorInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerFormEditorInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerFormEditorInterface___findChildren_atList(void* ptr, int i);
void QDesignerFormEditorInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerFormEditorInterface___findChildren_newList(void* ptr);
void* QDesignerFormEditorInterface___findChildren_atList3(void* ptr, int i);
void QDesignerFormEditorInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerFormEditorInterface___findChildren_newList3(void* ptr);
void QDesignerFormEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormEditorInterface_EventDefault(void* ptr, void* e);
char QDesignerFormEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormEditorInterface_MetaObjectDefault(void* ptr);
void QDesignerFormEditorInterface_TimerEventDefault(void* ptr, void* event);
void* QDesignerFormWindowCursorInterface_Current(void* ptr);
void* QDesignerFormWindowCursorInterface_FormWindow(void* ptr);
char QDesignerFormWindowCursorInterface_HasSelection(void* ptr);
char QDesignerFormWindowCursorInterface_IsWidgetSelected(void* ptr, void* widget);
char QDesignerFormWindowCursorInterface_MovePosition(void* ptr, long long operation, long long mode);
int QDesignerFormWindowCursorInterface_Position(void* ptr);
void QDesignerFormWindowCursorInterface_ResetWidgetProperty(void* ptr, void* widget, struct QtDesigner_PackedString name);
void* QDesignerFormWindowCursorInterface_SelectedWidget(void* ptr, int index);
int QDesignerFormWindowCursorInterface_SelectedWidgetCount(void* ptr);
void QDesignerFormWindowCursorInterface_SetPosition(void* ptr, int position, long long mode);
void QDesignerFormWindowCursorInterface_SetProperty(void* ptr, struct QtDesigner_PackedString name, void* value);
void QDesignerFormWindowCursorInterface_SetWidgetProperty(void* ptr, void* widget, struct QtDesigner_PackedString name, void* value);
void* QDesignerFormWindowCursorInterface_Widget(void* ptr, int index);
int QDesignerFormWindowCursorInterface_WidgetCount(void* ptr);
void QDesignerFormWindowCursorInterface_DestroyQDesignerFormWindowCursorInterface(void* ptr);
void QDesignerFormWindowCursorInterface_DestroyQDesignerFormWindowCursorInterfaceDefault(void* ptr);
void QDesignerFormWindowInterface_ConnectAboutToUnmanageWidget(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectAboutToUnmanageWidget(void* ptr);
void QDesignerFormWindowInterface_AboutToUnmanageWidget(void* ptr, void* widget);
void* QDesignerFormWindowInterface_AbsoluteDir(void* ptr);
void QDesignerFormWindowInterface_ActivateResourceFilePaths(void* ptr, struct QtDesigner_PackedString paths, int errorCount, struct QtDesigner_PackedString errorMessages);
void QDesignerFormWindowInterface_ActivateResourceFilePathsDefault(void* ptr, struct QtDesigner_PackedString paths, int errorCount, struct QtDesigner_PackedString errorMessages);
void QDesignerFormWindowInterface_ConnectActivated(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectActivated(void* ptr);
void QDesignerFormWindowInterface_Activated(void* ptr, void* widget);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ActiveResourceFilePaths(void* ptr);
void QDesignerFormWindowInterface_AddResourceFile(void* ptr, struct QtDesigner_PackedString path);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Author(void* ptr);
void QDesignerFormWindowInterface_ConnectChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectChanged(void* ptr);
void QDesignerFormWindowInterface_Changed(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_CheckContents(void* ptr);
void QDesignerFormWindowInterface_ClearSelection(void* ptr, char update);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Comment(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_Contents(void* ptr);
void* QDesignerFormWindowInterface_Core(void* ptr);
void* QDesignerFormWindowInterface_CoreDefault(void* ptr);
void* QDesignerFormWindowInterface_Cursor(void* ptr);
void QDesignerFormWindowInterface_EmitSelectionChanged(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ExportMacro(void* ptr);
void QDesignerFormWindowInterface_ConnectFeatureChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectFeatureChanged(void* ptr);
void QDesignerFormWindowInterface_FeatureChanged(void* ptr, long long feature);
long long QDesignerFormWindowInterface_Features(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_FileName(void* ptr);
void QDesignerFormWindowInterface_ConnectFileNameChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectFileNameChanged(void* ptr);
void QDesignerFormWindowInterface_FileNameChanged(void* ptr, struct QtDesigner_PackedString fileName);
void* QDesignerFormWindowInterface_QDesignerFormWindowInterface_FindFormWindow(void* widget);
void* QDesignerFormWindowInterface_QDesignerFormWindowInterface_FindFormWindow2(void* object);
void* QDesignerFormWindowInterface_FormContainer(void* ptr);
void QDesignerFormWindowInterface_ConnectGeometryChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectGeometryChanged(void* ptr);
void QDesignerFormWindowInterface_GeometryChanged(void* ptr);
void* QDesignerFormWindowInterface_Grid(void* ptr);
char QDesignerFormWindowInterface_HasFeature(void* ptr, long long feature);
struct QtDesigner_PackedString QDesignerFormWindowInterface_IncludeHints(void* ptr);
char QDesignerFormWindowInterface_IsDirty(void* ptr);
char QDesignerFormWindowInterface_IsManaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_LayoutDefault(void* ptr, int margin, int spacing);
void QDesignerFormWindowInterface_LayoutFunction(void* ptr, struct QtDesigner_PackedString margin, struct QtDesigner_PackedString spacing);
void QDesignerFormWindowInterface_ConnectMainContainerChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectMainContainerChanged(void* ptr);
void QDesignerFormWindowInterface_MainContainerChanged(void* ptr, void* mainContainer);
void QDesignerFormWindowInterface_ManageWidget(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectObjectRemoved(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectObjectRemoved(void* ptr);
void QDesignerFormWindowInterface_ObjectRemoved(void* ptr, void* object);
struct QtDesigner_PackedString QDesignerFormWindowInterface_PixmapFunction(void* ptr);
void QDesignerFormWindowInterface_RemoveResourceFile(void* ptr, struct QtDesigner_PackedString path);
long long QDesignerFormWindowInterface_ResourceFileSaveMode(void* ptr);
struct QtDesigner_PackedString QDesignerFormWindowInterface_ResourceFiles(void* ptr);
void QDesignerFormWindowInterface_ConnectResourceFilesChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectResourceFilesChanged(void* ptr);
void QDesignerFormWindowInterface_ResourceFilesChanged(void* ptr);
void QDesignerFormWindowInterface_SelectWidget(void* ptr, void* widget, char sele);
void QDesignerFormWindowInterface_ConnectSelectionChanged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectSelectionChanged(void* ptr);
void QDesignerFormWindowInterface_SelectionChanged(void* ptr);
void QDesignerFormWindowInterface_SetAuthor(void* ptr, struct QtDesigner_PackedString author);
void QDesignerFormWindowInterface_SetComment(void* ptr, struct QtDesigner_PackedString comment);
char QDesignerFormWindowInterface_SetContents(void* ptr, void* device, struct QtDesigner_PackedString errorMessage);
char QDesignerFormWindowInterface_SetContents2(void* ptr, struct QtDesigner_PackedString contents);
void QDesignerFormWindowInterface_SetDirty(void* ptr, char dirty);
void QDesignerFormWindowInterface_SetExportMacro(void* ptr, struct QtDesigner_PackedString exportMacro);
void QDesignerFormWindowInterface_SetFeatures(void* ptr, long long features);
void QDesignerFormWindowInterface_SetFileName(void* ptr, struct QtDesigner_PackedString fileName);
void QDesignerFormWindowInterface_SetGrid(void* ptr, void* grid);
void QDesignerFormWindowInterface_SetIncludeHints(void* ptr, struct QtDesigner_PackedString includeHints);
void QDesignerFormWindowInterface_SetLayoutDefault(void* ptr, int margin, int spacing);
void QDesignerFormWindowInterface_SetLayoutFunction(void* ptr, struct QtDesigner_PackedString margin, struct QtDesigner_PackedString spacing);
void QDesignerFormWindowInterface_SetMainContainer(void* ptr, void* mainContainer);
void QDesignerFormWindowInterface_SetPixmapFunction(void* ptr, struct QtDesigner_PackedString pixmapFunction);
void QDesignerFormWindowInterface_SetResourceFileSaveMode(void* ptr, long long behavior);
void QDesignerFormWindowInterface_UnmanageWidget(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetManaged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectWidgetManaged(void* ptr);
void QDesignerFormWindowInterface_WidgetManaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetRemoved(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectWidgetRemoved(void* ptr);
void QDesignerFormWindowInterface_WidgetRemoved(void* ptr, void* widget);
void QDesignerFormWindowInterface_ConnectWidgetUnmanaged(void* ptr, long long t);
void QDesignerFormWindowInterface_DisconnectWidgetUnmanaged(void* ptr);
void QDesignerFormWindowInterface_WidgetUnmanaged(void* ptr, void* widget);
void QDesignerFormWindowInterface_DestroyQDesignerFormWindowInterface(void* ptr);
void QDesignerFormWindowInterface_DestroyQDesignerFormWindowInterfaceDefault(void* ptr);
void* QDesignerFormWindowInterface___simplifySelection_widgets_atList(void* ptr, int i);
void QDesignerFormWindowInterface___simplifySelection_widgets_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___simplifySelection_widgets_newList(void* ptr);
void* QDesignerFormWindowInterface___actions_atList(void* ptr, int i);
void QDesignerFormWindowInterface___actions_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___actions_newList(void* ptr);
void* QDesignerFormWindowInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerFormWindowInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___addActions_actions_newList(void* ptr);
void* QDesignerFormWindowInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerFormWindowInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___insertActions_actions_newList(void* ptr);
void* QDesignerFormWindowInterface___children_atList(void* ptr, int i);
void QDesignerFormWindowInterface___children_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___children_newList(void* ptr);
void* QDesignerFormWindowInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerFormWindowInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerFormWindowInterface___findChildren_atList(void* ptr, int i);
void QDesignerFormWindowInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerFormWindowInterface___findChildren_newList(void* ptr);
void* QDesignerFormWindowInterface___findChildren_atList3(void* ptr, int i);
void QDesignerFormWindowInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerFormWindowInterface___findChildren_newList3(void* ptr);
void QDesignerFormWindowInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_CloseDefault(void* ptr);
void QDesignerFormWindowInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DropEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_EventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerFormWindowInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerFormWindowInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerFormWindowInterface_HideDefault(void* ptr);
void QDesignerFormWindowInterface_HideEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerFormWindowInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerFormWindowInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerFormWindowInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_LowerDefault(void* ptr);
int QDesignerFormWindowInterface_MetricDefault(void* ptr, long long m);
void* QDesignerFormWindowInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerFormWindowInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerFormWindowInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerFormWindowInterface_PaintEngineDefault(void* ptr);
void QDesignerFormWindowInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_RaiseDefault(void* ptr);
void QDesignerFormWindowInterface_RepaintDefault(void* ptr);
void QDesignerFormWindowInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerFormWindowInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetFocus2Default(void* ptr);
void QDesignerFormWindowInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerFormWindowInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerFormWindowInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerFormWindowInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerFormWindowInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerFormWindowInterface_ShowDefault(void* ptr);
void QDesignerFormWindowInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ShowFullScreenDefault(void* ptr);
void QDesignerFormWindowInterface_ShowMaximizedDefault(void* ptr);
void QDesignerFormWindowInterface_ShowMinimizedDefault(void* ptr);
void QDesignerFormWindowInterface_ShowNormalDefault(void* ptr);
void* QDesignerFormWindowInterface_SizeHintDefault(void* ptr);
void QDesignerFormWindowInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_UpdateDefault(void* ptr);
void QDesignerFormWindowInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerFormWindowInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormWindowInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormWindowInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormWindowInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormWindowInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormWindowInterface_MetaObjectDefault(void* ptr);
void QDesignerFormWindowInterface_TimerEventDefault(void* ptr, void* event);
void* QDesignerFormWindowManagerInterface_Action(void* ptr, long long action);
void* QDesignerFormWindowManagerInterface_ActionGroup(void* ptr, long long actionGroup);
void* QDesignerFormWindowManagerInterface_ActiveFormWindow(void* ptr);
void QDesignerFormWindowManagerInterface_ConnectActiveFormWindowChanged(void* ptr, long long t);
void QDesignerFormWindowManagerInterface_DisconnectActiveFormWindowChanged(void* ptr);
void QDesignerFormWindowManagerInterface_ActiveFormWindowChanged(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_AddFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_CloseAllPreviews(void* ptr);
void* QDesignerFormWindowManagerInterface_Core(void* ptr);
void* QDesignerFormWindowManagerInterface_CreateFormWindow(void* ptr, void* parent, long long flags);
void* QDesignerFormWindowManagerInterface_CreatePreviewPixmap(void* ptr);
void* QDesignerFormWindowManagerInterface_FormWindow(void* ptr, int index);
void QDesignerFormWindowManagerInterface_ConnectFormWindowAdded(void* ptr, long long t);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowAdded(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowAdded(void* ptr, void* formWindow);
int QDesignerFormWindowManagerInterface_FormWindowCount(void* ptr);
void QDesignerFormWindowManagerInterface_ConnectFormWindowRemoved(void* ptr, long long t);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowRemoved(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowRemoved(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_ConnectFormWindowSettingsChanged(void* ptr, long long t);
void QDesignerFormWindowManagerInterface_DisconnectFormWindowSettingsChanged(void* ptr);
void QDesignerFormWindowManagerInterface_FormWindowSettingsChanged(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_RemoveFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_SetActiveFormWindow(void* ptr, void* formWindow);
void QDesignerFormWindowManagerInterface_ShowPluginDialog(void* ptr);
void QDesignerFormWindowManagerInterface_ShowPreview(void* ptr);
void QDesignerFormWindowManagerInterface_DestroyQDesignerFormWindowManagerInterface(void* ptr);
void QDesignerFormWindowManagerInterface_DestroyQDesignerFormWindowManagerInterfaceDefault(void* ptr);
void* QDesignerFormWindowManagerInterface___dragItems_item_list_newList(void* ptr);
void* QDesignerFormWindowManagerInterface___children_atList(void* ptr, int i);
void QDesignerFormWindowManagerInterface___children_setList(void* ptr, void* i);
void* QDesignerFormWindowManagerInterface___children_newList(void* ptr);
void* QDesignerFormWindowManagerInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerFormWindowManagerInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerFormWindowManagerInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerFormWindowManagerInterface___findChildren_atList(void* ptr, int i);
void QDesignerFormWindowManagerInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerFormWindowManagerInterface___findChildren_newList(void* ptr);
void* QDesignerFormWindowManagerInterface___findChildren_atList3(void* ptr, int i);
void QDesignerFormWindowManagerInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerFormWindowManagerInterface___findChildren_newList3(void* ptr);
void QDesignerFormWindowManagerInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerFormWindowManagerInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerFormWindowManagerInterface_DeleteLaterDefault(void* ptr);
void QDesignerFormWindowManagerInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerFormWindowManagerInterface_EventDefault(void* ptr, void* e);
char QDesignerFormWindowManagerInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerFormWindowManagerInterface_MetaObjectDefault(void* ptr);
void QDesignerFormWindowManagerInterface_TimerEventDefault(void* ptr, void* event);
int QDesignerMemberSheetExtension_Count(void* ptr);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_DeclaredInClass(void* ptr, int index);
int QDesignerMemberSheetExtension_IndexOf(void* ptr, struct QtDesigner_PackedString name);
char QDesignerMemberSheetExtension_InheritedFromWidget(void* ptr, int index);
char QDesignerMemberSheetExtension_IsSignal(void* ptr, int index);
char QDesignerMemberSheetExtension_IsSlot(void* ptr, int index);
char QDesignerMemberSheetExtension_IsVisible(void* ptr, int index);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_MemberGroup(void* ptr, int index);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_MemberName(void* ptr, int index);
struct QtDesigner_PackedList QDesignerMemberSheetExtension_ParameterNames(void* ptr, int index);
struct QtDesigner_PackedList QDesignerMemberSheetExtension_ParameterTypes(void* ptr, int index);
void QDesignerMemberSheetExtension_SetMemberGroup(void* ptr, int index, struct QtDesigner_PackedString group);
void QDesignerMemberSheetExtension_SetVisible(void* ptr, int index, char visible);
struct QtDesigner_PackedString QDesignerMemberSheetExtension_Signature(void* ptr, int index);
void QDesignerMemberSheetExtension_DestroyQDesignerMemberSheetExtension(void* ptr);
void QDesignerMemberSheetExtension_DestroyQDesignerMemberSheetExtensionDefault(void* ptr);
void* QDesignerMemberSheetExtension___parameterNames_atList(void* ptr, int i);
void QDesignerMemberSheetExtension___parameterNames_setList(void* ptr, void* i);
void* QDesignerMemberSheetExtension___parameterNames_newList(void* ptr);
void* QDesignerMemberSheetExtension___parameterTypes_atList(void* ptr, int i);
void QDesignerMemberSheetExtension___parameterTypes_setList(void* ptr, void* i);
void* QDesignerMemberSheetExtension___parameterTypes_newList(void* ptr);
void* QDesignerObjectInspectorInterface_NewQDesignerObjectInspectorInterface(void* parent, long long flags);
void* QDesignerObjectInspectorInterface_Core(void* ptr);
void* QDesignerObjectInspectorInterface_CoreDefault(void* ptr);
void QDesignerObjectInspectorInterface_SetFormWindow(void* ptr, void* formWindow);
void QDesignerObjectInspectorInterface_DestroyQDesignerObjectInspectorInterface(void* ptr);
void QDesignerObjectInspectorInterface_DestroyQDesignerObjectInspectorInterfaceDefault(void* ptr);
void* QDesignerObjectInspectorInterface___actions_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___actions_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___actions_newList(void* ptr);
void* QDesignerObjectInspectorInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___addActions_actions_newList(void* ptr);
void* QDesignerObjectInspectorInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___insertActions_actions_newList(void* ptr);
void* QDesignerObjectInspectorInterface___children_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___children_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___children_newList(void* ptr);
void* QDesignerObjectInspectorInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerObjectInspectorInterface___findChildren_atList(void* ptr, int i);
void QDesignerObjectInspectorInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___findChildren_newList(void* ptr);
void* QDesignerObjectInspectorInterface___findChildren_atList3(void* ptr, int i);
void QDesignerObjectInspectorInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerObjectInspectorInterface___findChildren_newList3(void* ptr);
void QDesignerObjectInspectorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_CloseDefault(void* ptr);
void QDesignerObjectInspectorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_EventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerObjectInspectorInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerObjectInspectorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerObjectInspectorInterface_HideDefault(void* ptr);
void QDesignerObjectInspectorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerObjectInspectorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerObjectInspectorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerObjectInspectorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_LowerDefault(void* ptr);
int QDesignerObjectInspectorInterface_MetricDefault(void* ptr, long long m);
void* QDesignerObjectInspectorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerObjectInspectorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerObjectInspectorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerObjectInspectorInterface_PaintEngineDefault(void* ptr);
void QDesignerObjectInspectorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_RaiseDefault(void* ptr);
void QDesignerObjectInspectorInterface_RepaintDefault(void* ptr);
void QDesignerObjectInspectorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerObjectInspectorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetFocus2Default(void* ptr);
void QDesignerObjectInspectorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerObjectInspectorInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerObjectInspectorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerObjectInspectorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerObjectInspectorInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerObjectInspectorInterface_ShowDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerObjectInspectorInterface_ShowNormalDefault(void* ptr);
void* QDesignerObjectInspectorInterface_SizeHintDefault(void* ptr);
void QDesignerObjectInspectorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_UpdateDefault(void* ptr);
void QDesignerObjectInspectorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerObjectInspectorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerObjectInspectorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerObjectInspectorInterface_DeleteLaterDefault(void* ptr);
void QDesignerObjectInspectorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerObjectInspectorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerObjectInspectorInterface_MetaObjectDefault(void* ptr);
void QDesignerObjectInspectorInterface_TimerEventDefault(void* ptr, void* event);
void* QDesignerPropertyEditorInterface_NewQDesignerPropertyEditorInterface(void* parent, long long flags);
void* QDesignerPropertyEditorInterface_Core(void* ptr);
void* QDesignerPropertyEditorInterface_CoreDefault(void* ptr);
struct QtDesigner_PackedString QDesignerPropertyEditorInterface_CurrentPropertyName(void* ptr);
char QDesignerPropertyEditorInterface_IsReadOnly(void* ptr);
void* QDesignerPropertyEditorInterface_Object(void* ptr);
void QDesignerPropertyEditorInterface_ConnectPropertyChanged(void* ptr, long long t);
void QDesignerPropertyEditorInterface_DisconnectPropertyChanged(void* ptr);
void QDesignerPropertyEditorInterface_PropertyChanged(void* ptr, struct QtDesigner_PackedString name, void* value);
void QDesignerPropertyEditorInterface_SetObject(void* ptr, void* object);
void QDesignerPropertyEditorInterface_SetPropertyValue(void* ptr, struct QtDesigner_PackedString name, void* value, char changed);
void QDesignerPropertyEditorInterface_SetReadOnly(void* ptr, char readOnly);
void QDesignerPropertyEditorInterface_DestroyQDesignerPropertyEditorInterface(void* ptr);
void QDesignerPropertyEditorInterface_DestroyQDesignerPropertyEditorInterfaceDefault(void* ptr);
void* QDesignerPropertyEditorInterface___actions_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___actions_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___actions_newList(void* ptr);
void* QDesignerPropertyEditorInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___addActions_actions_newList(void* ptr);
void* QDesignerPropertyEditorInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___insertActions_actions_newList(void* ptr);
void* QDesignerPropertyEditorInterface___children_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___children_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___children_newList(void* ptr);
void* QDesignerPropertyEditorInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerPropertyEditorInterface___findChildren_atList(void* ptr, int i);
void QDesignerPropertyEditorInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___findChildren_newList(void* ptr);
void* QDesignerPropertyEditorInterface___findChildren_atList3(void* ptr, int i);
void QDesignerPropertyEditorInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerPropertyEditorInterface___findChildren_newList3(void* ptr);
void QDesignerPropertyEditorInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_CloseDefault(void* ptr);
void QDesignerPropertyEditorInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DropEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_EventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerPropertyEditorInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerPropertyEditorInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerPropertyEditorInterface_HideDefault(void* ptr);
void QDesignerPropertyEditorInterface_HideEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerPropertyEditorInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerPropertyEditorInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerPropertyEditorInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_LowerDefault(void* ptr);
int QDesignerPropertyEditorInterface_MetricDefault(void* ptr, long long m);
void* QDesignerPropertyEditorInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerPropertyEditorInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerPropertyEditorInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerPropertyEditorInterface_PaintEngineDefault(void* ptr);
void QDesignerPropertyEditorInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_RaiseDefault(void* ptr);
void QDesignerPropertyEditorInterface_RepaintDefault(void* ptr);
void QDesignerPropertyEditorInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerPropertyEditorInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetFocus2Default(void* ptr);
void QDesignerPropertyEditorInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerPropertyEditorInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerPropertyEditorInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerPropertyEditorInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerPropertyEditorInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerPropertyEditorInterface_ShowDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ShowFullScreenDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowMaximizedDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowMinimizedDefault(void* ptr);
void QDesignerPropertyEditorInterface_ShowNormalDefault(void* ptr);
void* QDesignerPropertyEditorInterface_SizeHintDefault(void* ptr);
void QDesignerPropertyEditorInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_UpdateDefault(void* ptr);
void QDesignerPropertyEditorInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerPropertyEditorInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerPropertyEditorInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerPropertyEditorInterface_DeleteLaterDefault(void* ptr);
void QDesignerPropertyEditorInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerPropertyEditorInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerPropertyEditorInterface_MetaObjectDefault(void* ptr);
void QDesignerPropertyEditorInterface_TimerEventDefault(void* ptr, void* event);
int QDesignerPropertySheetExtension_Count(void* ptr);
char QDesignerPropertySheetExtension_HasReset(void* ptr, int index);
int QDesignerPropertySheetExtension_IndexOf(void* ptr, struct QtDesigner_PackedString name);
char QDesignerPropertySheetExtension_IsAttribute(void* ptr, int index);
char QDesignerPropertySheetExtension_IsChanged(void* ptr, int index);
char QDesignerPropertySheetExtension_IsEnabled(void* ptr, int index);
char QDesignerPropertySheetExtension_IsEnabledDefault(void* ptr, int index);
char QDesignerPropertySheetExtension_IsVisible(void* ptr, int index);
void* QDesignerPropertySheetExtension_Property(void* ptr, int index);
struct QtDesigner_PackedString QDesignerPropertySheetExtension_PropertyGroup(void* ptr, int index);
struct QtDesigner_PackedString QDesignerPropertySheetExtension_PropertyName(void* ptr, int index);
char QDesignerPropertySheetExtension_Reset(void* ptr, int index);
void QDesignerPropertySheetExtension_SetAttribute(void* ptr, int index, char attribute);
void QDesignerPropertySheetExtension_SetChanged(void* ptr, int index, char changed);
void QDesignerPropertySheetExtension_SetProperty(void* ptr, int index, void* value);
void QDesignerPropertySheetExtension_SetPropertyGroup(void* ptr, int index, struct QtDesigner_PackedString group);
void QDesignerPropertySheetExtension_SetVisible(void* ptr, int index, char visible);
void QDesignerPropertySheetExtension_DestroyQDesignerPropertySheetExtension(void* ptr);
void QDesignerPropertySheetExtension_DestroyQDesignerPropertySheetExtensionDefault(void* ptr);
void* QDesignerResourceBrowserInterface___actions_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___actions_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___actions_newList(void* ptr);
void* QDesignerResourceBrowserInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___addActions_actions_newList(void* ptr);
void* QDesignerResourceBrowserInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___insertActions_actions_newList(void* ptr);
void* QDesignerResourceBrowserInterface___children_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___children_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___children_newList(void* ptr);
void* QDesignerResourceBrowserInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerResourceBrowserInterface___findChildren_atList(void* ptr, int i);
void QDesignerResourceBrowserInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___findChildren_newList(void* ptr);
void* QDesignerResourceBrowserInterface___findChildren_atList3(void* ptr, int i);
void QDesignerResourceBrowserInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerResourceBrowserInterface___findChildren_newList3(void* ptr);
void QDesignerResourceBrowserInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerResourceBrowserInterface_CloseDefault(void* ptr);
void QDesignerResourceBrowserInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_DropEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerResourceBrowserInterface_EventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerResourceBrowserInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerResourceBrowserInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerResourceBrowserInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerResourceBrowserInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerResourceBrowserInterface_HideDefault(void* ptr);
void QDesignerResourceBrowserInterface_HideEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerResourceBrowserInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerResourceBrowserInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerResourceBrowserInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_LowerDefault(void* ptr);
int QDesignerResourceBrowserInterface_MetricDefault(void* ptr, long long m);
void* QDesignerResourceBrowserInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerResourceBrowserInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerResourceBrowserInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerResourceBrowserInterface_PaintEngineDefault(void* ptr);
void QDesignerResourceBrowserInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_RaiseDefault(void* ptr);
void QDesignerResourceBrowserInterface_RepaintDefault(void* ptr);
void QDesignerResourceBrowserInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerResourceBrowserInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerResourceBrowserInterface_SetFocus2Default(void* ptr);
void QDesignerResourceBrowserInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerResourceBrowserInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerResourceBrowserInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerResourceBrowserInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerResourceBrowserInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerResourceBrowserInterface_ShowDefault(void* ptr);
void QDesignerResourceBrowserInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_ShowFullScreenDefault(void* ptr);
void QDesignerResourceBrowserInterface_ShowMaximizedDefault(void* ptr);
void QDesignerResourceBrowserInterface_ShowMinimizedDefault(void* ptr);
void QDesignerResourceBrowserInterface_ShowNormalDefault(void* ptr);
void* QDesignerResourceBrowserInterface_SizeHintDefault(void* ptr);
void QDesignerResourceBrowserInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_UpdateDefault(void* ptr);
void QDesignerResourceBrowserInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerResourceBrowserInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerResourceBrowserInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerResourceBrowserInterface_DeleteLaterDefault(void* ptr);
void QDesignerResourceBrowserInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerResourceBrowserInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerResourceBrowserInterface_MetaObjectDefault(void* ptr);
void QDesignerResourceBrowserInterface_TimerEventDefault(void* ptr, void* event);
void* QDesignerTaskMenuExtension_PreferredEditAction(void* ptr);
void* QDesignerTaskMenuExtension_PreferredEditActionDefault(void* ptr);
struct QtDesigner_PackedList QDesignerTaskMenuExtension_TaskActions(void* ptr);
void QDesignerTaskMenuExtension_DestroyQDesignerTaskMenuExtension(void* ptr);
void QDesignerTaskMenuExtension_DestroyQDesignerTaskMenuExtensionDefault(void* ptr);
void* QDesignerTaskMenuExtension___taskActions_atList(void* ptr, int i);
void QDesignerTaskMenuExtension___taskActions_setList(void* ptr, void* i);
void* QDesignerTaskMenuExtension___taskActions_newList(void* ptr);
struct QtDesigner_PackedString QDesignerWidgetBoxInterface_FileName(void* ptr);
char QDesignerWidgetBoxInterface_Load(void* ptr);
char QDesignerWidgetBoxInterface_Save(void* ptr);
void QDesignerWidgetBoxInterface_SetFileName(void* ptr, struct QtDesigner_PackedString fileName);
void QDesignerWidgetBoxInterface_DestroyQDesignerWidgetBoxInterface(void* ptr);
void QDesignerWidgetBoxInterface_DestroyQDesignerWidgetBoxInterfaceDefault(void* ptr);
void* QDesignerWidgetBoxInterface___dropWidgets_item_list_newList(void* ptr);
void* QDesignerWidgetBoxInterface___actions_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___actions_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___actions_newList(void* ptr);
void* QDesignerWidgetBoxInterface___addActions_actions_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___addActions_actions_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___addActions_actions_newList(void* ptr);
void* QDesignerWidgetBoxInterface___insertActions_actions_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___insertActions_actions_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___insertActions_actions_newList(void* ptr);
void* QDesignerWidgetBoxInterface___children_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___children_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___children_newList(void* ptr);
void* QDesignerWidgetBoxInterface___dynamicPropertyNames_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___dynamicPropertyNames_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___dynamicPropertyNames_newList(void* ptr);
void* QDesignerWidgetBoxInterface___findChildren_atList(void* ptr, int i);
void QDesignerWidgetBoxInterface___findChildren_setList(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___findChildren_newList(void* ptr);
void* QDesignerWidgetBoxInterface___findChildren_atList3(void* ptr, int i);
void QDesignerWidgetBoxInterface___findChildren_setList3(void* ptr, void* i);
void* QDesignerWidgetBoxInterface___findChildren_newList3(void* ptr);
void QDesignerWidgetBoxInterface_ActionEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ChangeEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_CloseDefault(void* ptr);
void QDesignerWidgetBoxInterface_CloseEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ContextMenuEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragEnterEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragLeaveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DragMoveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DropEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_EnterEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_EventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_FocusInEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_FocusNextPrevChildDefault(void* ptr, char next);
void QDesignerWidgetBoxInterface_FocusOutEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_HasHeightForWidthDefault(void* ptr);
int QDesignerWidgetBoxInterface_HeightForWidthDefault(void* ptr, int w);
void QDesignerWidgetBoxInterface_HideDefault(void* ptr);
void QDesignerWidgetBoxInterface_HideEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_InitPainterDefault(void* ptr, void* painter);
void QDesignerWidgetBoxInterface_InputMethodEventDefault(void* ptr, void* event);
void* QDesignerWidgetBoxInterface_InputMethodQueryDefault(void* ptr, long long query);
void QDesignerWidgetBoxInterface_KeyPressEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_KeyReleaseEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_LeaveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_LowerDefault(void* ptr);
int QDesignerWidgetBoxInterface_MetricDefault(void* ptr, long long m);
void* QDesignerWidgetBoxInterface_MinimumSizeHintDefault(void* ptr);
void QDesignerWidgetBoxInterface_MouseDoubleClickEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseMoveEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MousePressEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MouseReleaseEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_MoveEventDefault(void* ptr, void* event);
char QDesignerWidgetBoxInterface_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void* QDesignerWidgetBoxInterface_PaintEngineDefault(void* ptr);
void QDesignerWidgetBoxInterface_PaintEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_RaiseDefault(void* ptr);
void QDesignerWidgetBoxInterface_RepaintDefault(void* ptr);
void QDesignerWidgetBoxInterface_ResizeEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_SetDisabledDefault(void* ptr, char disable);
void QDesignerWidgetBoxInterface_SetEnabledDefault(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetFocus2Default(void* ptr);
void QDesignerWidgetBoxInterface_SetHiddenDefault(void* ptr, char hidden);
void QDesignerWidgetBoxInterface_SetStyleSheetDefault(void* ptr, struct QtDesigner_PackedString styleSheet);
void QDesignerWidgetBoxInterface_SetVisibleDefault(void* ptr, char visible);
void QDesignerWidgetBoxInterface_SetWindowModifiedDefault(void* ptr, char vbo);
void QDesignerWidgetBoxInterface_SetWindowTitleDefault(void* ptr, struct QtDesigner_PackedString vqs);
void QDesignerWidgetBoxInterface_ShowDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ShowFullScreenDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowMaximizedDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowMinimizedDefault(void* ptr);
void QDesignerWidgetBoxInterface_ShowNormalDefault(void* ptr);
void* QDesignerWidgetBoxInterface_SizeHintDefault(void* ptr);
void QDesignerWidgetBoxInterface_TabletEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_UpdateDefault(void* ptr);
void QDesignerWidgetBoxInterface_UpdateMicroFocusDefault(void* ptr);
void QDesignerWidgetBoxInterface_WheelEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ChildEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_ConnectNotifyDefault(void* ptr, void* sign);
void QDesignerWidgetBoxInterface_CustomEventDefault(void* ptr, void* event);
void QDesignerWidgetBoxInterface_DeleteLaterDefault(void* ptr);
void QDesignerWidgetBoxInterface_DisconnectNotifyDefault(void* ptr, void* sign);
char QDesignerWidgetBoxInterface_EventFilterDefault(void* ptr, void* watched, void* event);
void* QDesignerWidgetBoxInterface_MetaObjectDefault(void* ptr);
void QDesignerWidgetBoxInterface_TimerEventDefault(void* ptr, void* event);
void* QExtensionFactory_NewQExtensionFactory(void* parent);
void* QExtensionFactory_CreateExtension(void* ptr, void* object, struct QtDesigner_PackedString iid, void* parent);
void* QExtensionFactory_CreateExtensionDefault(void* ptr, void* object, struct QtDesigner_PackedString iid, void* parent);
void* QExtensionFactory_Extension(void* ptr, void* object, struct QtDesigner_PackedString iid);
void* QExtensionFactory_ExtensionDefault(void* ptr, void* object, struct QtDesigner_PackedString iid);
void* QExtensionFactory_ExtensionManager(void* ptr);
void* QExtensionFactory___children_atList(void* ptr, int i);
void QExtensionFactory___children_setList(void* ptr, void* i);
void* QExtensionFactory___children_newList(void* ptr);
void* QExtensionFactory___dynamicPropertyNames_atList(void* ptr, int i);
void QExtensionFactory___dynamicPropertyNames_setList(void* ptr, void* i);
void* QExtensionFactory___dynamicPropertyNames_newList(void* ptr);
void* QExtensionFactory___findChildren_atList(void* ptr, int i);
void QExtensionFactory___findChildren_setList(void* ptr, void* i);
void* QExtensionFactory___findChildren_newList(void* ptr);
void* QExtensionFactory___findChildren_atList3(void* ptr, int i);
void QExtensionFactory___findChildren_setList3(void* ptr, void* i);
void* QExtensionFactory___findChildren_newList3(void* ptr);
void QExtensionFactory_ChildEvent(void* ptr, void* event);
void QExtensionFactory_ChildEventDefault(void* ptr, void* event);
void QExtensionFactory_ConnectNotify(void* ptr, void* sign);
void QExtensionFactory_ConnectNotifyDefault(void* ptr, void* sign);
void QExtensionFactory_CustomEvent(void* ptr, void* event);
void QExtensionFactory_CustomEventDefault(void* ptr, void* event);
void QExtensionFactory_DeleteLater(void* ptr);
void QExtensionFactory_DeleteLaterDefault(void* ptr);
void QExtensionFactory_DisconnectNotify(void* ptr, void* sign);
void QExtensionFactory_DisconnectNotifyDefault(void* ptr, void* sign);
char QExtensionFactory_Event(void* ptr, void* e);
char QExtensionFactory_EventDefault(void* ptr, void* e);
char QExtensionFactory_EventFilter(void* ptr, void* watched, void* event);
char QExtensionFactory_EventFilterDefault(void* ptr, void* watched, void* event);
void* QExtensionFactory_MetaObject(void* ptr);
void* QExtensionFactory_MetaObjectDefault(void* ptr);
void QExtensionFactory_TimerEvent(void* ptr, void* event);
void QExtensionFactory_TimerEventDefault(void* ptr, void* event);
void* QExtensionManager_NewQExtensionManager(void* parent);
void* QExtensionManager_Extension(void* ptr, void* object, struct QtDesigner_PackedString iid);
void* QExtensionManager_ExtensionDefault(void* ptr, void* object, struct QtDesigner_PackedString iid);
void QExtensionManager_RegisterExtensions(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QExtensionManager_RegisterExtensionsDefault(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QExtensionManager_UnregisterExtensions(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QExtensionManager_UnregisterExtensionsDefault(void* ptr, void* factory, struct QtDesigner_PackedString iid);
void QExtensionManager_DestroyQExtensionManager(void* ptr);
void QExtensionManager_DestroyQExtensionManagerDefault(void* ptr);
void* QExtensionManager___children_atList(void* ptr, int i);
void QExtensionManager___children_setList(void* ptr, void* i);
void* QExtensionManager___children_newList(void* ptr);
void* QExtensionManager___dynamicPropertyNames_atList(void* ptr, int i);
void QExtensionManager___dynamicPropertyNames_setList(void* ptr, void* i);
void* QExtensionManager___dynamicPropertyNames_newList(void* ptr);
void* QExtensionManager___findChildren_atList(void* ptr, int i);
void QExtensionManager___findChildren_setList(void* ptr, void* i);
void* QExtensionManager___findChildren_newList(void* ptr);
void* QExtensionManager___findChildren_atList3(void* ptr, int i);
void QExtensionManager___findChildren_setList3(void* ptr, void* i);
void* QExtensionManager___findChildren_newList3(void* ptr);
void QExtensionManager_ChildEvent(void* ptr, void* event);
void QExtensionManager_ChildEventDefault(void* ptr, void* event);
void QExtensionManager_ConnectNotify(void* ptr, void* sign);
void QExtensionManager_ConnectNotifyDefault(void* ptr, void* sign);
void QExtensionManager_CustomEvent(void* ptr, void* event);
void QExtensionManager_CustomEventDefault(void* ptr, void* event);
void QExtensionManager_DeleteLater(void* ptr);
void QExtensionManager_DeleteLaterDefault(void* ptr);
void QExtensionManager_DisconnectNotify(void* ptr, void* sign);
void QExtensionManager_DisconnectNotifyDefault(void* ptr, void* sign);
char QExtensionManager_Event(void* ptr, void* e);
char QExtensionManager_EventDefault(void* ptr, void* e);
char QExtensionManager_EventFilter(void* ptr, void* watched, void* event);
char QExtensionManager_EventFilterDefault(void* ptr, void* watched, void* event);
void* QExtensionManager_MetaObject(void* ptr);
void* QExtensionManager_MetaObjectDefault(void* ptr);
void QExtensionManager_TimerEvent(void* ptr, void* event);
void QExtensionManager_TimerEventDefault(void* ptr, void* event);
void* QFormBuilder_NewQFormBuilder();
void QFormBuilder_AddPluginPath(void* ptr, struct QtDesigner_PackedString pluginPath);
void QFormBuilder_ClearPluginPaths(void* ptr);
struct QtDesigner_PackedList QFormBuilder_CustomWidgets(void* ptr);
struct QtDesigner_PackedString QFormBuilder_PluginPaths(void* ptr);
void QFormBuilder_SetPluginPath(void* ptr, struct QtDesigner_PackedString pluginPaths);
void QFormBuilder_DestroyQFormBuilder(void* ptr);
void QFormBuilder_DestroyQFormBuilderDefault(void* ptr);
void* QFormBuilder___customWidgets_atList(void* ptr, int i);
void QFormBuilder___customWidgets_setList(void* ptr, void* i);
void* QFormBuilder___customWidgets_newList(void* ptr);

#ifdef __cplusplus
}
#endif

#endif